### ISSUE TITLE
Subquery does not support as 

### ISSUE THREAD

**Issue by xianshun163** [apache/shardingsphere#10092]
## Bug Report
A simple example:  
select  o.id  from   ( select  order_id as id   from t_order ) o;
In  our business code,   It is used very frequently. 
It  is  that  any suggestions,  how    to   support  it ? 

### Which version of ShardingSphere did you use?
master
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-proxy
### Reason analyze (If you can)
the  table  do not have  a field  "id"   ,  see the  exception msg.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
make a   sql  like this: 
select  o.id  from   ( select  order_id as id   from t_order ) o;

**Comment by xianshun163** [comment]
I  use the  master branches  code.

**Comment by tristaZero** [comment]
> select o.id from ( select order_id as id from t_order ) o;

@xianshun163 Hi is there any exception?

**Comment by xianshun163** [comment]
Hi,  I use the shardingsphere proxy,    and  this is the  msg ：

[ERROR] 2021-04-15 19:19:08.792 [ShardingSphere-Command-22] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
java.lang.NullPointerException: null
	at org.apache.shardingsphere.proxy.backend.response.header.query.impl.QueryHeaderBuilder.build(QueryHeaderBuilder.java:77)
	at org.apache.shardingsphere.proxy.backend.response.header.query.impl.QueryHeaderBuilder.build(QueryHeaderBuilder.java:64)
	at org.apache.shardingsphere.proxy.backend.communication.DatabaseCommunicationEngine.createQueryHeader(DatabaseCommunicationEngine.java:123)
	at org.apache.shardingsphere.proxy.backend.communication.DatabaseCommunicationEngine.createQueryHeaders(DatabaseCommunicationEngine.java:115)
	at org.apache.shardingsphere.proxy.backend.communication.DatabaseCommunicationEngine.processExecuteQuery(DatabaseCommunicationEngine.java:106)
	at org.apache.shardingsphere.proxy.backend.communication.DatabaseCommunicationEngine.execute(DatabaseCommunicationEngine.java:101)
	at org.apache.shardingsphere.proxy.backend.text.data.impl.SchemaAssignedDatabaseBackendHandler.execute(SchemaAssignedDatabaseBackendHandler.java:55)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:57)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:93)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by xianshun163** [comment]
> > select o.id from ( select order_id as id from t_order ) o;
> 
> @xianshun163 Hi is there any exception?

**Comment by tristaZero** [comment]
Hi @xianshun163 ,
Thanks for your feedback, looks valuable.

@strongduanmu , could you have a look at this  one? 
It seems we do not prepare the correct query header due to the metadata of a subquery.

**Comment by xianshun163** [comment]
@tristaZero   do you know  when  the  5.0.0-beta    will  publish？  
I  am testing  the  master branch code ，and  want to use to the production。 
In addition, is that   still have  a  wechat group ?

**Comment by tristaZero** [comment]
Hey, welcome. :) The beta release is under preparation now. WeChat ID `ss_assistant_1` will guide you to enter WeChat group.

**Comment by strongduanmu** [comment]
@xianshun163 This exception is fixed by #10582. The following is the result of the latest code execution.

```
mysql> select o.id from ( select order_id as id from t_order ) o;
+-----+
| id  |
+-----+
|   2 |
|   4 |
|   6 |
|   8 |
|  59 |
| 100 |
|   1 |
|   3 |
|   5 |
|   7 |
|  11 |
+-----+
11 rows in set (1.01 sec)
```

**Comment by xianshun163** [comment]
@strongduanmu  
it work well now。 But when  I  view the code ,  Is that a  but  here：
code:  QueryHeaderBuilder.java
line about 78, where I  sign (!!)   
sql: select o.id from ( select order_id as id from t_order ) o;
when the order_id is a primaryKey,  this code  can not  judge  Correct , because  the columnName is  change as  "id" , it can not get from the tableMetaData object.

 if (null != actualTableName && dataNodeContainedRule.isPresent()) {
            tableName = dataNodeContainedRule.get().findLogicTableByActualTable(actualTableName).orElse("");
            TableMetaData tableMetaData = metaData.getSchema().get(tableName);
        (!!)     primaryKey = null != tableMetaData && Optional.ofNullable(tableMetaData.getColumns().get(columnName.toLowerCase())).map(ColumnMetaData::isPrimaryKey).orElse(false);
        } else {
            tableName = actualTableName;
            primaryKey = false;
        }

**Comment by tristaZero** [comment]
@xianshun163 So is that a potential bug?
