### ISSUE TITLE
getting org.antlr.v4.runtime.tree.ErrorNodeImpl cannot be cast to org.antlr.v4.runtime.ParserRuleContext

### ISSUE THREAD

**Issue by arun-prasat** [apache/shardingsphere#10263]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
org.apache.shardingsphere:sharding-jdbc-spring-boot-starter:4.0.0-RC3

### Expected behavior
I am trying to execute the query in springboot via sharding sphere - **SELECT b.id FROM a AS b WHERE (b.name = 'sent') AND (lower(arrayElement(b.ep.Value, indexOf(b.ep.Key, 'id'))) = '1196' OR lower(arrayElement(b.ep.Value, indexOf(b.ep.Key, 'campaign_id'))) = '1197')**. I am getting the below issue, The query is executing fine in the clickhouse database.
java.lang.ClassCastException: org.antlr.v4.runtime.tree.ErrorNodeImpl cannot be cast to org.antlr.v4.runtime.ParserRuleContext
	at org.apache.shardingsphere.core.parse.core.extractor.impl.dml.PredicateExtractor.extractRecursiveWithParen(PredicateExtractor.java:83)
	at org.apache.shardingsphere.core.parse.core.extractor.impl.dml.PredicateExtractor.extractRecursiveWithLogicalOperation(PredicateExtractor.java:71)
	at org.apache.shardingsphere.core.parse.core.extractor.impl.dml.PredicateExtractor.extractRecursiveWithLogicalOperation(PredicateExtractor.java:74)
	at org.apache.shardingsphere.core.parse.core.extractor.impl.dml.PredicateExtractor.extractRecursiveWithLogicalOperation(PredicateExtractor.java:73)
	at org.apache.shardingsphere.core.parse.core.extractor.impl.dml.PredicateExtractor.extract(PredicateExtractor.java:65)
	at org.apache.shardingsphere.core.parse.core.extractor.impl.dml.WhereExtractor.extract(WhereExtractor.java:48)
	at org.apache.shardingsphere.core.parse.core.extractor.SQLSegmentsExtractorEngine.extract(SQLSegmentsExtractorEngine.java:47)
	at org.apache.shardingsphere.core.parse.core.SQLParseKernel.parse(SQLParseKernel.java:62)
	at org.apache.shardingsphere.core.parse.SQLParseEngine.parse0(SQLParseEngine.java:71)
	at org.apache.shardingsphere.core.parse.SQLParseEngine.parse(SQLParseEngine.java:53)
	at org.apache.shardingsphere.core.route.router.sharding.ShardingRouter.parse(ShardingRouter.java:80)
	at org.apache.shardingsphere.core.route.PreparedStatementRoutingEngine.route(PreparedStatementRoutingEngine.java:61)
	at org.apache.shardingsphere.core.PreparedQueryShardingEngine.route(PreparedQueryShardingEngine.java:59)
	at org.apache.shardingsphere.core.BaseShardingEngine.executeRoute(BaseShardingEngine.java:91)
	at org.apache.shardingsphere.core.BaseShardingEngine.shard(BaseShardingEngine.java:74)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.shard(ShardingPreparedStatement.java:222)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.executeQuery(ShardingPreparedStatement.java:107)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2292)

If i remove the brackets it is working fine - SELECT b.id FROM a AS b WHERE (b.name = 'sent') AND **lower(arrayElement(b.ep.Value, indexOf(b.ep.Key, 'id'))) = '1196' OR lower(arrayElement(b.ep.Value, indexOf(b.ep.Key, 'campaign_id'))) = '1197'**.

**Comment by avalon5666** [comment]
Pls try newest version.

**Comment by arun-prasat** [comment]
I tried with the below version which is the latest one found in maven repository but still getting the exception for the same query,(I searched for 5.0.0-alpha which is not available for sharding-jdbc-spring-boot-starter)
 implementation group: 'org.apache.shardingsphere', name: 'sharding-jdbc-spring-boot-starter', version: '4.1.1'
Exception :
line 1:53 no viable alternative at input '(lower'
line 1:53 no viable alternative at input '(lower'
ine 1:122 extraneous input 'lower' expecting {'!', '~', '+', '-', '.', '(', '{', '?', '@', POSITION, CASE, CAST, TRIM, SUBSTRING, IF, NOT, NULL, TRUE, FALSE, EXISTS, INTERVAL, DATE, TIME, TIMESTAMP, LOCALTIME, LOCALTIMESTAMP, MAX, MIN, SUM, COUNT, AVG, LOCAL, NAME, TYPE, ADA, C92, CATALOG_NAME, CHARACTER_SET_CATALOG, CHARACTER_SET_NAME, CHARACTER_SET_SCHEMA, CLASS_ORIGIN, COBOL, COLLATION_CATALOG, COLLATION_NAME, COLLATION_SCHEMA, COLUMN_NAME, COMMAND_FUNCTION, COMMITTED, CONDITION_NUMBER, CONNECTION_NAME, CONSTRAINT_CATALOG, CONSTRAINT_NAME, CONSTRAINT_SCHEMA, CURSOR_NAME, DATA, DATETIME_INTERVAL_CODE, DATETIME_INTERVAL_PRECISION, DYNAMIC_FUNCTION, FORTRAN, LENGTH, MESSAGE_LENGTH, MESSAGE_OCTET_LENGTH, MESSAGE_TEXT, MORE92, MUMPS, NULLABLE, NUMBER, PASCAL, PLI, REPEATABLE, RETURNED_LENGTH, RETURNED_OCTET_LENGTH, RETURNED_SQLSTATE, ROW_COUNT, SCALE, SCHEMA_NAME, SERIALIZABLE, SERVER_NAME, SUBCLASS_ORIGIN, TABLE_NAME, UNCOMMITTED, UNNAMED, CONVERT, CURRENT_TIMESTAMP, EXTRACT, GLOBAL, IDENTIFIER_, STRING_, NUMBER_, HEX_DIGIT_, BIT_NUM_}
line 1:145 no viable alternative at input '(arrayElement(b.ep.'


java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4456)
	at org.apache.shardingsphere.sql.parser.sql92.visitor.SQL92Visitor.visitExpr(SQL92Visitor.java:237)
	at org.apache.shardingsphere.sql.parser.sql92.visitor.SQL92Visitor.visitExpr(SQL92Visitor.java:108)
	at org.apache.shardingsphere.sql.parser.autogen.SQL92StatementParser$ExprContext.accept(SQL92StatementParser.java:4227)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.apache.shardingsphere.sql.parser.sql92.visitor.SQL92Visitor.visitExpr(SQL92Visitor.java:234)
	at org.apache.shardingsphere.sql.parser.sql92.visitor.SQL92Visitor.visitExpr(SQL92Visitor.java:108)
	at org.apache.shardingsphere.sql.parser.autogen.SQL92StatementParser$ExprContext.accept(SQL92StatementParser.java:4227)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.apache.shardingsphere.sql.parser.sql92.visitor.SQL92Visitor.visitExpr(SQL92Visitor.java:234)
	at org.apache.shardingsphere.sql.parser.sql92.visitor.SQL92Visitor.visitExpr(SQL92Visitor.java:108)
	at org.apache.shardingsphere.sql.parser.autogen.SQL92StatementParser$ExprContext.accept(SQL92StatementParser.java:4227)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.apache.shardingsphere.sql.parser.sql92.visitor.impl.SQL92DMLVisitor.visitWhereClause(SQL92DMLVisitor.java:447)
	at org.apache.shardingsphere.sql.parser.sql92.visitor.impl.SQL92DMLVisitor.visitWhereClause(SQL92DMLVisitor.java:102)
	at org.apache.shardingsphere.sql.parser.autogen.SQL92StatementParser$WhereClauseContext.accept(SQL92StatementParser.java:2562)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.apache.shardingsphere.sql.parser.sql92.visitor.impl.SQL92DMLVisitor.visitSelectClause(SQL92DMLVisitor.java:235)
	at org.apache.shardingsphere.sql.parser.sql92.visitor.impl.SQL92DMLVisitor.visitSelectClause(SQL92DMLVisitor.java:102)
	at org.apache.shardingsphere.sql.parser.autogen.SQL92StatementParser$SelectClauseContext.accept(SQL92StatementParser.java:1323)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.apache.shardingsphere.sql.parser.sql92.visitor.impl.SQL92DMLVisitor.visitUnionClause(SQL92DMLVisitor.java:217)
	at org.apache.shardingsphere.sql.parser.sql92.visitor.impl.SQL92DMLVisitor.visitUnionClause(SQL92DMLVisitor.java:102)
	at org.apache.shardingsphere.sql.parser.autogen.SQL92StatementParser$UnionClauseContext.accept(SQL92StatementParser.java:1235)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.apache.shardingsphere.sql.parser.sql92.visitor.impl.SQL92DMLVisitor.visitSelect(SQL92DMLVisitor.java:209)
	at org.apache.shardingsphere.sql.parser.sql92.visitor.impl.SQL92DMLVisitor.visitSelect(SQL92DMLVisitor.java:102)
	at org.apache.shardingsphere.sql.parser.autogen.SQL92StatementParser$SelectContext.accept(SQL92StatementParser.java:1188)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.apache.shardingsphere.sql.parser.SQLParserEngine.parse0(SQLParserEngine.java:80)
	at org.apache.shardingsphere.sql.parser.SQLParserEngine.parse(SQLParserEngine.java:61)
	at org.apache.shardingsphere.underlying.route.DataNodeRouter.createRouteContext(DataNodeRouter.java:97)
	at org.apache.shardingsphere.underlying.route.DataNodeRouter.executeRoute(DataNodeRouter.java:89)
	at org.apache.shardingsphere.underlying.route.DataNodeRouter.route(DataNodeRouter.java:76)
	at org.apache.shardingsphere.underlying.pluggble.prepare.PreparedQueryPrepareEngine.route(PreparedQueryPrepareEngine.java:54)
	at org.apache.shardingsphere.underlying.pluggble.prepare.BasePrepareEngine.executeRoute(BasePrepareEngine.java:96)
	at org.apache.shardingsphere.underlying.pluggble.prepare.BasePrepareEngine.prepare(BasePrepareEngine.java:83)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.prepare(ShardingPreparedStatement.java:183)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.executeQuery(ShardingPreparedStatement.java:116)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2292)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2050)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2012)
	at org.hibernate.loader.Loader.doQuery(Loader.java:953)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:354)
	at org.hibernate.loader.Loader.doList(Loader.java:2815)
	at org.hibernate.loader.Loader.doList(Loader.java:2797)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2629)
	at org.hibernate.loader.Loader.list(Loader.java:2624)
	at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:338)
	at org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java:2123)
	at org.hibernate.internal.AbstractSharedSessionContract.list(AbstractSharedSessionContract.java:1134)
	at org.hibernate.query.internal.NativeQueryImpl.doList(NativeQueryImpl.java:173)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1526)
	at org.hibernate.query.Query.getResultList(Query.java:165)

**Comment by tristaZero** [comment]
Hi @arun-prasat ,

>  SELECT b.id FROM a AS b WHERE (b.name = 'sent') AND (lower(arrayElement(b.ep.Value, indexOf(b.ep.Key, 'id'))) = '1196' OR lower(arrayElement(b.ep.Value, indexOf(b.ep.Key, 'campaign_id'))) = '1197')

Does this SQL cause the exception even with 5.0.0-alpha?

**Comment by tristaZero** [comment]
@strongduanmu Could you figure out our master branch can parse it well?

**Comment by strongduanmu** [comment]
Hi @arun-prasat, thank you very much for your feedback, but I am sorry to tell you that `shardingsphere` does not support clickhouse now. There are many differences between clickhouse SQL and sql92 standards.

**Comment by arun-prasat** [comment]
> Hi @arun-prasat ,
> 
> > SELECT b.id FROM a AS b WHERE (b.name = 'sent') AND (lower(arrayElement(b.ep.Value, indexOf(b.ep.Key, 'id'))) = '1196' OR lower(arrayElement(b.ep.Value, indexOf(b.ep.Key, 'campaign_id'))) = '1197')
> 
> Does this SQL cause the exception even with 5.0.0-alpha?

yes I tried with 5.0.0-alpha also with the master branch still no luck. Getting the same parser exception.

**Comment by arun-prasat** [comment]
> Hi @arun-prasat, thank you very much for your feedback, but I am sorry to tell you that `shardingsphere` does not support clickhouse now. There are many differences between clickhouse SQL and sql92 standards.

Thanks for your response. Is there any pipeline to implement for clickhouse in near future?

**Comment by strongduanmu** [comment]
@arun-prasat The community currently has no plans to support `clickhouse`. If you are interested, you are welcome to join in us to promote this work. 😊
