### ISSUE TITLE
Using asynchronous processing for routing errors

### ISSUE THREAD

**Issue by wang7621422811** [apache/shardingsphere#10279]
I'm using the JDK `CompletableFuture.supplyAsync()`,Occasionally, however, routing fails
```
It should be "shsc_wms_wgb." Now it is "shsc_wms_wsh."w_outbound_master'
Caused by: java.sql.SQLSyntaxErrorException: Table shsc_wms_wsh.w_outbound_master doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:970)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1020)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.getQueryResult(PreparedStatementExecutor.java:109)
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.access$200(PreparedStatementExecutor.java:45)
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor$2.executeSQL(PreparedStatementExecutor.java:101)
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor$2.executeSQL(PreparedStatementExecutor.java:97)
	at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteCallback.execute0(SQLExecuteCallback.java:82)
	at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteCallback.execute(SQLExecuteCallback.java:58)
	at org.apache.shardingsphere.underlying.executor.engine.ExecutorEngine.syncExecute(ExecutorEngine.java:97)
	at org.apache.shardingsphere.underlying.executor.engine.ExecutorEngine.parallelExecute(ExecutorEngine.java:93)
	at org.apache.shardingsphere.underlying.executor.engine.ExecutorEngine.execute(ExecutorEngine.java:76)
	at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteTemplate.execute(SQLExecuteTemplate.java:68)
	at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteTemplate.execute(SQLExecuteTemplate.java:51)
	at org.apache.shardingsphere.shardingjdbc.executor.AbstractStatementExecutor.executeCallback(AbstractStatementExecutor.java:129)
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.executeQuery(PreparedStatementExecutor.java:104)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.executeQuery(ShardingPreparedStatement.java:118)
	at sun.reflect.GeneratedMethodAccessor409.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:56)
	at com.sun.proxy.$Proxy317.executeQuery(Unknown Source)
	at com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor.queryTotal(PaginationInterceptor.java:199)
```
this select sql
```sql
SELECT COUNT(1) FROM ( SELECT detail.item_id, detail.item_code, detail.item_name, MASTER.company_id, MASTER.company_name, MASTER.company_code, sum(expand.base_planned_qty) AS base_planned_qty, sum(expand.base_picked_qty) AS base_picked_qty, sum(expand.base_diffied_qty) AS base_diffied_qty FROM w_outbound_master MASTER LEFT JOIN w_outbound_detail detail ON MASTER.id = detail.outbound_id AND detail.warehouse_code = MASTER.warehouse_code LEFT JOIN w_outbound_detail_expand expand ON detail.id = expand.outbound_detail_id AND detail.warehouse_code = expand.warehouse_code LEFT JOIN w_wave_detail wd ON wd.outbound_master_id = MASTER.id AND wd.warehouse_code = MASTER.warehouse_code LEFT JOIN w_wave_master wm ON wm.id = wd.wave_id AND wm.warehouse_code = wd.warehouse_code LEFT JOIN w_customers customers ON MASTER.customer_id = customers.id AND MASTER.warehouse_code = customers.warehouse_code LEFT JOIN w_customer_collection collection ON collection.id = customers.collection_id AND collection.warehouse_code = customers.warehouse_code LEFT JOIN w_item_master item ON item.id = detail.item_id AND item.warehouse_code = detail.warehouse_code LEFT JOIN w_warm_layer layer ON layer.id = item.temp_id AND layer.warehouse_code = item.warehouse_code LEFT JOIN w_zone zone ON zone.temp_id = layer.id AND zone.warehouse_code = layer.warehouse_code LEFT JOIN w_work_area area ON area.zone_id = zone.id AND area.warehouse_code = zone.warehouse_code WHERE MASTER.warehouse_code = ? AND wm.is_allocated = 1 AND area.STATUS = 1 AND area.id = ? AND detail.item_type = 'BEEF' AND collection.collection_code = ? AND MASTER.delivery_date = ? GROUP BY MASTER.company_id, detail.item_code HAVING sum(expand.base_planned_qty) > (sum(expand.base_picked_qty) + sum(expand.base_diffied_qty)) ) TOTAL 
```

**Comment by tristaZero** [comment]
Hi 
which release do you use? Are the relevant tables in this  SQL all sharding tables?

> SELECT COUNT(1) FROM ( SELECT detail.item_id, detail.item_code, detail.item_name, MASTER.company_id, MASTER.company_name, MASTER.company_code, sum(expand.base_planned_qty) AS base_planned_qty, sum(expand.base_picked_qty) AS base_picked_qty, sum(expand.base_diffied_qty) AS base_diffied_qty FROM w_outbound_master MASTER LEFT JOIN w_outbound_detail detail ON MASTER.id = detail.outbound_id AND detail.warehouse_code = MASTER.warehouse_code LEFT JOIN w_outbound_detail_expand expand ON detail.id = expand.outbound_detail_id AND detail.warehouse_code = expand.warehouse_code LEFT JOIN w_wave_detail wd ON wd.outbound_master_id = MASTER.id AND wd.warehouse_code = MASTER.warehouse_code LEFT JOIN w_wave_master wm ON wm.id = wd.wave_id AND wm.warehouse_code = wd.warehouse_code LEFT JOIN w_customers customers ON MASTER.customer_id = customers.id AND MASTER.warehouse_code = customers.warehouse_code LEFT JOIN w_customer_collection collection ON collection.id = customers.collection_id AND collection.warehouse_code = customers.warehouse_code LEFT JOIN w_item_master item ON item.id = detail.item_id AND item.warehouse_code = detail.warehouse_code LEFT JOIN w_warm_layer layer ON layer.id = item.temp_id AND layer.warehouse_code = item.warehouse_code LEFT JOIN w_zone zone ON zone.temp_id = layer.id AND zone.warehouse_code = layer.warehouse_code LEFT JOIN w_work_area area ON area.zone_id = zone.id AND area.warehouse_code = zone.warehouse_code WHERE MASTER.warehouse_code = ? AND wm.is_allocated = 1 AND area.STATUS = 1 AND area.id = ? AND detail.item_type = 'BEEF' AND collection.collection_code = ? AND MASTER.delivery_date = ? GROUP BY MASTER.company_id, detail.item_code HAVING sum(expand.base_planned_qty) > (sum(expand.base_picked_qty) + sum(expand.base_diffied_qty)) ) TOTAL

**Comment by terrymanu** [comment]
Closed because of no response anymore.
