### ISSUE TITLE
why proxy not support ddl sql in xa transaction

### ISSUE THREAD

**Issue by wenjixi** [apache/shardingsphere#10280]
```java
coordinator.database.communication.jdbc.execute.engine.jdbc.JDBCExecuteEngine

   @Override
    public void checkExecutePrerequisites(final ExecutionContext executionContext) {
        if (isExecuteDDLInXATransaction(executionContext.getSqlStatementContext().getSqlStatement())) {
            throw new TableModifyInTransactionException(getTableName(executionContext.getSqlStatementContext()));
        }
    }

 private boolean isExecuteDDLInXATransaction(final SQLStatement sqlStatement) {
        TransactionStatus transactionStatus = backendConnection.getTransactionStatus();
        return TransactionType.XA == transactionStatus.getTransactionType()
                && sqlStatement instanceof DDLStatement
                && transactionStatus.isInTransaction();
    }
```
when i use ，it throw exception

```java
coordinator.database.exception.TableModifyInTransactionException
	at coordinator.database.communication.jdbc.execute.engine.jdbc.JDBCExecuteEngine.checkExecutePrerequisites(JDBCExecuteEngine.java:79)
	at coordinator.database.communication.jdbc.JDBCDatabaseCommunicationEngine.doExecute(JDBCDatabaseCommunicationEngine.java:96)
	at coordinator.database.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:74)
	at coordinator.database.text.query.QueryBackendHandler.execute(QueryBackendHandler.java:54)
	at coordinator.provider.postgresql.command.query.text.PostgreSQLComQueryExecutor.execute(PostgreSQLComQueryExecutor.java:73)
	at coordinator.provider.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:108)
	at coordinator.provider.command.CommandExecutorTask.run(CommandExecutorTask.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
```

**Comment by menghaoranss** [comment]
`DDL` can not be rolled back, will destroy the highly consistency of XA

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 30 days, we will close it. 
If you still have related questions, please submit a new issue, thank you.
