### ISSUE TITLE
got an error `Your password does not satisfy the current policy requirements` on proxy 

### ISSUE THREAD

**Issue by taojintianxia** [apache/shardingsphere#10296]
let's suppose there are 3 centos 7 to reproduce the issue

proxy : code from github @ 2021-05-10 : 17:26
mysql : 5.7.34 MySQL Community Server

|  machine-A   | machine-B  | machine-C  | 
|  ----  | ----  | ----  |
| proxy  | mysql-A | mysql-B |

I could access MySQL-A and MySQL-B seperately from proxy by mysql client.

but when I try to start up the proxy , I got following error : 

```log
Exception in thread "main" java.lang.IllegalStateException: Error while loading privilege with java.util.concurrent.FutureTask@f73dcd6
	at org.apache.shardingsphere.authority.provider.natived.builder.StoragePrivilegeBuilder.lambda$save$3(StoragePrivilegeBuilder.java:111)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.apache.shardingsphere.authority.provider.natived.builder.StoragePrivilegeBuilder.save(StoragePrivilegeBuilder.java:107)
	at org.apache.shardingsphere.authority.provider.natived.builder.StoragePrivilegeBuilder.buildPrivilegesInStorage(StoragePrivilegeBuilder.java:94)
	at org.apache.shardingsphere.authority.provider.natived.builder.StoragePrivilegeBuilder.lambda$buildPrivilegesInStorage$1(StoragePrivilegeBuilder.java:84)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at org.apache.shardingsphere.authority.provider.natived.builder.StoragePrivilegeBuilder.buildPrivilegesInStorage(StoragePrivilegeBuilder.java:84)
	at org.apache.shardingsphere.authority.provider.natived.builder.StoragePrivilegeBuilder.build(StoragePrivilegeBuilder.java:71)
	at org.apache.shardingsphere.authority.provider.natived.NativeAuthorityProviderAlgorithm.init(NativeAuthorityProviderAlgorithm.java:42)
	at org.apache.shardingsphere.authority.rule.AuthorityRule.<init>(AuthorityRule.java:48)
	at org.apache.shardingsphere.authority.rule.builder.AuthorityRuleBuilder.build(AuthorityRuleBuilder.java:36)
	at org.apache.shardingsphere.authority.rule.builder.AuthorityRuleBuilder.build(AuthorityRuleBuilder.java:32)
	at org.apache.shardingsphere.infra.rule.builder.ShardingSphereRulesBuilder.buildGlobalRules(ShardingSphereRulesBuilder.java:100)
	at org.apache.shardingsphere.infra.context.metadata.MetaDataContextsBuilder.buildGlobalSchemaMetaData(MetaDataContextsBuilder.java:109)
	at org.apache.shardingsphere.infra.context.metadata.MetaDataContextsBuilder.build(MetaDataContextsBuilder.java:96)
	at org.apache.shardingsphere.proxy.initializer.impl.AbstractBootstrapInitializer.createMetaDataContexts(AbstractBootstrapInitializer.java:84)
	at org.apache.shardingsphere.proxy.initializer.impl.AbstractBootstrapInitializer.init(AbstractBootstrapInitializer.java:67)
	at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:48)
Caused by: java.util.concurrent.ExecutionException: org.apache.shardingsphere.infra.exception.ShardingSphereException: java.sql.SQLException: Your password does not satisfy the current policy requirements
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.apache.shardingsphere.authority.provider.natived.builder.StoragePrivilegeBuilder.lambda$save$3(StoragePrivilegeBuilder.java:109)
	... 24 more
Caused by: org.apache.shardingsphere.infra.exception.ShardingSphereException: java.sql.SQLException: Your password does not satisfy the current policy requirements
	at org.apache.shardingsphere.authority.provider.natived.builder.StoragePrivilegeBuilder.save(StoragePrivilegeBuilder.java:125)
	at org.apache.shardingsphere.authority.provider.natived.builder.StoragePrivilegeBuilder.lambda$save$2(StoragePrivilegeBuilder.java:105)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Your password does not satisfy the current policy requirements
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2449)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:98)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at org.apache.shardingsphere.authority.provider.natived.builder.dialect.MySQLPrivilegeHandler.create(MySQLPrivilegeHandler.java:73)
	at org.apache.shardingsphere.authority.provider.natived.builder.StoragePrivilegeBuilder.save(StoragePrivilegeBuilder.java:121)
	... 6 more
```

following is my server.yaml and config-sharding.yaml

server.yaml 
```yaml
rules:
  - !AUTHORITY
    users:
      - root@:root
    provider:
      type: NATIVE
```

config-sharding.yaml
```yaml
schemaName: sbtest

dataSources:
  ds_0:
    url: jdbc:mysql://111.111.111.111:3306/sbtest?serverTimezone=UTC&useSSL=false
    username: root
    password: xxxx
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 256
    minPoolSize: 256
    maintenanceIntervalMilliseconds: 30000
  ds_1:
    url: jdbc:mysql://111.111.111.112:3306/sbtest?serverTimezone=UTC&useSSL=false
    username: root
    password: xxxx
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 256
    minPoolSize: 256
    maintenanceIntervalMilliseconds: 30000

rules:
- !SHARDING
  tables:
    sbtest1:
      actualDataNodes: ds_${0..1}.sbtest1_${0..99}
      tableStrategy:
        standard:
          shardingColumn: id
          shardingAlgorithmName: table_inline_1
      keyGenerateStrategy:
        column: id
        keyGeneratorName: snowflake
    sbtest2:
      actualDataNodes: ds_${0..1}.sbtest2_${0..99}
      tableStrategy:
        standard:
          shardingColumn: id
          shardingAlgorithmName: table_inline_2
      keyGenerateStrategy:
        column: id
        keyGeneratorName: snowflake
    sbtest3:
      actualDataNodes: ds_${0..1}.sbtest3_${0..99}
      tableStrategy:
        standard:
          shardingColumn: id
          shardingAlgorithmName: table_inline_3
      keyGenerateStrategy:
        column: id
        keyGeneratorName: snowflake
    sbtest4:
      actualDataNodes: ds_${0..1}.sbtest4_${0..99}
      tableStrategy:
        standard:
          shardingColumn: id
          shardingAlgorithmName: table_inline_4
      keyGenerateStrategy:
        column: id
        keyGeneratorName: snowflake
    sbtest5:
      actualDataNodes: ds_${0..1}.sbtest5_${0..99}
      tableStrategy:
        standard:
          shardingColumn: id
          shardingAlgorithmName: table_inline_5
      keyGenerateStrategy:
        column: id
        keyGeneratorName: snowflake
    sbtest6:
      actualDataNodes: ds_${0..1}.sbtest6_${0..99}
      tableStrategy:
        standard:
          shardingColumn: id
          shardingAlgorithmName: table_inline_6
      keyGenerateStrategy:
        column: id
        keyGeneratorName: snowflake
    sbtest7:
      actualDataNodes: ds_${0..1}.sbtest7_${0..99}
      tableStrategy:
        standard:
          shardingColumn: id
          shardingAlgorithmName: table_inline_7
      keyGenerateStrategy:
        column: id
        keyGeneratorName: snowflake
    sbtest8:
      actualDataNodes: ds_${0..1}.sbtest8_${0..99}
      tableStrategy:
        standard:
          shardingColumn: id
          shardingAlgorithmName: table_inline_8
      keyGenerateStrategy:
        column: id
        keyGeneratorName: snowflake
    sbtest9:
      actualDataNodes: ds_${0..1}.sbtest9_${0..99}
      tableStrategy:
        standard:
          shardingColumn: id
          shardingAlgorithmName: table_inline_9
      keyGenerateStrategy:
        column: id
        keyGeneratorName: snowflake
    sbtest10:
      actualDataNodes: ds_${0..1}.sbtest10_${0..99}
      tableStrategy:
        standard:
          shardingColumn: id
          shardingAlgorithmName: table_inline_10
      keyGenerateStrategy:
        column: id
        keyGeneratorName: snowflake

  defaultDatabaseStrategy:
    standard:
      shardingColumn: id
      shardingAlgorithmName: database_inline

  shardingAlgorithms:
    database_inline:
      type: INLINE
      props:
        algorithm-expression: ds_${id % 2}
    table_inline_1:
      type: INLINE
      props:
        algorithm-expression: sbtest1_${id % 100}
    table_inline_2:
      type: INLINE
      props:
        algorithm-expression: sbtest2_${id % 100}
    table_inline_3:
      type: INLINE
      props:
        algorithm-expression: sbtest3_${id % 100}
    table_inline_4:
      type: INLINE
      props:
        algorithm-expression: sbtest4_${id % 100}
    table_inline_5:
      type: INLINE
      props:
        algorithm-expression: sbtest5_${id % 100}
    table_inline_6:
      type: INLINE
      props:
        algorithm-expression: sbtest6_${id % 100}
    table_inline_7:
      type: INLINE
      props:
        algorithm-expression: sbtest7_${id % 100}
    table_inline_8:
      type: INLINE
      props:
        algorithm-expression: sbtest8_${id % 100}
    table_inline_9:
      type: INLINE
      props:
        algorithm-expression: sbtest9_${id % 100}
    table_inline_10:
      type: INLINE
      props:
        algorithm-expression: sbtest10_${id % 100}
  keyGenerators:
    snowflake:
      type: SNOWFLAKE
      props:
        worker-id: 123
```

**Comment by taojintianxia** [comment]
on mysql machine, launch mysql
```mysql
>mysql uninstall plugin validate_password;
```

after that clause , the problem solved

**Comment by taojintianxia** [comment]
but when connect to proxy from another machine , execute any sql will get follwoing error : 

```log
Unknown exception: [SQL checking failed. Error message: .]
``

![image](https://user-images.githubusercontent.com/4112856/117641771-230c3200-b1b9-11eb-9c6e-12d54f2000c6.png)
