### ISSUE TITLE
sharding-jdbc(4.1.1)  UNION ALL limit Exception

### ISSUE THREAD

**Issue by zuoyedalaohu** [apache/shardingsphere#10300]
[c.x.c.o.c.d.m.c.extOper.OpCustomMapper.getCustList.debug:143] ==>  Preparing: SELECT concat(tab.cust_type,tab.cust_no) as id,tab.cust_no,tab.ub_cust_no,tab.cust_name, tab.cust_type,tab.salesman_code,tab.salesman_name,tab.salesman_dept_no, tab.salesman_dept_name,ifnull(tab.link_telphone,'') link_telphone,ifnull(tab.link_person,'') link_person,tab.if_limit, tab.limit_no,IFNULL(lmt.available_limit_amt,0) available_limit_amt,tab.belong_company, tab.state,tab.open_bank,tab.account_no from ( SELECT ci.cust_no, ci.ub_cust_no, ci.cust_name, 'JZ' AS cust_type, ci.salesman_code, ci.salesman_name, ci.salesman_dept_no, ci.salesman_dept_name, ci.link_telphone, ci.link_person, ci.if_limit, ci.limit_no, ci.belong_company, ci.mnemonic_code, ci.state, null as open_bank, null as account_no FROM op_deco_comp_info ci WHERE 1 = 1 and ci.belong_company in ( ? ) AND ci.state = ? UNION ALL SELECT si.cust_no, si.ub_cust_no, si.cust_name, 'GY' AS cust_type, si.salesman_code as salesman_code, si.salesman_name as salesman_name, si.salesman_dept_no as salesman_dept_no, si.salesman_dept_name as salesman_dept_name, si.link_telphone, si.link_person, '' as if_limit, '' as limit_no, si.belong_company, si.mnemonic_code, si.state, '' as open_bank, '' as account_no FROM op_supplier_info si WHERE 1 = 1 and si.belong_company in ( ? ) AND si.state = ? UNION ALL SELECT ti.cust_no, ti.ub_cust_no, ti.cust_name, 'YS' AS cust_type, '' as salesman_code, '' as salesman_name, '' as salesman_dept_no, '' as salesman_dept_name, ti.link_telephone as link_telphone, '' as link_person, '' as if_limit, '' as limit_no, ti.belong_company, ti.mnemonic_code, ti.state, ti.open_bank as open_bank, ti.account_no as account_no FROM op_transporter_info ti WHERE 1 = 1 and ti.belong_company in ( ? ) AND ti.state = ? UNION ALL SELECT ci.custom_no as cust_no, cr.ub_cust_no, ci.custom_name as cust_name, 'GR' AS cust_type, cr.salesman_code, cr.salesman_name, cr.salesman_dept_no, cr.salesman_dept_name, ci.telephone as link_telphone, ci.custom_name as link_person, cr.if_limit, cr.limit_no, cr.belong_company, ci.mnemonic_code, cr.state, '' as open_bank, '' as account_no FROM oper_custom_info ci,oper_custom_right cr WHERE 1 = 1 and ci.custom_no = cr.custom_no and cr.belong_company in ( ? ) AND cr.state = ? ) tab LEFT JOIN op_limit_info lmt ON tab.limit_no = lmt.limit_no where 1=1 limit ? , ? 
[c.x.c.o.c.d.m.c.extOper.OpCustomMapper.getCustList.debug:143] ==> Parameters: D00193(String), 1(String), D00193(String), 1(String), D00193(String), 1(String), D00193(String), 1(String), 0(Integer), 20(Integer)

Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at org.apache.shardingsphere.sql.parser.binder.segment.select.pagination.PaginationContext.getValue(PaginationContext.java:57)
	at org.apache.shardingsphere.sql.parser.binder.segment.select.pagination.PaginationContext.<init>(PaginationContext.java:50)
	at org.apache.shardingsphere.sql.parser.binder.segment.select.pagination.engine.LimitPaginationContextEngine.createPaginationContext(LimitPaginationContextEngine.java:38)
	at org.apache.shardingsphere.sql.parser.binder.segment.select.pagination.engine.PaginationContextEngine.createPaginationContext(PaginationContextEngine.java:48)
	at org.apache.shardingsphere.sql.parser.binder.statement.dml.SelectStatementContext.<init>(SelectStatementContext.java:100)
	at org.apache.shardingsphere.sql.parser.binder.SQLStatementContextFactory.getDMLStatementContext(SQLStatementContextFactory.java:103)
	at org.apache.shardingsphere.sql.parser.binder.SQLStatementContextFactory.newInstance(SQLStatementContextFactory.java:87)
	at org.apache.shardingsphere.underlying.route.DataNodeRouter.createRouteContext(DataNodeRouter.java:99)
	at org.apache.shardingsphere.underlying.route.DataNodeRouter.executeRoute(DataNodeRouter.java:89)
	at org.apache.shardingsphere.underlying.route.DataNodeRouter.route(DataNodeRouter.java:76)
	at org.apache.shardingsphere.underlying.pluggble.prepare.PreparedQueryPrepareEngine.route(PreparedQueryPrepareEngine.java:54)
	at org.apache.shardingsphere.underlying.pluggble.prepare.BasePrepareEngine.executeRoute(BasePrepareEngine.java:96)
	at org.apache.shardingsphere.underlying.pluggble.prepare.BasePrepareEngine.prepare(BasePrepareEngine.java:83)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.prepare(ShardingPreparedStatement.java:183)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:143)
	at sun.reflect.GeneratedMethodAccessor207.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
	at com.sun.proxy.$Proxy317.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.ReuseExecutor.doQuery(ReuseExecutor.java:60)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at sun.reflect.GeneratedMethodAccessor203.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy315.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	... 86 common frames omitted

**Comment by strongduanmu** [comment]
@zuoyedalaohu Can you provide your sharding configuration? In the sharding scenario, the union syntax is not currently supported.

**Comment by terrymanu** [comment]
Closed because of no response anymore.
