### ISSUE TITLE
openGauss Proxy alter user with SUPERUSER failed

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#10477]
### Is your feature request related to a problem?

Superuser in openGauss is `sysadmin`.
```sql
alter role some_user sysadmin;
```

`unrecognized role option "superuser"`

```
Exception in thread "main" java.lang.IllegalStateException: Error while loading privilege with java.util.concurrent.FutureTask@6b580b88
	at org.apache.shardingsphere.authority.provider.natived.builder.StoragePrivilegeBuilder.lambda$save$3(StoragePrivilegeBuilder.java:111)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.apache.shardingsphere.authority.provider.natived.builder.StoragePrivilegeBuilder.save(StoragePrivilegeBuilder.java:107)
	at org.apache.shardingsphere.authority.provider.natived.builder.StoragePrivilegeBuilder.buildPrivilegesInStorage(StoragePrivilegeBuilder.java:94)
	at org.apache.shardingsphere.authority.provider.natived.builder.StoragePrivilegeBuilder.lambda$buildPrivilegesInStorage$1(StoragePrivilegeBuilder.java:84)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.apache.shardingsphere.authority.provider.natived.builder.StoragePrivilegeBuilder.buildPrivilegesInStorage(StoragePrivilegeBuilder.java:84)
	at org.apache.shardingsphere.authority.provider.natived.builder.StoragePrivilegeBuilder.build(StoragePrivilegeBuilder.java:71)
	at org.apache.shardingsphere.authority.provider.natived.NativeAuthorityProviderAlgorithm.init(NativeAuthorityProviderAlgorithm.java:42)
	at org.apache.shardingsphere.authority.rule.AuthorityRule.<init>(AuthorityRule.java:50)
	at org.apache.shardingsphere.authority.rule.builder.AuthorityRuleBuilder.build(AuthorityRuleBuilder.java:36)
	at org.apache.shardingsphere.authority.rule.builder.AuthorityRuleBuilder.build(AuthorityRuleBuilder.java:32)
	at org.apache.shardingsphere.infra.rule.builder.ShardingSphereRulesBuilder.buildGlobalRules(ShardingSphereRulesBuilder.java:100)
	at org.apache.shardingsphere.infra.context.metadata.MetaDataContextsBuilder.buildGlobalSchemaMetaData(MetaDataContextsBuilder.java:105)
	at org.apache.shardingsphere.infra.context.metadata.MetaDataContextsBuilder.build(MetaDataContextsBuilder.java:92)
	at org.apache.shardingsphere.proxy.initializer.impl.AbstractBootstrapInitializer.createMetaDataContexts(AbstractBootstrapInitializer.java:84)
	at org.apache.shardingsphere.proxy.initializer.impl.AbstractBootstrapInitializer.init(AbstractBootstrapInitializer.java:67)
	at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:48)
Caused by: java.util.concurrent.ExecutionException: org.apache.shardingsphere.infra.exception.ShardingSphereException: org.postgresql.util.PSQLException: ERROR: unrecognized role option "superuser"
  Position: 26
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.apache.shardingsphere.authority.provider.natived.builder.StoragePrivilegeBuilder.lambda$save$3(StoragePrivilegeBuilder.java:109)
	... 24 more
Caused by: org.apache.shardingsphere.infra.exception.ShardingSphereException: org.postgresql.util.PSQLException: ERROR: unrecognized role option "superuser"
  Position: 26
	at org.apache.shardingsphere.authority.provider.natived.builder.StoragePrivilegeBuilder.save(StoragePrivilegeBuilder.java:125)
	at org.apache.shardingsphere.authority.provider.natived.builder.StoragePrivilegeBuilder.lambda$save$2(StoragePrivilegeBuilder.java:105)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: unrecognized role option "superuser"
  Position: 26
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:98)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at org.apache.shardingsphere.authority.provider.natived.builder.dialect.PostgreSQLPrivilegeHandler.grantAll(PostgreSQLPrivilegeHandler.java:88)
	at org.apache.shardingsphere.authority.provider.natived.builder.StoragePrivilegeBuilder.save(StoragePrivilegeBuilder.java:122)
	... 7 more
```

**Comment by TeslaCN** [comment]
Close due to `Native` authority is already deprecated. #13911
