### ISSUE TITLE
java.lang.String cannot be cast to org.apache.shardingsphere.infra.yaml.config.YamlRuleConfiguration

### ISSUE THREAD

**Issue by feiquan666** [apache/shardingsphere#10472]
### config-sharding.yml
schemaName: db
dataSourceCommon:
  username: root
  password: pass
  connectionTimeoutMilliseconds: 30000
  idleTimeoutMilliseconds: 60000
  maxLifetimeMilliseconds: 1800000
  maxPoolSize: 50
  minPoolSize: 1
  maintenanceIntervalMilliseconds: 30000
dataSources:
  db0: 
    url:  .........................
  db1: 
    url:  jdbc:mysql://..............
  db2: 
    url:  jdbc:mysql://............
rules: 
    - !SHARDING
    tables: 
      pr_user: 
        actualDataNodes: db${0..2}.pr_user${0..1}
        databaseStrategy: 
          standard: 
            shardingColumn: country_id
            shardingAlgorithName: databaseInline
        tableStartege: 
          standard: 
            shardingColumn: id
            shardingAlgorithmName: userTableInline
      pr_user_detail: 
        actualDataNodes: db${0..2}.pr_user_detail${0..1}
        # 分库策略
        databaseStrategy: 
          standard: 
            shardingColumn: country_id
            shardingAlgorithName: databaseInline
        tableStartege:
          standard: 
            shardingColumn: id
            shardingAlgorithmName: userDetailtableInline
      pr_country:
        actualDataNodes: db${0..2}.pr_country
    broadcastTables: 
      - pr_country
    bindingTables: 
      - pr_user,pr_user_detail
    shardingAlgorithms: 
      databaseInline: 
        type: INLINE
        props: 
          algorithm-expression: db${country_id % 3}
      userTableInline: 
        type: INLINE
        props:
          algorithm-expression: pr_user${user_id % 2}
      userDetailtableInline:
        type: INLINE
        props: 
          algorithm-expression: pr_user_detail${user_id % 2}

### server.yml
authentication:
  users:
    root:
      password: root
    sharding:
      password: pass
      authorizedSchemas: db

props:
  max-connections-size-per-query: 1
  acceptor-size: 16  
  executor-size: 16  
  proxy-transaction-type: LOCAL
  proxy-opentracing-enabled: false
  proxy-hint-enabled: false
  query-with-cipher-column: true
  sql-show: false
  check-table-metadata-enabled: false
使用 start.bat 启动 报错如下：

Starting the ShardingSphere-Proxy ...
Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to org.apache.shardingsphere.infra.yaml.config.YamlRuleConfiguration
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.Iterator.forEachRemaining(Unknown Source)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.collect(Unknown Source)
        at org.apache.shardingsphere.infra.yaml.swapper.YamlRuleConfigurationSwapperEngine.swapToRuleConfigurations(YamlRuleConfigurationSwapperEngine.java:66)
        at org.apache.shardingsphere.proxy.config.yaml.swapper.YamlProxyConfigurationSwapper.lambda$getRuleConfigurations$0(YamlProxyConfigurationSwapper.java:59)
        at java.util.stream.Collectors.lambda$toMap$58(Unknown Source)
        at java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)
        at java.util.Iterator.forEachRemaining(Unknown Source)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.collect(Unknown Source)
        at org.apache.shardingsphere.proxy.config.yaml.swapper.YamlProxyConfigurationSwapper.getRuleConfigurations(YamlProxyConfigurationSwapper.java:58)
        at org.apache.shardingsphere.proxy.config.yaml.swapper.YamlProxyConfigurationSwapper.swap(YamlProxyConfigurationSwapper.java:50)
        at org.apache.shardingsphere.proxy.initializer.impl.StandardBootstrapInitializer.getProxyConfiguration(StandardBootstrapInitializer.java:33)
        at org.apache.shardingsphere.proxy.initializer.impl.AbstractBootstrapInitializer.init(AbstractBootstrapInitializer.java:62)
        at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:48)
请按任意键继续. . .

**Comment by menghaoranss** [comment]
Which version of ShardingSphere did you use?

**Comment by feiquan666** [comment]
5.0

**Comment by CanonNr** [comment]
`java.lang.String cannot be cast to org.apache.shardingsphere.infra.yaml.config.YamlRuleConfiguration`
遇到了相同的问题,我使用的是官方的sharding-proxy docker镜像部署

**Comment by menghaoranss** [comment]
could you please provide your YAML configuration file?

**Comment by feiquan666** [comment]
> could you please provide your YAML configuration file?

我不是已经提供了配置文件么？
程序内我使用的是Java API 进行配置的

**Comment by feiquan666** [comment]
> could you please provide your YAML configuration file?

我已经向您的 邮箱 menghaoranss@gmail.com 发送了邮件

**Comment by CanonNr** [comment]
折腾好久后已经没有问题了，确实是YAML问题，但是之前有问题得YAML没有保存

**Comment by feiquan666** [comment]
不要使用 5.x，太多坑了

**Comment by wolegequya** [comment]
I also met the same problem. How can I solve it

**Comment by wolegequya** [comment]
> 不要使用 5.x，太多坑了

求教，你的问题解决了么？

**Comment by zhifengcloud** [comment]
请问后面怎么解决的,我的5.0也是遇到这个问题

**Comment by terrymanu** [comment]
English only
