### ISSUE TITLE
npe occurs when sharding-raw-jdbc-example is in SHARDING_READWRITE_SPLITTING type

### ISSUE THREAD

**Issue by totalo** [apache/shardingsphere#10583]
### Which version of ShardingSphere did you use?

5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior

Complete the example as normal

### Actual behavior

npe
```
Exception in thread "main" java.lang.NullPointerException
	at org.apache.shardingsphere.driver.jdbc.adapter.executor.ForceExecuteTemplate.execute(ForceExecuteTemplate.java:42)
	at org.apache.shardingsphere.driver.jdbc.adapter.AbstractResultSetAdapter.close(AbstractResultSetAdapter.java:82)
	at org.apache.shardingsphere.example.core.jdbc.repository.OrderRepositoryImpl.getOrders(OrderRepositoryImpl.java:114)
	at org.apache.shardingsphere.example.core.jdbc.repository.OrderRepositoryImpl.selectAll(OrderRepositoryImpl.java:98)
	at org.apache.shardingsphere.example.core.jdbc.service.OrderServiceImpl.printData(OrderServiceImpl.java:148)
	at org.apache.shardingsphere.example.core.jdbc.service.OrderServiceImpl.processSuccess(OrderServiceImpl.java:95)
	at org.apache.shardingsphere.example.core.api.ExampleExecuteTemplate.run(ExampleExecuteTemplate.java:29)
	at org.apache.shardingsphere.example.sharding.raw.jdbc.JavaConfigurationExampleMain.main(JavaConfigurationExampleMain.java:42)
```

### Reason analyze (If you can)
resultSet is null , When he shuts down, an exception occurs

**Comment by RaigorJiang** [comment]
![image](https://user-images.githubusercontent.com/5668787/120925501-80899500-c70b-11eb-8fdd-c778e3e5d07e.png)

I tested this scenario and there was no exception. 
If any table does not exist in databases, it may cause the problem described by @totalo

**Comment by totalo** [comment]
Sorry, this is my configuration problem
