### ISSUE TITLE
loadColumnMetaData null pointer with geometry column

### ISSUE THREAD

**Issue by AyaUchida** [apache/shardingsphere#10716]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-RC1 
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
tomcat startup with no exception
### Actual behavior
`Caused by: java.lang.NullPointerException
		at org.apache.shardingsphere.infra.metadata.schema.builder.loader.dialect.MySQLTableMetaDataLoader.loadColumnMetaData(MySQLTableMetaDataLoader.java:95)
		at org.apache.shardingsphere.infra.metadata.schema.builder.loader.dialect.MySQLTableMetaDataLoader.loadColumnMetaDataMap(MySQLTableMetaDataLoader.java:77)
		at org.apache.shardingsphere.infra.metadata.schema.builder.loader.dialect.MySQLTableMetaDataLoader.loadTableMetaDataMap(MySQLTableMetaDataLoader.java:59)
		at org.apache.shardingsphere.infra.metadata.schema.builder.loader.dialect.MySQLTableMetaDataLoader.load(MySQLTableMetaDataLoader.java:54)
		at org.apache.shardingsphere.infra.metadata.schema.builder.SchemaBuilder.lambda$appendDialectRemainTables$1(SchemaBuilder.java:116)
		at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
		at java.util.concurrent.FutureTask.run(FutureTask.java)
		... 3 more`
### Reason analyze (If you can)
I got a mysql table with column type geometry。The method 'loadColumnMetaData' in MySQLTableMetaDataLoader will
get null when 'dataTypeMap.get(dataType)' executed at MySQLTableMetaDataLoader  line 95.
Then I checked how dataTypeMap created,I found databaseMetaData.getTypeInfo() in org.apache.shardingsphere.infra.metadata.schema.builder.loader.DataTypeLoader can not get geomtry type.

My environment is JDK1.8.0_144 and mysql-connector-java-8.0.15

**Comment by zjcnb** [comment]
Can you provide the configuration information?

I think you have a problem with the configuration information

such as

> spring:
  shardingsphere:
    props:
      sql-show: true
    datasource:
      common:
        driver-class-name: com.mysql.jdbc.Driver
      names: ds0
      ds0:
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
        type: com.alibaba.druid.pool.DruidDataSource

**Comment by AyaUchida** [comment]
@zjcnb 
Cause it's a old project，I used the spring namespace configuration like this

`

    <readwrite-splitting:load-balance-algorithm id="loadbalanceAlgorith" type="RANDOM"/>
    <readwrite-splitting:rule id="masterslaveRule">
        <readwrite-splitting:data-source-rule id="msds" write-data-source-name="master-dataSource"
                                        read-data-source-names="slave-dataSource"
                                        load-balance-algorithm-ref="loadbalanceAlgorith"/>
    </readwrite-splitting:rule>

    <sharding:key-generate-algorithm id="uuidAlgorithm" type="UUID"/>
    <sharding:key-generate-strategy id="uuidKeyGenerator" column="id" algorithm-ref="uuidAlgorithm"/>
    <sharding:sharding-algorithm id="jyTableAlgorithm" type="INLINE">
        <props>
            <prop key="algorithm-expression">jy_year_$->{year_id}</prop>
        </props>
    </sharding:sharding-algorithm>
    <sharding:standard-strategy id="jyTableStrategy" sharding-column="year_id" algorithm-ref="jyTableAlgorithm"/>
    <sharding:rule id="shardingRule">
        <sharding:table-rules>
            <sharding:table-rule logic-table="jiaoyu"
                                 actual-data-nodes="msds.jy_year_$->{2015..2022}"
                                 table-strategy-ref="jyTableStrategy" key-generate-strategy-ref="uuidKeyGenerator"/>
        </sharding:table-rules>
    </sharding:rule>
    <shardingsphere:data-source id="shardingDataSource" data-source-names="master-dataSource,slave-dataSource"
                                rule-refs="masterslaveRule,shardingRule">
        <props>
            <prop key="max-connections-size-per-query">16</prop>
        </props>
    </shardingsphere:data-source>
`

The table with data type Point is not a sharding table.

Because I can't solve this problem, so I changed to use 4.1.1 instead of 5.0.0-RC1. For now it works well.

**Comment by terrymanu** [comment]
It looks like meta data loading problem with rare data type.
Does anyone interest this issue?

**Comment by zjcnb** [comment]
It's same to https://github.com/apache/shardingsphere/issues/12548, please assign me. I will refactor here
