### ISSUE TITLE
sqlite-jdbc throw SQLFeatureNotSupportedException

### ISSUE THREAD

**Issue by ko12ko** [apache/shardingsphere#10751]
**Libs:**
org.xerial:sqlite-jdbc:3.34.0
org.apache.shardingsphere:sharding-jdbc-spring-boot-starter:4.1.1

**Logs:**
```
Caused by: java.sql.SQLFeatureNotSupportedException: null
	at org.sqlite.jdbc4.JDBC4DatabaseMetaData.supportsStoredFunctionsUsingCallSyntax(JDBC4DatabaseMetaData.java:36) ~[sqlite-jdbc-3.34.0.jar:na]
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.datasource.metadata.CachedDatabaseMetaData.<init>(CachedDatabaseMetaData.java:429) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.context.ShardingRuntimeContext.createCachedDatabaseMetaData(ShardingRuntimeContext.java:57) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.context.ShardingRuntimeContext.<init>(ShardingRuntimeContext.java:50) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.datasource.ShardingDataSource.<init>(ShardingDataSource.java:54) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.api.ShardingDataSourceFactory.createDataSource(ShardingDataSourceFactory.java:48) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration.shardingDataSource(SpringBootConfiguration.java:103) ~[sharding-jdbc-spring-boot-starter-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration$$EnhancerBySpringCGLIB$$59a4aba.CGLIB$shardingDataSource$1(<generated>) ~[sharding-jdbc-spring-boot-starter-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration$$EnhancerBySpringCGLIB$$59a4aba$$FastClassBySpringCGLIB$$910e0584.invoke(<generated>) ~[sharding-jdbc-spring-boot-starter-4.1.1.jar:4.1.1]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.7.jar:5.3.7]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.7.jar:5.3.7]
	at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration$$EnhancerBySpringCGLIB$$59a4aba.shardingDataSource(<generated>) ~[sharding-jdbc-spring-boot-starter-4.1.1.jar:4.1.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_202]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.7.jar:5.3.7]
	... 75 common frames omitted
```

**Expected:**
No SQLFeatureNotSupportedException.

**Comment by terrymanu** [comment]
It looks like cannot support sqllite.
Does anyone interest this issue?

**Comment by terrymanu** [comment]
Nobody interest this issue for long time, I just close it.
