### ISSUE TITLE
一些复杂的sql报错

### ISSUE THREAD

**Issue by shenyao2333** [apache/shardingsphere#10934]
#### 想从一个老项目里针对多数据源进行升级，在我使用了sharding-jdbc后，发现以前运行正常的sql现在报错了，简单的sql到是正常，像表关联表比较多的就直接不行了，它会报Can not find owner from table.错误，或者 Cause: java.lang.IndexOutOfBoundsException: Index: 0] with root cause错误，

这只是随便点两下发现的错误，我猜后面还有一些不支持的sql，所以就只能放弃这次升级了。

### 希望大佬能尽快修复一下这些bug，可以让老项目直接迁移使用

我粘贴一个报错的sql
SELECT * FROM
	( SELECT strength, game_id, member_id, crated_time FROM club_sugar_game GROUP BY member_id, game_id ORDER BY strength DESC ) game
	LEFT JOIN member m ON game.member_id = m.id 
GROUP BY
	game.member_id 
ORDER BY
	strength DESC,
	game_id ASC 

刚才还发现了这个错误
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
at org.apache.shardingsphere.sql.parser.binder.segment.select.pagination.PaginationContext.getValue(PaginationContext.java:57)
at org.apache.shardingsphere.sql.parser.binder.segment.select.pagination.PaginationContext.<init>(PaginationContext.java:51)
at org.apache.shardingsphere.sql.parser.binder.segment.select.pagination.engine.LimitPaginationContextEngine.createPaginationContext

**Comment by strongduanmu** [comment]
@shenyao2333 For english only, other language will not be accept.
