### ISSUE TITLE
Error when not select *, but select part of all fields

### ISSUE THREAD

**Issue by xueshiji** [apache/shardingsphere#11029]
### Which version of ShardingSphere did you use?
Both 5.0.0-alpha and 5.0.0-beta have this problem.

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
Successful execution of sql.
### Actual behavior
Unsuccessful execution of sql
### Reason analyze (If you can)
N/A
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Use Oracle 11g,MybatisPlus.
Run the TestdemoApplicationTests will get java.sql.SQLException: getValidColumnIndex.
If you don't use sharding, you will get the correct result.
### Example codes for reproduce this issue (such as a github link).
<https://github.com/xueshiji/testdemo.git>

**Comment by avalon5666** [comment]
Can you set sql.show=true, and provider the configuration and full exception log?

**Comment by xueshiji** [comment]
@avalon5666 Please look at this <https://github.com/xueshiji/testdemo>

**Comment by avalon5666** [comment]
I don't have an oracle environment now, can you run and provider more information.

**Comment by xueshiji** [comment]
@avalon5666  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.5.RELEASE)

2021-06-28 22:21:23.605  INFO 2140 --- [           main] c.e.testdemo.TestdemoApplicationTests    : Starting TestdemoApplicationTests on DESKTOP-L6C28LP with PID 2140 (started by xuehsiji in C:\Users\xuehsiji\Desktop\IdeaProjects\testdemo)
2021-06-28 22:21:23.605  INFO 2140 --- [           main] c.e.testdemo.TestdemoApplicationTests    : No active profile set, falling back to default profiles: default
2021-06-28 22:21:25.622  INFO 2140 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2021-06-28 22:21:25.637  WARN 2140 --- [           main] com.zaxxer.hikari.util.DriverDataSource  : Registered driver with driverClassName=oracle.jdbc.driver.OracleDriver was not found, trying direct instantiation.
2021-06-28 22:21:26.637  INFO 2140 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
 _ _   |_  _ _|_. ___ _ |    _ 
| | |\/|_)(_| | |_\  |_)||_|_\ 
     /               |         
                        3.4.3 
2021-06-28 22:21:34.840  INFO 2140 --- [           main] c.e.testdemo.TestdemoApplicationTests    : Started TestdemoApplicationTests in 11.844 seconds (JVM running for 14.246)
2021-06-28 22:21:37.982  INFO 2140 --- [           main] ShardingSphere-SQL                       : Logic SQL: SELECT COUNT(*) FROM TEST_TABLE WHERE (valuee = ? AND code = ?)
2021-06-28 22:21:37.982  INFO 2140 --- [           main] ShardingSphere-SQL                       : SQLStatement: OracleSelectStatement(lock=Optional.empty)
2021-06-28 22:21:37.982  INFO 2140 --- [           main] ShardingSphere-SQL                       : Actual SQL: ds0 ::: SELECT COUNT(*) FROM TEST_TABLE_4419 WHERE (valuee = ? AND code = ?) ::: [666, 4419]
2021-06-28 22:21:38.231  INFO 2140 --- [           main] ShardingSphere-SQL                       : Logic SQL: SELECT * FROM ( SELECT TMP.*, ROWNUM ROW_ID FROM ( SELECT  
gid,fieldd
  FROM TEST_TABLE 
 
 WHERE (valuee = ? AND code = ?) ) TMP WHERE ROWNUM <=?) WHERE ROW_ID > ?
2021-06-28 22:21:38.231  INFO 2140 --- [           main] ShardingSphere-SQL                       : SQLStatement: OracleSelectStatement(lock=Optional.empty)
2021-06-28 22:21:38.231  INFO 2140 --- [           main] ShardingSphere-SQL                       : Actual SQL: ds0 ::: SELECT * FROM ( SELECT TMP.*, ROWNUM ROW_ID FROM ( SELECT  
gid,fieldd
  FROM TEST_TABLE_4419 
 
 WHERE (valuee = ? AND code = ?) ) TMP WHERE ROWNUM <=?) WHERE ROW_ID > ? ::: [666, 4419, 2, 0]

org.springframework.jdbc.InvalidResultSetAccessException: 
### Error querying database.  Cause: java.sql.SQLException: 无效的列索引: getValidColumnIndex
### The error may exist in com/example/testdemo/testEntityMapper.java (best guess)
### The error may involve com.example.testdemo.testEntityMapper.selectPage
### The error occurred while handling results
### SQL: SELECT * FROM ( SELECT TMP.*, ROWNUM ROW_ID FROM ( SELECT   gid,fieldd   FROM TEST_TABLE     WHERE (valuee = ? AND code = ?) ) TMP WHERE ROWNUM <=?) WHERE ROW_ID > ?
### Cause: java.sql.SQLException: 无效的列索引: getValidColumnIndex
; invalid ResultSet access for SQL []; nested exception is java.sql.SQLException: 无效的列索引: getValidColumnIndex

	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:238)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy163.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForIPage(MybatisMapperMethod.java:121)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:85)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy171.selectPage(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy172.selectPage(Unknown Source)
	at com.example.testdemo.TestdemoApplicationTests.contextLoads(TestdemoApplicationTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:532)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:108)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.sql.SQLException: 无效的列索引: getValidColumnIndex
	at oracle.jdbc.driver.OracleResultSetMetaData.getValidColumnIndex(OracleResultSetMetaData.java:114)
	at oracle.jdbc.driver.OracleResultSetMetaData.getColumnName(OracleResultSetMetaData.java:328)
	at oracle.jdbc.driver.OracleResultSetMetaData.getColumnLabel(OracleResultSetMetaData.java:310)
	at org.apache.shardingsphere.driver.jdbc.core.resultset.ShardingSphereResultSetMetaData.getColumnLabel(ShardingSphereResultSetMetaData.java:97)
	at org.apache.ibatis.executor.resultset.ResultSetWrapper.<init>(ResultSetWrapper.java:60)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getFirstResultSet(DefaultResultSetHandler.java:251)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:188)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:65)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:64)
	at com.sun.proxy.$Proxy184.query(Unknown Source)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:81)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at com.sun.proxy.$Proxy183.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:151)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:145)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
	... 58 more

2021-06-28 22:21:38.512  INFO 2140 --- [       Thread-7] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2021-06-28 22:21:38.590  INFO 2140 --- [       Thread-7] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.

**Comment by avalon5666** [comment]
Duplicate with #8841

**Comment by xueshiji** [comment]
> Duplicate with #8841

@avalon5666 ， I don't think so, Issue #8841 is an unexpected result, but my issue is an execution exception.The only thing in common is that they are both 
paged queries

**Comment by avalon5666** [comment]
we investigate th root cause, I think they are relevant.

**Comment by xueshiji** [comment]
@strongduanmu ,Could you like to look at this issue and issue #8841? Do you think they are the same problem?

**Comment by avalon5666** [comment]
Fixed by #10833

**Comment by avalon5666** [comment]
> @strongduanmu ,Could you like to look at this issue and issue #8841? Do you think they are the same problem?

@xueshiji You are right, duplication with #10832
