### ISSUE TITLE
Springboot service can not startup when the datatype of column(mysql) is json

### ISSUE THREAD

**Issue by chenqin091017** [apache/shardingsphere#11024]
### Which version of ShardingSphere did you use?

shardingsphere-jdbc-core 5.0.0-beta

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Expected behavior

springboot service can startup

### Actual behavior

springboot service can not startup

### Reason analyze (If you can)
When service start ,ShardingSphere will load some informations from mysql.
Because the datatype of column is json and dataTypeMap don't have this key，throw NullPointerException.
Could I let ShardingSphere not load the information of other tables(not using ShardingSphere)?
Thanks.

```java
Caused by: java.lang.NullPointerException: null
	at org.apache.shardingsphere.infra.metadata.schema.builder.loader.dialect.MySQLTableMetaDataLoader.loadColumnMetaData(MySQLTableMetaDataLoader.java:95)
	at org.apache.shardingsphere.infra.metadata.schema.builder.loader.dialect.MySQLTableMetaDataLoader.loadColumnMetaDataMap(MySQLTableMetaDataLoader.java:77)
	at org.apache.shardingsphere.infra.metadata.schema.builder.loader.dialect.MySQLTableMetaDataLoader.loadTableMetaDataMap(MySQLTableMetaDataLoader.java:59)
	at org.apache.shardingsphere.infra.metadata.schema.builder.loader.dialect.MySQLTableMetaDataLoader.load(MySQLTableMetaDataLoader.java:54)
	at org.apache.shardingsphere.infra.metadata.schema.builder.SchemaBuilder.lambda$appendDialectRemainTables$1(SchemaBuilder.java:116)
```
<img width="1099" alt="QQ20210626-172126@2x" src="https://user-images.githubusercontent.com/17311435/123508753-d49cef00-d6a3-11eb-90c2-a3bc9768c9cf.png">

**Comment by avalon5666** [comment]
set check-table-metadata-enabled=false

**Comment by chenqin091017** [comment]
> set check-table-metadata-enabled=false
It's working.Thanks!
