### ISSUE TITLE
sharding-jdbc 4.1.1：[org.hibernate.engine.jdbc.spi.SqlExceptionHelper]Unknown column 'NOW' in 'where clause'

### ISSUE THREAD

**Issue by trycache0828** [apache/shardingsphere#11041]
## Bug Report

line 1:349 no viable alternative at input 'YEAR(NOW)'.

[org.hibernate.engine.jdbc.spi.SqlExceptionHelper]SQL Error: 1054, SQLState: 42S22

[org.hibernate.engine.jdbc.spi.SqlExceptionHelper]Unknown column 'NOW' in 'where clause'

The condition ‘AND YEAR(tn.create_date) = YEAR(NOW())’ resolved to  ‘AND YEAR(tn.create_date) = YEAR(NOW)’

### Which version of ShardingSphere did you use?

4.1.1

    <dependency>
        <groupId>org.apache.shardingsphere</groupId>
        <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
        <version>4.1.1</version>
    </dependency>

    <dependency>
        <groupId>org.apache.shardingsphere</groupId>
        <artifactId>sharding-jdbc-core</artifactId>
        <version>4.1.1</version>
    </dependency>

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

## Usage scenarios

Spring 3.x + Hibernate 4.x + Sharding-JDBC 4.1.1

### Expected behavior

Missing parentheses for function now().The MySQL function now() is resolved to the column name now.

java.sql.SQLSyntaxErrorException: Unknown column 'NOW' in 'where clause'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:955)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1005)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.getQueryResult(PreparedStatementExecutor.java:109)
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.access$200(PreparedStatementExecutor.java:45)
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor$2.executeSQL(PreparedStatementExecutor.java:101)
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor$2.executeSQL(PreparedStatementExecutor.java:97)
	at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteCallback.execute0(SQLExecuteCallback.java:82)
	at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteCallback.execute(SQLExecuteCallback.java:58)
	at org.apache.shardingsphere.underlying.executor.engine.ExecutorEngine.syncExecute(ExecutorEngine.java:97)
	at org.apache.shardingsphere.underlying.executor.engine.ExecutorEngine.serialExecute(ExecutorEngine.java:82)
	at org.apache.shardingsphere.underlying.executor.engine.ExecutorEngine.execute(ExecutorEngine.java:76)
	at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteTemplate.execute(SQLExecuteTemplate.java:68)
	at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteTemplate.execute(SQLExecuteTemplate.java:51)
	at org.apache.shardingsphere.shardingjdbc.executor.AbstractStatementExecutor.executeCallback(AbstractStatementExecutor.java:129)
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.executeQuery(PreparedStatementExecutor.java:104)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.executeQuery(ShardingPreparedStatement.java:118)
	at sun.reflect.GeneratedMethodAccessor324.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)
	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)
	at com.sun.proxy.$Proxy418.executeQuery(Unknown Source)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:1962)
	at org.hibernate.loader.Loader.doQuery(Loader.java:829)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:289)
	at org.hibernate.loader.Loader.doList(Loader.java:2447)
	at org.hibernate.loader.Loader.doList(Loader.java:2433)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2263)
	at org.hibernate.loader.Loader.list(Loader.java:2258)
	at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:331)
	at org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java:1697)
	at org.hibernate.internal.AbstractSessionImpl.list(AbstractSessionImpl.java:225)
	at org.hibernate.internal.SQLQueryImpl.list(SQLQueryImpl.java:156)

### Actual behavior

MySQL function now() should be resolved to function now ()

**Comment by avalon5666** [comment]
Can you set sql.show=true, and provider the configuration and full exception log?

**Comment by trycache0828** [comment]
> Can you set sql.show=true, and provider the configuration and full exception log?

## The configration:

https://github.com/apache/shardingsphere/issues/10843

**Comment by avalon5666** [comment]
Can you set sql.show=true, and provider the configuration and full exception log? I need to confirm the logical sql and actual sql.

**Comment by trycache0828** [comment]
> Can you set sql.show=true, and provider the configuration and full exception log? I need to confirm the logical sql and actual sql.

The print result of logical SQL parsing is also wrong.Missing parentheses for function now().The MySQL function now() is resolved to the column name now.

## SQL

[ShardingSphere-SQL]Logic SQL: SELECT tnc.id, tnc.name, tnc.create_date AS createDate FROM t_user_child AS tnc, t_user AS tn WHERE YEAR(tn.create_date) = YEAR(NOW) ORDER BY tnc.create_date DESC

[ShardingSphere-SQL]Actual SQL: SELECT tnc.id, tnc.name, tnc.create_date AS createDate FROM t_user_child AS tnc, t_user_2019 AS tn WHERE YEAR(tn.create_date) = YEAR(NOW) ORDER BY tnc.create_date DESC

**Comment by avalon5666** [comment]
It seem the executing sql missing parenthesis, pls confirm the sql gen by hibernate is correct.

**Comment by trycache0828** [comment]
> It seem the executing sql missing parenthesis, pls confirm the sql gen by hibernate is correct.

![image](https://user-images.githubusercontent.com/14318621/123744246-1070c800-d8e1-11eb-9f47-c5061aa12e60.png)

**Comment by avalon5666** [comment]
The logical sql is pass by user code, pls confirm you sql is correct.
