### ISSUE TITLE
5.0.0_beta version start errror , the error is java.lang.NullPointerException

### ISSUE THREAD

**Issue by whiltemoon** [apache/shardingsphere#11047]
this is my :pom file config

> <?xml version="1.0" encoding="UTF-8"?>
> <project xmlns="http://maven.apache.org/POM/4.0.0"

         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <arthur.version>1.0.0</arthur.version>
        <lombok.version>1.18.20</lombok.version>
        <mybatis-plus_vserion>3.4.1</mybatis-plus_vserion>
        <commons.lang3.version>3.11</commons.lang3.version>
        <druid.vserion>1.1.22</druid.vserion>
        <mysql.version>8.0.18</mysql.version>
        <sharding-jdbc-version>5.0.0-beta</sharding-jdbc-version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>${sharding-jdbc-version}</version>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>${mysql.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>${commons.lang3.version}</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid</artifactId>
            <version>${druid.vserion}</version>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>${mybatis-plus_vserion}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.atlantis</groupId>
            <artifactId>arthurapi</artifactId>
            <version>${arthur.version}</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
_</project>_

this is my :yml file config

> `spring:
>   shardingsphere:

    props:
      sql-show: true
    datasource:
      names:
        master,slave
      common:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:xxxxx
        username: xxx
        password: xxx
        druid:
          initial-size: 5
          max-active: 20
          min-idle: 5
      slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://sxxxx
        username: xxx
        password: xxx
        druid:
          initial-size: 5
          max-active: 20
          min-idle: 5
    rules:
      readwrite-splitting:
        data-sources:
          ds:
            write-data-source-name: master
            read-data-source-names: slave`

down is the error info :
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shardingSphereDataSource' defined in class path resource [org/apache/shardingsphere/spring/boot/ShardingSphereAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'shardingSphereDataSource' threw exception; nested exception is org.apache.shardingsphere.infra.exception.ShardingSphereException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:769)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1313)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302)
	at com.atlantis.arthur.SpringArthurApplication.main(SpringArthurApplication.java:10)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'shardingSphereDataSource' threw exception; nested exception is org.apache.shardingsphere.infra.exception.ShardingSphereException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 20 common frames omitted
Caused by: org.apache.shardingsphere.infra.exception.ShardingSphereException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at org.apache.shardingsphere.infra.metadata.schema.builder.SchemaBuilder.appendDialectRemainTables(SchemaBuilder.java:125)
	at org.apache.shardingsphere.infra.metadata.schema.builder.SchemaBuilder.appendRemainTables(SchemaBuilder.java:97)
	at org.apache.shardingsphere.infra.metadata.schema.builder.SchemaBuilder.build(SchemaBuilder.java:78)
	at org.apache.shardingsphere.infra.context.metadata.MetaDataContextsBuilder.buildSchema(MetaDataContextsBuilder.java:136)
	at org.apache.shardingsphere.infra.context.metadata.MetaDataContextsBuilder.buildMetaData(MetaDataContextsBuilder.java:101)
	at org.apache.shardingsphere.infra.context.metadata.MetaDataContextsBuilder.build(MetaDataContextsBuilder.java:90)
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.<init>(ShardingSphereDataSource.java:55)
	at org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactory.createDataSource(ShardingSphereDataSourceFactory.java:49)
	at org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration.shardingSphereDataSource(ShardingSphereAutoConfiguration.java:73)
	at org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration$$EnhancerBySpringCGLIB$$efc1d769.CGLIB$shardingSphereDataSource$0(<generated>)
	at org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration$$EnhancerBySpringCGLIB$$efc1d769$$FastClassBySpringCGLIB$$175d94ea.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration$$EnhancerBySpringCGLIB$$efc1d769.shardingSphereDataSource(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)

**Comment by whiltemoon** [comment]
spring:
  shardingsphere:
    props:
      sql-show: true
    datasource:
      names:
        master,slave
      common:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:xxxxx
        username: xxx
        password: xxx
        druid:
          initial-size: 5
          max-active: 20
          min-idle: 5
      slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://sxxxx
        username: xxx
        password: xxx
        druid:
          initial-size: 5
          max-active: 20
          min-idle: 5
    rules:
      readwrite-splitting:
        data-sources:
          ds:
            write-data-source-name: master
            read-data-source-names: slave

**Comment by whiltemoon** [comment]
![image](https://user-images.githubusercontent.com/84312284/123724214-ccc68180-d840-11eb-8940-00257d6c96db.png)

跟踪了一下代码。 具体是这里报的空指针。

**Comment by RaigorJiang** [comment]
Hello @whiltemoon, for English only, please translate the content, thank you.

**Comment by whiltemoon** [comment]
![image](https://user-images.githubusercontent.com/84312284/123725129-680c2680-d842-11eb-949f-3199e0522dc8.png)

**Comment by RaigorJiang** [comment]
@whiltemoon  Thanks for your report, I will have a try with your configuration.

**Comment by whiltemoon** [comment]
@RaigorJiang  can you help me , what's issue about my error?

**Comment by RaigorJiang** [comment]
Yes, I am investigating, and I will reply you as soon as possible.

**Comment by whiltemoon** [comment]
@RaigorJiang  thanks you so much , if need more info , i can provider

**Comment by RaigorJiang** [comment]
@whiltemoon  I modified the [example module](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/sharding-example/sharding-spring-boot-mybatis-example) to fit your configuration, but can not reproduce the exception, can you provide a demo project on github?   So I can clone and test with your project.

**Comment by whiltemoon** [comment]
@RaigorJiang ok . i will do this noon

**Comment by RaigorJiang** [comment]
Thank you~

**Comment by whiltemoon** [comment]
@RaigorJiang  i have upload , the address is : https://github.com/whiltemoon/testjdbc
and you need change down config:
![image](https://user-images.githubusercontent.com/84312284/123899278-b6d9bf00-d91b-11eb-9780-8e377da9b0a3.png)

**Comment by RaigorJiang** [comment]
OK 👍

**Comment by RaigorJiang** [comment]
Hi @whiltemoon 
I just modified the datasource config and started normality, no NPE occurred.
shall we communicate via WeChat?   My WeChat account is also `RaigorJiang`.

```
2021-06-30 14:31:24.657 arthur[main][INFO ]o.s.boot.web.embedded.tomcat.TomcatWebServer - Tomcat initialized with port(s): 10012 (http)
2021-06-30 14:31:24.663 arthur[main][INFO ]org.apache.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-10012"]
2021-06-30 14:31:24.663 arthur[main][INFO ]org.apache.catalina.core.StandardService - Starting service [Tomcat]
2021-06-30 14:31:24.663 arthur[main][INFO ]org.apache.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/9.0.44]
2021-06-30 14:31:24.740 arthur[main][INFO ]o.a.c.core.ContainerBase.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
2021-06-30 14:31:24.740 arthur[main][INFO ]o.s.b.w.s.c.ServletWebServerApplicationContext - Root WebApplicationContext: initialization completed in 933 ms
2021-06-30 14:31:24.875 arthur[main][INFO ]o.s.scheduling.concurrent.ThreadPoolTaskExecutor - Initializing ExecutorService 'applicationTaskExecutor'
2021-06-30 14:31:25.017 arthur[main][INFO ]com.alibaba.druid.pool.DruidDataSource - {dataSource-1} inited
2021-06-30 14:31:35.118 arthur[main][INFO ]com.alibaba.druid.pool.DruidDataSource - {dataSource-2} inited
```

**Comment by RaigorJiang** [comment]
![image](https://user-images.githubusercontent.com/5668787/123927298-497f6a00-d9bf-11eb-8054-eb022c8ccbf2.png)

After confirmation, the problem is caused by the json format column in the table, which is duplicate with #10900 , #11024

**Comment by whiltemoon** [comment]
thankd you @RaigorJiang  issuse is my table has 'json' type cloumn .    can set check-table-metadata-enabled  deal but, this check-table-metadata-enabled conf not effected at  5.0.0_beta

**Comment by ican2056** [comment]
This seems to have something to do with the version of MySQL，5.7.34 is ok，but 5.7.25 not
