### ISSUE TITLE
Build Failed for Prelease

### ISSUE THREAD

**Issue by iamkyu** [apache/shardingsphere#11080]
### Which version of ShardingSphere did you use?
5.0.0-beta

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 

### Expected behavior
Success builds. When I do it

```shell
$ ./mvnw clean install -Prelease
```

### Actual behavior
Build Failed

```shell
~~~ skip above ~~~


[INFO] --- maven-surefire-plugin:2.22.0:test (default-test) @ shardingsphere-jdbc-core ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSourceTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.229 s - in org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSourceTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.core.datasource.metadata.ShardingSphereDatabaseMetaDataTest
[INFO] Tests run: 173, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.076 s - in org.apache.shardingsphere.driver.jdbc.core.datasource.metadata.ShardingSphereDatabaseMetaDataTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.core.resultset.GeneratedKeysResultSetMetaDataTest
[INFO] Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.111 s - in org.apache.shardingsphere.driver.jdbc.core.resultset.GeneratedKeysResultSetMetaDataTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.core.resultset.DatabaseMetaDataResultSetTest
[INFO] Tests run: 46, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.186 s - in org.apache.shardingsphere.driver.jdbc.core.resultset.DatabaseMetaDataResultSetTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.core.resultset.EncryptResultSetTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 s - in org.apache.shardingsphere.driver.jdbc.core.resultset.EncryptResultSetTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.core.resultset.ResultSetUtilTest
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 s - in org.apache.shardingsphere.driver.jdbc.core.resultset.ResultSetUtilTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.core.resultset.ShardingSphereResultSetTest
[INFO] Tests run: 59, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.578 s - in org.apache.shardingsphere.driver.jdbc.core.resultset.ShardingSphereResultSetTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.core.resultset.GeneratedKeysResultSetTest
[INFO] Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.apache.shardingsphere.driver.jdbc.core.resultset.GeneratedKeysResultSetTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.core.connection.ShardingSphereConnectionTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.047 s - in org.apache.shardingsphere.driver.jdbc.core.connection.ShardingSphereConnectionTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.core.statement.ReadwriteSplittingStatementTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.641 s - in org.apache.shardingsphere.driver.jdbc.core.statement.ReadwriteSplittingStatementTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.core.statement.EncryptPreparedStatementTest
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.043 s - in org.apache.shardingsphere.driver.jdbc.core.statement.EncryptPreparedStatementTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatementTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.771 s - in org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatementTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatementTest
[INFO] Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.648 s - in org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatementTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.core.statement.FederatePrepareStatementTest
[INFO] Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.727 s - in org.apache.shardingsphere.driver.jdbc.core.statement.FederatePrepareStatementTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.core.statement.ShadowStatementTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.153 s - in org.apache.shardingsphere.driver.jdbc.core.statement.ShadowStatementTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.core.statement.EncryptStatementTest
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.234 s - in org.apache.shardingsphere.driver.jdbc.core.statement.EncryptStatementTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.core.statement.FederateStatementTest
[INFO] Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.901 s - in org.apache.shardingsphere.driver.jdbc.core.statement.FederateStatementTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.core.statement.ShadowPreparedStatementTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.113 s - in org.apache.shardingsphere.driver.jdbc.core.statement.ShadowPreparedStatementTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.core.statement.ReadwriteSplittingPreparedStatementTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.018 s - in org.apache.shardingsphere.driver.jdbc.core.statement.ReadwriteSplittingPreparedStatementTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationDataSourceTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationDataSourceTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationPreparedStatementTest
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.233 s - in org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationPreparedStatementTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationStatementTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 s - in org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationStatementTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.unsupported.UnSupportedDatabaseMetaDataResultSetTest
[INFO] Tests run: 23, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in org.apache.shardingsphere.driver.jdbc.unsupported.UnSupportedDatabaseMetaDataResultSetTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationParameterMetaTest
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.021 s - in org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationParameterMetaTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest
[INFO] Tests run: 22, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.062 s - in org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedGeneratedKeysResultSetTest
[INFO] Tests run: 38, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 s - in org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedGeneratedKeysResultSetTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest
[INFO] Tests run: 36, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 s - in org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedUpdateOperationResultSetTest
[INFO] Tests run: 82, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.043 s - in org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedUpdateOperationResultSetTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.adapter.invocation.JdbcMethodInvocationTest
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.012 s <<< FAILURE! - in org.apache.shardingsphere.driver.jdbc.adapter.invocation.JdbcMethodInvocationTest
[ERROR] assertInvokeFailure(org.apache.shardingsphere.driver.jdbc.adapter.invocation.JdbcMethodInvocationTest)  Time elapsed: 0.006 s  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<java.lang.IllegalAccessException> but was<java.lang.NoSuchMethodException>
        at org.apache.shardingsphere.driver.jdbc.adapter.invocation.JdbcMethodInvocationTest.assertInvokeFailure(JdbcMethodInvocationTest.java:32)

[INFO] Running org.apache.shardingsphere.driver.jdbc.adapter.invocation.SetParameterMethodInvocationTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.apache.shardingsphere.driver.jdbc.adapter.invocation.SetParameterMethodInvocationTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.adapter.PreparedStatementAdapterTest
[INFO] Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.045 s - in org.apache.shardingsphere.driver.jdbc.adapter.PreparedStatementAdapterTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.adapter.ResultSetGetterAdapterTest
[INFO] Tests run: 52, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.057 s - in org.apache.shardingsphere.driver.jdbc.adapter.ResultSetGetterAdapterTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.adapter.ResultSetAdapterTest
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.064 s - in org.apache.shardingsphere.driver.jdbc.adapter.ResultSetAdapterTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.adapter.WrapperAdapterTest
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.058 s - in org.apache.shardingsphere.driver.jdbc.adapter.WrapperAdapterTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.adapter.ConnectionAdapterTest
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in org.apache.shardingsphere.driver.jdbc.adapter.ConnectionAdapterTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.adapter.StatementAdapterTest
[INFO] Tests run: 23, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.132 s - in org.apache.shardingsphere.driver.jdbc.adapter.StatementAdapterTest
[INFO] Running org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactoryTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.021 s - in org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactoryTest
[INFO] Running org.apache.shardingsphere.driver.executor.batch.BatchPreparedStatementExecutorTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.068 s - in org.apache.shardingsphere.driver.executor.batch.BatchPreparedStatementExecutorTest
[INFO] Running org.apache.shardingsphere.driver.executor.batch.BatchExecutionUnitTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 s - in org.apache.shardingsphere.driver.executor.batch.BatchExecutionUnitTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   JdbcMethodInvocationTest.assertInvokeFailure »  Unexpected exception, expected...
[INFO] 
[ERROR] Tests run: 826, Failures: 0, Errors: 1, Skipped: 1
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for shardingsphere 5.0.0-RC1-SNAPSHOT:
[INFO] 
[INFO] shardingsphere ..................................... SUCCESS [  6.918 s]
[INFO] shardingsphere-agent ............................... SUCCESS [  0.563 s]
[INFO] shardingsphere-agent-api ........................... SUCCESS [  4.470 s]
[INFO] shardingsphere-agent-core .......................... SUCCESS [ 10.450 s]
[INFO] shardingsphere-agent-bootstrap ..................... SUCCESS [  4.438 s]
[INFO] shardingsphere-sql-parser .......................... SUCCESS [  0.574 s]
[INFO] shardingsphere-sql-parser-spi ...................... SUCCESS [  2.203 s]
[INFO] shardingsphere-sql-parser-statement ................ SUCCESS [ 20.758 s]
[INFO] shardingsphere-sql-parser-engine ................... SUCCESS [  6.111 s]
[INFO] shardingsphere-distsql-parser ...................... SUCCESS [  0.217 s]
[INFO] shardingsphere-distsql-parser-statement ............ SUCCESS [  2.520 s]
[INFO] shardingsphere-distsql-parser-engine ............... SUCCESS [  6.484 s]
[INFO] shardingsphere-infra ............................... SUCCESS [  0.411 s]
[INFO] shardingsphere-infra-parser ........................ SUCCESS [  4.914 s]
[INFO] shardingsphere-infra-common ........................ SUCCESS [ 17.686 s]
[INFO] shardingsphere-infra-binder ........................ SUCCESS [ 10.254 s]
[INFO] shardingsphere-infra-route ......................... SUCCESS [  5.366 s]
[INFO] shardingsphere-agent-plugins ....................... SUCCESS [  0.274 s]
[INFO] shardingsphere-agent-plugin-metrics ................ SUCCESS [  0.235 s]
[INFO] shardingsphere-agent-metrics-api ................... SUCCESS [  5.624 s]
[INFO] shardingsphere-agent-metrics-prometheus ............ SUCCESS [  4.468 s]
[INFO] shardingsphere-db-protocol ......................... SUCCESS [  0.281 s]
[INFO] shardingsphere-db-protocol-core .................... SUCCESS [  5.787 s]
[INFO] shardingsphere-features ............................ SUCCESS [  0.546 s]
[INFO] shardingsphere-sharding ............................ SUCCESS [  0.312 s]
[INFO] shardingsphere-sharding-distsql .................... SUCCESS [  0.208 s]
[INFO] shardingsphere-sharding-distsql-statement .......... SUCCESS [  2.579 s]
[INFO] shardingsphere-sharding-distsql-parser ............. SUCCESS [  4.062 s]
[INFO] shardingsphere-readwrite-splitting ................. SUCCESS [  0.231 s]
[INFO] shardingsphere-readwrite-splitting-distsql ......... SUCCESS [  0.204 s]
[INFO] shardingsphere-readwrite-splitting-distsql-statement SUCCESS [  2.287 s]
[INFO] shardingsphere-readwrite-splitting-distsql-parser .. SUCCESS [  4.656 s]
[INFO] shardingsphere-db-discovery ........................ SUCCESS [  0.309 s]
[INFO] shardingsphere-db-discovery-distsql ................ SUCCESS [  0.236 s]
[INFO] shardingsphere-db-discovery-distsql-statement ...... SUCCESS [  2.271 s]
[INFO] shardingsphere-db-discovery-distsql-parser ......... SUCCESS [  4.317 s]
[INFO] shardingsphere-encrypt ............................. SUCCESS [  0.240 s]
[INFO] shardingsphere-encrypt-distsql ..................... SUCCESS [  0.243 s]
[INFO] shardingsphere-encrypt-distsql-statement ........... SUCCESS [  2.512 s]
[INFO] shardingsphere-encrypt-distsql-parser .............. SUCCESS [  4.020 s]
[INFO] shardingsphere-sql-parser-test ..................... SUCCESS [ 14.662 s]
[INFO] shardingsphere-sql-parser-dialect .................. SUCCESS [  0.770 s]
[INFO] shardingsphere-sql-parser-sql92 .................... SUCCESS [ 17.108 s]
[INFO] shardingsphere-sql-parser-mysql .................... SUCCESS [ 44.344 s]
[INFO] shardingsphere-sql-parser-postgresql ............... SUCCESS [ 41.117 s]
[INFO] shardingsphere-sql-parser-oracle ................... SUCCESS [ 37.497 s]
[INFO] shardingsphere-sql-parser-sqlserver ................ SUCCESS [ 18.898 s]
[INFO] shardingsphere-infra-rewrite ....................... SUCCESS [ 11.019 s]
[INFO] shardingsphere-infra-optimize ...................... SUCCESS [ 10.306 s]
[INFO] shardingsphere-infra-executor ...................... SUCCESS [ 13.180 s]
[INFO] shardingsphere-infra-authority ..................... SUCCESS [  0.171 s]
[INFO] shardingsphere-infra-authority-api ................. SUCCESS [  2.253 s]
[INFO] shardingsphere-test ................................ SUCCESS [  0.328 s]
[INFO] shardingsphere-test-common ......................... SUCCESS [  2.417 s]
[INFO] shardingsphere-infra-context ....................... SUCCESS [  9.597 s]
[INFO] shardingsphere-governance .......................... SUCCESS [  0.216 s]
[INFO] shardingsphere-governance-repository ............... SUCCESS [  0.120 s]
[INFO] shardingsphere-governance-repository-api ........... SUCCESS [  2.682 s]
[INFO] shardingsphere-infra-authority-common .............. SUCCESS [  7.847 s]
[INFO] shardingsphere-governance-core ..................... SUCCESS [  9.286 s]
[INFO] shardingsphere-sharding-api ........................ SUCCESS [  2.867 s]
[INFO] shardingsphere-infra-merge ......................... SUCCESS [  7.413 s]
[INFO] shardingsphere-infra-datetime ...................... SUCCESS [  0.135 s]
[INFO] shardingsphere-infra-datetime-spi .................. SUCCESS [  2.110 s]
[INFO] shardingsphere-infra-datetime-type ................. SUCCESS [  0.189 s]
[INFO] shardingsphere-system-datetime ..................... SUCCESS [  3.507 s]
[INFO] shardingsphere-sharding-core ....................... SUCCESS [ 26.655 s]
[INFO] shardingsphere-readwrite-splitting-api ............. SUCCESS [  2.270 s]
[INFO] shardingsphere-readwrite-splitting-core ............ SUCCESS [  7.927 s]
[INFO] shardingsphere-encrypt-api ......................... SUCCESS [  2.827 s]
[INFO] shardingsphere-encrypt-core ........................ SUCCESS [ 12.175 s]
[INFO] shardingsphere-db-discovery-api .................... SUCCESS [  2.139 s]
[INFO] shardingsphere-db-discovery-provider ............... SUCCESS [  0.128 s]
[INFO] shardingsphere-db-discovery-mgr .................... SUCCESS [  6.948 s]
[INFO] shardingsphere-db-discovery-core ................... SUCCESS [  6.874 s]
[INFO] shardingsphere-proxy ............................... SUCCESS [  0.331 s]
[INFO] shardingsphere-proxy-common ........................ SUCCESS [  6.200 s]
[INFO] shardingsphere-shadow .............................. SUCCESS [  0.156 s]
[INFO] shardingsphere-shadow-api .......................... SUCCESS [  1.846 s]
[INFO] shardingsphere-shadow-core ......................... SUCCESS [  6.053 s]
[INFO] shardingsphere-transaction ......................... SUCCESS [  0.918 s]
[INFO] shardingsphere-transaction-core .................... SUCCESS [  5.272 s]
[INFO] shardingsphere-transaction-2pc ..................... SUCCESS [  0.372 s]
[INFO] shardingsphere-transaction-xa ...................... SUCCESS [  0.490 s]
[INFO] shardingsphere-transaction-xa-spi .................. SUCCESS [  6.774 s]
[INFO] shardingsphere-transaction-xa-atomikos ............. SUCCESS [  5.611 s]
[INFO] shardingsphere-transaction-xa-core ................. SUCCESS [ 10.418 s]
[INFO] shardingsphere-scaling ............................. SUCCESS [  0.281 s]
[INFO] shardingsphere-scaling-distsql ..................... SUCCESS [  0.118 s]
[INFO] shardingsphere-scaling-distsql-statement ........... SUCCESS [  2.446 s]
[INFO] shardingsphere-scaling-distsql-parser .............. SUCCESS [  5.223 s]
[INFO] shardingsphere-jdbc ................................ SUCCESS [  0.283 s]
[INFO] shardingsphere-jdbc-core ........................... FAILURE [ 35.305 s]
[INFO] shardingsphere-governance-repository-provider ...... SKIPPED
[INFO] shardingsphere-governance-repository-zookeeper-curator SKIPPED
[INFO] shardingsphere-scaling-core ........................ SKIPPED
[INFO] shardingsphere-db-protocol-mysql ................... SKIPPED
[INFO] shardingsphere-scaling-dialect ..................... SKIPPED
[INFO] shardingsphere-scaling-mysql ....................... SKIPPED
[INFO] shardingsphere-scaling-postgresql .................. SKIPPED
[INFO] shardingsphere-proxy-backend ....................... SKIPPED
[INFO] shardingsphere-proxy-frontend ...................... SKIPPED
[INFO] shardingsphere-proxy-frontend-spi .................. SKIPPED
[INFO] shardingsphere-proxy-frontend-core ................. SKIPPED
[INFO] shardingsphere-agent-plugin-tracing ................ SKIPPED
[INFO] shardingsphere-agent-tracing-test .................. SKIPPED
[INFO] shardingsphere-agent-tracing-jaeger ................ SKIPPED
[INFO] shardingsphere-agent-tracing-zipkin ................ SKIPPED
[INFO] shardingsphere-agent-tracing-opentracing ........... SKIPPED
[INFO] shardingsphere-agent-plugin-logging ................ SKIPPED
[INFO] shardingsphere-agent-logging-base .................. SKIPPED
[INFO] shardingsphere-agent-distribution .................. SKIPPED
[INFO] shardingsphere-distsql-parser-test ................. SKIPPED
[INFO] shardingsphere-db-protocol-postgresql .............. SKIPPED
[INFO] shardingsphere-database-datetime ................... SKIPPED
[INFO] shardingsphere-governance-context .................. SKIPPED
[INFO] shardingsphere-jdbc-governance ..................... SKIPPED
[INFO] shardingsphere-jdbc-spring ......................... SKIPPED
[INFO] shardingsphere-jdbc-spring-infra ................... SKIPPED
[INFO] shardingsphere-jdbc-spring-boot-starter-infra ...... SKIPPED
[INFO] shardingsphere-jdbc-spring-namespace-infra ......... SKIPPED
[INFO] shardingsphere-sharding-spring ..................... SKIPPED
[INFO] shardingsphere-sharding-spring-boot-starter ........ SKIPPED
[INFO] shardingsphere-shadow-spring ....................... SKIPPED
[INFO] shardingsphere-shadow-spring-boot-starter .......... SKIPPED
[INFO] shardingsphere-encrypt-spring ...................... SKIPPED
[INFO] shardingsphere-encrypt-spring-boot-starter ......... SKIPPED
[INFO] shardingsphere-readwrite-splitting-spring .......... SKIPPED
[INFO] shardingsphere-readwrite-splitting-spring-boot-starter SKIPPED
[INFO] shardingsphere-jdbc-transaction-spring ............. SKIPPED
[INFO] shardingsphere-jdbc-core-spring .................... SKIPPED
[INFO] shardingsphere-jdbc-core-spring-boot-starter ....... SKIPPED
[INFO] shardingsphere-sharding-spring-namespace ........... SKIPPED
[INFO] shardingsphere-readwrite-splitting-spring-namespace  SKIPPED
[INFO] shardingsphere-encrypt-spring-namespace ............ SKIPPED
[INFO] shardingsphere-shadow-spring-namespace ............. SKIPPED
[INFO] shardingsphere-jdbc-core-spring-namespace .......... SKIPPED
[INFO] shardingsphere-jdbc-governance-spring .............. SKIPPED
[INFO] shardingsphere-jdbc-governance-spring-boot-starter . SKIPPED
[INFO] shardingsphere-jdbc-governance-spring-namespace .... SKIPPED
[INFO] shardingsphere-proxy-frontend-mysql ................ SKIPPED
[INFO] shardingsphere-proxy-frontend-postgresql ........... SKIPPED
[INFO] shardingsphere-governance-repository-etcd .......... SKIPPED
[INFO] shardingsphere-proxy-bootstrap ..................... SKIPPED
[INFO] shardingsphere-db-discovery-spring ................. SKIPPED
[INFO] shardingsphere-db-discovery-spring-namespace ....... SKIPPED
[INFO] shardingsphere-db-discovery-spring-boot-starter .... SKIPPED
[INFO] shardingsphere-scaling-bootstrap ................... SKIPPED
[INFO] shardingsphere-transaction-xa-narayana ............. SKIPPED
[INFO] shardingsphere-transaction-xa-bitronix ............. SKIPPED
[INFO] shardingsphere-transaction-base .................... SKIPPED
[INFO] shardingsphere-transaction-base-seata-at ........... SKIPPED
[INFO] shardingsphere-integration-test .................... SKIPPED
[INFO] shardingsphere-integration-test-fixture ............ SKIPPED
[INFO] shardingsphere-integration-test-suite .............. SKIPPED
[INFO] shardingsphere-integration-agent-test .............. SKIPPED
[INFO] shardingsphere-integration-agent-test-plugins ...... SKIPPED
[INFO] shardingsphere-integration-agent-test-common ....... SKIPPED
[INFO] shardingsphere-integration-agent-test-metrics ...... SKIPPED
[INFO] shardingsphere-integration-agent-test-zipkin ....... SKIPPED
[INFO] shardingsphere-integration-agent-test-jaeger ....... SKIPPED
[INFO] shardingsphere-integration-scaling-test ............ SKIPPED
[INFO] shardingsphere-integration-scaling-test-mysql ...... SKIPPED
[INFO] shardingsphere-rewrite-test ........................ SKIPPED
[INFO] shardingsphere-distribution ........................ SKIPPED
[INFO] shardingsphere-src-distribution .................... SKIPPED
[INFO] shardingsphere-jdbc-distribution ................... SKIPPED
[INFO] shardingsphere-proxy-distribution .................. SKIPPED
[INFO] shardingsphere-scaling-distribution ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  09:27 min
[INFO] Finished at: 2021-06-30T22:53:05+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project shardingsphere-jdbc-core: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/kjnam/workspace/shardingsphere/shardingsphere-jdbc/shardingsphere-jdbc-core/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :shardingsphere-jdbc-core
```

/shardingsphere/shardingsphere-jdbc/shardingsphere-jdbc-core/target/surefire-reports/org.apache.shardingsphere.driver.jdbc.adapter.invocation.JdbcMethodInvocationTest.txt
```
-------------------------------------------------------------------------------
Test set: org.apache.shardingsphere.driver.jdbc.adapter.invocation.JdbcMethodInvocationTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.012 s <<< FAILURE! - in org.apache.shardingsphere.driver.jdbc.adapter.invocation.JdbcMethodInvocationTest
assertInvokeFailure(org.apache.shardingsphere.driver.jdbc.adapter.invocation.JdbcMethodInvocationTest)  Time elapsed: 0.006 s  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<java.lang.IllegalAccessException> but was<java.lang.NoSuchMethodException>
	at org.apache.shardingsphere.driver.jdbc.adapter.invocation.JdbcMethodInvocationTest.assertInvokeFailure(JdbcMethodInvocationTest.java:32)


```

### Reason analyze (If you can)
Broken Test in `org.apache.shardingsphere.driver.jdbc.adapter.invocation.JdbcMethodInvocationTest`

```java
@Test(expected = IllegalAccessException.class)
public void assertInvokeFailure() throws NoSuchMethodException {
    JdbcMethodInvocation actual = new JdbcMethodInvocation(String.class.getDeclaredMethod("indexOfSupplementary", int.class, int.class), new Object[] {1, 1});
    actual.invoke("");
}
```
- `NoSuchMethodException` occured when Class.getDeclaredMethod(String,  Class<?>...) called.
- but test expected Thrown `IllegalAccessException`

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. check out the repository
2.  execute maven build command `$ ./mvnw clean install -Prelease`

### Example codes for reproduce this issue (such as a github link).
N/A

**Comment by iamkyu** [comment]
My mistake.
when `Clazz.class.getDeclaredMethod(String, Class<?>...)` Called
- with [AdoptOpenJDK 8.0.292.j9](https://www.eclipse.org/openj9/) : `NoSuchMethodException` Occured.
- with AdoptOpenJDK 8.0.292.hs-adpt: No exceptions occurs. `IllegalAccessException` Occured when 'method.invoke(Object, Object...)' (Same as test case)
