### ISSUE TITLE
Sharding JDBC 5.0.0-beta createDataSource error

### ISSUE THREAD

**Issue by boycai** [apache/shardingsphere#11092]
### Which version of ShardingSphere did you use?
shardingsphere-jdbc-core-5.0.0-beta

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
shardingsphere-jdbc

### Actual behavior
throw Exception

### Example codes for reproduce this issue (such as a github link).
**My code：**
`DataSource dataSource = YamlShardingSphereDataSourceFactory.createDataSource(yamlBytes);`

**To print the stack as follows：**
`Caused by: org.yaml.snakeyaml.constructor.ConstructorException: Can't construct a java object for tag:yaml.org,2002:com.alibaba.druid.pool.DruidDataSource; exception=Class is not accepted: com.alibaba.druid.pool.DruidDataSource
 in 'reader', line 4, column 8:
      ds0: !!com.alibaba.druid.pool.DruidDa ... 
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:313)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:462)
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:183)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:443)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:136)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.newInstance(Constructor.java:281)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:246)
	... 102 common frames omitted
`
`Caused by: java.lang.IllegalArgumentException: Class is not accepted: com.alibaba.druid.pool.DruidDataSource
	at org.apache.shardingsphere.infra.yaml.engine.constructor.ShardingSphereYamlConstructor.getClassForName(ShardingSphereYamlConstructor.java:60)
	at org.yaml.snakeyaml.constructor.Constructor.getClassForNode(Constructor.java:640)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.getConstructor(Constructor.java:298)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:308)
	... 112 common frames omitted
`

**Comment by avalon5666** [comment]
Reference [example](https://github.com/apache/shardingsphere/blob/5.0.0-beta/examples/shardingsphere-jdbc-example/sharding-example/sharding-raw-jdbc-example/src/main/resources/META-INF/sharding-databases.yaml).
We update the document.

**Comment by boycai** [comment]
Problem has been solved, thank you
