### ISSUE TITLE
"2Unknown exception: [INSERT INTO .... ON DUPLICATE KEY UPDATE can not support update for sh arding column.]"

### ISSUE THREAD

**Issue by riverdba** [apache/shardingsphere#11157]
## Bug Report
[ERROR] 2021-07-05 15:43:33.881 [ShardingSphere-Scaling-execute-5] o.a.s.s.c.e.i.AbstractImporter - flush failed 0/3 times
.
java.sql.BatchUpdateException: 2Unknown exception: [INSERT INTO .... ON DUPLICATE KEY UPDATE can not support update for sh
arding column.]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.Util.getInstance(Util.java:408)
        at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163)
        at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1632)
        at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1298)
        at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970)
        at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
        at org.apache.shardingsphere.scaling.core.executor.importer.AbstractImporter.executeBatchInsert(AbstractImporter.j
ava:167)
        at org.apache.shardingsphere.scaling.core.executor.importer.AbstractImporter.doFlush(AbstractImporter.java:142)
        at org.apache.shardingsphere.scaling.core.executor.importer.AbstractImporter.tryFlush(AbstractImporter.java:127)
        at org.apache.shardingsphere.scaling.core.executor.importer.AbstractImporter.flushInternal(AbstractImporter.java:1
18)
        at org.apache.shardingsphere.scaling.core.executor.importer.AbstractImporter.lambda$flush$2(AbstractImporter.java:
109)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at org.apache.shardingsphere.scaling.core.executor.importer.AbstractImporter.flush(AbstractImporter.java:104)
        at org.apache.shardingsphere.scaling.core.executor.importer.AbstractImporter.write(AbstractImporter.java:89)
        at org.apache.shardingsphere.scaling.core.executor.importer.AbstractImporter.start(AbstractImporter.java:81)
        at org.apache.shardingsphere.scaling.core.executor.AbstractScalingExecutor.run(AbstractScalingExecutor.java:47)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(T
rustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: 2Unknown exception: [INSERT INTO .... ON DUPLICATE KEY UPDATE can not support update for
 sharding column.]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058)
        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158)
        at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1593)
        ... 21 common frames omitted
### Which version of ShardingSphere did you use?
apache-shardingsphere-5.0.0-beta-shardingsphere-scaling-bin.tar.gz
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
I use scaling5.0 migration data to ShardingSphere-Proxy4.1.0

**Comment by strongduanmu** [comment]
> I use scaling5.0 migration data to ShardingSphere-Proxy4.1.0

@riverdba Can you try `ShardingSphere-Proxy 5.0.0-beta`? The latest version has better SQL support.

**Comment by riverdba** [comment]
> > I use scaling5.0 migration data to ShardingSphere-Proxy4.1.0
> 
> @riverdba Can you try `ShardingSphere-Proxy 5.0.0-beta`? The latest version has better SQL support.
Yes,I used ShardingSphere-Proxy 5.0.0-beta.download from:
https://mirrors.bfsu.edu.cn/apache/shardingsphere/5.0.0-beta/apache-shardingsphere-5.0.0-beta-shardingsphere-scaling-bin.tar.gz

**Comment by strongduanmu** [comment]
@riverdba Still having problems with the latest version?

**Comment by riverdba** [comment]
> @strongduanmu  Still having problems with the latest version?

Yes.

**Comment by strongduanmu** [comment]
The sharding table does not allow updating the sharding column, so an exception is thrown.@avalon566  will help investigate possible problems in scaling?

**Comment by avalon5666** [comment]
Migration from single database to sharding, the source shardingsphereJdbc must configure sharding column. It will exclude sharding column from where condition.
