### ISSUE TITLE
Investigate mvn install failure

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#11307]
The mvn install failure sometimes, please investigate.

 
```log
[ERROR] Tests run: 1372, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 22.192 s <<< FAILURE! - in org.apache.shardingsphere.test.integration.engine.it.dql.GeneralDQLIT
[ERROR] assertExecute[jdbc: dbtbl_with_readwrite_splitting_and_encrypt -> H2 -> Placeholder -> SELECT 1 as a](org.apache.shardingsphere.test.integration.engine.it.dql.GeneralDQLIT)  Time elapsed: 0.038 s  <<< ERROR!
java.lang.ClassCastException: org.apache.shardingsphere.authority.rule.builder.AuthorityRuleBuilder cannot be cast to org.apache.shardingsphere.infra.rule.builder.scope.SchemaRuleBuilder

[ERROR] assertExecuteQuery[jdbc: readwrite_splitting -> H2 -> Literal -> SELECT t_order.order_id,t_order.user_id,status FROM t_order t_order WHERE t_order.user_id = ? AND order_id = ?](org.apache.shardingsphere.test.integration.engine.it.dql.GeneralDQLIT)  Time elapsed: 0.035 s  <<< ERROR!
java.lang.ClassCastException: org.apache.shardingsphere.authority.rule.builder.AuthorityRuleBuilder cannot be cast to org.apache.shardingsphere.infra.rule.builder.scope.SchemaRuleBuilder
```

**Comment by totalo** [comment]
hi, I want to try to fix it.

**Comment by strongduanmu** [comment]
@totalo Welcome!

**Comment by totalo** [comment]
hi @terrymanu ,Do you have stack information? It doesn't seem to be able to reproduce in my local area, but I guess yours is because the JAR package doesn't match.

**Comment by terrymanu** [comment]
@totalo The problem maybe throw when executing by `mvn -T 1C install`

**Comment by totalo** [comment]
> @totalo The exception maybe throw when executing by `mvn -T 1C install`

ok，thx

**Comment by terrymanu** [comment]
More details for exception thrown some times:

```log
[ERROR] 2021-07-18 18:44:58.150 [ShardingSphere-21] o.a.s.t.i.junit.watcher.ITWatcher - Error case: assertExecute[jdbc: tbl -> H2 -> Placeholder -> SELECT t_order.* FROM t_order t_order WHERE user_id = ? AND order_id = ?], message: java.lang.ClassCastException: org.apache.shardingsphere.authority.rule.builder.AuthorityRuleBuilder cannot be cast to org.apache.shardingsphere.infra.rule.builder.scope.SchemaRuleBuilder
	at org.apache.shardingsphere.infra.rule.builder.ShardingSphereRulesBuilder.lambda$buildSchemaRules$0(ShardingSphereRulesBuilder.java:69)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.apache.shardingsphere.infra.rule.builder.ShardingSphereRulesBuilder.buildSchemaRules(ShardingSphereRulesBuilder.java:69)
	at org.apache.shardingsphere.infra.context.metadata.MetaDataContextsBuilder.build(MetaDataContextsBuilder.java:98)
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.<init>(ShardingSphereDataSource.java:55)
	at org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactory.createDataSource(ShardingSphereDataSourceFactory.java:49)
	at org.apache.shardingsphere.driver.api.yaml.YamlShardingSphereDataSourceFactory.createDataSource(YamlShardingSphereDataSourceFactory.java:85)
	at org.apache.shardingsphere.test.integration.junit.container.adapter.impl.ShardingSphereJDBCContainer.getDataSource(ShardingSphereJDBCContainer.java:72)
	at org.apache.shardingsphere.test.integration.junit.compose.ContainerCompose.getDataSourceMap(ContainerCompose.java:162)
	at org.apache.shardingsphere.test.integration.engine.it.BaseITCase.createDataSource(BaseITCase.java:83)
	at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[ERROR] 2021-07-18 18:44:58.150 [ShardingSphere-21] o.a.s.t.i.junit.watcher.ITWatcher - Error case: assertExecute[jdbc: tbl -> H2 -> Placeholder -> SELECT t_order.* FROM t_order t_order WHERE user_id = ? AND order_id = ?], message: java.lang.ClassCastException: org.apache.shardingsphere.authority.rule.builder.AuthorityRuleBuilder cannot be cast to org.apache.shardingsphere.infra.rule.builder.scope.SchemaRuleBuilder
	at org.apache.shardingsphere.infra.rule.builder.ShardingSphereRulesBuilder.lambda$buildSchemaRules$0(ShardingSphereRulesBuilder.java:69)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.apache.shardingsphere.infra.rule.builder.ShardingSphereRulesBuilder.buildSchemaRules(ShardingSphereRulesBuilder.java:69)
	at org.apache.shardingsphere.infra.context.metadata.MetaDataContextsBuilder.build(MetaDataContextsBuilder.java:98)
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.<init>(ShardingSphereDataSource.java:55)
	at org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactory.createDataSource(ShardingSphereDataSourceFactory.java:49)
	at org.apache.shardingsphere.driver.api.yaml.YamlShardingSphereDataSourceFactory.createDataSource(YamlShardingSphereDataSourceFactory.java:85)
	at org.apache.shardingsphere.test.integration.junit.container.adapter.impl.ShardingSphereJDBCContainer.getDataSource(ShardingSphereJDBCContainer.java:72)
	at org.apache.shardingsphere.test.integration.junit.compose.ContainerCompose.getDataSourceMap(ContainerCompose.java:162)
	at org.apache.shardingsphere.test.integration.engine.it.BaseITCase.createDataSource(BaseITCase.java:83)
	at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by totalo** [comment]
I guess it is because multiple CPUs use multiple CPUs, and when each CPU is built by a single thread, the speed of the CPUs is not consistent, resulting in the sequence of loading is not consistent, leading to the occurrence of contingencies. This needs to be further observed. I'm going to fix a TODO.

**Comment by terrymanu** [comment]
OK, I will merge and try

**Comment by terrymanu** [comment]
The problem still existed, I just revert it by #11412

**Comment by totalo** [comment]
> The problem still existed, I just revert it by #11412

Okay, I'll keep trying to figure it out.
