### ISSUE TITLE
Does shardingsphere-proxy support aws redshift?

### ISSUE THREAD

**Issue by hanxiang01** [apache/shardingsphere#11340]
Hello Team,
I am trying to proxy the aws redshift database with shardingspere -proxy but have been experiencing some problems and would like to ask if aws redshift is supported?
The problem is described as follows:

`警告: Unsupported Server Version: 8.0.2
[INFO ] 12:50:42.881 [main] c.a.d.xa.XATransactionalResource - resource-1-ds_0: refreshed XAResource
[WARN ] 12:50:43.005 [main] c.a.r.xa.XaResourceRecoveryManager - Error while retrieving xids from resource - will retry later...
org.postgresql.xa.PGXAException: Error during recover
Caused by: org.postgresql.util.PSQLException: ERROR: Specified types or functions (one per INFO message) not supported on Redshift tables.`

`警告: Unsupported Server Version: 8.0.2
[INFO ] 12:50:43.571 [main] c.a.d.xa.XATransactionalResource - resource-1-ds_0: refreshed XAResource
[INFO ] 12:50:43.605 [main] ShardingSphere-metadata - Loading 0 logic tables' meta data.
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: type "e" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)`

thank you.

**Comment by strongduanmu** [comment]
Hi @hanxiang01, `Shardingsphere-Proxy` fully supports MySQL and PostgreSQL databases. Amazon Redshift is based on PostgreSQL 8.0.2 version. I don't know how different it is from standard PostgreSQL. These differences may cause some problems.

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 30 days, we will close it. 
If you still have related questions, please submit a new issue, thank you.
