### ISSUE TITLE
not support pgsql left join sql?

### ISSUE THREAD

**Issue by simpleSOA** [apache/shardingsphere#11360]
String q = "SELECT r.id FROM t_pd_tag_rule r LEFT JOIN t_au_user u ON u.id = r.create_id WHERE r.name = ?";
SQLParserExecutor executor = new SQLParserExecutor("PostgreSQL");
executor.parse(q);

result:
line 1:55 no viable alternative at input 'SELECTr.idFROMt_pd_tag_rulerLEFTJOINt_au_useruON'
line 1:55 no viable alternative at input 'SELECTr.idFROMt_pd_tag_rulerLEFTJOINt_au_useruON'
Exception in thread "main" org.apache.shardingsphere.sql.parser.exception.SQLParsingException: You have an error in your SQL syntax

version:5.0.0-beta

**Comment by tuichenchuxin** [comment]
I want to track this issue.

**Comment by simpleSOA** [comment]
> I want to track this issue.

the exception detail:
line 1:55 no viable alternative at input 'SELECTr.idFROMt_pd_tag_rulerLEFTJOINt_au_useruON'
line 1:55 no viable alternative at input 'SELECTr.idFROMt_pd_tag_rulerLEFTJOINt_au_useruON'
Exception in thread "main" org.apache.shardingsphere.sql.parser.exception.SQLParsingException: You have an error in your SQL syntax
	at org.apache.shardingsphere.sql.parser.core.parser.SQLParserExecutor.twoPhaseParse(SQLParserExecutor.java:63)
	at org.apache.shardingsphere.sql.parser.core.parser.SQLParserExecutor.parse(SQLParserExecutor.java:45)
	at Test1.test(Test1.java:18)
	at Test1.main(Test1.java:12)

**Comment by tuichenchuxin** [comment]
@simpleSOA I found that if you replate the word `u` to any other word then is ok.
This is a bug in sql parser.
like `select * from t_user u` can't be parsed well.
We will fix it later.

**Comment by tuichenchuxin** [comment]
![image](https://user-images.githubusercontent.com/86938616/127498462-c556fdc2-a59c-4ff4-a151-1d30db2dc7cf.png)
baserule.g4

**Comment by menghaoranss** [comment]
@tuichenchuxin I will move this issue to the next version, you can still try to resolve it later

**Comment by tuichenchuxin** [comment]
It has been fixed by this pr #12332
