### ISSUE TITLE
union all  report Error

### ISSUE THREAD

**Issue by Yule-Momoko** [apache/shardingsphere#11386]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-beta
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-JDBC
### Expected behavior
union all  report Error
### Actual behavior
Caused by: java.lang.IllegalStateException: union select is not supported yet.
at org.apache.shardingsphere.sql.parser.mysql.visitor.statement.impl.MySQLStatementSQLVisitor.visitQueryExpressionBody(MySQLStatementSQLVisitor.java:594)
at org.apache.shardingsphere.sql.parser.mysql.visitor.statement.impl.MySQLStatementSQLVisitor.visitQueryExpressionBody(MySQLStatementSQLVisitor.java:198)
at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$QueryExpressionBodyContext.accept(MySQLStatementParser.java:4373)
at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
at org.apache.shardingsphere.sql.parser.mysql.visitor.statement.impl.MySQLStatementSQLVisitor.visitQueryExpression(MySQLStatementSQLVisitor.java:564)
at org.apache.shardingsphere.sql.parser.mysql.visitor.statement.impl.MySQLStatementSQLVisitor.visitQueryExpression(MySQLStatementSQLVisitor.java:198)
at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$QueryExpressionContext.accept(MySQLStatementParser.java:4279)
at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)

**Comment by Yule-Momoko** [comment]
My routing strategy is Hint
![image](https://user-images.githubusercontent.com/67772051/126132983-3ec6b266-7772-4ea2-8f4d-d11288d0812f.png)

**Comment by tristaZero** [comment]
All the SQLs (including union) routing to one sharding table can be executed well, right?
@strongduanmu @tuichenchuxin

**Comment by strongduanmu** [comment]
> All the SQLs (including union) routing to one sharding table can be executed well, right?
> @strongduanmu @tuichenchuxin

@tristaZero Union and union all is not supported now. The SQL execution routed to a single node needs to be continued.

**Comment by tuichenchuxin** [comment]
I want to fix it.

**Comment by Yule-Momoko** [comment]
Will it be fixed in the next version？

**Comment by strongduanmu** [comment]
> Will it be fixed in the next version？

@Yule-Momoko Yes, it will be fixed later. You are welcome to help test it.
