### ISSUE TITLE
getTables should not use com.google.common.base.Function

### ISSUE THREAD

**Issue by klniu** [apache/shardingsphere#11384]
## Bug Report
ShardingRule.java using  
```java
return tableRules.stream().map((Function<TableRule, String>) TableRule::getLogicTable).collect(Collectors.toList());
```
will cause exception as following:

```
Caused by: java.lang.IncompatibleClassChangeError: vtable stub
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.apache.shardingsphere.sharding.rule.ShardingRule.getTables(ShardingRule.java:532)
	at org.apache.shardingsphere.sharding.rule.ShardingRule.getExcludedTables(ShardingRule.java:187)
	at org.apache.shardingsphere.sharding.rule.ShardingRule.<init>(ShardingRule.java:127)
	at org.apache.shardingsphere.sharding.rule.builder.AlgorithmProvidedShardingRuleBuilder.build(AlgorithmProvidedShardingRuleBuilder.java:37)
	at org.apache.shardingsphere.sharding.rule.builder.AlgorithmProvidedShardingRuleBuilder.build(AlgorithmProvidedShardingRuleBuilder.java:33)
	at org.apache.shardingsphere.infra.rule.builder.ShardingSphereRulesBuilder.lambda$buildSchemaRules$0(ShardingSphereRulesBuilder.java:66)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.apache.shardingsphere.infra.rule.builder.ShardingSphereRulesBuilder.buildSchemaRules(ShardingSphereRulesBuilder.java:66)
	at org.apache.shardingsphere.infra.context.metadata.MetaDataContextsBuilder.buildMetaData(MetaDataContextsBuilder.java:99)
	at org.apache.shardingsphere.infra.context.metadata.MetaDataContextsBuilder.build(MetaDataContextsBuilder.java:90)
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.<init>(ShardingSphereDataSource.java:55)
	at org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactory.createDataSource(ShardingSphereDataSourceFactory.java:49)
	at org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration.shardingSphereDataSource(ShardingSphereAutoConfiguration.java:73)
	at org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration$$EnhancerBySpringCGLIB$$3025d7db.CGLIB$shardingSphereDataSource$0(<generated>)
	at org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration$$EnhancerBySpringCGLIB$$3025d7db$$FastClassBySpringCGLIB$$516d3ef6.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration$$EnhancerBySpringCGLIB$$3025d7db.shardingSphereDataSource(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 71 common frames omitted
```
### Which version of ShardingSphere did you use?
5.0.0-beta or matster

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 

### Expected behavior
ShardingRule.java

```java
 @Override
    public Collection<String> getTables() {
        return tableRules.stream().map(TableRule::getLogicTable).collect(Collectors.toList());
    }
```

### Actual behavior
ShardingRule.java
```java
    @Override
    public Collection<String> getTables() {
        return tableRules.stream().map((Function<TableRule, String>) TableRule::getLogicTable).collect(Collectors.toList());
    }
```

**Comment by tristaZero** [comment]
Hi @klniu ,
You debugged it, looks nice. Would you like to raise a PR to fix this issue? It's not difficult, isn't it?
[How to raise a PR](https://shardingsphere.apache.org/community/cn/contribute/contributor/) will give you a hand.

**Comment by klniu** [comment]
ok, thanks, I will do it.

The problem is that the Java Stream Map method only requires java.util.Function, and does not require cast. Just using Lambda function is fine. 

However, the addition of a forced conversion and the import com.google.common.base.Function by mistake caused the exception.
