### ISSUE TITLE
Protocol incompatibility between ShardingSphere-proxy and Tbase

### ISSUE THREAD

**Issue by changming8** [apache/shardingsphere#11474]
## Bug Report
We use the TBase database, and we use shardingSphere-proxy as database middleware. After the proxy is successfully deployed, there is no exception, but the application side reports a protocol error:

WARN operator.DBPreProc [331] : Reconnect database after 10 seconds due to the following error: Protocol error. Session setup failed.

21/07/23 14:57:14 WARN operator.DBPreProc [331] : Reconnect database after 10 seconds due to the following error: Protocol error. Session setup failed.

21/07/23 14:57:24 INFO core.Engine [532] : ----> Current job status: JOB_INITIALIZER_FAIL(32)

21/07/23 14:57:24 ERROR core.Engine [576] : Job init error detected, status = JOB_INITIALIZER_FAIL

21/07/23 14:57:24 ERROR core.Engine [146] : Fail to call job initializer .

java.lang.Exception: java.sql.SQLException: Failed to connect database after retry 3 times.

at com.tencent.teg.dc.dx.operator.DBPreProc.doInit(DBPreProc.java:34)

at com.tencent.teg.dc.dx.core.Engine.startEngine(Engine.java:140)

at com.tencent.teg.dc.dx.core.AnyLoader.startJob(AnyLoader.java:250)

at com.tencent.teg.dc.dx.core.AnyLoader.main(AnyLoader.java:115)

at com.tencent.teg.dc.dx.core.Launcher.main(Launcher.java:11)

Caused by: java.sql.SQLException: Failed to connect database after retry 3 times.

at com.tencent.teg.dc.dx.utils.DxDBUtils.getConnectionFailover(DxDBUtils.java:329)

at com.tencent.teg.dc.dx.operator.DBPreProc.doInit(DBPreProc.java:31)

... 4 more

Caused by: org.postgresql.util.PSQLException: Protocol error. Session setup failed.

at org.postgresql.core.v3.ConnectionFactoryImpl.readStartupMessages(ConnectionFactoryImpl.java:496)

at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:112)

at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)

at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)

at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)

at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)

at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:30)

at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)

How to solve it?

**Comment by changming8** [comment]
It's OK to replace with a higher version of PG driver. Proxy is incompatible with postgresql-9. X driver
