### ISSUE TITLE
Why is the NACOS config center implemented but no registry?

### ISSUE THREAD

**Issue by chenjia123** [apache/shardingsphere#11470]
## Aim: Try using nacos instead of ZK 

I use the following configuration file:
```yaml
# server.yaml
orchestration:
  orchestration_ds:
    orchestrationType: registry_center,config_center,distributed_lock_manager
    instanceType: nacos
    serverLists: http://localhost:8848
    namespace: orchestration
```
However, it does not take effect and has an exception:
```
Exception in thread "main" java.lang.RuntimeException: Invalid `org.apache.shardingsphere.orchestration.center.RegistryCenterRepository` SPI type `nacos`.
	at org.apache.shardingsphere.spi.TypeBasedSPIServiceLoader.newService(TypeBasedSPIServiceLoader.java:46)
	at org.apache.shardingsphere.orchestration.core.registrycenter.RegistryCenterRepositoryServiceLoader.load(RegistryCenterRepositoryServiceLoader.java:49)
	at org.apache.shardingsphere.orchestration.core.facade.ShardingOrchestrationFacade.<init>(ShardingOrchestrationFacade.java:69)
	at org.apache.shardingsphere.shardingproxy.Bootstrap.startWithRegistryCenter(Bootstrap.java:131)
	at org.apache.shardingsphere.shardingproxy.Bootstrap.main(Bootstrap.java:87)
```

And then I found this:
![image](https://user-images.githubusercontent.com/22190625/126754498-0ded461a-4ab0-4e80-ac92-aac14d732926.png)

So,
- Why is this project(sharding-orchestration-center-nacos) incomplete? The RegistryCenterRepository interface is not implemented.
- Isn't NACOS suitable for the registry?
- Why do we need a registry in a sharding-proxy? In some instances,I think just need the config center.

Thanks!

**Comment by terrymanu** [comment]
Reg center need to ephemeral or TTL, only ZooKeeper and etcd can support the feature.
So NACOS  has been removed from version 5.x.
