### ISSUE TITLE
ERROR 1815 (HY000): Internal error

### ISSUE THREAD

**Issue by bai1986** [apache/shardingsphere#11671]
When I execute the following SQL in the apache-shardingsphere-5.0.0-RC1-SNAPSHOT-shardingsphere-proxy-bin, the following error is reported：
    select product_id, apply_id from coupon_activity_map     inner join coupon_products_map  on coupon_activity_map.coupon_apply_id = coupon_products_map.apply_id             where product_id in (1900080401,100022,20468821) and coupon_activity_map.activity_end_date > '2021-08-03 10:39:11';

ERROR 1815 (HY000): Internal error: exception while executing query: class java.sql.Timestamp cannot be cast to class java.lang.Long (java.sql.Timestamp is in module java.sql of loader 'platform'; java.lang.Long is in module java.base of loader 'bootstrap')

the proxy logs as follows:
Caused by: java.lang.ClassCastException: class java.sql.Timestamp cannot be cast to class java.lang.Long (java.sql.Timestamp is in module java.sql of loader 'platform'; java.lang.Long is in module java.base of loader 'bootstrap')
        at Buzz.execute(Unknown Source)
        at Buzz.execute(Unknown Source)
        at org.apache.calcite.interpreter.TableScanNode.lambda$createEnumerable$1(TableScanNode.java:270)
        at org.apache.calcite.linq4j.EnumerableDefaults$28.moveNext(EnumerableDefaults.java:3667)
        at org.apache.calcite.linq4j.TransformedEnumerator.moveNext(TransformedEnumerator.java:35)
        at org.apache.calcite.linq4j.EnumerableDefaults.toLookup_(EnumerableDefaults.java:3563)
        at org.apache.calcite.linq4j.EnumerableDefaults$14.enumerator(EnumerableDefaults.java:2621)
        at org.apache.calcite.linq4j.EnumerableDefaults$MergeJoinEnumerator.getLeftEnumerator(EnumerableDefaults.java:4137)
        at org.apache.calcite.linq4j.EnumerableDefaults$MergeJoinEnumerator.leftMoveNext(EnumerableDefaults.java:4153)
        at org.apache.calcite.linq4j.EnumerableDefaults$MergeJoinEnumerator.start(EnumerableDefaults.java:4174)
        at org.apache.calcite.linq4j.EnumerableDefaults$MergeJoinEnumerator.<init>(EnumerableDefaults.java:4132)
        at org.apache.calcite.linq4j.EnumerableDefaults$13.enumerator(EnumerableDefaults.java:2187)
        at Baz$7$1.<init>(Unknown Source)
        at Baz$7.enumerator(Unknown Source)
        at org.apache.calcite.linq4j.AbstractEnumerable.iterator(AbstractEnumerable.java:33)
        at org.apache.calcite.avatica.MetaImpl.createCursor(MetaImpl.java:90)
        at org.apache.calcite.avatica.AvaticaResultSet.execute(AvaticaResultSet.java:184)
        at org.apache.calcite.jdbc.CalciteResultSet.execute(CalciteResultSet.java:64)
        at org.apache.calcite.jdbc.CalciteResultSet.execute(CalciteResultSet.java:43)
        at org.apache.calcite.avatica.AvaticaConnection.executeQueryInternal(AvaticaConnection.java:573)
        ... 16 common frames omitted

**Comment by taojintianxia** [comment]
hi , there . would you please paste your proxy configuration here ?

**Comment by bai1986** [comment]
config-sharding.yaml
schemaName: ProductDB

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/ProductDB00?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=GBK&character_set_server= gbk&connectionCollation=gbk_bin
    username: shardingsphere
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/ProductDB01?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=GBK&character_set_server= gbk&connectionCollation=gbk_bin
    username: shardingsphere
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_2:
    url: jdbc:mysql://127.0.0.1:3306/ProductDB02?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=GBK&character_set_server= gbk&connectionCollation=gbk_bin
    username: shardingsphere
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_3:
    url: jdbc:mysql://127.0.0.1:3306/ProductDB03?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=GBK&character_set_server= gbk&connectionCollation=gbk_bin
    username: shardingsphere
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_4:
    url: jdbc:mysql://127.0.0.1:3306/ProductDB04?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=GBK&character_set_server= gbk&connectionCollation=gbk_bin
    username: shardingsphere
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_5:
    url: jdbc:mysql://127.0.0.1:3306/ProductDB05?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=GBK&character_set_server= gbk&connectionCollation=gbk_bin
    username: shardingsphere
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_6:
    url: jdbc:mysql://127.0.0.1:3306/ProductDB06?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=GBK&character_set_server= gbk&connectionCollation=gbk_bin
    username: shardingsphere
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_7:
    url: jdbc:mysql://127.0.0.1:3306/ProductDB07?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=GBK&character_set_server= gbk&connectionCollation=gbk_bin
    username: shardingsphere
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
  - !SHARDING
    tables:
      Products_Core:
        actualDataNodes: ds_${0..7}.Products_Core
        keyGenerateStrategy:
          column: id
          keyGeneratorName: snowflake
        databaseStrategy:
          standard:
            shardingColumn: product_id
            shardingAlgorithmName: product_core_database_inline
      products_ddshop_category:
        actualDataNodes: ds_${0..7}.products_ddshop_category
        keyGenerateStrategy:
          column: id
          keyGeneratorName: snowflake
        databaseStrategy:
          standard:
            shardingColumn: id
            shardingAlgorithmName: ddshop_database_inline
      mytest:
        actualDataNodes: ds_0.mytest
      coupon_products_map:
        actualDataNodes: ds_4.coupon_products_map
    defaultDatabaseStrategy:
      none:
    defaultTableStrategy:
      none:

    shardingAlgorithms:
      product_core_database_inline:
        type: INLINE
        props:
          algorithm-expression: ds_${product_id % 7}
      ddshop_database_inline:
        type: INLINE
        props:
          algorithm-expression: ds_${id % 7}

    keyGenerators:
      snowflake:
        type: SNOWFLAKE
        props:
          worker-id: 123

**Comment by strongduanmu** [comment]
@bai1986 Thank you for your feedback, tis issue is duplicated with #10760. And we will fix it later.
