### ISSUE TITLE
Proxy can't route 'select ... for update' to the writeable node

### ISSUE THREAD

**Issue by cqiwencom** [apache/shardingsphere#11746]
### Which version of ShardingSphere did you use?
ShardingSphere-Proxy 5.0.0-beta

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
When executing 'select ... for update' , the select statement should be routed to the writable node.

### Actual behavior
When executing 'select ... for update' , the select statement was routed to the readable node.

### Reason analyze (If you can)
Proxy can't route 'select ... for update' to the writeable node

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

schemaName: testdb

dataSources:
  write_ds:
    url: jdbc:mysql://127.0.0.1:6446/testdb?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  read_ds_0:
    url: jdbc:mysql://127.0.0.1:6447/testdb?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !READWRITE_SPLITTING
  dataSources:
    pr_ds:
      writeDataSourceName: write_ds
      readDataSourceNames:
        - read_ds_0

When executing 'select ... for update' , the select statement was routed to read_ds_0. But in fact, this select statement should be routed to node write_ds.

**Comment by strongduanmu** [comment]
@cqiwencom Can you try the master branch? I used the master branch to test and the routing results were normal.

```
[INFO ] 2021-08-11 11:53:59.301 [ShardingSphere-Command-1] ShardingSphere-SQL - Logic SQL: select * from actor for update
[INFO ] 2021-08-11 11:53:59.301 [ShardingSphere-Command-1] ShardingSphere-SQL - SQLStatement: MySQLSelectStatement(limit=Optional.empty, lock=Optional[org.apache.shardingsphere.sql.parser.sql.common.segment.dml.predicate.LockSegment@137e13b5], window=Optional.empty)
[INFO ] 2021-08-11 11:53:59.301 [ShardingSphere-Command-1] ShardingSphere-SQL - Actual SQL: write_ds ::: select * from actor for update
```

**Comment by cqiwencom** [comment]
> @cqiwencom Can you try the master branch? I used the master branch to test and the routing results were normal.
> 
> ```
> [INFO ] 2021-08-11 11:53:59.301 [ShardingSphere-Command-1] ShardingSphere-SQL - Logic SQL: select * from actor for update
> [INFO ] 2021-08-11 11:53:59.301 [ShardingSphere-Command-1] ShardingSphere-SQL - SQLStatement: MySQLSelectStatement(limit=Optional.empty, lock=Optional[org.apache.shardingsphere.sql.parser.sql.common.segment.dml.predicate.LockSegment@137e13b5], window=Optional.empty)
> [INFO ] 2021-08-11 11:53:59.301 [ShardingSphere-Command-1] ShardingSphere-SQL - Actual SQL: write_ds ::: select * from actor for update
> ```

在我的日志文件中没有看到您上面的这种信息。但有如下的报错信息显示在日志中：

[ERROR] 2021-08-12 12:31:20.828 [Connection-3-ThreadExecutor] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
java.lang.ClassCastException: org.apache.shardingsphere.sql.parser.sql.common.segment.dml.expr.BinaryOperationExpression cannot be cast to org.apache.shardingsphere.sql.parser.sql.common.statement.SQLStatement
	at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserExecutor.parse(SQLStatementParserExecutor.java:47)
	at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserEngine.parse(SQLStatementParserEngine.java:48)
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine.parse0(ShardingSphereSQLParserEngine.java:67)
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine.parse(ShardingSphereSQLParserEngine.java:56)
	at org.apache.shardingsphere.proxy.backend.text.TextProtocolBackendHandlerFactory.newInstance(TextProtocolBackendHandlerFactory.java:86)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.<init>(MySQLComQueryPacketExecutor.java:52)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecutorFactory.newInstance(MySQLCommandExecutorFactory.java:73)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandExecutor(MySQLCommandExecuteEngine.java:60)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:96)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by tristaZero** [comment]
@strongduanmu Hi any progress?

@cqiwencom thanks for your attention, I can see your many activities these days. Are you testing ShardingProxy?

**Comment by strongduanmu** [comment]
@cqiwencom From your log, it looks like a parsing exception, not a readwrite splitting exception. Can you try the master branch?

**Comment by cqiwencom** [comment]
> @strongduanmu Hi any progress?
> 
> @cqiwencom thanks for your attention, I can see your many activities these days. Are you testing ShardingProxy?

Yes,i do.

**Comment by tristaZero** [comment]
@cqiwencom Could you pull the latest commit from the master branch and give it a test? Look forward to your reply, thanks.

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 30 days, we will close it. 
If you still have related questions, please submit a new issue, thank you.
