### ISSUE TITLE
springboot project Used shardingsphere-jdbc and  Flyway:  throw ShardingSphereException `global_variables` single table does not exist

### ISSUE THREAD

**Issue by dyplus** [apache/shardingsphere#11771]
![image](https://user-images.githubusercontent.com/54160389/129017482-f9fa98a0-5dc8-4446-b93e-5e1d4b6d84cc.png)

implementation('org.apache.shardingsphere:shardingsphere-jdbc-core-spring-boot-starter:5.0.0-beta')

**Comment by tristaZero** [comment]
Hi @dyplus Thanks for your issue. could you provide your SQL triggering this issue?

**Comment by coolbeevip** [comment]
Same issue

```
select VARIABLE_VALUE from performance_schema.global_variables where variable_name = 'pxc_strict_mode'
```

**Comment by tristaZero** [comment]
@lanchengx Hi could you look at this sql for our client's adapting work?

**Comment by jinkun2014** [comment]
Caused by: org.apache.shardingsphere.infra.exception.ShardingSphereException: `global_variables` single table does not exist.
	at org.apache.shardingsphere.sharding.route.engine.type.single.SingleTablesRoutingEngine.fillRouteContext(SingleTablesRoutingEngine.java:80)
	at org.apache.shardingsphere.sharding.route.engine.type.single.SingleTablesRoutingEngine.route(SingleTablesRoutingEngine.java:59)
	at org.apache.shardingsphere.sharding.route.engine.ShardingSQLRouter.createRouteContext(ShardingSQLRouter.java:61)
	at org.apache.shardingsphere.sharding.route.engine.ShardingSQLRouter.createRouteContext(ShardingSQLRouter.java:47)
	at org.apache.shardingsphere.infra.route.engine.impl.PartialSQLRouteExecutor.route(PartialSQLRouteExecutor.java:62)
	at org.apache.shardingsphere.infra.route.engine.SQLRouteEngine.route(SQLRouteEngine.java:52)
	at org.apache.shardingsphere.infra.context.kernel.KernelProcessor.route(KernelProcessor.java:54)
	at org.apache.shardingsphere.infra.context.kernel.KernelProcessor.generateExecutionContext(KernelProcessor.java:46)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.createExecutionContext(ShardingSpherePreparedStatement.java:363)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.executeQuery(ShardingSpherePreparedStatement.java:178)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.queryForString(JdbcTemplate.java:197)
	at org.flywaydb.core.internal.database.mysql.MySQLDatabase.isRunningInPerconaXtraDBClusterWithStrictMode(MySQLDatabase.java:79)
	at org.flywaydb.core.internal.database.mysql.MySQLDatabase.<init>(MySQLDatabase.java:61)
	at org.flywaydb.core.internal.database.mysql.MySQLDatabaseType.createDatabase(MySQLDatabaseType.java:109)
	at org.flywaydb.core.internal.database.base.BaseDatabaseType.createDatabase(BaseDatabaseType.java:141)
	at org.flywaydb.core.Flyway.execute(Flyway.java:545)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:172)
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
	... 19 common frames omitted

**Comment by strongduanmu** [comment]
@jinkun2014 Can you try the master branch? We support `performance_schema` query when using Proxy in the master branch.

**Comment by terrymanu** [comment]
Closed because of no response anymore.

**Comment by lanchengx** [comment]
@jinkun2014 Sorry for not replying in time, `performance_schema` is not supported yet, we will improve it as soon as possible.
