### ISSUE TITLE
ShardingSphere cannot resolve information_schema

### ISSUE THREAD

**Issue by rfscouto** [apache/shardingsphere#11992]
Using ShardingSphere 5.0.0-RC1-SNAPSHOT, Hibernate Core 5.4.18.

```
     - SPRING_JPA_DATABASE=POSTGRESQL
     - SPRING_JPA_HIBERNATE_DDL-AUTO=update
     - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.PostgreSQL9Dialect
     - SPRING_JPA_PROPERTIES_HIBERNATE_TEMP_USE_JDBC_METADATA_DEFAULTS=false
     - SPRING_JPA_PROPERTIES_HIBERNATE_TEMP_USE_JDBC_LOB_NON_CONTEXTUAL_CREATION=true
     - SPRING_JPA_PROPERTIES_OPEN-IN-VIEW=false
     - SPRING_LIQUIBASE_DEFAULT-SCHEMA=public
     - SPRING_SHARDINGSPHERE_ENABLED=false
     - SPRING_SHARDINGSPHERE_ALTERNATEIMPL=true
     - SPRING_SHARDINGSPHERE_SCHEMANAME=public
     - SPRING_SHARDINGSPHERE_DATASOURCE_NAMES=testdatasource
     - SPRING_SHARDINGSPHERE_DATASOURCE_testdatasource_TYPE=com.zaxxer.hikari.HikariDataSource
     - SPRING_SHARDINGSPHERE_DATASOURCE_testdatasource_DRIVER-CLASS-NAME=org.postgresql.Driver
     - SPRING_SHARDINGSPHERE_DATASOURCE_testdatasource_JDBC-URL=${DATASOURCE_URL}
     - SPRING_SHARDINGSPHERE_DATASOURCE_testdatasource_URL=${DATASOURCE_URL}
     - SPRING_SHARDINGSPHERE_DATASOURCE_testdatasource_USERNAME=${DATASOURCE_USERNAME}
     - SPRING_SHARDINGSPHERE_DATASOURCE_testdatasource_PASSWORD=${DATASOURCE_PASSWORD}
     - SPRING_SHARDINGSPHERE_DATASOURCE_testdatasource_SCHEMA=public
     - SPRING_SHARDINGSPHERE_SHARDING_TABLES_MAIN_ACTUAL-DATA-NODES=testdatasource.main$->{0..1}
     - SPRING_SHARDINGSPHERE_SHARDING_TABLES_MAIN_TABLE-STRATEGY_INLINE_SHARDING-COLUMN=id
     - SPRING_SHARDINGSPHERE_SHARDING_TABLES_MAIN_TABLE-STRATEGY_INLINE_ALGORITHM-EXPRESSION=main$->{id}
     - SPRING_SHARDINGSPHERE_SHARDING_TABLES_MAIN_KEY-GENERATOR_COLUMN=id
     - SPRING_SHARDINGSPHERE_SHARDING_TABLES_MAIN_KEY-GENERATOR_TYPE=UUID
```

When hibernate is initialising, it can't access the information_schema to access sequences: 

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.apache.shardingsphere.infra.exception.SchemaNotExistedException: Schema 'information_schema' doesn't exist.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at main.main(mainQuery.java:15)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.apache.shardingsphere.infra.exception.SchemaNotExistedException: Schema 'information_schema' doesn't exist.
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:403)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:378)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792)
	... 23 common frames omitted
Caused by: org.apache.shardingsphere.infra.exception.SchemaNotExistedException: Schema 'information_schema' doesn't exist.
	at org.apache.shardingsphere.infra.binder.statement.dml.SelectStatementContext.getSchema(SelectStatementContext.java:107)
	at org.apache.shardingsphere.infra.binder.statement.dml.SelectStatementContext.<init>(SelectStatementContext.java:92)
	at org.apache.shardingsphere.infra.binder.SQLStatementContextFactory.getDMLStatementContext(SQLStatementContextFactory.java:125)
	at org.apache.shardingsphere.infra.binder.SQLStatementContextFactory.newInstance(SQLStatementContextFactory.java:108)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.createLogicSQL(ShardingSphereStatement.java:365)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.createExecutionContext(ShardingSphereStatement.java:372)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.executeQuery(ShardingSphereStatement.java:146)
	at io.opentracing.contrib.jdbc.TracingStatement.executeQuery(TracingStatement.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.opentracing.contrib.common.WrapperProxy$1.invoke(WrapperProxy.java:73)
	at com.sun.proxy.$Proxy207.executeQuery(Unknown Source)
	at org.hibernate.tool.schema.extract.internal.SequenceInformationExtractorLegacyImpl.extractMetadata(SequenceInformationExtractorLegacyImpl.java:42)
	at org.hibernate.tool.schema.extract.internal.DatabaseInformationImpl.initializeSequences(DatabaseInformationImpl.java:65)
	at org.hibernate.tool.schema.extract.internal.DatabaseInformationImpl.<init>(DatabaseInformationImpl.java:59)
	at org.hibernate.tool.schema.internal.Helper.buildDatabaseInformation(Helper.java:155)
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.doMigration(AbstractSchemaMigrator.java:96)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:184)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:73)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:314)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:468)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1237)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:391)
	... 27 common frames omitted
```

<img width="1753" alt="Screenshot 2021-08-24 at 21 35 36" src="https://user-images.githubusercontent.com/2998542/130679111-385509c2-c82b-4623-9d61-25ec965f1e63.png">

The initialised metadata only contains, in fact, the public schema. 
Is this somehow connected to https://github.com/apache/shardingsphere/issues/6693?

**Comment by RaigorJiang** [comment]
Yes, the query to `information_schema` is currently not supported, it is under planning, please pay attention to follow-up updates, thanks!

**Comment by sandynz** [comment]
Since #11994 is in progress, I'll close it now.
