### ISSUE TITLE
SqlValidatorException for ShardingSphere-5.0.0-beta: No match found for function signature ifnull

### ISSUE THREAD

**Issue by trycache-npe-lab** [apache/shardingsphere#12049]
## Bug Report

org.apache.calcite.sql.validate.SqlValidatorException: No match found for function signature ifnull(<CHARACTER>, <CHARACTER>)

### Which version of ShardingSphere did you use?

ShardingSphere-5.0.0-beta

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC 

### Expected behavior

org.apache.calcite.sql.validate.SqlValidatorException: No match found for function signature ifnull(<CHARACTER>, <CHARACTER>)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

### Actual behavior

SQL syntax parsing is normal

### Reason analyze (If you can)

SQL syntax parsing is not supported

### Example codes for reproduce this issue (such as a github link).

SELECT ifnull( t3.name, '' ) AS actUser FROM auser t3

**Comment by avalon5666** [comment]
Related #11437.

**Comment by trycache0828** [comment]
> Related #11437.

## I have encountered a new problem. Is it a paging query proble?

	java.lang.AssertionError: not a literal: ?0
		at org.apache.calcite.rex.RexLiteral.findValue(RexLiteral.java:1174)
		at org.apache.calcite.rex.RexLiteral.intValue(RexLiteral.java:1149)
		at org.apache.calcite.rel.metadata.RelMdUtil.checkInputForCollationAndLimit(RelMdUtil.java:886)
		at org.apache.calcite.rel.rules.SortJoinTransposeRule.onMatch(SortJoinTransposeRule.java:135)
		at org.apache.calcite.plan.volcano.VolcanoRuleCall.onMatch(VolcanoRuleCall.java:229)
		at org.apache.calcite.plan.volcano.IterativeRuleDriver.drive(IterativeRuleDriver.java:58)
		at org.apache.calcite.plan.volcano.VolcanoPlanner.findBestExp(VolcanoPlanner.java:510)
		at org.apache.calcite.tools.Programs.lambda$standard$3(Programs.java:271)
		at org.apache.calcite.tools.Programs$SequenceProgram.run(Programs.java:331)
		at org.apache.calcite.prepare.Prepare.optimize(Prepare.java:166)
		at org.apache.calcite.prepare.Prepare.prepareSql(Prepare.java:297)
		at org.apache.calcite.prepare.Prepare.prepareSql(Prepare.java:208)
		at org.apache.calcite.prepare.CalcitePrepareImpl.prepare2_(CalcitePrepareImpl.java:642)
		at org.apache.calcite.prepare.CalcitePrepareImpl.prepare_(CalcitePrepareImpl.java:508)

**Comment by trycache0905** [comment]
您好！    您的邮件已收到，我会尽快处理！谢谢！    顺祝：工作顺利！

**Comment by RaigorJiang** [comment]
This issue has been inactive for too long, and ShardingSphere has released several new versions, so I will close it.
Users are advised to try the latest version, and if the problem reproduces, please reopen it or submit a new one.

**Comment by trycache-npe-lab** [comment]
您好！    您的邮件已收到，我会尽快处理！谢谢！    顺祝：工作顺利！
