### ISSUE TITLE
run sharding proxy succeed, but  connect proxydb error

### ISSUE THREAD

**Issue by dengjin001** [apache/shardingsphere#12078]
proxy log:
 ``[ERROR] 2021-08-28 16:16:54.552 [638410870044491777_Worker-1] o.a.s.e.e.h.g.LogJobErrorHandler - Job '638410870044491777' exception occur in job processing
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Access denied for user 'root'@'127.0.0.1' to database 'sharding_db'
        at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:589)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:575)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at org.apache.shardingsphere.scaling.core.config.datasource.StandardJDBCDataSourceConfiguration.toDataSource(StandardJDBCDataSourceConfiguration.java:89)
        at org.apache.shardingsphere.scaling.core.common.datasource.DataSourceFactory.newInstance(DataSourceFactory.java:38)
        at org.apache.shardingsphere.scaling.core.common.datasource.DataSourceManager.createTargetDataSources(DataSourceManager.java:67)
        at org.apache.shardingsphere.scaling.core.common.datasource.DataSourceManager.createDataSources(DataSourceManager.java:54)
        at org.apache.shardingsphere.scaling.core.common.datasource.DataSourceManager.<init>(DataSourceManager.java:49)
        at org.apache.shardingsphere.scaling.core.job.preparer.ScalingJobPreparer.prepare(ScalingJobPreparer.java:52)
        at org.apache.shardingsphere.scaling.core.job.ScalingJob.execute(ScalingJob.java:47)
        at org.apache.shardingsphere.elasticjob.simple.executor.SimpleJobExecutor.process(SimpleJobExecutor.java:33)
        at org.apache.shardingsphere.elasticjob.simple.executor.SimpleJobExecutor.process(SimpleJobExecutor.java:29)
        at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.process(ElasticJobExecutor.java:177)
        at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.process(ElasticJobExecutor.java:147)
        at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.execute(ElasticJobExecutor.java:130)
        at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.execute(ElasticJobExecutor.java:106)
        at org.apache.shardingsphere.elasticjob.lite.internal.schedule.LiteJob.execute(LiteJob.java:35)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'root'@'127.0.0.1' to database 'sharding_db'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.Util.getInstance(Util.java:408)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
        at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2199)
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2230)
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2025)
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778)
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:354)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:554)
        ... 18 common frames omitted ``

cmd  can connect  mysql  but command 'show batabases' errer:
![image](https://user-images.githubusercontent.com/29300542/131211512-e62118dd-ed09-4eb1-b309-893be70de2e8.png)

**Comment by terrymanu** [comment]
What is `proxydb` and which version did you use?

**Comment by dengjin001** [comment]
> 您使用什么版本？`proxydb`

sharding -proxy 5.0.0-beta

**Comment by tristaZero** [comment]
> Failed to initialize pool: Access denied for user 'root'@'127.0.0.1' to database 'sharding_db' at

Hi @dengjin001 
The log showed that it's about privileges. Could you give it a check?

**Comment by dengjin001** [comment]
> > Failed to initialize pool: Access denied for user 'root'@'127.0.0.1' to database 'sharding_db' at
> 
> Hi @dengjin001
> The log showed that it's about privileges. Could you give it a check?

i only start sharding-proxy, use mysql -client  connection,  mysql command show error.
use navicat connection, although test connection is ok, but can't open this database.

![image](https://user-images.githubusercontent.com/29300542/131676091-40d9e774-f90a-4bb2-bf3a-926cabdd661e.png)

![image](https://user-images.githubusercontent.com/29300542/131676967-844adaef-0851-4459-9d04-4939f4bc6b72.png)

![image](https://user-images.githubusercontent.com/29300542/131676807-fb96daa9-8672-425e-8d7e-ec8056269a24.png)

**Comment by dengjin001** [comment]
actual database is  Alibaba RDS,  It looks like it issue the same problem.  [https://github.com/apache/shardingsphere/issues/11550](url)

**Comment by RaigorJiang** [comment]
Hi @dengjin001 
Is your problem solved?

**Comment by tristaZero** [comment]
Hi @dengjin001 could you try the master branch?

**Comment by dengjin001** [comment]
> Hi @dengjin001 could you try the master branch?

using latest master branch, server.yaml use default setting,  mysql client show 'Access denied for user 'root'@'127.0.0.1' , Alibaba RDS can not create ''root' and 'sharding' account

**Comment by RaigorJiang** [comment]
What about change the user configuration in server.yaml to match your account in Alibaba RDS?

**Comment by dengjin001** [comment]
> What about change the user configuration in server.yaml to match your account in Alibaba RDS?

server.yaml use  Alibaba RDS account is ok

**Comment by tristaZero** [comment]
@dengjin001 Do you use the sharding feature in RDS? ShardingProxy or ShardingJDBC?

**Comment by RaigorJiang** [comment]
> @dengjin001 Do you use the sharding feature in RDS? ShardingProxy or ShardingJDBC?

ShardingProxy.
