### ISSUE TITLE
5.0 version doesn't support IDENTITY_COLUMN for oracle 11g

### ISSUE THREAD

**Issue by 15935561673** [apache/shardingsphere#12122]
Caused by: java.sql.SQLSyntaxErrorException: ORA-00904: "IDENTITY_COLUMN": 标识符无效

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:445) ~[ojdbc6-11.2.0.3.jar:11.2.0.3.0]
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396) ~[ojdbc6-11.2.0.3.jar:11.2.0.3.0]
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:879) ~[ojdbc6-11.2.0.3.jar:11.2.0.3.0]
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:450) ~[ojdbc6-11.2.0.3.jar:11.2.0.3.0]
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192) ~[ojdbc6-11.2.0.3.jar:11.2.0.3.0]
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531) ~[ojdbc6-11.2.0.3.jar:11.2.0.3.0]
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:207) ~[ojdbc6-11.2.0.3.jar:11.2.0.3.0]
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:884) ~[ojdbc6-11.2.0.3.jar:11.2.0.3.0]
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1167) ~[ojdbc6-11.2.0.3.jar:11.2.0.3.0]
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1289) ~[ojdbc6-11.2.0.3.jar:11.2.0.3.0]
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3584) ~[ojdbc6-11.2.0.3.jar:11.2.0.3.0]
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3628) ~[ojdbc6-11.2.0.3.jar:11.2.0.3.0]
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1493) ~[ojdbc6-11.2.0.3.jar:11.2.0.3.0]
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:3240) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_executeQuery(FilterEventAdapter.java:465) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:3237) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.executeQuery(PreparedStatementProxyImpl.java:181) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227) ~[druid-1.2.6.jar:1.2.6]
	at org.apache.shardingsphere.infra.metadata.schema.builder.loader.dialect.OracleTableMetaDataLoader.loadColumnMetaDataMap(OracleTableMetaDataLoader.java:83) ~[shardingsphere-infra-common-5.0.0-beta.jar:5.0.0-beta]
	at org.apache.shardingsphere.infra.metadata.schema.builder.loader.dialect.OracleTableMetaDataLoader.loadTableMetaDataMap(OracleTableMetaDataLoader.java:69) ~[shardingsphere-infra-common-5.0.0-beta.jar:5.0.0-beta]
	at org.apache.shardingsphere.infra.metadata.schema.builder.loader.dialect.OracleTableMetaDataLoader.load(OracleTableMetaDataLoader.java:64) ~[shardingsphere-infra-common-5.0.0-beta.jar:5.0.0-beta]
	at org.apache.shardingsphere.infra.metadata.schema.builder.SchemaBuilder.lambda$appendDialectRemainTables$1(SchemaBuilder.java:116) ~[shardingsphere-infra-common-5.0.0-beta.jar:5.0.0-beta]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[na:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]

**Comment by SteNicholas** [comment]
@15935561673 , do you have interest to support `IDENTITY_COLUMN` in Oracle syntax?

**Comment by tristaZero** [comment]
Hi could you set `sql-show` = true to get the detailed info?

**Comment by 15935561673** [comment]
> 嗨，您可以设置`sql-show`= true 以获取详细信息吗？
启动时出现的问题
。

**Comment by 15935561673** [comment]
> 嗨，您可以设置`sql-show`= true 以获取详细信息吗？
oracle出现的问题，换成mysql8.x版本一切正常

**Comment by sandynz** [comment]
Hi @15935561673 , are you still testing with Oracle? Could you get the execution failed SQL?

**Comment by terrymanu** [comment]
Closed because of no response anymore.
