### ISSUE TITLE
 ShardingSphere-JDBC 5.0.0-RC1-SNAPSHOT throws  SELECT command denied to user exception

### ISSUE THREAD

**Issue by coolbeevip** [apache/shardingsphere#12264]
### Which version of ShardingSphere did you use?

5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC 

### Actual behavior

```
Caused by: java.sql.SQLSyntaxErrorException: SELECT command denied to user 'dbuser0'@'172.19.0.1' for table 'user'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1200)
	at com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:111)
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java)
	at org.apache.shardingsphere.authority.provider.natived.builder.dialect.MySQLPrivilegeHandler.diff(MySQLPrivilegeHandler.java:61)
	at org.apache.shardingsphere.authority.provider.natived.builder.StoragePrivilegeBuilder.save(StoragePrivilegeBuilder.java:119)
	... 6 more
```

### Reason analyze (If you can)

5.0.0-beta worked

In 5.0.0-RC1-SNAPSHOT, Do I need database administrator privileges?

**Comment by RaigorJiang** [comment]
Hi @coolbeevip 
The reason is the default authority rule onfiguration `NATIVE` needs to query the mysql.user table, and the JDBC configuration user may not have this permission.
The solution is to adjust the default authority rule onfiguration to `ALL_PRIVILEGES_PERMITTED`.

I'm dealing with this problem, it will be fixed soon.
