### ISSUE TITLE
java.sql.Timestamp cannot be cast to java.lang.Number

### ISSUE THREAD

**Issue by kar1rose** [apache/shardingsphere#12286]
## Question

when I use join query with two databases, it will throw this error
`String sql = "select * from t_user t join p_order p on t.id = p.user_id ";
while (rs.next()) {
    for (int i = 1; i <= count; i++) {
        System.out.print(rs.getObject(i));
        if (i != count) {
            System.out.print("|");
        }
    }
    System.out.println();
}
`

`java.lang.ClassCastException: java.sql.Timestamp cannot be cast to java.lang.Number

	at org.apache.calcite.avatica.util.AbstractCursor$NumberAccessor.getNumber(AbstractCursor.java:722)
	at org.apache.calcite.avatica.util.AbstractCursor$TimestampFromNumberAccessor.getTimestamp(AbstractCursor.java:996)
	at org.apache.calcite.avatica.AvaticaSite.get(AvaticaSite.java:372)
	at org.apache.calcite.avatica.AvaticaResultSet.getObject(AvaticaResultSet.java:393)
	at org.apache.shardingsphere.infra.executor.sql.execute.result.query.impl.driver.jdbc.type.stream.JDBCStreamQueryResult.getValue(JDBCStreamQueryResult.java:87)
	at org.apache.shardingsphere.infra.merge.result.impl.stream.StreamMergedResult.getValue(StreamMergedResult.java:47)
	at org.apache.shardingsphere.driver.jdbc.core.resultset.ShardingSphereResultSet.getObject(ShardingSphereResultSet.java:359)`

it will cast timestamp to Number and error, if I just use single table query ,it's ok like this 
'String sql = "select * from t_user t ";'

**Comment by RaigorJiang** [comment]
@kar1rose 
What's your version of ShardingSphere?  
And please provide your configuration and the `Logic SQL` and `Actual SQL`, by set `props.sql-show` to `true`.

**Comment by kar1rose** [comment]
version was 5.0.0-beta 
`ShardingTableRuleConfiguration orderTableRuleConfig = new ShardingTableRuleConfiguration("t_user", "db${1}.user");
ShardingTableRuleConfiguration userTableRuleConfig = new ShardingTableRuleConfiguration("p_order", "db${2}.purchase_order");
ShardingRuleConfiguration shardingRuleConfig = new ShardingRuleConfiguration();
        shardingRuleConfig.getTables().add(orderTableRuleConfig);
        shardingRuleConfig.getTables().add(userTableRuleConfig);
Properties properties = new Properties();
        properties.setProperty("sql-show", "true");
try {
            dataSource = ShardingSphereDataSourceFactory.createDataSource(dataSourceMap, Collections.singleton(shardingRuleConfig), properties);
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
`
that's my configuration,I just want to test a Cross-database query 

> @kar1rose
> What's your version of ShardingSphere?
> And please provide your configuration and the `Logic SQL` and `Actual SQL`, by set `props.sql-show` to `true`.

**Comment by kar1rose** [comment]
sql print was such that 
2021-09-08 14:34:07 logback [main] INFO  ShardingSphere-SQL - Logic SQL: select * from t_user t join p_order p on t.id = p.user_id 
2021-09-08 14:34:07 logback [main] INFO  ShardingSphere-SQL - SQLStatement: MySQLSelectStatement(limit=Optional.empty, lock=Optional.empty, window=Optional.empty)
2021-09-08 14:34:07 logback [main] INFO  ShardingSphere-SQL - Actual SQL: db1 ::: select * from t_user t join p_order p on t.id = p.user_id 
2021-09-08 14:34:07 logback [main] INFO  ShardingSphere-SQL - Actual SQL: db2 ::: select * from t_user t join p_order p on t.id = p.user_id

**Comment by RaigorJiang** [comment]
Hi @kar1rose 
Looks like a problem with the field format, if you execute `select * from p_order p` separately, is it correct?

**Comment by RaigorJiang** [comment]
> Hi,
> It is always correct when I use single table query, like this
> 
> > id|order_name|goods_name|user_id|goods_id|amounts|amounts_d|datetime
> > 1|订单1|Iphone12|1|0|4999.22|4999.22|2021-09-08 16:37:25.0

This is a bit complicated and needs more time to investigate. 
If you can provide a demo project on github (include table structures), it can help us reproduce the problem more easily.

**Comment by kar1rose** [comment]
> > Hi,
> > It is always correct when I use single table query, like this
> > > id|order_name|goods_name|user_id|goods_id|amounts|amounts_d|datetime
> > > 1|订单1|Iphone12|1|0|4999.22|4999.22|2021-09-08 16:37:25.0
> 
> This is a bit complicated and needs more time to investigate.
> If you can provide a demo project on github (include table structures), it can help us reproduce the problem more easily.

https://github.com/kar1rose/sharding-jdbc-demo.git

ok ,eum you can test with the code ,thx

**Comment by RaigorJiang** [comment]
> ok ,eum you can test with the code ,thx
OK.

**Comment by RaigorJiang** [comment]
Hi @kar1rose 
I verified this problem. When getting the result of the `datetime` type, calcite uses the `timestamp` type to receive it. The problem occurs here.
![image](https://user-images.githubusercontent.com/5668787/132617359-e9753e62-8446-415d-8ed9-516bd07d3480.png)

@strongduanmu  Could you take a look?

**Comment by strongduanmu** [comment]
@kar1rose Thank you for your feedback, this issue is duplicated with #10760, and i will fix this exception before next release.
