### ISSUE TITLE
An error about starting sharding-proxy in version 5.0.0-beta

### ISSUE THREAD

**Issue by marker-wu** [apache/shardingsphere#12292]
Hello, I started sharding-proxy in version 5.0.0-beta and reported an error. The error message is as follows: 

Exception in thread "main" org.apache.shardingsphere.governance.repository.api.exception.GovernanceException: org.apache.zookeeper.KeeperException$OperationTimeoutException : KeeperErrorCode = OperationTimeout
at org.apache.shardingsphere.governance.repository.zookeeper.handler.CuratorZookeeperExceptionHandler.handleException(CuratorZookeeperExceptionHandler.java:51)
at org.apache.shardingsphere.governance.repository.zookeeper.CuratorZookeeperRepository.initCuratorClient(CuratorZookeeperRepository.java:127)
at org.apache.shardingsphere.governance.repository.zookeeper.CuratorZookeeperRepository.init(CuratorZookeeperRepository.java:81)
at org.apache.shardingsphere.governance.core.registry.RegistryCenterRepositoryFactory.newInstance(RegistryCenterRepositoryFactory.java:49)
at org.apache.shardingsphere.governance.core.GovernanceFacade.init(GovernanceFacade.java:58)
at org.apache.shardingsphere.proxy.initializer.impl.GovernanceBootstrapInitializer.getProxyConfiguration(GovernanceBootstrapInitializer.java:58)
at org.apache.shardingsphere.proxy.initializer.impl.AbstractBootstrapInitializer.init(AbstractBootstrapInitializer.java:66)
at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:48)
Caused by: org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
at org.apache.shardingsphere.governance.repository.zookeeper.CuratorZookeeperRepository.initCuratorClient(CuratorZookeeperRepository.java:124)
... 6 more

Please give me some solutions to the trouble, thank you

**Comment by RaigorJiang** [comment]
Hi @marker-wu
Please provide your configuration in `server.yaml`.

**Comment by marker-wu** [comment]
> Hi @marker-wu
> Please provide your configuration in `server.yaml`.
Hi：The content of my server.yaml is as follows：
governance:
  name: governance_ds
  registryCenter:
    type: ZooKeeper
    serverLists: 192.168.238.128:2181
    props:
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
  overwrite: false
rules:
  - !AUTHORITY
    users:
      - root@%:admin
      - sharding@:sharding
    provider:
      type: NATIVE

props:
  max-connections-size-per-query: 1
  executor-size: 16  # Infinite by default.
  proxy-frontend-flush-threshold: 128  # The default value is 128.
  proxy-transaction-type: LOCAL
  xa-transaction-manager-type: Atomikos
  proxy-opentracing-enabled: false
  proxy-hint-enabled: false
  sql-show: false
  check-table-metadata-enabled: false
  lock-wait-timeout-milliseconds: 50000 # The maximum time to wait for a lock
  show-process-list-enabled: false


The zookeeper address is correct and it is running normally

**Comment by marker-wu** [comment]
![image](https://user-images.githubusercontent.com/45256940/132610357-a2486099-3c42-44de-811a-ba09bfb3ed25.png)
![image](https://user-images.githubusercontent.com/45256940/132610366-bc1a02ee-488b-4253-97c7-d499471d1cf4.png)

**Comment by RaigorJiang** [comment]
@marker-wu 
The configuration format is correct, so the problem is still focused on ZK itself.
You said that ZK is running normally, so can other clients connect successfully from the Proxy machine? Is the firewall turned off?

**Comment by marker-wu** [comment]
I can use the ZK client to connect to the ZK server, but the sharding-proxy cannot be connected
Yes, the firewall is turned off
![image](https://user-images.githubusercontent.com/45256940/132612237-e8d260b9-0dc0-4b62-8c12-ed746ef8f032.png)

**Comment by RaigorJiang** [comment]
Um. . Strange question
Since no one has ever reported that they cannot connect to ZK, consider changing to a different environment?

**Comment by marker-wu** [comment]
Does it have anything to do with the version of ZK? The latest version I installed from docker

**Comment by RaigorJiang** [comment]
> Does it have anything to do with the version of ZK? The latest version I installed from docker

Which docker image do you use, could you give the docker hub link please?

**Comment by marker-wu** [comment]
https://github.com/31z4/zookeeper-docker/blob/10a34d67458bd30a4f334166860d8213f84e97a7/3.7.0/Dockerfile

**Comment by marker-wu** [comment]
https://hub.docker.com/layers/zookeeper/library/zookeeper/3.7.0/images/sha256-5d84555246accc3b640551dc28c59fd81e645a3ce268aedf9b3c50854fa07902?context=explore

**Comment by RaigorJiang** [comment]
> https://hub.docker.com/layers/zookeeper/library/zookeeper/3.7.0/images/sha256-5d84555246accc3b640551dc28c59fd81e645a3ce268aedf9b3c50854fa07902?context=explore

I tested with this mirror. Proxy can connect normally without special configuration.
So, please check the environment, for example, try installing the local ZK? Or find the reason for another machine.

**Comment by RaigorJiang** [comment]
Docker log:
![image](https://user-images.githubusercontent.com/5668787/132620909-695d1fd6-ebe1-4fdf-9b02-9dfca8827a71.png)

**Comment by marker-wu** [comment]
> > https://hub.docker.com/layers/zookeeper/library/zookeeper/3.7.0/images/sha256-5d84555246accc3b640551dc28c59fd81e645a3ce268aedf9b3c50854fa07902?context=explore
> 
> I tested with this mirror. Proxy can connect normally without special configuration.
> So, please check the environment, for example, try installing the local ZK? Or find the reason for another machine.

The local ZK and the virtual machine manually install ZK, and the proxy can be connected normally, but the ZK installed with docker cannot connect to the proxy, but it can be connected with the ZK client tool. It’s really weird... anyway. thank you for your reply!

**Comment by marker-wu** [comment]
> > https://hub.docker.com/layers/zookeeper/library/zookeeper/3.7.0/images/sha256-5d84555246accc3b640551dc28c59fd81e645a3ce268aedf9b3c50854fa07902?context=explore
> 
> I tested with this mirror. Proxy can connect normally without special configuration.
> So, please check the environment, for example, try installing the local ZK? Or find the reason for another machine.

The local ZK and proxy can be connected normally, but the ZK installed with docker, the proxy cannot be connected, but it can be connected with the ZK client tool, which is really weird...

**Comment by marker-wu** [comment]
The situation is: ZK is running in my virtual machine, and then the program (demo program, shardingProxy) is running on the host machine, my demo program can connect to ZK, but the proxy cannot be connected

**Comment by RaigorJiang** [comment]
Have you reached the limit on the number of clients in ZK?  Configured by `maxClientCnxns`.

**Comment by marker-wu** [comment]
> Have you reached the limit on the number of clients in ZK? Configured by `maxClientCnxns`.

NO，I shutdown the demo program, and the proxy cannot connect to ZK

**Comment by RaigorJiang** [comment]
No more ideas, sorry.

**Comment by marker-wu** [comment]
> > https://hub.docker.com/layers/zookeeper/library/zookeeper/3.7.0/images/sha256-5d84555246accc3b640551dc28c59fd81e645a3ce268aedf9b3c50854fa07902?context=explore
> 
> I tested with this mirror. Proxy can connect normally without special configuration.
> So, please check the environment, for example, try installing the local ZK? Or find the reason for another machine.

Is your ZK running locally or on another machine?

**Comment by RaigorJiang** [comment]
There are the following environments: 
local machine, Docker container, remote host, 
they all work normally.

**Comment by tristaZero** [comment]
Is it a bug or not?

**Comment by RaigorJiang** [comment]
@tristaZero  
The test is normal, and other colleagues use it normally, no one else reports this problem. 
So it is still more likely to be an environmental problem.   
Hope @marker-wu can do more verification.

**Comment by marker-wu** [comment]
The sharding-proxy can't even connect to my colleague’s ZK. It can only connect to the local ZK. The sharding-ui has the same problem. It’s really weird.

**Comment by RaigorJiang** [comment]
is `192.168.238.128` your docker container's address?
Maybe the switch has restrictions?
Try other virtual machines?

**Comment by marker-wu** [comment]
> is `192.168.238.128` your docker container's address?
> Maybe the switch has restrictions?
> Try other virtual machines?

Yes,`192.168.238.128` is my docker container's address
I tried to connect to my colleague’s ZK, but it couldn’t be connected. My demo program can be connected.

**Comment by RaigorJiang** [comment]
Why not map the port to localhost, and then the proxy uses the local port to connect？

> Yes,`192.168.238.128` is my docker container's address

**Comment by marker-wu** [comment]
There is a problem with what I said just now. 192.168.238.128 is a local virtual machine of mine. Then I run ZK in the virtual machine with docker. I have done port 2181 mapping.

**Comment by RaigorJiang** [comment]
This scene is indeed a bit unusual.
ShardingSphere uses `Apache Curator` as the client of ZK connection. Maybe you can investigate whether curator supports the scenario you described.

**Comment by shulipeng** [comment]
I have same question , if i use local zk , it can work

**Comment by taojintianxia** [comment]
you guys can not conntect to the zk which luanched by docker, then would you please share the command you start up the zk ? @shulipeng @marker-wu @RaigorJiang

**Comment by marker-wu** [comment]
> you guys can not conntect to the zk which luanched by docker, then would you please share the command you start up the zk ? @shulipeng @marker-wu @RaigorJiang
> 
> like `docker run blabla`

docker run --privileged=true -d --name zookeeper --publish 2181:2181  -d zookeeper:latest
Not only the ZK running in docker cannot be connected, but also the ZK manually installed on another machine cannot be connected.

**Comment by taojintianxia** [comment]
> > you guys can not conntect to the zk which luanched by docker, then would you please share the command you start up the zk ? @shulipeng @marker-wu @RaigorJiang
> > like `docker run blabla`
> 
> docker run --privileged=true -d --name zookeeper --publish 2181:2181 -d zookeeper:latest
> Not only the ZK running in docker cannot be connected, but also the ZK manually installed on another machine cannot be connected.

since you can connect to zk by a ZK UI app, which mean proxy should connect too.... for another zk which installed on your colleagues or a server, did you try to connect to that zk by the ZI ZUI app ?

following is the screenshot of my machine

![image](https://user-images.githubusercontent.com/4112856/133400444-df341cdd-b0fc-4fd5-aff4-225c2acf0b3e.png)

I build a lastest proxy through the code I pull just now . and then I luanched up zk by docker command `docker run -dit --name zookeeper -p 2181:2181 zookeeper:3.7.0`

after zk start up, I luanched the [ZKUI](https://github.com/DeemOpen/zkui) and proxy

when proxy start up, I could see the corresponding config through zkui.

**Comment by marker-wu** [comment]
> > > you guys can not conntect to the zk which luanched by docker, then would you please share the command you start up the zk ? @shulipeng @marker-wu @RaigorJiang
> > > like `docker run blabla`
> > 
> > 
> > docker run --privileged=true -d --name zookeeper --publish 2181:2181 -d zookeeper:latest
> > Not only the ZK running in docker cannot be connected, but also the ZK manually installed on another machine cannot be connected.
> 
> since you can connect to zk by a ZK UI app, which mean proxy should connect too.... for another zk which installed on your colleagues or a server, did you try to connect to that zk by the ZI ZUI app ?
> 
> following is the screenshot of my machine
> 
> ![image](https://user-images.githubusercontent.com/4112856/133400444-df341cdd-b0fc-4fd5-aff4-225c2acf0b3e.png)
> 
> I build a lastest proxy through the code I pull just now . and then I luanched up zk by docker command `docker run -dit --name zookeeper -p 2181:2181 zookeeper:3.7.0`
> 
> after zk start up, I luanched the [ZKUI](https://github.com/DeemOpen/zkui) and proxy
> 
> when proxy start up, I could see the corresponding config through zkui.

I can connect to ZK (my local machine and my colleague's machine) through the ZK client tool (ZooInspector), but the agent cannot connect to ZK

**Comment by shulipeng** [comment]
@taojintianxia 
How can i setting zk operation timeout  in shardingsphere-ui ?  
may be it was our vm machine connection problems?
here are my stack info:

![1631698928(1)](https://user-images.githubusercontent.com/20982490/133410455-cb6561ce-47c2-4a73-b0a1-7489d9b338d7.png)

**Comment by taojintianxia** [comment]
@shulipeng I didn't see where is the timeout config for shardingsphere-ui.

**Comment by taojintianxia** [comment]
@marker-wu so, the zk UI related app could access zk, but proxy can not .. en ....this makes me loss the word.
do you want to try like following process ?
1. docker run -dit --name zookeeper -p 2181:2181 zookeeper:3.7.0
2. docker run -itd -e ZKLIST='YOUR_IP:2181' -p 9090:9090 maauso/zkui (your ip, not 127.0.0.1 or localhost)
3. start up proxy.

this process works fine on my machine and my environment.

**Comment by RaigorJiang** [comment]
@marker-wu 
Can you use a Curator client to test your ZK connection?  So we can check if it is a issue of  Curator?

**Comment by marker-wu** [comment]
> @marker-wu
> Can you use a Curator client to test your ZK connection? So we can check if it is an issue of Curator?

My demo program is connected to ZK with Curator

**Comment by marker-wu** [comment]
> @marker-wu so, the zk UI related app could access zk, but proxy can not .. en ....this makes me loss the word.
> do you want to try like following process ?
> 
> 1. docker run -dit --name zookeeper -p 2181:2181 zookeeper:3.7.0
> 2. docker run -itd -e ZKLIST='YOUR_IP:2181' -p 9090:9090 maauso/zkui (your ip, not 127.0.0.1 or localhost)
> 3. start up proxy.
> 
> this process works fine on my machine and my environment.

I executed 1, 3 and it does not work

**Comment by RaigorJiang** [comment]
> > @marker-wu
> > Can you use a Curator client to test your ZK connection? So we can check if it is an issue of Curator?
> 
> My demo program is connected to ZK with Curator

Is the version same with than in ShardingSphere?   
`<curator.version>5.1.0</curator.version>`

**Comment by marker-wu** [comment]
> > > @marker-wu
> > > Can you use a Curator client to test your ZK connection? So we can check if it is an issue of Curator?
> > 
> > 
> > My demo program is connected to ZK with Curator
> 
> Is the version same with than in ShardingSphere?
> `<curator.version>5.1.0</curator.version>`
 <parent>
        <groupId>org.apache.curator</groupId>
        <artifactId>apache-curator</artifactId>
        <version>2.13.0</version>
    </parent>

**Comment by shulipeng** [comment]
> > @marker-wu so, the zk UI related app could access zk, but proxy can not .. en ....this makes me loss the word.
> > do you want to try like following process ?
> > 
> > 1. docker run -dit --name zookeeper -p 2181:2181 zookeeper:3.7.0
> > 2. docker run -itd -e ZKLIST='YOUR_IP:2181' -p 9090:9090 maauso/zkui (your ip, not 127.0.0.1 or localhost)
> > 3. start up proxy.
> > 
> > this process works fine on my machine and my environment.
> 
> I executed 1, 3 and it does not work

You can try set host name with your ip in /etc/hosts , like 192.168.86.131 zk-131 
I try it and find all work fine !!! Include sharding-ui and sharding-proxy . 
I think it is zk problems，i just setting in /etc/hosts , I don't why.

before setting :
![c00e12a2093cc073b58dc2f2c843a0f](https://user-images.githubusercontent.com/20982490/133541526-2ab47cc5-fb3a-4d4f-bde0-e2b5a4bf9758.png)

after setting :
![11fcf5eb6fffc04ed55c7f79215dd91](https://user-images.githubusercontent.com/20982490/133541527-8f283cf1-6454-41bd-8094-f878dc7f0a17.png)

**Comment by RaigorJiang** [comment]
@shulipeng 
Is your Proxy work on Windows?   
Some old version ZK clients have this problem, is that means we need to upgrade Curator framework to newer version?

**Comment by shulipeng** [comment]
> @shulipeng
> Is your Proxy work on Windows?
> Some old version ZK clients have this problem, is that means we need to upgrade Curator framework to newer version?

No，all in my virtual machine . 
I try to replace curator-*-5.1.0.jar with curator-*-5.2.0.jar in sharding-proxy lib directory. but it doesn't work
I will try another zk and curator version ...

**Comment by marker-wu** [comment]
> > > @marker-wu so, the zk UI related app could access zk, but proxy can not .. en ....this makes me loss the word.
> > > do you want to try like following process ?
> > > 
> > > 1. docker run -dit --name zookeeper -p 2181:2181 zookeeper:3.7.0
> > > 2. docker run -itd -e ZKLIST='YOUR_IP:2181' -p 9090:9090 maauso/zkui (your ip, not 127.0.0.1 or localhost)
> > > 3. start up proxy.
> > > 
> > > this process works fine on my machine and my environment.
> > 
> > 
> > I executed 1, 3 and it does not work
> 
> You can try set host name with your ip in /etc/hosts , like 192.168.86.131 zk-131
> I try it and find all work fine !!! Include sharding-ui and sharding-proxy .
> I think it is zk problems，i just setting in /etc/hosts , I don't why.
> 
> before setting :
> ![c00e12a2093cc073b58dc2f2c843a0f](https://user-images.githubusercontent.com/20982490/133541526-2ab47cc5-fb3a-4d4f-bde0-e2b5a4bf9758.png)
> 
> after setting :
> ![11fcf5eb6fffc04ed55c7f79215dd91](https://user-images.githubusercontent.com/20982490/133541527-8f283cf1-6454-41bd-8094-f878dc7f0a17.png)

I have configured a domain name mapping in the windows system hosts file, which can connect to the ZK of the virtual machine with a domain name.
![image](https://user-images.githubusercontent.com/45256940/133545756-9ef51a41-31df-4060-a051-36d5cb0bf1c7.png)
![image](https://user-images.githubusercontent.com/45256940/133546045-3bb6f74c-16b4-4e84-8362-85f9d4760578.png)

**Comment by marker-wu** [comment]
> @shulipeng
> Is your Proxy work on Windows?
> Some old version ZK clients have this problem, is that means we need to upgrade Curator framework to newer version?

I think it's a bug of Curator ,may be that the referenced version of Curator is too high

**Comment by RaigorJiang** [comment]
I found a blog related to this problem:
https://blog.csdn.net/tt_rsn/article/details/106954735

**Comment by sandynz** [comment]
Hi @marker-wu , thanks for your feedback. Since it's already resolved, could we close it?
