### ISSUE TITLE
Failed to fetch schema of  ‘table_name’

### ISSUE THREAD

**Issue by dengjin001** [apache/shardingsphere#12311]
shardingsphere -5.0.0-beata error show ：

``2021-09-09 17:09:51.305 [DubboServerHandler-192.168.0.159:20881-thread-27] INFO  ShardingSphere-SQL -Logic SQL: SELECT * FROM asset_balance_detail LIMIT 1
2021-09-09 17:09:51.305 [DubboServerHandler-192.168.0.159:20881-thread-27] INFO  ShardingSphere-SQL -SQLStatement: MySQLSelectStatement(limit=Optional[org.apache.shardingsphere.sql.parser.sql.common.segment.dml.pagination.limit.LimitSegment@6c0de631], lock=Optional.empty, window=Optional.empty)
2021-09-09 17:09:51.305 [DubboServerHandler-192.168.0.159:20881-thread-27] INFO  ShardingSphere-SQL -Actual SQL(simple): [master] ::: 5
2021-09-09 17:09:51.446 [DubboServerHandler-192.168.0.159:20881-thread-27] ERROR i.s.r.d.sql.struct.cache.AbstractTableMetaCache -get table meta of the table `asset_balance_detail` error: Failed to fetch schema of asset_balance_detail
java.sql.SQLException: Failed to fetch schema of asset_balance_detail
	at io.seata.rm.datasource.sql.struct.cache.MysqlTableMetaCache.fetchSchema(MysqlTableMetaCache.java:86)
	at io.seata.rm.datasource.sql.struct.cache.AbstractTableMetaCache.lambda$getTableMeta$0(AbstractTableMetaCache.java:61)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2343)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2341)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2324)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	at io.seata.rm.datasource.sql.struct.cache.AbstractTableMetaCache.getTableMeta(AbstractTableMetaCache.java:59)
	at io.seata.rm.datasource.AbstractConnectionProxy.prepareStatement(AbstractConnectionProxy.java:115)
	at sun.reflect.GeneratedMethodAccessor384.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.ConnectionLogger.invoke(ConnectionLogger.java:55)
	at com.sun.proxy.$Proxy124.prepareStatement(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:86)
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:59)
	at sun.reflect.GeneratedMethodAccessor383.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:106)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at com.sun.proxy.$Proxy279.prepare(Unknown Source)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.prepareStatement(MybatisSimpleExecutor.java:94)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doUpdate(MybatisSimpleExecutor.java:55)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.update(MybatisCachingExecutor.java:85)
	at sun.reflect.GeneratedMethodAccessor390.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:106)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at com.sun.proxy.$Proxy278.update(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor390.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:64)
	at com.sun.proxy.$Proxy278.update(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:194)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
	at com.sun.proxy.$Proxy240.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:271)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:60)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy246.insert(Unknown Source)
	at com.baomidou.mybatisplus.extension.service.IService.save(IService.java:63)
	at com.baomidou.mybatisplus.extension.service.IService$$FastClassBySpringCGLIB$$f8525d18.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at com.htmj.assetImpl.AssetBalanceDetailSrvImpl$$EnhancerBySpringCGLIB$$a9ac3e46.save(<generated>)
	at org.apache.dubbo.common.bytecode.Wrapper8.invokeMethod(Wrapper8.java)
	at org.apache.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:47)
	at org.apache.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:84)
	at org.apache.dubbo.config.invoker.DelegateProviderMetaDataInvoker.invoke(DelegateProviderMetaDataInvoker.java:56)
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)
	at io.seata.integration.dubbo.ApacheDubboTransactionPropagationFilter.invoke(ApacheDubboTransactionPropagationFilter.java:69)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at com.alibaba.dubbo.rpc.Invoker$CompatibleInvoker.invoke(Invoker.java:55)
	at io.seata.integration.dubbo.alibaba.AlibabaDubboTransactionPropagationFilter.invoke(AlibabaDubboTransactionPropagationFilter.java:45)
	at com.alibaba.dubbo.rpc.Filter.invoke(Filter.java:29)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:77)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:46)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:89)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:52)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.auth.filter.ProviderAuthFilter.invoke(ProviderAuthFilter.java:48)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:132)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:189)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:41)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:145)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:100)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:175)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
	at java.lang.Long.compareTo(Long.java:54)
	at org.apache.shardingsphere.sharding.merge.dql.orderby.CompareUtil.compareTo(CompareUtil.java:54)
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.compareTo(OrderByValue.java:120)
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.compareTo(OrderByValue.java:43)
	at java.util.PriorityQueue.siftUpComparable(PriorityQueue.java:656)
	at java.util.PriorityQueue.siftUp(PriorityQueue.java:647)
	at java.util.PriorityQueue.offer(PriorityQueue.java:344)
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByStreamMergedResult.orderResultSetsToQueue(OrderByStreamMergedResult.java:58)
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByStreamMergedResult.<init>(OrderByStreamMergedResult.java:50)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.build(ShardingDQLResultMerger.java:87)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.merge(ShardingDQLResultMerger.java:65)
	at org.apache.shardingsphere.infra.merge.MergeEngine.executeMerge(MergeEngine.java:87)
	at org.apache.shardingsphere.infra.merge.MergeEngine.merge(MergeEngine.java:77)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.mergeQuery(ShardingSphereStatement.java:448)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.executeQuery(ShardingSphereStatement.java:150)
	at io.seata.rm.datasource.sql.struct.cache.MysqlTableMetaCache.fetchSchema(MysqlTableMetaCache.java:81)
	... 96 common frames omitted``

**Comment by RaigorJiang** [comment]
Hi @dengjin001 
Please provide more information:
- ShardingSphere-JDBC or ShardingSphere-Proxy?
- which vision do you use?
- what's your sharding configuration?
- what are the `Logic SQL` and `Actual SQL`?  Set `props.sql-show` to `true` to print them.

**Comment by dengjin001** [comment]
> Hi @dengjin001
> Please provide more information:
> 
> * ShardingSphere-JDBC or ShardingSphere-Proxy?
        ShardingSphere-JDBC
> * which vision do you use?
      5.0.0-beta
> * what's your sharding configuration?
    `sharding:
        tables:
          asset_balance_detail:
            actual-data-nodes: master.asset_balance_detail_$->{0..4}
            table-strategy:
              standard:
                sharding-column: user_id
                sharding-algorithm-name: balance-line
          asset_ticket_detail:
            actual-data-nodes: master.asset_ticket_detail_$->{0..4}
            table-strategy:
              standard:
                sharding-column: user_id
                sharding-algorithm-name: ticket-line
          asset_expense_detail:
            actual-data-nodes: master.asset_expense_detail_$->{0..4}
            table-strategy:
              standard:
                sharding-column: user_id 
                sharding-algorithm-name: expense-line
        binding-tables:
          - asset_balance_detail
          - asset_ticket_detail
          - asset_expense_detail

        keyGenerators:
          snowflake:
            type: SNOWFLAKE
            props:
              worker-id: 123
        shardingAlgorithms:
          balance-line:
            type: INLINE
            props:
              algorithm-expression: asset_balance_detail_$->{user_id.toBigInteger() % 5}
          ticket-line:
            type: INLINE
            props:
              algorithm-expression: asset_ticket_detail_$->{user_id.toBigInteger() % 5} 
          expense-line:
            type: INLINE
            props:
              algorithm-expression: asset_expense_detail_$->{user_id.toBigInteger() % 5} `
> * what are the `Logic SQL` and `Actual SQL`?  Set `props.sql-show` to `true` to print them.
      `  ShardingSphere-SQL -Logic SQL: SELECT * FROM asset_balance_detail LIMIT 1
 ShardingSphere-SQL -SQLStatement: MySQLSelectStatement(limit=Optional[org.apache.shardingsphere.sql.parser.sql.common.segment.dml.pagination.limit.LimitSegment@3ce8b0d3], lock=Optional.empty, window=Optional.empty)  
ShardingSphere-SQL -Actual SQL: master ::: SELECT * FROM asset_balance_detail_0 ORDER BY balance_detail_id ASC  LIMIT 1
ShardingSphere-SQL -Actual SQL: master ::: SELECT * FROM asset_balance_detail_1 ORDER BY balance_detail_id ASC  LIMIT 1
 ShardingSphere-SQL -Actual SQL: master ::: SELECT * FROM asset_balance_detail_2 ORDER BY balance_detail_id ASC  LIMIT 1
ShardingSphere-SQL -Actual SQL: master ::: SELECT * FROM asset_balance_detail_3 ORDER BY balance_detail_id ASC  LIMIT 1
ShardingSphere-SQL -Actual SQL: master ::: SELECT * FROM asset_balance_detail_4 ORDER BY balance_detail_id ASC  LIMIT 1`

**Comment by RaigorJiang** [comment]
@dengjin001 
Seeing that there are shardingsphere and seata exceptions in your log, which one is the source of the problem?
You provided insert and select SQL, which one of the exceptions occurred?

**Comment by dengjin001** [comment]
> @dengjin001
> 看到您的日志中有碎片圈和座位异常，问题的根源是什么？
> 您提供了插入和选择 SQL，哪些例外发生？

debug  see org.apache.shardingsphere.sharding.merge.dql.orderby.CompareUtil.compareTo, thisValue type is long, but otherValue type is string.
![微信图片_20210910130804](https://user-images.githubusercontent.com/29300542/132802765-85f71831-cce2-4ec9-854e-2c0791624a42.png)
![微信图片_20210910130812](https://user-images.githubusercontent.com/29300542/132802768-4a4a6f76-f0a6-43ac-9a78-cec43513a2a6.png)

**Comment by RaigorJiang** [comment]
> debug see org.apache.shardingsphere.sharding.merge.dql.orderby.CompareUtil.compareTo, thisValue type is long, but otherValue type is string.
So, are your table columns inconsistent? There are varchar and bigint in different tables?

**Comment by dengjin001** [comment]
> > debug see org.apache.shardingsphere.sharding.merge.dql.orderby.CompareUtil.compareTo, thisValue type is long, but otherValue type is string.
> 
> So, are your table columns inconsistent? There are varchar and bigint in different tables?

ok ，because  there is a sharding table type not the same
