### ISSUE TITLE
Whether to support cockroachDB？

### ISSUE THREAD

**Issue by ulwfcyvi** [apache/shardingsphere#12352]
Caused by: org.postgresql.util.PSQLException: 在系统 catalog 中找不到名称数据类型(datatype)。
	at org.postgresql.jdbc.PgDatabaseMetaData.getMaxNameLength(PgDatabaseMetaData.java:82)
	at org.postgresql.jdbc.PgDatabaseMetaData.getMaxColumnNameLength(PgDatabaseMetaData.java:847)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.datasource.metadata.CachedDatabaseMetaData.<init>(CachedDatabaseMetaData.java:395)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.context.ShardingRuntimeContext.createCachedDatabaseMetaData(ShardingRuntimeContext.java:57)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.context.ShardingRuntimeContext.<init>(ShardingRuntimeContext.java:50)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.datasource.ShardingDataSource.<init>(ShardingDataSource.java:54)
	at org.apache.shardingsphere.shardingjdbc.api.ShardingDataSourceFactory.createDataSource(ShardingDataSourceFactory.java:48)
	at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration.shardingDataSource(SpringBootConfiguration.java:103)
	at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration$$EnhancerBySpringCGLIB$$1c8a2197.CGLIB$shardingDataSource$0(<generated>)
	at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration$$EnhancerBySpringCGLIB$$1c8a2197$$FastClassBySpringCGLIB$$5b61065d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
	at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration$$EnhancerBySpringCGLIB$$1c8a2197.shardingDataSource(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 41 common frames omitted

**Comment by terrymanu** [comment]
What is the useful with ShardingSphere and cockroachDB?

**Comment by tristaZero** [comment]
@ulwfcyvi Thanks for your question. I am still interested in this issue. Could I know why you want to use ShardingSphere with cockroachDB?  THnaks?

**Comment by ulwfcyvi** [comment]
> @ulwfcyvi Thanks for your question. I am still interested in this issue. Could I know why you want to use ShardingSphere with cockroachDB? Thanks?

Because our cockroachDB query is slow, someone asked me to try ShardingSphere with cockroachDB. I think ShardingSphere is not suitable for cockroachDB. Because cockroachDB is a distributed database. What do you think?

**Comment by ulwfcyvi** [comment]
> What is the useful with ShardingSphere and cockroachDB?

Because our cockroachDB query is slow, someone asked me to try ShardingSphere with cockroachDB. I think ShardingSphere is not suitable for cockroachDB. Because cockroachDB is a distributed database. What do you think?

**Comment by terrymanu** [comment]
I am not sure `ShardingSphere is not suitable for cockroachDB`, maybe we need to try it first

**Comment by ulwfcyvi** [comment]
> I am not sure `ShardingSphere is not suitable for cockroachDB`, maybe we need to try it first
> 
> @ ulwfcyvi what is the reason for slow query with cockroachDB? What is your expect for performance?

It may be because CRDB is mainly optimized for OLTP and is not a real HTAP database.

**Comment by tristaZero** [comment]
Hi @ulwfcyvi 
Thanks for your feedback. Yep, ShardingSphere can help upgrade DBMS, e.g., Postgresql, Mysql to become a distributed database or do something like encryption. So your aim is to leverage ShardingSphere to make OLAP on CRDB become faster?

**Comment by ulwfcyvi** [comment]
> ShardingSphere

Yes, but I don’t know if I can improve query performance

**Comment by ulwfcyvi** [comment]
> Hi @ulwfcyvi
> Thanks for your feedback. Yep, ShardingSphere can help upgrade DBMS, e.g., Postgresql, Mysql to become a distributed database or do something like encryption. So your aim is to leverage ShardingSphere to make OLAP on CRDB become faster?

Yes, but I don’t know if I can improve query performance

**Comment by tristaZero** [comment]
Hi @ulwfcyvi You can have a try, as the main aim of ShardingSphere is not for what you want. But welcome your any attempt. If you need any help, please ping us here. ;-)

**Comment by tristaZero** [comment]
Since we didn't received any comments beyond 7 days, I have to close it.

**Comment by terrymanu** [comment]
I think the discussion is finished, I just close it
