### ISSUE TITLE
when  using the data encrypt and the sql condition contians DATE_FORMAT(:createdTime,'%y-%m-%d') and limit ,it will throws java.lang.ClassCastException:

### ISSUE THREAD

**Issue by wuwu20048** [apache/shardingsphere#12516]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.1.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior

I am using the ShardingSphere data encryption, Found that some SQL syntax error

```java
Query query = ss.createQuery("from User where age=:age and DATE_FORMAT(createdTime,'%y-%m-%d')=DATE_FORMAT(:createdTime,'%y-%m-%d')");
                query.setParameter("age", 11);
                query.setParameter("createdTime", new Date());
                query.setMaxResults(10);
                List list = query.list();
```
 

### Actual behavior
when no add setMaxResults,it run well

but when setMaxResults(10) ,it will throw 
``` java
Caused by: java.lang.ClassCastException: java.sql.Timestamp cannot be cast to java.lang.Integer
	at org.apache.shardingsphere.sql.parser.binder.segment.select.pagination.PaginationContext.getValue(PaginationContext.java:57)
	at org.apache.shardingsphere.sql.parser.binder.segment.select.pagination.PaginationContext.<init>(PaginationContext.java:51)
	at org.apache.shardingsphere.sql.parser.binder.segment.select.pagination.engine.LimitPaginationContextEngine.createPaginationContext(LimitPaginationContextEngine.java:38)
	at org.apache.shardingsphere.sql.parser.binder.segment.select.pagination.engine.PaginationContextEngine.createPaginationContext(PaginationContextEngine.java:48)
	at org.apache.shardingsphere.sql.parser.binder.statement.dml.SelectStatementContext.<init>(SelectStatementContext.java:100)
	at org.apache.shardingsphere.sql.parser.binder.SQLStatementContextFactory.getDMLStatementContext(SQLStatementContextFactory.java:103)
	at org.apache.shardingsphere.sql.parser.binder.SQLStatementContextFactory.newInstance(SQLStatementContextFactory.java:87)
	at org.apache.shardingsphere.underlying.route.DataNodeRouter.createRouteContext(DataNodeRouter.java:99)
	at org.apache.shardingsphere.underlying.route.DataNodeRouter.executeRoute(DataNodeRouter.java:89)
	at org.apache.shardingsphere.underlying.route.DataNodeRouter.route(DataNodeRouter.java:76)
	at org.apache.shardingsphere.underlying.pluggble.prepare.PreparedQueryPrepareEngine.route(PreparedQueryPrepareEngine.java:54)
	at org.apache.shardingsphere.underlying.pluggble.prepare.BasePrepareEngine.executeRoute(BasePrepareEngine.java:96)
	at org.apache.shardingsphere.underlying.pluggble.prepare.BasePrepareEngine.prepare(BasePrepareEngine.java:83)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.EncryptPreparedStatement.getSQLUnit(EncryptPreparedStatement.java:161)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.EncryptPreparedStatement.executeQuery(EncryptPreparedStatement.java:103)
	at
```
### Reason analyze (If you can)
it seems like the  createdTime value was been  identified  as the paginationValue
![](https://tva1.sinaimg.cn/large/008i3skNly1gujim40sbaj61oo0b20vh02.jpg)

**Comment by strongduanmu** [comment]
@wuwu20048 Thank you for your feedback, i will check it later.

**Comment by ZWMdarker** [comment]
![image](https://user-images.githubusercontent.com/35095364/144983468-f185f404-644e-4a29-ab53-a43da2fd963f.png)
I ran into the same problem with version 5.0.0
