### ISSUE TITLE
The MULTIPOLYGON, GEOMETRY, and PONIT types cannot be obtained by mysql JDBC using the DatabaseMetaData getTypeInfo method, causing a loadColumnMetaDataMap report NullPointerException

### ISSUE THREAD

**Issue by power522** [apache/shardingsphere#12548]
Startup log：

dataTypes`{BIGINT=-5, BIGINT UNSIGNED=-5, BINARY=-2, BIT=-7, BLOB=-4, BOOL=-7, CHAR=1, DATE=91, DATETIME=93, DECIMAL=3, DOUBLE=8, DOUBLE PRECISION=8, ENUM=12, FLOAT=7, INT=4, INT UNSIGNED=4, INTEGER=4, INTEGER UNSIGNED=4, JSON=-1, LONG VARBINARY=-4, LONG VARCHAR=-1, LONGBLOB=-4, LONGTEXT=-1, MEDIUMBLOB=-4, MEDIUMINT=4, MEDIUMINT UNSIGNED=4, MEDIUMTEXT=-1, NUMERIC=2, REAL=8, SET=12, SMALLINT=5, SMALLINT UNSIGNED=5, TEXT=-1, TIME=92, TIMESTAMP=93, TINYBLOB=-4, TINYINT=-6, TINYINT UNSIGNED=-6, TINYTEXT=-1, VARBINARY=-3, VARCHAR=12} `

dataType=varchar 
dataType=varchar 
dataType=varchar 
dataType=datetime 
dataType=int 
dataType=varchar 
dataType=varchar 
dataType=varchar 
dataType=varchar 
dataType=varchar 
dataType=varchar 
dataType=varchar 
dataType=varchar 
dataType=varchar 
dataType=int 
dataType=bit 
dataType=datetime 
dataType=varchar 
dataType=int 
dataType=varchar 
dataType=multipolygon 
[ERROR] 2021-09-18 06:47:15.846 [main] o.a.s.i.m.s.b.l.TableMetaDataLoaderEngine - Dialect load table meta data error 
org.apache.shardingsphere.infra.exception.ShardingSphereException: java.util.concurrent.ExecutionException: java.lang.NullPointerException 
	at org.apache.shardingsphere.infra.metadata.schema.builder.loader.TableMetaDataLoaderEngine.loadByDialect(TableMetaDataLoaderEngine.java:99) 
	at org.apache.shardingsphere.infra.metadata.schema.builder.loader.TableMetaDataLoaderEngine.load(TableMetaDataLoaderEngine.java:66) 
	at org.apache.shardingsphere.singletable.metadata.SingleTableMetaDataBuilder.load(SingleTableMetaDataBuilder.java:55) 
	at org.apache.shardingsphere.singletable.metadata.SingleTableMetaDataBuilder.load(SingleTableMetaDataBuilder.java:42) 
	at org.apache.shardingsphere.infra.metadata.schema.builder.TableMetaDataBuilder.load(TableMetaDataBuilder.java:65) 
	at org.apache.shardingsphere.mode.metadata.MetaDataContextsBuilder.build(MetaDataContextsBuilder.java:101) 
	at org.apache.shardingsphere.mode.manager.memory.MemoryContextManagerBuilder.build(MemoryContextManagerBuilder.java:49) 
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.initContext(BootstrapInitializer.java:75) 
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.init(BootstrapInitializer.java:66) 
	at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:47) 
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException 
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 
	at org.apache.shardingsphere.infra.metadata.schema.builder.loader.TableMetaDataLoaderEngine.loadByDialect(TableMetaDataLoaderEngine.java:93) 
	... 9 common frames omitted 
Caused by: java.lang.NullPointerException: null 
	at org.apache.shardingsphere.infra.metadata.schema.builder.loader.dialect.MySQLTableMetaDataLoader.loadColumnMetaData(MySQLTableMetaDataLoader.java:94) 
	at org.apache.shardingsphere.infra.metadata.schema.builder.loader.dialect.MySQLTableMetaDataLoader.loadColumnMetaDataMap(MySQLTableMetaDataLoader.java:75) 
	at org.apache.shardingsphere.infra.metadata.schema.builder.loader.dialect.MySQLTableMetaDataLoader.load(MySQLTableMetaDataLoader.java:54) 
	at org.apache.shardingsphere.infra.metadata.schema.builder.loader.TableMetaDataLoaderEngine.lambda$loadByDialect$0(TableMetaDataLoaderEngine.java:89) 
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
	at java.lang.Thread.run(Thread.java:745) 
Thanks for using Atomikos! Evaluate http://www.atomikos.com/Main/ExtremeTransactions for advanced features and professional support 
or register at http://www.atomikos.com/Main/RegisterYourDownload to disable this message and receive FREE tips & advice 
[INFO ] 2021-09-18 06:47:18.047 [main] o.a.s.p.i.BootstrapInitializer - Database name is `MySQL`, version is `5.7.24-log` 
[INFO ] 2021-09-18 06:47:18.225 [main] o.a.s.p.frontend.ShardingSphereProxy - ShardingSphere-Proxy start success 
------------------------------------------------------------------------------------------------------------------------
jdbc version mysql-connector-java 5.1.47
**The solution**
class MySQLTableMetaDataLoader
`private Map<String, Collection<ColumnMetaData>> loadColumnMetaDataMap(final DataSource dataSource, final Collection<String> tables) throws SQLException {

        Map<String, Collection<ColumnMetaData>> result = new HashMap<>();
        try (
                Connection connection = dataSource.getConnection();
                PreparedStatement preparedStatement = connection.prepareStatement(getTableMetaDataSQL(tables))) {
            Map<String, Integer> dataTypes = DataTypeLoader.load(connection.getMetaData());
            dataTypes.putIfAbsent("JSON", -1);
            **// add Spatial database type**

            dataTypes.putIfAbsent("MULTIPOLYGON", -1);

            dataTypes.putIfAbsent("GEOMETRY", -1);

            dataTypes.putIfAbsent("POINT", -1);

            preparedStatement.setString(1, connection.getCatalog());
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                while (resultSet.next()) {
                    String tableName = resultSet.getString("TABLE_NAME");
                    ColumnMetaData columnMetaData = loadColumnMetaData(dataTypes, resultSet);
                    if (!result.containsKey(tableName)) {
                        result.put(tableName, new LinkedList<>());
                    }
                    result.get(tableName).add(columnMetaData);
                }
            }
        }
        return result;
    }`

**Comment by ymind** [comment]
me too

**Comment by yx9o** [comment]
Hi @power522 , for English only, please modify the issue title and content, thank you.

**Comment by zjcnb** [comment]
It 's support JSON data type in master branch, But I think it 's need refactor here.

**Comment by tristaZero** [comment]
@power522 Hey could you try the master branch as @zjcnb said?

**Comment by terrymanu** [comment]
No response
