### ISSUE TITLE
no well implements AbstractUnsupportedOperationConnection

### ISSUE THREAD

**Issue by tuhanglsWorld** [apache/shardingsphere#12607]
org.springframework.dao.InvalidDataAccessApiUsageException: ConnectionCallback; isValid; nested exception is java.sql.SQLFeatureNotSupportedException: isValid
Caused by: java.sql.SQLFeatureNotSupportedException: isValid
	at org.apache.shardingsphere.shardingjdbc.jdbc.unsupported.AbstractUnsupportedOperationConnection.isValid(AbstractUnsupportedOperationConnection.java:161)
	at sun.reflect.GeneratedMethodAccessor235.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.jdbc.core.JdbcTemplate$CloseSuppressingInvocationHandler.invoke(JdbcTemplate.java:1614)
	at com.sun.proxy.$Proxy287.isValid(Unknown Source)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.isConnectionValid(DataSourceHealthIndicator.java:134)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:334)
	... 138 common frames omitted

![image](https://user-images.githubusercontent.com/91142166/134197231-80d49982-c3ca-400c-a517-041d5ee1cba0.png)

**Comment by strongduanmu** [comment]
@tuhanglsWorld Can you try the latest version? It has been supported now.

**Comment by terrymanu** [comment]
No feedback for long time, I just close it.

**Comment by bert82503** [comment]
> No feedback for long time, I just close it.

It has resolved for 5.* version.
pls see #6002
