### ISSUE TITLE
Proxy might get wrong schema which configuration is not complete to decide frontend database protocol type

### ISSUE THREAD

**Issue by justbk2015** [apache/shardingsphere#12672]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
master
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
proxy
### Expected behavior
when scaling task over and I restart proxy, I can use gsql connect to opengauss.
### Actual behavior
I can use gsql connect to opengauss, the return info is:
gsql: received invalid response to SSL negotiation: j.
### Reason analyze (If you can)
1. the reason is  FrontDatabaseProtocolTypeFactory::getDatabaseType function use invalid schema to set databaseType to default. (default is MySQL),.
2.because when scaling task running,  it add logic_db on governance_ds/metadata/, but this schema dataSources is empty.
getDatabaseType only use first schema (this is logic) , and  that databaseType is MySQL， so error occur.
3. I guess use postgrsql database have some problem.
![49562352f028acf3d730d7b3b439e29](https://user-images.githubusercontent.com/12265143/134626248-04873309-2942-4c63-bbfa-0718da587a81.png)

init server version in BootstrapInitializer.java have some problem (can't initlization):
![image](https://user-images.githubusercontent.com/12265143/134634883-626f7a18-6840-4856-b1e0-56ddb35b43df.png)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. open sharding-proxy zookeeper config and scaling config, then start
2. start sharding-scaling
3. create a scaling job (no need wait this job over, just when zookeeper have logic_db node in governance_ds/metadata/)
4.  delete job from zookeeker
5. restart sharding-proxy
6. use gsql connect to openguass, judje if can connect success.
### Example codes for reproduce this issue (such as a github link).
no need.
### error trace:
java.lang.IndexOutOfBoundsException: readerIndex(1) + length(4) exceeds writerIndex(1): PooledSlicedByteBuf(ridx: 1, widx: 1, cap: 1/1, unwrapped: PooledUnsafeDirectByteBuf(ridx: 4, widx: 8, cap: 1024))
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1477)
        at io.netty.buffer.AbstractByteBuf.readIntLE(AbstractByteBuf.java:818)
        at org.apache.shardingsphere.db.protocol.mysql.payload.MySQLPacketPayload.readInt4(MySQLPacketPayload.java:111)
        at org.apache.shardingsphere.db.protocol.mysql.packet.handshake.MySQLHandshakeResponse41Packet.<init>(MySQLHandshakeResponse41Packet.java:56)
        at org.apache.shardingsphere.proxy.frontend.mysql.authentication.MySQLAuthenticationEngine.authPhaseFastPath(MySQLAuthenticationEngine.java:83)
        at org.apache.shardingsphere.proxy.frontend.mysql.authentication.MySQLAuthenticationEngine.authenticate(MySQLAuthenticationEngine.java:70)
        at org.apache.shardingsphere.proxy.frontend.netty.FrontendChannelInboundHandler.authenticate(FrontendChannelInboundHandler.java:79)
        at org.apache.shardingsphere.proxy.frontend.netty.FrontendChannelInboundHandler.channelRead(FrontendChannelInboundHandler.java:71)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:308)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:422)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)

**Comment by sandynz** [comment]
It works on OSX which scaling.

It seems proxy get a schema (e.g. logic_db) which configuration is not complete (`dataSources` and `rules` are empty) on Windows platform, so it cause issue.

I'll reproduce it and comment here later.

**Comment by sandynz** [comment]
Verification:
```
mysql> create database logic_db;
Query OK, 0 rows affected (0.01 sec)

mysql> show databases;
+-------------+
| schema_name |
+-------------+
| sharding_db |
| shard1      |
| logic_db    |
+-------------+
3 rows in set (0.00 sec)
```

`logic_db` has empty `dataSources` and `rules`.

Set breakpoint on `FrontDatabaseProtocolTypeFactory.getDatabaseType()`, start proxy, `ProxyContext.getInstance().getContextManager().getMetaDataContexts().getAllSchemaNames()` return `0 = "logic_db"
1 = "sharding_db"
2 = "shard1"`.

`.iterator().next()` will return `logic_db`. Since `dataSources` is empty, then default database MySQL will be used.
If current testing database type is not MySQL, then connect to proxy will be failed.

Since `getAllSchemaNames()` return `HashMap`, the first element depends on contents.

**Comment by justbk2015** [comment]
@rfscholte you only modify first problem, 
 BootstrapInitializer.java have some problem (can't initlization) --this problem still exists, I think, you need some filter operator to avoid empty logic_db.

**Comment by sandynz** [comment]
> @rfscholte you only modify first problem,
> BootstrapInitializer.java have some problem (can't initlization) --this problem still exists, I think, you need some filter operator to avoid empty logic_db.

I tested with `psql`, it works, but `setDatabaseServerInfo()` will ignore `setServerVersion`, since `findBackendDataSource()` return empty result.

I'll start another PR to improve it.
