### ISSUE TITLE
The CI always fails on ubuntu-latest  for JDK 11 with FederationStatementTest

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#12727]
Please check.

```log
Error:  Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.816 s <<< FAILURE! - in org.apache.shardingsphere.driver.jdbc.core.statement.FederationStatementTest
Error:  assertQueryWithFederationInSingleAndShardingTableRewriteByExecuteQuery(org.apache.shardingsphere.driver.jdbc.core.statement.FederationStatementTest)  Time elapsed: 2.3 s  <<< ERROR!
java.sql.SQLException: exception while executing query: org.h2.jdbc.JdbcSQLException: The object is already closed [90007-196]
	at org.apache.shardingsphere.driver.jdbc.core.statement.FederationStatementTest.assertQueryWithFederationInSingleAndShardingTableRewrite(FederationStatementTest.java:84)
	at org.apache.shardingsphere.driver.jdbc.core.statement.FederationStatementTest.assertQueryWithFederationInSingleAndShardingTableRewriteByExecuteQuery(FederationStatementTest.java:74)
Caused by: java.lang.RuntimeException: org.h2.jdbc.JdbcSQLException: The object is already closed [90007-196]
	at org.apache.shardingsphere.driver.jdbc.core.statement.FederationStatementTest.assertQueryWithFederationInSingleAndShardingTableRewrite(FederationStatementTest.java:84)
	at org.apache.shardingsphere.driver.jdbc.core.statement.FederationStatementTest.assertQueryWithFederationInSingleAndShardingTableRewriteByExecuteQuery(FederationStatementTest.java:74)
Caused by: org.h2.jdbc.JdbcSQLException: The object is already closed [90007-196]
	at org.apache.shardingsphere.driver.jdbc.core.statement.FederationStatementTest.assertQueryWithFederationInSingleAndShardingTableRewrite(FederationStatementTest.java:84)
	at org.apache.shardingsphere.driver.jdbc.core.statement.FederationStatementTest.assertQueryWithFederationInSingleAndShardingTableRewriteByExecuteQuery(FederationStatementTest.java:74)
```

**Comment by strongduanmu** [comment]
@terrymanu Thank you for your feedback, I will check this exception.

**Comment by strongduanmu** [comment]
I tried to use JDK11 to reproduce this problem, but there was no exception. Since this unit test plan is migrated to integration testing, I will promote the migration of the last two integration tests #10916 #10915, and then delete this test class.

**Comment by strongduanmu** [comment]
`FederationStatementTest` has been deleted now.
