### ISSUE TITLE
Upgrade antlr4 to 4.8

### ISSUE THREAD

**Issue by zhfeng** [apache/shardingsphere#12791]
## Feature Request

I'd like to upgarde antlr4 to 4.8

### Is your feature request related to a problem?
https://github.com/quarkiverse/quarkus-shardingsphere-jdbc/issues/2

### Describe the feature you would like.
It throws exception when building quarkus-shardingsphere-jdbc in native mode
```
ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.8ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.8Fatal error:java.lang.AbstractMethodError: org.apache.calcite.rel.rules.ReduceExpressionsRule$Config.toRule[Ljava.lang.Object;@6c7ff3ce/invokeInterface
	at java.base/java.lang.invoke.MemberName.<init>(MemberName.java:610)
	at java.base/java.lang.invoke.InfoFromMemberName.convertToMemberName(InfoFromMemberName.java:137)
	at java.base/java.lang.invoke.InfoFromMemberName.reflectAs(InfoFromMemberName.java:103)
	at java.base/java.lang.invoke.MethodHandles.reflectAs(MethodHandles.java:242)
	at com.oracle.svm.methodhandles.MethodHandleFeature.registerMethodHandle(MethodHandleFeature.java:252)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:572)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.replaceObject(AnalysisConstantReflectionProvider.java:217)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.interceptValue(AnalysisConstantReflectionProvider.java:188)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:102)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:81)
	at com.oracle.graal.pointsto.ObjectScanner.scanField(ObjectScanner.java:160)
	at com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:332)
	at com.oracle.graal.pointsto.ObjectScanner.lambda$scanConstant$6(ObjectScanner.java:258)
	at com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:188)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:172)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool.awaitQuiescence(ForkJoinPool.java:2984)
	at com.oracle.graal.pointsto.util.CompletionExecutor.complete(CompletionExecutor.java:238)
	at com.oracle.graal.pointsto.BigBang.checkObjectGraph(BigBang.java:623)
	at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:587)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:707)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:532)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:491)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:380)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)
Error: Image build request failed with exit status 1
```

**Comment by strongduanmu** [comment]
@zhfeng Are you interested in submitting a PR to upgrade antlr?
