### ISSUE TITLE
Failed to execute DistSQL in PostgreSQL extended protocol

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#12989]
Related to #12964 

### Which version of ShardingSphere did you use?
master 

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
PostgreSQL Proxy 

### Example codes for reproduce this issue (such as a github link).

```
try (Statement statement = connection.createStatement()) {
    try (ResultSet rs = statement.executeQuery("SHOW RESOURCES")) {
    }
}
```

### Expected behavior

DistSQL works well.

### Actual behavior

```
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: unrecognized configuration parameter "resources"
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:224)
	at icu.wwj.hello.jdbc.DDLTest.main(DDLTest.java:14)
```

### Reason analyze (If you can)

DistSQL worked well using `psql` because `psql` client using simple query protocol by default. 

```
$ psql -h 127.0.0.1 -p 3307 -Upostgres -d wuweijie
Password for user postgres: 
psql (13.3)
Type "help" for help.

wuweijie=> show resources;
 name |    type    |   host    | port |    db    |                                                                         attribute                                                                          
------+------------+-----------+------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------
 ds_0 | PostgreSQL | localhost | 5432 | wuweijie | {"maxLifetimeMilliseconds":1800000,"readOnly":false,"minPoolSize":0,"idleTimeoutMilliseconds":60000,"maxPoolSize":12,"connectionTimeoutMilliseconds":3000}
(1 row)

```

**Comment by RaigorJiang** [comment]
`show resources` syntax requires `from schemaName` now. Please use new API, refer to:  https://github.com/apache/shardingsphere/pull/13015

**Comment by RaigorJiang** [comment]
@TeslaCN Would you please help to verify if the problem is solved?

**Comment by TeslaCN** [comment]
@RaigorJiang 
The `show schema resources` worked.

**Comment by RaigorJiang** [comment]
@TeslaCN 
OK, so I will close this issue. Thank you!
