### ISSUE TITLE
Exception during pool initialization

### ISSUE THREAD

**Issue by penghuazhou** [apache/shardingsphere#13016]
when use ShardingSphere UI to add a dataSource for example ds_03, if there is insert sql execute send to ShardingSphere-Proxy(no sql execute this time, will not have error)，if throw this error? 

![image](https://user-images.githubusercontent.com/13001038/137087714-17bf3ec9-cbbb-47fe-850b-797d1c6ad004.png)

Which version of ShardingSphere did you use?
apache-shardingsphere-4.1.1-src-release, ShardingSphere-Proxy

sharding_db=> insert into t_order (user_id,info,c1,crt_time) values (22,'xxxxxxxxzxxxxx',1,now());
HikariDataSource HikariDataSource (HikariPool-8) has been closed.

[ERROR] 15:30:19.502 [Curator-TreeCache-5] com.zaxxer.hikari.pool.HikariPool - HikariPool-24 - Exception during pool initialization.
org.postgresql.util.PSQLException: FATAL: sorry, too many clients already
    at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:514)
    at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)
    at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
    at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
    at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
    at org.postgresql.Driver.makeConnection(Driver.java:454)
    at org.postgresql.Driver.connect(Driver.java:256)
    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
    at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:354)
    at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
    at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
    at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:554)
    at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
    at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
    at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCRawBackendDataSourceFactory.build(JDBCRawBackendDataSourceFactory.java:74)
    at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.createDataSources(JDBCBackendDataSource.java:70)
    at

**Comment by TeslaCN** [comment]
Refer to https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_max_connections

**Comment by TeslaCN** [comment]
@penghuazhou 
This error message `sorry, too many clients already` is returned by actual database. Consider increasing the `max_connections` of the databases.
