### ISSUE TITLE
ShardingSphere-JDBC 5.0.0-RC1-SNAPSHOT: throw StringIndexOutOfBoundsException when config the encrypt rule and use the sql join 

### ISSUE THREAD

**Issue by wuwu20048** [apache/shardingsphere#13057]
## Bug Report

when use sql join with two tables ,and the tables have the encrypt rule ,it will throw the StringIndexOutOfBoundsException
but with no encrypt rule for the tables, it run well .

the sql is:
```java
Query query = ss.createQuery("select a from Doctor a,Doctor1 b where a.id=b.doctorId and a.mobile=:mobile)");
                query.setParameter("mobile", mobile);
                List list = query.list();
```
the encrypt rule:

```xml
	<encrypt:rule id="encryptRule" query-with-cipher-column="false">
	<encrypt:table name="doctor">
		<encrypt:column logic-column="mobile" plain-column="${plain.column:mobile}" cipher-column="mobile_cipher" encrypt-algorithm-ref="sm4_encryptor" />
		<encrypt:column logic-column="idcard" plain-column="${plain.column:idcard}" cipher-column="idcard_cipher" encrypt-algorithm-ref="sm4_encryptor" />
	</encrypt:table>
	<encrypt:table name="doctor1">
			<encrypt:column logic-column="mobile" plain-column="Mobile" cipher-column="mobile_cipher" encrypt-algorithm-ref="sm4_encryptor" />
		</encrypt:table>
	</encrypt:rule>

	<shardingsphere:data-source id="encryptDataSource" data-source-names="dataSource"  rule-refs="encryptRule">
		<props>
			<prop key="sql-show">true</prop>
		</props>
	</shardingsphere:data-source>
```

### Which version of ShardingSphere did you use?
the master branch ,5.0.0-RC1-SNAPSHOT
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 
### Actual behavior
```java
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -20
	at java.lang.String.substring(String.java:1967)
	at org.apache.shardingsphere.infra.rewrite.sql.impl.AbstractSQLBuilder.getConjunctionText(AbstractSQLBuilder.java:64)
	at org.apache.shardingsphere.infra.rewrite.sql.impl.AbstractSQLBuilder.toSQL(AbstractSQLBuilder.java:47)
	at org.apache.shardingsphere.infra.rewrite.engine.RouteSQLRewriteEngine.rewrite(RouteSQLRewriteEngine.java:52)
	at org.apache.shardingsphere.infra.rewrite.SQLRewriteEntry.rewrite(SQLRewriteEntry.java:71)
	at org.apache.shardingsphere.infra.context.kernel.KernelProcessor.rewrite(KernelProcessor.java:59)
	at org.apache.shardingsphere.infra.context.kernel.KernelProcessor.generateExecutionContext(KernelProcessor.java:47)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.createExecutionContext(ShardingSpherePreparedStatement.java:378)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.executeQuery(ShardingSpherePreparedStatement.java:180)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:70)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2117)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1900)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1876)
	at org.hibernate.loader.Loader.doQuery(Loader.java:919)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:336)
	at org.hibernate.loader.Loader.doList(Loader.java:2617)
	at org.hibernate.loader.Loader.doList(Loader.java:2600)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2429)
	at org.hibernate.loader.Loader.list(Loader.java:2424)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:501)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:371)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:216)
	at org.hibernate.internal.StatelessSessionImpl.list(StatelessSessionImpl.java:566)
	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:87)
```
### Reason analyze (If you can)

it works fine with 5.0.0-beta, but 5.0.0-RC1-SNAPSHOT not work fine .

with 5.0.0-RC1-SNAPSHOT,  
Scene 1:
- query-with-cipher-column="false" 
- i found that if one the of tables was not in encrypt rule, it works fine 。
- all of the two tables config the encrypt rule, it   works not  fine 。
Scene 2:
- query-with-cipher-column="true" 
- all of the two tables config the encrypt rule, it  works fine 。

**Comment by cheese8** [comment]
thanks for your feedback, i will check it later.

**Comment by wuwu20048** [comment]
i found that  springboot encryption configuration works fine.  but the xml config i reported  above throw StringIndexOutOfBoundsException . can you check it ?

eg:

```java
public interface CustomerRepository extends CrudRepository<Customer, Long> {
    
    @Query(value = "SELECT u FROM Customer u, Person a WHERE u.id = a.id and a.name='aa' and u.firstName='c'")
    public List<Customer> findViewInfo();
}
```
```
spring.application.name=encrypt-demo

spring.shardingsphere.datasource.names=ds
spring.shardingsphere.datasource.ds.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.ds.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.ds.jdbc-url=jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
spring.shardingsphere.datasource.ds.username=root
spring.shardingsphere.datasource.ds.password=

spring.shardingsphere.rules.encrypt.encryptors.name-encryptor.type=AES
spring.shardingsphere.rules.encrypt.encryptors.name-encryptor.props.aes-key-value=1234567890123456

spring.shardingsphere.rules.encrypt.query-with-cipher-column=false

spring.shardingsphere.rules.encrypt.tables.customer.columns.first_name.cipher-column=first_name_cipher
spring.shardingsphere.rules.encrypt.tables.customer.columns.first_name.plain-column=first_name
spring.shardingsphere.rules.encrypt.tables.customer.columns.first_name.encryptor-name=name-encryptor


spring.shardingsphere.rules.encrypt.tables.person.name=personEncrypt
spring.shardingsphere.rules.encrypt.tables.person.columns.name.cipher-column=name_cipher
spring.shardingsphere.rules.encrypt.tables.person.columns.name.plain-column=name
spring.shardingsphere.rules.encrypt.tables.person.columns.name.encryptor-name=name-encryptor


spring.shardingsphere.props.sql-show=true
```

**Comment by LeeGuoPing** [comment]
Please assign it to me
