### ISSUE TITLE
Could not initialize class org.apache.shardingsphere.sql.parser.core.rule.registry.ParseRuleRegistry

### ISSUE THREAD

**Issue by BruceZhangXL** [apache/shardingsphere#13082]
## Bug Report
java.lang.NoClassDefFoundError, message=Could not initialize class org.apache.shardingsphere.sql.parser.core.rule.registry.ParseRuleRegistry 】 
java.lang.NoClassDefFoundError: Could not initialize class org.apache.shardingsphere.sql.parser.core.rule.registry.ParseRuleRegistry
	at org.apache.shardingsphere.sql.parser.SQLParseEngine.parse0(SQLParseEngine.java:70)
	at org.apache.shardingsphere.sql.parser.SQLParseEngine.parse(SQLParseEngine.java:52)
	at org.apache.shardingsphere.core.route.router.sharding.ShardingRouter.parse$original$K1EIPfwP(ShardingRouter.java:86)
	at org.apache.shardingsphere.core.route.router.sharding.ShardingRouter.parse$original$K1EIPfwP$accessor$fYOJ3msv(ShardingRouter.java)
	at org.apache.shardingsphere.core.route.router.sharding.ShardingRouter$auxiliary$8V8n2toM.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at org.apache.shardingsphere.core.route.router.sharding.ShardingRouter.parse(ShardingRouter.java)

### Which version of ShardingSphere did you use?
4.1.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
run fine under jdk 11
### Actual behavior
sometime throw  NoClassDefFoundError under jdk 11, the error seldom occur  but really exists ,must restart app once occured
### Reason analyze (If you can)
![image](https://user-images.githubusercontent.com/10344508/137657981-045e411f-fe55-4722-a00a-629cab281f78.png)

the static code block in ParseRuleRegistry maybe occer error,should wrap them with try and catch the real exception,instead of throw the initialize class fail exception.

**Comment by lanchengx** [comment]
Hi @BruceZhangXL , thanks for your feedback, could you try the latest version 5.0.0-beta? `ParseRuleRegistry` has some adjustments.

**Comment by BruceZhangXL** [comment]
> Hi @BruceZhangXL , thanks for your feedback, could you try the latest version 5.0.0-beta? `ParseRuleRegistry` has some adjustments.

the code had changed too much in 5.0.0, i can not find  this class named ParseRuleRegistry. we can not try this version in prod env.
