### ISSUE TITLE
How can I use etcd?

### ISSUE THREAD

**Issue by penghuazhou** [apache/shardingsphere#13142]
version:/Users/zego/IdeaProjects/apache-shardingsphere-5.0.0-beta-src-release

<img width="801" alt="企业微信截图_b0c4d4bd-e96d-450b-999f-5bfc5e59ee73" src="https://user-images.githubusercontent.com/13001038/137886212-6b284cac-a30f-44fd-b2ce-bed450ad8014.png">

java.lang.IllegalArgumentException: Invalid path string "//19.1.72.12:2379" caused by empty node name specified @1
        at org.apache.zookeeper.common.PathUtils.validatePath(PathUtils.java:91)
        at org.apache.zookeeper.client.ConnectStringParser.<init>(ConnectStringParser.java:62)
        at org.apache.zookeeper.ZooKeeper.createDefaultHostProvider(ZooKeeper.java:1514)
        at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:1107)
        at org.apache.zookeeper.admin.ZooKeeperAdmin.<init>(ZooKeeperAdmin.java:166)
        at org.apache.curator.utils.DefaultZookeeperFactory.newZooKeeper(DefaultZookeeperFactory.java:30)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl$2.newZooKeeper(CuratorFrameworkImpl.java:210)
        at org.apache.curator.HandleHolder$1.getZooKeeper(HandleHolder.java:100)
        at org.apache.curator.HandleHolder.getZooKeeper(HandleHolder.java:48)
        at org.apache.curator.ConnectionState.reset(ConnectionState.java:195)
        at org.apache.curator.ConnectionState.start(ConnectionState.java:102)
        at org.apache.curator.CuratorZookeeperClient.start(CuratorZookeeperClient.java:214)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.start(CuratorFrameworkImpl.java:334)
        at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.init(ZookeeperRegistryCenter.java:98)
        at org.apache.shardingsphere.scaling.core.api.ScalingAPIFactory$RegistryCenterHolder.createRegistryCenter(ScalingAPIFactory.java:206)
        at org.apache.shardingsphere.scaling.core.api.ScalingAPIFactory$RegistryCenterHolder.getInstance(ScalingAPIFactory.java:197)
        at org.apache.shardingsphere.scaling.core.api.ScalingAPIFactory.getRegistryCenter(ScalingAPIFactory.java:102)
        at org.apache.shardingsphere.scaling.core.executor.job.FinishedCheckJobExecutor.start(FinishedCheckJobExecutor.java:41)
        at org.apache.shardingsphere.scaling.core.api.ScalingWorker.init(ScalingWorker.java:50)
        at org.apache.shardingsphere.proxy.initializer.impl.GovernanceBootstrapInitializer.initScalingWorker(GovernanceBootstrapInitializer.java:136)
        at org.apache.shardingsphere.proxy.initializer.impl.AbstractBootstrapInitializer.init(AbstractBootstrapInitializer.java:76)
        at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:48)
[ERROR] 2021-10-19 17:43:34.092 [main] o.a.curator.CuratorZookeeperClient -
java.io.IOException: java.lang.IllegalArgumentException: Invalid path string "//19.1.72.12:2379" caused by empty node name specified @1
        at org.apache.curator.ConnectionState.close(ConnectionState.java:121)
        at org.apache.curator.CuratorZookeeperClient.close(CuratorZookeeperClient.java:243)
        at org.apache.curator.CuratorZookeeperClient.close(CuratorZookeeperClient.java:226)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.close(CuratorFrameworkImpl.java:402)
        at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.init(ZookeeperRegistryCenter.java:101)
        at org.apache.shardingsphere.scaling.core.api.ScalingAPIFactory$RegistryCenterHolder.createRegistryCenter(ScalingAPIFactory.java:206)
        at org.apache.shardingsphere.scaling.core.api.ScalingAPIFactory$RegistryCenterHolder.getInstance(ScalingAPIFactory.java:197)
        at org.apache.shardingsphere.scaling.core.api.ScalingAPIFactory.getRegistryCenter(ScalingAPIFactory.java:102)
        at org.apache.shardingsphere.scaling.core.executor.job.FinishedCheckJobExecutor.start(FinishedCheckJobExecutor.java:41)
        at org.apache.shardingsphere.scaling.core.api.ScalingWorker.init(ScalingWorker.java:50)
        at org.apache.shardingsphere.proxy.initializer.impl.GovernanceBootstrapInitializer.initScalingWorker(GovernanceBootstrapIni:

**Comment by penghuazhou** [comment]
shardingsphere-proxy 5.0.0 do not support etcd?

![image](https://user-images.githubusercontent.com/13001038/141420132-5ac332f7-0ffc-4099-9768-3bc9de2ca095.png)


[ERROR] 2021-11-12 14:20:58.597 [main] o.a.curator.CuratorZookeeperClient -
java.io.IOException: java.lang.IllegalArgumentException: Invalid path string "//
localhost:2379" caused by empty node name specified @1
        at org.apache.curator.ConnectionState.close(ConnectionState.java:121)
        at org.apache.curator.CuratorZookeeperClient.close(CuratorZookeeperClien
t.java:243)
        at org.apache.curator.CuratorZookeeperClient.close(CuratorZookeeperClien
t.java:226)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.close(CuratorF
rameworkImpl.java:402)
        at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryC
enter.init(ZookeeperRegistryCenter.java:101)
        at org.apache.shardingsphere.scaling.core.api.ScalingAPIFactory$Registry
CenterHolder.createRegistryCenter(ScalingAPIFactory.java:205)

**Comment by penghuazhou** [comment]
how can I user etcd in shardingsphere-5.0.0?

![image](https://user-images.githubusercontent.com/13001038/141421458-2764806e-754f-46cc-a5e0-b70d278f45ae.png)


[ERROR] 2021-11-12 14:20:58.597 [main] o.a.curator.CuratorZookeeperClient -
java.io.IOException: java.lang.IllegalArgumentException: Invalid path string "//
localhost:2379" caused by empty node name specified @1
        at org.apache.curator.ConnectionState.close(ConnectionState.java:121)
        at org.apache.curator.CuratorZookeeperClient.close(CuratorZookeeperClien
t.java:243)
        at org.apache.curator.CuratorZookeeperClient.close(CuratorZookeeperClien
t.java:226)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.close(CuratorF
rameworkImpl.java:402)
        at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryC
enter.init(ZookeeperRegistryCenter.java:101)
        at org.apache.shardingsphere.scaling.core.api.ScalingAPIFactory$Registry
CenterHolder.createRegistryCenter(ScalingAPIFactory.java:205)

**Comment by zjcnb** [comment]
![image](https://user-images.githubusercontent.com/33742097/141455945-5579cad8-2351-442d-a9c9-ef8d00d5c463.png)
@penghuazhou  Hi,  it 's seem to work well, Can you check your etcd?

**Comment by penghuazhou** [comment]
> ![image](https://user-images.githubusercontent.com/33742097/141455945-5579cad8-2351-442d-a9c9-ef8d00d5c463.png) @penghuazhou Hi, it 's seem to work well, Can you check your etcd?

Is it need other config?

**Comment by penghuazhou** [comment]
thanks
