### ISSUE TITLE
It error when use shardingsphere-agent.jar, why?

### ISSUE THREAD

**Issue by penghuazhou** [apache/shardingsphere#13153]
version: apache-shardingsphere-5.0.0-beta-src-release

<img width="956" alt="企业微信截图_04ad7b36-7375-4b41-9f0e-8e5eb8a6e275" src="https://user-images.githubusercontent.com/13001038/137901909-ff349f46-8bd1-4cf6-9648-a5ca0f60ab0d.png">

[ERROR] 2021-10-19 19:31:30.130 [epollEventLoopGroup-2-1] o.a.s.a.c.b.listener.LoggingListener - Failed to instrument io.netty.channel.ChannelFutureListener$1.
java.lang.NullPointerException: null
        at org.apache.shardingsphere.agent.core.plugin.PluginLoader$1.matches(PluginLoader.java:132)
        at org.apache.shardingsphere.agent.core.plugin.PluginLoader$1.matches(PluginLoader.java:128)
        at org.apache.shardingsphere.dependencies.net.bytebuddy.agent.builder.AgentBuilder$RawMatcher$ForElementMatchers.matches(AgentBuilder.java:1312)
        at org.apache.shardingsphere.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10343)
        at org.apache.shardingsphere.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10302)
        at org.apache.shardingsphere.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1600(AgentBuilder.java:10068)
        at org.apache.shardingsphere.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10687)
        at org.apache.shardingsphere.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10634)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.apache.shardingsphere.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10225)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at io.netty.channel.ChannelFutureListener.<clinit>(ChannelFutureListener.java:41)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:348)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

**Comment by dachuan9e** [comment]
@penghuazhou  Cloud you please confirm which version did you use?  If you build from src cloud you provide git commit info.

**Comment by penghuazhou** [comment]
> @penghuazhou Cloud you please confirm which version did you use? If you build from src cloud you provide git commit info.

build from source, version is :version: apache-shardingsphere-5.0.0-beta-src-release, i download the source from https://downloads.apache.org/shardingsphere/5.0.0-beta/apache-shardingsphere-5.0.0-beta-src.zip

**Comment by dachuan9e** [comment]
@penghuazhou Please use the recent code in branch master.

**Comment by penghuazhou** [comment]
> @penghuazhou Please use the recent code in branch master.

Does shardingsphere-proxy alse need recent code? because we want usr shardingsphere-proxy5.0.0 at November. does it will support in shardingsphere-proxy5.0.0?

**Comment by dachuan9e** [comment]
Do you mean the agent?

**Comment by dachuan9e** [comment]
If you use the master it maybe support now

**Comment by penghuazhou** [comment]
@dachuan9e But we will use it to prd environment, we need a release version。

**Comment by RaigorJiang** [comment]
Hi @penghuazhou 
5.0.0-RC1 is on the way.

![image](https://user-images.githubusercontent.com/5668787/138234009-f4897d55-79bd-4a7d-b3e2-8b04729069ee.png)



If you want to know the release news, subscribe mail list is the best way, please refer to:
https://shardingsphere.apache.org/community/cn/contribute/subscribe/

**Comment by penghuazhou** [comment]
thanks

**Comment by penghuazhou** [comment]
@RaigorJiang,  It can not work when i use shardingsphere-agent in shardingsphere-proxy 5.0.0, the error message is below, can you help me?
I use shardingsphere-agent refer to https://shardingsphere.apache.org/document/5.0.0/cn/features/governance/observability/agent/

[ERROR] 2021-11-15 11:31:49.599 [main] o.a.s.a.c.b.listener.LoggingListener -
Failed to instrument org.apache.shardingsphere.infra.metadata.schema.builder
.loader.dialect.OracleTableMetaDataLoader
java.lang.NullPointerException: null
at org.apache.shardingsphere.agent.core.plugin.ApmPluginLoader$1.matc
hes(ApmPluginLoader.java:134)
at org.apache.shardingsphere.agent.core.plugin.ApmPluginLoader$1.matc
hes(ApmPluginLoader.java:130)
at org.apache.shardingsphere.dependencies.net.bytebuddy.agent.builder
.AgentBuilder$RawMatcher$ForElementMatchers.matches(AgentBuilder.java:1828)
at org.apache.shardingsphere.dependencies.net.bytebuddy.agent.builder
.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:1133
9)
at org.apache.shardingsphere.dependencies.net.bytebuddy.agent.builder
.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:11298)
at org.apache.shardingsphere.dependencies.net.bytebuddy.agent.builder
.AgentBuilder$Default$ExecutingTransformer.access$1700(AgentBuilder.java:1101
6)
at org.apache.shardingsphere.dependencies.net.bytebuddy.agent.builder

**Comment by RaigorJiang** [comment]
Hi @penghuazhou 
thanks for your feedback, @dachuan9e please help :)

**Comment by dachuan9e** [comment]
Do you add some interceptor for 'org.apache.shardingsphere.infra.metadata.schema.builder
.loader.dialect.OracleTableMetaDataLoader' ? @penghuazhou

**Comment by penghuazhou** [comment]
@dachuan9e, I am not add some interceptor.

**Comment by penghuazhou** [comment]
I can work now, thanks.

**Comment by dachuan9e** [comment]
You are welcome.
