### ISSUE TITLE
Use BoundaryBasedRangeShardingAlgorithm,get error "java.lang.Integer cannot be cast to java.lang.Long"

### ISSUE THREAD

**Issue by yinyanghuafa** [apache/shardingsphere#13167]
## Question

I use BoundaryBasedRangeShardingAlgorithm in shardingsphere-proxy,  the version is 5.0.0-beta ,and config is :

schemaName:sharding_db
dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/testdatabase1?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/testdatabase2?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
rules:
  !SHARDING
    tables:
      t_order:
        actualDataNodes: ds_${0..1}.t_order
        tableStrategy:
        keyGenerateStrategy:
    bindingTables:
      t_order
    defaultDatabaseStrategy:
      standard:
        shardingColumn: order_id
        shardingAlgorithmName: org.apache.shardingsphere.sharding.algorithm.sharding.range.BoundaryBasedRangeShardingAlgorithm
    defaultTableStrategy:
      none:
    shardingAlgorithms:
      org.apache.shardingsphere.sharding.algorithm.sharding.range.BoundaryBasedRangeShardingAlgorithm:
        type: BOUNDARY_RANGE
        props:
          sharding-ranges: 10
    keyGenerators:
      snowflake:
        type: SNOWFLAKE
        props:
          worker-id: 123

and create sql is :  create table t_order(user_id bigint,order_id bigint);
then i execute the sql : select * from t_order where order_id=1 
and  met the problem : 
`[ERROR] 2021-10-20 12:28:18.457 [Connection-1-ThreadExecutor] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at org.apache.shardingsphere.sharding.algorithm.sharding.range.AbstractRangeShardingAlgorithm.lambda$doSharding$0(AbstractRangeShardingAlgorithm.java:54)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.apache.shardingsphere.sharding.algorithm.sharding.range.AbstractRangeShardingAlgorithm.doSharding(AbstractRangeShardingAlgorithm.java:54)
	at org.apache.shardingsphere.sharding.route.strategy.type.standard.StandardShardingStrategy.doSharding(StandardShardingStrategy.java:68)
	at org.apache.shardingsphere.sharding.route.strategy.type.standard.StandardShardingStrategy.doSharding(StandardShardingStrategy.java:57)
	at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.routeDataSources(ShardingStandardRoutingEngine.java:207)
	at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.route0(ShardingStandardRoutingEngine.java:195)
	at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.routeByShardingConditionsWithCondition(ShardingStandardRoutingEngine.java:118)
	at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.routeByShardingConditions(ShardingStandardRoutingEngine.java:111)
	at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.getDataNodes(ShardingStandardRoutingEngine.java:88)
	at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.route(ShardingStandardRoutingEngine.java:70)
	at org.apache.shardingsphere.sharding.route.engine.ShardingSQLRouter.createRouteContext(ShardingSQLRouter.java:56)`

I met the same prolem in version 5.0.0-RC1-SNAPSHOT,please give me some advice.

**Comment by lanchengx** [comment]
Hi @yinyanghuafa , thanks for your feedback, this should be a bug, we will fix it later, or you can try it.

**Comment by strongduanmu** [comment]
@yinyanghuafa Thank you very much for your feedback. I have submitted a PR to fix this problem. After the PR is merged, can you use the master branch to help test it?
