### ISSUE TITLE
Cannot find transaction manager of [BASE]

### ISSUE THREAD

**Issue by rmzf9192** [apache/shardingsphere#13433]
java.lang.NullPointerException: Cannot find transaction manager of [BASE]
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:923) ~[guava-30.0-jre.jar!/:?]
	at org.apache.shardingsphere.transaction.ShardingTransactionManagerEngine.getTransactionManager(ShardingTransactionManagerEngine.java:88) ~[sharding-transaction-core-4.1.1.jar!/:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.connection.ShardingConnection.<init>(ShardingConnection.java:55) ~[sharding-jdbc-core-4.1.1.jar!/:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.datasource.ShardingDataSource.getConnection(ShardingDataSource.java:65) ~[sharding-jdbc-core-4.1.1.jar!/:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.datasource.ShardingDataSource.getConnection(ShardingDataSource.java:40) ~[sharding-jdbc-core-4.1.1.jar!/:4.1.1]
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122) ~[hibernate-core-5.4.28.Final.jar!/:5.4.28.Final]
	at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38) ~[hibernate-core-5.4.28.Final.jar!/:5.4.28.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:108) ~[hibernate-core-5.4.28.Final.jar!/:5.4.28.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:138) ~[hibernate-core-5.4.28.Final.jar!/:5.4.28.Final]
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:50) ~[hibernate-core-5.4.28.Final.jar!/:5.4.28.Final]
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:149) ~[hibernate-core-5.4.28.Final.jar!/:5.4.28.Final]
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176) ~[hibernate-core-5.4.28.Final.jar!/:5.4.28.Final]
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:151) ~[hibernate-core-5.4.28.Final.jar!/:5.4.28.Final]
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:2103) ~[hibernate-core-5.4.28.Final.jar!/:5.4.28.Final]
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2040) ~[hibernate-core-5.4.28.Final.jar!/:5.4.28.Final]
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2018) ~[hibernate-core-5.4.28.Final.jar!/:5.4.28.Final]

**Comment by menghaoranss** [comment]
could you provide your configurations?

**Comment by rmzf9192** [comment]
#################################### spring配置   start  ####################################
spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    dataSource:
      names: yst-yym    
      yst-yym:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbcUrl: XXXX
        username: XXXX
        password: XXXXX
        # 初始化连接池超时时间
        initializationFailTimeout: 60000
        # 等待从连接池中获取连接的时间，毫秒
        connectionTimeout: 20000
        # 连接池最大连接数
        maximumPoolSize: 200
        # 泄露检测的时间间隔（距离从连接池离开）
        leakDetectionThreshold: 6000
        # 连接池最小数量
        minimumIdle: 50
    props:
      sql:
        show: true
      max:
        connections:
          size:
            per:
              query: 50

**Comment by rmzf9192** [comment]
That problem has been solved
