### ISSUE TITLE
Sharding Scaling dataSource connection is not released when execute check scaling xxxx command

### ISSUE THREAD

**Issue by wangeDear** [apache/shardingsphere#13434]
5.0.0-RC ShardingSphere-Proxy

dataSource connection is not released

log：
[ERROR] 2021-11-02 19:00:02.427 [_finished_check_Worker-1] o.a.s.s.core.job.FinishedCheckJob - scaling job 662316049231773697 finish check failed!
org.apache.shardingsphere.scaling.core.common.exception.DataCheckFailException: get table columns failed
	at org.apache.shardingsphere.scaling.core.job.check.consistency.DataConsistencyCheckerImpl.getTablesColumnNamesMap(DataConsistencyCheckerImpl.java:163)
	at org.apache.shardingsphere.scaling.core.job.check.consistency.DataConsistencyCheckerImpl.dataCheck(DataConsistencyCheckerImpl.java:115)
	at org.apache.shardingsphere.scaling.core.api.impl.ScalingAPIImpl.dataConsistencyCheck0(ScalingAPIImpl.java:190)
	at org.apache.shardingsphere.scaling.core.api.impl.ScalingAPIImpl.dataConsistencyCheck(ScalingAPIImpl.java:174)
	at org.apache.shardingsphere.scaling.core.job.FinishedCheckJob.dataConsistencyCheck(FinishedCheckJob.java:73)
	at org.apache.shardingsphere.scaling.core.job.FinishedCheckJob.execute(FinishedCheckJob.java:59)
	at org.apache.shardingsphere.elasticjob.simple.executor.SimpleJobExecutor.process(SimpleJobExecutor.java:33)
	at org.apache.shardingsphere.elasticjob.simple.executor.SimpleJobExecutor.process(SimpleJobExecutor.java:29)
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.process(ElasticJobExecutor.java:177)
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.process(ElasticJobExecutor.java:147)
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.execute(ElasticJobExecutor.java:130)
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.execute(ElasticJobExecutor.java:106)
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.LiteJob.execute(LiteJob.java:35)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.sql.SQLSyntaxErrorException: SELECT command denied to user 'test'@'' for table 'checksums'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1202)
	at com.mysql.cj.jdbc.DatabaseMetaData$2.forEach(DatabaseMetaData.java:2159)
	at com.mysql.cj.jdbc.DatabaseMetaData$2.forEach(DatabaseMetaData.java:2088)
	at com.mysql.cj.jdbc.IterateBlock.doForAll(IterateBlock.java:56)
	at com.mysql.cj.jdbc.DatabaseMetaData.getColumns(DatabaseMetaData.java:2264)
	at com.zaxxer.hikari.pool.ProxyDatabaseMetaData.getColumns(ProxyDatabaseMetaData.java:90)
	at com.zaxxer.hikari.pool.HikariProxyDatabaseMetaData.getColumns(HikariProxyDatabaseMetaData.java)
	at org.apache.shardingsphere.driver.jdbc.core.datasource.metadata.ShardingSphereDatabaseMetaData.getColumns(ShardingSphereDatabaseMetaData.java:121)
	at org.apache.shardingsphere.scaling.core.job.check.consistency.DataConsistencyCheckerImpl.getTablesColumnNamesMap(DataConsistencyCheckerImpl.java:156)
	... 14 common frames omitted

**Comment by menghaoranss** [comment]
@sandynz could you have a look here.

**Comment by sandynz** [comment]
Hi @ccw55ccw ,  it seems no `SELECT` permission for `test` account from error log:
> Caused by: java.sql.SQLSyntaxErrorException: SELECT command denied to user 'test'@'' for table 'checksums'

Could you check MySQL `test` account's permissions, e.g. execute following SQL:
```
show grants for 'test'@'';
```

**Comment by ccw55ccw** [comment]
> Hi @ccw55ccw , it seems no `SELECT` permission for `test` account from error log:
> 
> > Caused by: java.sql.SQLSyntaxErrorException: SELECT command denied to user 'test'@'' for table 'checksums'
> 
> Could you check MySQL `test` account's permissions, e.g. execute following SQL:
> 
> ```
> show grants for 'test';
> ```

mysql> show grants for 'test';
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Grants for test@%                                                                                                                                                                                                                                                                                                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| GRANT INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, SHUTDOWN, PROCESS, FILE, REFERENCES, INDEX, ALTER, SHOW DATABASES, SUPER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER, CREATE TABLESPACE ON *.* TO 'test'@'%' WITH GRANT OPTION |

**Comment by ccw55ccw** [comment]
after check scaling XXX is executed connection will not be release and no exceptions

**Comment by ccw55ccw** [comment]
![image](https://user-images.githubusercontent.com/9948504/140243229-7027abed-fc86-44d6-bdc5-3ade9bb6985d.png)
![image](https://user-images.githubusercontent.com/9948504/140243254-631f2443-8242-48d9-9eb5-5a33f64fd4db.png)
![image](https://user-images.githubusercontent.com/9948504/140243272-86c870fa-9b5e-47a6-a767-a67576ddea63.png)

The mysql connection pool will be full in one night

**Comment by sandynz** [comment]
@ccw55ccw You could add `SELECT` permission for `test` account, e.g.
```
grant SELECT on *.* to 'test';
```

Thanks for your feedback, I'll investigate the connection pool issue.

**Comment by ccw55ccw** [comment]
> @ccw55ccw You could add `SELECT` permission for `test` account, e.g.
> 
> ```
> grant SELECT on *.* to 'test';
> ```
> 
> Thanks for your feedback, I'll investigate the connection pool issue.

I found out through debugging that the lower version of Atomikos may cause connection leaks.
when i replace another version of Atomikos 5.0.8 the connection leaks  didn't not happened.

**Comment by sandynz** [comment]
> I found out through debugging that the lower version of Atomikos may cause connection leaks. when i replace another version of Atomikos 5.0.8 the connection leaks did not happened.

@ccw55ccw Thanks for sharing.

I tested with version `4.0.6` and `5.0.8`, that's true. I found the code difference of these two versions.

In XATransactionalResource.setRecoveryService (version 4.0.6)
```
	public void setRecoveryService ( RecoveryService recoveryService )
            throws ResourceException
    {
        if ( recoveryService != null ) {
            if ( LOGGER.isTraceEnabled() ) LOGGER.logTrace ( "Installing recovery service on resource "
                    + getName () );
            this.branchIdentifier=recoveryService.getName();
            recover();
        }
    }
```

In XATransactionalResource.setRecoveryService (version 5.0.8)
```
	public void setRecoveryService ( RecoveryService recoveryService )
            throws ResourceException
    {
        if ( recoveryService != null ) {
            if ( LOGGER.isTraceEnabled() ) LOGGER.logTrace ( "Installing recovery service on resource "
                    + getName () );
            this.branchIdentifier=recoveryService.getName();
        }
    }
```
Invocation of `recover()` is the difference.

Part of stack trace of new connection created in version 4.0.6:
```
"Connection-1-ThreadExecutor@6093" prio=10 tid=0x34 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:124)
	  at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:107)
	  at com.mysql.jdbc.jdbc2.optional.MysqlXADataSource.getXAConnection(MysqlXADataSource.java:46)
	  at com.atomikos.datasource.xa.jdbc.JdbcTransactionalResource.createXAConnection(JdbcTransactionalResource.java:167)
	  at com.atomikos.datasource.xa.jdbc.JdbcTransactionalResource.refreshXAConnection(JdbcTransactionalResource.java:100)
	  - locked <0x2b98> (a org.apache.shardingsphere.transaction.xa.atomikos.manager.AtomikosXARecoverableResource)
	  at com.atomikos.datasource.xa.XATransactionalResource.refreshXAResource(XATransactionalResource.java:459)
	  at com.atomikos.datasource.xa.XATransactionalResource.getXAResource(XATransactionalResource.java:315)
	  at com.atomikos.datasource.xa.XATransactionalResource.recover(XATransactionalResource.java:449)
	  at com.atomikos.datasource.xa.XATransactionalResource.setRecoveryService(XATransactionalResource.java:416)
	  at com.atomikos.icatch.config.Configuration.addResource(Configuration.java:249)
	  - locked <0x1d15> (a java.lang.Class)
	  at com.atomikos.icatch.config.UserTransactionServiceImp.registerResource(UserTransactionServiceImp.java:124)
	  at org.apache.shardingsphere.transaction.xa.atomikos.manager.AtomikosTransactionManagerProvider.registerRecoveryResource(AtomikosTransactionManagerProvider.java:51)
	  at org.apache.shardingsphere.transaction.xa.jta.datasource.XATransactionDataSource.<init>(XATransactionDataSource.java:65)
	  at org.apache.shardingsphere.transaction.xa.XAShardingSphereTransactionManager.newXATransactionDataSource(XAShardingSphereTransactionManager.java:62)
```

I had a short look at Atomikos [Release Notes](https://www.atomikos.com/Main/ReleaseNotes) and [TransactionsEssentials 5.0](https://www.atomikos.com/Blog/TransactionsEssentials5dot0), it need more investigation of upgrading atomikos version.

Upgrade atomikos may be the easiest way, I'm considering other ways too.

**Comment by sandynz** [comment]
Atomikos version is upgraded for now.

There is another way: Disable XA for scaling when initializing `ShardingSphereDataSource`, it need to extend `ContextManagerBuilder`, I'll investigate it later.
