### ISSUE TITLE
shardingjdbc encrypt null exception

### ISSUE THREAD

**Issue by Dr-wgy** [apache/shardingsphere#13484]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

        <shardingsphere.version>4.0.0-RC2</shardingsphere.version>

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 
### Expected behavior
no exception

### Actual behavior
Caused by: java.lang.NullPointerException: null
	at org.apache.shardingsphere.shardingjdbc.jdbc.adapter.AbstractStatementAdapter$1.execute(AbstractStatementAdapter.java:59)
	at org.apache.shardingsphere.shardingjdbc.jdbc.adapter.AbstractStatementAdapter$1.execute(AbstractStatementAdapter.java:55)
	at org.apache.shardingsphere.shardingjdbc.jdbc.adapter.executor.ForceExecuteTemplate.execute(ForceExecuteTemplate.java:44)
	at org.apache.shardingsphere.shardingjdbc.jdbc.adapter.AbstractStatementAdapter.close(AbstractStatementAdapter.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:78)
	at com.sun.proxy.$Proxy138.close(Unknown Source)
	at org.apache.ibatis.executor.BaseExecutor.closeStatement(BaseExecutor.java:285)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:52)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy136.update(Unknown Source)

**Comment by wuguanyu** [comment]
![image](https://user-images.githubusercontent.com/24486917/140605480-c42c18de-f421-489d-babb-f9b52593d952.png)

**Comment by strongduanmu** [comment]
@wuguanyu Can you try the latest version? `4.0.0-RC2` is too old.

**Comment by wuguanyu** [comment]
@strongduanmu  maybe imcompatible with mysql jdbc connection 6.0.6 ,I use 4.0.1  It worked 
Can we provide some best compatible with  mysql jdbc connection and ShardingSphere-JDBC

**Comment by strongduanmu** [comment]
@wuguanyu I think the version of the mysql driver should be the same with database, and shardingsphere has no special requirements.
