### ISSUE TITLE
Can MySQL keyword query be supported？

### ISSUE THREAD

**Issue by Un-use** [apache/shardingsphere#13509]
this is a SQL，

> SELECT 'name', 'desc' FROM t1   (' is`)

it be rewirte to

> SELECT 'name' AS name, 'desc' AS desc FROM t1    (' is`)

but this SQL is error, because 'name', 'desc' is MySQL keword，
how to solve this error？

**Comment by strongduanmu** [comment]
@Un-use Can you try the latest version?

**Comment by Un-use** [comment]
5.0.0-beta？ not support

**Comment by Un-use** [comment]
> Logic SQL: SELECT * FROM t1
> SQLStatement: MySQLSelectStatement(limit=Optional.empty, lock=Optional.empty)
> Actual SQL: logic_db ::: SELECT id, name AS name, prevent AS prevent, desc AS desc FROM t1

log like this

**Comment by strongduanmu** [comment]
@tuichenchuxin Can you help check this issue?

**Comment by tuichenchuxin** [comment]
OK, I'll check this issue.

**Comment by tuichenchuxin** [comment]
@Un-use can you offer me your config and the table create sql?
I have tried on 5.0.0-beta, ``` select * from t1 ``` can be used well.

**Comment by Un-use** [comment]
### config：
rules:
  - !ENCRYPT
    encryptors:
      encryptor_custom:
        type: custom
    tables:
      t1:
        columns:
          name:
            plainColumn: name
            cipherColumn: nameCipher
            encryptorName: encryptor_custom
          desc:
            plainColumn: desc
            cipherColumn: descCipher
            encryptorName: encryptor_custom
    queryWithCipherColumn: false

### table：
CREATE TABLE `t1` (
  `id` double unsigned NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `nameCipher` varchar(255) DEFAULT NULL,
  `desc` varchar(500) DEFAULT NULL,
  `descCipher` varchar(1536) DEFAULT NULL
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

### log like this：
> Logic SQL: SELECT * FROM `t1`
> SQLStatement: MySQLSelectStatement(limit=Optional.empty, lock=Optional.empty, window=Optional.empty)
> Actual SQL: logic_db ::: SELECT `t1`.`id`, `t1`.`name` AS name, `t1`.`desc` AS desc FROM `t1`

### error info
 Cause: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:434)
	... 60 common frames omitted
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.apache.shardingsphere.infra.merge.MergeEngine.merge(MergeEngine.java:78)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.mergeQuery(ShardingSpherePreparedStatement.java:379)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.getResultSet(ShardingSpherePreparedStatement.java:324)
	at io.opentracing.contrib.jdbc.TracingStatement.getResultSet(TracingStatement.java:170)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getFirstResultSet(DefaultResultSetHandler.java:226)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:176)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy216.query(Unknown Source)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	... 66 common frames omitted

**Comment by tuichenchuxin** [comment]
@Un-use Thank you for your feedback. There is indeed a problem when using keywords as fields. I'll try to fix it later.
