### ISSUE TITLE
Have a mistake when encryptor-name value contain  '_' .

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#13564]
refer to: #13554 

### Which version of ShardingSphere did you use?

master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC 

### Expected behavior

start up success.

### Actual behavior

```
Caused by: java.lang.IllegalArgumentException: aes-key-value can not be null.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:217) ~[guava-29.0-jre.jar:na]
	at org.apache.shardingsphere.encrypt.algorithm.AESEncryptAlgorithm.createSecretKey(AESEncryptAlgorithm.java:57) ~[shardingsphere-encrypt-core-5.0.0-RC1-SNAPSHOT.jar:5.0.0-RC1-SNAPSHOT]
	at org.apache.shardingsphere.encrypt.algorithm.AESEncryptAlgorithm.init(AESEncryptAlgorithm.java:53) ~[shardingsphere-encrypt-core-5.0.0-RC1-SNAPSHOT.jar:5.0.0-RC1-SNAPSHOT]
	at org.apache.shardingsphere.spring.boot.registry.AbstractAlgorithmProvidedBeanRegistry.postProcessAfterInitialization(AbstractAlgorithmProvidedBeanRegistry.java:98) ~[shardingsphere-jdbc-spring-boot-starter-infra-5.0.0-RC1-SNAPSHOT.jar:5.0.0-RC1-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:437) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602) ~[spring-beans-5.3.7.jar:5.3.7]
	... 123 common frames omitted
```

### Reason analyze (If you can)

`spring.shardingsphere.rules.encrypt.tables.t_address.columns.address_name.encryptor-name` value not contain  _ 
such as : `encryptor_aes`

**Comment by zjcnb** [comment]
Duplicate issue #8382. close it.
