### ISSUE TITLE
DatabaseTypeRecognizer.getDatabaseType(final DataSource dataSource) return null when SQLException happen

### ISSUE THREAD

**Issue by ningpp** [apache/shardingsphere#13659]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0,  master

### Expected behavior
 throw new IllegalStateException ...

### Actual behavior
return 

### Reason analyze (If you can)
when i write a wrong jdbc url ( mistake ),  the error log is not good .
log like this 

Caused by: java.lang.IllegalStateException: Database type inconsistent with 'org.apache.shardingsphere.infra.database.type.dialect.MySQLDatabaseType@1da53f4f' and 'null'
	at com.google.common.base.Preconditions.checkState(Preconditions.java:826) ~[guava-30.1.1-jre.jar:?]
	at org.apache.shardingsphere.infra.database.type.DatabaseTypeRecognizer.getDatabaseType(DatabaseTypeRecognizer.java:45) ~[shardingsphere-infra-common-5.0.0.jar:5.0.0]
	at org.apache.shardingsphere.infra.rule.builder.schema.SchemaRulesBuilder.buildRules(SchemaRulesBuilder.java:69) ~[shardingsphere-infra-common-5.0.0.jar:5.0.0]
	at org.apache.shardingsphere.mode.manager.memory.MemoryContextManagerBuilder.build(MemoryContextManagerBuilder.java:53) ~[shardingsphere-memory-mode-core-5.0.0.jar:5.0.0]
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.createContextManager(ShardingSphereDataSource.java:75) ~[shardingsphere-jdbc-core-5.0.0.jar:5.0.0]
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.<init>(ShardingSphereDataSource.java:61) ~[shardingsphere-jdbc-core-5.0.0.jar:5.0.0]
	at org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactory.createDataSource(ShardingSphereDataSourceFactory.java:79) ~[shardingsphere-jdbc-core-5.0.0.jar:5.0.0]

**Comment by menghaoranss** [comment]
@ningpp do you have any suggestions?

**Comment by ningpp** [comment]
what about throw new IllegalStateException ?

**Comment by ningpp** [comment]
hello?

**Comment by terrymanu** [comment]
@ningpp Yes, it is better to throw IllegalArgumentException than return null.
Could you try to submit a pull request?

**Comment by ningpp** [comment]
OK
