### ISSUE TITLE
whether to support  query  information_schrma？sharding-jdbc5.0.0

### ISSUE THREAD

**Issue by xfzhaoGit** [apache/shardingsphere#13739]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by xfzhaoGit** [comment]
![Uploading EBEDD196-C04B-4934-B148-34BBAB70BD92.jpeg…]()

**Comment by RaigorJiang** [comment]
Hi @xfzhaoGit 
ShardingSphere-JDBC does not yet support querying information_schrma.
By the way, your picture cannot be displayed, can you describe your scene?

**Comment by xfzhaoGit** [comment]
There is a scenario in my project to determine whether the database table exists, I need to use the information_schema database, but shardingsphere reports an error message, and the information_schema does not exist。

**Comment by xfzhaoGit** [comment]
![Uploading B859C907-C0BD-46D0-A594-17AFEC1303BF.jpeg…]()

**Comment by xfzhaoGit** [comment]
![Uploading DCB4ACCF-89C7-4BD8-A8D8-751FB4A8B0D6.jpeg…]()

> ``

**Comment by RaigorJiang** [comment]
Because ShardingSphere uses logical schemas and  logical tables to handle distributed tasks.
Can `show databases` and `show tables` meet your requirements?

**Comment by xfzhaoGit** [comment]
for queries like this I try not to use sharding, is there a similar configuration?

**Comment by RaigorJiang** [comment]
No, because information_schrma is not a logical database, ShardingSphere does not know which actual node the user wants to query.

**Comment by xfzhaoGit** [comment]
In my project, I use single database and partial table sharding, and  I dont think sharding is used for the query and other operation of non-sharded tables. Is there an example of this?

**Comment by RaigorJiang** [comment]
> In my project, I use single database and partial table sharding, and I dont think sharding is used for the query and other operation of non-sharded tables. Is there an example of this?

The non-sharding tables does not need to be configured, ShardingSphere will recognize them. You can see those tables through `show tables`.

**Comment by xfzhaoGit** [comment]
ok thanks

**Comment by xsong123** [comment]
'show tables like ...' sql still error:
com.google.common.util.concurrent.UncheckedExecutionException: org.apache.shardingsphere.sql.parser.exception.SQLParsingException: You have an error in your SQL syntax
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
	at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserEngine.parse(SQLStatementParserEngine.java:48)
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine.parse0(ShardingSphereSQLParserEngine.java:71)
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine.parse(ShardingSphereSQLParserEngine.java:60)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.<init>(ShardingSpherePreparedStatement.java:157)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.<init>(ShardingSpherePreparedStatement.java:128)
	at org.apache.shardingsphere.driver.jdbc.core.connection.ShardingSphereConnection.prepareStatement(ShardingSphereConnection.java:78)

Caused by: org.apache.shardingsphere.sql.parser.exception.SQLParsingException: You have an error in your SQL syntax
	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.twoPhaseParse(SQLParserExecutor.java:68)
	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.parse(SQLParserExecutor.java:49)
	at org.apache.shardingsphere.sql.parser.api.SQLParserEngine.parse(SQLParserEngine.java:51)
	at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserExecutor.parse(SQLStatementParserExecutor.java:47)
	at org.apache.shardingsphere.infra.parser.cache.SQLStatementCacheLoader.load(SQLStatementCacheLoader.java:40)
	at org.apache.shardingsphere.infra.parser.cache.SQLStatementCacheLoader.load(SQLStatementCacheLoader.java:29)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 78 more

**Comment by RaigorJiang** [comment]
> 'show tables like ...' sql still error:
com.google.common.util.concurrent.UncheckedExecutionException: org.apache.shardingsphere.sql.parser.exception.SQLParsingException: You have an error in your SQL syntax

Hi @xsong123 
Looks like a parsing problem, you can create a new issue.
