### ISSUE TITLE
5.0.0---Querying data from multiple tables results in null pointers

### ISSUE THREAD

**Issue by majian-spc** [apache/shardingsphere#13772]
## Question

`### Error querying database.  Cause: java.lang.NullPointerException
### Cause: java.lang.NullPointerException

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.NullPointerException
`

`Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.NullPointerException
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 98 common frames omitted
Caused by: java.lang.NullPointerException: null`

**Comment by RaigorJiang** [comment]
Hello @majian-spc ,
for English only, please translate the title, thank you

**Comment by strongduanmu** [comment]
Hi @majian-spc Can you submit an issue according to the bug template? From your issue, I can't get any meaningful information.

**Comment by Comven** [comment]
In my case, NullPointerException appears when sorting the query result set .I don't know if it belongs to the same problem  #13544

**Comment by terrymanu** [comment]
It looks like the exception thrown from MyBatis.
There are no enough information during this issue, I just close it.
