### ISSUE TITLE
refreshMetaData

### ISSUE THREAD

**Issue by xsong123** [apache/shardingsphere#13853]
version:
shardingsphere5.0.0
mysql5.7

procedure:
two app link to the same db, one create table  in the db, another query included the table from the db .

error:
java.lang.NullPointerException
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.getOrderValuesCaseSensitiveFromTables(OrderByValue.java:74)
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.getOrderValuesCaseSensitive(OrderByValue.java:64)
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.<init>(OrderByValue.java:58)
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByStreamMergedResult.orderResultSetsToQueue(OrderByStreamMergedResult.java:56)
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByStreamMergedResult.<init>(OrderByStreamMergedResult.java:50)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByStreamMergedResult.<init>(GroupByStreamMergedResult.java:52)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.getGroupByMergedResult(ShardingDQLResultMerger.java:108)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.build(ShardingDQLResultMerger.java:78)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.merge(ShardingDQLResultMerger.java:63)
	at org.apache.shardingsphere.infra.merge.MergeEngine.executeMerge(MergeEngine.java:90)
	at org.apache.shardingsphere.infra.merge.MergeEngine.merge(MergeEngine.java:80)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.mergeQuery(ShardingSpherePreparedStatement.java:393)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.executeQuery(ShardingSpherePreparedStatement.java:182)

**Comment by lanchengx** [comment]
Hi @xsong123 , Which one of proxy and jdbc are you using? 
In addition, is the DDL statement executed by proxy?

**Comment by xsong123** [comment]
i don't use proxy, only use jdbc

**Comment by lanchengx** [comment]
In the latest master branch, `Proxy` already supports the use of `DistSQL` to refresh metadata, but `JDBC` is being planned

**Comment by menghaoranss** [comment]
@xsong123 do you use zookeeper?

**Comment by terrymanu** [comment]
@xsong123 Hi, could you change the title for search friendly?

**Comment by terrymanu** [comment]
Because of no response anymore, I just close this issue.

**Comment by xsong123** [comment]
zookeeper can synchronous refreshMetaData ???
