### ISSUE TITLE
Load database server info failed.

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#13872]
### Which version of ShardingSphere did you use?

`master`

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

`ShardingSphere-Proxy`

### Expected behavior

No error message

### Actual behavior

```
Exception in thread "main" org.apache.shardingsphere.infra.exception.ShardingSphereException: Load database server info failed:
	at org.apache.shardingsphere.proxy.database.DatabaseServerInfo.<init>(DatabaseServerInfo.java:44)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.lambda$setDatabaseServerInfo$0(BootstrapInitializer.java:96)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.setDatabaseServerInfo(BootstrapInitializer.java:95)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.init(BootstrapInitializer.java:71)
	at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:47)
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 3001ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:689)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
	at org.apache.shardingsphere.proxy.database.DatabaseServerInfo.<init>(DatabaseServerInfo.java:39)
	... 5 more
```

`config-database-discovery.yaml`

```
schemaName: database_discovery_db

dataSources:
  ds_0:
    url: jdbc:postgresql://127.0.0.1:15400/sbtest
    username: test
    password: 123456
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:postgresql://127.0.0.1:15400/sbtest
    username: test
    password: 123456
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !DB_DISCOVERY
  dataSources:
    pr_ds:
      dataSourceNames:
        - ds_0
        - ds_1
      discoveryTypeName: openGauss
  discoveryTypes:
    openGauss:
      type: openGauss
      props:
        zkServerLists: 'localhost:2181'
        keepAliveCron: '0/5 * * * * ?'
```
`server.yaml : `

```
rules:
  - !AUTHORITY
    users:
      - root@%:root
      - sharding@:sharding
    provider:
      type: ALL_PRIVILEGES_PERMITTED


props:
  max-connections-size-per-query: 1
  sql-show: true
```

**Comment by zjcnb** [comment]
I adjust `connectionTimeoutMilliseconds` param, is ok.
