### ISSUE TITLE
select subquery Bug

### ISSUE THREAD

**Issue by userkdg** [apache/shardingsphere#13940]
### Which version of ShardingSphere did you use?
5.0.0-GA

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior

select count(0) as cnt from ( select address_cipher as address from ec_oms_order ) as tmp;

### Actual behavior

select count(0) as cnt from ( select address from ec_oms_order ) as tmp;

### Reason analyze (If you can)

sql parser failed , not supported subquery select on encrypt tables

### Example codes for reproduce this issue (such as a github link).
```
MySQL [ec_order_db]> preview select count(0) as cnt from ( select address from ec_oms_order ) as tmp;
+------------------+-------------------------------------------------------------------------+
| data_source_name | sql                                                                     |
+------------------+-------------------------------------------------------------------------+
| ec_order_ds      | select count(0) as cnt from ( select address from ec_oms_order ) as tmp |
+------------------+-------------------------------------------------------------------------+
```

**Comment by userkdg** [comment]
please ,every boss how to deal

**Comment by strongduanmu** [comment]
Hi @userkdg, thank you for your feedback, I will check this issue.

**Comment by strongduanmu** [comment]
Hi @userkdg, I have tested this issue on version 5.0.0 and this is indeed a bug. The latest master branch has fixed this problem, welcome to test.

**Comment by userkdg** [comment]
> Hi @userkdg, I have tested this issue on version 5.0.0 and this is indeed a bug. The latest master branch has fixed this problem, welcome to test.

...the case, i git pull the lastest master branch, then shardingsphere-proxy-distribution build docker image, container, but the **bug still exists**.....

**Comment by userkdg** [comment]
> Hi @userkdg, I have tested this issue on version 5.0.0 and this is indeed a bug. The latest master branch has fixed this problem, welcome to test.

i try found the fixed commit - revision number 【b8db81f51e533773a8992c4909cc4f623279a356 】, message 【optimize encrypt subquery projection rewrite logic (#13643)】, but not fix it .

**Comment by strongduanmu** [comment]
@userkdg This is the result of my test, and no exception was found.

```
[INFO ] 2021-12-07 09:17:23.323 [Connection-1-ThreadExecutor] ShardingSphere-SQL - Logic SQL: select count(0) as cnt from (select order_id from t_encrypt) as tmp
[INFO ] 2021-12-07 09:17:23.324 [Connection-1-ThreadExecutor] ShardingSphere-SQL - SQLStatement: MySQLSelectStatement(limit=Optional.empty, lock=Optional.empty, window=Optional.empty)
[INFO ] 2021-12-07 09:17:23.324 [Connection-1-ThreadExecutor] ShardingSphere-SQL - Actual SQL: ds_1 ::: select count(0) as cnt from (select order_cipher AS order_id from t_encrypt) as tmp
```

**Comment by userkdg** [comment]
> @userkdg This is the result of my test, and no exception was found.
> 
> ```
> [INFO ] 2021-12-07 09:17:23.323 [Connection-1-ThreadExecutor] ShardingSphere-SQL - Logic SQL: select count(0) as cnt from (select order_id from t_encrypt) as tmp
> [INFO ] 2021-12-07 09:17:23.324 [Connection-1-ThreadExecutor] ShardingSphere-SQL - SQLStatement: MySQLSelectStatement(limit=Optional.empty, lock=Optional.empty, window=Optional.empty)
> [INFO ] 2021-12-07 09:17:23.324 [Connection-1-ThreadExecutor] ShardingSphere-SQL - Actual SQL: ds_1 ::: select count(0) as cnt from (select order_cipher AS order_id from t_encrypt) as tmp
> ```

thinks，i check it on local env，success ! but had a new issue now 

 on my build docker container，when  ** mysql -hxxx -P53308 -uroot -pxxx ** connect to proxy，then not login command line , the proxy console print  the error：
``` 
02:05:38.752 [epollEventLoopGroup-3-1] DEBUG org.apache.shardingsphere.db.protocol.codec.PacketCodec - Read from client 9b9c9754 :
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 21 00 00 00 03 73 65 6c 65 63 74 20 40 40 76 65 |!....select @@ve|
|00000010| 72 73 69 6f 6e 5f 63 6f 6d 6d 65 6e 74 20 6c 69 |rsion_comment li|
|00000020| 6d 69 74 20 31                                  |mit 1           |
+--------+-------------------------------------------------+----------------+
Exception in thread "ShardingSphere-Command-0" java.lang.NoSuchMethodError: org.apache.shardingsphere.db.protocol.mysql.packet.command.MySQLCommandPacketFactory.newInstance(Lorg/apache/shardingsphere/db/protocol/mysql/packet/command/MySQLCommandPacketType;Lorg/apache/shardingsphere/db/protocol/mysql/payload/MySQLPacketPayload;)Lorg/apache/shardingsphere/db/protocol/mysql/packet/command/MySQLCommandPacket;
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandPacket(MySQLCommandExecuteEngine.java:55)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandPacket(MySQLCommandExecuteEngine.java:46)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:96)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
02:05:42.054 [main-SendThread(192.168.243.34:12181)] DEBUG org.apache.zookeeper.ClientCnxn - Got ping response for session id: 0x104e9235c6801e4 after 1ms.
02:0
``` 
additional docker files 
``` text
ext-lib
  bcpkix-jdk15on-1.60.jar
  bcprov-jdk15on-1.60.jar
  bd-shardingsphere-custom-encrypt-algo-5.0.0.jar
  hutool-core-5.7.16.jar
  hutool-crypto-5.7.16.jar
  mysql-connector-java-8.0.26.jar


lib
  accessors-smart-1.2.jar
  aggdesigner-algorithm-6.0.jar
  animal-sniffer-annotations-1.18.jar
  antlr4-runtime-4.9.2.jar
  apiguardian-api-1.1.0.jar
  asm-5.0.4.jar
  atomikos-util-5.0.8.jar
  audience-annotations-0.5.0.jar
  avatica-core-1.18.0.jar
  avatica-metrics-1.18.0.jar
  calcite-core-1.27.0.jar
  calcite-linq4j-1.27.0.jar
  checker-qual-2.11.1.jar
  commons-codec-1.10.jar
  commons-collections4-4.2.jar
  commons-compiler-3.0.11.jar
  commons-exec-1.3.jar
  commons-io-2.8.0.jar
  commons-lang-2.6.jar
  commons-lang3-3.4.jar
  commons-logging-1.1.3.jar
  curator-client-5.1.0.jar
  curator-framework-5.1.0.jar
  curator-recipes-5.1.0.jar
  elasticjob-api-3.0.1.jar
  elasticjob-dataflow-executor-3.0.1.jar
  elasticjob-error-handler-general-3.0.1.jar
  elasticjob-error-handler-spi-3.0.1.jar
  elasticjob-executor-kernel-3.0.1.jar
  elasticjob-http-executor-3.0.1.jar
  elasticjob-infra-common-3.0.1.jar
  elasticjob-lite-core-3.0.1.jar
  elasticjob-lite-lifecycle-3.0.1.jar
  elasticjob-registry-center-3.0.1.jar
  elasticjob-script-executor-3.0.1.jar
  elasticjob-simple-executor-3.0.1.jar
  elasticjob-tracing-api-3.0.1.jar
  elasticjob-tracing-rdb-3.0.1.jar
  error_prone_annotations-2.3.4.jar
  esri-geometry-api-2.2.0.jar
  failsafe-2.3.3.jar
  failureaccess-1.0.1.jar
  groovy-2.4.19-indy.jar
  grpc-api-1.27.1.jar
  grpc-context-1.27.1.jar
  grpc-core-1.27.1.jar
  grpc-grpclb-1.27.1.jar
  grpc-netty-1.27.1.jar
  grpc-protobuf-1.27.1.jar
  grpc-protobuf-lite-1.27.1.jar
  grpc-stub-1.27.1.jar
  gson-2.8.6.jar
  guava-29.0-jre.jar
  HikariCP-3.4.2.jar
  httpclient-4.5.9.jar
  httpcore-4.4.11.jar
  jackson-annotations-2.10.0.jar
  jackson-core-2.10.0.jar
  jackson-databind-2.10.0.jar
  jackson-dataformat-yaml-2.10.0.jar
  janino-3.0.11.jar
  jcl-over-slf4j-1.7.7.jar
  jetcd-common-0.5.0.jar
  jetcd-core-0.5.0.jar
  jetcd-resolver-0.5.0.jar
  json-path-2.4.0.jar
  json-smart-2.3.jar
  jsr305-3.0.2.jar
  jta-1.1.jar
  listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
  log4j-1.2.17.jar
  logback-classic-1.2.0.jar
  logback-core-1.2.0.jar
  mchange-commons-java-0.2.15.jar
  memory-0.9.0.jar
  netty-buffer-4.1.69.Final.jar
  netty-codec-4.1.69.Final.jar
  netty-codec-http-4.1.69.Final.jar
  netty-codec-http2-4.1.69.Final.jar
  netty-codec-socks-4.1.69.Final.jar
  netty-common-4.1.69.Final.jar
  netty-handler-4.1.69.Final.jar
  netty-handler-proxy-4.1.69.Final.jar
  netty-resolver-4.1.69.Final.jar
  netty-transport-4.1.69.Final.jar
  netty-transport-native-epoll-4.1.69.Final-linux-aarch_64.jar
  netty-transport-native-epoll-4.1.69.Final-linux-x86_64.jar
  netty-transport-native-epoll-4.1.69.Final.jar
  netty-transport-native-unix-common-4.1.69.Final.jar
  perfmark-api-0.19.0.jar
  postgresql-42.2.5.jar
  proto-google-common-protos-1.17.0.jar
  protobuf-java-3.11.0.jar
  protobuf-java-util-3.11.0.jar
  quartz-2.3.2.jar
  shardingsphere-authority-api-5.0.1-SNAPSHOT.jar
  shardingsphere-authority-core-5.0.1-SNAPSHOT.jar
  shardingsphere-cluster-mode-core-5.0.1-SNAPSHOT.jar
  shardingsphere-cluster-mode-repository-api-5.0.1-SNAPSHOT.jar
  shardingsphere-cluster-mode-repository-etcd-5.0.1-SNAPSHOT.jar
  shardingsphere-cluster-mode-repository-zookeeper-curator-5.0.1-SNAPSHOT.jar
  shardingsphere-db-discovery-api-5.0.1-SNAPSHOT.jar
  shardingsphere-db-discovery-core-5.0.1-SNAPSHOT.jar
  shardingsphere-db-discovery-distsql-handler-5.0.1-SNAPSHOT.jar
  shardingsphere-db-discovery-distsql-parser-5.0.1-SNAPSHOT.jar
  shardingsphere-db-discovery-distsql-statement-5.0.1-SNAPSHOT.jar
  shardingsphere-db-discovery-mgr-5.0.1-SNAPSHOT.jar
  shardingsphere-db-protocol-core-5.0.1-SNAPSHOT.jar
  shardingsphere-db-protocol-mysql-5.0.1-SNAPSHOT.jar
  shardingsphere-db-protocol-opengauss-5.0.1-SNAPSHOT.jar
  shardingsphere-db-protocol-postgresql-5.0.1-SNAPSHOT.jar
  shardingsphere-distsql-parser-5.0.1-SNAPSHOT.jar
  shardingsphere-distsql-statement-5.0.1-SNAPSHOT.jar
  shardingsphere-encrypt-api-5.0.1-SNAPSHOT.jar
  shardingsphere-encrypt-core-5.0.1-SNAPSHOT.jar
  shardingsphere-encrypt-distsql-handler-5.0.1-SNAPSHOT.jar
  shardingsphere-encrypt-distsql-parser-5.0.1-SNAPSHOT.jar
  shardingsphere-encrypt-distsql-statement-5.0.1-SNAPSHOT.jar
  shardingsphere-infra-binder-5.0.1-SNAPSHOT.jar
  shardingsphere-infra-common-5.0.1-SNAPSHOT.jar
  shardingsphere-infra-context-5.0.1-SNAPSHOT.jar
  shardingsphere-infra-datetime-spi-5.0.1-SNAPSHOT.jar
  shardingsphere-infra-executor-5.0.1-SNAPSHOT.jar
  shardingsphere-infra-federation-optimizer-5.0.1-SNAPSHOT.jar
  shardingsphere-infra-merge-5.0.1-SNAPSHOT.jar
  shardingsphere-infra-parser-5.0.1-SNAPSHOT.jar
  shardingsphere-infra-rewrite-5.0.1-SNAPSHOT.jar
  shardingsphere-infra-route-5.0.1-SNAPSHOT.jar
  shardingsphere-jdbc-core-5.0.1-SNAPSHOT.jar
  shardingsphere-memory-mode-core-5.0.1-SNAPSHOT.jar
  shardingsphere-mode-core-5.0.1-SNAPSHOT.jar
  shardingsphere-parser-api-5.0.1-SNAPSHOT.jar
  shardingsphere-parser-core-5.0.1-SNAPSHOT.jar
  shardingsphere-proxy-backend-5.0.1-SNAPSHOT.jar
  shardingsphere-proxy-bootstrap-5.0.1-SNAPSHOT.jar
  shardingsphere-proxy-frontend-core-5.0.1-SNAPSHOT.jar
  shardingsphere-proxy-frontend-mysql-5.0.1-SNAPSHOT.jar
  shardingsphere-proxy-frontend-opengauss-5.0.1-SNAPSHOT.jar
  shardingsphere-proxy-frontend-postgresql-5.0.1-SNAPSHOT.jar
  shardingsphere-proxy-frontend-spi-5.0.1-SNAPSHOT.jar
  shardingsphere-readwrite-splitting-api-5.0.1-SNAPSHOT.jar
  shardingsphere-readwrite-splitting-core-5.0.1-SNAPSHOT.jar
  shardingsphere-readwrite-splitting-distsql-handler-5.0.1-SNAPSHOT.jar
  shardingsphere-readwrite-splitting-distsql-parser-5.0.1-SNAPSHOT.jar
  shardingsphere-readwrite-splitting-distsql-statement-5.0.1-SNAPSHOT.jar
  shardingsphere-scaling-core-5.0.1-SNAPSHOT.jar
  shardingsphere-scaling-distsql-handler-5.0.1-SNAPSHOT.jar
  shardingsphere-scaling-distsql-parser-5.0.1-SNAPSHOT.jar
  shardingsphere-scaling-distsql-statement-5.0.1-SNAPSHOT.jar
  shardingsphere-scaling-mysql-5.0.1-SNAPSHOT.jar
  shardingsphere-scaling-opengauss-5.0.1-SNAPSHOT.jar
  shardingsphere-scaling-postgresql-5.0.1-SNAPSHOT.jar
  shardingsphere-shadow-api-5.0.1-SNAPSHOT.jar
  shardingsphere-shadow-core-5.0.1-SNAPSHOT.jar
  shardingsphere-shadow-distsql-handler-5.0.1-SNAPSHOT.jar
  shardingsphere-shadow-distsql-parser-5.0.1-SNAPSHOT.jar
  shardingsphere-shadow-distsql-statement-5.0.1-SNAPSHOT.jar
  shardingsphere-sharding-api-5.0.1-SNAPSHOT.jar
  shardingsphere-sharding-core-5.0.1-SNAPSHOT.jar
  shardingsphere-sharding-distsql-handler-5.0.1-SNAPSHOT.jar
  shardingsphere-sharding-distsql-parser-5.0.1-SNAPSHOT.jar
  shardingsphere-sharding-distsql-statement-5.0.1-SNAPSHOT.jar
  shardingsphere-single-table-api-5.0.1-SNAPSHOT.jar
  shardingsphere-single-table-core-5.0.1-SNAPSHOT.jar
  shardingsphere-spi-5.0.1-SNAPSHOT.jar
  shardingsphere-sql-parser-engine-5.0.1-SNAPSHOT.jar
  shardingsphere-sql-parser-mysql-5.0.1-SNAPSHOT.jar
  shardingsphere-sql-parser-opengauss-5.0.1-SNAPSHOT.jar
  shardingsphere-sql-parser-oracle-5.0.1-SNAPSHOT.jar
  shardingsphere-sql-parser-postgresql-5.0.1-SNAPSHOT.jar
  shardingsphere-sql-parser-spi-5.0.1-SNAPSHOT.jar
  shardingsphere-sql-parser-sql92-5.0.1-SNAPSHOT.jar
  shardingsphere-sql-parser-sqlserver-5.0.1-SNAPSHOT.jar
  shardingsphere-sql-parser-statement-5.0.1-SNAPSHOT.jar
  shardingsphere-standalone-mode-core-5.0.1-SNAPSHOT.jar
  shardingsphere-standalone-mode-repository-api-5.0.1-SNAPSHOT.jar
  shardingsphere-standalone-mode-repository-file-5.0.1-SNAPSHOT.jar
  shardingsphere-system-datetime-5.0.1-SNAPSHOT.jar
  shardingsphere-transaction-api-5.0.1-SNAPSHOT.jar
  shardingsphere-transaction-core-5.0.1-SNAPSHOT.jar
  shardingsphere-transaction-xa-atomikos-5.0.1-SNAPSHOT.jar
  shardingsphere-transaction-xa-core-5.0.1-SNAPSHOT.jar
  shardingsphere-transaction-xa-spi-5.0.1-SNAPSHOT.jar
  sketches-core-0.9.0.jar
  slf4j-api-1.7.7.jar
  snakeyaml-1.16.jar
  transactions-5.0.8.jar
  transactions-api-5.0.8.jar
  transactions-jdbc-5.0.8.jar
  transactions-jta-5.0.8.jar
  uzaygezen-core-0.2.jar
  zookeeper-3.6.0.jar
  zookeeper-jute-3.6.0.jar
```

**Comment by strongduanmu** [comment]
> thinks，i check it on local env，success ! but had a new issue now

@userkdg Welcome to submit a new issue to report this issue.

**Comment by userkdg** [comment]
> @userkdg This is the result of my test, and no exception was found.
> 
> ```
> [INFO ] 2021-12-07 09:17:23.323 [Connection-1-ThreadExecutor] ShardingSphere-SQL - Logic SQL: select count(0) as cnt from (select order_id from t_encrypt) as tmp
> [INFO ] 2021-12-07 09:17:23.324 [Connection-1-ThreadExecutor] ShardingSphere-SQL - SQLStatement: MySQLSelectStatement(limit=Optional.empty, lock=Optional.empty, window=Optional.empty)
> [INFO ] 2021-12-07 09:17:23.324 [Connection-1-ThreadExecutor] ShardingSphere-SQL - Actual SQL: ds_1 ::: select count(0) as cnt from (select order_cipher AS order_id from t_encrypt) as tmp
> ```

bad!! subquery table set alias , proxy rewrite sql error .  such as :

actual
``` sql
MySQL [ec_order_db]> preview select count(1) as cnt from (select a.address from ec_oms_order a) as tmp;
+------------------+-----------------------------------------------------------------------------------------------+
| data_source_name | sql                                                                                           |
+------------------+-----------------------------------------------------------------------------------------------+
| ec_order_ds      | select count(1) as cnt from (select a.a.address_cipher AS address from ec_oms_order a) as tmp |
+------------------+-----------------------------------------------------------------------------------------------+

```
Expected 

``` sql 
 select count(1) as cnt from (select a.address_cipher AS address from ec_oms_order a) as tmp
```

**Comment by strongduanmu** [comment]
> ```sql
> MySQL [ec_order_db]> preview select count(1) as cnt from (select a.address from ec_oms_order a) as tmp;
> ```

Hi @userkdg, thank you for your test, and can you report this bug on another issue?
