### ISSUE TITLE
Type cast exception occurred when executing single table query that contains unsigned bigint or datetime type

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#13948]
### Which version of ShardingSphere did you use?

5.0.0 version or master branch

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy.

Connecting to the proxy directly through cli will not cause an exception, but using java or go programs to connect to the proxy will cause an exception.

### Expected behavior

Execute single table query successfully.

### Actual behavior

```
Exception in thread "main" java.sql.SQLException: Unknown exception: [java.lang.Long cannot be cast to java.lang.Integer]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.nextRow(MysqlIO.java:1999)
	at com.mysql.jdbc.MysqlIO.readSingleRowSet(MysqlIO.java:3403)
	at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:471)
	at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:3115)
	at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:2344)
	at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1373)
	at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:788)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2011)
	at com.strongduanmu.proxy.ShardingProxyJdbcTest.testSelect(ShardingProxyJdbcTest.java:148)
	at com.strongduanmu.proxy.ShardingProxyJdbcTest.main(ShardingProxyJdbcTest.java:24)
```

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

Configure a sharding rule, and then execute the following statement to create a single table.

```sql
create table t_single(id int(11) unsigned, order_id bigint(20) unsigned);
insert into t_single(id, order_id) values(1, 1), (2, 2);

alter table add column create_time datetime(3);
update t_single set create_time = now();
```

**Comment by strongduanmu** [comment]
Fixed by #13982.
