### ISSUE TITLE
Exception in thread "main" org.apache.shardingsphere.elasticjob.reg.exception.RegException: org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout?

### ISSUE THREAD

**Issue by CrackerSuperior** [apache/shardingsphere#13976]
Version
  sharding-proxy-master

Config
``` yaml
schemaName: copier_db

dataSources:
  ds_0:
    url: jdbc:mysql://172.18.40.145:3306/copytest?serverTimezone=UTC&useSSL=false
    username: pcloud
    password: pcloud
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://172.18.40.96:3306/copytest?serverTimezone=UTC&useSSL=false
    username: pcloud
    password: pcloud
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_2:
    url: jdbc:mysql://172.18.40.97:3306/copytest?serverTimezone=UTC&useSSL=false
    username: pcloud
    password: pcloud
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !DB_DISCOVERY
  dataSources:
    pr_ds:
      dataSourceNames:
        - ds_0
        - ds_1
        - ds_2
      discoveryTypeName: mgr
  discoveryTypes:
    mgr:
      type: MGR
      props:
        groupName: ce9be252-2b71-11e6-b8f4-00212844f856
        zkServerLists: '172.18.40.145:2181'
        keepAliveCron: '0/5 * * * * ?'
```

Error
``` java

Exception in thread "main" org.apache.shardingsphere.elasticjob.reg.exception.RegException: org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.shardingsphere.elasticjob.reg.exception.RegExceptionHandler.handleException(RegExceptionHandler.java:48)
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.init(ZookeeperRegistryCenter.java:107)
	at org.apache.shardingsphere.dbdiscovery.mgr.MGRDatabaseDiscoveryType.startPeriodicalUpdate(MGRDatabaseDiscoveryType.java:272)
	at org.apache.shardingsphere.dbdiscovery.rule.DatabaseDiscoveryRule.startMonitor(DatabaseDiscoveryRule.java:121)
	at org.apache.shardingsphere.dbdiscovery.rule.DatabaseDiscoveryRule.<init>(DatabaseDiscoveryRule.java:78)
	at org.apache.shardingsphere.dbdiscovery.rule.DatabaseDiscoveryRule.<init>(DatabaseDiscoveryRule.java:66)
	at org.apache.shardingsphere.dbdiscovery.rule.builder.DatabaseDiscoveryRuleBuilder.build(DatabaseDiscoveryRuleBuilder.java:46)
	at org.apache.shardingsphere.dbdiscovery.rule.builder.DatabaseDiscoveryRuleBuilder.build(DatabaseDiscoveryRuleBuilder.java:36)
	at org.apache.shardingsphere.infra.rule.builder.schema.SchemaRulesBuilder.buildRules(SchemaRulesBuilder.java:85)
	at org.apache.shardingsphere.infra.rule.builder.schema.SchemaRulesBuilder.buildRules(SchemaRulesBuilder.java:70)
	at org.apache.shardingsphere.mode.manager.memory.MemoryContextManagerBuilder.build(MemoryContextManagerBuilder.java:53)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.initContext(BootstrapInitializer.java:79)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.init(BootstrapInitializer.java:70)
	at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:47)
Caused by: org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.init(ZookeeperRegistryCenter.java:102)
	... 12 more

```

**And My firewall is turned off.**

**Comment by zjcnb** [comment]
@CrackerSuperior Hi, Can you check your zookeeper? It 's work well ? By the way. use cluster mode if your use discovery ha.

**Comment by terrymanu** [comment]
Closed because of no response anymore.
