### ISSUE TITLE
sql parse exception

### ISSUE THREAD

**Issue by oulexue** [apache/shardingsphere#13977]
### Which version of ShardingSphere did you use?
5.0.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
jdbc

### Expected behavior
I execute an SQL that returns a null value，this exception has occurred

this is the sql:

SELECT
	sum( vs.debit_amount ) AS debitAmount,
	sum( lender_amount ) AS lenderAmount,
FROM
	tb_finance_voucher_subject vs
	LEFT JOIN tb_finance_voucher v ON vs.voucher_id = v.id
	LEFT JOIN tb_finance_account_title t ON vs.subject_id = t.id 
WHERE
	(
		v.STATUS = 0 
	OR v.STATUS = 2) 
	AND v.voucher_date < '2021-01-01'  
	AND t.account_title_code LIKE '101%' 
	AND v.sob_id = 1419547607742603265
	group by v.sob_id
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Caused by: org.apache.ibatis.executor.ExecutorException: Error preparing statement.  Cause: com.google.common.util.concurrent.UncheckedExecutionException: org.apache.shardingsphere.sql.parser.exception.SQLParsingException: You have an error in your SQL syntax
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:97)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:59)
	at sun.reflect.GeneratedMethodAccessor150.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor.intercept(PaginationInterceptor.java:205)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy462.prepare(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor150.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at io.renren.common.interceptor.DataFilterInterceptor.intercept(DataFilterInterceptor.java:68)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy462.prepare(Unknown Source)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.prepareStatement(MybatisSimpleExecutor.java:92)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doQuery(MybatisSimpleExecutor.java:66)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:136)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:76)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
	... 125 more

**Comment by tuichenchuxin** [comment]
@oulexue I saw your sql have an error `sum( lender_amount ) AS lenderAmount,`
`,`

**Comment by oulexue** [comment]
That's not the reason. I've changed it to 'vs.lender_amount'

**Comment by oulexue** [comment]
I have found the cause of the problem，The cause of the problem is that the SQL is written incorrectly
