### ISSUE TITLE
Add syntax for `SHOW SHARDING KEY GENERATORS`

### ISSUE THREAD

**Issue by lanchengx** [apache/shardingsphere#13998]
For details, please refer to https://github.com/apache/shardingsphere/issues/13994

The ANTLR definition syntax is as follows:

```sql
SHOW SHARDING KEY GENERATORS (FROM schemaName)?
```

Examples are as follows:

```sql
> SHOW SHARDING KEY GENERATORS;
+-------------------------+--------+-------------------+
| name                    | type   | props             |
+-------------------------+----------------------------+
| uuid_key_generator      | uuid   | "worker-id"=123   |
+-------------------------+--------+-------------------+
```

**Comment by CrackerSuperior** [comment]
If I want to develop this, is there a time limit?

**Comment by RaigorJiang** [comment]
Wecome @CrackerSuperior ,
This is not an urgent task, you can try to solve it for a few days, @lanchengx can also help you.

**Comment by CrackerSuperior** [comment]
> Wecome @CrackerSuperior , This is not an urgent task, you can try to solve it for a few days, @lanchengx can also help you.

nice,thanks

**Comment by CrackerSuperior** [comment]
![image](https://user-images.githubusercontent.com/45088781/145841709-068406fd-10ac-4622-b137-31f4a99ed80d.png)
![image](https://user-images.githubusercontent.com/45088781/145841720-2562cdd5-4644-40d9-94b7-7e98927b4f85.png)
Is this effect okay?

**Comment by RaigorJiang** [comment]
> Is this effect okay?

Yes, It looks very good!

**Comment by CrackerSuperior** [comment]
> > Is this effect okay?
> 
> Yes, It looks very good!

Okay, if there is free time after get off work tomorrow, I will finish the remaining unit tests and other parts

**Comment by CrackerSuperior** [comment]
When I was doing the parsing test of the grammar definition, the following error occurred

``` java

java.lang.ExceptionInInitializerError
	at org.apache.shardingsphere.test.sql.parser.parameterized.DistSQLParserParameterizedTest.<clinit>(DistSQLParserParameterizedTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.runners.Parameterized.allParameters(Parameterized.java:280)
	at org.junit.runners.Parameterized.<init>(Parameterized.java:248)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:50)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.IllegalStateException: Find duplicated Case ID: parse-sql
	at com.google.common.base.Preconditions.checkState(Preconditions.java:589)
	at org.apache.shardingsphere.test.sql.parser.parameterized.jaxb.distsql.loader.DistSQLCasesLoader.buildCaseMap(DistSQLCasesLoader.java:48)
	at org.apache.shardingsphere.test.sql.parser.parameterized.loader.CasesLoader.loadFromTargetDirectory(CasesLoader.java:65)
	at org.apache.shardingsphere.test.sql.parser.parameterized.loader.CasesLoader.load(CasesLoader.java:51)
	at org.apache.shardingsphere.test.sql.parser.parameterized.loader.CasesLoader.<init>(CasesLoader.java:45)
	at org.apache.shardingsphere.test.sql.parser.parameterized.jaxb.distsql.loader.DistSQLCasesLoader.<init>(DistSQLCasesLoader.java:41)
	at org.apache.shardingsphere.test.sql.parser.parameterized.jaxb.CasesRegistry.<init>(CasesRegistry.java:41)
	at org.apache.shardingsphere.test.sql.parser.parameterized.jaxb.CasesRegistry.<clinit>(CasesRegistry.java:29)
	... 26 more

```

**Comment by lanchengx** [comment]
![image](https://user-images.githubusercontent.com/52209337/146109310-a034a3e4-67a6-4e89-8aeb-8128298969d3.png)

could you determine if there is any duplication in your project?

**Comment by CrackerSuperior** [comment]
> ![image](https://user-images.githubusercontent.com/52209337/146109310-a034a3e4-67a6-4e89-8aeb-8128298969d3.png)
> 
> could you determine if there is any duplication in your project?

![image](https://user-images.githubusercontent.com/45088781/146109857-8af45035-7bc0-417e-8b98-8b5e7f6c181f.png)
It is like this.

**Comment by CrackerSuperior** [comment]
![image](https://user-images.githubusercontent.com/45088781/146110706-eb89cac6-82db-4d17-99fe-d4f12f85b8b4.png)
![image](https://user-images.githubusercontent.com/45088781/146110708-18a7341c-fa59-464d-97bb-3ea6ddabd34b.png)
![image](https://user-images.githubusercontent.com/45088781/146110711-0c3558be-fb4c-4d93-abb2-45358be87fe7.png)
is this normal? Why are there two the same? @lanchengx

**Comment by lanchengx** [comment]
- `parse.xml` was removed in the submission of `e7a4d7c718436bf87ca8830a7772af0f3fe7f821`, your project may not be fully synchronized with the master,

- If there is no problem with the test, you can submit a PR

**Comment by CrackerSuperior** [comment]
> * `parse.xml` was removed in the submission of `e7a4d7c718436bf87ca8830a7772af0f3fe7f821`, your project may not be fully synchronized with the master,
> * If there is no problem with the test, you can submit a PR

I haven't done anything like this before, what should I do(submit a PR)?

**Comment by RaigorJiang** [comment]
This document may help:
https://shardingsphere.apache.org/community/cn/contribute/contributor/

**Comment by CrackerSuperior** [comment]
> This document may help: https://shardingsphere.apache.org/community/cn/contribute/contributor/

![image](https://user-images.githubusercontent.com/45088781/146298129-630b3341-9c71-4149-baca-eb4d38baea0f.png)
Is this right?

**Comment by RaigorJiang** [comment]
> Is this right?

Yes, it is right. 
@lanchengx, please help to review, thanks~
