### ISSUE TITLE
org.yaml.snakeyaml.error.YAMLException: Invalid tag: !SHARDING

### ISSUE THREAD

**Issue by wuguowei19880907** [apache/shardingsphere#14077]
SHARDING-SPHERE 5.0.0 & JAVA8

ERROR INFO:
```
Cannot create property=rules for JavaBean=org.apache.shardingsphere.infra.yaml.config.pojo.YamlRootConfiguration@484d78b
 in 'reader', line 1, column 1:
    dataSources:
    ^
Can't construct a java object for !SHARDING; exception=Invalid tag: !SHARDING
 in 'reader', line 13, column 3:
    - !SHARDING
      ^

 in 'reader', line 13, column 1:
    - !SHARDING
    ^

        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:312)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:345)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:444)
        at org.apache.shardingsphere.infra.yaml.engine.YamlEngine.unmarshal(YamlEngine.java:71)
        at org.apache.shardingsphere.driver.api.yaml.YamlShardingSphereDataSourceFactory.createDataSource(YamlShardingSphereDataSourceFactory.java:73)
        at org.apache.shardingsphere.benchmark.db.shardingjdbc.ShardingJDBCDataSourceFactory.newInstance(ShardingJDBCDataSourceFactory.java:49)
        at org.apache.shardingsphere.benchmark.jmeter.common.datapreparation.shardingsphere.sharding.JMeterShardingSphereCommonShardingInsert.<clinit>(JMeterShardingSphereCommonShardingInsert.java:24)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.jmeter.protocol.java.sampler.JavaSampler.createJavaClient(JavaSampler.java:222)
        at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:193)
        at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:630)
        at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558)
        at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489)
        at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256)
        at java.lang.Thread.run(Thread.java:748)
Caused by: Can't construct a java object for !SHARDING; exception=Invalid tag: !SHARDING
 in 'reader', line 13, column 3:
    - !SHARDING
      ^

        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:349)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequenceStep2(BaseConstructor.java:275)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequence(BaseConstructor.java:246)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructSequence.construct(Constructor.java:536)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:297)
        ... 22 more
Caused by: org.yaml.snakeyaml.error.YAMLException: Invalid tag: !SHARDING
        at org.yaml.snakeyaml.nodes.Tag.getClassName(Tag.java:112)
        at org.yaml.snakeyaml.constructor.Constructor.getClassForNode(Constructor.java:655)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.getConstructor(Constructor.java:335)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:345)
        ... 28 more

```

YAML：

```
dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 111111
    jdbcUrl: jdbc:mysql://localhost:3306/shardingsphere_benchmark?serverTimezone=UTC&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 1800000
    maximumPoolSize: 200
rules:
- !SHARDING
  tables:
    sbtest:
      actualDataNodes: ds_0.sbtest${0..1}
      databaseStrategy:
        standard:
          shardingColumn: id
          shardingAlgorithmName: database_inline
      tableStrategy:
        standard:
          shardingColumn: k
          shardingAlgorithmName: table_inline
      keyGenerateStrategy:
        column: id
        keyGeneratorName: increment

  shardingAlgorithms:
    database_inline:
      type: INLINE
      props:
        algorithm-expression: ds_0
    table_inline:
      type: INLINE
      props:
        algorithm-expression: sbtest${k % 2}
  keyGenerators:
    increment:
      type: SNOWFLAKE

props:
  max.connections.size.per.query: 10
  acceptor.size: 200  # The default value is available processors count * 2.
  executor.size: 200  # Infinite by default.
  query.with.cipher.column: true
  sql-show: true
  allow.range.query.with.inline.sharding: false
  check.table.metadata.enabled: false

```

**Comment by zjcnb** [comment]
@wuguowei19880907  Hi, i have two suggestions. one is check your yaml body format, other one is mvn clean install agagin.

**Comment by wuguowei19880907** [comment]
> @wuguowei19880907 Hi, i have two suggestions. one is check your yaml body format, other one is mvn clean install aga

This is my yaml file,please help me to check it.
[YAML.zip](https://github.com/apache/shardingsphere/files/7710158/YAML.zip)

I've tested that execute `mvn clean package`,but it gave me the error again

**Comment by zjcnb** [comment]
> > @wuguowei19880907 Hi, i have two suggestions. one is check your yaml body format, other one is mvn clean install aga
> 
> This is my yaml file,please help me to check it. [YAML.zip](https://github.com/apache/shardingsphere/files/7710158/YAML.zip)
> 
> I've tested that execute `mvn clean package`,but it gave me the error again

Let 's me check it.

**Comment by zjcnb** [comment]
[config-sharding.yaml.zip](https://github.com/apache/shardingsphere/files/7712050/config-sharding.yaml.zip)

Maybe, you can use it replace your configuration.

**Comment by wuguowei19880907** [comment]
> [config-sharding.yaml.zip](https://github.com/apache/shardingsphere/files/7712050/config-sharding.yaml.zip)
> 
> Maybe, you can use it replace your configuration.

I test like this,but get error:
```

Cannot create property=rules for JavaBean=org.apache.shardingsphere.infra.yaml.config.pojo.YamlRootConfiguration@63949798
 in 'reader', line 1, column 1:
    schemaName: sharding_db
    ^
Can't construct a java object for !SHARDING; exception=Invalid tag: !SHARDING
 in 'reader', line 16, column 3:
    - !SHARDING
      ^

 in 'reader', line 16, column 1:
    - !SHARDING
    ^

        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:312)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:345)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:444)
        at org.apache.shardingsphere.infra.yaml.engine.YamlEngine.unmarshal(YamlEngine.java:71)
        at org.apache.shardingsphere.driver.api.yaml.YamlShardingSphereDataSourceFactory.createDataSource(YamlShardingSphereDataSourceFactory.java:73)
        at org.apache.shardingsphere.benchmark.db.shardingjdbc.ShardingJDBCDataSourceFactory.newInstance(ShardingJDBCDataSourceFactory.java:49)
        at org.apache.shardingsphere.benchmark.jmeter.common.datapreparation.shardingsphere.sharding.JMeterShardingSphereCommonShardingInsert.<clinit>(JMeterShardingSphereCommonShardingInsert.java:24)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.jmeter.protocol.java.sampler.JavaSampler.createJavaClient(JavaSampler.java:222)
        at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:193)
        at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:630)
        at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558)
        at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489)
        at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256)
        at java.lang.Thread.run(Thread.java:748)
Caused by: Can't construct a java object for !SHARDING; exception=Invalid tag: !SHARDING
 in 'reader', line 16, column 3:
    - !SHARDING
      ^

        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:349)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequenceStep2(BaseConstructor.java:275)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequence(BaseConstructor.java:246)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructSequence.construct(Constructor.java:536)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:297)
        ... 22 more
Caused by: org.yaml.snakeyaml.error.YAMLException: Invalid tag: !SHARDING
        at org.yaml.snakeyaml.nodes.Tag.getClassName(Tag.java:112)
        at org.yaml.snakeyaml.constructor.Constructor.getClassForNode(Constructor.java:655)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.getConstructor(Constructor.java:335)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:345)
        ... 28 more

```

The configuration like this:
```

schemaName: sharding_db

dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !SHARDING
  tables:
    sbtest:
      actualDataNodes: ds_0.sbtest${0..1}
      databaseStrategy:
        standard:
          shardingColumn: id
          shardingAlgorithmName: database_inline
      tableStrategy:
        standard:
          shardingColumn: k
          shardingAlgorithmName: table_inline
      keyGenerateStrategy:
        column: id
        keyGeneratorName: increment

  shardingAlgorithms:
    database_inline:
      type: INLINE
      props:
        algorithm-expression: ds_0
    table_inline:
      type: INLINE
      props:
        algorithm-expression: sbtest${order_id % 2}

  keyGenerators:
    increment:
      type: SNOWFLAKE

```

**Comment by RaigorJiang** [comment]
I suggest trying to run the example project on your machine to determine whether the dependent environment is normal.
https://github.com/apache/shardingsphere/tree/master/examples

**Comment by AlanFiasco** [comment]
There are symbols like backspace characters in the YAML file. It is recommended that you can pull the code again or copy a new file to make changes.

**Comment by xsong123** [comment]
now all examples are INLINE, how to set complex algorithm?

  shardingAlgorithms:
    database_inline:
      type: INLINE
      props:
        algorithm-expression: ds_0
    table_inline:
      type: INLINE
      props:
        algorithm-expression: sbtest${order_id % 2}

**Comment by RaigorJiang** [comment]
@xsong123  
Please refer to: 
https://github.com/apache/shardingsphere/blob/master/shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/resources/yaml/sharding-rule.yaml

**Comment by terrymanu** [comment]
I just close this issue because no response for long time.

**Comment by xiaozhenzz** [comment]
我遇到了和你一样的问题，但是目前似乎没有答案

**Comment by AlchemyHouse** [comment]
hi terry

The yaml file format is ! Each character has meaning, so when using "!" Input is required in the form

have a good day

**Comment by Like-whale** [comment]
我最近也遇见了同样的问题，我使用snakeyaml去解析，报同样的错误。请问你后变解决这个问题了吗？

**Comment by wuguowei19880907** [comment]
> 我最近也遇见了同样的问题，我使用snakeyaml去解析，报同样的错误。请问你后变解决这个问题了吗？

没有，后来我就不做sharding了，做别的去了

**Comment by wonderfulxin** [comment]
Maybe you change the version to 5.3.0 , you can solve this
<dependency>
			<groupId>org.apache.shardingsphere</groupId>
			<artifactId>shardingsphere-jdbc-core</artifactId>
			<version>5.3.0</version>
		</dependency>

		<dependency>
			<groupId>org.yaml</groupId>
			<artifactId>snakeyaml</artifactId>
			<version>1.33</version>
		</dependency>
