### ISSUE TITLE
java.lang.ClassCastException: java.sql.Time cannot be cast to java.sql.Timestamp

### ISSUE THREAD

**Issue by ryan-hao** [apache/shardingsphere#14125]
version
shardingsphere-jdbc-core-spring-boot-starter', version: '5.0.0

![image](https://user-images.githubusercontent.com/50565298/146398507-3fd5919d-4a84-4b5a-8cc8-3cf306847bb8.png)
![image](https://user-images.githubusercontent.com/50565298/146398818-21f0b6c2-dbbf-4faf-9d11-f215e8a27d17.png)

java.lang.ClassCastException: java.sql.Time cannot be cast to java.sql.Timestamp
	at org.apache.shardingsphere.driver.jdbc.core.resultset.ResultSetUtil.convertLocalTimeValue(ResultSetUtil.java:139) ~[shardingsphere-jdbc-core-5.0.0.jar:5.0.0]
	at org.apache.shardingsphere.driver.jdbc.core.resultset.ResultSetUtil.convertValue(ResultSetUtil.java:65) ~[shardingsphere-jdbc-core-5.0.0.jar:5.0.0]
	at org.apache.shardingsphere.driver.jdbc.core.resultset.ShardingSphereResultSet.getObject(ShardingSphereResultSet.java:371) ~[shardingsphere-jdbc-core-5.0.0.jar:5.0.0]
	at org.springframework.jdbc.support.JdbcUtils.getResultSetValue(JdbcUtils.java:229) ~[spring-jdbc-5.3.12.jar:5.3.12]
	at org.springframework.jdbc.core.BeanPropertyRowMapper.getColumnValue(BeanPropertyRowMapper.java:401) ~[spring-jdbc-5.3.12.jar:5.3.12]
	at org.springframework.jdbc.core.BeanPropertyRowMapper.mapRow(BeanPropertyRowMapper.java:312) ~[spring-jdbc-5.3.12.jar:5.3.12]
	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:94) ~[spring-jdbc-5.3.12.jar:5.3.12]
	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:61) ~[spring-jdbc-5.3.12.jar:5.3.12]
	at org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:453) ~[spring-jdbc-5.3.12.jar:5.3.12]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:381) ~[spring-jdbc-5.3.12.jar:5.3.12]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:465) ~[spring-jdbc-5.3.12.jar:5.3.12]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:475) ~[spring-jdbc-5.3.12.jar:5.3.12]

**Comment by strongduanmu** [comment]
Hi @ryan-hao, thank you for your feedback, can you provide the step to reproduce this exception?

**Comment by ryan-hao** [comment]
> Hi @ryan-hao, thank you for your feedback, can you provide the step to reproduce this exception?

database: mysql
CREATE TABLE `ind_test_1` (
  `id` bigint(20) NOT NULL,
  `info_date` date DEFAULT NULL,
  `info_time` time DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ind_test_2` (
  `id` bigint(20) NOT NULL,
  `info_date` date DEFAULT NULL,
  `info_time` time DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

entity
@Data
public class TestDateTime {
   private Long id;

   private LocalDate infoDate;

   private LocalTime infoTime;
}

![image](https://user-images.githubusercontent.com/50565298/146475188-c7e5841e-3680-44c0-807e-5a7e9dbad50a.png)

    rules:
      sharding:
        tables:
          ind_test:
            actual-data-nodes: test-db.ind_test_$->{1..2}
            table-strategy:
              standard:
                sharding-column: id
                sharding-algorithm-name: ind-test-inline
            key-generate-strategy:
              column: id
              key-generator-name: snowflake
        sharding-algorithms:
          ind-test-inline:
            type: INLINE
            props:
              algorithm-expression: ind_test_$->{id % 2 + 1}
        key-generators:
          snowflake:
            type: SNOWFLAKE
            props:
              worker-id: 123

**Comment by linghengqian** [comment]
- @ryan-hao I can't test this Error Log on my example. Please provide a git that includes this unit test.

**Comment by linghengqian** [comment]
- It is largely impossible to reproduce in the master branch unless you provide unit tests.
