### ISSUE TITLE
java.util.UnknownFormatConversionException: Conversion = ' '

### ISSUE THREAD

**Issue by oneslideicywater** [apache/shardingsphere#14127]
## running sharding-proxy using docker-compose

```yaml
version: '3.9'
services:
  sphere: 
    image: apache/shardingsphere-proxy:5.0.0
    ports:
      - 13308:3308
    environment:
      - PORT=3308
    volumes:
      - "/root/sharding-proxy/conf:/opt/shardingsphere-proxy/conf" 
    deploy:
      # 副本
      replicas: 1

```

## config-sharding.yaml

```yaml
schemaName: sharding_db

dataSources:
  ds_0:
    url: jdbc:postgresql://192.168.10.54:5432/postgres
    username: postgres
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:postgresql://192.168.10.54:5433/postgres
    username: postgres
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_2:
    url: jdbc:postgresql://192.168.10.54:5434/postgres
    username: postgres
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_3:
    url: jdbc:postgresql://192.168.10.54:5435/postgres
    username: postgres
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !SHARDING
  tables:
    t_person:
      actualDataNodes: ds_${0..3}.t_person_${0..7}
      tableStrategy:
        standard:
          shardingColumn: city
          shardingAlgorithmName: model_inline
      databaseStrategy:
        standard:
          shardingColumn: person_id
          shardingAlgorithmName: model_db_inline

  bindingTables:
    - t_person
  defaultDatabaseStrategy:
    standard:
      shardingColumn: user_id
      shardingAlgorithmName: database_inline
  defaultTableStrategy:
    none:

  shardingAlgorithms:
    database_inline:
      type: INLINE
      props:
        algorithm-expression: ds_${user_id % 2}
    model_db_inline:
      type: INLINE
      props:
        algorithm-expression: ds_${person_id % 4}
    model_inline:
      type: INLINE
      props:
        algorithm-expression: t_person_{city % 8}

```

## create table and insert 

```bash

root@8d725c240571:/# psql -U postgres -h 192.168.10.54 -p 13308 -d sharding_db
Password for user postgres: 
psql (10.16 (Debian 10.16-1.pgdg90+1))
Type "help" for help.

sharding_db=> create table t_person( person_id int primary key, city int not null);
CREATE TABLE
sharding_db=> insert into t_person(1,2);
ERROR:  You have an error in your SQL syntax
sharding_db=> insert into t_person values(1,2);
ERROR:  Conversion = ' '

```
## sharding-proxy logs

version: 5.0.0

```bash
[ERROR] 2021-12-13 07:59:02.268 [Connection-4-ThreadExecutor] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
java.util.UnknownFormatConversionException: Conversion = ' '
	at java.util.Formatter.checkText(Formatter.java:2579)
	at java.util.Formatter.parse(Formatter.java:2565)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at org.apache.shardingsphere.infra.exception.ShardingSphereException.<init>(ShardingSphereException.java:34)
	at org.apache.shardingsphere.sharding.route.strategy.type.standard.StandardShardingStrategy.doSharding(StandardShardingStrategy.java:72)
	at org.apache.shardingsphere.sharding.route.strategy.type.standard.StandardShardingStrategy.doSharding(StandardShardingStrategy.java:57)
	at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.routeTables(ShardingStandardRoutingEngine.java:218)
	at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.route0(ShardingStandardRoutingEngine.java:198)
	at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.routeByShardingConditionsWithCondition(ShardingStandardRoutingEngine.java:118)
	at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.routeByShardingConditions(ShardingStandardRoutingEngine.java:111)
	at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.getDataNodes(ShardingStandardRoutingEngine.java:88)
	at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.route(ShardingStandardRoutingEngine.java:70)
	at org.apache.shardingsphere.sharding.route.engine.ShardingSQLRouter.createRouteContext(ShardingSQLRouter.java:56)
	at org.apache.shardingsphere.sharding.route.engine.ShardingSQLRouter.createRouteContext(ShardingSQLRouter.java:44)
	at org.apache.shardingsphere.infra.route.engine.impl.PartialSQLRouteExecutor.route(PartialSQLRouteExecutor.java:62)
	at org.apache.shardingsphere.infra.route.engine.SQLRouteEngine.route(SQLRouteEngine.java:53)
	at org.apache.shardingsphere.infra.context.kernel.KernelProcessor.route(KernelProcessor.java:54)
	at org.apache.shardingsphere.infra.context.kernel.KernelProcessor.generateExecutionContext(KernelProcessor.java:46)
	at org.apache.shardingsphere.proxy.backend.communication.DatabaseCommunicationEngine.execute(DatabaseCommunicationEngine.java:121)
	at org.apache.shardingsphere.proxy.backend.text.data.impl.SchemaAssignedDatabaseBackendHandler.execute(SchemaAssignedDatabaseBackendHandler.java:55)
	at org.apache.shardingsphere.proxy.frontend.postgresql.command.query.text.PostgreSQLComQueryExecutor.execute(PostgreSQLComQueryExecutor.java:71)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:99)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by oneslideicywater** [comment]
```yaml
    model_inline:
      type: INLINE
      props:
        algorithm-expression: t_person_{city % 8}  #  should be  t_person_${city % 8} 
```

but the error is quite misleading
