### ISSUE TITLE
Aggregations such as max, sum, count got NullPointerException using 5.0.0

### ISSUE THREAD

**Issue by sid-ihycq** [apache/shardingsphere#14194]
## Bug Report

I build my project just follow the case in official doc and found both of those sql below will got NullPointerException
```
select max(id) from t_order
select count(1) frrm t_order
```

Exception in thread "main" java.lang.NullPointerException
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.getValueCaseSensitiveFromTables(GroupByMemoryMergedResult.java:134)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.getValueCaseSensitive(GroupByMemoryMergedResult.java:124)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.init(GroupByMemoryMergedResult.java:73)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.init(GroupByMemoryMergedResult.java:53)
	at org.apache.shardingsphere.infra.merge.result.impl.memory.MemoryMergedResult.<init>(MemoryMergedResult.java:51)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.<init>(GroupByMemoryMergedResult.java:56)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.getGroupByMergedResult(ShardingDQLResultMerger.java:108)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.build(ShardingDQLResultMerger.java:78)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.merge(ShardingDQLResultMerger.java:63)
	at org.apache.shardingsphere.infra.merge.MergeEngine.executeMerge(MergeEngine.java:90)
	at org.apache.shardingsphere.infra.merge.MergeEngine.merge(MergeEngine.java:80)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.mergeQuery(ShardingSpherePreparedStatement.java:393)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.executeQuery(ShardingSpherePreparedStatement.java:182)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2322)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2075)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2037)
	at org.hibernate.loader.Loader.doQuery(Loader.java:956)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:357)
	at org.hibernate.loader.Loader.doList(Loader.java:2868)
	at org.hibernate.loader.Loader.doList(Loader.java:2850)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2682)
	at org.hibernate.loader.Loader.list(Loader.java:2677)
	at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:338)
	at org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java:2181)
	at org.hibernate.internal.AbstractSharedSessionContract.list(AbstractSharedSessionContract.java:1204)
	at org.hibernate.query.internal.NativeQueryImpl.doList(NativeQueryImpl.java:177)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1617)
	at org.hibernate.query.internal.AbstractProducedQuery.uniqueResult(AbstractProducedQuery.java:1659)

### Which version of ShardingSphere did you use?
hibernate-core: 5.6.3.Final
shardingsphere-jdbc-core: 5.0.0

use in springboot with jpa go the same exception:
spring-boot-starter-parent: 2.5.6
shardingsphere-jdbc-core-spring-boot-starter: 5.0.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Example codes for reproduce this issue (such as a github link).
just call JpaRepository.count().

**Comment by strongduanmu** [comment]
Hi @sid-ihycq, can you try the master branch? I think this bug has been fixed.

**Comment by sid-ihycq** [comment]
@strongduanmu Yes, I think it's becauseof my inline expression is like  test${0..1}.OrderItem_${0..1} , change to test${0..1}.order_item_${0..1} using java api it seems be resloved.

**Comment by strongduanmu** [comment]
> 

@sid-ihycq The actual table name must be consistent with the database.

**Comment by strongduanmu** [comment]
@sid-ihycq Since this issue has been resolved, can we close this issue?

**Comment by sid-ihycq** [comment]
@strongduanmu yeah you can close it. but before, i‘d like to say, shouldn't the table name be consistent with my inline expression？hibernate auto create tables with it, but aggregations doesn't？

**Comment by strongduanmu** [comment]
> 
@sid-ihycq The actual table must be consistent with the database, because the metadata of ShardingSphere will be loaded according to the actual table. Inconsistent case may result in the metadata not being loaded.
