### ISSUE TITLE
org.apache.shardingsphere.sql.parser.exception.SQLParsingException: You have an error in your SQL syntax

### ISSUE THREAD

**Issue by zgq7** [apache/shardingsphere#14224]
my project dependency version：
- springboot 2.1.7
- shardingsphere-jdbc-core-spring-boot-starter 5.0.0
- mybatis-plus 3.2.0
-  mysql 5.1.27
- mysql-connector 8.0.17

***
i customed xml sql like :
```xml
    <select id="getTableNames" resultType="java.lang.String">
        SHOW TABLES LIKE #{likeStr}
    </select>
```
it‘s worked like : 
```sql
SHOW TABLES LIKE 't_order_%' ;
```
when i haven't add sharding-jdbc in my project it worked normally。

but it occured error when I use it after i add sharding-jdbc in my project :

```text
Caused by: org.apache.shardingsphere.sql.parser.exception.SQLParsingException: You have an error in your SQL syntax
	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.twoPhaseParse(SQLParserExecutor.java:68)
	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.parse(SQLParserExecutor.java:49)
	at org.apache.shardingsphere.sql.parser.api.SQLParserEngine.parse(SQLParserEngine.java:51)
	at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserExecutor.parse(SQLStatementParserExecutor.java:47)
	at org.apache.shardingsphere.infra.parser.cache.SQLStatementCacheLoader.load(SQLStatementCacheLoader.java:40)
	at org.apache.shardingsphere.infra.parser.cache.SQLStatementCacheLoader.load(SQLStatementCacheLoader.java:29)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 89 more
```

you can reproduce this case like this :
```java
    @Test
    public void build() {
        SQLParserExecutor sqlParserExecutor = new SQLParserExecutor("MySQL", false);
        try {
            sqlParserExecutor.parse("show tables like ? ");
            log.info("sharding jdbc sql 编译成功");
        } catch (Exception e) {
            log.error("sharding jdbc sql 编译报错：", e);
        }
    }
```
it will occured a error 

```text
16:05:17.004 [main] ERROR - sharding jdbc sql 编译报错：
org.apache.shardingsphere.sql.parser.exception.SQLParsingException: You have an error in your SQL syntax
	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.twoPhaseParse(SQLParserExecutor.java:68)
	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.parse(SQLParserExecutor.java:49)
```

how to avoid this :
```java
    @Test
    public void build() {
        SQLParserExecutor sqlParserExecutor = new SQLParserExecutor("MySQL", false);
        try {
            sqlParserExecutor.parse("show tables like 'table_name' ");
            log.info("sharding jdbc sql 编译成功");
        } catch (Exception e) {
            log.error("sharding jdbc sql 编译报错：", e);
        }
    }
```

so my mybatis xml code changed like this 👍 
 ```xml
    <select id="getTableNames" resultType="java.lang.String">
        SHOW TABLES LIKE ${likeStr}
    </select>
```
so that the prama value will be like "'t_xxx'" 。

***
my expected 

- [ ] ：when sharding-jdbc parse the sql which is 'show tables' can use # rather than $ in mybatis xml 。

thanks !  :bug::bug::bug::bug::bug::bug:

@terrymanu

**Comment by strongduanmu** [comment]
@zgq7 Thank you for your feedback, we will investigate this issue.

**Comment by tuichenchuxin** [comment]
@zgq7 I have tried this sql 
`show tables like ?`
In original JDBC. It can't be supported in mysql, So I think we should not support this.

**Comment by zgq7** [comment]
maybe you didn't understood my means，'show tables like ? ' is not the original jdbc sql，it is compiled by mybatis,
then parse the sql by sharding-jdbc SQLParseEngine。
I think you shoud run my junit test and reply me in github，becuase now there more problems in my project afted added sharding-jdbc。

thanks!










At 2021-12-23 10:45:11, "tuichenchuxin" ***@***.***> wrote:

@zgq7 I have tried this sql
show tables like ?
In original JDBC. It can't be supported in mysql, So I think we should not support this.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tuichenchuxin** [comment]
@zgq7 I found before reply is a mistake, So I delete it. :)
Original JDBC can support this sql `show tables like ? `. But not by prepareStatement. 
I'll figure out how to support this sql in ShardingSphere.

**Comment by zgq7** [comment]
@tuichenchuxin 

```java
    @Test
    public void build5() {
        SQLParserExecutor sqlParserExecutor = new SQLParserExecutor("MySQL", false);
        try {
            sqlParserExecutor.parse("select a.rank from table_name a");
            log.info("sharding jdbc sql 编译成功");
        } catch (Exception e) {
            log.error("sharding jdbc sql 编译报错：", e);
        }
    }
```
it alse occure a error，because there has a column which name is rank ...

```text
11:38:44.972 [main] ERROR - sharding jdbc sql 编译报错：
org.apache.shardingsphere.sql.parser.exception.SQLParsingException: You have an error in your SQL syntax
	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.twoPhaseParse(SQLParserExecutor.java:68)
	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.parse(SQLParserExecutor.java:49)
```

if the column name is ranke，the case will pass 。:bug::bug::bug:

maybe these are still many sql parse problems in my project ，do you have good advice for me ?

**Comment by tuichenchuxin** [comment]
@zgq7 
Rank is not supported in mysql 8.0 but can be supported in mysql 5.7.
this is related to #13759
I think we should avoid using this keywork as a column name.
And I'll support rank in shardingsphere later.

**Comment by zgq7** [comment]
@tuichenchuxin 
OK，I knew , thakn you for your reply 👍

**Comment by liujia13142324** [comment]
mark

**Comment by terrymanu** [comment]
The version is out of service, please try new version
