### ISSUE TITLE
xa recover got exception when encrypt rule configured

### ISSUE THREAD

**Issue by roodkcab** [apache/shardingsphere#14262]
### Which version of ShardingSphere did you use?
master branch

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
proxy

### Expected behavior
`xa recover` should work when used with encrypt

### Actual behavior
exception occured
```
[ERROR] 2021-12-23 15:50:37.736 [Connection-3-ThreadExecutor] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
java.lang.ClassCastException: org.apache.shardingsphere.encrypt.rule.EncryptRule cannot be cast to org.apache.shardingsphere.infra.merge.engine.decorator.impl.TransparentRule
	at org.apache.shardingsphere.infra.merge.engine.decorator.impl.TransparentResultDecorator.decorate(TransparentResultDecorator.java:29)
	at org.apache.shardingsphere.infra.merge.MergeEngine.decorate(MergeEngine.java:114)
	at org.apache.shardingsphere.infra.merge.MergeEngine.merge(MergeEngine.java:81)
	at org.apache.shardingsphere.proxy.backend.communication.DatabaseCommunicationEngine.mergeQuery(DatabaseCommunicationEngine.java:241)
	at org.apache.shardingsphere.proxy.backend.communication.DatabaseCommunicationEngine.processExecuteQuery(DatabaseCommunicationEngine.java:208)
	at org.apache.shardingsphere.proxy.backend.communication.DatabaseCommunicationEngine.execute(DatabaseCommunicationEngine.java:164)
	at org.apache.shardingsphere.proxy.backend.text.data.impl.SchemaAssignedDatabaseBackendHandler.execute(SchemaAssignedDatabaseBackendHandler.java:56)
	at org.apache.shardingsphere.proxy.backend.text.transaction.TransactionXAHandler.execute(TransactionXAHandler.java:82)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:62)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:96)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:69)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748
```

**Comment by roodkcab** [comment]
```
    public ResultDecorator newInstance(final DatabaseType databaseType, final ShardingSphereSchema schema,
                                       final EncryptRule encryptRule, final ConfigurationProperties props, final SQLStatementContext sqlStatementContext) {
        if (sqlStatementContext instanceof SelectStatementContext) {
            EncryptAlgorithmMetaData metaData = new EncryptAlgorithmMetaData(schema, encryptRule, (SelectStatementContext) sqlStatementContext);
            return new EncryptDQLResultDecorator(metaData);
        } 
        if (sqlStatementContext.getSqlStatement() instanceof DALStatement) {
            return new EncryptDALResultDecorator();
        }
        return new TransparentResultDecorator();
    }
```
`EncryptResultDecoratorEngine` returns a `TransparentResultDecorator` which in turn receive a `EncryptRule` instead of `TransparentRule` in decorate method

**Comment by jingshanglu** [comment]
@roodkcab Maybe we should add a condition branch for `XA recover`.

**Comment by roodkcab** [comment]
> @roodkcab Maybe we should add a condition branch for `XA recover`.

how about let TransparentResultDecorator accept all `ShardingRule` ?

**Comment by jingshanglu** [comment]
> > @roodkcab Maybe we should add a condition branch for `XA recover`.
> 
> how about let TransparentResultDecorator accept all `ShardingRule` ?

@roodkcab Maybe  it's better to just add one `decorate` func in `TransparentResultDecorator` for `EncryptRule `.

**Comment by roodkcab** [comment]
> > > @roodkcab Maybe we should add a condition branch for `XA recover`.
> > 
> > 
> > how about let TransparentResultDecorator accept all `ShardingRule` ?
> 
> @roodkcab Maybe it's better to just add one `decorate` func in `TransparentResultDecorator` for `EncryptRule `.

ok, What about other rules? Shall we add a special exception for `TransparentResultDecorator`, for currently exception is threw by java itself, the callstack is difficult to debug.

**Comment by jingshanglu** [comment]
@roodkcab Hey, i've checked it, maybe we can use `EncryptDQLResultDecorator`, what do you think?

**Comment by terrymanu** [comment]
This issue is opened for long time any no feedback, I just close it.
