### ISSUE TITLE
If multiple logical tables map to one actual table, aggregations such as max, sum, count will get NullPointerException using shardingsphere-jdbc 5.0.0

### ISSUE THREAD

**Issue by NOLouser** [apache/shardingsphere#14273]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
org.apache.shardingsphere:shardingsphere-jdbc-core:5.0.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
the sql:
```

SELECT COUNT(1) FROM dep_task_info_hint

```

the java code:
```

try (HintManager hintManager = HintManager.getInstance()) {
    hintManager.addTableShardingValue("dep_task_info_hint", "202111");
    hintManager.addTableShardingValue("dep_task_info_hint", "202112");
    List<Map<String, Object>> queryForList = jdbcTemplate.queryForList("SELECT COUNT(1) FROM dep_task_info_hint");
    LOGGER.info(GSON.toJson(queryForList));
}

```

the shardingsphere yaml:
```

rules:
  # 分片配置
  - !SHARDING
    tables:
      dep_task_info:
        actualDataNodes: ${SOURCE-KEY}.dep_task_info_$->{['2020','2021','2022']}$->{['01','02','03','04','05','06','07','08','09','10','11','12']}
        tableStrategy:
          standard:
            shardingColumn: id_
            shardingAlgorithmName: monthTableShardingAlgorithm
      dep_task_result:
        actualDataNodes: ${SOURCE-KEY}.dep_task_result_$->{['2020','2021','2022']}$->{['01','02','03','04','05','06','07','08','09','10','11','12']}
        tableStrategy:
          standard:
            shardingColumn: task_id_
            shardingAlgorithmName: monthTableShardingAlgorithm
      dep_task_info_hint:
        actualDataNodes: ${SOURCE-KEY}.dep_task_info_$->{['2020','2021','2022']}$->{['01','02','03','04','05','06','07','08','09','10','11','12']}
        tableStrategy:
          hint:
            shardingAlgorithmName: hintMonthTableShardingAlgorithm
      dep_task_result_hint:
        actualDataNodes: ${SOURCE-KEY}.dep_task_result_$->{['2020','2021','2022']}$->{['01','02','03','04','05','06','07','08','09','10','11','12']}
        tableStrategy:
          hint:
            shardingAlgorithmName: hintMonthTableShardingAlgorithm
    # 绑定规则列表
    bindingTables:
      - dep_task_info,dep_task_result
      - dep_task_info_hint,dep_task_result_hint
    # 分片算法配置
    shardingAlgorithms:
      monthTableShardingAlgorithm:
        type: CLASS_BASED_MONTH
        props: {}
      hintMonthTableShardingAlgorithm:
        type: CLASS_BASED_HINT
        props: {}

# 全局配置
props:
  # 输出路由日志
  sql-show: true
  # 检查元数据
  check-table-metadata-enabled: false
  # 一次查询请求在每个数据库实例中所能使用的最大连接数
  max-connections-size-per-query: 36

```

### Actual behavior
the log:
```

[INFO] 2021-12-23 19:56:25.570 ? org.springframework.boot.StartupInfoLogger:61 - [Test worker]Started DepTaskServiceForProductTest in 14.83 seconds (JVM running for 16.853)
[INFO] 2021-12-23 19:56:25.891 ? org.apache.shardingsphere.infra.executor.sql.log.SQLLogger:74 - [Test worker]Logic SQL: SELECT COUNT(1) FROM dep_task_info_hint
[INFO] 2021-12-23 19:56:25.891 ? org.apache.shardingsphere.infra.executor.sql.log.SQLLogger:74 - [Test worker]SQLStatement: MySQLSelectStatement(limit=Optional.empty, lock=Optional.empty, window=Optional.empty)
[INFO] 2021-12-23 19:56:25.891 ? org.apache.shardingsphere.infra.executor.sql.log.SQLLogger:74 - [Test worker]Actual SQL: localhost ::: SELECT COUNT(1) FROM dep_task_info_202111
[INFO] 2021-12-23 19:56:25.892 ? org.apache.shardingsphere.infra.executor.sql.log.SQLLogger:74 - [Test worker]Actual SQL: localhost ::: SELECT COUNT(1) FROM dep_task_info_202112

java.lang.NullPointerException
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.getValueCaseSensitiveFromTables(GroupByMemoryMergedResult.java:134)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.getValueCaseSensitive(GroupByMemoryMergedResult.java:124)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.init(GroupByMemoryMergedResult.java:73)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.init(GroupByMemoryMergedResult.java:53)
	at org.apache.shardingsphere.infra.merge.result.impl.memory.MemoryMergedResult.<init>(MemoryMergedResult.java:51)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.<init>(GroupByMemoryMergedResult.java:56)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.getGroupByMergedResult(ShardingDQLResultMerger.java:108)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.build(ShardingDQLResultMerger.java:78)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.merge(ShardingDQLResultMerger.java:63)
	at org.apache.shardingsphere.infra.merge.MergeEngine.executeMerge(MergeEngine.java:90)
	at org.apache.shardingsphere.infra.merge.MergeEngine.merge(MergeEngine.java:80)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.mergeQuery(ShardingSphereStatement.java:435)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.executeQuery(ShardingSphereStatement.java:137)
	at org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:452)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:381)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:465)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:475)
	at org.springframework.jdbc.core.JdbcTemplate.queryForList(JdbcTemplate.java:525)
	at com.kungeek.dep.center.core.service.DepTaskServiceForProductTest.selectCount(DepTaskServiceForProductTest.java:226)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)

```

### Reason analyze (If you can)
1、It used the logical table to look up in the scheme;
2、Scheme includes only non-routing tables.
![image](https://user-images.githubusercontent.com/40658641/147239976-9e13ea2f-fc7b-485f-a50d-943ea8ad4f84.png)
![image](https://user-images.githubusercontent.com/40658641/147302808-2c907e0e-c32b-4cb7-902c-5ca21fa542f9.png)
![image](https://user-images.githubusercontent.com/40658641/147240136-73ae56c8-7a35-4c5d-b71f-fa4caae34b83.png)

### Example codes for reproduce this issue (such as a github link).
[shardingsphere5.0.0_demo](https://github.com/NOLouser/shardingsphere5.0.0_demo)

**Comment by strongduanmu** [comment]
@NOLouser Please first confirm whether all actual tables corresponding to the `dep_task_info_hint` table exist. ShardingSphere will randomly select an actual table to load when loading metadata and store it in the metadata corresponding to the logical table.

**Comment by NOLouser** [comment]
@strongduanmu 
Hi, this is [my github demo](https://github.com/NOLouser/shardingsphere5.0.0_demo).Please read README.md and do it.

**Comment by NOLouser** [comment]
@strongduanmu 
Hello, I have found the cause of the problem. The location of the problem is org.apache.shardingsphere.sharding.metadata.ShardingTableMetaDataBuilder#getTableMetaDataMap. If multiple logical tables map to one actual table, it will only contain one logical table.
![image](https://user-images.githubusercontent.com/40658641/147327494-92f50cd4-9725-49e2-a47d-13ad45eb389f.png)

**Comment by tuichenchuxin** [comment]
@NOLouser Yes, it will only load one table, because sharding tables are all same, so for tableMetaData, we only need one table.

**Comment by NOLouser** [comment]
@tuichenchuxin 
Hi, this is not the problem I want to point out. I want to say,  if multiple logical tables map to one actual table(like logicTable t_order, t_order_hint all map to one actualTable t_order_202112 ), it will only create one logicTable tableMetaData(the other logicTable tableMetaData will be lost), and it will cause problems when using the lost logicTable tableMetaData. Please take a look at [my excample demo](https://github.com/NOLouser/shardingsphere5.0.0_demo).

**Comment by tuichenchuxin** [comment]
@NOLouser Oh, I get the point. We didn't consider about two logic table route to one actual table. Why need this?

**Comment by NOLouser** [comment]
@tuichenchuxin 
Hi, because shardingSphere not support serveral sharding strategies for one logicTable, but we can use one sharding strategy for one logicTable, and that will need serveral logicTables map to one actualTable. Please look at [this official reply](https://github.com/apache/shardingsphere/issues/8820).

**Comment by tuichenchuxin** [comment]
@NOLouser Oh, I get it. I'll fix this issue later.

**Comment by NOLouser** [comment]
@tuichenchuxin 
Thanks a lot!

**Comment by tuichenchuxin** [comment]
@NOLouser By the way, are you willing to fix this problem?

**Comment by NOLouser** [comment]
@tuichenchuxin 
I'm sorry. I'm not very familiar with using github.

**Comment by NOLouser** [comment]
@tuichenchuxin 
There are several places where this method org.apache.shardingsphere.sharding.rule.ShardingRule#findLogicTableByActualTable is used. I'm not sure if all places are affected. Or I just need to fix load tableMetaData problem?
![image](https://user-images.githubusercontent.com/40658641/147354882-9f1d1dc1-17b2-4cc0-8b41-efa885055b20.png)

**Comment by tuichenchuxin** [comment]
@NOLouser You can focus on fixing the load bug, But if there is something affected, then you should fixed them too.
You can refer to [this guide](https://shardingsphere.apache.org/community/en/contribute/contributor/) to submit a pr

**Comment by NOLouser** [comment]
@tuichenchuxin For further communication, can you send the wechat id to my email——whpnolouser@gmail.com?

**Comment by ChinkenEight** [comment]
This problem hasn't been solved yet
