### ISSUE TITLE
Compiles have error messages.

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#14338]
```
Exception in thread "pool-1-thread-1" java.lang.NullPointerException
        at org.apache.shardingsphere.infra.config.datasource.pool.destroyer.impl.HikariDataSourcePoolDestroyer.lambda$destroy$0(HikariDataSourcePoolDestroyer.java:38)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by LeeGuoPing** [comment]
May I have a try

**Comment by strongduanmu** [comment]
> May I have a try

@LeeGuoPing Welcome.

**Comment by LeeGuoPing** [comment]
@zjcnb @strongduanmu dear brothers, please see `DataSourceConfigurationValidatorTest` 's method ` assertValidateSuccess`, finally  use HikariDataSource no argument constructor, so the pool is null . so `hikariDataSource.getHikariPoolMXBean()` is null in this test case.

![image](https://user-images.githubusercontent.com/35389145/147451111-6bf70b54-3d77-4855-af96-5046d454c68f.png)


![image](https://user-images.githubusercontent.com/35389145/147450550-4c533137-24ec-4a6e-bfb2-521112269ed5.png)

![image](https://user-images.githubusercontent.com/35389145/147450622-893b35cc-a9f5-444f-8968-f2ee2069c019.png)

![image](https://user-images.githubusercontent.com/35389145/147451191-55347824-f97b-40ed-903c-c3c73403534f.png)

**Comment by LeeGuoPing** [comment]
And because of the error print in another thread.  so, it doesn't matter main thread, the test case works fine even thouth it has error

![image](https://user-images.githubusercontent.com/35389145/147453988-4b06db1b-d252-4e3b-b2c0-1da4580e685e.png)
