### ISSUE TITLE
shardingsphere-proxy start fail

### ISSUE THREAD

**Issue by xcmonline** [apache/shardingsphere#14543]
Starting the ShardingSphere-Proxy ...
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/shardingsphere/mode/repository/cluster/ClusterPersistRepositoryConfiguration
        at org.apache.shardingsphere.mode.manager.cluster.yaml.ClusterPersistRepositoryConfigurationYamlSwapper.swapToObject(ClusterPersistRepositoryConfigurationYamlSwapper.java:41)
        at org.apache.shardingsphere.mode.manager.cluster.yaml.ClusterPersistRepositoryConfigurationYamlSwapper.swapToObject(ClusterPersistRepositoryConfigurationYamlSwapper.java:27)
        at org.apache.shardingsphere.infra.yaml.config.swapper.mode.PersistRepositoryConfigurationYamlSwapperEngine.swapToObject(PersistRepositoryConfigurationYamlSwapperEngine.java:57)
        at org.apache.shardingsphere.infra.yaml.config.swapper.mode.ModeConfigurationYamlSwapper.swapToObject(ModeConfigurationYamlSwapper.java:44)
        at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.init(BootstrapInitializer.java:67)
        at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:47)
Caused by: java.lang.ClassNotFoundException: org.apache.shardingsphere.mode.repository.cluster.ClusterPersistRepositoryConfiguration
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)

server.ymal
`
scaling:
  blockQueueSize: 10000
  workerThread: 40
  clusterAutoSwitchAlgorithm:
    type: IDLE
    props:
      incremental-task-idle-minute-threshold: 30
  dataConsistencyCheckAlgorithm:
    type: DEFAULT

mode:
  type: Cluster
  repository:
    type: ZooKeeper
    props:
      namespace: governance_ds
      server-lists: localhost:2181
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
  overwrite: true

rules:
  - !AUTHORITY
    users:
      - root@%:root
      - sharding@:sharding
    provider:
      type: ALL_PRIVILEGES_PERMITTED
  - !TRANSACTION
    defaultType: XA
    providerType: Atomikos

props:
  max-connections-size-per-query: 1
  kernel-executor-size: 16  
  proxy-frontend-flush-threshold: 128  
  proxy-opentracing-enabled: false
  proxy-hint-enabled: false
  sql-show: false
  check-table-metadata-enabled: false
  show-process-list-enabled: false
  proxy-backend-query-fetch-size: -1
  check-duplicate-table-enabled: false
  sql-comment-parse-enabled: false
  proxy-frontend-executor-size: 0 
  proxy-backend-executor-suitable: OLAP
  proxy-frontend-max-connections: 0 
  sql-federation-enabled: false
`

config-sharding.ymal
`
schemaName: sharding_db

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !SHARDING
  tables:
    obs_aws_data_min:
      actualDataNodes: ds_0.obs_aws_data_min_${0..1}
      tableStrategy:
        standard:
          shardingColumn: observ_time
          shardingAlgorithmName: sharding_by_time
      keyGenerateStrategy:
        column: id
        keyGeneratorName: snowflake
  defaultDatabaseStrategy:
    none:
  defaultTableStrategy:
    none:

  shardingAlgorithms:
    sharding_by_time:
      type: auto_interval
      props:
        datetime-lower: "2021-10-01 00:00:00"
        sharding-seconds: "86400"
        datetime-upper: "2021-11-05 00:00:00"

  keyGenerators:
    snowflake:
      type: SNOWFLAKE
      props:
        worker-id: 123
`

**Comment by zjcnb** [comment]
@xcmonline Hello, Can you tell me your ShardingSphere-Proxy version?

**Comment by xcmonline** [comment]
> @xcmonline你好，你能告诉我你的ShardingSphere-Proxy版本吗？

apache-shardingsphere-5.0.0-shardingsphere-proxy

**Comment by xcmonline** [comment]
only setting.
server.ymal
`mode:
  type: Cluster
  repository:
    type: Zookeeper
    props:
      namespace: qiyun_db1
      server-lists: localhost:2181
  overwrite: true
rules:
  - !AUTHORITY
    users:
      - root@%:123456
    provider:
      type: ALL_PRIVILEGES_PERMITTED
props:
  max-connections-size-per-query: 1
  kernel-executor-size: 16
  proxy-frontend-flush-threshold: 128
  proxy-opentracing-enabled: false
  proxy-hint-enabled: false
  sql-show: false
  check-table-metadata-enabled: false`

and 

config-sharding.yaml
`schemaName: testdb
dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&useSSL=false
    username: root
    password: xxxxxx
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
rules:
- !SHARDING
  tables:
    obs_aws_data_min:
      actualDataNodes: ds_0.obs_aws_data_min_${0..1}
      tableStrategy:
        standard:
          shardingColumn: observ_time
          shardingAlgorithmName: sharding_by_time
      keyGenerateStrategy:
        column: id
        keyGeneratorName: snowflake
  defaultDatabaseStrategy:
    none:
  defaultTableStrategy:
    none:
  shardingAlgorithms:
    sharding_by_time:
      type: auto_interval
      props:
        datetime-lower: "2020-10-01 00:00:00"
        sharding-seconds: "86400"
        datetime-upper: "2020-10-05 00:00:00"
  keyGenerators:
    snowflake:
      type: SNOWFLAKE
      props:
        worker-id: 123
`

**Comment by zjcnb** [comment]
@xcmonline Can you check your ${shardingsphere-proxy}/lib directory. Are `shardingsphere-cluster-mode-repository-zookeeper-curator.5.0.0.jar` in it?

**Comment by xcmonline** [comment]
> @xcmonline Can you check your ${shardingsphere-proxy}/lib directory. Are `shardingsphere-cluster-mode-repository-zookeeper-curator.5.0.0.jar` in it?

zookeeper-3.6.0.jar and zookeeper-jute-3.6.0.jar .
shardingsphere-cluster-mode-repository-zookeeper-curator.5.0.0.jar  not found, where can I download it.

**Comment by THMAIL** [comment]
> 

you can download it with https://mavenlibs.com/jar/file/org.apache.shardingsphere/shardingsphere-cluster-mode-repository-zookeeper-curator#all_versions, but I have tried it doesn't work at all  !!!!
