### ISSUE TITLE
ShardingSphereDatabaseMetaData.getPrimaryKeys might throw exception

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#14633]
### Which version of ShardingSphere did you use?
master branch

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
`ShardingSphereDatabaseMetaData.getPrimaryKeys` doesn't throw exception

### Actual behavior
Sometime it works, sometimes it throw exception.

In scaling data consistency check (primary key loader was replaced for now):
```
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'scaling_ds_11.t_order_0' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2449)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381)
	at com.mysql.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:3737)
	at com.mysql.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:3727)
	at com.mysql.jdbc.IterateBlock.doForAll(IterateBlock.java:50)
	at com.mysql.jdbc.DatabaseMetaData.getPrimaryKeys(DatabaseMetaData.java:3725)
	at com.zaxxer.hikari.pool.ProxyDatabaseMetaData.getPrimaryKeys(ProxyDatabaseMetaData.java:125)
	at com.zaxxer.hikari.pool.HikariProxyDatabaseMetaData.getPrimaryKeys(HikariProxyDatabaseMetaData.java)
	at org.apache.shardingsphere.driver.jdbc.core.datasource.metadata.ShardingSphereDatabaseMetaData.getPrimaryKeys(ShardingSphereDatabaseMetaData.java:147)
	at org.apache.shardingsphere.data.pipeline.core.metadata.loader.PipelineTableMetaDataLoader.loadPrimaryKeys(PipelineTableMetaDataLoader.java:79)
	at org.apache.shardingsphere.data.pipeline.core.metadata.loader.PipelineTableMetaDataLoader.loadTableMetadataMap(PipelineTableMetaDataLoader.java:59)
	at org.apache.shardingsphere.data.pipeline.core.metadata.loader.PipelineTableMetaDataLoader.<init>(PipelineTableMetaDataLoader.java:42)
	at org.apache.shardingsphere.data.pipeline.core.check.consistency.DataConsistencyCheckerImpl.getTableMetaDataLoader(DataConsistencyCheckerImpl.java:208)
	at org.apache.shardingsphere.data.pipeline.core.check.consistency.DataConsistencyCheckerImpl.checkRecordsContent(DataConsistencyCheckerImpl.java:149)
	... 12 common frames omitted
```

In test project, still 3 possibilities:
- No exception thrown
- MySQLSyntaxErrorException: Table 'scaling_ds_11.t_order_0' doesn't exist
- MySQLSyntaxErrorException: Table 'scaling_ds_12.t_order_0' doesn't exist

Exception stack trace example:
```
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'scaling_ds_11.t_order_0' doesn't exist

//...
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2439)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1365)
	at com.mysql.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:3738)
	at com.mysql.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:3728)
	at com.mysql.jdbc.IterateBlock.doForAll(IterateBlock.java:50)
	at com.mysql.jdbc.DatabaseMetaData.getPrimaryKeys(DatabaseMetaData.java:3726)
	at com.zaxxer.hikari.pool.ProxyDatabaseMetaData.getPrimaryKeys(ProxyDatabaseMetaData.java:159)
	at com.zaxxer.hikari.pool.HikariProxyDatabaseMetaData.getPrimaryKeys(HikariProxyDatabaseMetaData.java)
	at org.apache.shardingsphere.driver.jdbc.core.datasource.metadata.ShardingSphereDatabaseMetaData.getPrimaryKeys(ShardingSphereDatabaseMetaData.java:147)
	at test.shardingsphere.metadta.ShardingJdbcMetadataTest.loadPrimaryKeys(ShardingJdbcMetadataTest.java:44)
	at test.shardingsphere.metadta.ShardingJdbcMetadataTest.loadPrimaryKeys(ShardingJdbcMetadataTest.java:37)
//...
```

### Reason analyze (If you can)
In `ShardingSphereDatabaseMetaData.java`, code snippets:
```
    @Override
    public ResultSet getPrimaryKeys(final String catalog, final String schema, final String table) throws SQLException {
        return createDatabaseMetaDataResultSet(getDatabaseMetaData().getPrimaryKeys(getActualCatalog(catalog), getActualSchema(schema), getActualTable(catalog, table)));
    }
    
    private String getActualTable(final String catalog, final String table) {
        if (null == table) {
            return null;
        }
        return findDataNodeContainedRule().map(each -> findActualTable(each, catalog, table).orElse(table)).orElse(table);
    }
    
    private Optional<String> findActualTable(final DataNodeContainedRule dataNodeContainedRule, final String catalog, final String table) {
        return Strings.isNullOrEmpty(catalog) ? dataNodeContainedRule.findFirstActualTable(table) : dataNodeContainedRule.findActualTableByCatalog(catalog, table);  
    }
    
    private String getActualSchema(final String schema) {
        return null != schema && schema.contains(DefaultSchema.LOGIC_NAME) ? dataSourcesMetaData.getDataSourceMetaData(getDataSourceName()).getSchema() : schema;
    }
    
    private String getDataSourceName() {
        if (null == currentPhysicalDataSourceName) {
            currentPhysicalDataSourceName = connection.getConnectionManager().getRandomPhysicalDataSourceName();
        }
        return currentPhysicalDataSourceName;
    }
```

In `ShardingRule.java`, code snippets:
```
    @Override
    public Optional<String> findFirstActualTable(final String logicTable) {
        return findTableRule(logicTable).map(tableRule -> tableRule.getActualDataNodes().get(0).getTableName());
    }
```

Summary:
- `currentPhysicalDataSourceName` is fetched with random data source name. It might be `scaling_ds_10`, `scaling_ds_11`, or `scaling_ds_12` in this test case.
- `dataNodeContainedRule.findFirstActualTable` impl in `ShardingRule` will get first actual data node's table name. It's `t_order_0` every time in this test case.
- For `autoTables`, `t_order_0` doesn't exist in every physical data source.

Some screenshots on debugging:
1, `currentPhysicalDataSourceName`:
<img width="1077" alt="WX20220106-162129@2x" src="https://user-images.githubusercontent.com/42492540/148676716-73ca5b22-84a5-4311-bf84-e8f34d7975df.png">

2, `getActualTable`:
<img width="1416" alt="WX20220106-162324@2x" src="https://user-images.githubusercontent.com/42492540/148676758-d27f7da7-988b-413e-a704-750a7838df0c.png">

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
https://github.com/sandynz/shardingsphere-test/tree/master/metadata-test

### Example codes for reproduce this issue (such as a github link).
https://github.com/sandynz/shardingsphere-test/tree/master/metadata-test

**Comment by tuichenchuxin** [comment]
I want to investigate this issue.

**Comment by sandynz** [comment]
> After investigating it, I found it's hard to determinate which pyhsical connection should be used. So, can we use the the information in `TableMetaData`?

Hi @tuichenchuxin , I used `TableMetaDataLoader.load` before, there's other issue, e.g. #14415
