### ISSUE TITLE
rename table error

### ISSUE THREAD

**Issue by xsong123** [apache/shardingsphere#14667]
shardingsphere version 5.0.0

config as below：
rules:
  tables:
    basicinfo:
      actualDataNodes: ds_${0..0}.basicinfo_${0..15}
      ...

sql as below：
rename  table basicinfo to hisbasicinfo20210101;
ps: table[hisbasicinfo20210101] has no rule

error as below：
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Can not find visitor rule: `RenameTableContext`
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
	at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserEngine.parse(SQLStatementParserEngine.java:48)
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine.parse0(ShardingSphereSQLParserEngine.java:71)
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine.parse(ShardingSphereSQLParserEngine.java:60)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.<init>(ShardingSpherePreparedStatement.java:157)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.<init>(ShardingSpherePreparedStatement.java:128)
	at org.apache.shardingsphere.driver.jdbc.core.connection.ShardingSphereConnection.prepareStatement(ShardingSphereConnection.java:78)
	at org.seasar.extension.jdbc.util.ConnectionUtil.prepareStatement(ConnectionUtil.java:93)
	at org.seasar.extension.jdbc.manager.JdbcContextImpl.getPreparedStatement(JdbcContextImpl.java:130)

**Comment by CrackerSuperior** [comment]
Sorry, if I remember correctly, the rename statement is not supported for the time being

**Comment by strongduanmu** [comment]
As @CrackerSuperior said, the rename statement is not currently supported. Are you interested in this task? @xsong123 @CrackerSuperior  You are welcome to submit PRs to support the rename statement.

**Comment by strongduanmu** [comment]
By the way, you can try the `ALTER TABLE RENAME TO...` statement, which I remember is supported.

**Comment by totalo** [comment]
I will look into this, please assign me.

**Comment by strongduanmu** [comment]
> 

@totalo Welcome.
