### ISSUE TITLE
how to refreshMetaData

### ISSUE THREAD

**Issue by xsong123** [apache/shardingsphere#14732]
version:
shardingsphere5.0.0
mysql5.7

procedure:
two app link to the same db, one create table in the db, another query included the table from the db .

error:
java.lang.NullPointerException
at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.getOrderValuesCaseSensitiveFromTables(OrderByValue.java:74)
at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.getOrderValuesCaseSensitive(OrderByValue.java:64)
at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.(OrderByValue.java:58)
at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByStreamMergedResult.orderResultSetsToQueue(OrderByStreamMergedResult.java:56)
at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByStreamMergedResult.(OrderByStreamMergedResult.java:50)
at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByStreamMergedResult.(GroupByStreamMergedResult.java:52)
at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.getGroupByMergedResult(ShardingDQLResultMerger.java:108)
at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.build(ShardingDQLResultMerger.java:78)
at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.merge(ShardingDQLResultMerger.java:63)
at org.apache.shardingsphere.infra.merge.MergeEngine.executeMerge(MergeEngine.java:90)
at org.apache.shardingsphere.infra.merge.MergeEngine.merge(MergeEngine.java:80)
at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.mergeQuery(ShardingSpherePreparedStatement.java:393)
at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.executeQuery(ShardingSpherePreparedStatement.java:182)

**Comment by xsong123** [comment]
old issue #13853

**Comment by lanchengx** [comment]
For the refresh table metadata statement, please refer to [RAL]( https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/distsql/syntax/ral/#%E5%85%B6%E4%BB%96) , currently only Proxy supports using DistSQL.

**Comment by menghaoranss** [comment]
which mode did you use, `Cluster` or `Standalone`?

**Comment by xsong123** [comment]
> which mode did you use, `Cluster` or `Standalone`?

it's Cluster.
different apps access to the same db, when one app create a table ,another app cannot get the table's metadata.

**Comment by TeslaCN** [comment]
Please deploy ShardingSphere in cluster mode and execute DDL via ShardingSphere-Proxy. You may refer to
https://shardingsphere.apache.org/document/current/en/overview/#hybrid-architecture

Since this issue has been inactive for a while, I'm closing it. Please open a new issue if you have other problems.
