### ISSUE TITLE
shardingsphere-jdbc connect  oracle

### ISSUE THREAD

**Issue by cicscpmi** [apache/shardingsphere#14774]
## Bug Report
I use shardingsphere-jdbc to connect oracle,With ojdbc7.jar;
use YAML config like:
dataSources:
  unique_ds:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: oracle.jdbc.OracleDriver
    jdbcUrl: jdbc:oracle:thin:@127.0.0.1:1521/helowin
    username: test
    password: test

2022-01-14 17:15:28,479 --main-- [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Start completed. 
Exception in thread "main" java.lang.NullPointerException
	at org.apache.shardingsphere.sql.parser.oracle.visitor.statement.impl.OracleDDLStatementSQLVisitor.visitCreateDefinitionClause(OracleDDLStatementSQLVisitor.java:160)
	at org.apache.shardingsphere.sql.parser.oracle.visitor.statement.impl.OracleDDLStatementSQLVisitor.visitCreateDefinitionClause(OracleDDLStatementSQLVisitor.java:129)
	at org.apache.shardingsphere.sql.parser.autogen.OracleStatementParser$CreateDefinitionClauseContext.accept(OracleStatementParser.java:43497)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.apache.shardingsphere.sql.parser.oracle.visitor.statement.impl.OracleDDLStatementSQLVisitor.visitCreateTable(OracleDDLStatementSQLVisitor.java:142)
	at org.apache.shardingsphere.sql.parser.oracle.visitor.statement.impl.OracleDDLStatementSQLVisitor.visitCreateTable(OracleDDLStatementSQLVisitor.java:129)
	at org.apache.shardingsphere.sql.parser.autogen.OracleStatementParser$CreateTableContext.accept(OracleStatementParser.java:42782)
	at org.apache.shardingsphere.sql.parser.api.SQLVisitorEngine.visit(SQLVisitorEngine.java:53)
	at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserExecutor.parse(SQLStatementParserExecutor.java:48)
	at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserEngine.parse(SQLStatementParserEngine.java:47)
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine.parse0(ShardingSphereSQLParserEngine.java:70)
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine.parse(ShardingSphereSQLParserEngine.java:59)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.createLogicSQL(ShardingSphereStatement.java:406)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.executeUpdate(ShardingSphereStatement.java:202)
	at org.apache.shardingsphere.example.core.jdbc.repository.UserRepositoryImpl.createTableIfNotExists(UserRepositoryImpl.java:46)
	at org.apache.shardingsphere.example.core.jdbc.service.UserServiceImpl.initEnvironment(UserServiceImpl.java:38)
	at org.apache.shardingsphere.example.core.api.ExampleExecuteTemplate.run(ExampleExecuteTemplate.java:28)
	at org.apache.shardingsphere.example.encrypt.raw.jdbc.EncryptRawYamlConfigurationExample.main(EncryptRawYamlConfigurationExample.java:35)

**Comment by terrymanu** [comment]
I just set it as invalid because of no reason to close it
