### ISSUE TITLE
Maybe `ShardingSphere-JDBC` can filter some configuration when pull remote configuration.

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#15075]
### Which version of ShardingSphere did you use?

`master`

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

`ShardingSphere-JDBC` and `ShardingSphere-Proxy`

### Expected behavior

`ShardingSphere-Proxy` implement `custom encrypt algorithm` and start up success by `cluster mode`. 

`ShardingSphere-JDBC` use schemaName and  cluster mode configuration read Zookeeper configuration. Maybe it needn't  load `custom encrypt algorithm` type.

### Actual behavior

```
Caused by: org.apache.shardingsphere.spi.exception.ServiceProviderNotFoundException: No implementation class load from SPI `org.apache.shardingsphere.encrypt.spi.EncryptAlgorithm` with type `TTT`.
	at org.apache.shardingsphere.spi.typed.TypedSPIRegistry.getRegisteredService(TypedSPIRegistry.java:76) ~[shardingsphere-spi-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at org.apache.shardingsphere.infra.config.algorithm.ShardingSphereAlgorithmFactory.createAlgorithm(ShardingSphereAlgorithmFactory.java:41) ~[shardingsphere-infra-common-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at org.apache.shardingsphere.encrypt.rule.EncryptRule.lambda$new$0(EncryptRule.java:65) ~[shardingsphere-encrypt-core-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[na:1.8.0_211]
	at org.apache.shardingsphere.encrypt.rule.EncryptRule.<init>(EncryptRule.java:65) ~[shardingsphere-encrypt-core-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at org.apache.shardingsphere.encrypt.rule.builder.EncryptRuleBuilder.build(EncryptRuleBuilder.java:36) ~[shardingsphere-encrypt-core-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at org.apache.shardingsphere.encrypt.rule.builder.EncryptRuleBuilder.build(EncryptRuleBuilder.java:32) ~[shardingsphere-encrypt-core-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at org.apache.shardingsphere.infra.rule.builder.schema.SchemaRulesBuilder.buildRules(SchemaRulesBuilder.java:85) ~[shardingsphere-infra-common-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at org.apache.shardingsphere.infra.rule.builder.schema.SchemaRulesBuilder.buildRules(SchemaRulesBuilder.java:70) ~[shardingsphere-infra-common-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.beforeBuildContextManager(ClusterContextManagerBuilder.java:104) ~[shardingsphere-cluster-mode-core-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.build(ClusterContextManagerBuilder.java:84) ~[shardingsphere-cluster-mode-core-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.createContextManager(ShardingSphereDataSource.java:80) ~[shardingsphere-jdbc-core-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.<init>(ShardingSphereDataSource.java:57) ~[shardingsphere-jdbc-core-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactory.createDataSource(ShardingSphereDataSourceFactory.java:50) ~[shardingsphere-jdbc-core-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration.dataSource(ShardingSphereAutoConfiguration.java:107) ~[shardingsphere-jdbc-core-spring-boot-starter-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration$$EnhancerBySpringCGLIB$$b89895b8.CGLIB$dataSource$3(<generated>) ~[shardingsphere-jdbc-core-spring-boot-starter-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration$$EnhancerBySpringCGLIB$$b89895b8$$FastClassBySpringCGLIB$$16fef4ec.invoke(<generated>) ~[shardingsphere-jdbc-core-spring-boot-starter-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration$$EnhancerBySpringCGLIB$$b89895b8.dataSource(<generated>) ~[shardingsphere-jdbc-core-spring-boot-starter-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_211]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_211]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	... 20 common frames omitted
```

**Comment by terrymanu** [comment]
I just set it as `invalid` because of closed by author without any reason.
