### ISSUE TITLE
Cannot get result set with enum , shardingsphere and mybatis-plus conflict

### ISSUE THREAD

**Issue by dragonorant** [apache/shardingsphere#15083]
```xml
<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
    <version>5.0.0</version>
</dependency>

<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-boot-starter</artifactId>
    <version>3.5.0</version>
</dependency>
```

```yml
# mybaits-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-column-underline: true
      refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  type-enums-package: com.sanyicloud.**.enums

```

```java
@Data
class Device{
    @TableField(value = "device_type")
    private DeviceTypeEnum deviceType;
}

@Getter
@AllArgsConstructor
 enum DeviceTypeEnum implements IEnum<Short>{
    IOS((short) 1, "ios"),
    ANDROID((short) 2,"android"),
    OTHER((short) 3, "other"),;
    @EnumValue
    private final Short code;
    @JsonValue
    private final String desc;
    @Override
    public Short getValue() {
        return this.code;
    }
}
```
The above configuration can successfully insert data, but the data cannot be queried。

exception
```text
2022-01-26 14:08:52.064  INFO [account-service,,] 95936 --- [           main] ShardingSphere-SQL                       : Actual SQL: master ::: SELECT  id,account_id,device_num,device_type,create_time,update_time,promo_code  FROM sanyi_third_0

org.springframework.dao.InvalidDataAccessApiUsageException: Error attempting to get column 'device_type' from result set.  Cause: java.sql.SQLFeatureNotSupportedException: getObject with type
; getObject with type; nested exception is java.sql.SQLFeatureNotSupportedException: getObject with type

Caused by: java.sql.SQLFeatureNotSupportedException: getObject with type
	at org.apache.shardingsphere.driver.jdbc.core.resultset.ShardingSphereResultSet.getObject(ShardingSphereResultSet.java:373)
	at org.apache.shardingsphere.driver.jdbc.core.resultset.ShardingSphereResultSet.getObject(ShardingSphereResultSet.java:378)
	at com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler.getNullableResult(MybatisEnumTypeHandler.java:118)
	at com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler.getNullableResult(MybatisEnumTypeHandler.java:49)
```

Underlying code
```java
ShardingSphereResultSet.class

    @Override
    public <T> T getObject(final int columnIndex, final Class<T> type) throws SQLException {
// columnIndex == 4 type == Short.class
        if (LocalDateTime.class.equals(type) || LocalDate.class.equals(type) || LocalTime.class.equals(type)) {
            return (T) ResultSetUtil.convertValue(mergeResultSet.getValue(columnIndex, Timestamp.class), type);
        }
        throw new SQLFeatureNotSupportedException("getObject with type");
    }
```
code
```java
@Test
public void test(){
    List<Device> list = thirdService.list();
}

```

How can I continue to use enumeration class object parameters

**Comment by RaigorJiang** [comment]
Hi @dragonorant , I have used enums in my project and no similar problem has occurred. Can you provide a demo (on GitHub) to reproduce the issue?

**Comment by dragonorant** [comment]
> 嗨@dragonorant，我在我的项目中使用了枚举，没有发生类似的问题。您能否提供一个演示（在 GitHub 上）来重现该问题？

hi @RaigorJiang 
Here is my project address 
```url
https://github.com/dragonorant/demo
```
Here are the test cases
```text
sanyi-account/account-service/src/test/java/com/sanyicloud/MainTest.java/test()
```

**Comment by RaigorJiang** [comment]
> Here are the test cases
> 
> ```
> sanyi-account/account-service/src/test/java/com/sanyicloud/MainTest.java/test()
> ```

@dragonorant OK, I'll check it later.

**Comment by dragonorant** [comment]
@RaigorJiang  感谢

**Comment by RaigorJiang** [comment]
@dragonorant 
Hello, since your project depends on nacos, but you did not provide the configuration in nacos, I cannot run the demo directly.
However, according to your entity structure, I used MyBatis-Plus combined with ShardingSphere to verify and found the problem.
The `SQLFeatureNotSupportedException` is caused by the operation of MybatisEnumTypeHandler when querying the ResultSet, which can be considered a bug and I will try to fix it.

**Comment by RaigorJiang** [comment]
Hi @dragonorant,
the issue has been fixed in master, you can build and try again.

**Comment by dragonorant** [comment]
OK, thanks
