### ISSUE TITLE
to consider the sqlType of value parameter when setting the value to the corresponding placeholder in a executing SQL

### ISSUE THREAD

**Issue by dissdic** [apache/shardingsphere#15134]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
yes
### Describe the feature you would like.
in the case of not knowning the specific type of the field to be used in where condition in a SQL,I can only invoke the setValue method of the PreparedStatement instance.but things don't work like I expected.in the underlying code,shardingsphere don't process the type conversion.

**Comment by dissdic** [comment]
I'm currently working on this issue,and the deadline would be before noon next day.

**Comment by TeslaCN** [comment]
Hi @dissdic 
Could you provide more informations and show us how to reproduce your problem? I can hardly understand your problem from your brief descriptions.

**Comment by dissdic** [comment]
I'm sorry ,it's my fault,I mean when I use spring-boot-starter-jdbc for interaction with Database.unlike other frameworks like mybatis, we may obtain Connection instance and PreparedStatement instance manually and use them to execute SQL directly.In shardingsphere,the implementation of&nbsp; PreparedStatement interface that we usually use is ShardingspherePreparedStatement which is also a subclass of AbstractPreparedStatementAdapter,as we get a SQL and there are some condition placeholder or value placeholder in the form of '?',so we need set specific value to the corresponding placeholder,in a case of that we're not sure of the database types of some fields we tend to set values in a SQL due to they were generated automatically,then we can only use the method setObject(..) to do so which is implemented in the abstract class AbstractPreparedStatementAdapter,now the problem is the implementation seems to not consider the sql type argument despite in the method `void setObject(int parameterType,Object x,int targetSqlType)` we've actually presented while invocation,and just set the Object value we present without any type conversion,and that cause error from underlying jdbc code.


this's basically the main problem i met while using shardingsphere currently,do you think it should be a problem or not? and I've fix it on local,can I commit a PR?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/shardingsphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月10日(星期四) 下午2:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/shardingsphere] to consider the sqlType of value parameter when setting the value to the corresponding placeholder in a executing SQL (Issue #15134)





 
Hi @dissdic
 Could you provide more informations and show us how to reproduce your problem? I can hardly understand your problem from your brief descriptions.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TeslaCN** [comment]
Hi @dissdic 
Could you provide more details about your issue? 
Database like PostgreSQL will handle the type conversion on server side, which means user can provide string as value no matter what the column's type is. And the JDBC Driver may handle the type conversion stuff implicitly.

**Comment by dissdic** [comment]
sorry,I've worked on other things recently,so i don't have the stacktrace info right now,i will reply you with it later.basicly the problem i encounter is just like what you said.In my case,the automatic type conversion didn't work,cause when using shardingsphere in my project,the implementation of PreparedStatement was switched from PgPreparedStatement to ShardingSpherePreparedStatement,and the&nbsp; PgPreparedStatement seems do all the type conversion if you see the source code while the ShardingSpherePreparedStatement don't
I'm not sure if the JDBC driver or the PgSql server would do the type conversion like you said,I'll give you the stacktrace i got.
&nbsp;


1814788049
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月17日(星期二) 中午11:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/shardingsphere] to consider the sqlType of value parameter when setting the value to the corresponding placeholder in a executing SQL (Issue #15134)





 
Hi @dissdic
 Could you provide more details about your issue?
 Database like PostgreSQL will handle the type conversion on server side, which means user can provide string as value no matter what the column's type is. And the JDBC Driver may handle the type conversion stuff implicitly.

**Comment by TeslaCN** [comment]
Hi @dissdic 
Any update here?

**Comment by terrymanu** [comment]
@dissdic Hi, can you reformat your content? It is difficult to read.

**Comment by dissdic** [comment]
for some reason,the format in the view got messed up.
**here is the stacktrace info I got :**
```
Caused by: org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [SELECT kkk.id as id,kkk.name as name,kkk.domain_name as domain_name,kkk."version" as "version",kkk.insert_user as insert_user,kkk.insert_date as insert_date,kkk.update_user as update_user,kkk.update_date as update_date FROM wms_kkk as kkk  WHERE kkk.id = ? ]; nested exception is org.postgresql.util.PSQLException: 错误: 操作符不存在: bigint = character varying
  建议：没有匹配指定名称和参数类型的操作符. 您也许需要增加明确的类型转换.
  位置：256
at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:101)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
at logwire.web.service.query.sql.jdbc.JdbcTemplateUtil.translateException(JdbcTemplateUtil.java:79)
at logwire.web.service.query.sql.jdbc.JdbcTemplateUtil.execute(JdbcTemplateUtil.java:61)
at logwire.web.service.query.sql.DynamicSqlSelect.doSelect(DynamicSqlSelect.java:733)
at logwire.web.service.query.sql.DynamicSqlSelect.doSelect(DynamicSqlSelect.java:660)
at logwire.web.service.query.sql.DynamicSqlSelect.forIterator(DynamicSqlSelect.java:443)
at logwire.web.service.query.sql.DynamicSqlSelect.getSingleRow(DynamicSqlSelect.java:601)
... 54 common frames omitted
Caused by: org.postgresql.util.PSQLException: 错误: 操作符不存在: bigint = character varying
  建议：没有匹配指定名称和参数类型的操作符. 您也许需要增加明确的类型转换.
  位置：256
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2468)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2211)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:309)
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
at org.apache.shardingsphere.driver.executor.callback.impl.PreparedStatementExecuteQueryCallback.executeQuery(PreparedStatementExecuteQueryCallback.java:40)
at org.apache.shardingsphere.driver.executor.callback.ExecuteQueryCallback.executeSQL(ExecuteQueryCallback.java:44)
at org.apache.shardingsphere.driver.executor.callback.ExecuteQueryCallback.executeSQL(ExecuteQueryCallback.java:36)
at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutorCallback.execute(JDBCExecutorCallback.java:85)
at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutorCallback.execute(JDBCExecutorCallback.java:64)
at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.syncExecute(ExecutorEngine.java:101)
at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.serialExecute(ExecutorEngine.java:87)
at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.execute(ExecutorEngine.java:81)
at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutor.execute(JDBCExecutor.java:65)
at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutor.execute(JDBCExecutor.java:49)
at org.apache.shardingsphere.driver.executor.DriverJDBCExecutor.executeQuery(DriverJDBCExecutor.java:73)
at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.executeQuery0(ShardingSpherePreparedStatement.java:212)
at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.executeQuery(ShardingSpherePreparedStatement.java:181)
at logwire.web.service.query.sql.DynamicSqlSelect.lambda$doSelect$15(DynamicSqlSelect.java:725)
at logwire.web.service.query.sql.jdbc.JdbcTemplateUtil.execute(JdbcTemplateUtil.java:46)
... 58 common frames omitted
```
for setting values in to a SQL,we used the setValues(PreparedStatement ps) in PreparedStatementSetter,as you can see in the image below:

![image](https://user-images.githubusercontent.com/42462093/180973912-d5499409-7b79-4f4b-bf7b-de03a172d483.png)

**and the implementation of this abstract method is like this:**

![image](https://user-images.githubusercontent.com/42462093/180974190-c99be6e7-adcb-437b-8a2a-1a7510abf34a.png)

**and the code of the another setValue method present in the sceenshot is:**

![image](https://user-images.githubusercontent.com/42462093/180974462-cc75b4ae-7a6f-4793-84c6-ab3fca459c5f.png)

![image](https://user-images.githubusercontent.com/42462093/180974646-df6c54e8-7239-4039-ad65-55f6bd166629.png)

the core code is:
> field.setValueIgnoreCheck(ps, index + 1, values.get(i), this.dialect);

which present as:

![image](https://user-images.githubusercontent.com/42462093/180974877-d9b7a838-86b2-4ce9-8c81-07c835d097fa.png)

the code of the method setValueInPreparedStatement shown in the sceenshot is:

![image](https://user-images.githubusercontent.com/42462093/180975084-fd53ffc3-83e5-42be-8996-389537f8de00.png)

despite these execution processes,I got the explicit detail info of this method while debugging:

![image](https://user-images.githubusercontent.com/42462093/180975265-cbd0295b-6c36-4d9d-95f0-b7cc5717a7d1.png)

this shows that eventually the setValue of ShardingSpherePreparedStatement was invoked.and I got the Exception written in the beginning.

**Comment by terrymanu** [comment]
`shardingsphere-jdbc-core-spring-boot-starter` is deprecated and removed in 5.3.0, please try new version and use ShardingSphere Driver.
