### ISSUE TITLE
Integrate test for jdbc:shadow -> h2 test cases cannot run.

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#15371]
Integrate test for jdbc:shadow -> h2 test cases cannot run.
The `init.sql` file is missing, but MySQL and PostgreSQL is ok.

Please finish the `init.sql` of h2. 

Please run all test cases in `shardingsphere-integration-test-suite` module to reproduce the issue.

Just update `engine-env.properties` to below before you run test cases:

```
# EMBEDDED, DOCKER, NATIVE
it.env.type=EMBEDDED

it.adapters=jdbc

#it.scenarios=db,tbl,dbtbl_with_readwrite_splitting,readwrite_splitting,encrypt,dbtbl_with_readwrite_splitting_and_encrypt,sharding_governance,shadow
it.scenarios=shadow

#it.databases=H2,MySQL,PostgreSQL
it.databases=H2

it.run.additional.cases=false
```

Error message are:

```log
java.lang.AssertionError: File `env/shadow/init-sql/h2/init.sql` must exist.

	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.apache.shardingsphere.test.integration.env.EnvironmentPath.getFile(EnvironmentPath.java:130)
	at org.apache.shardingsphere.test.integration.env.EnvironmentPath.getInitSQLFile(EnvironmentPath.java:75)
	at org.apache.shardingsphere.test.integration.framework.container.atomic.storage.impl.H2Container.execute(H2Container.java:48)
	at org.apache.shardingsphere.test.integration.framework.container.atomic.ShardingSphereContainer.start(ShardingSphereContainer.java:65)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.apache.shardingsphere.test.integration.framework.container.atomic.ShardingSphereContainers.start(ShardingSphereContainers.java:72)
	at org.apache.shardingsphere.test.integration.framework.container.compose.ComposedContainerManager.lambda$before$0(ComposedContainerManager.java:67)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
	at org.apache.shardingsphere.test.integration.framework.container.compose.ComposedContainerManager.before(ComposedContainerManager.java:67)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

**Comment by LeeGuoPing** [comment]
May I have a try

**Comment by totalo** [comment]
> May I have a try

Welcome

**Comment by LeeGuoPing** [comment]
@terrymanu I found that There are `h2 `and `mysql `in yaml under h2 folder, Is it right? I think we should use `H2 `better

![image](https://user-images.githubusercontent.com/35389145/153699950-be591ab6-f882-4bc3-a447-5b52f7e14da8.png)
