### ISSUE TITLE
Add example that implements the Metadata SPI for third-party JDBC pools

### ISSUE THREAD

**Issue by linghengqian** [apache/shardingsphere#15507]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?

No.

### Describe the feature you would like.

In ShardingSphere `5.1.0`, using the JDBC pool is required to have multiple classes that implements its corresponding metadata SPI. This is available at https://shardingsphere.apache.org/document/current/en/dev-manual/data-source/ manifested, but not obvious.

Under the `org.apache.shardingsphere.infra.datasource.pool.metadata.type` package, three JDBC pools such as `DBCP`, `HikariCP`, `Tomcat DBCP` (Not `Tomcat JDBC Pool`) are integrated by default, and implements the corresponding `org.apache.shardingsphere.infra.datasource.pool.metadata.DataSourcePoolMetaData` and `org.apache.shardingsphere.infra.datasource.pool.metadata.DataSourceJdbcUrlMetaData` interfaces. In addition, for `HikariCP`, it also implements the `org.apache.shardingsphere.infra.datasource.pool.destroyer.DataSourcePoolDestroyer` interface.

![image](https://user-images.githubusercontent.com/20187731/154699793-937d48ca-42b3-4dde-bede-58a7c3e21fe6.png)

In the case of using a third-party `JDBC pool` that does not implement the metadata SPI (using `Alibaba Druid` as an example), the information the user gets is not clear. The user is likely to get something like this.

```shell
Caused by: java.lang.NoClassDefFoundError: org/apache/tomcat/dbcp/dbcp2/BasicDataSource
	at org.apache.shardingsphere.infra.datasource.pool.metadata.type.dbcp.TomcatDBCPDataSourcePoolMetaData.getType(TomcatDBCPDataSourcePoolMetaData.java:67) ~[shardingsphere-infra-common-5.1.0.jar:5.1.0]
	at org.apache.shardingsphere.spi.typed.TypedSPIRegistry.lambda$findRegisteredService$0(TypedSPIRegistry.java:44) ~[shardingsphere-spi-5.1.0.jar:5.1.0]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[na:1.8.0_312]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361) ~[na:1.8.0_312]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[na:1.8.0_312]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[na:1.8.0_312]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[na:1.8.0_312]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_312]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[na:1.8.0_312]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_312]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531) ~[na:1.8.0_312]
	at org.apache.shardingsphere.spi.typed.TypedSPIRegistry.findRegisteredService(TypedSPIRegistry.java:44) ~[shardingsphere-spi-5.1.0.jar:5.1.0]
	at org.apache.shardingsphere.infra.datasource.pool.metadata.DataSourcePoolMetaDataFactory.newInstance(DataSourcePoolMetaDataFactory.java:46) ~[shardingsphere-infra-common-5.1.0.jar:5.1.0]
	at org.apache.shardingsphere.infra.datasource.props.DataSourceProperties.<init>(DataSourceProperties.java:53) ~[shardingsphere-infra-common-5.1.0.jar:5.1.0]
	at org.apache.shardingsphere.spring.boot.datasource.DataSourceMapSetter.getDataSource(DataSourceMapSetter.java:92) ~[shardingsphere-jdbc-spring-boot-starter-infra-5.1.0.jar:5.1.0]
	at org.apache.shardingsphere.spring.boot.datasource.DataSourceMapSetter.getDataSourceMap(DataSourceMapSetter.java:65) ~[shardingsphere-jdbc-spring-boot-starter-infra-5.1.0.jar:5.1.0]
	at org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration.setEnvironment(ShardingSphereAutoConfiguration.java:122) ~[shardingsphere-jdbc-core-spring-boot-starter-5.1.0.jar:5.1.0]
	at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:110) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:102) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.15.jar:5.3.15]
	... 29 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.tomcat.dbcp.dbcp2.BasicDataSource
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[na:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_312]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[na:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_312]
	... 51 common frames omitted
```

I think an example can be added at https://github.com/apache/shardingsphere/tree/master/examples to provide users with reference. I believe this is also helpful to users of `C3P0` and `BeeCP`.

**Comment by linghengqian** [comment]
Because the Example module looks like it's being refactored, and a number of related issues are being addressed. Therefore, I think this issue should be postponed. (Uncertain about the placement and format of the integration content related to the `JDBC Pools`)

**Comment by linghengqian** [comment]
I created a simple test case to help locate this situation. It's at https://github.com/linghengqian/shardingsphere-jdbc-pools-test

**Comment by zjcnb** [comment]
> I created a simple test case to help locate this situation. It's at https://github.com/linghengqian/shardingsphere-jdbc-pools-test

Thx.

**Comment by linghengqian** [comment]
Maybe the content description on the first floor is wrong. After referring to the operation of the website https://github.com/apache/shardingsphere/issues/15563 , I noticed that the introduction of `org.apache.commons:commons-dbcp2:2.9.0` still reported an error , you must import `org.apache.tomcat:tomcat-dbcp` to be normal (regardless of the version of this component is `9.0.58` or `10.0.14` ), which seems strange.

**Comment by linghengqian** [comment]
@zjcnb 
- If this related issue is a bug rather than a feature, I should close this issue and specify in the `FAQ` that ShardingSphere JDBC `5.1.0` uses a non-hikaricp JDBC Pool that needs to import `org.apache.tomcat:tomcat-dbcp` ?

**Comment by linghengqian** [comment]
@zjcnb 

- The bugs involved in this issue have been fixed for a long time, and the description does not point to a discussion. Adding an example of the required SPI doesn't make much sense for consumers at this point. 

- I think closing this issue is a good choice？

**Comment by linghengqian** [comment]
I think https://github.com/apache/shardingsphere/issues/19607 would provide a reasonable example for the c3p0 JDBC pool.  So I don't think there's more to do with this issue.
