### ISSUE TITLE
Exception in getting data source from jfinal integration

### ISSUE THREAD

**Issue by lyh061619** [apache/shardingsphere#15563]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.1.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Actual behavior
Get data source
### Reason analyze (If you can)

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/tomcat/dbcp/dbcp2/BasicDataSource
	at org.apache.shardingsphere.infra.datasource.pool.metadata.type.dbcp.TomcatDBCPDataSourcePoolMetaData.getType(TomcatDBCPDataSourcePoolMetaData.java:67)
	at org.apache.shardingsphere.spi.typed.TypedSPIRegistry.lambda$findRegisteredService$0(TypedSPIRegistry.java:44)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at org.apache.shardingsphere.spi.typed.TypedSPIRegistry.findRegisteredService(TypedSPIRegistry.java:44)
	at org.apache.shardingsphere.infra.datasource.pool.metadata.DataSourcePoolMetaDataFactory.newInstance(DataSourcePoolMetaDataFactory.java:46)
	at org.apache.shardingsphere.infra.datasource.props.DataSourcePropertiesCreator.createProperties(DataSourcePropertiesCreator.java:81)
	at org.apache.shardingsphere.infra.datasource.props.DataSourcePropertiesCreator.create(DataSourcePropertiesCreator.java:57)
	at org.apache.shardingsphere.infra.metadata.resource.DataSourcesMetaData.<init>(DataSourcesMetaData.java:41)
	at org.apache.shardingsphere.infra.metadata.ShardingSphereMetaData.createResource(ShardingSphereMetaData.java:73)
	at org.apache.shardingsphere.infra.metadata.ShardingSphereMetaData.create(ShardingSphereMetaData.java:66)
	at org.apache.shardingsphere.mode.metadata.MetaDataContextsBuilder.getMetaDataMap(MetaDataContextsBuilder.java:105)
	at org.apache.shardingsphere.mode.metadata.MetaDataContextsBuilder.build(MetaDataContextsBuilder.java:96)
	at org.apache.shardingsphere.mode.manager.memory.MemoryContextManagerBuilder.build(MemoryContextManagerBuilder.java:49)
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.createContextManager(ShardingSphereDataSource.java:81)
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.<init>(ShardingSphereDataSource.java:64)
	at org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactory.createDataSource(ShardingSphereDataSourceFactory.java:77)
	at org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactory.createDataSource(ShardingSphereDataSourceFactory.java:92)
	at org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactory.createDataSource(ShardingSphereDataSourceFactory.java:151)
	at com.demo.common.DemoConfig.configPlugin(DemoConfig.java:133)
	at com.jfinal.core.Config.configPluginWithOrder(Config.java:70)
	at com.jfinal.core.Config.configJFinal(Config.java:59)
	at com.jfinal.core.JFinal.init(JFinal.java:61)
	at com.jfinal.core.JFinalFilter.init(JFinalFilter.java:64)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:111)
	at io.undertow.servlet.core.ManagedFilter.createFilter(ManagedFilter.java:80)
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:594)
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:559)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:601)
	at com.jfinal.server.undertow.UndertowServer.configHttp(UndertowServer.java:287)
	at com.jfinal.server.undertow.UndertowServer.doStart(UndertowServer.java:265)
	at com.jfinal.server.undertow.UndertowServer.start(UndertowServer.java:158)
	at com.jfinal.server.undertow.UndertowServer.start(UndertowServer.java:83)
	at com.demo.common.DemoConfig.main(DemoConfig.java:48)
Caused by: java.lang.ClassNotFoundException: org.apache.tomcat.dbcp.dbcp2.BasicDataSource
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 43 more

### Example codes for reproduce this issue (such as a github link).
ShardingRuleConfiguration configuration =new ShardingRuleConfiguration();
		
		DruidPlugin druidPlugin = new DruidPlugin(p.get("jdbcUrl"), p.get("user"), p.get("password"));
		druidPlugin.start();
		me.add(druidPlugin);
		
	    Map<String, DataSource> dataSourceMap = new HashMap<>();
	    dataSourceMap.put("db0", druidPlugin.getDataSource());
	    
	    ShardingTableRuleConfiguration blogRule = new ShardingTableRuleConfiguration("blog", "db0.blog_${0..9}");
	    blogRule.setKeyGenerateStrategy(new KeyGenerateStrategyConfiguration("id", "snowflake"));
	    configuration.getTables().add(blogRule);
	    
	    configuration.setDefaultTableShardingStrategy(new StandardShardingStrategyConfiguration("id", "blog_inline"));
        Properties props2 =new Properties();
        props2.setProperty("algorithm-expression","blog_${id % 10}");
        configuration.getShardingAlgorithms().put("blog_inline",new ShardingSphereAlgorithmConfiguration("INLINE",props2));
        
        Properties prop3 = new Properties();
        configuration.getKeyGenerators().put("snowflake", new ShardingSphereAlgorithmConfiguration("SNOWFLAKE", prop3));
	   
	    DataSource dataSource = null;
		try {
			dataSource = ShardingSphereDataSourceFactory.createDataSource(dataSourceMap, Collections.singleton(configuration), new Properties());
		} catch (SQLException e) {
			e.printStackTrace();
		}
	    ActiveRecordPlugin arp = new ActiveRecordPlugin(dataSource);
	    arp.setContainerFactory(new CaseInsensitiveContainerFactory());
	    arp.setDialect(new MysqlDialect());
	    arp.setDevMode(true);
	    arp.setShowSql(true);
}

**Comment by lyh061619** [comment]
Ali Druid JDBC connection pool. Look at POM Tomcat DBCP jar package test dependency. Shouldn't formal release be unnecessary

**Comment by zjcnb** [comment]
> Ali Druid JDBC connection pool. Look at POM Tomcat DBCP jar package test dependency. Shouldn't formal release be unnecessary

@lyh061619 Thank you for your feedback , i will see it. And Can you provider a demo?

**Comment by lyh061619** [comment]
> > Ali Druid JDBC connection pool. Look at POM Tomcat DBCP jar package test dependency. Shouldn't formal release be unnecessary
> 
> @lyh061619 Thank you for your feedback , i will see it. And Can you provider a demo?
of course
[jfinal_demo_for_maven.zip](https://github.com/apache/shardingsphere/files/8114116/jfinal_demo_for_maven.zip)

**Comment by zjcnb** [comment]
Thx

**Comment by lyh061619** [comment]
> Thx

Remove the Tomcat DBCP dependency from the local test POM. Note that MVN compiler 1.8+

**Comment by zjcnb** [comment]
> > Thx
> 
> Remove the Tomcat DBCP dependency from the local test POM. Note that MVN compiler jdk 1.8+

I download it and check it. The `ShardingSphere` not supprot `mariadb` now, When i change to `mysql` it 's work well.

**Comment by lyh061619** [comment]
> 



> > > Thx
> > 
> > 
> > Remove the Tomcat DBCP dependency from the local test POM. Note that MVN compiler jdk 1.8+
> 
> I download it and check it. The `ShardingSphere` not supprot `mariadb` now, When i change to `mysql` it 's work well.

**Comment by lyh061619** [comment]
> > > Thx
> > 
> > 
> > Remove the Tomcat DBCP dependency from the local test POM. Note that MVN compiler jdk 1.8+
> 
> I download it and check it. The `ShardingSphere` not supprot `mariadb` now, When i change to `mysql` it 's work well.

I use MariaDB and POM to add Tomcat DBCP jar, which is also normal

**Comment by zjcnb** [comment]
> > > > Thx
> > > 
> > > 
> > > Remove the Tomcat DBCP dependency from the local test POM. Note that MVN compiler jdk 1.8+
> > 
> > 
> > I download it and check it. The `ShardingSphere` not supprot `mariadb` now, When i change to `mysql` it 's work well.
> 
> I use MariaDB and POM to add Tomcat DBCP jar, which is also normal

I suggest change to `mysql` database if you use `ShardingSphere`.

**Comment by lyh061619** [comment]
> 

I see. There is no such problem when testing version 5.0.0. This problem will occur when testing version 5.1.0

**Comment by zjcnb** [comment]
> > 
> 
> I see. There is no such problem when testing version 5.0.0. This problem will occur when testing version 5.1.0

Yeah, Let me double check it.

**Comment by lyh061619** [comment]
> > > 
> > 
> > 
> > I see. There is no such problem when testing version 5.0.0. This problem will occur when testing version 5.1.0
> 
> Yeah, Let me double check it.

Yes, the MariaDB I use uses Mysql to drive the connection URL: JDBC: MySQL. There is no problem with the connection test

This problem should not be the problem of data differences

So I think there is a bug in version 5.1.0

**Comment by zjcnb** [comment]
> > > > 
> > > 
> > > 
> > > I see. There is no such problem when testing version 5.0.0. This problem will occur when testing version 5.1.0
> > 
> > 
> > Yeah, Let me double check it.
> 
> Yes, the MariaDB I use uses Mysql to drive the connection URL: JDBC: MySQL. There is no problem with the connection test
> 
> This problem should not be the problem of data differences
> 
> So I think there is a bug in version 5.1.0

refer to #15507

**Comment by linghengqian** [comment]
> > Thx
> 
> Remove the Tomcat DBCP dependency from the local test POM. Note that MVN compiler jdk 1.8+

I have to wonder if this step can be carried out. Because in the metadata SPI implementation of `ShardingSphere` 5.1.0, the corresponding classes for the related JDBC Pools are called directly. If it is `reflect` by the class name, this in turn affects the packaging of `GraalVM`, requiring the addition of new hints.

What do you think?
