### ISSUE TITLE
sharding sphere 5.1version not support this SQL query statements

### ISSUE THREAD

**Issue by yuwentao** [apache/shardingsphere#15618]
version:shardingsphere 5.1.0 

SQL:
SELECT old.id AS id, old.name, new.id AS quoteId, new.name FROM s_field old INNER JOIN (SELECT id, relate_field, name FROM s_field WHERE show_type = 'quote' AND verify_type = 'customer_addr' AND function_id = 1415965658951864322 AND tenant_id = 1 AND tenant_id = 1) new ON new.relate_field = old.copy_field_id WHERE old.tenant_id = 1 UNION SELECT old.id AS id, old.name, new.id AS quoteId, new.name FROM s_field old INNER JOIN (SELECT id, relate_field, name FROM s_field WHERE show_type = 'quote' AND verify_type != 'customer_addr' AND function_id = 1415965658951864322 AND tenant_id = 1 AND tenant_id = 1) new ON new.relate_field = old.id WHERE old.tenant_id = 1

Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.NullPointerException
        at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
        at sun.reflect.GeneratedMethodAccessor171.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
        ... 171 more
Caused by: java.lang.NullPointerException
        at org.apache.shardingsphere.infra.binder.segment.select.subquery.engine.SubqueryTableContextEngine.createSubqueryTableContexts(SubqueryTableContextEngine.java:43)
        at org.apache.shardingsphere.infra.binder.segment.table.TablesContext.createSubqueryTables(TablesContext.java:85)
        at org.apache.shardingsphere.infra.binder.segment.table.TablesContext.<init>(TablesContext.java:78)
2022-02-24 17:19:05.059        at org.apache.shardingsphere.infra.binder.statement.dml.SelectStatementContext.<init>(SelectStatementContext.java:105)
         at org.apache.shardingsphere.infra.binder.SQLStatementContextFactory.getDMLStatementContext(SQLStatementContextFactory.java:133)

**Comment by strongduanmu** [comment]
@yuwentao Thank you for your feedback, can you translate your title to english? And provide your sharding configuration?

**Comment by yuwentao** [comment]
have opened sql-federation =true:
Properties props = new Properties();
props.setProperty(ConfigurationPropertyKey.SQL_FEDERATION_ENABLED.getKey(), String.valueOf(Boolean.TRUE));
props.setProperty(ConfigurationPropertyKey.SQL_SHOW.getKey(), Boolean.TRUE.toString());

**Comment by yuwentao** [comment]
> @yuwentao Thank you for your feedback, can you provide your sharding configuration and table init sql?

if I need to modify my sql Statment about "union"?

**Comment by yuwentao** [comment]
https://shardingsphere.apache.org/document/5.1.0/cn/features/sharding/use-norms/sql/
Experimental supported SQL:
SELECT col1, col2 FROM tbl_name UNION SELECT col1, col2 FROM tbl_name |  
SELECT col1, col2 FROM tbl_name UNION ALL SELECT col1, col2 FROM tbl_name

**Comment by anonymous-lj** [comment]
I also encountered similar problems, which should be caused by union

**Comment by pengzhizhuo** [comment]
I also encountered similar problems

**Comment by RaigorJiang** [comment]
This issue has been inactive for a long time, and ShardingSphere has released several new versions, so I will close it.
Please try the latest version, and if the problem reproduces, please reopen it or submit a new one.
