### ISSUE TITLE
sql contains '@' , paser error

### ISSUE THREAD

**Issue by xsong123** [apache/shardingsphere#15622]
shardingsphere version 5.0.0
mysql version 5.7

sql as below:
SELECT
            ddt.DefaultDate default_date,
            ddt.DefaultDateBalance default_date_prin_bal,
            CASE WHEN ddt.DefaultType = 'A' THEN '00'
                WHEN ddt.DefaultType = 'B' THEN '01'
                WHEN ddt.DefaultType = 'D' THEN '02'
                WHEN ddt.DefaultType = 'E' THEN '03'
                ELSE ddt.DefaultType
            END default_type,
            ddt.FirstDisposalDate disp_start_date,

            @num := IF(@key = ddt.ASSETCODE, @num + 1, 1) rn,
            @key := ddt.ASSETCODE assetcode
        FROM
	AssetDefaultDisposalTrust_fb2107202348 ddt,
	(SELECT @KEY := '', @num := 0) t1
WHERE
	ddt.productcode = 'XMDM202107202348'
AND ddt.datadate <= str_to_date (
	'2021-11-25 0:00:00',
	'yyyy-MM-dd hh24:mi:ss'
)

paser error:
Caused by: org.apache.shardingsphere.sql.parser.exception.SQLParsingException: You have an error in your SQL syntax
	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.twoPhaseParse(SQLParserExecutor.java:68)
	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.parse(SQLParserExecutor.java:49)
	at org.apache.shardingsphere.sql.parser.api.SQLParserEngine.parse(SQLParserEngine.java:51)
	at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserExecutor.parse(SQLStatementParserExecutor.java:47)
	at org.apache.shardingsphere.infra.parser.cache.SQLStatementCacheLoader.load(SQLStatementCacheLoader.java:40)
	at org.apache.shardingsphere.infra.parser.cache.SQLStatementCacheLoader.load(SQLStatementCacheLoader.java:29)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 65 more

**Comment by strongduanmu** [comment]
@xsong123 Thank you for your feedback, I will investigate this problem.
