### ISSUE TITLE
Does shardingsphere-jdbc version 5.1.0 not support column name start with underline, e.g. _code ?

### ISSUE THREAD

**Issue by arewei** [apache/shardingsphere#15940]
## Question

Does shardingsphere-jdbc version 5.1.0 not support column name start with underline, e.g. _code ?
full sql is: 
```sql
SELECT id,_code,_name,_value,remark,created_by,created_account_name,created_date,last_modified_by,last_modified_account_name,last_modified_date FROM sys_config
```

the exception is:
```java
Caused by: org.apache.shardingsphere.sql.parser.exception.SQLParsingException: You have an error in your SQL syntax
	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.twoPhaseParse(SQLParserExecutor.java:68)
	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.parse(SQLParserExecutor.java:49)
	at org.apache.shardingsphere.sql.parser.api.SQLParserEngine.parse(SQLParserEngine.java:47)
	at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserExecutor.parse(SQLStatementParserExecutor.java:48)
	at org.apache.shardingsphere.infra.parser.cache.SQLStatementCacheLoader.load(SQLStatementCacheLoader.java:41)
	at org.apache.shardingsphere.infra.parser.cache.SQLStatementCacheLoader.load(SQLStatementCacheLoader.java:30)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 99 common frames omitted
```

**Comment by RaigorJiang** [comment]
Hi @arewei 
Fields starting with `_` are not currently supported, but you can use them by adding quotes, e.g. `_code`:
```sql
SELECT id,`_code`,`_name`,`_value`,remark,created_by,created_account_name,created_date,last_modified_by,last_modified_account_name,last_modified_date FROM sys_config
```

**Comment by strongduanmu** [comment]
Hi @arewei Thank you for your feedback, @tuichenchuxin Can you help check this issue?

**Comment by arewei** [comment]
@RaigorJiang , @strongduanmu  Thanks a lot, it works by adding quotes.
