### ISSUE TITLE
The unit test execute failed occasionally in shardingsphere-proxy-backend

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#16039]
```
Error:  Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.021 s <<< FAILURE! - in org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngineTest
Error:  assertBinaryProtocolQueryHeader(org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngineTest)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.shardingsphere.proxy.backend.context.BackendExecutorContext
 at org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngineTest.assertBinaryProtocolQueryHeader(JDBCDatabaseCommunicationEngineTest.java:114)

Error:  assertCloseResultSetsWithExceptionThrown(org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngineTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.shardingsphere.proxy.backend.context.BackendExecutorContext
 at org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngineTest.assertCloseResultSetsWithExceptionThrown(JDBCDatabaseCommunicationEngineTest.java:216)

Error:  assertCloseCorrectly(org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngineTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.shardingsphere.proxy.backend.context.BackendExecutorContext
 at org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngineTest.assertCloseCorrectly(JDBCDatabaseCommunicationEngineTest.java:201)

Error:  assertAddResultSetCorrectly(org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngineTest)  Time elapsed: 0.009 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.shardingsphere.proxy.backend.context.BackendExecutorContext
 at org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngineTest.assertAddResultSetCorrectly(JDBCDatabaseCommunicationEngineTest.java:191)

Error:  assertAddStatementCorrectly(org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngineTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.shardingsphere.proxy.backend.context.BackendExecutorContext
 at org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngineTest.assertAddStatementCorrectly(JDBCDatabaseCommunicationEngineTest.java:181)

[INFO] Running org.apache.shardingsphere.proxy.backend.communication.jdbc.datasource.JDBCBackendDataSourceTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.222 s - in org.apache.shardingsphere.proxy.backend.communication.jdbc.datasource.JDBCBackendDataSourceTest
[INFO] Running org.apache.shardingsphere.proxy.backend.context.ProxyContextTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.066 s - in org.apache.shardingsphere.proxy.backend.context.ProxyContextTest
[INFO] Running org.apache.shardingsphere.proxy.backend.context.BackendExecutorContextTest
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.003 s <<< FAILURE! - in org.apache.shardingsphere.proxy.backend.context.BackendExecutorContextTest
Error:  assertGetInstance(org.apache.shardingsphere.proxy.backend.context.BackendExecutorContextTest)  Time elapsed: 0.002 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.shardingsphere.proxy.backend.context.BackendExecutorContext
 at org.apache.shardingsphere.proxy.backend.context.BackendExecutorContextTest.assertGetInstance(BackendExecutorContextTest.java:54)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Errors: 
Error:    DatabaseCommunicationEngineFactoryTest.assertNewBinaryProtocolInstance:79 » NoClassDefFound
Error:    DatabaseCommunicationEngineFactoryTest.assertNewTextProtocolInstance:70 » NoClassDefFound
Error:    ProxySQLExecutorTest.assertCheckExecutePrerequisitesWhenExecuteDDLInBaseTransaction:88 » NoClassDefFound
Error:    ProxySQLExecutorTest.assertCheckExecutePrerequisitesWhenExecuteDDLInMySQLTransaction:120 » ExceptionInInitializer
Error:    ProxySQLExecutorTest.assertCheckExecutePrerequisitesWhenExecuteDDLInPostgreSQLTransaction » 
Error:    ProxySQLExecutorTest.assertCheckExecutePrerequisitesWhenExecuteDDLInXATransaction » 
Error:    ProxySQLExecutorTest.assertCheckExecutePrerequisitesWhenExecuteDDLNotInPostgreSQLTransaction:129 » NoClassDefFound
Error:    ProxySQLExecutorTest.assertCheckExecutePrerequisitesWhenExecuteDDLNotInXATransaction:96 » NoClassDefFound
Error:    ProxySQLExecutorTest.assertCheckExecutePrerequisitesWhenExecuteDMLInPostgreSQLTransaction:112 » NoClassDefFound
Error:    ProxySQLExecutorTest.assertCheckExecutePrerequisitesWhenExecuteDMLInXATransaction:80 » NoClassDefFound
Error:    JDBCDatabaseCommunicationEngineTest.assertAddResultSetCorrectly:191 » NoClassDefFound
Error:    JDBCDatabaseCommunicationEngineTest.assertAddStatementCorrectly:181 » NoClassDefFound
Error:    JDBCDatabaseCommunicationEngineTest.assertBinaryProtocolQueryHeader:114 » NoClassDefFound
Error:    JDBCDatabaseCommunicationEngineTest.assertCloseCorrectly:201 » NoClassDefFound
Error:    JDBCDatabaseCommunicationEngineTest.assertCloseResultSetsWithExceptionThrown:216 » NoClassDefFound
Error:    BackendExecutorContextTest.assertGetInstance:54 NoClassDefFound Could not init...
```

**Comment by menghaoranss** [comment]
It may be caused by multiple unit tests using `ProxyContext` at the same time, I will follow up.

**Comment by TeslaCN** [comment]
I think this has been fixed in https://github.com/apache/shardingsphere/pull/17802.
