### ISSUE TITLE
 ContextManager onInitialized callback for 'RULE_ALTERED_JOB_WORKER' failed.

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#16211]
### Which version of ShardingSphere did you use?

`master`

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

`ShardingSphere-Proxy`

```
[ERROR] 2022-03-19 19:39:52.560 [main] o.a.s.p.i.BootstrapInitializer - contextManager onInitialized callback for 'RULE_ALTERED_JOB_WORKER' failed
org.apache.shardingsphere.mode.repository.cluster.ClusterPersistRepositoryException: java.lang.IllegalStateException: Already started
	at org.apache.shardingsphere.mode.repository.cluster.zookeeper.handler.CuratorZookeeperExceptionHandler.handleException(CuratorZookeeperExceptionHandler.java:51)
	at org.apache.shardingsphere.mode.repository.cluster.zookeeper.CuratorZookeeperRepository.start(CuratorZookeeperRepository.java:260)
	at org.apache.shardingsphere.mode.repository.cluster.zookeeper.CuratorZookeeperRepository.watch(CuratorZookeeperRepository.java:251)
	at org.apache.shardingsphere.data.pipeline.core.api.impl.GovernanceRepositoryAPIImpl.watch(GovernanceRepositoryAPIImpl.java:120)
	at org.apache.shardingsphere.data.pipeline.core.execute.PipelineJobExecutor.watchGovernanceRepositoryConfiguration(PipelineJobExecutor.java:52)
	at org.apache.shardingsphere.data.pipeline.core.execute.PipelineJobExecutor.doStart(PipelineJobExecutor.java:48)
	at org.apache.shardingsphere.data.pipeline.api.executor.AbstractLifecycleExecutor.start(AbstractLifecycleExecutor.java:41)
	at org.apache.shardingsphere.data.pipeline.scenario.rulealtered.RuleAlteredJobWorker.initWorkerIfNecessary(RuleAlteredJobWorker.java:117)
	at org.apache.shardingsphere.data.pipeline.scenario.rulealtered.spi.ContextManagerLifecycleListenerImpl.onInitialized(ContextManagerLifecycleListenerImpl.java:46)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.contextManagerInitializedCallback(BootstrapInitializer.java:80)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.init(BootstrapInitializer.java:59)
	at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:47)
Caused by: java.lang.IllegalStateException: Already started
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at org.apache.curator.framework.recipes.cache.CuratorCacheImpl.start(CuratorCacheImpl.java:88)
	at org.apache.shardingsphere.mode.repository.cluster.zookeeper.CuratorZookeeperRepository.start(CuratorZookeeperRepository.java:256)
	... 10 common frames omitted
[INFO ] 2022-03-19 19:39:52.610 [main] o.a.s.p.v.ShardingSphereProxyVersion - Database name is `MySQL`, version is `8.0.25`
[INFO ] 2022-03-19 19:39:52.896 [main] o.a.s.p.frontend.ShardingSphereProxy - ShardingSphere-Proxy Cluster mode started successfully
```

### Configuration

```
schemaName: sharding_db

dataSources:
 ds_0:
   url: jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false
   username: root
   password: 123456
   connectionTimeoutMilliseconds: 30000
   idleTimeoutMilliseconds: 60000
   maxLifetimeMilliseconds: 1800000
   maxPoolSize: 50
   minPoolSize: 1
 ds_1:
   url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false
   username: root
   password: 123456
   connectionTimeoutMilliseconds: 30000
   idleTimeoutMilliseconds: 60000
   maxLifetimeMilliseconds: 1800000
   maxPoolSize: 50
   minPoolSize: 1

rules:
- !SHARDING
 tables:
   t_order:
     actualDataNodes: ds_${0..1}.t_order_${0..1}
     tableStrategy:
       standard:
         shardingColumn: order_id
         shardingAlgorithmName: t_order_inline
     keyGenerateStrategy:
       column: order_id
       keyGeneratorName: snowflake
   t_order_item:
     actualDataNodes: ds_${0..1}.t_order_item_${0..1}
     tableStrategy:
       standard:
         shardingColumn: order_id
         shardingAlgorithmName: t_order_item_inline
     keyGenerateStrategy:
       column: order_item_id
       keyGeneratorName: snowflake
 bindingTables:
   - t_order,t_order_item
 defaultDatabaseStrategy:
   standard:
     shardingColumn: user_id
     shardingAlgorithmName: database_inline
 defaultTableStrategy:
   none:
 
 shardingAlgorithms:
   database_inline:
     type: INLINE
     props:
       algorithm-expression: ds_${user_id % 2}
   t_order_inline:
     type: INLINE
     props:
       algorithm-expression: t_order_${order_id % 2}
   t_order_item_inline:
     type: INLINE
     props:
       algorithm-expression: t_order_item_${order_id % 2}
 
 keyGenerators:
   snowflake:
     type: SNOWFLAKE
```

**Comment by sandynz** [comment]
Looks it's affected by #15672, code changes:
<img width="1437" alt="图片" src="https://user-images.githubusercontent.com/42492540/159120088-feecb84b-f791-4790-a8f7-107473ed77e8.png">

Every time call of `watch` will trigger `cache.start();`.

@menghaoranss Could you help to have a look at it when you have time?

**Comment by menghaoranss** [comment]
> Looks it's affected by #15672, code changes: <img alt="图片" width="1437" src="https://user-images.githubusercontent.com/42492540/159120088-feecb84b-f791-4790-a8f7-107473ed77e8.png">
> 
> Every time call of `watch` will trigger `cache.start();`.
> 
> @menghaoranss Could you help to have a look at it when you have time?

I will follow up.
