### ISSUE TITLE
Run Bootstrap in IDE failed since ClassNotFoundException: com.zaxxer.hikari.HikariDataSource

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#16216]
### Which version of ShardingSphere did you use?
master branch, commit cc529b55da374b63f48886329e65e29f3596a26b

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy.
Run `Bootstrap` in IDE.

### Expected behavior
No exception

### Actual behavior
Could not start, exception:
```
Exception in thread "main" java.lang.ClassNotFoundException: com.zaxxer.hikari.HikariDataSource
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.shardingsphere.infra.datasource.pool.creator.DataSourcePoolCreator.createDataSource(DataSourcePoolCreator.java:75)
	at org.apache.shardingsphere.infra.datasource.pool.creator.DataSourcePoolCreator.create(DataSourcePoolCreator.java:59)
	at org.apache.shardingsphere.infra.datasource.pool.creator.DataSourcePoolCreator.lambda$create$0(DataSourcePoolCreator.java:49)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.apache.shardingsphere.infra.datasource.pool.creator.DataSourcePoolCreator.create(DataSourcePoolCreator.java:49)
	at org.apache.shardingsphere.mode.metadata.persist.MetaDataPersistService.getEffectiveDataSources(MetaDataPersistService.java:127)
	at org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.createSchemaConfiguration(ClusterContextManagerBuilder.java:134)
	at org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.createMetaDataContextsBuilder(ClusterContextManagerBuilder.java:127)
	at org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.build(ClusterContextManagerBuilder.java:71)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.createContextManager(BootstrapInitializer.java:72)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.init(BootstrapInitializer.java:57)
	at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:47)
```

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Run `Bootstrap` in IDE.

**Comment by sandynz** [comment]
Already fixed.
