### ISSUE TITLE
ShardingSphere-Proxy PostgreSQL in memory mode startup failed since #16272

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#16301]
### Which version of ShardingSphere did you use?

master - edf83226b03c979af77543a34356ad435c330749

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy PostgreSQL

### Expected behavior

ShardingSphere-Proxy PostgreSQL in memory mode startup succeeded.

### Actual behavior

ShardingSphere-Proxy MySQL startup succeeded.

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.apache.shardingsphere.infra.metadata.schema.ShardingSphereSchema.getTables()" because the return value of "org.apache.shardingsphere.infra.metadata.ShardingSphereMetaData.getSchema()" is null
	at org.apache.shardingsphere.infra.federation.optimizer.metadata.FederationMetaData.<init>(FederationMetaData.java:38)
	at org.apache.shardingsphere.infra.federation.optimizer.context.OptimizerContextFactory.create(OptimizerContextFactory.java:47)
	at org.apache.shardingsphere.mode.metadata.MetaDataContextsBuilder.build(MetaDataContextsBuilder.java:113)
	at org.apache.shardingsphere.mode.manager.memory.MemoryContextManagerBuilder.build(MemoryContextManagerBuilder.java:58)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.createContextManager(BootstrapInitializer.java:72)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.init(BootstrapInitializer.java:57)
	at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:47)
```

**Comment by strongduanmu** [comment]
@TeslaCN Thank you for your feedback, I will investigate this issue.

**Comment by TeslaCN** [comment]
@strongduanmu 
I found this issue is caused by my configuration:
```yaml
schemaName: postgres
dataSources:
  ds_0:
    url: jdbc:postgresql://127.0.0.1:5432/postgres?prepareThreshold=1
    username: postgres
    password: postgres
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 32
    minPoolSize: 0

rules: []
```

**Comment by strongduanmu** [comment]
@TeslaCN Thank you, I will optimize this problem.
