### ISSUE TITLE
Execute `show databases;` failure since NPE thrown with new namespace in proxy cluster mode

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#16458]
### Which version of ShardingSphere did you use?
master branch, commit f8ff9963de642e0a26f3ff8d38a172c0e28229a0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
No exception occur.

### Actual behavior
SQL:
```
mysql> create database scaling_bmsql;
ERROR 1997 (C1997): Runtime exception: [null]
mysql> show databases;
ERROR 1997 (C1997): Runtime exception: [null]
```

Exception stack trace:
```
[ERROR] 2022-03-29 14:23:50.475 [Connection-1-ThreadExecutor] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
java.lang.NullPointerException: null
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.parseSql(MySQLComQueryPacketExecutor.java:82)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.<init>(MySQLComQueryPacketExecutor.java:70)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecutorFactory.newInstance(MySQLCommandExecutorFactory.java:75)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandExecutor(MySQLCommandExecuteEngine.java:62)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:98)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Reason analyze (If you can)
In `MySQLComQueryPacketExecutor.parseSql`:
```
        ShardingSphereSQLParserEngine sqlStatementParserEngine = new ShardingSphereSQLParserEngine(
                DatabaseTypeRegistry.getTrunkDatabaseTypeName(metaDataContexts.getMetaData(schemaName).getResource().getDatabaseType()),
                metaDataContexts.getGlobalRuleMetaData().findSingleRule(SQLParserRule.class).orElseThrow(() -> new IllegalStateException("SQLParserRule not found")).toParserConfiguration());
```
`schemaName` is null, `metaDataContexts.getMetaData(schemaName)` return null.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. Modify `server.yaml`, in Cluster mode repository ZooKeeper, change `namespace` to a new one, e.g. `ns0329`.
2. Start Proxy.
3. Login to proxy with MySQL client, execute SQLs: `show databases;`, `create database scaling_bmsql;`.

**Comment by zjcnb** [comment]
Same question #16456
