### ISSUE TITLE
Splitting H2RepositoryTest.assertMethod() into multiple unit test.

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#16507]
```
    @Test
    public void assertMethod() {
        assertThat(h2Repository.getType(), is("H2"));
        assertSetProperty();
        assertPersistAndGet();
        assertPersistAndGetChildrenKeys();
        assertDelete();
        h2Repository.close();
    }
```

Splitting assertMethod() method.

**Comment by Devamparikh** [comment]
Can I take this up? I am willing to try this. :-)

**Comment by zjcnb** [comment]
> Can I take this up? I am willing to try this. :-)

Welcome, i assign you.

**Comment by Devamparikh** [comment]
Hey there, I'm having below error while splitting assertMethod can @zjcnb help me to understand and remove it? Also it would be helpful if you could tell me, Am I on correct path! 
thank you in advance :-)
``` 
java.lang.NullPointerException: Cannot invoke "java.sql.Connection.prepareStatement(String)" because "this.connection" is null

	at org.apache.shardingsphere.mode.repository.standalone.h2.H2Repository.get(H2Repository.java:85)
	at org.apache.shardingsphere.mode.repository.standalone.h2.H2Repository.persist(H2Repository.java:129)
	at org.apache.shardingsphere.mode.repository.standalone.h2.H2RepositoryTest.assertMethodPersistAndGet(H2RepositoryTest.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```
![Screenshot from 2022-04-01 15-38-08](https://user-images.githubusercontent.com/60180815/161243159-b5d03b58-e3d2-42b2-bd53-b546802f525e.png)

**Comment by zjcnb** [comment]
> Hey there, I'm having below error while splitting assertMethod can @zjcnb help me to understand and remove it? Also it would be helpful if you could tell me, Am I on correct path! thank you in advance :-)
> 
> ```
> java.lang.NullPointerException: Cannot invoke "java.sql.Connection.prepareStatement(String)" because "this.connection" is null
> 
> 	at org.apache.shardingsphere.mode.repository.standalone.h2.H2Repository.get(H2Repository.java:85)
> 	at org.apache.shardingsphere.mode.repository.standalone.h2.H2Repository.persist(H2Repository.java:129)
> 	at org.apache.shardingsphere.mode.repository.standalone.h2.H2RepositoryTest.assertMethodPersistAndGet(H2RepositoryTest.java:52)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
> 	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
> 	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
> 	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
> 	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
> 	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
> ```
> 
> ![Screenshot from 2022-04-01 15-38-08](https://user-images.githubusercontent.com/60180815/161243159-b5d03b58-e3d2-42b2-bd53-b546802f525e.png)

Hi , I think the assertSetProperty() is call it in every unit test.

**Comment by Devamparikh** [comment]
@zjcnb you are saying that assertSetProperty() should be called in every test cases?
and assertSetProperty() should me method and not Junit test?
