### ISSUE TITLE
About developer friendliness？

### ISSUE THREAD

**Issue by VeejaLiu** [apache/shardingsphere#16540]
I encountered a runtime exception while using：
```
 [ERROR] 2022-04-01 14:31:02.297 [ShardingSphere-Command-3] o.a.s.p.f.c.CommandExecutorTask - Exception occur:
java.lang.NullPointerException: null
	at org.apache.shardingsphere.sharding.rule.ShardingRule.generateKey(ShardingRule.java:474)
	at org.apache.shardingsphere.sharding.route.engine.condition.engine.impl.InsertClauseShardingConditionEngine.lambda$generateKeys$0(InsertClauseShardingConditionEngine.java:133)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.apache.shardingsphere.sharding.route.engine.condition.engine.impl.InsertClauseShardingConditionEngine.generateKeys(InsertClauseShardingConditionEngine.java:133)
	at org.apache.shardingsphere.sharding.route.engine.condition.engine.impl.InsertClauseShardingConditionEngine.appendGeneratedKeyConditions(InsertClauseShardingConditionEngine.java:125)
	at org.apache.shardingsphere.sharding.route.engine.condition.engine.impl.InsertClauseShardingConditionEngine.createShardingConditions(InsertClauseShardingConditionEngine.java:63)
	at org.apache.shardingsphere.sharding.route.engine.condition.engine.impl.InsertClauseShardingConditionEngine.createShardingConditions(InsertClauseShardingConditionEngine.java:52)
	at org.apache.shardingsphere.sharding.route.engine.ShardingSQLRouter.createShardingConditions(ShardingSQLRouter.java:66)
	at org.apache.shardingsphere.sharding.route.engine.ShardingSQLRouter.createRouteContext(ShardingSQLRouter.java:50)
	at org.apache.shardingsphere.sharding.route.engine.ShardingSQLRouter.createRouteContext(ShardingSQLRouter.java:44)
	at org.apache.shardingsphere.infra.route.engine.impl.PartialSQLRouteExecutor.route(PartialSQLRouteExecutor.java:73)
	at org.apache.shardingsphere.infra.route.engine.SQLRouteEngine.route(SQLRouteEngine.java:53)
	at org.apache.shardingsphere.infra.context.kernel.KernelProcessor.route(KernelProcessor.java:54)
	at org.apache.shardingsphere.infra.context.kernel.KernelProcessor.generateExecutionContext(KernelProcessor.java:46)
	at org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:116)
	at org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:67)
	at org.apache.shardingsphere.proxy.backend.text.data.impl.SchemaAssignedDatabaseBackendHandler.execute(SchemaAssignedDatabaseBackendHandler.java:55)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:62)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:96)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:69)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```
# And my config:
## server.yaml
```
rules:
  - !AUTHORITY
    users:
      - root@%:root
      - sharding@%:sharding
    provider:
      type: ALL_PRIVILEGES_PERMITTED

props:
  max-connections-size-per-query: 1
  kernel-executor-size: 16  # Infinite by default.
  proxy-frontend-flush-threshold: 128  # The default value is 128.
  proxy-hint-enabled: false
  sql-show: true
  check-table-metadata-enabled: false
```

## config-sharding.yaml
```
schemaName: sharding_db

dataSources:
  database_team_a:
    url: jdbc:mysql://127.0.0.1:3306/database_team_a?serverTimezone=UTC&useSSL=false
    username: ***
    password: ***
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  database_team_b:
    url: jdbc:mysql://127.0.0.1:3306/database_team_b?serverTimezone=UTC&useSSL=false
    username: ***
    password: ***
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !SHARDING
  tables:
    email_campaign:
      actualDataNodes: database_${["team_a","team_b"]}.email_campaign
      keyGenerateStrategy:
        column: email_campaign_id
        keyGeneratorName: snowflake
  bindingTables:
    - email_campaign
  defaultDatabaseStrategy:
    standard:
      shardingColumn: team_id
      shardingAlgorithmName: database_sharding_method
  defaultTableStrategy:
    none:

  shardingAlgorithms:
    database_sharding_method:
      type: CLASS_BASED
      props:
        strategy: STANDARD
        algorithmClassName: com.standard.TestSharding
```

and I just insert one row into table:
```sql
insert into email_campaign (team_id, user_id, content) values ("a", "a_123", "content by test");
``` 
I checked the error code:
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/22064617/161211555-e987566b-2276-43ce-a70e-ac323f14df04.png">

I guess the probability is that there are some problems with my configuration, but seriously, can you tell me what kind of problems there are instead of throwing a runtime exception to confuse me?

Thank you！

**Comment by VeejaLiu** [comment]
And my sharding strategy:
```java
/**
 * @author liuweijia
 * @email: weijialiu@hiretual.com
 */
public class TestSharding implements PreciseShardingAlgorithm<String> {

    private static final String PREFIX = "database_";

    @Override
    public String doSharding(Collection<String> availableTargetNames, PreciseShardingValue<String> preciseShardingValue) {
        System.out.println("========single sharding========");
        if (preciseShardingValue != null) {
            String value = preciseShardingValue.getValue();
            return PREFIX + "team_" + value;
        }
        return PREFIX + "team_default";
    }
}
```

**Comment by tuichenchuxin** [comment]
@VeejaLiu Try to add this
```
  keyGenerators:
    snowflake:
      type: SNOWFLAKE
```

**Comment by VeejaLiu** [comment]
@tuichenchuxin Thank you! 
I also found this problem and I have solved it now. 
But I mean, in this case, can you give me a more friendly hint?

**Comment by tuichenchuxin** [comment]
@VeejaLiu Sure, we do have a plan.

**Comment by VeejaLiu** [comment]
@tuichenchuxin Thank you!
