### ISSUE TITLE
gsql could not login to proxy if backend database is MogDB (openGauss) since SQL_ASCII charset

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#16705]
### Which version of ShardingSphere did you use?
master branch, commit 0aa073b7921a2c761bc9fa9b6bcb9bfe03bf210f

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy, backend database is MogDB (based on openGauss)
macOS

### Expected behavior
Login successfully with gsql.
Access macOS host proxy from docker.

### Actual behavior
Client got error message:
```
$ gsql --host=host.docker.internal --port=3307 scaling_db root
gsql: ERROR:  SQL_ASCII
```

There's exception in proxy log:
```
[ERROR] 2022-04-09 22:02:47.501 [nioEventLoopGroup-3-1] o.a.s.p.f.n.FrontendChannelInboundHandler - Exception occur: 
java.nio.charset.UnsupportedCharsetException: SQL_ASCII
	at java.nio.charset.Charset.forName(Charset.java:531)
	at org.apache.shardingsphere.proxy.frontend.opengauss.authentication.OpenGaussAuthenticationEngine.processStartupMessage(OpenGaussAuthenticationEngine.java:105)
	at org.apache.shardingsphere.proxy.frontend.opengauss.authentication.OpenGaussAuthenticationEngine.authenticate(OpenGaussAuthenticationEngine.java:98)
	at org.apache.shardingsphere.proxy.frontend.netty.FrontendChannelInboundHandler.authenticate(FrontendChannelInboundHandler.java:83)
	at org.apache.shardingsphere.proxy.frontend.netty.FrontendChannelInboundHandler.channelRead(FrontendChannelInboundHandler.java:75)
```

**Comment by TeslaCN** [comment]
Hi @sandynz 
This issue is cause by `LANG` of your environment. I can reproduce this issue by the following operations. Consider setting your `LANG` to UTF-8 to avoid this issue. We may do some enhancements to support more charset in ShardingSphere-Proxy.

<img width="698" alt="image" src="https://user-images.githubusercontent.com/20503072/162579339-6e6dcd1a-3f18-4b61-a827-1f4aae0fd258.png">

**Comment by sandynz** [comment]
`LANG` is not set by default.
```
omm@b74ff82d07b4:~$ echo $LANG

omm@b74ff82d07b4:~$ locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

After set `export LANG=en_US.UTF-8`, it works.
