### ISSUE TITLE
Shardingsphere-proxy fails to establish a connection when it proxies multiple versions of mysql databases

### ISSUE THREAD

**Issue by lwclover** [apache/shardingsphere#16735]
Shardingsphere proxy version 5.0.0.

Shardingsphere-proxy proxies 2 mysql servers, mysql 5.6 and 5.7.

The mysql driver version used by the application is  8.0.13,Now select version() result is 5.7.34-log-ShardingSphere-Proxy 5.

The application fails to establish a connection, Exception is:
```
java.sql.SQLException: Could not map transaction isolation '1' to a valid JDBC level.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.ConnectionImpl.getTransactionIsolation(ConnectionImpl.java:1229)
	at com.zaxxer.hikari.pool.PoolBase.checkDefaultIsolation(PoolBase.java:479)
	at com.zaxxer.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:442)
	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:410)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:363)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at com.lixiang.proxy.test.ProxyJDBCTest.main(ProxyJDBCTest.java:28)
```

The reason is that mysql needs to query the isolation level of the database after establishing a connection, Mysql5.6 does not support transaction_isolation syntax。

[`transaction_isolation was added in MySQL 5.7.20 as an alias for tx_isolation, which is now deprecated and is removed in MySQL 8.0. Applications should be adjusted to use transaction_isolation in preference to tx_isolation.`](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_tx_isolation)

I think the correct way is to return the corresponding mysql version。

I'm fixing this problem and need a little help。

**Comment by TeslaCN** [comment]
Is there any error logs in ShardingSphere-Proxy?

**Comment by lwclover** [comment]
> 
There is no error in ShardingSphere-Proxy.
