### ISSUE TITLE
cluster mode only support zookeeper ，not pluggable 。because use elastic job , the CoordinatorRegistryCenter implement class，only  ZookeeperRegistryCenter

### ISSUE THREAD

**Issue by xue2lang** [apache/shardingsphere#16972]
## Bug Report

```text
[ERROR] 2022-04-21 14:23:37.884 [main] o.a.s.p.i.BootstrapInitializer - contextManager onInitialized callback for 'RULE_ALTERED_JOB_WORKER' failed
java.lang.IllegalArgumentException: Unsupported clusterType=etcd
	at org.apache.shardingsphere.data.pipeline.core.registry.CoordinatorRegistryCenterInitializer.createRegistryCenter(CoordinatorRegistryCenterInitializer.java:50)
	at org.apache.shardingsphere.data.pipeline.core.api.PipelineAPIFactory$RegistryCenterHolder.createRegistryCenter(PipelineAPIFactory.java:155)
	at org.apache.shardingsphere.data.pipeline.core.api.PipelineAPIFactory$RegistryCenterHolder.getInstance(PipelineAPIFactory.java:145)
	at org.apache.shardingsphere.data.pipeline.core.api.PipelineAPIFactory.getRegistryCenter(PipelineAPIFactory.java:103)
	at org.apache.shardingsphere.data.pipeline.core.execute.FinishedCheckJobExecutor.doStart(FinishedCheckJobExecutor.java:40)
	at org.apache.shardingsphere.data.pipeline.api.executor.AbstractLifecycleExecutor.start(AbstractLifecycleExecutor.java:41)
	at org.apache.shardingsphere.data.pipeline.scenario.rulealtered.RuleAlteredJobWorker.initWorkerIfNecessary(RuleAlteredJobWorker.java:118)
	at org.apache.shardingsphere.data.pipeline.scenario.rulealtered.spi.ContextManagerLifecycleListenerImpl.onInitialized(ContextManagerLifecycleListenerImpl.java:46)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.contextManagerInitializedCallback(BootstrapInitializer.java:80)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.init(BootstrapInitializer.java:59)
	at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:47)
```

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
normal start
### Actual behavior
occur Exception ，and output log 
### Reason analyze (If you can)
```java
 // CoordinatorRegistryCenterInitializer 
    /**
     * Create registry center instance.
     *
     * @param modeConfig mode configuration
     * @param namespaceRelativePath namespace relative path
     * @return registry center instance
     */
    public CoordinatorRegistryCenter createRegistryCenter(final ModeConfiguration modeConfig, final String namespaceRelativePath) {
        ClusterPersistRepositoryConfiguration repositoryConfig = (ClusterPersistRepositoryConfiguration) modeConfig.getRepository();
        String clusterType = modeConfig.getRepository().getType();
        //now clusterType only support zookeeper ，so we want use other clusterType，we should implement this interface class CoordinatorRegistryCenter
        if ("ZooKeeper".equalsIgnoreCase(clusterType)) {
            CoordinatorRegistryCenter result = new ZookeeperRegistryCenter(getZookeeperConfig(repositoryConfig, namespaceRelativePath));
            result.init();
            return result;
        }
        throw new IllegalArgumentException("Unsupported clusterType=" + clusterType);
    }

```
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
only modify cluster type

**Comment by zjcnb** [comment]
@xue2lang Hi, It only has exception message, But ShardingSphere-Proxy can work.

**Comment by xue2lang** [comment]
> @xue2lang Hi, it only has exception message, But ShardingSphere-Proxy can work.

i see it can work, but it lost framework extensibility @zjcnb

**Comment by sandynz** [comment]
Hi @xue2lang , thanks for your feedback. ElasticJob will support more registry center later, just as ShardingSphere.

**Comment by xue2lang** [comment]
ok , thanks for your reply,  i close this issue @sandynz

**Comment by removeif** [comment]
hi, Which version of ElasticJob is expected to be supported Nacos?

**Comment by sandynz** [comment]
Hi @removeif , there's no exact version planned for now. There's some research of how to share registry center implementations between ShardingSphere and ElasticJob.
