### ISSUE TITLE
DataSourceProvidedDatabaseConfiguration cast to DataSourceGeneratedDatabaseConfiguration

### ISSUE THREAD

**Issue by By1995** [apache/shardingsphere#17009]
this is a obvious error, why
in method createMetaDataContextsBuilder :
result.addDatabase(each, databaseType, createDatabaseConfiguration(each, metaDataPersistService, parameter), props);
in method  createDatabaseConfiguration:
return new DataSourceProvidedDatabaseConfiguration(dataSources, databaseRuleConfigs);
in method buildRules:
DataSourceGeneratedDatabaseConfiguration configuration = (DataSourceGeneratedDatabaseConfiguration) databaseConfig;

Exception in thread "main" java.lang.ClassCastException: org.apache.shardingsphere.infra.config.database.impl.DataSourceProvidedDatabaseConfiguration cannot be cast to org.apache.shardingsphere.infra.config.database.impl.DataSourceGeneratedDatabaseConfiguration
	at org.apache.shardingsphere.infra.rule.builder.schema.SchemaRulesBuilder.buildRules(SchemaRulesBuilder.java:70)
	at org.apache.shardingsphere.mode.metadata.MetaDataContextsBuilder.getDatabaseRules(MetaDataContextsBuilder.java:105)
	at org.apache.shardingsphere.mode.metadata.MetaDataContextsBuilder.addDatabase(MetaDataContextsBuilder.java:83)
	at org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.createMetaDataContextsBuilder(ClusterContextManagerBuilder.java:137)
	at org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.build(ClusterContextManagerBuilder.java:76)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.createContextManager(BootstrapInitializer.java:75)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.init(BootstrapInitializer.java:60)
	at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:47)

**Comment by strongduanmu** [comment]
@By1995 Can you submit issue according to bug template?

**Comment by terrymanu** [comment]
No response for this issue, I just close it.
