### ISSUE TITLE
java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by fanfantian** [apache/shardingsphere#17086]
## Bug Report

version 5.1.1

[ERROR] 2022-04-25 12:54:44.351 [ShardingSphere-Scaling-execute-4] o.a.s.d.p.core.task.IncrementalTask - importer onFailure, taskId=ds_0
java.lang.NullPointerException: null
        at org.apache.shardingsphere.data.pipeline.core.record.RecordUtil.extractConditionColumns(RecordUtil.java:61)
        at org.apache.shardingsphere.data.pipeline.core.importer.AbstractImporter.executeUpdate(AbstractImporter.java:183)
        at org.apache.shardingsphere.data.pipeline.core.importer.AbstractImporter.executeUpdate(AbstractImporter.java:178)
        at org.apache.shardingsphere.data.pipeline.core.importer.AbstractImporter.doFlush(AbstractImporter.java:150)
        at org.apache.shardingsphere.data.pipeline.core.importer.AbstractImporter.tryFlush(AbstractImporter.java:132)
        at org.apache.shardingsphere.data.pipeline.core.importer.AbstractImporter.flushInternal(AbstractImporter.java:123)
        at org.apache.shardingsphere.data.pipeline.core.importer.AbstractImporter.lambda$flush$2(AbstractImporter.java:115)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.apache.shardingsphere.data.pipeline.core.importer.AbstractImporter.flush(AbstractImporter.java:112)
        at org.apache.shardingsphere.data.pipeline.core.importer.AbstractImporter.write(AbstractImporter.java:93)
        at org.apache.shardingsphere.data.pipeline.core.importer.AbstractImporter.doStart(AbstractImporter.java:79)
        at org.apache.shardingsphere.data.pipeline.api.executor.AbstractLifecycleExecutor.start(AbstractLifecycleExecutor.java:41)
        at org.apache.shardingsphere.data.pipeline.api.executor.AbstractLifecycleExecutor.run(AbstractLifecycleExecutor.java:61)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
[INFO ] 2022-04-25 12:54:44.352 [ShardingSphere-Scaling-execute-4] o.a.s.d.p.a.e.AbstractLifecycleExecutor - stop lifecycle executor: org.apache.shardingsphere.data.pipeline.core.task.IncrementalTask@4c3b4338
[INFO ] 2022-04-25 12:54:44.352 [ShardingSphere-Scaling-execute-4] o.a.s.d.p.a.e.AbstractLifecycleExecutor - stop lifecycle executor: org.apache.shardingsphere.data.pipeline.mysql.ingest.MySQLIncrementalDumper@607ce7d9
[INFO ] 2022-04-25 12:54:44.352 [ShardingSphere-Scaling-execute-4] o.a.s.d.p.a.e.AbstractLifecycleExecutor - stop lifecycle executor: org.apache.shardingsphere.data.pipeline.mysql.importer.MySQLImporter@23ef029d
[INFO ] 2022-04-25 12:54:44.352 [ShardingSphere-Scaling-execute-4] o.a.s.d.p.a.e.AbstractLifecycleExecutor - stop lifecycle executor: org.apache.shardingsphere.data.pipeline.mysql.importer.MySQLImporter@507fcfef
[INFO ] 2022-04-25 12:54:44.352 [ShardingSphere-Scaling-execute-4] o.a.s.d.p.a.e.AbstractLifecycleExecutor - stop lifecycle executor: org.apache.shardingsphere.data.pipeline.mysql.importer.MySQLImporter@1efb9a7
[INFO ] 2022-04-25 12:54:44.363 [ShardingSphere-Scaling-execute-3] o.a.s.d.p.c.i.AbstractImporter - importer write done, rowCount=5, finishedByBreak=false
[INFO ] 2022-04-25 12:54:44.411 [ShardingSphere-Scaling-execute-0] o.a.s.d.p.m.i.MySQLIncrementalDumper - incremental dump, eventCount=30118
[ERROR] 2022-04-25 12:54:44.411 [ShardingSphere-Scaling-execute-3] o.a.s.d.p.s.r.RuleAlteredJobScheduler - Incremental task execute failed.
org.apache.shardingsphere.data.pipeline.core.exception.PipelineJobExecutionException: Task ds_0 execute failed
        at org.apache.shardingsphere.data.pipeline.core.task.IncrementalTask.waitForResult(IncrementalTask.java:129)
        at org.apache.shardingsphere.data.pipeline.core.task.IncrementalTask.doStart(IncrementalTask.java:86)
        at org.apache.shardingsphere.data.pipeline.api.executor.AbstractLifecycleExecutor.start(AbstractLifecycleExecutor.java:41)
        at org.apache.shardingsphere.data.pipeline.api.executor.AbstractLifecycleExecutor.run(AbstractLifecycleExecutor.java:61)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException: null
        at org.apache.shardingsphere.data.pipeline.core.record.RecordUtil.extractConditionColumns(RecordUtil.java:61)
        at org.apache.shardingsphere.data.pipeline.core.importer.AbstractImporter.executeUpdate(AbstractImporter.java:183)
        at org.apache.shardingsphere.data.pipeline.core.importer.AbstractImporter.executeUpdate(AbstractImporter.java:178)
        at org.apache.shardingsphere.data.pipeline.core.importer.AbstractImporter.doFlush(AbstractImporter.java:150)
        at org.apache.shardingsphere.data.pipeline.core.importer.AbstractImporter.tryFlush(AbstractImporter.java:132)
        at org.apache.shardingsphere.data.pipeline.core.importer.AbstractImporter.flushInternal(AbstractImporter.java:123)
        at org.apache.shardingsphere.data.pipeline.core.importer.AbstractImporter.lambda$flush$2(AbstractImporter.java:115)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.apache.shardingsphere.data.pipeline.core.importer.AbstractImporter.flush(AbstractImporter.java:112)

### how to repeat
添加mysql单实例源
ALTER RESOURCE ds_0 (
    URL="jdbc:mysql://10.0.0.1:3306/testdb?serverTimezone=UTC&useSSL=false",
    USER=cctest,
    PASSWORD=cctest,
    PROPERTIES("maximumPoolSize"=50,"idleTimeout"="60000")
);

把现有系统中的表配置到规则里，使用 tables 规则 INLINE 算法

CREATE SHARDING ALGORITHM account_database_inline (
TYPE(NAME=INLINE,PROPERTIES("algorithm-expression"="ds_0"))
);
CREATE SHARDING ALGORITHM user_database_inline (
TYPE(NAME=INLINE,PROPERTIES("algorithm-expression"="ds_0"))
);
700张拼接的月表
CREATE SHARDING TABLE RULE testtable_201101 (DATANODES("ds_0.testtable_201901"),
DATABASE_STRATEGY(TYPE=standard,SHARDING_COLUMN=aid,SHARDING_ALGORITHM=account_database_inline),KEY_GENERATE_STRATEGY(COLUMN=aid,TYPE(NAME=snowflake))
)...........................,testtable_210001 (DATANODES("ds_0.testtable_210001"),
DATABASE_STRATEGY(TYPE=standard,SHARDING_COLUMN=aid,SHARDING_ALGORITHM=account_database_inline),KEY_GENERATE_STRATEGY(COLUMN=ACCOUNTID,TYPE(NAME=snowflake))
)

CREATE SHARDING SCALING RULE scaling_manual2 (
DATA_CONSISTENCY_CHECKER(TYPE(NAME=CRC32_MATCH))
);

加入目标端数据库资源
ADD RESOURCE ds_1 (
    URL="jdbc:mysql://10.0.0.1:3306/testdb_0?serverTimezone=UTC&useSSL=false",
    USER=testuser,
    PASSWORD=testuser,
    PROPERTIES("maximumPoolSize"=50,"idleTimeout"="60000")
),ds_2 (
    URL="jdbc:mysql://10.0.0.2:3306/testdb_1?serverTimezone=UTC&useSSL=false",
    USER=testuser,
    PASSWORD=testuser,
    PROPERTIES("maximumPoolSize"=50,"idleTimeout"="60000")
);

ALTER SHARDING ALGORITHM account_database_inline (
TYPE(NAME=INLINE,PROPERTIES("algorithm-expression"="ds_${aid% 2 + 1}"))
);

700张拼接的月表迁移
CREATE SHARDING TABLE RULE testtable_201101 (DATANODES("ds_${1..2}.testtable_201901"),
DATABASE_STRATEGY(TYPE=standard,SHARDING_COLUMN=aid,SHARDING_ALGORITHM=account_database_inline),KEY_GENERATE_STRATEGY(COLUMN=aid,TYPE(NAME=snowflake))
)...........................,testtable_210001 (DATANODES("ds_${1..2}.testtable_210001"),
DATABASE_STRATEGY(TYPE=standard,SHARDING_COLUMN=aid,SHARDING_ALGORITHM=account_database_inline),KEY_GENERATE_STRATEGY(COLUMN=ACCOUNTID,TYPE(NAME=snowflake))
)

**Comment by sandynz** [comment]
Hi @fanfantian , thanks for you feedback.

I had a look at related code of stack trace:
```
java.lang.NullPointerException: null
at org.apache.shardingsphere.data.pipeline.core.record.RecordUtil.extractConditionColumns(RecordUtil.java:61)
at org.apache.shardingsphere.data.pipeline.core.importer.AbstractImporter.executeUpdate(AbstractImporter.java:183)
```

From `RecordUtil.extractConditionColumns`:
```
    public static List<Column> extractConditionColumns(final DataRecord dataRecord, final Set<String> shardingColumns) {
        List<Column> result = new ArrayList<>(dataRecord.getColumns().size());
        for (Column each : dataRecord.getColumns()) {
            if (each.isPrimaryKey() || shardingColumns.contains(each.getName())) { // Line 61
                result.add(each);
            }
        }
        return result;
    }
```
The NPE should be from `shardingColumns`.

From `AbstractImporter.executeUpdate`:
```
    private void executeUpdate(final Connection connection, final DataRecord record) throws SQLException {
        List<Column> conditionColumns = RecordUtil.extractConditionColumns(record, importerConfig.getShardingColumnsMap().get(record.getTableName())); // Line 183
```
It means `importerConfig.getShardingColumnsMap().get(record.getTableName())` return null.

Could you help to do some debug to show `importerConfig.getShardingColumnsMap().get(record.getTableName())` value, `importerConfig.getShardingColumnsMap()` value and `record.getTableName()` value? Since I could not reproduce this issue on local.

**Comment by sandynz** [comment]
I reproduced this issue.
Use uppercase table name in sharding rule, and use lowercase table name in underlying sharded actual tables. e.g. T_ORDER in sharding rule, t_order_0 in sharded table.
