### ISSUE TITLE
Use scaling feature with mysql 8.x are EXECUTE_INCREMENTAL_TASK_FAILURE

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#17092]
### Which version of ShardingSphere did you use?

master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

`ShardingSphere-Proxy`

### Expected behavior

```
+------+-------------+----------+--------+-------------------------------+--------------------------+
| item | data_source | status   | active | inventory_finished_percentage | incremental_idle_seconds |
+------+-------------+----------+--------+-------------------------------+--------------------------+
| 0    | ds_0        | FINISHED | false  | 100                           | 81                       |
| 1    | ds_1        | FINISHED | false  | 100                           | 81                       |
+------+-------------+----------+--------+-------------------------------+--------------------------+
```

### Actual behavior

```
+------+-------------+----------------------------------+--------+-------------------------------+--------------------------+
| item | data_source | status                           | active | inventory_finished_percentage | incremental_idle_seconds |
+------+-------------+----------------------------------+--------+-------------------------------+--------------------------+
| 0    | ds_0        | EXECUTE_INCREMENTAL_TASK_FAILURE | true   | 100                           | 9                        |
| 1    | ds_1        | EXECUTE_INCREMENTAL_TASK_FAILURE | true   | 100                           | 5                        |
+------+-------------+----------------------------------+--------+-------------------------------+--------------------------+
```

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

```
mysql> create database test1;
Query OK, 0 rows affected (0.85 sec)

mysql> use test1;
Database changed
mysql> ADD RESOURCE ds_0 (
    ->     URL="jdbc:mysql://127.0.0.1:3306/scaling_ds_0?serverTimezone=UTC&useSSL=false",
    ->     USER=root,
    ->     PASSWORD=123456,
    ->     PROPERTIES("maximumPoolSize"=50,"idleTimeout"="60000")
    -> ), ds_1 (
    ->     URL="jdbc:mysql://127.0.0.1:3306/scaling_ds_1?serverTimezone=UTC&useSSL=false",
    ->     USER=root,
    ->     PASSWORD=123456,
    ->     PROPERTIES("maximumPoolSize"=50,"idleTimeout"="60000")
    -> );
Query OK, 0 rows affected (0.93 sec)

mysql> CREATE SHARDING TABLE RULE t_order(
    -> RESOURCES(ds_0,ds_1),
    -> SHARDING_COLUMN=order_id,
    -> TYPE(NAME=hash_mod,PROPERTIES("sharding-count"=4)),
    -> KEY_GENERATE_STRATEGY(COLUMN=order_id,TYPE(NAME=snowflake))
    -> ), t_order_item(
    -> RESOURCES(ds_0,ds_1),
    -> SHARDING_COLUMN=order_id,
    -> TYPE(NAME=hash_mod,PROPERTIES("sharding-count"=4)),
    -> KEY_GENERATE_STRATEGY(COLUMN=order_id,TYPE(NAME=snowflake))
    -> );
Query OK, 0 rows affected (2.03 sec)

mysql> CREATE TABLE t_order (order_id INT NOT NULL, user_id INT NOT NULL, status VARCHAR(45) NULL, PRIMARY KEY (order_id));
Query OK, 0 rows affected (0.30 sec)

mysql>
mysql> CREATE TABLE t_order_item (item_id INT NOT NULL, order_id INT NOT NULL, user_id INT NOT NULL, status VARCHAR(45) NULL, creation_date DATE, PRIMARY KEY (item_id));
Query OK, 0 rows affected (0.04 sec)

mysql> insert into t_order (order_id, user_id, status) values (1,2,'ok'),(2,4,'ok'),(3,6,'ok'),(4,1,'ok'),(5,3,'ok'),(6,5,'ok');
Query OK, 6 rows affected (0.07 sec)

mysql>
mysql> insert into t_order_item (item_id, order_id, user_id, status) values (1,1,2,'ok'),(2,2,4,'ok'),(3,3,6,'ok'),(4,4,1,'ok'),(5,5,3,'ok'),(6,6,5,'ok');
Query OK, 6 rows affected (0.00 sec)

mysql> preview select count(1) from t_order;
+------------------+-------------------------------------------------------------------------+
| data_source_name | actual_sql                                                              |
+------------------+-------------------------------------------------------------------------+
| ds_0             | select count(1) from t_order_0 UNION ALL select count(1) from t_order_2 |
| ds_1             | select count(1) from t_order_1 UNION ALL select count(1) from t_order_3 |
+------------------+-------------------------------------------------------------------------+
2 rows in set (0.10 sec)

mysql>
mysql> preview select count(1) from t_order_item;
+------------------+-----------------------------------------------------------------------------------+
| data_source_name | actual_sql                                                                        |
+------------------+-----------------------------------------------------------------------------------+
| ds_0             | select count(1) from t_order_item_0 UNION ALL select count(1) from t_order_item_2 |
| ds_1             | select count(1) from t_order_item_1 UNION ALL select count(1) from t_order_item_3 |
+------------------+-----------------------------------------------------------------------------------+
2 rows in set (0.01 sec)

mysql> ADD RESOURCE ds_2 (
    ->     URL="jdbc:mysql://127.0.0.1:3306/scaling_ds_10?serverTimezone=UTC&useSSL=false",
    ->     USER=root,
    ->     PASSWORD=123456,
    ->     PROPERTIES("maximumPoolSize"=50,"idleTimeout"="60000")
    -> ), ds_3 (
    ->     URL="jdbc:mysql://127.0.0.1:3306/scaling_ds_11?serverTimezone=UTC&useSSL=false",
    ->     USER=root,
    ->     PASSWORD=123456,
    ->     PROPERTIES("maximumPoolSize"=50,"idleTimeout"="60000")
    -> ), ds_4 (
    ->     URL="jdbc:mysql://127.0.0.1:3306/scaling_ds_12?serverTimezone=UTC&useSSL=false",
    ->     USER=root,
    ->     PASSWORD=123456,
    ->     PROPERTIES("maximumPoolSize"=50,"idleTimeout"="60000")
    -> );
Query OK, 0 rows affected (0.10 sec)

mysql>
mysql> CREATE SHARDING SCALING RULE scaling_auto2 (
    -> COMPLETION_DETECTOR(TYPE(NAME=IDLE, PROPERTIES("incremental-task-idle-minute-threshold"=1))),
    -> DATA_CONSISTENCY_CHECKER(TYPE(NAME=CRC32_MATCH))
    -> );
Query OK, 0 rows affected (0.07 sec)

mysql>
mysql> ALTER SHARDING TABLE RULE t_order(
    -> RESOURCES(ds_2,ds_3,ds_4),
    -> SHARDING_COLUMN=order_id,
    -> TYPE(NAME=hash_mod,PROPERTIES("sharding-count"=6)),
    -> KEY_GENERATE_STRATEGY(COLUMN=order_id,TYPE(NAME=snowflake))
    -> ), t_order_item(
    -> RESOURCES(ds_2,ds_3,ds_4),
    -> SHARDING_COLUMN=order_id,
    -> TYPE(NAME=hash_mod,PROPERTIES("sharding-count"=6)),
    -> KEY_GENERATE_STRATEGY(COLUMN=order_id,TYPE(NAME=snowflake))
    -> );
Query OK, 0 rows affected (0.14 sec)

mysql> show scaling list;
+----------------------------------+----------------------+----------------------+--------+---------------------+-----------+
| id                               | tables               | sharding_total_count | active | create_time         | stop_time |
+----------------------------------+----------------------+----------------------+--------+---------------------+-----------+
| 0130317c30317c3054317c7465737431 | t_order,t_order_item | 2                    | true   | 2022-04-25 19:19:25 | NULL      |
+----------------------------------+----------------------+----------------------+--------+---------------------+-----------+
1 row in set (0.07 sec)

mysql> show scaling status 0130317c30317c3054317c7465737431
    -> ;
+------+-------------+----------------------------------+--------+-------------------------------+--------------------------+
| item | data_source | status                           | active | inventory_finished_percentage | incremental_idle_seconds |
+------+-------------+----------------------------------+--------+-------------------------------+--------------------------+
| 0    | ds_0        | EXECUTE_INCREMENTAL_TASK_FAILURE | true   | 100                           | 9                        |
| 1    | ds_1        | EXECUTE_INCREMENTAL_TASK_FAILURE | true   | 100                           | 5                        |
+------+-------------+----------------------------------+--------+-------------------------------+--------------------------+
2 rows in set (0.01 sec)
```

### Exception

```
[INFO ] 2022-04-25 19:19:33.531 [ShardingSphere-Scaling-execute-3] o.a.s.d.p.a.e.AbstractLifecycleExecutor - start lifecycle executor: org.apache.shardingsphere.data.pipeline.mysql.importer.MySQLImporter@4a903585
[INFO ] 2022-04-25 19:19:33.531 [ShardingSphere-Scaling-execute-3] o.a.s.d.p.c.i.AbstractImporter - importer write
[ERROR] 2022-04-25 19:19:33.534 [nioEventLoopGroup-5-1] o.a.s.d.p.m.i.client.MySQLClient - protocol resolution error
java.lang.RuntimeException: Bad handshake
	at org.apache.shardingsphere.data.pipeline.mysql.ingest.client.netty.MySQLNegotiateHandler.channelRead(MySQLNegotiateHandler.java:100)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:305)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] 2022-04-25 19:19:33.534 [ShardingSphere-Scaling-execute-4] o.a.s.d.p.s.r.RuleAlteredJobScheduler - Incremental task execute failed.
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Bad handshake
	at org.apache.shardingsphere.data.pipeline.mysql.ingest.client.MySQLClient.waitExpectedResponse(MySQLClient.java:216)
	at org.apache.shardingsphere.data.pipeline.mysql.ingest.client.MySQLClient.connect(MySQLClient.java:94)
	at org.apache.shardingsphere.data.pipeline.mysql.ingest.MySQLIncrementalDumper.dump(MySQLIncrementalDumper.java:94)
	at org.apache.shardingsphere.data.pipeline.mysql.ingest.MySQLIncrementalDumper.doStart(MySQLIncrementalDumper.java:86)
	at org.apache.shardingsphere.data.pipeline.api.executor.AbstractLifecycleExecutor.start(AbstractLifecycleExecutor.java:41)
	at org.apache.shardingsphere.data.pipeline.core.task.IncrementalTask.doStart(IncrementalTask.java:85)
	at org.apache.shardingsphere.data.pipeline.api.executor.AbstractLifecycleExecutor.start(AbstractLifecycleExecutor.java:41)
	at org.apache.shardingsphere.data.pipeline.api.executor.AbstractLifecycleExecutor.run(AbstractLifecycleExecutor.java:61)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Bad handshake
	at io.netty.util.concurrent.DefaultPromise.get(DefaultPromise.java:350)
	at org.apache.shardingsphere.data.pipeline.mysql.ingest.client.MySQLClient.waitExpectedResponse(MySQLClient.java:204)
	... 14 common frames omitted
Caused by: java.lang.RuntimeException: Bad handshake
	at org.apache.shardingsphere.data.pipeline.mysql.ingest.client.netty.MySQLNegotiateHandler.channelRead(MySQLNegotiateHandler.java:100)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:305)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 common frames omitted
[INFO ] 2022-04-25 19:19:33.535 [ShardingSphere-Scaling-execute-4] o.a.s.d.p.s.r.RuleAlteredJobScheduler - stop job 0130317c30317c3054317c7465737431
```

### MySQL Configuration
<img width="757" alt="image" src="https://user-images.githubusercontent.com/33742097/165080079-680a71cd-b845-4586-aed0-2c851854957a.png">
<img width="853" alt="image" src="https://user-images.githubusercontent.com/33742097/165080143-12b2285a-5ff3-448b-866f-48b97e45f31c.png">
<img width="939" alt="image" src="https://user-images.githubusercontent.com/33742097/165080269-d0ae2f1e-5773-4239-91ca-d8d2dc6a8145.png">

**Comment by azexcy** [comment]
OK, I will track this issue

**Comment by azexcy** [comment]
OK, I will track this issue

**Comment by zjcnb** [comment]
> @zjcnb I can't reproduce the problem, can you provider the config of mysql, like `my.cnf` file

```
zhaojinchao@zhaojinchao的MacBook etc % cat my.cnf
# Default Homebrew MySQL server config
[mysqld]
# Only allow connections from localhost
bind-address = 127.0.0.1
mysqlx-bind-address = 127.0.0.1
server-id=1
log-bin=mysql-bin
binlog-format=row
binlog-row-image=full
max_connections=1200
```

**Comment by azexcy** [comment]
I tested it(both test at docker and native), use the same configuration, but the problem can't reproduce

**Comment by azexcy** [comment]
https://github.com/apache/shardingsphere/actions/runs/2284252654
The scaling IT test will execute once  a day, it does not appear to have this problem, did you do any special operations?

**Comment by zjcnb** [comment]
> https://github.com/apache/shardingsphere/actions/runs/2284252654 The scaling IT test will execute once a day, it does not appear to have this problem, did you do any special operations?

No, i not have special operations. I use `brew install mysql` in my macbook.

**Comment by TeslaCN** [comment]
Hi @azexcy @zjcnb 
Could we finish this in 5.1.2?

**Comment by strongduanmu** [comment]
Hi @zjcnb @sandynz, can we finish this issue in 5.1.3?

**Comment by azexcy** [comment]
I reproduce the problem.  bacause the account password plugin is not equals with  `default_authentication_plugin`
please check the result of `show variables like 'default_authentication_plugin';` or change account password plugin.
> ps. the account at this issue is root

**Comment by zjcnb** [comment]
> I reproduce the problem. bacause the account password plugin is not equals with `default_authentication_plugin` please check the result of `show variables like 'default_authentication_plugin';` or change account password plugin.
> 
> > ps. the account at this issue is root

Thank you for your reply, i will try.
