### ISSUE TITLE
Proxy cluster start up failed when pull PG configuration from reigster center.

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#17170]
### Which version of ShardingSphere did you use?

`master`

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

`ShardingSphere-Proxy`

### Expected behavior

Proxy cluster can be start up

### Actual behavior

```
[ERROR] 2022-04-28 14:14:45.934 [main] o.a.s.i.m.s.l.SchemaMetaDataLoaderEngine - Dialect load table meta data error
org.postgresql.util.PSQLException: ERROR: column "column_key" does not exist
  位置：44
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.apache.shardingsphere.infra.metadata.schema.loader.dialect.MySQLSchemaMetaDataLoader.loadColumnMetaDataMap(MySQLSchemaMetaDataLoader.java:110)
	at org.apache.shardingsphere.infra.metadata.schema.loader.dialect.MySQLSchemaMetaDataLoader.load(MySQLSchemaMetaDataLoader.java:66)
	at org.apache.shardingsphere.infra.metadata.schema.loader.SchemaMetaDataLoaderEngine.lambda$loadByDialect$1(SchemaMetaDataLoaderEngine.java:90)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: syntax error at or near "`"
  位置：15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:329)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:315)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:291)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:243)
	at com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:111)
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java)
	at org.apache.shardingsphere.infra.metadata.schema.loader.common.ColumnMetaDataLoader.load(ColumnMetaDataLoader.java:75)
	at org.apache.shardingsphere.infra.metadata.schema.loader.common.TableMetaDataLoader.load(TableMetaDataLoader.java:52)
	at org.apache.shardingsphere.infra.metadata.schema.loader.SchemaMetaDataLoaderEngine.loadByDefault(SchemaMetaDataLoaderEngine.java:80)
	at org.apache.shardingsphere.infra.metadata.schema.loader.SchemaMetaDataLoaderEngine.load(SchemaMetaDataLoaderEngine.java:68)
	at org.apache.shardingsphere.singletable.metadata.SingleTableSchemaMetaDataBuilder.load(SingleTableSchemaMetaDataBuilder.java:57)
	at org.apache.shardingsphere.singletable.metadata.SingleTableSchemaMetaDataBuilder.load(SingleTableSchemaMetaDataBuilder.java:44)
	at org.apache.shardingsphere.infra.metadata.schema.builder.TableMetaDataBuilder.load(TableMetaDataBuilder.java:59)
	at org.apache.shardingsphere.infra.metadata.schema.loader.SchemaLoader.load(SchemaLoader.java:57)
	at org.apache.shardingsphere.infra.metadata.database.loader.DatabaseLoader.load(DatabaseLoader.java:53)
	at org.apache.shardingsphere.mode.metadata.MetaDataContextsBuilder.addDatabase(MetaDataContextsBuilder.java:84)
	at org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.createMetaDataContextsBuilder(ClusterContextManagerBuilder.java:138)
	at org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.build(ClusterContextManagerBuilder.java:75)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.createContextManager(BootstrapInitializer.java:75)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.init(BootstrapInitializer.java:60)
	at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:47)
```

**Comment by zjcnb** [comment]
The bug are fixed.
