### ISSUE TITLE
 In the case of sub-tables, if the sql contains on duplicate key update, it will cause an error in the actually generated sql

### ISSUE THREAD

**Issue by carlyin0801** [apache/shardingsphere#17198]
**Bug Report**
Which version of ShardingSphere did you use?
5.0.0

Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

Expected behavior
[insert into t_pipeline_info (PIPELINE_ID, PROJECT_ID, PIPELINE_NAME, PIPELINE_DESC) values (?, ?, ?, ?) on duplicate key update t_pipeline_info.PIPELINE_DESC = ?]
can be converted into
[insert into t_pipeline_info_0 (PIPELINE_ID, PROJECT_ID, PIPELINE_NAME, PIPELINE_DESC) values (?, ?, ?, ?) on duplicate key update t_pipeline_info_0.PIPELINE_DESC = ?]

Actual behavior
converted to [insert into **t_pipeline_info_0** (PIPELINE_ID, PROJECT_ID, PIPELINE_NAME, PIPELINE_DESC) values (?, ?, ?, ?) on duplicate key update **t_pipeline_info**.PIPELINE_DESC = ?]

**The error message is as follows:**
2022-04-29 11:45:55.634|biz-6f32770874f04555a58353f335304281||SQLLogger.java|74|INFO||||||[XNIO-1 task-1] Logic SQL: insert into t_pipeline_info (PIPELINE_ID, PROJECT_ID, PIPELINE_NAME, PIPELINE_DESC) values (?, ?, ?, ?) on duplicate key update t_pipeline_info.PIPELINE_DESC = ?
2022-04-29 11:45:55.634|biz-6f32770874f04555a58353f335304281||SQLLogger.java|74|INFO||||||[XNIO-1 task-1] SQLStatement: MySQLInsertStatement(setAssignment=Optional.empty, onDuplicateKeyColumns=Optional[org.apache.shardingsphere.sql.parser.sql.common.segment.dml.column.OnDuplicateKeyColumnsSegment@4e2038b4])
2022-04-29 11:45:55.634|biz-6f32770874f04555a58353f335304281||SQLLogger.java|74|INFO||||||[XNIO-1 task-1] Actual SQL: ds_0 ::: insert into t_pipeline_info_0 (PIPELINE_ID, PROJECT_ID, PIPELINE_NAME, PIPELINE_DESC) values (?, ?, ?, ?) on duplicate key update t_pipeline_info.PIPELINE_DESC = ? ::: [p-17bd8ac017dsfsd1f, devops0, bnmvvv123dsfdf, 232323yui, 232323yui]
2022-04-29 11:45:55.669|biz-6f32770874f04555a58353f335304281||RuntimeExceptionMapper.kt|47|ERROR||||||[XNIO-1 task-1] Failed with runtime exception org.jooq.exception.DataAccessException: SQL [insert into t_pipeline_info (PIPELINE_ID, PROJECT_ID, PIPELINE_NAME, PIPELINE_DESC) values (?, ?, ?, ?) on duplicate key update t_pipeline_info.PIPELINE_DESC = ?]; Unknown column 't_pipeline_info.PIPELINE_DESC' in 'field list'
at org.jooq_3.14.7.MYSQL.debug(Unknown Source)
at org.jooq.impl.Tools.translate(Tools.java:2880)

**Comment by carlyin0801** [comment]
@strongduanmu hi, can you please take a look

**Comment by strongduanmu** [comment]
@carlyin0801 Please submit issue with bug template.

**Comment by carlyin0801** [comment]
The issue template has been updated, please take a look

**Comment by strongduanmu** [comment]
> @strongduanmu The issue template has been updated, please take a look

Please add your sharding configuration, and table init sql.

**Comment by carlyin0801** [comment]
configuration:
"ds_\${0..1}.t_pipeline_info_\${0..1}"

table init sql:
CREATE TABLE `t_pipeline_info_0` (
  `PIPELINE_ID` varchar(34) NOT NULL DEFAULT '' COMMENT '流水线ID （P-32位UUID)=34位',
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `PIPELINE_NAME` varchar(255) NOT NULL COMMENT '名称',
  `PIPELINE_DESC` varchar(255) DEFAULT NULL COMMENT '描述',
  PRIMARY KEY (`PIPELINE_ID`),
  UNIQUE KEY `T_PIPELINE_INFO_NAME_uindex` (`PROJECT_ID`,`PIPELINE_NAME`),
  KEY `PROJECT_ID` (`PROJECT_ID`,`PIPELINE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='流水线定义表';

CREATE TABLE `t_pipeline_info_1` (
  `PIPELINE_ID` varchar(34) NOT NULL DEFAULT '' COMMENT '流水线ID （P-32位UUID)=34位',
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `PIPELINE_NAME` varchar(255) NOT NULL COMMENT '名称',
  `PIPELINE_DESC` varchar(255) DEFAULT NULL COMMENT '描述',
  PRIMARY KEY (`PIPELINE_ID`),
  UNIQUE KEY `T_PIPELINE_INFO_NAME_uindex` (`PROJECT_ID`,`PIPELINE_NAME`),
  KEY `PROJECT_ID` (`PROJECT_ID`,`PIPELINE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='流水线定义表';

**Comment by cheese8** [comment]
Assign it to me? thanks @strongduanmu

**Comment by strongduanmu** [comment]
@cheese8 Welcome, I just assign this issue to you.
