### ISSUE TITLE
DistSQL RAL SHOW TABLE METADATA TABLE NAME risk of NPE

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#17365]
### Which version of ShardingSphere did you use?

`master`

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

`ShardingSphere-Proxy`

### Expected behavior

Not throw NPE.

### Actual behavior

```
readwrite_splitting_db=> SHOW TABLE METADATA t_order;
ERROR:  java.lang.NullPointerException
readwrite_splitting_db=>
```

The `t_order` table does not actually exist.

```

java.lang.NullPointerException: null
	at org.apache.shardingsphere.proxy.backend.text.distsql.ral.common.queryable.ShowTableMetadataHandler.getRows(ShowTableMetadataHandler.java:69)
	at org.apache.shardingsphere.proxy.backend.text.distsql.ral.QueryableRALBackendHandler.handle(QueryableRALBackendHandler.java:49)
	at org.apache.shardingsphere.proxy.backend.text.distsql.ral.RALBackendHandler.execute(RALBackendHandler.java:49)
	at org.apache.shardingsphere.proxy.frontend.postgresql.command.query.simple.PostgreSQLComQueryExecutor.execute(PostgreSQLComQueryExecutor.java:76)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:107)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by lanchengx** [comment]
Hi @zjcnb could you provide the relevant configuration? I can't reproduce it in Proxy started with only `server.yaml` configuration.
<img width="254" alt="image" src="https://user-images.githubusercontent.com/52209337/167575386-3455c3ed-ba31-419b-857e-a22e0edda9ed.png">
