### ISSUE TITLE
The problem of  insert into select from ... sql

### ISSUE THREAD

**Issue by PaleWhiteDot** [apache/shardingsphere#17396]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [[GitHub issues](https://github.com/apache/shardingsphere/issues)](https://github.com/apache/shardingsphere/issues).
- Read documentation: [[ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview)](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

5.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

#### SQL

database：mysql

sql：

```
insert into  table1 select from table2
```

#### error1

throw exception like this:

```
Caused by: org.apache.shardingsphere.infra.exception.ShardingSphereException: The table inserted and the table selected must be the same or bind tables.
```

table1 and table2 are not same table,so i think i should configure bind tables.

### Config

```
rules:
  - !SHARDING
    bindingTables: ["table1", "table2"]
    ......
```

#### error2

throw exception like this:

```
Caused by: java.lang.NullPointerException
		 at org.apache.shardingsphere.sharding.rule.ShardingRule.isBroadcastTable(ShardingRule.java:463) ~[shardingsphere-sharding-core-5.1.1.jar:5.1.1]
		 at org.apache.shardingsphere.sharding.rule.ShardingRule.getTableRule(ShardingRule.java:352) ~[shardingsphere-sharding-core-5.1.1.jar:5.1.1]
		 at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_202]
		 at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_202]
		 at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_202]
		 at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_202]
		 at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_202]
		 at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_202]
		 at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_202]
		 at org.apache.shardingsphere.sharding.rule.ShardingRule.createBindingTableRule(ShardingRule.java:217) ~[shardingsphere-sharding-core-5.1.1.jar:5.1.1]
		 at org.apache.shardingsphere.sharding.rule.ShardingRule.createBindingTableRules(ShardingRule.java:207) ~[shardingsphere-sharding-core-5.1.1.jar:5.1.1]
```

In the construction method of shardingRule,bindingTables and broadCastTables will be initialized. Here we call the base node createBindingTableRules() first.then call the createBroadcastTables method.

```
  public ShardingRule(final ShardingRuleConfiguration config, final Collection<String> dataSourceNames) {
        this.dataSourceNames = getDataSourceNames(config.getTables(), config.getAutoTables(), dataSourceNames);
        tableRules.putAll(createTableRules(config.getTables(), config.getDefaultKeyGenerateStrategy()));
        tableRules.putAll(createAutoTableRules(config.getAutoTables(), config.getDefaultKeyGenerateStrategy()));
        bindingTableRules.putAll(createBindingTableRules(config.getBindingTableGroups()));
        broadcastTables = createBroadcastTables(config.getBroadcastTables());
    ......
    }
```

However,when calling the createBindingTablerules() method, the following judgment will be made

```
    public TableRule getTableRule(final String logicTableName) {
        Optional<TableRule> tableRule = findTableRule(logicTableName);
        if (tableRule.isPresent()) {
            return tableRule.get();
        }
        if (isBroadcastTable(logicTableName)) {
            return new TableRule(dataSourceNames, logicTableName);
        }
        throw new ShardingSphereConfigurationException("Cannot find table rule with logic table: '%s'", logicTableName);
    }
```

This method will call the isBroadCastTable() method to determine whether the configured table name is broadCastTable,but the broadCastTable has not been initialized at this time,so it will eventually lead to NPE.So i thind when calling ShardingRule construction method,we should first call createBroadCastTables() method to initialize broadCastTables.

**Comment by tain198127** [comment]
Hi @PaleWhiteDot 
could you show some yaml config , DDL sql and prototype code for reproduce this issue?
