### ISSUE TITLE
ClusterContextManagerCoordinatorTest.assertTriggerShowProcessList run failed on Windows CI

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#17461]
## Bug Report

https://github.com/apache/shardingsphere/runs/6341978025?check_suite_focus=true

```
Error:  Failures: 
Error:    ClusterContextManagerCoordinatorTest.assertTriggerShowProcessList:374 
Argument(s) are different! Wanted:
clusterPersistRepository.persist(
    "/execution_nodes/foo_process_id/proxy_10.1.0.207@3307",
    "contexts:
- startTimeMillis: 0
"
);
-> at org.apache.shardingsphere.mode.manager.cluster.coordinator.ClusterContextManagerCoordinatorTest.assertTriggerShowProcessList(ClusterContextManagerCoordinatorTest.java:374)
Actual invocations have different arguments:
clusterPersistRepository.persist(
    "/execution_nodes/foo_process_id/proxy_10.1.0.207@3307",
    "contexts:
- startTimeMillis: 0
"
);
-> at org.apache.shardingsphere.mode.manager.cluster.coordinator.ClusterContextManagerCoordinator.triggerShowProcessList(ClusterContextManagerCoordinator.java:306)
clusterPersistRepository.delete(
    "/nodes/compute_nodes/process_trigger/proxy/10.1.0.207@3307/foo_process_id"
);
-> at org.apache.shardingsphere.mode.manager.cluster.coordinator.ClusterContextManagerCoordinator.triggerShowProcessList(ClusterContextManagerCoordinator.java:310)
```

**Comment by Trydamere** [comment]
@sandynz Hi, are you working on this issue? I can try to solve it.

**Comment by strongduanmu** [comment]
@Trydamere Welcome.

**Comment by sandynz** [comment]
@Trydamere , welcome. I'm not working on it.

**Comment by Trydamere** [comment]
The cause is the line break is different bewteen windows and linux. I will pull request after the build is finished.
