### ISSUE TITLE
Invalid binding table configuration in ShardingRuleConfiguration when alter SHARDING TABLE RULE

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#17487]
### Which version of ShardingSphere did you use?

`master`

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

`ShardingSphere-Proxy`

### Expected behavior

`No error msg`

### Actual behavior

```
五月 09, 2022 6:54:08 下午 com.google.common.eventbus.EventBus$LoggingHandler handleException
严重: Exception thrown by subscriber method start(org.apache.shardingsphere.mode.manager.cluster.coordinator.registry.cache.event.StartScalingEvent) on subscriber org.apache.shardingsphere.data.pipeline.scenario.rulealtered.RuleAlteredJobWorker@6dde1bf5 when dispatching event: StartScalingEvent(databaseName=sharding_db, activeVersion=0, newVersion=1)
java.lang.IllegalArgumentException: Invalid binding table configuration in ShardingRuleConfiguration.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
	at org.apache.shardingsphere.sharding.rule.ShardingRule.<init>(ShardingRule.java:120)
	at org.apache.shardingsphere.sharding.schedule.ShardingRuleAlteredDetector.findRuleAlteredLogicTables(ShardingRuleAlteredDetector.java:80)
	at org.apache.shardingsphere.data.pipeline.scenario.rulealtered.RuleAlteredJobWorker.createJobConfig(RuleAlteredJobWorker.java:193)
	at org.apache.shardingsphere.data.pipeline.scenario.rulealtered.RuleAlteredJobWorker.start(RuleAlteredJobWorker.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:67)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:108)
	at com.google.common.eventbus.EventBus.post(EventBus.java:212)
	at org.apache.shardingsphere.proxy.backend.text.distsql.rdl.rule.RuleDefinitionBackendHandler.persistRuleConfigurationChange(RuleDefinitionBackendHandler.java:161)
	at org.apache.shardingsphere.proxy.backend.text.distsql.rdl.rule.RuleDefinitionBackendHandler.prepareScaling(RuleDefinitionBackendHandler.java:150)
	at org.apache.shardingsphere.proxy.backend.text.distsql.rdl.rule.RuleDefinitionBackendHandler.execute(RuleDefinitionBackendHandler.java:83)
	at org.apache.shardingsphere.proxy.backend.text.distsql.rdl.rule.RuleDefinitionBackendHandler.execute(RuleDefinitionBackendHandler.java:58)
	at org.apache.shardingsphere.proxy.backend.text.DatabaseRequiredBackendHandler.execute(DatabaseRequiredBackendHandler.java:51)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:97)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:107)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

### Configuration

```
databaseName: sharding_db

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/ds_0?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/ds_0?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !SHARDING
  tables:
    t_order:
      actualDataNodes: ds_${0..1}.t_order_${0..1}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: t_order_inline
      keyGenerateStrategy:
        column: order_id
        keyGeneratorName: snowflake
    t_order_item:
      actualDataNodes: ds_${0..1}.t_order_item_${0..1}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: t_order_item_inline
      keyGenerateStrategy:
        column: order_item_id
        keyGeneratorName: snowflake
  bindingTables:
    - t_order,t_order_item
  defaultDatabaseStrategy:
    standard:
      shardingColumn: user_id
      shardingAlgorithmName: database_inline
  defaultTableStrategy:
    none:

  shardingAlgorithms:
    database_inline:
      type: INLINE
      props:
        algorithm-expression: ds_${user_id % 2}
    t_order_inline:
      type: INLINE
      props:
        algorithm-expression: t_order_${order_id % 2}
    t_order_item_inline:
      type: INLINE
      props:
        algorithm-expression: t_order_item_${order_id % 2}

  keyGenerators:
    snowflake:
      type: SNOWFLAKE

  scalingName: default_scaling
  scaling:
    default_scaling:
      input:
        workerThread: 40
        batchSize: 1000
      output:
        workerThread: 40
        batchSize: 1000
      streamChannel:
        type: MEMORY
        props:
          block-queue-size: 10000
      completionDetector:
        type: IDLE
        props:
          incremental-task-idle-seconds-threshold: 1800
      dataConsistencyChecker:
        type: DATA_MATCH
        props:
          chunk-size: 1000
```

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

```
ADD RESOURCE ds_2 (
    HOST=127.0.0.1,
    PORT=3306,
    DB=ds0,
    USER=root,
    PASSWORD=123456
);
ADD RESOURCE ds_3 (
    HOST=127.0.0.1,
    PORT=3306,
    DB=ds0,
    USER=root,
    PASSWORD=123456
);
ADD RESOURCE ds_4 (
    HOST=127.0.0.1,
    PORT=3306,
    DB=ds0,
    USER=root,
    PASSWORD=123456
);


ALTER SHARDING TABLE RULE t_order(
 RESOURCES(ds_2,ds_3,ds_4),
 SHARDING_COLUMN=order_id,
 TYPE(NAME=hash_mod,PROPERTIES("sharding-count"=6)),
 KEY_GENERATE_STRATEGY(COLUMN=order_id,TYPE(NAME=snowflake))
 );
```

**Comment by strongduanmu** [comment]
> Hi, I want to investigate this.

@yx9o Welcome.

**Comment by zjcnb** [comment]
> @zjcnb Hi, I can't reproduce this error with the configuration above, what should I do. I executed the following sql: ![企业微信截图_16521913709662](https://user-images.githubusercontent.com/12792261/167647748-8477d01b-52b6-48ce-bbdf-81a0b8156718.png) ![企业微信截图_16521913879383](https://user-images.githubusercontent.com/12792261/167647801-90c1f677-b6a7-4925-96c9-fc754a27225a.png) ![企业微信截图_16521914182681](https://user-images.githubusercontent.com/12792261/167647830-af60f73d-40fe-4c7e-a373-8029df1ffda6.png) ![企业微信截图_16521914338287](https://user-images.githubusercontent.com/12792261/167647846-2f1eae94-a5f0-4aa3-9e50-a7d9cefd0ec6.png)

Sorry, i forget to provider `server.yaml`, i use `cluster mode`

**Comment by yx9o** [comment]
Ok, i'll try again.

**Comment by TeslaCN** [comment]
+1

Drop binding table rule didn't worked in cluster mode.

```
bmsql_sharding=> drop sharding binding table rules (bmsql_warehouse, bmsql_customer);
SUCCESS
bmsql_sharding=> ADD RESOURCE target_0 (
bmsql_sharding(>     URL="jdbc:opengauss://127.0.0.1:35433/bmsql_0",
bmsql_sharding(>     USER=omm,
bmsql_sharding(>     PASSWORD=Huawei@123,
bmsql_sharding(>     PROPERTIES("maximumPoolSize"=64, "minimumIdle"=0,"idleTimeout"="60000")
bmsql_sharding(> ), target_1 (
bmsql_sharding(>     URL="jdbc:opengauss://127.0.0.1:35433/bmsql_1",
bmsql_sharding(>     USER=omm,
bmsql_sharding(>     PASSWORD=Huawei@123,
bmsql_sharding(>     PROPERTIES("maximumPoolSize"=64, "minimumIdle"=0,"idleTimeout"="60000")
bmsql_sharding(> ), target_2 (
bmsql_sharding(>     URL="jdbc:opengauss://127.0.0.1:35433/bmsql_2",
bmsql_sharding(>     USER=omm,
bmsql_sharding(>     PASSWORD=Huawei@123,
bmsql_sharding(>     PROPERTIES("maximumPoolSize"=64, "minimumIdle"=0,"idleTimeout"="60000")
bmsql_sharding(> );
SUCCESS
bmsql_sharding=> ALTER SHARDING TABLE RULE bmsql_warehouse(
bmsql_sharding(>     RESOURCES(target_0, target_1, target_2),
bmsql_sharding(>     SHARDING_COLUMN=w_id,
bmsql_sharding(>     TYPE(NAME=MOD,PROPERTIES("sharding-count"=3))
bmsql_sharding(> );
SUCCESS
bmsql_sharding=> show sharding binding table rules;
            sharding_binding_tables            
-----------------------------------------------
 bmsql_warehouse, bmsql_customer
 bmsql_stock, bmsql_district, bmsql_order_line
(2 rows)

bmsql_sharding=> drop sharding binding table rules (bmsql_warehouse, bmsql_customer);
ERROR:  Invalid binding table configuration in ShardingRuleConfiguration.
bmsql_sharding=> show sharding binding table rules;
            sharding_binding_tables            
-----------------------------------------------
 bmsql_warehouse, bmsql_customer
 bmsql_stock, bmsql_district, bmsql_order_line
(2 rows)
```

```
[INFO ] 2022-05-11 14:33:38.603 [Connection-1-ThreadExecutor] o.a.s.m.m.c.c.r.c.s.ScalingRegistrySubscriber - start scaling job, locked the schema name, event=MetadataVersionPreparedEvent(version=1, databaseName=bmsql_sharding)
[INFO ] 2022-05-11 14:33:38.603 [Connection-1-ThreadExecutor] o.a.s.d.p.s.r.RuleAlteredJobWorker - Start scaling job by StartScalingEvent(databaseName=bmsql_sharding, activeVersion=0, newVersion=1)
[ERROR] 2022-05-11 14:33:38.646 [Connection-1-ThreadExecutor] c.g.common.eventbus.EventBus.default - Exception thrown by subscriber method start(org.apache.shardingsphere.mode.manager.cluster.coordinator.registry.cache.event.StartScalingEvent) on subscriber org.apache.shardingsphere.data.pipeline.scenario.rulealtered.RuleAlteredJobWorker@bb12f41 when dispatching event: StartScalingEvent(databaseName=bmsql_sharding, activeVersion=0, newVersion=1)
java.lang.IllegalArgumentException: Invalid binding table configuration in ShardingRuleConfiguration.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
	at org.apache.shardingsphere.sharding.rule.ShardingRule.<init>(ShardingRule.java:120)
	at org.apache.shardingsphere.sharding.schedule.ShardingRuleAlteredDetector.findRuleAlteredLogicTables(ShardingRuleAlteredDetector.java:80)
	at org.apache.shardingsphere.data.pipeline.scenario.rulealtered.RuleAlteredJobWorker.createJobConfig(RuleAlteredJobWorker.java:193)
	at org.apache.shardingsphere.data.pipeline.scenario.rulealtered.RuleAlteredJobWorker.start(RuleAlteredJobWorker.java:172)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:67)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:108)
	at com.google.common.eventbus.EventBus.post(EventBus.java:212)
	at org.apache.shardingsphere.proxy.backend.text.distsql.rdl.rule.RuleDefinitionBackendHandler.persistRuleConfigurationChange(RuleDefinitionBackendHandler.java:161)
	at org.apache.shardingsphere.proxy.backend.text.distsql.rdl.rule.RuleDefinitionBackendHandler.prepareScaling(RuleDefinitionBackendHandler.java:150)
	at org.apache.shardingsphere.proxy.backend.text.distsql.rdl.rule.RuleDefinitionBackendHandler.execute(RuleDefinitionBackendHandler.java:83)
	at org.apache.shardingsphere.proxy.backend.text.distsql.rdl.rule.RuleDefinitionBackendHandler.execute(RuleDefinitionBackendHandler.java:58)
	at org.apache.shardingsphere.proxy.backend.text.DatabaseRequiredBackendHandler.execute(DatabaseRequiredBackendHandler.java:51)
	at org.apache.shardingsphere.proxy.frontend.opengauss.command.query.simple.OpenGaussComQueryExecutor.execute(OpenGaussComQueryExecutor.java:76)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:107)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:77)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR] 2022-05-11 14:36:22.582 [Connection-1-ThreadExecutor] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
java.lang.IllegalArgumentException: Invalid binding table configuration in ShardingRuleConfiguration.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
	at org.apache.shardingsphere.sharding.rule.ShardingRule.<init>(ShardingRule.java:120)
	at org.apache.shardingsphere.sharding.rule.builder.ShardingRuleBuilder.build(ShardingRuleBuilder.java:41)
	at org.apache.shardingsphere.sharding.rule.builder.ShardingRuleBuilder.build(ShardingRuleBuilder.java:35)
	at org.apache.shardingsphere.infra.rule.builder.schema.SchemaRulesBuilder.buildRules(SchemaRulesBuilder.java:56)
	at org.apache.shardingsphere.mode.metadata.MetaDataContextsBuilder.getDatabaseRules(MetaDataContextsBuilder.java:105)
	at org.apache.shardingsphere.mode.metadata.MetaDataContextsBuilder.addDatabase(MetaDataContextsBuilder.java:83)
	at org.apache.shardingsphere.mode.manager.ContextManager.buildChangedMetaDataContext(ContextManager.java:552)
	at org.apache.shardingsphere.mode.manager.ContextManager.alterRuleConfiguration(ContextManager.java:318)
	at org.apache.shardingsphere.proxy.backend.text.distsql.rdl.rule.RuleDefinitionBackendHandler.processSQLStatement(RuleDefinitionBackendHandler.java:113)
	at org.apache.shardingsphere.proxy.backend.text.distsql.rdl.rule.RuleDefinitionBackendHandler.execute(RuleDefinitionBackendHandler.java:87)
	at org.apache.shardingsphere.proxy.backend.text.distsql.rdl.rule.RuleDefinitionBackendHandler.execute(RuleDefinitionBackendHandler.java:58)
	at org.apache.shardingsphere.proxy.backend.text.DatabaseRequiredBackendHandler.execute(DatabaseRequiredBackendHandler.java:51)
	at org.apache.shardingsphere.proxy.frontend.opengauss.command.query.simple.OpenGaussComQueryExecutor.execute(OpenGaussComQueryExecutor.java:76)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:107)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:77)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by yx9o** [comment]
@strongduanmu Hi, I want to reuse `ShardingRule.isValidBindingTableConfiguration` in the `AlterShardingTableRuleStatementUpdater` class. In order to meet the requirements, I need to pass some data used in `isValidBindingTableConfiguration` in the form of parameters, which may cause the method parameter list to become longer. Is it feasible?

**Comment by strongduanmu** [comment]
@yx9o How many parameters will be added? If there are too many parameters, consider adding a parameter object for encapsulation.

**Comment by yx9o** [comment]
> @yx9o How many parameters will be added? If there are too many parameters, consider adding a parameter object for encapsulation.

OK, it's changed. Please review it.

**Comment by TeslaCN** [comment]
Hi @zjcnb @yx9o 
Have we finished this issue?

**Comment by yx9o** [comment]
> Hi @zjcnb @yx9o Have we finished this issue?

Yes, it's done.

**Comment by TeslaCN** [comment]
Close via #17931.
