### ISSUE TITLE
After creating table via ShardingSphereDataSource in proxy, metadata/logic_db/ created in registry center

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#17777]
### Which version of ShardingSphere did you use?
release branch
Need to revert temp workaround commit.
Change `ShardingSpherePipelineDataSourceConfiguration` code to:
```
    public ShardingSpherePipelineDataSourceConfiguration(final YamlRootConfiguration rootConfig) {
        YamlParameterConfiguration parameterConfig = new YamlParameterConfiguration(rootConfig.getDataSources(), rootConfig.getRules());
...
```
And also `YamlParameterConfiguration`.

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
Proxy, scaling enabled

### Expected behavior
No `metadata/logic_db/` is created in registry center.

### Actual behavior
`metadata/logic_db/` is created.

### Reason analyze (If you can)
Scaling job will create table in target automatically (related code is AbstractDataSourcePreparer), SQL is:
```
CREATE TABLE IF NOT EXISTS `t_order` (
  `order_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `status` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

There's invocation of `CuratorZookeeperRepository.persist`, `key` is `/metadata/logic_db/tables/t_order`, value is:
```
columns:
  order_id:
    caseSensitive: false
    dataType: 4
    generated: true
    name: order_id
    primaryKey: true
  user_id:
    caseSensitive: false
    dataType: 4
    generated: false
    name: user_id
    primaryKey: false
  status:
    caseSensitive: false
    dataType: 12
    generated: false
    name: status
    primaryKey: false
name: t_order
```

Screenshot:
1,
<img width="1117" alt="图片" src="https://user-images.githubusercontent.com/42492540/168983888-7452b5a5-4fc6-4ac9-8a38-644b834c9d45.png">

2,
<img width="1211" alt="图片" src="https://user-images.githubusercontent.com/42492540/168983330-f09ed31f-d09c-40bd-9532-bbf39e37d116.png">

Related stack trace:
```
persist:151, CuratorZookeeperRepository (org.apache.shardingsphere.mode.repository.cluster.zookeeper)
persist:67, SchemaMetaDataPersistService (org.apache.shardingsphere.mode.metadata.persist.service)
lambda$update$0:45, SchemaMetaDataRegistrySubscriber (org.apache.shardingsphere.mode.manager.cluster.coordinator.registry.metadata.subscriber)
accept:-1, 916026305 (org.apache.shardingsphere.mode.manager.cluster.coordinator.registry.metadata.subscriber.SchemaMetaDataRegistrySubscriber$$Lambda$1273)
forEach:1259, ArrayList (java.util)
update:45, SchemaMetaDataRegistrySubscriber (org.apache.shardingsphere.mode.manager.cluster.coordinator.registry.metadata.subscriber)
invoke0:-1, NativeMethodAccessorImpl (sun.reflect)
invoke:62, NativeMethodAccessorImpl (sun.reflect)
invoke:43, DelegatingMethodAccessorImpl (sun.reflect)
invoke:498, Method (java.lang.reflect)
invokeSubscriberMethod:87, Subscriber (com.google.common.eventbus)
invokeSubscriberMethod:144, Subscriber$SynchronizedSubscriber (com.google.common.eventbus)
run:72, Subscriber$1 (com.google.common.eventbus)
execute:30, DirectExecutor (com.google.common.util.concurrent)
dispatchEvent:67, Subscriber (com.google.common.eventbus)
dispatch:108, Dispatcher$PerThreadQueuedDispatcher (com.google.common.eventbus)
post:212, EventBus (com.google.common.eventbus)
lambda$refresh$1:64, CreateTableStatementSchemaRefresher (org.apache.shardingsphere.infra.context.refresher.type)
accept:-1, 1508359143 (org.apache.shardingsphere.infra.context.refresher.type.CreateTableStatementSchemaRefresher$$Lambda$1272)
ifPresent:159, Optional (java.util)
refresh:58, CreateTableStatementSchemaRefresher (org.apache.shardingsphere.infra.context.refresher.type)
refresh:44, CreateTableStatementSchemaRefresher (org.apache.shardingsphere.infra.context.refresher.type)
refresh:73, MetaDataRefreshEngine (org.apache.shardingsphere.infra.context.refresher)
refreshMetaData:159, DriverJDBCExecutor (org.apache.shardingsphere.driver.executor)
doExecute:154, DriverJDBCExecutor (org.apache.shardingsphere.driver.executor)
execute:142, DriverJDBCExecutor (org.apache.shardingsphere.driver.executor)
execute:412, ShardingSphereStatement (org.apache.shardingsphere.driver.jdbc.core.statement)
execute0:436, ShardingSphereStatement (org.apache.shardingsphere.driver.jdbc.core.statement)
execute:354, ShardingSphereStatement (org.apache.shardingsphere.driver.jdbc.core.statement)
executeTargetTableSQL:61, AbstractDataSourcePreparer (org.apache.shardingsphere.data.pipeline.core.prepare.datasource)
prepareTargetTables:55, MySQLDataSourcePreparer (org.apache.shardingsphere.data.pipeline.mysql.prepare.datasource)
prepareTarget:90, RuleAlteredJobPreparer (org.apache.shardingsphere.data.pipeline.scenario.rulealtered)
prepare:69, RuleAlteredJobPreparer (org.apache.shardingsphere.data.pipeline.scenario.rulealtered)
execute:51, RuleAlteredJob (org.apache.shardingsphere.data.pipeline.scenario.rulealtered)
process:33, SimpleJobExecutor (org.apache.shardingsphere.elasticjob.simple.executor)
process:29, SimpleJobExecutor (org.apache.shardingsphere.elasticjob.simple.executor)
process:172, ElasticJobExecutor (org.apache.shardingsphere.elasticjob.executor)
lambda$process$0:153, ElasticJobExecutor (org.apache.shardingsphere.elasticjob.executor)
run:-1, 1261037162 (org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor$$Lambda$1158)
call:511, Executors$RunnableAdapter (java.util.concurrent)
runInterruptibly:125, TrustedListenableFutureTask$TrustedFutureInterruptibleTask (com.google.common.util.concurrent)
run:69, InterruptibleTask (com.google.common.util.concurrent)
run:78, TrustedListenableFutureTask (com.google.common.util.concurrent)
runWorker:1149, ThreadPoolExecutor (java.util.concurrent)
run:624, ThreadPoolExecutor$Worker (java.util.concurrent)
run:748, Thread (java.lang)
```

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1, Revert temp workaround commit fa8d79835e72b8162d1e7f42aef2cbd633489af8 on master branch.
2, Run scaling job.
3, Check `metadata/` in registry center.

**Comment by sandynz** [comment]
Except `metadata/logic_db/tables/t_order`, there're other nodes will be created, e.g. `/metadata/logic_db/versions/0/dataSources` and `/metadata/logic_db/versions/0/rules`.

Related code path:
```
"Curator-SafeNotifyService-0@6397" daemon prio=5 tid=0x34 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.apache.shardingsphere.mode.repository.cluster.zookeeper.CuratorZookeeperRepository.persist(CuratorZookeeperRepository.java:151)
	  at org.apache.shardingsphere.mode.metadata.persist.service.impl.SchemaRulePersistService.persist(SchemaRulePersistService.java:55)
	  at org.apache.shardingsphere.mode.manager.cluster.coordinator.ClusterContextManagerCoordinator.persistSchema(ClusterContextManagerCoordinator.java:266)
	  at org.apache.shardingsphere.mode.manager.cluster.coordinator.ClusterContextManagerCoordinator.renew(ClusterContextManagerCoordinator.java:83)
```
