### ISSUE TITLE
java.lang.NumberFormatException: For input string: "8849485702" at InstanceId.<init>(InstanceId.java:65)

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#17819]
## Bug Report

This issue affects ShardingSphere >= 5.1.0

Caused by: https://github.com/apache/shardingsphere/pull/15188

Relates to #17806.

### Which version of ShardingSphere did you use?

master - https://github.com/apache/shardingsphere/tree/a393962f5b3eec2d154ad1c2c5d15a758efc499b

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Scaling (ShardingSphere-JDBC is used in Scaling)

### Actual behavior

After data consistency check kept failing for 12 hours, new error occurred.

```
[INFO ] 2022-05-20 09:51:00.032 [_finished_check_Worker-1] o.a.s.d.p.core.job.FinishedCheckJob - scaling job 0130317c30317c3054317c626d73716c5f7368617264696e67 almost finished.
[INFO ] 2022-05-20 09:51:00.032 [_finished_check_Worker-1] o.a.s.d.p.s.r.s.DefaultSourceWritingStopLock - lock, databaseName=bmsql_sharding, jobId=0130317c30317c3054317c626d73716c5f7368617264696e67
[INFO ] 2022-05-20 09:51:00.054 [_finished_check_Worker-1] o.a.s.d.p.c.a.i.RuleAlteredJobAPIImpl - stopClusterWriteDB, tryLockSuccess=true
[INFO ] 2022-05-20 09:51:00.056 [_finished_check_Worker-1] o.a.s.d.p.core.job.FinishedCheckJob - dataConsistencyCheck for job 0130317c30317c3054317c626d73716c5f7368617264696e67
[INFO ] 2022-05-20 09:51:00.057 [_finished_check_Worker-1] o.a.s.d.p.a.c.TableNameSchemaNameMapping - mapping={pg_trigger=pg_catalog, bmsql_district=public, bmsql_oorder=public, bmsql_stock=public, columns=information_schema, pg_class=pg_catalog, pg_tablespace=pg_catalog, pg_database=pg_catalog, bmsql_customer=public, bmsql_item=public, tables=information_schema, bmsql_new_order=public, bmsql_history=public, bmsql_warehouse=public, pg_inherits=pg_catalog, bmsql_order_line=public, views=information_schema, bmsql_config=public}
[INFO ] 2022-05-20 09:51:00.060 [_finished_check_Worker-1] o.a.s.d.p.s.r.s.DefaultSourceWritingStopLock - releaseLock, databaseName=bmsql_sharding, jobId=0130317c30317c3054317c626d73716c5f7368617264696e67
[INFO ] 2022-05-20 09:51:00.060 [_finished_check_Worker-1] o.a.s.d.p.c.a.i.RuleAlteredJobAPIImpl - restoreClusterWriteDB, before releaseLock, databaseName=bmsql_sharding, jobId=0130317c30317c3054317c626d73716c5f7368617264696e67
[ERROR] 2022-05-20 09:51:00.062 [_finished_check_Worker-1] o.a.s.d.p.core.job.FinishedCheckJob - scaling job 0130317c30317c3054317c626d73716c5f7368617264696e67 finish check failed!
java.lang.NumberFormatException: For input string: "8849485702"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.valueOf(Integer.java:999)
	at org.apache.shardingsphere.infra.instance.definition.InstanceId.<init>(InstanceId.java:65)
	at org.apache.shardingsphere.infra.instance.definition.InstanceDefinition.<init>(InstanceDefinition.java:36)
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.createContextManager(ShardingSphereDataSource.java:78)
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.<init>(ShardingSphereDataSource.java:64)
	at org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactory.createDataSource(ShardingSphereDataSourceFactory.java:77)
	at org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactory.createDataSource(ShardingSphereDataSourceFactory.java:138)
	at org.apache.shardingsphere.driver.data.pipeline.datasource.creator.ShardingSpherePipelineDataSourceCreator.createPipelineDataSource(ShardingSpherePipelineDataSourceCreator.java:43)
	at org.apache.shardingsphere.data.pipeline.core.datasource.PipelineDataSourceFactory.newInstance(PipelineDataSourceFactory.java:44)
	at org.apache.shardingsphere.data.pipeline.core.check.consistency.DataConsistencyChecker.checkCount(DataConsistencyChecker.java:111)
	at org.apache.shardingsphere.data.pipeline.core.check.consistency.DataConsistencyChecker.check(DataConsistencyChecker.java:93)
	at org.apache.shardingsphere.data.pipeline.core.api.impl.RuleAlteredJobAPIImpl.dataConsistencyCheck(RuleAlteredJobAPIImpl.java:288)
	at org.apache.shardingsphere.data.pipeline.core.api.impl.RuleAlteredJobAPIImpl.dataConsistencyCheck(RuleAlteredJobAPIImpl.java:274)
	at org.apache.shardingsphere.data.pipeline.core.job.FinishedCheckJob.dataConsistencyCheck(FinishedCheckJob.java:124)
	at org.apache.shardingsphere.data.pipeline.core.job.FinishedCheckJob.execute(FinishedCheckJob.java:89)
	at org.apache.shardingsphere.elasticjob.simple.executor.SimpleJobExecutor.process(SimpleJobExecutor.java:33)
	at org.apache.shardingsphere.elasticjob.simple.executor.SimpleJobExecutor.process(SimpleJobExecutor.java:29)
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.process(ElasticJobExecutor.java:172)
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.process(ElasticJobExecutor.java:141)
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.execute(ElasticJobExecutor.java:124)
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.execute(ElasticJobExecutor.java:100)
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.LiteJob.execute(LiteJob.java:35)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

**Comment by TeslaCN** [comment]
The pid_max of my system is the following value, which means if there are 100 `ShardingSphereDataSource` in JVM, this error will occurred.
```
% cat /proc/sys/kernel/pid_max
4194304
```

**Comment by TeslaCN** [comment]
Hi @menghaoranss
Could you have a look at this?

**Comment by cheese8** [comment]
I'd like to follow this, thanks. @TeslaCN @menghaoranss

**Comment by TeslaCN** [comment]
> I'd like to follow this, thanks. @TeslaCN @menghaoranss

Assigned.
