### ISSUE TITLE
DistSql Bug: Executing add-resource continuously may encounter "HikariDataSource (HikariPool-xxx) has been closed" exception

### ISSUE THREAD

**Issue by pencilcap123** [apache/shardingsphere#17918]
### Which version of ShardingSphere did you use?
5.1.1 Release

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
All the add-resources dist-sql will success if all the jdbc properties are correct.

### Actual behavior
Add-resource dist-sql may failed after serveral success.

### Reason analyze (If you can)
concurrent issue 
1. datasource graceful close is triggered async in validate method
2. getting jdbc connection from datasource is required to fetch db meta in addresource method
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/41630875/170035675-19c815ac-d0d0-40f2-952b-c3c236f7276c.png">

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
executing add-resource distsql continuously  may leads to this problem. In my case, client would receive exception after 2~3 successful add-resource distsql
![image](https://user-images.githubusercontent.com/41630875/170036808-0b2484f9-dde3-4c0b-bc55-9b1690c70e54.png)

and stacktrace in shardingproxy server :
```
[ERROR] 2022-05-24 20:01:09.465 [ShardingSphere-Command-5] o.a.s.p.b.t.d.r.r.AddResourceBackendHandler - Add resource failed
java.lang.IllegalArgumentException: HikariDataSource HikariDataSource (HikariPool-163) has been closed.
	at org.apache.shardingsphere.infra.database.type.DatabaseTypeRecognizer.getDatabaseType(DatabaseTypeRecognizer.java:55)
	at org.apache.shardingsphere.infra.database.type.DatabaseTypeRecognizer.getDatabaseType(DatabaseTypeRecognizer.java:44)
	at org.apache.shardingsphere.infra.metadata.schema.loader.SchemaLoader.load(SchemaLoader.java:52)
	at org.apache.shardingsphere.infra.metadata.database.loader.DatabaseLoader.load(DatabaseLoader.java:53)
	at org.apache.shardingsphere.mode.metadata.MetaDataContextsBuilder.addSchema(MetaDataContextsBuilder.java:84)
	at org.apache.shardingsphere.mode.manager.ContextManager.buildChangedMetaDataContextWithAddedDataSource(ContextManager.java:478)
	at org.apache.shardingsphere.mode.manager.ContextManager.refreshMetaDataContext(ContextManager.java:451)
	at org.apache.shardingsphere.mode.manager.ContextManager.addResource(ContextManager.java:232)
	at org.apache.shardingsphere.proxy.backend.text.distsql.rdl.resource.AddResourceBackendHandler.execute(AddResourceBackendHandler.java:64)
	at org.apache.shardingsphere.proxy.backend.text.distsql.rdl.resource.AddResourceBackendHandler.execute(AddResourceBackendHandler.java:45)
	at org.apache.shardingsphere.proxy.backend.text.SchemaRequiredBackendHandler.execute(SchemaRequiredBackendHandler.java:51)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:97)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:100)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-163) has been closed.
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
	at org.apache.shardingsphere.infra.database.type.DatabaseTypeRecognizer.getDatabaseType(DatabaseTypeRecognizer.java:52)
	... 16 common frames omitted
```

### Example codes for reproduce this issue (such as a github link).
not necessary

**Comment by pencilcap123** [comment]
@RaigorJiang Is it a bug recently introduced in 5.1.1 ? Will it help if I roll back to 5.1.0 or a certain earlier version ?

**Comment by RaigorJiang** [comment]
Hi @pencilcap123 
The cause of the exception still needs to be investigated, and it will be updated here when there is progress.

**Comment by RaigorJiang** [comment]
Hi @pencilcap123 
I verified the 5.1.1 Release and master branch, and did not reproduce your problem.

The code you analyzed is not accurate, the connection pool used for `getDatabaseType` is created in the `buildChangedMetaDataContextWithAddedDataSource` method, it is not the same as the one in the validator.

I guess you have specified `poolName` for connection pool and the `poolName` is duplicated, please check and give feedback.

**Comment by RaigorJiang** [comment]
Closed because no response.

**Comment by pencilcap123** [comment]
> Hi @pencilcap123 I verified the 5.1.1 Release and master branch, and did not reproduce your problem.
> 
> The code you analyzed is not accurate, the connection pool used for `getDatabaseType` is created in the `buildChangedMetaDataContextWithAddedDataSource` method, it is not the same as the one in the validator.
> 
> I guess you have specified `poolName` for connection pool and the `poolName` is duplicated, please check and give feedback.

there is no poolName attribute assigned for the connection pool, but I do specified a lot of pool properties
