### ISSUE TITLE
Scaling IncrementTask not handle BigDecimal correct

### ISSUE THREAD

**Issue by azexcy** [apache/shardingsphere#18064]
## Bug Report

When insert table data that not set the value of numeric column.
Scaling IncrementTask `PostgreSQLWalDumper` handle numeric to `BigDecimal` not corrently.

### Which version of ShardingSphere did you use?

master a159040ed39eb26838fc236f1e99c8ff22c4f336

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

Proxy

### Expected behavior

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/101622833/170946353-fa5841ef-6e5a-41a1-a0e7-389c1718b2c3.png">

### Actual behavior

`new BigDecimal("")` or `new BigDecimal("null")` will cause exception.

### Reason analyze (If you can)

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/101622833/170944965-f4e82738-c05d-40ba-82f9-b453b2edf36a.png">

seem other data type will also cause problem.
```
[ERROR] 2022-05-30 16:55:05.771 [ShardingSphere-Scaling-Incremental-0130317c30317c3054317c7368617264696e675f6462-4] o.a.s.d.p.s.r.RuleAlteredJobScheduler - Incremental task execute failed.
java.lang.NumberFormatException: For input string: "null"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at org.apache.shardingsphere.data.pipeline.postgresql.ingest.wal.decode.TestDecodingPlugin.readColumnData(TestDecodingPlugin.java:170)
	at org.apache.shardingsphere.data.pipeline.postgresql.ingest.wal.decode.TestDecodingPlugin.readColumn(TestDecodingPlugin.java:129)
	at org.apache.shardingsphere.data.pipeline.postgresql.ingest.wal.decode.TestDecodingPlugin.readWriteRowEvent(TestDecodingPlugin.java:90)
	at org.apache.shardingsphere.data.pipeline.postgresql.ingest.wal.decode.TestDecodingPlugin.readTableEvent(TestDecodingPlugin.java:69)
	at org.apache.shardingsphere.data.pipeline.postgresql.ingest.wal.decode.TestDecodingPlugin.decode(TestDecodingPlugin.java:51)
	at org.apache.shardingsphere.data.pipeline.postgresql.ingest.PostgreSQLWalDumper.dump(PostgreSQLWalDumper.java:91)
	at org.apache.shardingsphere.data.pipeline.postgresql.ingest.PostgreSQLWalDumper.doStart(PostgreSQLWalDumper.java:75)
	at org.apache.shardingsphere.data.pipeline.api.executor.AbstractLifecycleExecutor.start(AbstractLifecycleExecutor.java:41)
	at org.apache.shardingsphere.data.pipeline.core.task.IncrementalTask.doStart(IncrementalTask.java:85)
	at org.apache.shardingsphere.data.pipeline.api.executor.AbstractLifecycleExecutor.start(AbstractLifecycleExecutor.java:41)
	at org.apache.shardingsphere.data.pipeline.api.executor.AbstractLifecycleExecutor.run(AbstractLifecycleExecutor.java:61)
	at java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1640)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by sandynz** [comment]
Close now since it's fixed.
