### ISSUE TITLE
error by max_allowed_packet

### ISSUE THREAD

**Issue by VeejaLiu** [apache/shardingsphere#18100]
# Proxy 5.1.1

I have a long sql(>4M)
```
insert into XXX values (....)
```
When I directly import this SQL into the database, there is no problem.

But when i use proxy, it show:
```
(py3) ubuntu@ip-xx-xx-xx-xx:~$ mysql -h127.0.0.1 -P3307 -uroot -proot xxxx < xxxx.sql
ERROR at line 1: Packet for query is too large (4316145 > 4194304). You can change this value on the server by setting the max_allowed_packet' variable.
```
And I view my variable in proxy：
```
MySQL [xxxx]> show variables like 'max_allowed_packet';
+--------------------+----------+
| Variable_name      | Value    |
+--------------------+----------+
| max_allowed_packet | 4194304 |
+--------------------+----------+
1 row in set (0.005 sec)
```
Well, It is not enough.
Then I modify my resource config by:
```
ALTER RESOURCE database_team_default(
    URL="jdbc:mysql://xxxx",
    USER=root,
    PASSWORD="xxxx",
    PROPERTIES("maximumPoolSize"=10,"idleTimeout"="30000","maxAllowedPacket"="16777216")
);
```
then view variable in proxy again:
```
MySQL [xxxx]> show variables like 'max_allowed_packet';
+--------------------+----------+
| Variable_name      | Value    |
+--------------------+----------+
| max_allowed_packet | 16777216 |
+--------------------+----------+
1 row in set (0.005 sec)
```
I think it's good now.

But when i import data into proxy, the error still occurred.
```
(py3) ubuntu@ip-xx-xx-xx-xx:~$ mysql -h127.0.0.1 -P3307 -uroot -proot xxx < EMAIL_THREAD.sql
ERROR at line 1: Packet for query is too large (4316145 > 4194304). You can change this value on the server by setting the max_allowed_packet' variable.
```
And error in log:
```
[ERROR] 2022-05-31 09:58:20.276 [ShardingSphere-Command-8] o.a.s.p.f.c.CommandExecutorTask - Exception occur:
com.mysql.jdbc.PacketTooBigException: Packet for query is too large (4316145 > 4194304). You can change this value on the server by setting the max_allowed_packet' variable.
	at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3638)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2506)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2439)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:829)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:923)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:103)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at org.apache.shardingsphere.proxy.backend.communication.jdbc.executor.callback.impl.ProxyStatementExecutorCallback.execute(ProxyStatementExecutorCallback.java:40)
	at org.apache.shardingsphere.proxy.backend.communication.jdbc.executor.callback.ProxyJDBCExecutorCallback.executeSQL(ProxyJDBCExecutorCallback.java:73)
	at org.apache.shardingsphere.proxy.backend.communication.jdbc.executor.callback.ProxyJDBCExecutorCallback.executeSQL(ProxyJDBCExecutorCallback.java:66)
	at org.apache.shardingsphere.proxy.backend.communication.jdbc.executor.callback.ProxyJDBCExecutorCallback.executeSQL(ProxyJDBCExecutorCallback.java:44)
	at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutorCallback.execute(JDBCExecutorCallback.java:85)
	at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutorCallback.execute(JDBCExecutorCallback.java:64)
	at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.syncExecute(ExecutorEngine.java:101)
	at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.parallelExecute(ExecutorEngine.java:97)
	at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.execute(ExecutorEngine.java:82)
	at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutor.execute(JDBCExecutor.java:65)
	at org.apache.shardingsphere.proxy.backend.communication.jdbc.executor.ProxyJDBCExecutor.execute(ProxyJDBCExecutor.java:71)
	at org.apache.shardingsphere.proxy.backend.communication.ProxySQLExecutor.useDriverToExecute(ProxySQLExecutor.java:164)
	at org.apache.shardingsphere.proxy.backend.communication.ProxySQLExecutor.execute(ProxySQLExecutor.java:125)
	at org.apache.shardingsphere.proxy.backend.communication.ProxySQLExecutor.execute(ProxySQLExecutor.java:119)
	at org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:139)
	at org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:73)
	at org.apache.shardingsphere.proxy.backend.text.data.impl.SchemaAssignedDatabaseBackendHandler.execute(SchemaAssignedDatabaseBackendHandler.java:56)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:97)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:100)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by VeejaLiu** [comment]
I restarted the proxy and solved this problem. 

Now I just want to say a four letter word.















































Good....

**Comment by VeejaLiu** [comment]
So this also shows that it is useful to modify the resource attribute if there are related problems.
