### ISSUE TITLE
Initialization of bean failed; nested exception is java.lang.IllegalArgumentException: argument type mismatch

### ISSUE THREAD

**Issue by StupidManYI** [apache/shardingsphere#18192]
2022-06-06 16:08:04.245  INFO 10520 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'stringToNoneShardingStrategyConfigurationConverter' of type [org.apache.shardingsphere.spring.boot.converter.StringToNoneShardingStrategyConfigurationConverter] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
          2022-06-06 16:08:04.249  INFO 10520 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'spring.shardingsphere-org.apache.shardingsphere.spring.boot.prop.SpringBootPropertiesConfiguration' of type [org.apache.shardingsphere.spring.boot.prop.SpringBootPropertiesConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
          2022-06-06 16:08:04.395  WARN 10520 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration': Initialization of bean failed; nested exception is java.lang.IllegalArgumentException: argument type mismatch
          2022-06-06 16:08:04.400  INFO 10520 --- [           main] ConditionEvaluationReportLoggingListener : 
          
          Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
          2022-06-06 16:08:04.450 ERROR 10520 --- [           main] o.s.boot.SpringApplication               : Application run failed
          
          org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration': Initialization of bean failed; nested exception is java.lang.IllegalArgumentException: argument type mismatch
	          at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	          at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	          at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	          at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	          at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	          at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	          at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:409) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	          at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1341) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	          at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1181) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	          at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	          at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	          at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	          at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	          at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	          at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	          at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:229) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	          at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:723) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	          at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:536) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	          at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.11.RELEASE.jar:2.3.11.RELEASE]
	          at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755) [spring-boot-2.3.11.RELEASE.jar:2.3.11.RELEASE]
	          at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.3.11.RELEASE.jar:2.3.11.RELEASE]
	          at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402) [spring-boot-2.3.11.RELEASE.jar:2.3.11.RELEASE]
	          at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) [spring-boot-2.3.11.RELEASE.jar:2.3.11.RELEASE]
	          at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247) [spring-boot-2.3.11.RELEASE.jar:2.3.11.RELEASE]
	          at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236) [spring-boot-2.3.11.RELEASE.jar:2.3.11.RELEASE]
	          at com.echao.echao.application.app.AppApplication.main(AppApplication.java:21) [classes/:na]
          Caused by: java.lang.IllegalArgumentException: argument type mismatch
	          at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_332]
	          at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_332]
	          at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_332]
	          at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_332]
	          at org.apache.shardingsphere.infra.datasource.pool.creator.DataSourceReflection.setField(DataSourceReflection.java:141) ~[shardingsphere-infra-common-5.1.0.jar:5.1.0]
	          at org.apache.shardingsphere.infra.datasource.pool.creator.DataSourceReflection.lambda$setField$0(DataSourceReflection.java:120) ~[shardingsphere-infra-common-5.1.0.jar:5.1.0]
	          at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_332]
	          at org.apache.shardingsphere.infra.datasource.pool.creator.DataSourceReflection.setField(DataSourceReflection.java:120) ~[shardingsphere-infra-common-5.1.0.jar:5.1.0]
	          at org.apache.shardingsphere.infra.datasource.pool.creator.DataSourcePoolCreator.setConfiguredFields(DataSourcePoolCreator.java:86) ~[shardingsphere-infra-common-5.1.0.jar:5.1.0]
	          at org.apache.shardingsphere.infra.datasource.pool.creator.DataSourcePoolCreator.create(DataSourcePoolCreator.java:68) ~[shardingsphere-infra-common-5.1.0.jar:5.1.0]
	          at org.apache.shardingsphere.spring.boot.datasource.DataSourceMapSetter.getDataSource(DataSourceMapSetter.java:92) ~[shardingsphere-jdbc-spring-boot-starter-infra-5.1.0.jar:5.1.0]
	          at org.apache.shardingsphere.spring.boot.datasource.DataSourceMapSetter.getDataSourceMap(DataSourceMapSetter.java:65) ~[shardingsphere-jdbc-spring-boot-starter-infra-5.1.0.jar:5.1.0]
	          at org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration.setEnvironment(ShardingSphereAutoConfiguration.java:122) ~[shardingsphere-jdbc-core-spring-boot-starter-5.1.0.jar:5.1.0]
	          at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:108) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	          at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:100) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	          at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:415) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	          at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1791) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	          at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	          ... 25 common frames omitted

**Comment by StupidManYI** [comment]
when I add more druid  configuration  , the application will  report an error  (  'org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration': Initialization of bean failed; nested exception is java.lang.IllegalArgumentException: argument type mismatch
  at
)

        #the more druid configuration

        minIdle: 2
        # 初始化连接数
        initialSize: 1
        # 最大连接数
        maxTotal: 5
        maxWaitMillis: 200s
        connectionInitSqls: SET NAMES utf8mb4  #让 druid 支持特殊字符x


**my yaml config**



          spring:
            shardingsphere:
              datasource:
                #数据库名称（可以与数据库中的库名不一致）
                names: ds0
                ds0:
                  type: com.alibaba.druid.pool.DruidDataSource
                  driverClassName: com.mysql.cj.jdbc.Driver
                  url: jdbc:mysql://xxxx:8888/echao_basic1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true&tinyInt1isBit=false
                  username: root
                  password: "123456"
                  # 数据库连接池的最小连接数
                  #        minIdle: 2
                  #        # 初始化连接数
                  #        initialSize: 1
                  #        # 最大连接数
                  #        maxTotal: 5
                  #            maxWaitMillis: 200s
                  #        connectionInitSqls: SET NAMES utf8mb4  #让 druid 支持特殊字符
              rules:
                defaultDatabaseStrategy:
                  inline:
                    sharding-column: id
                    algorithm-expression: ds0
                  defaultKeyGenerateStrategy:
                    type: MyShardingKeyGenerator
                    column: id
          `

**Comment by StupidManYI** [comment]
But when I Remove the more druid configuration ,the application run successful

**Comment by linghengqian** [comment]
Not formatting markdown is really abstract... Have a minimal replica of the demo? The logs you give include ElasticSearch, Redis, and Spring Data integrations that aren't related to them.💨

**Comment by StupidManYI** [comment]
> 

sorry,I've changed that .

**Comment by StupidManYI** [comment]
I found that error might related to 

    connectionInitSqls: SET NAMES utf8mb4  #让 druid 支持特殊字符

when I remove this line , the application run successful

**Comment by linghengqian** [comment]
Alibaba druid does not have `maxTotal` and `maxWaitMillis` attributes, see https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8 . This has nothing to do with ShardingSphere.

**Comment by StupidManYI** [comment]
The error happened when I add this line 

`connectionInitSqls: SET NAMES utf8mb4  #让 druid 支持特殊字符`

this attributes is in the Alibaba druid properties.
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/50037510/172125500-d06159f5-1e88-4953-9d81-116115cf8b85.png">

You can remove the other extraneous druid attributes , but add the config which mentioned above , then you can see this error  

I use the mybatis-plus3 ss jdbc 5 druid 1.2.8

**Comment by linghengqian** [comment]
> The error happened when I added this line 
> 
> `connectionInitSqls: SET NAMES utf8mb4  #让 druid 支持特殊字符`

- Use MySQL JDBC-driven properties to perform SQL for specific data sources, rather than through global properties of the JDBC pool, which most likely did not complete initialization at execution time, see https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-configuration-properties.html. 

- If you need to execute this SQL at startup for all of ShardingSphere's data sources, you should use Spring's `ApplicationRunner` or `CommandLineRunner` to execute the corresponding SQL event, as does `javax.annotation.PostConstruct`. 

- A more reasonable means of verification is to execute this SQL directly against the configured `ShardingSphere Proxy 5.1.1`. I get the impression that this SQL is not supported because not all databases can be changed this way.

**Comment by StupidManYI** [comment]
thanks

**Comment by StupidManYI** [comment]
The final solution is change that line as follw :

`connectProperties: {connectionInitSqls: SET NAMES utf8mb4}`
