### ISSUE TITLE
App connection Shardingsphere-proxy fails 

### ISSUE THREAD

**Issue by connor1024** [apache/shardingsphere#18482]
Shardingsphere-proxy :5.1.2

mysql service version : 5.7.18  (select version();)

app error log:

022-06-21 12:36:33.837 +0800 [TID: N/A] [RMI TCP Connection(10)-172.30.16.1] ERROR userId: tenantId: com.zaxxer.hikari.pool.HikariPool:497 - HikariPool-1 - Error thrown while acquiring connection from data source
java.sql.SQLException: Could not map transaction isolation '1' to a valid JDBC level.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.ConnectionImpl.getTransactionIsolation(ConnectionImpl.java:1220)
	at com.zaxxer.hikari.pool.PoolBase.checkDefaultIsolation(PoolBase.java:479)
	at com.zaxxer.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:442)
	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:410)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:363)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:330)

I'm need a little help。 @TeslaCN

**Comment by terrymanu** [comment]
The error log is not come from ShardingSphere, please check your usage first

**Comment by connor1024** [comment]
> The error log is not come from your application, can you provide the error log from ShardingSphere-Proxy?

ShardingSphere-Proxy not error log,    but when  proxy 5.1.0 ,app connection that successful

**Comment by TeslaCN** [comment]
You may set the `proxy-mysql-default-version` in server.yaml

https://github.com/apache/shardingsphere/blob/db210de5b14e58a25808cab1d7587b090f503584/shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/resources/conf/server.yaml#L91

https://github.com/mysql/mysql-connector-j/blob/ad86f36e100e104cd926c6b81c8cab9565750116/src/com/mysql/jdbc/ConnectionImpl.java#L2972-L2995

**Comment by connor1024** [comment]
> You may set the `proxy-mysql-default-version` in server.yaml
> 
> https://github.com/apache/shardingsphere/blob/db210de5b14e58a25808cab1d7587b090f503584/shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/resources/conf/server.yaml#L91
> 
> https://github.com/mysql/mysql-connector-j/blob/ad86f36e100e104cd926c6b81c8cab9565750116/src/com/mysql/jdbc/ConnectionImpl.java#L2972-L2995

thanks, edit server.yaml    [proxy-mysql-default-version=【mysqlversion】]。
