### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/shardingsphere/mode/repository/cluster/ClusterPersistRepositoryConfiguration

### ISSUE THREAD

**Issue by THMAIL** [apache/shardingsphere#18533]
### Which version of ShardingSphere did you use?
v5.1.1 release bin

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Actual behavior
`C:\Users\233\Downloads\apache-shardingsphere-5.1.1-shardingsphere-proxy-bin\bin>start.bat
we find java version: java8, full_version=1.8.0_191
Starting the ShardingSphere-Proxy ...
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/shardingsphere/mode/repository/cluster/ClusterPersistRepositoryConfiguration
        at org.apache.shardingsphere.mode.manager.cluster.yaml.ClusterPersistRepositoryConfigurationYamlSwapper.swapToObject(ClusterPersistRepositoryConfigurationYamlSwapper.java:41)
        at org.apache.shardingsphere.mode.manager.cluster.yaml.ClusterPersistRepositoryConfigurationYamlSwapper.swapToObject(ClusterPersistRepositoryConfigurationYamlSwapper.java:27)
        at org.apache.shardingsphere.infra.yaml.config.swapper.mode.PersistRepositoryConfigurationYamlSwapperEngine.swapToObject(PersistRepositoryConfigurationYamlSwapperEngine.java:60)
        at org.apache.shardingsphere.infra.yaml.config.swapper.mode.ModeConfigurationYamlSwapper.swapToObject(ModeConfigurationYamlSwapper.java:44)
        at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.init(BootstrapInitializer.java:56)
        at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:47)
Caused by: java.lang.ClassNotFoundException: org.apache.shardingsphere.mode.repository.cluster.ClusterPersistRepositoryConfiguration
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 6 more`

**Comment by zjcnb** [comment]
@THMAIL Can you provide your `ShardingSphere-Proxy.zip`? And maybe you can try with `5.1.2`.

**Comment by terrymanu** [comment]
Did the binary tar download from official website? Can you use SHA512 to verify the integrity of package?

**Comment by terrymanu** [comment]
Closed because of no feedback for long time.
