### ISSUE TITLE
Insert into..select .. from tbl_2 throw NullPointerException in PgSQL

### ISSUE THREAD

**Issue by xwscut** [apache/shardingsphere#18648]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.1.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 
### Expected behavior
Insert into tbl_1(colum1_name,colum2_name) select colum1_name,colum2_name from tbl_2 
### Actual behavior

throw NullPointerException

### Reason analyze (If you can)
Caused by: java.lang.NullPointerException
	at org.apache.shardingsphere.sql.parser.postgresql.visitor.statement.impl.PostgreSQLStatementSQLVisitor.createInsertValuesSegments(PostgreSQLStatementSQLVisitor.java:665)
	at org.apache.shardingsphere.sql.parser.postgresql.visitor.statement.impl.PostgreSQLStatementSQLVisitor.visitInsertRest(PostgreSQLStatementSQLVisitor.java:635)
	at org.apache.shardingsphere.sql.parser.postgresql.visitor.statement.impl.PostgreSQLStatementSQLVisitor.visitInsertRest(PostgreSQLStatementSQLVisitor.java:182)
	at org.apache.shardingsphere.sql.parser.autogen.PostgreSQLStatementParser$InsertRestContext.accept(PostgreSQLStatementParser.java:3116)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.apache.shardingsphere.sql.parser.postgresql.visitor.statement.impl.PostgreSQLStatementSQLVisitor.visitInsert(PostgreSQLStatementSQLVisitor.java:594)
	at org.apache.shardingsphere.sql.parser.postgresql.visitor.statement.impl.PostgreSQLStatementSQLVisitor.visitInsert(PostgreSQLStatementSQLVisitor.java:182)
	at org.apache.shardingsphere.sql.parser.autogen.PostgreSQLStatementParser$InsertContext.accept(PostgreSQLStatementParser.java:2974)
	at org.apache.shardingsphere.sql.parser.api.SQLVisitorEngine.visit(SQLVisitorEngine.java:55)
	at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserExecutor.parse(SQLStatementParserExecutor.java:48)
	at org.apache.shardingsphere.infra.parser.cache.SQLStatementCacheLoader.load(SQLStatementCacheLoader.java:41)
	at org.apache.shardingsphere.infra.parser.cache.SQLStatementCacheLoader.load(SQLStatementCacheLoader.java:30)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
	... 27 more
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
![image](https://user-images.githubusercontent.com/11586135/176090343-0eaf3b68-11c6-4ea3-aab0-36ccef6b7f77.png)

**Comment by terrymanu** [comment]
Closed because of no feedback for long time.
