### ISSUE TITLE
The OracleParserStatementExample in the example executes an error

### ISSUE THREAD

**Issue by jiangML** [apache/shardingsphere#18680]
### Which version of ShardingSphere did you use?
 master
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 OracleParserStatementExample in the example 
### Expected behavior
run successfully
### Actual behavior
```
Exception in thread "main" org.apache.shardingsphere.sql.parser.exception.SQLParsingException: You have an error in your SQL syntax
	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.twoPhaseParse(SQLParserExecutor.java:65)
	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.parse(SQLParserExecutor.java:46)
	at org.apache.shardingsphere.sql.parser.api.SQLParserEngine.parse(SQLParserEngine.java:47)
	at org.apache.shardingsphere.example.parser.oracle.statement.OracleParserStatementExample.lambda$main$0(OracleParserStatementExample.java:58)
	at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
	at org.apache.shardingsphere.example.parser.oracle.statement.OracleParserStatementExample.main(OracleParserStatementExample.java:55)
```

### Reason analyze (If you can)
Question statement: "SELECT t.id, t.name, t.age FROM table1 AS t ORDER BY t.id DESC;"
Oracle table alias does not support "AS"

**Comment by terrymanu** [comment]
This bug is not for example, but oracle parser.
