### ISSUE TITLE
javax.net.ssl.SSLException occurred when add resource by  `DistSQL`

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#18792]
### Which version of ShardingSphere did you use?

`master`

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

`ShardingSphere-Proxy`

```
Sat Jul 02 23:40:15 CST 2022 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Sat Jul 02 23:40:15 CST 2022 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Sat Jul 02 23:40:15 CST 2022 WARN: Caught while disconnecting...

EXCEPTION STACK TRACE:



** BEGIN NESTED EXCEPTION ** 

javax.net.ssl.SSLException
MESSAGE: closing inbound before receiving peer's close_notify

STACKTRACE:

javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:751)
	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:730)
	at com.mysql.jdbc.MysqlIO.quit(MysqlIO.java:2249)
	at com.mysql.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:4232)
	at com.mysql.jdbc.ConnectionImpl.close(ConnectionImpl.java:1472)
	at com.mysql.jdbc.jdbc2.optional.MysqlPooledConnection.close(MysqlPooledConnection.java:183)
	at com.mysql.jdbc.jdbc2.optional.JDBC4MysqlXAConnection.close(JDBC4MysqlXAConnection.java:46)
	at com.atomikos.datasource.xa.jdbc.JdbcTransactionalResource.close(JdbcTransactionalResource.java:153)
	at com.atomikos.icatch.config.Configuration.removeAndCloseResources(Configuration.java:361)
	at com.atomikos.icatch.config.Configuration.shutdown(Configuration.java:336)
	at com.atomikos.icatch.config.Configuration.shutdown(Configuration.java:328)
	at com.atomikos.icatch.config.UserTransactionServiceImp.shutdown(UserTransactionServiceImp.java:85)
	at org.apache.shardingsphere.transaction.xa.atomikos.manager.AtomikosTransactionManagerProvider.close(AtomikosTransactionManagerProvider.java:67)
	at org.apache.shardingsphere.transaction.xa.XAShardingSphereTransactionManager.close(XAShardingSphereTransactionManager.java:124)
	at org.apache.shardingsphere.transaction.ShardingSphereTransactionManagerEngine.close(ShardingSphereTransactionManagerEngine.java:94)
	at org.apache.shardingsphere.transaction.rule.TransactionRule.closeEngine(TransactionRule.java:111)
	at org.apache.shardingsphere.transaction.rule.TransactionRule.addResource(TransactionRule.java:92)
	at org.apache.shardingsphere.mode.manager.ContextManager.lambda$refreshMetaDataContext$18(ContextManager.java:496)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.apache.shardingsphere.mode.manager.ContextManager.refreshMetaDataContext(ContextManager.java:496)
	at org.apache.shardingsphere.mode.manager.ContextManager.addResource(ContextManager.java:215)
	at org.apache.shardingsphere.proxy.backend.text.distsql.rdl.resource.AddResourceBackendHandler.execute(AddResourceBackendHandler.java:63)
	at org.apache.shardingsphere.proxy.backend.text.distsql.rdl.resource.AddResourceBackendHandler.execute(AddResourceBackendHandler.java:44)
	at org.apache.shardingsphere.proxy.backend.text.DatabaseRequiredBackendHandler.execute(DatabaseRequiredBackendHandler.java:51)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:99)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:108)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)


** END NESTED EXCEPTION **


Sat Jul 02 23:40:15 CST 2022 WARN: Caught while disconnecting...

EXCEPTION STACK TRACE:



** BEGIN NESTED EXCEPTION ** 

javax.net.ssl.SSLException
MESSAGE: closing inbound before receiving peer's close_notify

STACKTRACE:

javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:751)
	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:730)
	at com.mysql.jdbc.MysqlIO.quit(MysqlIO.java:2249)
	at com.mysql.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:4232)
	at com.mysql.jdbc.ConnectionImpl.close(ConnectionImpl.java:1472)
	at com.mysql.jdbc.jdbc2.optional.MysqlPooledConnection.close(MysqlPooledConnection.java:183)
	at com.mysql.jdbc.jdbc2.optional.JDBC4MysqlXAConnection.close(JDBC4MysqlXAConnection.java:46)
	at com.atomikos.datasource.xa.jdbc.JdbcTransactionalResource.close(JdbcTransactionalResource.java:153)
	at com.atomikos.icatch.config.Configuration.removeAndCloseResources(Configuration.java:361)
	at com.atomikos.icatch.config.Configuration.shutdown(Configuration.java:336)
	at com.atomikos.icatch.config.Configuration.shutdown(Configuration.java:328)
	at com.atomikos.icatch.config.UserTransactionServiceImp.shutdown(UserTransactionServiceImp.java:85)
	at org.apache.shardingsphere.transaction.xa.atomikos.manager.AtomikosTransactionManagerProvider.close(AtomikosTransactionManagerProvider.java:67)
	at org.apache.shardingsphere.transaction.xa.XAShardingSphereTransactionManager.close(XAShardingSphereTransactionManager.java:124)
	at org.apache.shardingsphere.transaction.ShardingSphereTransactionManagerEngine.close(ShardingSphereTransactionManagerEngine.java:94)
	at org.apache.shardingsphere.transaction.rule.TransactionRule.closeEngine(TransactionRule.java:111)
	at org.apache.shardingsphere.transaction.rule.TransactionRule.addResource(TransactionRule.java:92)
	at org.apache.shardingsphere.mode.manager.ContextManager.lambda$refreshMetaDataContext$18(ContextManager.java:496)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.apache.shardingsphere.mode.manager.ContextManager.refreshMetaDataContext(ContextManager.java:496)
	at org.apache.shardingsphere.mode.manager.ContextManager.addResource(ContextManager.java:215)
	at org.apache.shardingsphere.proxy.backend.text.distsql.rdl.resource.AddResourceBackendHandler.execute(AddResourceBackendHandler.java:63)
	at org.apache.shardingsphere.proxy.backend.text.distsql.rdl.resource.AddResourceBackendHandler.execute(AddResourceBackendHandler.java:44)
	at org.apache.shardingsphere.proxy.backend.text.DatabaseRequiredBackendHandler.execute(DatabaseRequiredBackendHandler.java:51)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:99)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:108)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)


** END NESTED EXCEPTION **
```

1. 
`CREATE DATABASE sharding_db;`
2. 
```
ADD RESOURCE resource_0 (
    HOST=127.0.0.1,
    PORT=3306,
    DB=ds0,
    USER=root,
    PASSWORD=123456
),resource_1 (
    HOST=127.0.0.1,
    PORT=3306,
    DB=ds1,
    USER=root,
    PASSWORD=123456
);
```

`server.yaml : `

```
mode:
  type: Cluster
  repository:
    type: ZooKeeper
    props:
      namespace: governance_ds
      server-lists: localhost:2181
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
  overwrite: false

rules:
  - !AUTHORITY
    users:
      - root@%:root
      - sharding@:sharding
    provider:
      type: ALL_PERMITTED
```

**Comment by zjcnb** [comment]
I can't reproduce it, so i close it.
