### ISSUE TITLE
NumberFormatException occurred when use `MySQL.NORMAL_REPLICATION`

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#18914]
Master branch [https://github.com/apache/shardingsphere/commit/b01c9b3bf5bd44e651649b1e1535884bb6f395f9](commitid)

Use db-discovery feature - `MySQL.NORMAL_REPLICATION`

Not set `delay-milliseconds-threshold` in configuration

```
Exception in thread "main" java.lang.NumberFormatException: null
	at java.base/java.lang.Long.parseLong(Long.java:655)
	at java.base/java.lang.Long.parseLong(Long.java:817)
	at org.apache.shardingsphere.dbdiscovery.mysql.type.MySQLNormalReplicationDatabaseDiscoveryProviderAlgorithm.loadReplicaStatus(MySQLNormalReplicationDatabaseDiscoveryProviderAlgorithm.java:126)
	at org.apache.shardingsphere.dbdiscovery.algorithm.DatabaseDiscoveryEngine.loadReplicaStatus(DatabaseDiscoveryEngine.java:128)
	at org.apache.shardingsphere.dbdiscovery.algorithm.DatabaseDiscoveryEngine.postReplicaDataSourceDisabledEvent(DatabaseDiscoveryEngine.java:107)
	at org.apache.shardingsphere.dbdiscovery.algorithm.DatabaseDiscoveryEngine.changePrimaryDataSource(DatabaseDiscoveryEngine.java:77)
	at org.apache.shardingsphere.dbdiscovery.rule.DatabaseDiscoveryRule.findPrimaryReplicaRelationship(DatabaseDiscoveryRule.java:122)
	at org.apache.shardingsphere.dbdiscovery.rule.DatabaseDiscoveryRule.<init>(DatabaseDiscoveryRule.java:82)
	at org.apache.shardingsphere.dbdiscovery.rule.builder.DatabaseDiscoveryRuleBuilder.build(DatabaseDiscoveryRuleBuilder.java:47)
	at org.apache.shardingsphere.dbdiscovery.rule.builder.DatabaseDiscoveryRuleBuilder.build(DatabaseDiscoveryRuleBuilder.java:36)
	at org.apache.shardingsphere.infra.rule.builder.database.DatabaseRulesBuilder.build(DatabaseRulesBuilder.java:56)
	at org.apache.shardingsphere.infra.metadata.database.ShardingSphereDatabase.create(ShardingSphereDatabase.java:75)
	at org.apache.shardingsphere.infra.metadata.database.ShardingSphereDatabasesFactory.createGenericDatabases(ShardingSphereDatabasesFactory.java:79)
	at org.apache.shardingsphere.infra.metadata.database.ShardingSphereDatabasesFactory.create(ShardingSphereDatabasesFactory.java:67)
	at org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.buildMetaDataContexts(ClusterContextManagerBuilder.java:90)
	at org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.build(ClusterContextManagerBuilder.java:69)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.createContextManager(BootstrapInitializer.java:66)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.init(BootstrapInitializer.java:55)
	at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:50)
```

**Comment by sgunadhya** [comment]
What should be the behavior when the value is not set?

**Comment by strongduanmu** [comment]
Hi @zjcnb  , could we finish this issue in `5.1.3`?

**Comment by strongduanmu** [comment]
Hi, could we finish this issue in 5.2.1?

**Comment by TeslaCN** [comment]
@zhaojinchao95 
Is there any progress?

**Comment by zhaojinchao95** [comment]
> @zhaojinchao95 Is there any progress?

Move to 5.3.1 milestone.

**Comment by sandynz** [comment]
Hi @zhaojinchao95 , could it be done on 5.3.1?

**Comment by zhaojinchao95** [comment]
> Move to 5.3.1 milestone.

Move to 5.3.2 milestone.
