### ISSUE TITLE
Scaling increment task will failed when using openGauss with the table have null column value  

### ISSUE THREAD

**Issue by azexcy** [apache/shardingsphere#19070]
## Bug Report

When using openGauss database, scalling increment task will falied, when the insert row have null value of number(eg smallint, bytea)

create table sql:
```
CREATE TABLE "t_order_0" (
  "id" int8 NOT NULL,
  "order_id" int4 NOT NULL,
  "user_id" int4 NOT NULL,
  "status" varchar(50) COLLATE "pg_catalog"."default",
  "t_int2" int2,
  "t_numeric" numeric(10,2),
  "t_bool" bool,
  "t_bytea" bytea,
  "t_char" char(10) COLLATE "pg_catalog"."default",
  "t_varchar" varchar(128) COLLATE "pg_catalog"."default",
  "t_float" float8,
  "t_double" float4,
  "t_json" json,
  "t_jsonb" jsonb,
  "t_text" text COLLATE "pg_catalog"."default",
  "t_date" date,
  "t_time" time(6),
  "t_timestmap" timestamp(6),
  "t_timestamptz" timestamptz(6),
  CONSTRAINT "t_order_0_pkey" PRIMARY KEY ("id")
)
;
```

```
[ERROR] 2022-07-12 19:28:22.378 [ShardingSphere-Scaling-Incremental-0130317c30317c3054317c7368617264696e675f6462-4] o.a.s.d.p.s.r.RuleAlteredJobScheduler - Incremental task execute failed.
java.lang.NumberFormatException: For input string: "null"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Short.parseShort(Short.java:118)
	at java.lang.Short.parseShort(Short.java:144)
	at org.apache.shardingsphere.data.pipeline.opengauss.ingest.wal.decode.MppdbDecodingPlugin.readColumnData(MppdbDecodingPlugin.java:149)
	at org.apache.shardingsphere.data.pipeline.opengauss.ingest.wal.decode.MppdbDecodingPlugin.getColumnDataFromMppDataEvent(MppdbDecodingPlugin.java:127)
	at org.apache.shardingsphere.data.pipeline.opengauss.ingest.wal.decode.MppdbDecodingPlugin.readWriteRowEvent(MppdbDecodingPlugin.java:108)
	at org.apache.shardingsphere.data.pipeline.opengauss.ingest.wal.decode.MppdbDecodingPlugin.readTableEvent(MppdbDecodingPlugin.java:89)
	at org.apache.shardingsphere.data.pipeline.opengauss.ingest.wal.decode.MppdbDecodingPlugin.decode(MppdbDecodingPlugin.java:57)
	at org.apache.shardingsphere.data.pipeline.opengauss.ingest.OpenGaussWalDumper.dump(OpenGaussWalDumper.java:88)
	at org.apache.shardingsphere.data.pipeline.opengauss.ingest.OpenGaussWalDumper.doStart(OpenGaussWalDumper.java:74)
	at org.apache.shardingsphere.data.pipeline.api.executor.AbstractLifecycleExecutor.start(AbstractLifecycleExecutor.java:41)
	at org.apache.shardingsphere.data.pipeline.core.task.IncrementalTask.doStart(IncrementalTask.java:85)
	at org.apache.shardingsphere.data.pipeline.api.executor.AbstractLifecycleExecutor.start(AbstractLifecycleExecutor.java:41)
	at org.apache.shardingsphere.data.pipeline.api.executor.AbstractLifecycleExecutor.run(AbstractLifecycleExecutor.java:61)
	at java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1640)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/101622833/178479678-8c1a1aac-4ccf-42ff-8388-8565a1f8b50f.png">

### Which version of ShardingSphere did you use?

master 844c2d3f8691dee13e77a59180f123a6383a8939

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

Proxy

### Expected behavior

scaling start increment task 

### Actual behavior

increment task falied

### Reason analyze (If you can)

Not handle null value correctly.

**Comment by azexcy** [comment]
I will follow this

**Comment by azexcy** [comment]
the logic replication convert data like this
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/101622833/178481395-37e2f5f5-ceaf-4e7f-9ddf-16b5f7c744d5.png">
