### ISSUE TITLE
Package build failed

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#19396]
master branch https://github.com/apache/shardingsphere/commit/d5b6006bec3aaee933895852a817874c14793660

```
22:31:11.030 [main] DEBUG org.testcontainers.dockerclient.DockerClientProviderStrategy - UnixSocketClientProviderStrategy: failed with exception TimeoutException (Timeout waiting for result with exception). Root cause IOException (native connect() failed : Connection refused)
22:31:11.030 [main] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy - Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
22:31:11.030 [main] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy -     UnixSocketClientProviderStrategy: failed with exception TimeoutException (Timeout waiting for result with exception). Root cause IOException (native connect() failed : Connection refused)
22:31:11.030 [main] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy -     UnixSocketClientProviderStrategy: failed with exception TimeoutException (Timeout waiting for result with exception). Root cause IOException (native connect() failed : Connection refused)
22:31:11.030 [main] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy - As no valid configuration was found, execution cannot continue
[ERROR] Tests run: 10, Failures: 0, Errors: 10, Skipped: 0, Time elapsed: 60.694 s <<< FAILURE! - in org.apache.shardingsphere.integration.transaction.engine.postgresql.PostgreSQLProxyTransactionIT
[ERROR] assertLocalTransaction[PostgreSQL -> postgres:10-alpine -> PostgresSQLAutoCommitTestCase](org.apache.shardingsphere.integration.transaction.engine.postgresql.PostgreSQLProxyTransactionIT)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
        at org.apache.shardingsphere.integration.transaction.engine.postgresql.PostgreSQLProxyTransactionIT.<init>(PostgreSQLProxyTransactionIT.java:44)

[ERROR] assertDistributedTransaction[PostgreSQL -> postgres:10-alpine -> PostgresSQLAutoCommitTestCase](org.apache.shardingsphere.integration.transaction.engine.postgresql.PostgreSQLProxyTransactionIT)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
        at org.apache.shardingsphere.integration.transaction.engine.postgresql.PostgreSQLProxyTransactionIT.<init>(PostgreSQLProxyTransactionIT.java:44)

[ERROR] assertLocalTransaction[PostgreSQL -> postgres:10-alpine -> PostgreSQLSavePointTestCase](org.apache.shardingsphere.integration.transaction.engine.postgresql.PostgreSQLProxyTransactionIT)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
        at org.apache.shardingsphere.integration.transaction.engine.postgresql.PostgreSQLProxyTransactionIT.<init>(PostgreSQLProxyTransactionIT.java:44)

[ERROR] assertDistributedTransaction[PostgreSQL -> postgres:10-alpine -> PostgreSQLSavePointTestCase](org.apache.shardingsphere.integration.transaction.engine.postgresql.PostgreSQLProxyTransactionIT)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
        at org.apache.shardingsphere.integration.transaction.engine.postgresql.PostgreSQLProxyTransactionIT.<init>(PostgreSQLProxyTransactionIT.java:44)

[ERROR] assertLocalTransaction[PostgreSQL -> postgres:10-alpine -> MultiTableCommitAndRollbackTestCase](org.apache.shardingsphere.integration.transaction.engine.postgresql.PostgreSQLProxyTransactionIT)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
        at org.apache.shardingsphere.integration.transaction.engine.postgresql.PostgreSQLProxyTransactionIT.<init>(PostgreSQLProxyTransactionIT.java:44)

[ERROR] assertDistributedTransaction[PostgreSQL -> postgres:10-alpine -> MultiTableCommitAndRollbackTestCase](org.apache.shardingsphere.integration.transaction.engine.postgresql.PostgreSQLProxyTransactionIT)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
        at org.apache.shardingsphere.integration.transaction.engine.postgresql.PostgreSQLProxyTransactionIT.<init>(PostgreSQLProxyTransactionIT.java:44)

[ERROR] assertLocalTransaction[PostgreSQL -> postgres:10-alpine -> SingleTableCommitAndRollbackTestCase](org.apache.shardingsphere.integration.transaction.engine.postgresql.PostgreSQLProxyTransactionIT)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
        at org.apache.shardingsphere.integration.transaction.engine.postgresql.PostgreSQLProxyTransactionIT.<init>(PostgreSQLProxyTransactionIT.java:44)

[ERROR] assertDistributedTransaction[PostgreSQL -> postgres:10-alpine -> SingleTableCommitAndRollbackTestCase](org.apache.shardingsphere.integration.transaction.engine.postgresql.PostgreSQLProxyTransactionIT)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
        at org.apache.shardingsphere.integration.transaction.engine.postgresql.PostgreSQLProxyTransactionIT.<init>(PostgreSQLProxyTransactionIT.java:44)

[ERROR] assertLocalTransaction[PostgreSQL -> postgres:10-alpine -> ClassicTransferTestCase](org.apache.shardingsphere.integration.transaction.engine.postgresql.PostgreSQLProxyTransactionIT)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
        at org.apache.shardingsphere.integration.transaction.engine.postgresql.PostgreSQLProxyTransactionIT.<init>(PostgreSQLProxyTransactionIT.java:44)

[ERROR] assertDistributedTransaction[PostgreSQL -> postgres:10-alpine -> ClassicTransferTestCase](org.apache.shardingsphere.integration.transaction.engine.postgresql.PostgreSQLProxyTransactionIT)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
        at org.apache.shardingsphere.integration.transaction.engine.postgresql.PostgreSQLProxyTransactionIT.<init>(PostgreSQLProxyTransactionIT.java:44)

[INFO] Running org.apache.shardingsphere.integration.transaction.engine.opengauss.OpenGaussProxyTransactionIT
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.apache.shardingsphere.integration.transaction.engine.opengauss.OpenGaussProxyTransactionIT
[INFO] Running org.apache.shardingsphere.integration.transaction.engine.mysql.MySQLProxyTransactionIT
22:31:11.052 [main] INFO org.apache.shardingsphere.integration.transaction.engine.base.BaseITCase - Collect transaction test case, need to run cases don't contain this, skip: org.apache.shardingsphere.integration.transaction.cases.readonly.SetReadOnlyTestCase.
22:31:11.053 [main] INFO org.apache.shardingsphere.integration.transaction.engine.base.BaseITCase - Collect transaction test case, dbType is not matched, skip: org.apache.shardingsphere.integration.transaction.cases.autocommit.PostgresSQLAutoCommitTestCase.
22:31:11.053 [main] INFO org.apache.shardingsphere.integration.transaction.engine.base.BaseITCase - Collect transaction test case, need to run cases don't contain this, skip: org.apache.shardingsphere.integration.transaction.cases.autocommit.MySQLAutoCommitTestCase.
22:31:11.053 [main] INFO org.apache.shardingsphere.integration.transaction.engine.base.BaseITCase - Collect transaction test case, need to run cases don't contain this, skip: org.apache.shardingsphere.integration.transaction.cases.savepoint.OpenGaussSavePointTestCase.
22:31:11.053 [main] INFO org.apache.shardingsphere.integration.transaction.engine.base.BaseITCase - Collect transaction test case, need to run cases don't contain this, skip: org.apache.shardingsphere.integration.transaction.cases.savepoint.BaseSavePointTestCase.
22:31:11.053 [main] INFO org.apache.shardingsphere.integration.transaction.engine.base.BaseITCase - Collect transaction test case, dbType is not matched, skip: org.apache.shardingsphere.integration.transaction.cases.savepoint.PostgreSQLSavePointTestCase.
22:31:11.053 [main] INFO org.apache.shardingsphere.integration.transaction.engine.base.BaseITCase - Collect transaction test case, need to run cases don't contain this, skip: org.apache.shardingsphere.integration.transaction.cases.base.BaseTransactionTestCase.
[ERROR] Tests run: 10, Failures: 0, Errors: 10, Skipped: 0, Time elapsed: 0.002 s <<< FAILURE! - in org.apache.shardingsphere.integration.transaction.engine.mysql.MySQLProxyTransactionIT
[ERROR] assertLocalTransaction[MySQL -> mysql/mysql-server:5.7 -> MySQLSetReadOnlyTestCase](org.apache.shardingsphere.integration.transaction.engine.mysql.MySQLProxyTransactionIT)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
        at org.apache.shardingsphere.integration.transaction.engine.mysql.MySQLProxyTransactionIT.<init>(MySQLProxyTransactionIT.java:44)

[ERROR] assertDistributedTransaction[MySQL -> mysql/mysql-server:5.7 -> MySQLSetReadOnlyTestCase](org.apache.shardingsphere.integration.transaction.engine.mysql.MySQLProxyTransactionIT)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
        at org.apache.shardingsphere.integration.transaction.engine.mysql.MySQLProxyTransactionIT.<init>(MySQLProxyTransactionIT.java:44)

[ERROR] assertLocalTransaction[MySQL -> mysql/mysql-server:5.7 -> MySQLSavePointTestCase](org.apache.shardingsphere.integration.transaction.engine.mysql.MySQLProxyTransactionIT)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
        at org.apache.shardingsphere.integration.transaction.engine.mysql.MySQLProxyTransactionIT.<init>(MySQLProxyTransactionIT.java:44)

[ERROR] assertDistributedTransaction[MySQL -> mysql/mysql-server:5.7 -> MySQLSavePointTestCase](org.apache.shardingsphere.integration.transaction.engine.mysql.MySQLProxyTransactionIT)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
        at org.apache.shardingsphere.integration.transaction.engine.mysql.MySQLProxyTransactionIT.<init>(MySQLProxyTransactionIT.java:44)

[ERROR] assertLocalTransaction[MySQL -> mysql/mysql-server:5.7 -> MultiTableCommitAndRollbackTestCase](org.apache.shardingsphere.integration.transaction.engine.mysql.MySQLProxyTransactionIT)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
        at org.apache.shardingsphere.integration.transaction.engine.mysql.MySQLProxyTransactionIT.<init>(MySQLProxyTransactionIT.java:44)

[ERROR] assertDistributedTransaction[MySQL -> mysql/mysql-server:5.7 -> MultiTableCommitAndRollbackTestCase](org.apache.shardingsphere.integration.transaction.engine.mysql.MySQLProxyTransactionIT)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
        at org.apache.shardingsphere.integration.transaction.engine.mysql.MySQLProxyTransactionIT.<init>(MySQLProxyTransactionIT.java:44)

[ERROR] assertLocalTransaction[MySQL -> mysql/mysql-server:5.7 -> SingleTableCommitAndRollbackTestCase](org.apache.shardingsphere.integration.transaction.engine.mysql.MySQLProxyTransactionIT)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
        at org.apache.shardingsphere.integration.transaction.engine.mysql.MySQLProxyTransactionIT.<init>(MySQLProxyTransactionIT.java:44)

[ERROR] assertDistributedTransaction[MySQL -> mysql/mysql-server:5.7 -> SingleTableCommitAndRollbackTestCase](org.apache.shardingsphere.integration.transaction.engine.mysql.MySQLProxyTransactionIT)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
        at org.apache.shardingsphere.integration.transaction.engine.mysql.MySQLProxyTransactionIT.<init>(MySQLProxyTransactionIT.java:44)

[ERROR] assertLocalTransaction[MySQL -> mysql/mysql-server:5.7 -> ClassicTransferTestCase](org.apache.shardingsphere.integration.transaction.engine.mysql.MySQLProxyTransactionIT)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
        at org.apache.shardingsphere.integration.transaction.engine.mysql.MySQLProxyTransactionIT.<init>(MySQLProxyTransactionIT.java:44)

[ERROR] assertDistributedTransaction[MySQL -> mysql/mysql-server:5.7 -> ClassicTransferTestCase](org.apache.shardingsphere.integration.transaction.engine.mysql.MySQLProxyTransactionIT)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
        at org.apache.shardingsphere.integration.transaction.engine.mysql.MySQLProxyTransactionIT.<init>(MySQLProxyTransactionIT.java:44)

22:31:11.081 [ducttape-1] DEBUG org.testcontainers.dockerclient.DockerClientProviderStrategy - Pinging docker daemon...
22:31:11.081 [ducttape-1] DEBUG org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: 
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   MySQLProxyTransactionIT.<init>:44->BaseTransactionITCase.<init>:43->BaseITCase.<init>:102->BaseITCase.createAndStartComposedContainer:200 » IllegalState
[ERROR]   MySQLProxyTransactionIT.<init>:44->BaseTransactionITCase.<init>:43->BaseITCase.<init>:102->BaseITCase.createAndStartComposedContainer:200 » IllegalState
[ERROR]   MySQLProxyTransactionIT.<init>:44->BaseTransactionITCase.<init>:43->BaseITCase.<init>:102->BaseITCase.createAndStartComposedContainer:200 » IllegalState
[ERROR]   MySQLProxyTransactionIT.<init>:44->BaseTransactionITCase.<init>:43->BaseITCase.<init>:102->BaseITCase.createAndStartComposedContainer:200 » IllegalState
[ERROR]   MySQLProxyTransactionIT.<init>:44->BaseTransactionITCase.<init>:43->BaseITCase.<init>:102->BaseITCase.createAndStartComposedContainer:200 » IllegalState
[ERROR]   MySQLProxyTransactionIT.<init>:44->BaseTransactionITCase.<init>:43->BaseITCase.<init>:102->BaseITCase.createAndStartComposedContainer:200 » IllegalState
[ERROR]   MySQLProxyTransactionIT.<init>:44->BaseTransactionITCase.<init>:43->BaseITCase.<init>:102->BaseITCase.createAndStartComposedContainer:200 » IllegalState
[ERROR]   MySQLProxyTransactionIT.<init>:44->BaseTransactionITCase.<init>:43->BaseITCase.<init>:102->BaseITCase.createAndStartComposedContainer:200 » IllegalState
[ERROR]   MySQLProxyTransactionIT.<init>:44->BaseTransactionITCase.<init>:43->BaseITCase.<init>:102->BaseITCase.createAndStartComposedContainer:200 » IllegalState
[ERROR]   MySQLProxyTransactionIT.<init>:44->BaseTransactionITCase.<init>:43->BaseITCase.<init>:102->BaseITCase.createAndStartComposedContainer:200 » IllegalState
[ERROR]   PostgreSQLProxyTransactionIT.<init>:44->BaseTransactionITCase.<init>:43->BaseITCase.<init>:102->BaseITCase.createAndStartComposedContainer:200 » IllegalState
[ERROR]   PostgreSQLProxyTransactionIT.<init>:44->BaseTransactionITCase.<init>:43->BaseITCase.<init>:102->BaseITCase.createAndStartComposedContainer:200 » IllegalState
[ERROR]   PostgreSQLProxyTransactionIT.<init>:44->BaseTransactionITCase.<init>:43->BaseITCase.<init>:102->BaseITCase.createAndStartComposedContainer:200 » IllegalState
[ERROR]   PostgreSQLProxyTransactionIT.<init>:44->BaseTransactionITCase.<init>:43->BaseITCase.<init>:102->BaseITCase.createAndStartComposedContainer:200 » IllegalState
[ERROR]   PostgreSQLProxyTransactionIT.<init>:44->BaseTransactionITCase.<init>:43->BaseITCase.<init>:102->BaseITCase.createAndStartComposedContainer:200 » IllegalState
[ERROR]   PostgreSQLProxyTransactionIT.<init>:44->BaseTransactionITCase.<init>:43->BaseITCase.<init>:102->BaseITCase.createAndStartComposedContainer:200 » IllegalState
[ERROR]   PostgreSQLProxyTransactionIT.<init>:44->BaseTransactionITCase.<init>:43->BaseITCase.<init>:102->BaseITCase.createAndStartComposedContainer:200 » IllegalState
[ERROR]   PostgreSQLProxyTransactionIT.<init>:44->BaseTransactionITCase.<init>:43->BaseITCase.<init>:102->BaseITCase.createAndStartComposedContainer:200 » IllegalState
[ERROR]   PostgreSQLProxyTransactionIT.<init>:44->BaseTransactionITCase.<init>:43->BaseITCase.<init>:102->BaseITCase.createAndStartComposedContainer:200 » IllegalState
[ERROR]   PostgreSQLProxyTransactionIT.<init>:44->BaseTransactionITCase.<init>:43->BaseITCase.<init>:102->BaseITCase.createAndStartComposedContainer:200 » IllegalState

```

**Comment by FlyingZC** [comment]
I will fix it.

**Comment by FlyingZC** [comment]
The transaction integration test is configured to start the docker container, so if the docker is not started locally, an error will be reported. I will now remove this default configuration and the problem will be solved.
