### ISSUE TITLE
Why do `server-lists` have to use `http://` Schema?

### ISSUE THREAD

**Issue by pengdafu** [apache/shardingsphere#19443]
## Question
I tried to use cluster mode and use ETCD as the registry. 
But I get an error using the following configuration.

configuaration:

```yaml
mode:
  type: Cluster
  repository:
    type: Etcd
    props:
      namespace: /shardingproxy
      server-lists: localhost:2379
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
  overwrite: false
```

err log:
```shell
[WARN ] 2022-07-21 19:39:09.943 [grpc-default-executor-0] i.e.jetcd.resolver.SmartNameResolver - Error wile getting list of servers
io.etcd.jetcd.common.exception.EtcdException: Unable to resolve endpoints [localhost:2379]
	at io.etcd.jetcd.common.exception.EtcdExceptionFactory.newEtcdException(EtcdExceptionFactory.java:30)
	at io.etcd.jetcd.resolver.SmartNameResolver.doResolve(SmartNameResolver.java:137)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
七月 21, 2022 7:39:09 下午 io.grpc.internal.ManagedChannelImpl$NameResolverListener handleErrorInSyncContext
警告: [Channel<1>: (etcd)] Failed to resolve name. status=Status{code=NOT_FOUND, description=null, cause=null}
```

Unless I use the following configuration to boot properly.
```yaml
mode:
  type: Cluster
  repository:
    type: Etcd
    props:
      namespace: /shardingproxy
      server-lists: http://localhost:2379
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
  overwrite: false
```

**Comment by zjcnb** [comment]
@pengdafu `http://localhost:2379` Is this `etcd` requirement?
