### ISSUE TITLE
[SQL Parse] This version of ShardingSphere-Proxy doesn't yet support this SQL. 

### ISSUE THREAD

**Issue by mingyifei** [apache/shardingsphere#19465]
scene：

Client execute SQL throw `java.sql.SQLSyntaxErrorException: This version of ShardingSphere-Proxy doesn't yet support this SQL. 'You have an error in your SQL syntax'
`

version: master、sharding-proxy

rule config：no configuration.

server config: basic configuration.

client SQL：
`SELECT
	a.id,
	a.job_number,
	a.account,
	a.employ_num,
	a.nickname,
	a.realname,
	a.last_login_ip,
	a.last_login_time,
	a.login_count,
	a.on_job_status,
	a.phone_num,
	a.post,
	a.rank,
	a.email,
	a.create_time,
	a.creator,
	a.update_time,
	a.updator,
	a.deleted,
	a.ding_id,
	a.superior_id,
	a.version,
	a.feishu_id 
FROM
	sys_user a 
WHERE
	a.deleted = 'N' 
ORDER BY
	a.update_time DESC,
	a.id DESC 
	LIMIT 0,
	9999`

Delete some conditions and still throw [This version of ShardingSphere-Proxy doesn't]
for example：

`SELECT
	a.id,
	a.job_number,
	a.account,
	a.employ_num,
	a.nickname,
	a.realname,
	a.last_login_ip,
	a.last_login_time,
	a.login_count,
	a.on_job_status,
	a.phone_num,
	a.post,
	a.rank,
	a.email,
	a.create_time,
	a.creator,
	a.update_time,
	a.updator,
	a.deleted,
	a.ding_id,
	a.superior_id,
	a.version,
	a.feishu_id 
FROM
	sys_user a 
WHERE
	a.deleted = 'N'`

sharding-proxy exception：

`org.antlr.v4.runtime.misc.ParseCancellationException: null
	at org.antlr.v4.runtime.BailErrorStrategy.recover(BailErrorStrategy.java:51)
	at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser.select(MySQLStatementParser.java:20922)
	at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser.execute(MySQLStatementParser.java:1128)
	at org.apache.shardingsphere.sql.parser.mysql.parser.MySQLParser.parse(MySQLParser.java:38)
	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.twoPhaseParse(SQLParserExecutor.java:65)
	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.parse(SQLParserExecutor.java:48)
	at org.apache.shardingsphere.sql.parser.api.SQLParserEngine.parse(SQLParserEngine.java:47)
	at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserExecutor.parse(SQLStatementParserExecutor.java:48)
	at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserEngine.parse(SQLStatementParserEngine.java:47)
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine.parse$original$b9bZ3dOV(ShardingSphereSQLParserEngine.java:58)
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine.parse$original$b9bZ3dOV$accessor$4qbnS5hI(ShardingSphereSQLParserEngine.java)
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine$auxiliary$97J7qXmI.call(Unknown Source)
	at org.apache.shardingsphere.agent.core.plugin.interceptor.InstanceMethodAroundInterceptor.intercept(InstanceMethodAroundInterceptor.java:74)
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine.parse$original$mX8jvj0b(ShardingSphereSQLParserEngine.java)
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine.parse$original$mX8jvj0b$accessor$BaazUl4v(ShardingSphereSQLParserEngine.java)
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine$auxiliary$G3CQKZtu.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine.parse(ShardingSphereSQLParserEngine.java)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.parseSql(MySQLComQueryPacketExecutor.java:83)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.<init>(MySQLComQueryPacketExecutor.java:71)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecutorFactory.newInstance(MySQLCommandExecutorFactory.java:75)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandExecutor(MySQLCommandExecuteEngine.java:61)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:107)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run$original$fG8dbaSL(CommandExecutorTask.java:78)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run$original$fG8dbaSL$accessor$yHugbcBG(CommandExecutorTask.java)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask$auxiliary$zRrNxTQ2.call(Unknown Source)
	at org.apache.shardingsphere.agent.core.plugin.interceptor.InstanceMethodAroundInterceptor.intercept(InstanceMethodAroundInterceptor.java:74)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run$original$tyJ2TvVs(CommandExecutorTask.java)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run$original$tyJ2TvVs$accessor$fcLhao5I(CommandExecutorTask.java)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask$auxiliary$MqYRhs4w.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.antlr.v4.runtime.NoViableAltException: null
	at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:2026)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:467)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:393)
	at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser.select(MySQLStatementParser.java:20885)
	... 33 common frames omitted
[ERROR] 2022-07-22 14:16:00.081 [ShardingSphere-Command-10] o.a.s.p.f.c.CommandExecutorTask - SQL执行错误, msg:You have an error in your SQL syntax
org.apache.shardingsphere.sql.parser.exception.SQLParsingException: You have an error in your SQL syntax
	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.twoPhaseParse(SQLParserExecutor.java:68)
	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.parse(SQLParserExecutor.java:48)
	at org.apache.shardingsphere.sql.parser.api.SQLParserEngine.parse(SQLParserEngine.java:47)
	at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserExecutor.parse(SQLStatementParserExecutor.java:48)
	at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserEngine.parse(SQLStatementParserEngine.java:47)
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine.parse$original$b9bZ3dOV(ShardingSphereSQLParserEngine.java:58)
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine.parse$original$b9bZ3dOV$accessor$4qbnS5hI(ShardingSphereSQLParserEngine.java)
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine$auxiliary$97J7qXmI.call(Unknown Source)
	at org.apache.shardingsphere.agent.core.plugin.interceptor.InstanceMethodAroundInterceptor.intercept(InstanceMethodAroundInterceptor.java:74)
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine.parse$original$mX8jvj0b(ShardingSphereSQLParserEngine.java)
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine.parse$original$mX8jvj0b$accessor$BaazUl4v(ShardingSphereSQLParserEngine.java)
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine$auxiliary$G3CQKZtu.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine.parse(ShardingSphereSQLParserEngine.java)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.parseSql(MySQLComQueryPacketExecutor.java:83)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.<init>(MySQLComQueryPacketExecutor.java:71)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecutorFactory.newInstance(MySQLCommandExecutorFactory.java:75)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandExecutor(MySQLCommandExecuteEngine.java:61)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:107)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run$original$fG8dbaSL(CommandExecutorTask.java:78)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run$original$fG8dbaSL$accessor$yHugbcBG(CommandExecutorTask.java)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask$auxiliary$zRrNxTQ2.call(Unknown Source)
	at org.apache.shardingsphere.agent.core.plugin.interceptor.InstanceMethodAroundInterceptor.intercept(InstanceMethodAroundInterceptor.java:74)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run$original$tyJ2TvVs(CommandExecutorTask.java)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run$original$tyJ2TvVs$accessor$fcLhao5I(CommandExecutorTask.java)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask$auxiliary$MqYRhs4w.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by RaigorJiang** [comment]
Hi @mingyifei 
The meaning of the title is not clear, can you change it?

**Comment by mingyifei** [comment]
> Hi @mingyifei The meaning of the title is not clear, can you change it?

ok.

**Comment by tuichenchuxin** [comment]
Because of the keyword rank. It can't be supported by mysql 8 .So I think it's no need to be supported. It's same as #13759
