### ISSUE TITLE
`CoordinatorRegistryCenterInitializer` IllegalArgumentException occurred when use `etcd`

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#19715]
### Which version of ShardingSphere did you use?

`master` https://github.com/apache/shardingsphere/commit/a696de87196885f532b07c9a5b5c2b2bc95c8e06

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

`ShardingSphere-Proxy`

```
mode:
  type: Cluster
  repository:
    type: Etcd
    props:
      namespace: governance_ds
      server-lists: http://127.0.0.1:2379
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
  overwrite: false

rules:
  - !AUTHORITY
    users:
      - root@%:root
      - sharding@:sharding
    provider:
      type: ALL_PERMITTED
```

```
[ERROR] 2022-07-30 20:34:53.605 [main] o.a.s.p.i.BootstrapInitializer - contextManager onInitialized callback for 'org.apache.shardingsphere.data.pipeline.scenario.rulealtered.spi.RuleAlteredContextManagerLifecycleListener' failed
java.lang.IllegalArgumentException: Unsupported clusterType=Etcd
	at org.apache.shardingsphere.data.pipeline.core.registry.CoordinatorRegistryCenterInitializer.createRegistryCenter(CoordinatorRegistryCenterInitializer.java:50)
	at org.apache.shardingsphere.data.pipeline.core.api.PipelineAPIFactory$RegistryCenterHolder.createRegistryCenter(PipelineAPIFactory.java:148)
	at org.apache.shardingsphere.data.pipeline.core.api.PipelineAPIFactory$RegistryCenterHolder.getInstance(PipelineAPIFactory.java:138)
	at org.apache.shardingsphere.data.pipeline.core.api.PipelineAPIFactory.getRegistryCenter(PipelineAPIFactory.java:96)
	at org.apache.shardingsphere.data.pipeline.core.execute.FinishedCheckJobExecutor.doStart(FinishedCheckJobExecutor.java:40)
	at org.apache.shardingsphere.data.pipeline.api.executor.AbstractLifecycleExecutor.start(AbstractLifecycleExecutor.java:41)
	at org.apache.shardingsphere.data.pipeline.scenario.rulealtered.RuleAlteredJobWorker.initWorkerIfNecessary(RuleAlteredJobWorker.java:101)
	at org.apache.shardingsphere.data.pipeline.scenario.rulealtered.spi.RuleAlteredContextManagerLifecycleListener.onInitialized(RuleAlteredContextManagerLifecycleListener.java:45)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.contextManagerInitializedCallback(BootstrapInitializer.java:79)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.init(BootstrapInitializer.java:59)
	at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:52)
```

**Comment by linghengqian** [comment]
- This seems like reasonable behavior since the return value of `org.apache.shardingsphere.mode.repository.cluster.etcd.EtcdRepository.getType()` is `etcd` instead of `Etcd`.
- https://github.com/apache/shardingsphere/blob/a308ac767b23a420e62f6258fdf6999a8664d62c/mode/type/cluster/repository/provider/etcd/src/main/java/org/apache/shardingsphere/mode/repository/cluster/etcd/EtcdRepository.java#L200
