### ISSUE TITLE
NPE occurred when execute `REFRESH TABLE METADATA t_order FROM RESOURCE ds_1`

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#19714]
### Which version of ShardingSphere did you use?

`master` https://github.com/apache/shardingsphere/commit/a696de87196885f532b07c9a5b5c2b2bc95c8e06

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

```
[ERROR] 2022-07-30 20:26:32.965 [ShardingSphere-Command-0] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
java.lang.NullPointerException: null
	at org.apache.shardingsphere.infra.metadata.database.schema.loader.spi.DialectSchemaMetaDataLoaderFactory.findInstance(DialectSchemaMetaDataLoaderFactory.java:45)
	at org.apache.shardingsphere.infra.metadata.database.schema.loader.SchemaMetaDataLoaderEngine.load(SchemaMetaDataLoaderEngine.java:62)
	at org.apache.shardingsphere.infra.metadata.database.schema.builder.GenericSchemaBuilder.loadSchemas(GenericSchemaBuilder.java:93)
	at org.apache.shardingsphere.infra.metadata.database.schema.builder.GenericSchemaBuilder.build(GenericSchemaBuilder.java:76)
	at org.apache.shardingsphere.mode.manager.ContextManager.reloadTable(ContextManager.java:466)
	at org.apache.shardingsphere.mode.manager.ContextManager.reloadTable(ContextManager.java:456)
	at org.apache.shardingsphere.proxy.backend.handler.distsql.ral.updatable.RefreshTableMetadataHandler.update(RefreshTableMetadataHandler.java:41)
	at org.apache.shardingsphere.proxy.backend.handler.distsql.ral.UpdatableRALBackendHandler.execute(UpdatableRALBackendHandler.java:38)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:94)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:112)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

```
CREATE DATABASE TEST;
USE TEST;
REFRESH TABLE METADATA t_order FROM RESOURCE ds_1;
```

**Comment by RaigorJiang** [comment]
I think we need to check if the specified resource exists before executing refresh, like we do when `CREATE SHArDING TABLE RULE`.

**Comment by zjcnb** [comment]
> I think we need to check if the specified resource exists before executing refresh, like we do when `CREATE SHArDING TABLE RULE`.

Yeah, i think so. i think we can finish it in next milestone.

**Comment by RaigorJiang** [comment]
@zjcnb OK, I will fix it.

**Comment by strongduanmu** [comment]
Hi @RaigorJiang , could we finish this issue in 5.2.1?
