### ISSUE TITLE
LockContext.tryLock may occur exception and convert to warn log

### ISSUE THREAD

**Issue by azexcy** [apache/shardingsphere#20035]
## Bug Report

Use 1 ShardingSphere-Proxy  and the sharding item is 2.

Relation ci url
> https://github.com/apache/shardingsphere/runs/7745031071?check_suite_focus=true
https://github.com/apache/shardingsphere/runs/7745031071?check_suite_focus=true
https://github.com/apache/shardingsphere/runs/7737878020?check_suite_focus=true

Relation code at RuleAlteredJobPreparer

```
  private void prepareAndCheckTargetWithLock(final RuleAlteredJobContext jobContext) {
        RuleAlteredJobConfiguration jobConfig = jobContext.getJobConfig();
        // TODO the lock will be replaced
        String lockName = "prepare-" + jobConfig.getJobId();
        LockContext lockContext = PipelineContext.getContextManager().getInstanceContext().getLockContext();
        LockDefinition lockDefinition = new ExclusiveLockDefinition(lockName);
        if (lockContext.tryLock(lockDefinition, 3000)) {
            try {
                prepareAndCheckTarget(jobContext);
            } finally {
                lockContext.unlock(lockDefinition);
            }
        } else {
            waitUntilLockReleased(lockContext, lockDefinition);
        }
    }
```

```
[INFO ] 2022-08-09 12:29:02.409 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: [WARN ] 2022-08-09 12:29:01.955 [Thread-16] o.a.c.f.r.l.InterProcessSemaphoreV2 - Lease already released
[INFO ] 2022-08-09 12:29:02.409 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /it_db_mysql/lock/exclusive/locks/prepare-0130317c30317c3054317c7368617264696e675f6462/leases/_c_090eca4a-ac2f-46b7-9b16-dcf742dc7f6e-lease-0000000001
[INFO ] 2022-08-09 12:29:02.409 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:118)
[INFO ] 2022-08-09 12:29:02.409 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
[INFO ] 2022-08-09 12:29:02.409 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: 	at org.apache.zookeeper.ZooKeeper.delete(ZooKeeper.java:2000)
[INFO ] 2022-08-09 12:29:02.409 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: 	at org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:274)
[INFO ] 2022-08-09 12:29:02.409 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: 	at org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:268)
[INFO ] 2022-08-09 12:29:02.409 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: 	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:93)
[INFO ] 2022-08-09 12:29:02.409 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: 	at org.apache.curator.framework.imps.DeleteBuilderImpl.pathInForeground(DeleteBuilderImpl.java:265)
[INFO ] 2022-08-09 12:29:02.410 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: 	at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:249)
[INFO ] 2022-08-09 12:29:02.410 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: 	at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:34)
[INFO ] 2022-08-09 12:29:02.410 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: 	at org.apache.curator.framework.recipes.locks.InterProcessSemaphoreV2$3.close(InterProcessSemaphoreV2.java:456)
[INFO ] 2022-08-09 12:29:02.410 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: 	at org.apache.curator.shaded.com.google.common.io.Closeables.close(Closeables.java:78)
[INFO ] 2022-08-09 12:29:02.410 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: 	at org.apache.curator.utils.CloseableUtils.closeQuietly(CloseableUtils.java:59)
[INFO ] 2022-08-09 12:29:02.410 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: 	at org.apache.curator.framework.recipes.locks.InterProcessSemaphoreV2.returnLease(InterProcessSemaphoreV2.java:198)
[INFO ] 2022-08-09 12:29:02.410 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: 	at org.apache.curator.framework.recipes.locks.InterProcessSemaphoreV2.internalAcquire1Lease(InterProcessSemaphoreV2.java:428)
[INFO ] 2022-08-09 12:29:02.410 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: 	at org.apache.curator.framework.recipes.locks.InterProcessSemaphoreV2.acquire(InterProcessSemaphoreV2.java:284)
[INFO ] 2022-08-09 12:29:02.410 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: 	at org.apache.curator.framework.recipes.locks.InterProcessSemaphoreV2.acquire(InterProcessSemaphoreV2.java:246)
[INFO ] 2022-08-09 12:29:02.410 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: 	at org.apache.curator.framework.recipes.locks.InterProcessSemaphoreMutex.acquire(InterProcessSemaphoreMutex.java:55)
[INFO ] 2022-08-09 12:29:02.410 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: 	at org.apache.shardingsphere.mode.repository.cluster.zookeeper.lock.ZookeeperInternalLockHolder$ZookeeperInternalLock.tryLock(ZookeeperInternalLockHolder.java:64)
[INFO ] 2022-08-09 12:29:02.410 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: 	at org.apache.shardingsphere.mode.repository.cluster.zookeeper.CuratorZookeeperRepository.tryLock(CuratorZookeeperRepository.java:259)
[INFO ] 2022-08-09 12:29:02.410 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: 	at org.apache.shardingsphere.mode.manager.cluster.coordinator.ClusterLockPersistService.tryLock(ClusterLockPersistService.java:36)
[INFO ] 2022-08-09 12:29:02.410 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: 	at org.apache.shardingsphere.mode.lock.ShardingSphereLockContext.tryLock(ShardingSphereLockContext.java:43)
[INFO ] 2022-08-09 12:29:02.410 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: 	at org.apache.shardingsphere.data.pipeline.scenario.rulealtered.RuleAlteredJobPreparer.prepareAndCheckTargetWithLock(RuleAlteredJobPreparer.java:107)
[INFO ] 2022-08-09 12:29:02.410 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: 	at org.apache.shardingsphere.data.pipeline.scenario.rulealtered.RuleAlteredJobPreparer.prepare(RuleAlteredJobPreparer.java:82)
[INFO ] 2022-08-09 12:29:02.410 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: 	at org.apache.shardingsphere.data.pipeline.scenario.rulealtered.RuleAlteredJob.prepare(RuleAlteredJob.java:78)
[INFO ] 2022-08-09 12:29:02.410 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: 	at org.apache.shardingsphere.data.pipeline.scenario.rulealtered.RuleAlteredJob.lambda$execute$0(RuleAlteredJob.java:69)
[INFO ] 2022-08-09 12:29:02.410 [docker-java-stream-1979715885] :ShardingSphere-Proxy - STDOUT: 	at java.lang.Thread.run(Thread.java:748)
```

### Which version of ShardingSphere did you use?

master  97a54388f80c2aa408496b4f520e9df0beb02cb4

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

no warn and exception thrown

### Actual behavior

get warn message( zookeeper catch the exception)

**Comment by soulasuna** [comment]
Fixed
