### ISSUE TITLE
NodeExistsException occurred when proxy start up with sharding configuration

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#20153]
### Which version of ShardingSphere did you use?

`master` branch https://github.com/apache/shardingsphere/commit/ee85debafcd31df31ff4c39bc2d830f0c326e270

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

`ShardingSphere-Proxy`

```
Exception in thread "main" org.apache.shardingsphere.mode.repository.cluster.ClusterPersistRepositoryException: org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /governance_ds/nodes/compute_nodes/online/proxy/690c4a12-a305-4847-a1cb-8b4a6270ab7b
	at org.apache.shardingsphere.mode.repository.cluster.zookeeper.CuratorZookeeperRepository.persistEphemeral(CuratorZookeeperRepository.java:198)
	at org.apache.shardingsphere.mode.manager.cluster.coordinator.registry.status.compute.service.ComputeNodeStatusService.registerOnline(ComputeNodeStatusService.java:55)
	at org.apache.shardingsphere.mode.manager.cluster.coordinator.RegistryCenter.onlineInstance(RegistryCenter.java:96)
	at org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.registerOnline(ClusterContextManagerBuilder.java:82)
	at org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.build(ClusterContextManagerBuilder.java:57)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.createContextManager(BootstrapInitializer.java:67)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.init(BootstrapInitializer.java:57)
	at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:52)
Caused by: org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /governance_ds/nodes/compute_nodes/online/proxy/690c4a12-a305-4847-a1cb-8b4a6270ab7b
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:126)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1836)
	at org.apache.curator.framework.imps.CreateBuilderImpl$16.call(CreateBuilderImpl.java:1131)
	at org.apache.curator.framework.imps.CreateBuilderImpl$16.call(CreateBuilderImpl.java:1113)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:93)
	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:1110)
	at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:593)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:583)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:48)
	at org.apache.shardingsphere.mode.repository.cluster.zookeeper.CuratorZookeeperRepository.persistEphemeral(CuratorZookeeperRepository.java:193)
	... 7 more
```

### Configuration
```

- !SHARDING
  auditors:
    sharding_key_required_auditor:
      type: DML_SHARDING_CONDITIONS
  bindingTables:
  - t_order,t_order_item
  defaultAuditStrategy:
    allowHintDisable: true
    auditorNames:
    - sharding_key_required_auditor
  defaultDatabaseStrategy:
    standard:
      shardingAlgorithmName: database_inline
      shardingColumn: user_id
  keyGenerators:
    snowflake:
      type: SNOWFLAKE
  shardingAlgorithms:
    database_inline:
      props:
        algorithm-expression: ds_${user_id % 2}
      type: INLINE
    t_order_inline:
      props:
        algorithm-expression: t_order_${order_id % 2}
      type: INLINE
    t_order_item_inline:
      props:
        algorithm-expression: t_order_item_${order_id % 2}
      type: INLINE
  tables:
    t_order:
      actualDataNodes: ds_${0..1}.t_order_${0..1}
      auditStrategy:
        allowHintDisable: true
        auditorNames:
        - sharding_key_required_auditor
      keyGenerateStrategy:
        column: order_id
        keyGeneratorName: snowflake
      logicTable: t_order
      tableStrategy:
        standard:
          shardingAlgorithmName: t_order_inline
          shardingColumn: order_id
    t_order_item:
      actualDataNodes: ds_${0..1}.t_order_item_${0..1}
      keyGenerateStrategy:
        column: order_item_id
        keyGeneratorName: snowflake
      logicTable: t_order_item
      tableStrategy:
        standard:
          shardingAlgorithmName: t_order_item_inline
          shardingColumn: order_id
```

**Comment by zjcnb** [comment]
<img width="1716" alt="image" src="https://user-images.githubusercontent.com/33742097/184495615-b911a4b5-319e-479c-9e77-bb5b4e2a08ba.png">

**Comment by zjcnb** [comment]
@soulasuna Can you check it?

**Comment by soulasuna** [comment]
OK，i will fix it.
