### ISSUE TITLE
NPE occurred when AgentBuilder

### ISSUE THREAD

**Issue by sunkai-cai** [apache/shardingsphere#20319]
### Which version of ShardingSphere did you use?

master  https://github.com/apache/shardingsphere/commit/4b834438e606d29e2012318c75edefcb0fbd699e

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

```
[ERROR] 2022-08-20 09:31:32.769 [epollEventLoopGroup-2-1] o.a.s.a.c.b.listener.LoggingListener - Failed to instrument io.netty.channel.ChannelFutureListener$3                                            
java.lang.NullPointerException: Cannot invoke "java.util.Map.containsKey(Object)" because the return value of "org.apache.shardingsphere.agent.core.plugin.AgentPluginLoader.access$000(org.apache.shardingsphere.agent.core.plugin.AgentPluginLoader)" is null                                                                                                                                                     
        at org.apache.shardingsphere.agent.core.plugin.AgentPluginLoader$1.matches(AgentPluginLoader.java:134)                                                                                            
        at org.apache.shardingsphere.agent.core.plugin.AgentPluginLoader$1.matches(AgentPluginLoader.java:130)                                                                                            
        at org.apache.shardingsphere.dependencies.net.bytebuddy.agent.builder.AgentBuilder$RawMatcher$ForElementMatchers.matches(AgentBuilder.java:1833)
        at org.apache.shardingsphere.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:11870)
        at org.apache.shardingsphere.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:11828)
        at org.apache.shardingsphere.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1700(AgentBuilder.java:11545)
        at org.apache.shardingsphere.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:12308)
        at org.apache.shardingsphere.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:12240)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at org.apache.shardingsphere.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doPrivileged(AgentBuilder.java)
        at org.apache.shardingsphere.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:11771)
        at org.apache.shardingsphere.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$ByteBuddy$ModuleSupport.transform(Unknown Source)
        at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541) 
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) 
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at io.netty.channel.ChannelFutureListener.<clinit>(ChannelFutureListener.java:65)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) 
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
```

### Example codes for reproduce this issue (such as a github link).

cat conf/agent.yaml

```
applicationName: shardingsphere
ignoredPluginNames:
  - Jaeger
  - OpenTracing
  - Zipkin
  - OpenTelemetry
  - Logging
  - Prometheus

plugins:
  Prometheus:
    host:  "localhost"
    port: 9090
    props:
      JVM_INFORMATION_COLLECTOR_ENABLED : "true"
  Jaeger:
    host: "localhost"
    port: 5775
    props:
      SERVICE_NAME: "shardingsphere"
      JAEGER_SAMPLER_TYPE: "const"
      JAEGER_SAMPLER_PARAM: "1"
  Zipkin:
    host: "localhost"
    port: 9411
    props:
      SERVICE_NAME: "shardingsphere"
      URL_VERSION: "/api/v2/spans"
      SAMPLER_TYPE: "const"
      SAMPLER_PARAM: "1"
  OpenTracing:
    props:
      OPENTRACING_TRACER_CLASS_NAME: "org.apache.skywalking.apm.toolkit.opentracing.SkywalkingTracer"
  OpenTelemetry:
    props:
      otel.resource.attributes: "service.name=shardingsphere"
      otel.traces.exporter: "zipkin"
  Logging:
    props:
      LEVEL: "INFO"
```

**Comment by terrymanu** [comment]
I just set the issue as `invalid` because the author close it without any reason.
