### ISSUE TITLE
shardingsphere 5.1.2 proxy docker run tips

### ISSUE THREAD

**Issue by zacat** [apache/shardingsphere#20432]
shardingsphere 5.1.2 

config-sharding.yaml

databaseName: sharding_db

dataSources:
  ds_0:
    url: jdbc:mysql://192.168.130.131:3306/ds_0?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://192.168.130.131:3306/ds_1?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !SHARDING
  tables:
    t_bike:
      actualDataNodes: ds_${0..1}.t_bike_${0..9}
      databaseStrategy:  
        standard:
          shardingColumn: bike_id
          shardingAlgorithmName: database_inline
      tableStrategy:
        standard:
          shardingColumn: bike_id
          shardingAlgorithmName: bike_inline
      keyGenerateStrategy:
        column: bike_id
        keyGeneratorName: snowflake
    t_position:
      actualDataNodes: ds_${0..1}.t_position_${0..9}
      databaseStrategy:
        standard:
          shardingColumn: position_id
          shardingAlgorithmName: database_inline
      tableStrategy:
        standard:
          shardingColumn: position_id
          shardingAlgorithmName: position_inline
      keyGenerateStrategy:
        column: position_id
        keyGeneratorName: snowflake
  bindingTables:
    - t_bike,t_position
  defaultDatabaseStrategy:
    none:
  defaultTableStrategy:
    none:
  
  shardingAlgorithms:
    database_inline:
      type: MOD 
      props:
        sharding-count: 2
    bike_inline:
      type: HASH_MOD 
      props:
        sharding-count: '10' 
    position_inline:
      type: HASH_MOD 
      props:
        sharding-count: '10'
  
  keyGenerators:
    snowflake:
      type: SNOWFLAKE

docker run logs tips

Exception in thread "main" java.lang.IllegalArgumentException: Invalid binding table configuration in ShardingRuleConfiguration.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
	at org.apache.shardingsphere.sharding.rule.ShardingRule.<init>(ShardingRule.java:129)
	at org.apache.shardingsphere.sharding.rule.builder.ShardingRuleBuilder.build(ShardingRuleBuilder.java:41)
	at org.apache.shardingsphere.sharding.rule.builder.ShardingRuleBuilder.build(ShardingRuleBuilder.java:35)
	at org.apache.shardingsphere.infra.rule.builder.schema.DatabaseRulesBuilder.build(DatabaseRulesBuilder.java:56)
	at org.apache.shardingsphere.infra.metadata.database.ShardingSphereDatabase.create(ShardingSphereDatabase.java:73)
	at org.apache.shardingsphere.mode.metadata.MetaDataContextsBuilder.getGenericDatabases(MetaDataContextsBuilder.java:79)
	at org.apache.shardingsphere.mode.metadata.MetaDataContextsBuilder.getDatabases(MetaDataContextsBuilder.java:69)
	at org.apache.shardingsphere.mode.metadata.MetaDataContextsBuilder.build(MetaDataContextsBuilder.java:61)
	at org.apache.shardingsphere.mode.manager.memory.MemoryContextManagerBuilder.build(MemoryContextManagerBuilder.java:49)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.createContextManager(BootstrapInitializer.java:70)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.init(BootstrapInitializer.java:55)
	at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:50)

thank you!

**Comment by zacat** [comment]
[config-sharding.txt](https://github.com/apache/shardingsphere/files/9398693/config-sharding.txt)

**Comment by TeslaCN** [comment]
Please try the ShardingSphere 5.3.0. If the problem still exists, please open a new issue.
