### ISSUE TITLE
NullPointException

### ISSUE THREAD

**Issue by FileNotFoundExcetion** [apache/shardingsphere#20532]
select count(0) from (SELECT IfNUll(sum(ams.order_amount), 0) totalOrderAmount,                ifNUll(sum(ams.order_count), 0)  totalOrderCount,                ams.merchant_id  merchantId         FROM posx_direct_agent_mer_statistics ams         where          ams.agent_no_tree like CONCAT ('100209,102639,102916','%')         and ams.trade_date between ? and ?                              group by ams.merchant_id         order by ams.order_amount desc) tmp_count

Caused by: java.lang.NullPointerException: null
        at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.getValueCaseSensitiveFromTables(GroupByMemoryMergedResult.java:135)
        at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.getValueCaseSensitive(GroupByMemoryMergedResult.java:125)
        at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.init(GroupByMemoryMergedResult.java:73)
        at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.init(GroupByMemoryMergedResult.java:53)
        at org.apache.shardingsphere.infra.merge.result.impl.memory.MemoryMergedResult.<init>(MemoryMergedResult.java:51)
        at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.<init>(GroupByMemoryMergedResult.java:56)
        at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.getGroupByMergedResult(ShardingDQLResultMerger.java:118)
        at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.build(ShardingDQLResultMerger.java:86)
        at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.merge(ShardingDQLResultMerger.java:64)
        at org.apache.shardingsphere.infra.merge.MergeEngine.executeMerge(MergeEngine.java:78)
        at org.apache.shardingsphere.infra.merge.MergeEngine.merge(MergeEngine.java:67)
        at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.mergeQuery(ShardingSpherePreparedStatement.java:487)
        at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.getResultSet(ShardingSpherePreparedStatement.java:435)

**Comment by strongduanmu** [comment]
Hi @FileNotFoundExcetion, thank you for your feedback. ShardingSphere can not support subquery now.

**Comment by FileNotFoundExcetion** [comment]
you mean support  （SELECT IfNUll(sum(ams.order_amount), 0) totalOrderAmount, ifNUll(sum(ams.order_count), 0) totalOrderCount, ams.merchant_id merchantId FROM posx_direct_agent_mer_statistics ams where ams.agent_no_tree like CONCAT ('100209,102639,102916','%') and ams.trade_date between ? and ? group by ams.merchant_id order by ams.order_amount desc）？

**Comment by strongduanmu** [comment]
I think ShardingSphere can support `SELECT sum(ams.order_amount) totalOrderAmount, sum(ams.order_count) totalOrderCount, ams.merchant_id merchantId FROM posx_direct_agent_mer_statistics ams where ams.agent_no_tree like CONCAT ('100209,102639,102916','%') and ams.trade_date between ? and ? group by ams.merchant_id order by ams.order_amount desc`

**Comment by FileNotFoundExcetion** [comment]
thanks for your fast explaining...

**Comment by wushengxuan** [comment]
select ifnull(sum(ride_mileage) * 1000, 0)                          rideMileageMonth
             , sum(riding_time)                                             ridingTimeMonth
             , round(sum(ride_mileage) * 1000 / day (last_day(#{month})),2) avgRideMileageDay
             , sum(brakes_times)                                            brakesTimesMonth
             , sum(acceleration_times)                                      accelerationTimesMonth
             , sum(bending_times)                                           bendingTimesMonth
             , round(max(max_speed), 2)                                     maxSpeed
        from ride_history
        where del_flag = '0'
          and device_id = #{deviceId}
          and user_id = #{userId}
          and end_time between str_to_date(#{month}, '%Y-%m-%d') and date_add(str_to_date(#{month}, '%Y-%m-%d'), interval 1 month)
          and #{expireTime} >= end_time
          and sharding_id between #{shardingParams.startTimeStamp} and #{shardingParams.endTimeStamp}

my sql  report the sanme error 
Cause: java.lang.NullPointerException
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 38 more
Caused by: java.lang.NullPointerException
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.getValueCaseSensitiveFromTables(GroupByMemoryMergedResult.java:134)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.getValueCaseSensitive(GroupByMemoryMergedResult.java:124)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.init(GroupByMemoryMergedResult.java:73)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.init(GroupByMemoryMergedResult.java:53)
	at org.apache.shardingsphere.infra.merge.result.impl.memory.MemoryMergedResult.<init>(MemoryMergedResult.java:51)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.<init>(GroupByMemoryMergedResult.java:56)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.getGroupByMergedResult(ShardingDQLResultMerger.java:112)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.build(ShardingDQLResultMerger.java:82)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.merge(ShardingDQLResultMerger.java:63)
	at org.apache.shardingsphere.infra.merge.MergeEngine.executeMerge(MergeEngine.java:90)
	at org.apache.shardingsphere.infra.merge.MergeEngine.merge(MergeEngine.java:80)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.mergeQuery(ShardingSpherePreparedStatement.java:487)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.getResultSet(ShardingSpherePreparedStatement.java:435)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getFirstResultSet(DefaultResultSetHandler.java:237)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:187)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:65)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:108)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy480.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	... 45 more

**Comment by FileNotFoundExcetion** [comment]
select temp.rideMileageMonth,
       temp.ridingTimeMonth,
	   temp.avgRideMileageDay,
	   temp.brakesTimesMonth,
	   temp.accelerationTimesMonth,
	   temp.bendingTimesMonth,
	   temp.maxSpeed
 from (
 select ifnull(sum(ride_mileage) * 1000, 0)                          rideMileageMonth
         , sum(riding_time)                                             ridingTimeMonth
         , round(sum(ride_mileage) * 1000 / day (last_day(#{month})),2) avgRideMileageDay
         , sum(brakes_times)                                            brakesTimesMonth
         , sum(acceleration_times)                                      accelerationTimesMonth
         , sum(bending_times)                                           bendingTimesMonth
         , round(max(max_speed), 2)                                     maxSpeed
    from ride_history
    where del_flag = '0'
      and device_id = #{deviceId}
      and user_id = #{userId}
      and end_time between str_to_date(#{month}, '%Y-%m-%d') and date_add(str_to_date(#{month}, '%Y-%m-%d'), interval 1 month)
      and #{expireTime} >= end_time
      and sharding_id between #{shardingParams.startTimeStamp} and #{shardingParams.endTimeStamp}
	  ) temp

**Comment by FileNotFoundExcetion** [comment]
you can try it  .......i dont know whether succed
