### ISSUE TITLE
NullPointException

### ISSUE THREAD

**Issue by FileNotFoundExcetion** [apache/shardingsphere#20555]
DB type:MySQL

when i use limit paging，it would throw NPE exception.

Caused by: java.lang.NullPointerException
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.getValueCaseSensitiveFromTables(GroupByMemoryMergedResult.java:135)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.getValueCaseSensitive(GroupByMemoryMergedResult.java:125)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.init(GroupByMemoryMergedResult.java:73)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.init(GroupByMemoryMergedResult.java:53)
	at org.apache.shardingsphere.infra.merge.result.impl.memory.MemoryMergedResult.<init>(MemoryMergedResult.java:51)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.<init>(GroupByMemoryMergedResult.java:56)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.getGroupByMergedResult(ShardingDQLResultMerger.java:118)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.build(ShardingDQLResultMerger.java:86)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.merge(ShardingDQLResultMerger.java:64)
	at org.apache.shardingsphere.infra.merge.MergeEngine.executeMerge(MergeEngine.java:78)
	at org.apache.shardingsphere.infra.merge.MergeEngine.merge(MergeEngine.java:67)

scene: 
   when the actual sql router one 1 table ,it's result is true.but when when it router 2 table ,it throw null pointException.

here is sql print

][ShardingSphere-SQL.log][SQLLogger.java:74  ] Logic SQL: SELECT IfNUll(sum(ams.order_amount), 0) totalOrderAmount,
               ifNUll(sum(ams.order_count), 0)  totalOrderCount,
               ams.merchant_id  merchantId,
               ams.order_amount amount
        FROM posx_direct_agent_mer_statistics ams
        where
         ams.agent_no_tree like CONCAT ('null','%')
        and ams.trade_date between ? and ?
         
          
            AND ams.agent_no = ?
          
        group by ams.merchant_id
        order by ams.order_amount desc
         
            LIMIT ?,?
[posx-agent-gateway][2022-08-26 14:59:54,413][ INFO][main][][ShardingSphere-SQL.log][SQLLogger.java:74  ] SQLStatement: MySQLSelectStatement(table=Optional.empty, limit=Optional[org.apache.shardingsphere.sql.parser.sql.common.segment.dml.pagination.limit.LimitSegment@7294e45b], lock=Optional.empty, window=Optional.empty)
[posx-agent-gateway][2022-08-26 14:59:54,413][ INFO][main][][ShardingSphere-SQL.log][SQLLogger.java:74  ] Actual SQL: ss ::: SELECT IfNUll(sum(ams.order_amount), 0) totalOrderAmount,
               ifNUll(sum(ams.order_count), 0)  totalOrderCount,
               ams.merchant_id  merchantId,
               ams.order_amount amount
        FROM t_agent_mer_stat_202207 ams
        where
         ams.agent_no_tree like CONCAT ('null','%')
        and ams.trade_date between ? and ?
         
          
            AND ams.agent_no = ?
          
        group by ams.merchant_id
        order by ams.order_amount desc
         
            LIMIT ?,? ::: [20220701, 20220831, 102916, 0, 2147483647]
[posx-agent-gateway][2022-08-26 14:59:54,414][ INFO][main][][ShardingSphere-SQL.log][SQLLogger.java:74  ] Actual SQL: ss ::: SELECT IfNUll(sum(ams.order_amount), 0) totalOrderAmount,
               ifNUll(sum(ams.order_count), 0)  totalOrderCount,
               ams.merchant_id  merchantId,
               ams.order_amount amount
        FROM t_agent_mer_stat_202208 ams
        where
         ams.agent_no_tree like CONCAT ('null','%')
        and ams.trade_date between ? and ?
         
          
            AND ams.agent_no = ?
          
        group by ams.merchant_id
        order by ams.order_amount desc
         
            LIMIT ?,? ::: [20220701, 20220831, 102916, 0, 2147483647]

i don't know whether you can understand?

**Comment by terrymanu** [comment]
Please change the title for search friendly

**Comment by TeslaCN** [comment]
Please try the 5.3.0. If the issue still exists, please help us reproduce it.
