### ISSUE TITLE
ShardingSphere-Proxy  encrypt will close connection,`o.a.s.p.f.c.CommandExecutorTask - Exception occur: java.lang.IllegalArgumentException: Illegal base64 character 2d`.

### ISSUE THREAD

**Issue by wsm12138** [apache/shardingsphere#20713]
### Which version of ShardingSphere did you use?
97bc2168039c09728fc8c651c82ee9bddf641fef
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
have error but connection still connect
### Actual behavior
have error but connection interrupt

<img width="804" alt="image" src="https://user-images.githubusercontent.com/86462784/202146757-c5f6dd56-7b3d-4b7e-bed7-82b4fe51c9c6.png">

### Reason analyze (If you can)
```
[INFO ] 2022-09-01 08:36:22.124 [ShardingSphere-Command-94] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT c AS c FROM sbtest5 WHERE id=? /*shadow:true*/ ::: [18088786]
[ERROR] 2022-09-01 08:36:22.125 [ShardingSphere-Command-98] o.a.s.p.f.c.CommandExecutorTask - Exception occur:
java.lang.IllegalArgumentException: Illegal base64 character 2d
	at java.base/java.util.Base64$Decoder.decode0(Base64.java:847)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:566)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:589)
	at org.apache.shardingsphere.encrypt.algorithm.AESEncryptAlgorithm.decrypt(AESEncryptAlgorithm.java:77)
	at org.apache.shardingsphere.encrypt.algorithm.AESEncryptAlgorithm.decrypt(AESEncryptAlgorithm.java:41)
	at org.apache.shardingsphere.encrypt.merge.dql.EncryptMergedResult.getValue(EncryptMergedResult.java:57)
	at org.apache.shardingsphere.proxy.backend.communication.DatabaseCommunicationEngine.getQueryResponseRow(DatabaseCommunicationEngine.java:213)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.binary.execute.MySQLComStmtExecuteExecutor.getQueryRowPacket(MySQLComStmtExecuteExecutor.java:145)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.binary.execute.MySQLComStmtExecuteExecutor.getQueryRowPacket(MySQLComStmtExecuteExecutor.java:70)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecuteEngine.writeQueryData(MySQLCommandExecuteEngine.java:90)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:113)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:77)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. start proxy
2. config proxy `CREATE ENCRYPT RULE sbtest1 (
    COLUMNS(
        (NAME=c,CIPHER=c,TYPE(NAME=AES,PROPERTIES('aes-key-value'='123456abc')))
));`
3. start MySQL
4. use sysbench prepare data to MySQL,without proxy
5. use proxy execute `select `

**Comment by strongduanmu** [comment]
@wsm12138 Please use `sysbench` prepare data to MySQL through proxy.

**Comment by wsm12138** [comment]
I want to kown ,if we can't get data from  Proxy by encrpt_rule because of data  not encrypted.
why connection abort,rather than continue？

**Comment by TeslaCN** [comment]
![image](https://user-images.githubusercontent.com/20503072/199903855-f6939933-e31f-4407-a991-f8c31226c640.png)

**Comment by TeslaCN** [comment]
To fix this issue, we have to refactor MySQLPacket. Removing the sequence ID from MySQLPacket and handling sequence ID in Codec.
https://github.com/apache/shardingsphere/blob/35a97dd82bdad130379f7aa570e3baa3b7347942/db-protocol/mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/packet/MySQLPacket.java#L28-L33

**Comment by TeslaCN** [comment]
MySQL maintain a field `pkt_nr` in `NET` to hold sequence ID for current connection.

https://github.com/mysql/mysql-server/blob/a246bad76b9271cb4333634e954040a970222e0a/include/mysql_com.h#L921

Sequence ID would be verified when reading packet headers.

https://github.com/mysql/mysql-server/blob/a246bad76b9271cb4333634e954040a970222e0a/sql-common/net_serv.cc#L1477-L1502
