### ISSUE TITLE
Cluster Mode For Zk err

### ISSUE THREAD

**Issue by pengdafu** [apache/shardingsphere#20993]
## Question

We have many single tables, When we use ZK as the registry, we get an error：

```shell
org.apache.zookeeper.ClientCnxn - Session 0x200002070440000 for sever xxx.xxx.xxx.xxx/xxx.xxx.xxx.xxx/xxx.xxx.xxx.xxx:12181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
java.io.IOException: Packet len 1350746 is out of range!
at org.apache.zookeeper.ClientCnxnSocket.readLength(ClientCnxnSocket.java:121)
at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:82)
at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:348)
at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1262)
[ERROR] 2022-09-15 11:14:35.602 [main-EventThread] o.a.c.f.r.cache.CuratorCacheImpl - CuratorCache error
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
at org.apache.curator.framework.recipes.cache.CuratorCacheImpl.handleException(CuratorCacheImpl.java:299)
at org.apache.curator.framework.recipes.cache.CuratorCacheImpl.lambda$checkChildrenChanged$4(CuratorCacheImpl.java:211)
at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:892)
at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:844)
at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:643)
at org.apache.curator.framework.imps.GetChildrenBuilderImpl$2.processResult(GetChildrenBuilderImpl.java:187)
at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:664)
at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:551)
[INFO ] 2022-09-15 11:14:35.603 [main-EventThread] o.a.c.f.state.ConnectionStateManager - State change: SUSPENDED
[ERROR] 2022-09-15 11:14:35.603 [main-EventThread] o.a.c.f.imps.CuratorFrameworkImpl - Background operation retry gave up
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:851)
at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:643)
at org.apache.curator.framework.imps.GetChildrenBuilderImpl$2.processResult(GetChildrenBuilderImpl.java:187)
at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:664)
at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:551)
[ERROR] 2022-09-15 11:14:35.604 [main-EventThread] o.a.c.f.r.cache.CuratorCacheImpl - CuratorCache error
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
at org.apache.curator.framework.recipes.cache.CuratorCacheImpl.handleException(CuratorCacheImpl.java:299)
at org.apache.curator.framework.recipes.cache.CuratorCacheImpl.lambda$checkChildrenChanged$4(CuratorCacheImpl.java:211)
at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFra
```

**Comment by zhaojinchao95** [comment]
Maybe you should adjustment zk configuation? https://stackoverflow.com/questions/33408978/solr-zookeeper-cli-failing-ioexception-packet-len-is-out-of-range

**Comment by pengdafu** [comment]
Using the -d option to adjust the value of 'jute.maxbuffer' when starting Sharding can solve the problem.
