### ISSUE TITLE
java.lang.ClassCastException: org.apache.shardingsphere.infra.context.ConnectionContext cannot be cast to org.apache.shardingsphere.infra.binder.QueryContext

### ISSUE THREAD

**Issue by judykula** [apache/shardingsphere#21137]
## Bug Report

**For English only**, other languages will not accept.

[ERROR] 2022-09-22 17:30:49.224 [ShardingSphere-Command-1] o.a.s.a.c.p.i.InstanceMethodAroundInterceptor - Failed to execute the pre-method of method[route] in class[class org.apache.shardingsphere.infra.route.engine.SQLRouteEngine]
java.lang.ClassCastException: org.apache.shardingsphere.infra.context.ConnectionContext cannot be cast to org.apache.shardingsphere.infra.binder.QueryContext
	at org.apache.shardingsphere.agent.metrics.api.advice.SQLRouteEngineAdvice.beforeMethod(SQLRouteEngineAdvice.java:55)
	at org.apache.shardingsphere.agent.core.plugin.interceptor.InstanceMethodAroundInterceptor.intercept(InstanceMethodAroundInterceptor.java:63)
	at org.apache.shardingsphere.infra.route.engine.SQLRouteEngine.route(SQLRouteEngine.java)
	at org.apache.shardingsphere.infra.context.kernel.KernelProcessor.route(KernelProcessor.java:59)
	at org.apache.shardingsphere.infra.context.kernel.KernelProcessor.generateExecutionContext(KernelProcessor.java:51)
	at org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:126)
	at org.apache.shardingsphere.proxy.backend.handler.data.impl.UnicastDatabaseBackendHandler.execute(UnicastDatabaseBackendHandler.java:76)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:94)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:110)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run$original$DVM9twSv(CommandExecutorTask.java:77)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run$original$DVM9twSv$accessor$BuBKBPGk(CommandExecutorTask.java)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask$auxiliary$plsl7Ryl.call(Unknown Source)
	at org.apache.shardingsphere.agent.core.plugin.interceptor.InstanceMethodAroundInterceptor.intercept(InstanceMethodAroundInterceptor.java:74)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

### Which version of ShardingSphere did you use?
5.2.0

**Comment by TeslaCN** [comment]
It seems that the code in agent was outdated.

**Comment by judykula** [comment]
Can't you reproduce the problem? I tried both tag 5.2.0 and 5.2.1 of the master branch

**Comment by TeslaCN** [comment]
Hi @judykula 
Why closed this? Have you solved your problem?
