### ISSUE TITLE
gsql stuck if connecting to ShardingSphere-Proxy openGauss and specified a non-exist database name

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#21163]
### Which version of ShardingSphere did you use?

c3596089f4bfccd5d2b02b164c203f72e5d779be

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy openGauss

### Expected behavior

gsql client got error message immediately.

```
ERROR:  FATAL: database "nonexistdb" does not exist
```

### Actual behavior

gsql client stuck.

```
[ERROR] 2022-09-24 11:19:45.610 [epollEventLoopGroup-3-2] o.a.s.p.f.n.FrontendChannelInboundHandler - Exception occur: 
org.apache.shardingsphere.dialect.exception.syntax.database.UnknownDatabaseException: null
	at org.apache.shardingsphere.proxy.frontend.opengauss.authentication.OpenGaussAuthenticationHandler.loginWithSCRAMSha256Password(OpenGaussAuthenticationHandler.java:80)
	at org.apache.shardingsphere.proxy.frontend.opengauss.authentication.OpenGaussAuthenticationEngine.processPasswordMessage(OpenGaussAuthenticationEngine.java:115)
	at org.apache.shardingsphere.proxy.frontend.opengauss.authentication.OpenGaussAuthenticationEngine.authenticate(OpenGaussAuthenticationEngine.java:92)
	at org.apache.shardingsphere.proxy.frontend.netty.FrontendChannelInboundHandler.authenticate(FrontendChannelInboundHandler.java:77)
	at org.apache.shardingsphere.proxy.frontend.netty.FrontendChannelInboundHandler.channelRead(FrontendChannelInboundHandler.java:69)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)



Exception in thread "ShardingSphere-Command-0" java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
	at java.base/java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1111)
	at java.base/java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1102)
	at org.apache.shardingsphere.mode.process.ShowProcessListManager.removeProcessStatement(ShowProcessListManager.java:116)
	at org.apache.shardingsphere.mode.process.GovernanceExecuteProcessReporter.reportRemove(GovernanceExecuteProcessReporter.java:78)
	at org.apache.shardingsphere.infra.executor.sql.process.ExecuteProcessEngine.lambda$finishConnection$1(ExecuteProcessEngine.java:73)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.apache.shardingsphere.infra.executor.sql.process.ExecuteProcessEngine.finishConnection(ExecuteProcessEngine.java:73)
	at org.apache.shardingsphere.proxy.frontend.netty.FrontendChannelInboundHandler.closeAllResources(FrontendChannelInboundHandler.java:108)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

```
gsql -h 127.0.0.1 -p 55433 -U gaussdb nonexistdb -WPassword
```

**Comment by TeslaCN** [comment]
I found this issue could be reproduced by other ways which could cause error.

**Comment by strongduanmu** [comment]
Hi @TeslaCN , could we finish this issue in 5.2.1?

**Comment by TeslaCN** [comment]
> Hi @TeslaCN , could we finish this issue in 5.2.1?

I've moved this to next milestone.
