### ISSUE TITLE
ClusterPersistRepositoryException occurred when restart ShardingSphere-Proxy and use nacos

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#21266]
### Which version of ShardingSphere did you use?

`master`

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

`ShardingSphere-Proxy`

### Expected behavior

Start up successful

### Actual behavior

Start up fail

### Configuation

```
mode:
  type: Cluster
  repository:
    type: Nacos
    props:
      namespace: governance_ds
      server-lists: localhost:8848
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
  overwrite: false

rules:
  - !AUTHORITY
    users:
      - root@%:root
      - sharding@:sharding
    provider:
      type: ALL_PERMITTED
```

`DistSQL` : 

```
ADD RESOURCE ds_0 (
    HOST="127.0.0.1",
    PORT=3306,
    DB="ds2",
    USER="root",
    PASSWORD="123456"
)
```
The ds2 database has some tables.

Restart ShardingSphere-Proxy

```
Exception in thread "main" org.apache.shardingsphere.mode.repository.cluster.exception.ClusterPersistRepositoryException
	at org.apache.shardingsphere.mode.repository.cluster.nacos.NacosRepository.persist(NacosRepository.java:204)
	at org.apache.shardingsphere.mode.metadata.persist.service.schema.TableMetaDataPersistService.lambda$persist$0(TableMetaDataPersistService.java:44)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at org.apache.shardingsphere.mode.metadata.persist.service.schema.TableMetaDataPersistService.persist(TableMetaDataPersistService.java:44)
	at org.apache.shardingsphere.mode.metadata.persist.service.DatabaseMetaDataPersistService.persist(DatabaseMetaDataPersistService.java:125)
	at org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.lambda$null$2(ClusterContextManagerBuilder.java:110)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.lambda$persistMetaData$3(ClusterContextManagerBuilder.java:110)
	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4772)
	at org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.persistMetaData(ClusterContextManagerBuilder.java:109)
	at org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.build(ClusterContextManagerBuilder.java:68)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.createContextManager(BootstrapInitializer.java:68)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.init(BootstrapInitializer.java:58)
	at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:52)
[WARN ] 2022-09-29 17:25:56.382 [Thread-6] c.a.nacos.common.notify.NotifyCenter - [NotifyCenter] Start destroying Publisher
[WARN ] 2022-09-29 17:25:56.382 [Thread-0] c.a.n.c.http.HttpClientBeanHolder - [HttpClientBeanHolder] Start destroying common HttpClient
[WARN ] 2022-09-29 17:25:56.383 [Thread-6] c.a.nacos.common.notify.NotifyCenter - [NotifyCenter] Destruction of the end
[WARN ] 2022-09-29 17:25:56.384 [Thread-0] c.a.n.c.http.HttpClientBeanHolder - [HttpClientBeanHolder] Destruction of the end
```

**Comment by zhaojinchao95** [comment]
> I will fix this issue.

Ok, i assign you

**Comment by caqhy** [comment]
@zhaojinchao95

**Comment by strongduanmu** [comment]
Hi @caqhy @zhaojinchao95 , could we finish this issue in 5.2.1?

**Comment by TeslaCN** [comment]
Hi @caqhy  @zhaojinchao95 
Is there any progress?

**Comment by zhaojinchao95** [comment]
> Hi @caqhy @zhaojinchao95 Is there any progress?

The problem not reproduce, so i will close it.

**Comment by zhaojinchao95** [comment]
> Hi @caqhy @zhaojinchao95 , could we finish this issue in 5.2.1?

The problem not reproduce, so i will close it.
