### ISSUE TITLE
Why do I get error:org.apache.shardingsphere.infra.config.exception.ShardingSphereConfigurationException

### ISSUE THREAD

**Issue by liujiyuan** [apache/shardingsphere#21263]
I am new to shardingsphere. I use https://github.com/apache/shardingsphere/blob/master/shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/resources/conf/config-readwrite-splitting.yaml to demo, but when start the shardingproxy on apache/shardingsphere-proxy docker, I get the error. Could someone help me? 

`06:12:31.658 [HikariPool-2 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - After adding stats (total=2, active=0, idle=2, waiting=0)
Exception in thread "main" org.apache.shardingsphere.infra.config.exception.ShardingSphereConfigurationException
	at org.apache.shardingsphere.sharding.rule.ShardingRule.getTableRule(ShardingRule.java:390)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.apache.shardingsphere.sharding.rule.ShardingRule.createBindingTableRule(ShardingRule.java:241)
	at org.apache.shardingsphere.sharding.rule.ShardingRule.createBindingTableRules(ShardingRule.java:231)
	at org.apache.shardingsphere.sharding.rule.ShardingRule.<init>(ShardingRule.java:124)
	at org.apache.shardingsphere.sharding.rule.builder.ShardingRuleBuilder.build(ShardingRuleBuilder.java:41)
	at org.apache.shardingsphere.sharding.rule.builder.ShardingRuleBuilder.build(ShardingRuleBuilder.java:35)
	at org.apache.shardingsphere.infra.rule.builder.database.DatabaseRulesBuilder.build(DatabaseRulesBuilder.java:58)
	at org.apache.shardingsphere.infra.metadata.database.ShardingSphereDatabase.create(ShardingSphereDatabase.java:86)
	at org.apache.shardingsphere.infra.metadata.database.ShardingSphereDatabasesFactory.createGenericDatabases(ShardingSphereDatabasesFactory.java:80)
	at org.apache.shardingsphere.infra.metadata.database.ShardingSphereDatabasesFactory.create(ShardingSphereDatabasesFactory.java:68)
	at org.apache.shardingsphere.mode.metadata.MetaDataContextsFactory.create(MetaDataContextsFactory.java:68)
	at org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.build(ClusterContextManagerBuilder.java:54)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.createContextManager(BootstrapInitializer.java:67)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.init(BootstrapInitializer.java:57)
	at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:52)`

**Comment by liujiyuan** [comment]
I use docker apache/shardingsphere-proxy

**Comment by TeslaCN** [comment]
Have you configure any sharding rule in configuration files?

**Comment by RaigorJiang** [comment]
Closed due to no response.
