### ISSUE TITLE
Fetch forward is none and returns “ERROR:  Index: 0”

### ISSUE THREAD

**Issue by peilinqian** [apache/shardingsphere#21421]
### Which version of ShardingSphere did you use?
we find java version: java8, full_version=1.8.0_282, full_path=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/bin/java
ShardingSphere-5.2.1-SNAPSHOT
Commit ID: dirty-a467bbe1668c2c300d3c91236e9e213c565ab7bf
Commit Message: Fix openGauss cursor execution in xa transaction(#21250) (#21257)
Branch: a467bbe1668c2c300d3c91236e9e213c565ab7bf
Build time: 2022-09-29T16:40:08+0800

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
Fetch forward is none and returns normal；
### Actual behavior
Fetch forward is none and returns “ERROR:  Index: 0”

```
test_db=> start transaction;
START TRANSACTION
test_db=> cursor cur_test_01 for select * from t_ssdb order by 1;
DECLARE CURSOR
test_db=> ----without forward
test_db=> fetch from cur_test_01;
 id | c_id | a  |   b
----+------+----+-------
  1 |    1 | 10 | test1
(1 row)

test_db=> ----forward without count
test_db=> fetch forward from cur_test_01;
 id | c_id | a  |   b
----+------+----+--------
  1 |    2 | 10 | Test12
(1 row)

test_db=> ----forward with count
test_db=> fetch forward 2 from cur_test_01;
 id | c_id | a  |   b
----+------+----+--------
  1 |    2 |    | test12
  2 |    2 | 20 | test22
(2 rows)

test_db=> ----forward with all
test_db=> fetch forward all from cur_test_01;
 id | c_id |  a  |    b
----+------+-----+---------
  2 |    1 |  20 | test21
  2 |    3 |     | Test22
  3 |    3 |     | test3
  3 |    3 |     | test3
  3 |    1 |     | test31
  4 |    4 |  40 | test4
  5 |    5 |  50 | Test5
  6 |    6 |  60 | test6
  7 |    4 |  74 | test74
  8 |    5 |  85 | test85
  9 |    5 |  50 | test95
 10 |    6 | 106 | test106
(12 rows)

test_db=> ----forward next is none
test_db=> fetch forward cur_test_01;
ERROR:  Index: 0
test_db=> close cur_test_01;
CLOSE CURSOR
test_db=> end;
COMMIT
```

background log

```
[INFO ] 2022-10-09 16:16:55.471 [Connection-56-ThreadExecutor] ShardingSphere-SQL - Actual SQL: ds_0 ::: fetch  FORWARD 1  cur_test_01_t_ssdb;
[INFO ] 2022-10-09 16:16:55.471 [Connection-56-ThreadExecutor] ShardingSphere-SQL - Actual SQL: ds_1 ::: fetch  FORWARD 1  cur_test_01_t_ssdb;
[ERROR] 2022-10-09 16:16:55.475 [Connection-56-ThreadExecutor] o.a.s.p.f.c.CommandExecutorTask - Exception occur:
java.lang.IndexOutOfBoundsException: Index: 0
        at java.util.Collections$EmptyList.get(Collections.java:4456)
        at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.compareTo(OrderByValue.java:120)
        at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.compareTo(OrderByValue.java:43)
        at java.util.PriorityQueue.siftUpComparable(PriorityQueue.java:656)
        at java.util.PriorityQueue.siftUp(PriorityQueue.java:647)
        at java.util.PriorityQueue.offer(PriorityQueue.java:344)
        at org.apache.shardingsphere.sharding.merge.ddl.fetch.FetchStreamMergedResult.addOrderedResultSetsToQueue(FetchStreamMergedResult.java:133)
        at org.apache.shardingsphere.sharding.merge.ddl.fetch.FetchStreamMergedResult.<init>(FetchStreamMergedResult.java:66)
        at org.apache.shardingsphere.sharding.merge.ddl.ShardingDDLResultMerger.merge(ShardingDDLResultMerger.java:58)
        at org.apache.shardingsphere.infra.merge.MergeEngine.executeMerge(MergeEngine.java:82)
        at org.apache.shardingsphere.infra.merge.MergeEngine.merge(MergeEngine.java:71)
        at org.apache.shardingsphere.proxy.backend.communication.DatabaseCommunicationEngine.mergeQuery(DatabaseCommunicationEngine.java:174)
        at org.apache.shardingsphere.proxy.backend.communication.DatabaseCommunicationEngine.processExecuteQuery(DatabaseCommunicationEngine.java:140)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:134)
        at org.apache.shardingsphere.proxy.frontend.opengauss.command.query.simple.OpenGaussComQueryExecutor.execute(OpenGaussComQueryExecutor.java:76)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:111)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
```
--create table
drop table if exists t_ssdb;
create table t_ssdb(id int,c_id int,a int,b text);
insert into t_ssdb values (1,1,10,'test1'),(1,2,10,'Test12'),(1,2,null,'test12'),
(2,1,20,'test21'),(2,2,20,'test22'),(2,3,null,'Test22'),
(3,3,null,'test3'),(3,3,null,'test3'),(3,1,null,'test31'),(4,4,40,'test4'),(5,5,50,'Test5'),(6,6,60,'test6'),
(7,4,74,'test74'),(8,5,85,'test85'),(9,5,50,'test95'),(10,6,106,'test106');

start transaction;
cursor cur_test_01 for select * from t_ssdb order by 1;
----without forward
fetch from cur_test_01;
----forward without count 
fetch forward from cur_test_01;
----forward with count
fetch forward 2 from cur_test_01;
----forward with all
fetch forward all from cur_test_01;
----forward next is none
fetch forward cur_test_01;
close cur_test_01;
end;
```

### Example codes for reproduce this issue (such as a github link).
```
rules:
- !SHARDING
  tables:
    t_ssdb:
      actualDataNodes: ds_${0..1}.t_ssdb
      databaseStrategy:
        standard:
          shardingAlgorithmName: ds_database_inline
          shardingColumn: id
  defaultTableStrategy:
    none:
  defaultDatabaseStrategy:
    none:
  shardingAlgorithms:
    ds_database_inline:
      type: INLINE
      props:
        algorithm-expression: ds_${id % 2}
        allow-range-query-with-inline-sharding: true
```

**Comment by FlyingZC** [comment]
I want to investigate the issue,please assign it to me. @strongduanmu

**Comment by FlyingZC** [comment]
@peilinqian Check whether the last sql `fetch forward cur_test_01;` has a syntax problem.
<img width="439" alt="image" src="https://user-images.githubusercontent.com/19788130/194753968-2eacbb3c-0bc4-4c6a-9bb8-9a26bd27e2ec.png">

**Comment by wsm12138** [comment]
fixed by [bcde6f3](https://github.com/apache/shardingsphere/commit/bcde6f374c4a3a025173fbc9f6d0e66ed686a042)
<img width="888" alt="image" src="https://user-images.githubusercontent.com/86462784/195038446-1221aa95-bc9b-4015-8b5d-0b481efee288.png">

**Comment by peilinqian** [comment]
we find java version: java8, full_version=1.8.0_282, full_path=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/bin/java
ShardingSphere-5.2.1-SNAPSHOT
Commit ID: dirty-bcde6f374c4a3a025173fbc9f6d0e66ed686a042
Commit Message: Fix fetch forward all error in openGauss(#21421) (#21471)
Branch: bcde6f374c4a3a025173fbc9f6d0e66ed686a042
Build time: 2022-10-11T19:13:56+0800


```
test_db=> start transaction;
START TRANSACTION
test_db=> cursor cur_test_01 for select * from t_ssdb order by 1;
DECLARE CURSOR
test_db=> ----without forward
test_db=> fetch from cur_test_01;
 id | c_id | a  |   b
----+------+----+-------
  1 |    1 | 10 | test1
(1 row)

test_db=> ----forward without count
test_db=> fetch forward from cur_test_01;
 id | c_id | a  |   b
----+------+----+--------
  1 |    2 | 10 | Test12
(1 row)

test_db=> ----forward with count
test_db=> fetch forward 2 from cur_test_01;
 id | c_id | a  |   b
----+------+----+--------
  1 |    2 |    | test12
  2 |    2 | 20 | test22
(2 rows)

test_db=> ----forward with all
test_db=> fetch forward all from cur_test_01;
 id | c_id |  a  |    b
----+------+-----+---------
  2 |    1 |  20 | test21
  2 |    3 |     | Test22
  3 |    3 |     | test3
  3 |    3 |     | test3
  3 |    1 |     | test31
  4 |    4 |  40 | test4
  5 |    5 |  50 | Test5
  6 |    6 |  60 | test6
  7 |    4 |  74 | test74
  8 |    5 |  85 | test85
  9 |    5 |  50 | test95
 10 |    6 | 106 | test106
(12 rows)

test_db=> ----forward next is none
test_db=> fetch forward cur_test_01;
 id | c_id | a | b
----+------+---+---
(0 rows)

test_db=> close cur_test_01;
CLOSE CURSOR
test_db=> end;
COMMIT
test_db=>

```

**Comment by peilinqian** [comment]
```
[INFO ] 2022-11-15 14:57:58.220 [Connection-7-ThreadExecutor] ShardingSphere-SQL - Actual SQL: write_0 ::: fetch FORWARD ALL from cur_test_01_t_ssdb;
[INFO ] 2022-11-15 14:57:58.220 [Connection-7-ThreadExecutor] ShardingSphere-SQL - Actual SQL: write_1 ::: fetch FORWARD ALL from cur_test_01_t_ssdb;
[INFO ] 2022-11-15 14:57:58.236 [Connection-7-ThreadExecutor] ShardingSphere-SQL - Logic SQL: fetch forward cur_test_01;
[INFO ] 2022-11-15 14:57:58.236 [Connection-7-ThreadExecutor] ShardingSphere-SQL - SQLStatement: OpenGaussFetchStatement(super=FetchStatement(super=AbstractSQLStatement(parameterCount=0, parameterMarkerSegments=[], commentSegments=[]), cursorName=CursorNameSegment(startIndex=14, stopIndex=24, identifier=IdentifierValue(value=cur_test_01, quoteCharacter=NONE)), direction=Optional[DirectionSegment(startIndex=6, stopIndex=12, directionType=Optional[FORWARD], count=Optional.empty)]))
[INFO ] 2022-11-15 14:57:58.236 [Connection-7-ThreadExecutor] ShardingSphere-SQL - Actual SQL: write_0 ::: fetch  FORWARD 1  cur_test_01_t_ssdb;
[INFO ] 2022-11-15 14:57:58.236 [Connection-7-ThreadExecutor] ShardingSphere-SQL - Actual SQL: write_1 ::: fetch  FORWARD 1  cur_test_01_t_ssdb;
[ERROR] 2022-11-15 14:57:58.240 [Connection-7-ThreadExecutor] o.a.s.p.f.c.CommandExecutorTask - Exception occur:
java.lang.IndexOutOfBoundsException: Index: 0
        at java.util.Collections$EmptyList.get(Collections.java:4456)
        at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.compareTo(OrderByValue.java:120)
        at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.compareTo(OrderByValue.java:43)
        at java.util.PriorityQueue.siftUpComparable(PriorityQueue.java:656)
        at java.util.PriorityQueue.siftUp(PriorityQueue.java:647)
        at java.util.PriorityQueue.offer(PriorityQueue.java:344)
        at org.apache.shardingsphere.sharding.merge.ddl.fetch.FetchStreamMergedResult.addOrderedResultSetsToQueue(FetchStreamMergedResult.java:133)
        at org.apache.shardingsphere.sharding.merge.ddl.fetch.FetchStreamMergedResult.<init>(FetchStreamMergedResult.java:66)
        at org.apache.shardingsphere.sharding.merge.ddl.ShardingDDLResultMerger.merge(ShardingDDLResultMerger.java:58)
        at org.apache.shardingsphere.infra.merge.MergeEngine.executeMerge(MergeEngine.java:82)
        at org.apache.shardingsphere.infra.merge.MergeEngine.merge(MergeEngine.java:71)
        at org.apache.shardingsphere.proxy.backend.communication.DatabaseCommunicationEngine.mergeQuery(DatabaseCommunicationEngine.java:174)
        at org.apache.shardingsphere.proxy.backend.communication.DatabaseCommunicationEngine.processExecuteQuery(DatabaseCommunicationEngine.java:140)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:134)
        at org.apache.shardingsphere.proxy.frontend.opengauss.command.query.simple.OpenGaussComQueryExecutor.execute(OpenGaussComQueryExecutor.java:76)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:111)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[INFO ] 2022-11-15 14:57:58.242 [Connection-7-ThreadExecutor] ShardingSphere-SQL - Logic SQL: close cur_test_01;
[INFO ] 2022-11-15 14:57:58.242 [Connection-7-ThreadExecutor] ShardingSphere-SQL - SQLStatement: OpenGaussCloseStatement(super=CloseStatement(super=AbstractSQLStatement(parameterCount=0, parameterMarkerSegments=[], commentSegments=[]), cursorName=Optional[CursorNameSegment(startIndex=6, stopIndex=16, identifier=IdentifierValue(value=cur_test_01, quoteCharacter=NONE))], closeAll=false))
[INFO ] 2022-11-15 14:57:58.242 [Connection-7-ThreadExecutor] ShardingSphere-SQL - Actual SQL: write_0 ::: close cur_test_01_t_ssdb;
[INFO ] 2022-11-15 14:57:58.242 [Connection-7-ThreadExecutor] ShardingSphere-SQL - Actual SQL: write_1 ::: close cur_test_01_t_ssdb;
```



```
[peilq_sharding@kwemhisprc10431 auto_test]$ bash ss_home/bin/start.sh --version
we find java version: java8, full_version=1.8.0_282, full_path=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/bin/java
ShardingSphere-5.2.1-SNAPSHOT
Commit ID: dirty-20bf595dfeced4dd8ffee2f6d95de52fdf3e569d
Commit Message: Rename sub modules of shardingsphere-infra-datetime-type. (#21472)
Branch: 20bf595dfeced4dd8ffee2f6d95de52fdf3e569d
Build time: 2022-11-11T19:57:07+0800

```

**Comment by FlyingZC** [comment]
It's affected by  https://github.com/apache/shardingsphere/pull/21992

**Comment by wsm12138** [comment]
710f53e45aef175ad9b6c33121b8b0e1a90e6157

<img width="773" alt="image" src="https://user-images.githubusercontent.com/86462784/204439187-f593a84e-2a81-4ba8-87b7-ddf1f04e128f.png">
