### ISSUE TITLE
java.sql.SQLException: Invalid column index: getValidColumnIndex

### ISSUE THREAD

**Issue by kuchikij** [apache/shardingsphere#21906]
### Which version of ShardingSphere did you use?
5.2.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
SQL query successfully in Oracle database.

### Actual behavior
SQL query error in Oracle database. The following problems are encountered.
java.sql.SQLException: Invalid column index: getValidColumnIndex
	at oracle.jdbc.driver.OracleResultSetMetaData.getValidColumnIndex(OracleResultSetMetaData.java:102)
	at oracle.jdbc.driver.OracleResultSetMetaData.getColumnName(OracleResultSetMetaData.java:267)
	at oracle.jdbc.driver.OracleResultSetMetaData.getColumnLabel(OracleResultSetMetaData.java:256)
	at org.apache.shardingsphere.driver.jdbc.core.resultset.ShardingSphereResultSetMetaData.getColumnLabel(ShardingSphereResultSetMetaData.java:106)
	at org.springframework.jdbc.support.JdbcUtils.lookupColumnName(JdbcUtils.java:509)
	at org.springframework.jdbc.core.BeanPropertyRowMapper.mapRow(BeanPropertyRowMapper.java:294)
	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:94)
	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:61)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:679)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:669)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:694)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:748)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:216)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:223)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
The sql example like following:
```sql
select *
  from (select Res.*, rownum as rn
          from (SELECT a.*
                  FROM (select * from t_order where group_id = ?) a
                 inner join (select * from t_order_price) dr
                    on a.order_id = dr.order_id
                   and dr.price >= ?
                 ORDER BY a.create_date_time desc) Res
         where rownum <= ?)
 where rn > ?
```
* `t_order` is sharding table, `t_order_price` isn't sharding table.
* `t_order` has the unique index with the fields of *order_id* and *group_Id*.
* The subquery **select * from t_order_price** is used to filter data. It doesn't need to query field! But, in fact, debug in the code **((SelectStatementContext) sqlStatementContext).getProjectionsContext().getExpandProjections()**. I found the fileds from the table of `t_order_price`.
* `t_order` rule like following:
```property
spring.shardingsphere.rules.sharding.tables.t_order.actual-data-nodes=ds.t_order_$->{1..9999}
spring.shardingsphere.rules.sharding.tables.t_order.table-strategy.standard.sharding-column=group_id
spring.shardingsphere.rules.sharding.tables.t_order.table-strategy.standard.sharding-algorithm-name=t-order-inline
spring.shardingsphere.rules.sharding.sharding-algorithms.t-order-inline.type=INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.t-order-inline.props.algorithm-expression=t_order_$->{group_id}
```

**Comment by RaigorJiang** [comment]
Hi @kuchikij 
Thanks for your feedback, are `t_order` and `t_order_price`  sharding tables? what are their rules?

**Comment by kuchikij** [comment]
> Hi @kuchikij Thanks for your feedback, are `t_order` and `t_order_price` sharding tables? what are their rules?

@RaigorJiang I have added info to the above.

**Comment by fang1025** [comment]
Try listing columns instead of a.*.
a.* -> a.order_id, a.price...

**Comment by kuchikij** [comment]
> ```
> Try listing columns instead of a.*
> a.* -> a.order_id, a.price...
> ```

It'a feasible! Thanks!

**Comment by RaigorJiang** [comment]
Close because it has been resolved.
