### ISSUE TITLE
use mysql8 err

### ISSUE THREAD

**Issue by lizhenyu0128** [apache/shardingsphere#21935]
Shardingsphere proxy 5 connects to mysql8, and mysql-connector-java-8.0.18.jar has been placed in the ext lib directory. Startup error：
Caused by: com.mysql.cj.exceptions.UnableToConnectException: CLIENT_PLUGIN_AUTH is required
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
        at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:205)
        at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1340)
        at com.mysql.cj.NativeSession.connect(NativeSession.java:157)
        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:956)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
<img width="380" alt="c437ce195cec9f41f037d1e8cc32efa5" src="https://user-images.githubusercontent.com/39519954/199702066-64572f4d-d963-421c-9901-b968543a7e98.png">

i try to  driver-class-name: com.mysql.cj.jdbc.Driver  put  conf/config-sharding.yaml
<img width="1040" alt="05fab8ee365d3322d471fbdcc24a2061" src="https://user-images.githubusercontent.com/39519954/199702020-020252df-39db-41e2-9fd1-dd3ffa17c39d.png">

So how to use mysql8？

**Comment by lizhenyu0128** [comment]
used mysql version : 8.0.18

**Comment by TeslaCN** [comment]
This may be a database or driver problem.
