### ISSUE TITLE
The encryption field is empty, causing abnormal data encryption

### ISSUE THREAD

**Issue by dbin0123** [apache/shardingsphere#21948]
the encryption field is empty, causing abnormal data encryption, version 5.2.1

Exception information
`java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Optional.<init>(Optional.java:96)
	at java.util.Optional.of(Optional.java:108)
	at org.apache.shardingsphere.infra.binder.segment.insert.values.InsertValueContext.getLiteralValue(InsertValueContext.java:80)
	at org.apache.shardingsphere.encrypt.rewrite.parameter.rewriter.EncryptInsertValueParameterRewriter.encryptInsertValues(EncryptInsertValueParameterRewriter.java:86)
	at org.apache.shardingsphere.encrypt.rewrite.parameter.rewriter.EncryptInsertValueParameterRewriter.lambda$rewrite$1(EncryptInsertValueParameterRewriter.java:71)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.apache.shardingsphere.encrypt.rewrite.parameter.rewriter.EncryptInsertValueParameterRewriter.rewrite(EncryptInsertValueParameterRewriter.java:71)
	at org.apache.shardingsphere.encrypt.rewrite.parameter.rewriter.EncryptInsertValueParameterRewriter.rewrite(EncryptInsertValueParameterRewriter.java:50)
	at org.apache.shardingsphere.encrypt.rewrite.context.EncryptSQLRewriteContextDecorator.rewriteParameters(EncryptSQLRewriteContextDecorator.java:89)
	at org.apache.shardingsphere.encrypt.rewrite.context.EncryptSQLRewriteContextDecorator.decorate(EncryptSQLRewriteContextDecorator.java:58)
	at org.apache.shardingsphere.encrypt.rewrite.context.EncryptSQLRewriteContextDecorator.decorate(EncryptSQLRewriteContextDecorator.java:44)`

Get the encrypted field literal method to save
`org.apache.shardingsphere.infra.binder.segment.insert.values.InsertValueContext.getLiteralValue`
![Uploading image.png…]()

Using the `of' method of the 'Optional' class causes a null pointer exception

**Comment by strongduanmu** [comment]
Hi @dbin0123, thank you for your feedback. Does you mean insert encrypt field with null?

**Comment by dbin0123** [comment]
@strongduanmu yes

**Comment by strongduanmu** [comment]
This bug has been fixed in master branch, please test it.
