### ISSUE TITLE
the Aggregate Query sql report error npe

### ISSUE THREAD

**Issue by wushengxuan** [apache/shardingsphere#22025]
the sql report error
        select ifnull(sum(ride_mileage) * 1000, 0)                          rideMileageMonth
             , sum(riding_time)                                             ridingTimeMonth
             , round(sum(ride_mileage) * 1000 / day (last_day(#{month})),2) avgRideMileageDay
             , sum(brakes_times)                                            brakesTimesMonth
             , sum(acceleration_times)                                      accelerationTimesMonth
             , sum(bending_times)                                           bendingTimesMonth
             , round(max(max_speed), 2)                                     maxSpeed
        from ride_history
        where del_flag = '0'
          and device_id = #{deviceId}
          and user_id = #{userId}
          and end_time between str_to_date(#{month}, '%Y-%m-%d') and date_add(str_to_date(#{month}, '%Y-%m-%d'), interval 1 month)
          and #{expireTime} >= end_time
          and sharding_id between #{shardingParams.startTimeStamp} and #{shardingParams.endTimeStamp}

the error is:
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 38 more
Caused by: java.lang.NullPointerException
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.getValueCaseSensitiveFromTables(GroupByMemoryMergedResult.java:134)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.getValueCaseSensitive(GroupByMemoryMergedResult.java:124)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.init(GroupByMemoryMergedResult.java:73)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.init(GroupByMemoryMergedResult.java:53)
	at org.apache.shardingsphere.infra.merge.result.impl.memory.MemoryMergedResult.<init>(MemoryMergedResult.java:51)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.<init>(GroupByMemoryMergedResult.java:56)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.getGroupByMergedResult(ShardingDQLResultMerger.java:112)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.build(ShardingDQLResultMerger.java:82)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.merge(ShardingDQLResultMerger.java:63)
	at org.apache.shardingsphere.infra.merge.MergeEngine.executeMerge(MergeEngine.java:90)
	at org.apache.shardingsphere.infra.merge.MergeEngine.merge(MergeEngine.java:80)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.mergeQuery(ShardingSpherePreparedStatement.java:487)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.getResultSet(ShardingSpherePreparedStatement.java:435)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getFirstResultSet(DefaultResultSetHandler.java:237)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:187)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:65)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:108)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy480.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	... 45 more

**Comment by RaigorJiang** [comment]
Hi, @wushengxuan 
Please follow the issue template to provide version and configurations.

**Comment by wushengxuan** [comment]
the shardingsphere version is 5.1.0
the setting like this
`package com.cfmoto.vehicle.config.sharding;

import com.cfmoto.vehicle.constant.ShardingConstant;
import org.apache.shardingsphere.infra.config.algorithm.ShardingSphereAlgorithmConfiguration;
import org.apache.shardingsphere.sharding.api.config.ShardingRuleConfiguration;
import org.apache.shardingsphere.sharding.api.config.rule.ShardingTableRuleConfiguration;
import org.apache.shardingsphere.sharding.api.config.strategy.sharding.StandardShardingStrategyConfiguration;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.stereotype.Component;

import java.util.Properties;

@Component
public class CustomShardingConfiguration {

    static final String EVENT_PREFIX = "event-history";
    static final String RIDE_PREFIX = "ride-history";


    @Bean(name = EVENT_PREFIX + "ShardingProperties")
    @ConfigurationProperties(prefix = "sharding." + EVENT_PREFIX)
    public ShardingProperties getEventShardingProperties() {
        return new ShardingProperties();
    }

    @Bean(name = RIDE_PREFIX + "ShardingProperties")
    @ConfigurationProperties(prefix = "sharding." + RIDE_PREFIX)
    public ShardingProperties getRideShardingProperties() {
        return new ShardingProperties();
    }

    @Bean("ShardingRuleConfiguration")
    public ShardingRuleConfiguration getShardingRule(@Qualifier(EVENT_PREFIX + "ShardingProperties") ShardingProperties eventShardingProperties, @Qualifier(RIDE_PREFIX + "ShardingProperties") ShardingProperties rideShardingProperties) {
        ShardingTableRuleConfiguration eventResult = new ShardingTableRuleConfiguration(eventShardingProperties.getLogicTable(), eventShardingProperties.getActualDataNodes());
        eventResult.setTableShardingStrategy(new StandardShardingStrategyConfiguration(eventShardingProperties.getShardingColumns(), eventShardingProperties.getShardingAlgorithmKey()));

        ShardingTableRuleConfiguration rideResult = new ShardingTableRuleConfiguration(rideShardingProperties.getLogicTable(), rideShardingProperties.getActualDataNodes());
        rideResult.setTableShardingStrategy(new StandardShardingStrategyConfiguration(rideShardingProperties.getShardingColumns(), rideShardingProperties.getShardingAlgorithmKey()));

        ShardingRuleConfiguration shardingRuleConfig = new ShardingRuleConfiguration();
        shardingRuleConfig.getShardingAlgorithms().put(ShardingConstant.EVENT_SHARDING_ALGORITHM_KEY, new ShardingSphereAlgorithmConfiguration(ShardingConstant.EVENT_SHARDING_TYPE, new Properties()));
        shardingRuleConfig.getShardingAlgorithms().put(ShardingConstant.RIDE_SHARDING_ALGORITHM_KEY, new ShardingSphereAlgorithmConfiguration(ShardingConstant.RIDE_SHARDING_TYPE, new Properties()));
        shardingRuleConfig.getTables().add(eventResult);
        shardingRuleConfig.getTables().add(rideResult);
        return shardingRuleConfig;
    }
}
`

**application.properties**
`sharding.event-history.logic-table=event_history
sharding.event-history.sharding-columns=sharding_id
sharding.event-history.sharding-algorithm-key=event-Sharding-algorithm
sharding.event-history.actual-data-nodes=shardingvehicle.event_history_${202109..209912}
sharding.event-history.sharding-type=event-history-sharding
sharding.event-history.sharding-key=event-Sharding-algorithm
sharding.ride-history.logic-table=ride_history
sharding.ride-history.sharding-columns=sharding_id
sharding.ride-history.sharding-algorithm-key=ride-Sharding-algorithm
sharding.ride-history.actual-data-nodes=shardingvehicle.ride_history_${202109..209912}
sharding.ride-history.sharding-type=ride-history-sharding
sharding.ride-history.sharding-key=ride-Sharding-algorithm`

**Comment by RaigorJiang** [comment]
Hi @wushengxuan 
Sorry, I didn't reproduce this problem, can you try the latest version 5.3.1?

**Comment by RaigorJiang** [comment]
Closed due to no response.
If this problem persists, please reopen it or submit a new one.
