### ISSUE TITLE
err: org.apache.shardingsphere.dbdiscovery.mysql.exception.mgr.InvalidMGRGroupNameConfigurationException

### ISSUE THREAD

**Issue by MQMMMQM** [apache/shardingsphere#22251]
shardingsphere-proxy 5.2.1

**backend mysql:**
Three MySQL 8.0.30 form an InnoDB cluster
(MGR configured with the MySQL shell)
```
root@192-180-53-191:~$mysql -h192.180.53.191 -P3308 -uroot -pxxxx
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 244
Server version: 8.0.30 MySQL Community Server - GPL

Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
 
mysql> SELECT VARIABLE_VALUE FROM performance_schema.global_variables WHERE VARIABLE_NAME='group_replication_group_name';
+--------------------------------------+
| VARIABLE_VALUE                       |
+--------------------------------------+
| 3bee589a-6642-11ed-81f5-00505690025a |
+--------------------------------------+
1 row in set (0.00 sec)

mysql> SELECT VARIABLE_VALUE FROM performance_schema.global_variables WHERE VARIABLE_NAME='group_replication_single_primary_mode';
+----------------+
| VARIABLE_VALUE |
+----------------+
| ON             |
+----------------+
1 row in set (0.00 sec)

```

**config.yaml**
```
databaseName: database_discovery_mgr

dataSources:
  ds_0:
    url: jdbc:mysql://192.180.53.191:3306/testdb_a?serverTimezone=UTC&useSSL=false
    username: root
    password: xxxx
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://192.180.53.191:3307/testdb_a?serverTimezone=UTC&useSSL=false
    username: root
    password: xxxx
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_2:
    url: jdbc:mysql://192.180.53.191:3308/testdb_a?serverTimezone=UTC&useSSL=false
    username: root
    password: xxxx
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !DB_DISCOVERY
  dataSources:
    readwrite_ds_mgr:
      dataSourceNames:
        - ds_0
        - ds_1
        - ds_2
      discoveryHeartbeatName: mgr-heartbeat
      discoveryTypeName: mgr
  discoveryHeartbeats:
    mgr-heartbeat:
      props:
        keep-alive-cron: '0/1 * * * * ?'
  discoveryTypes:
    mgr:
      type: MySQL.MGR
      props:
        group-name: 3bee589a-6642-11ed-81f5-00505690025a


- !READWRITE_SPLITTING
  dataSources:
    readwrite_s_ds_mgr: 
       dynamicStrategy: 
         autoAwareDataSourceName: readwrite_ds_mgr
         writeDataSourceQueryEnabled: true
       loadBalancerName: random
  
  loadBalancers:
    random: 
      type: RANDOM

```

**error:**
when exec start.sh , err in stdout.log.
```
Exception in thread "main" java.util.concurrent.CompletionException: org.apache.shardingsphere.dbdiscovery.mysql.exception.mgr.InvalidMGRGroupNameConfigurationException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1629)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.shardingsphere.dbdiscovery.mysql.exception.mgr.InvalidMGRGroupNameConfigurationException
	at org.apache.shardingsphere.dbdiscovery.mysql.type.MGRMySQLDatabaseDiscoveryProviderAlgorithm.lambda$checkGroupName$3(MGRMySQLDatabaseDiscoveryProviderAlgorithm.java:123)
	at org.apache.shardingsphere.infra.util.exception.ShardingSpherePreconditions.checkState(ShardingSpherePreconditions.java:41)
	at org.apache.shardingsphere.dbdiscovery.mysql.type.MGRMySQLDatabaseDiscoveryProviderAlgorithm.checkGroupName(MGRMySQLDatabaseDiscoveryProviderAlgorithm.java:122)
	at org.apache.shardingsphere.dbdiscovery.mysql.type.MGRMySQLDatabaseDiscoveryProviderAlgorithm.checkSingleDataSourceEnvironment(MGRMySQLDatabaseDiscoveryProviderAlgorithm.java:103)
	at org.apache.shardingsphere.dbdiscovery.mysql.type.MGRMySQLDatabaseDiscoveryProviderAlgorithm.lambda$runAsyncCheckEnvironment$0(MGRMySQLDatabaseDiscoveryProviderAlgorithm.java:90)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	... 3 more
```

**Comment by zhaojinchao95** [comment]
@MQMMMQM Can you execute `SELECT MEMBER_HOST, MEMBER_PORT, MEMBER_STATE FROM performance_schema.replication_group_members` and show me result.

**Comment by MQMMMQM** [comment]
> 

```
mysql> SELECT MEMBER_HOST, MEMBER_PORT, MEMBER_STATE FROM performance_schema.replication_group_members;
+----------------+-------------+--------------+
| MEMBER_HOST    | MEMBER_PORT | MEMBER_STATE |
+----------------+-------------+--------------+
| 192-180-53-191 |        3306 | ONLINE       |
| 192-180-53-191 |        3308 | ONLINE       |
| 192-180-53-191 |        3307 | ONLINE       |
+----------------+-------------+--------------+
3 rows in set (0.00 sec)
```

**Comment by zhaojinchao95** [comment]
> > 
> 
> ```
> mysql> SELECT MEMBER_HOST, MEMBER_PORT, MEMBER_STATE FROM performance_schema.replication_group_members;
> +----------------+-------------+--------------+
> | MEMBER_HOST    | MEMBER_PORT | MEMBER_STATE |
> +----------------+-------------+--------------+
> | 192-180-53-191 |        3306 | ONLINE       |
> | 192-180-53-191 |        3308 | ONLINE       |
> | 192-180-53-191 |        3307 | ONLINE       |
> +----------------+-------------+--------------+
> 3 rows in set (0.00 sec)
> ```

Can you change MEMBER_HOST 1`92-180-52-191 `to `192.180.53.191`, and try it.

**Comment by MQMMMQM** [comment]
> > > 
> > 
> > 
> > ```
> > mysql> SELECT MEMBER_HOST, MEMBER_PORT, MEMBER_STATE FROM performance_schema.replication_group_members;
> > +----------------+-------------+--------------+
> > | MEMBER_HOST    | MEMBER_PORT | MEMBER_STATE |
> > +----------------+-------------+--------------+
> > | 192-180-53-191 |        3306 | ONLINE       |
> > | 192-180-53-191 |        3308 | ONLINE       |
> > | 192-180-53-191 |        3307 | ONLINE       |
> > +----------------+-------------+--------------+
> > 3 rows in set (0.00 sec)
> > ```
> 
> Can you change MEMBER_HOST `192-180-52-191 `to `192.180.53.191`, and try it.

```
mysql> SELECT MEMBER_HOST, MEMBER_PORT, MEMBER_STATE FROM performance_schema.replication_group_members;
+----------------+-------------+--------------+
| MEMBER_HOST    | MEMBER_PORT | MEMBER_STATE |
+----------------+-------------+--------------+
| 192.180.53.191 |        3306 | ONLINE       |
| 192.180.53.191 |        3307 | ONLINE       |
| 192.180.53.191 |        3308 | ONLINE       |
+----------------+-------------+--------------+
3 rows in set (0.01 sec)
```

```
...
[INFO ] 2022-11-18 18:02:06.532 [Curator-SafeNotifyService-0] org.quartz.impl.StdSchedulerFactory - Quartz scheduler 'MySQL.MGR-database_discovery_mgr-readwrite_ds_mgr' initialized from an externally provided properties instance.
[INFO ] 2022-11-18 18:02:06.532 [Curator-SafeNotifyService-0] org.quartz.impl.StdSchedulerFactory - Quartz scheduler version: 2.3.2
[INFO ] 2022-11-18 18:02:06.629 [Curator-SafeNotifyService-0] org.quartz.core.QuartzScheduler - Scheduler MySQL.MGR-database_discovery_mgr-readwrite_ds_mgr_$_NON_CLUSTERED started.
```
thanks!! it worked
