### ISSUE TITLE
Table by month, cross month query error

### ISSUE THREAD

**Issue by qingchengshi** [apache/shardingsphere#22829]
8:05:21.479 [http-nio-9090-exec-2] WARN  o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver - Resolved [org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : 
 SELECT COUNT(1) FROM attendance_three_well WHERE (is_use = ? AND day_date >= ? AND day_date <= ?) 

### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : 
 SELECT COUNT(1) FROM attendance_three_well WHERE (is_use = ? AND day_date >= ? AND day_date <= ?) 

Caused by: java.lang.NullPointerException: null
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.getValueCaseSensitiveFromTables(GroupByMemoryMergedResult.java:134)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.getValueCaseSensitive(GroupByMemoryMergedResult.java:124)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.init(GroupByMemoryMergedResult.java:73)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.init(GroupByMemoryMergedResult.java:53)
	at org.apache.shardingsphere.infra.merge.result.impl.memory.MemoryMergedResult.<init>(MemoryMergedResult.java:51)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.<init>(GroupByMemoryMergedResult.java:56)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.getGroupByMergedResult(ShardingDQLResultMerger.java:108)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.build(ShardingDQLResultMerger.java:78)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.merge(ShardingDQLResultMerger.java:63)
	at org.apache.shardingsphere.infra.merge.MergeEngine.executeMerge(MergeEngine.java:90)
	at org.apache.shardingsphere.infra.merge.MergeEngine.merge(MergeEngine.java:80)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.mergeQuery(ShardingSpherePreparedStatement.java:393)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.executeQuery(ShardingSpherePreparedStatement.java:182)
	at com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor.queryTotal(PaginationInterceptor.java:259)
	... 139 common frames omitted

**Comment by RaigorJiang** [comment]
Hi @qingchengshi 
Thanks for your feedback, please provide version of ShardingSphere and the sharding configuration.

**Comment by qingchengshi** [comment]
<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.0.0</version>
        </dependency>

spring.shardingsphere.enabled=true
spring.shardingsphere.datasource.names = m1 
spring.shardingsphere.props.sql-show=true
spring.shardingsphere.datasource.m1.type= com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.m1.jdbc-url= jdbc:mysql://127.0.0.1:3306/sy_attendance_gy_1?characterEncoding=UTF-8&rewriteBatchedStatements=true&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
spring.shardingsphere.datasource.m1.username = root
spring.shardingsphere.datasource.m1.password = 123456
spring.shardingsphere.datasource.m1.driver-class-name= com.mysql.cj.jdbc.Driver 
spring.shardingsphere.rules.sharding.tables.attendance_three_well.actual-data-nodes = m1.attendance_three_well_202$->{201..212}
spring.shardingsphere.rules.sharding.tables.attendance_three_well.table-strategy.standard.sharding-column = day_date
spring.shardingsphere.rules.sharding.tables.attendance_three_well.table-strategy.standard.sharding-algorithm-name = table-inline
spring.shardingsphere.rules.sharding.tables.attendance_three_well.key-generator.column = id
spring.shardingsphere.rules.sharding.tables.attendance_three_well.key-generator.type = SNOWFLAKE
spring.shardingsphere.rules.sharding.sharding-algorithms.table-inline.type = CLASS_BASED
spring.shardingsphere.rules.sharding.sharding-algorithms.table-inline.props.strategy = standard
spring.shardingsphere.rules.sharding.sharding-algorithms.table-inline.props.algorithmClassName = com.ms.attendance.threepairs.controller.CommonStandardShardingAlgorithm

**Comment by qingchengshi** [comment]
<dependency&gt;
    <groupId&gt;org.apache.shardingsphere</groupId&gt;
    <artifactId&gt;shardingsphere-jdbc-core-spring-boot-starter</artifactId&gt;
    <version&gt;5.0.0</version&gt;
</dependency&gt;
spring.shardingsphere.enabled=true spring.shardingsphere.datasource.names = m1  spring.shardingsphere.props.sql-show=true spring.shardingsphere.datasource.m1.type= com.zaxxer.hikari.HikariDataSource spring.shardingsphere.datasource.m1.jdbc-url= jdbc:mysql://127.0.0.1:3306/sy_attendance_gy_1?characterEncoding=UTF-8&amp;rewriteBatchedStatements=true&amp;autoReconnect=true&amp;useSSL=false&amp;serverTimezone=Asia/Shanghai spring.shardingsphere.datasource.m1.username = root spring.shardingsphere.datasource.m1.password = 123456 spring.shardingsphere.datasource.m1.driver-class-name= com.mysql.cj.jdbc.Driver  spring.shardingsphere.rules.sharding.tables.attendance_three_well.actual-data-nodes = m1.attendance_three_well_202$-&gt;{201..212} spring.shardingsphere.rules.sharding.tables.attendance_three_well.table-strategy.standard.sharding-column = day_date spring.shardingsphere.rules.sharding.tables.attendance_three_well.table-strategy.standard.sharding-algorithm-name = table-inline spring.shardingsphere.rules.sharding.tables.attendance_three_well.key-generator.column = id spring.shardingsphere.rules.sharding.tables.attendance_three_well.key-generator.type = SNOWFLAKE spring.shardingsphere.rules.sharding.sharding-algorithms.table-inline.type = CLASS_BASED spring.shardingsphere.rules.sharding.sharding-algorithms.table-inline.props.strategy = standard spring.shardingsphere.rules.sharding.sharding-algorithms.table-inline.props.algorithmClassName = com.ms.attendance.threepairs.controller.CommonStandardShardingAlgorithm

**Comment by qingchengshi** [comment]
query criteria   startTime=20221108&endTime=20221209
CommonStandardShardingAlgorithm  assemble tables   ["attendance_three_well_202211","attendance_three_well_202212"] 

11:25:48.410 [http-nio-9090-exec-2] INFO  ShardingSphere-SQL - Logic SQL: SELECT COUNT(1) FROM attendance_three_well WHERE (is_use = ? AND day_date >= ? AND day_date <= ?)
11:25:48.410 [http-nio-9090-exec-2] INFO  ShardingSphere-SQL - SQLStatement: MySQLSelectStatement(limit=Optional.empty, lock=Optional.empty, window=Optional.empty)
11:25:48.411 [http-nio-9090-exec-2] INFO  ShardingSphere-SQL - Actual SQL: m1 ::: SELECT COUNT(1) FROM attendance_three_well_202211 WHERE (is_use = ? AND day_date >= ? AND day_date <= ?) ::: [true, 20221108, 20221209]
11:25:48.411 [http-nio-9090-exec-2] INFO  ShardingSphere-SQL - Actual SQL: m1 ::: SELECT COUNT(1) FROM attendance_three_well_202212 WHERE (is_use = ? AND day_date >= ? AND day_date <= ?) ::: [true, 20221108, 20221209]


 @Override
    public Collection<String> doSharding(Collection<String> collection, RangeShardingValue<Long> rangeShardingValue) {
        // 逻辑表名
        String logicTableName = rangeShardingValue.getLogicTableName();
//        // 范围参数
        Range<Long> valueRange = rangeShardingValue.getValueRange();
        Set<String> queryRangeTables = extracted(logicTableName,valueRange.lowerEndpoint(),valueRange.upperEndpoint());
        ArrayList<String> tables = new ArrayList<>(collection);
        tables.retainAll(queryRangeTables);
        System.out.println(JSON.toJSONString(tables));
        return tables;
    }

**Comment by RaigorJiang** [comment]
Sorry, the code you provided contains undeclared functions, which we cannot test to verify.

In addition, when there is a lot of text, it is best to use markdown syntax. The friendly readability allows people who are willing to help you to analyze the problem faster.
