### ISSUE TITLE
Sharding cannot be initialized correctly under multithreading

### ISSUE THREAD

**Issue by zhangpan-soft** [apache/shardingsphere#22933]
## Bug Report

During the initial loading of sharding, if the initial loading is multi-threaded and SQL queries are executed under multiple threads at the same time, class loading will be performed, including Parser classes, javax packages, etc However, because it is multithreaded at this time, multiple threads will load classes, which will result in concurrent loading errors, and the classes cannot be loaded correctly, resulting in the inability of all sharding supported sql to run.

jdk version: 11
sharding-jdbc version: 4.0.1

There are also some other mistakes. Here are just two

eg:
```
java.util.concurrent.ExecutionException: java.lang.ExceptionInInitializerError
	java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	com.youpin.risk.data.collection.domain.handle.impl.RiskForecastDataCollection.execute(RiskForecastDataCollection.java:65)
	com.youpin.risk.data.collection.domain.handle.impl.RiskForecastDataCollection.execute(RiskForecastDataCollection.java:29)
	com.youpin.risk.data.collection.app.job.RiskForecastJob.executeTest(RiskForecastJob.java:61)
	java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	java.base/java.lang.reflect.Method.invoke(Unknown Source)
	com.xxl.job.core.handler.impl.MethodJobHandler.execute(MethodJobHandler.java:31)
	com.xxl.job.core.thread.JobThread.run(JobThread.java:163)
```

```
Exception:java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.xxl.job.core.handler.impl.MethodJobHandler.execute(MethodJobHandler.java:31)
	at com.xxl.job.core.thread.JobThread.run(JobThread.java:163)
Caused by: java.util.concurrent.ExecutionException: java.lang.ExceptionInInitializerError
	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.youpin.risk.data.collection.domain.handle.impl.RiskForecastDataCollection.execute(RiskForecastDataCollection.java:65)
	at com.youpin.risk.data.collection.domain.handle.impl.RiskForecastDataCollection.execute(RiskForecastDataCollection.java:29)
	at com.youpin.risk.data.collection.app.job.RiskForecastJob.executeTest(RiskForecastJob.java:60)
	... 6 more
Caused by: java.lang.ExceptionInInitializerError
	at org.apache.shardingsphere.sql.parser.SQLParseEngine.parse0(SQLParseEngine.java:70)
	at org.apache.shardingsphere.sql.parser.SQLParseEngine.parse(SQLParseEngine.java:52)
	at org.apache.shardingsphere.core.route.router.sharding.ShardingRouter.parse$original$mTveoZ8A(ShardingRouter.java:86)
	at org.apache.shardingsphere.core.route.router.sharding.ShardingRouter.parse$original$mTveoZ8A$accessor$ARs4izHS(ShardingRouter.java)
	at org.apache.shardingsphere.core.route.router.sharding.ShardingRouter$auxiliary$QXFNGdDx.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at org.apache.shardingsphere.core.route.router.sharding.ShardingRouter.parse(ShardingRouter.java)
	at org.apache.shardingsphere.core.route.PreparedStatementRoutingEngine.route(PreparedStatementRoutingEngine.java:61)
	at org.apache.shardingsphere.core.PreparedQueryShardingEngine.route(PreparedQueryShardingEngine.java:59)
	at org.apache.shardingsphere.core.BaseShardingEngine.executeRoute(BaseShardingEngine.java:85)
	at org.apache.shardingsphere.core.BaseShardingEngine.shard(BaseShardingEngine.java:68)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.shard(ShardingPreparedStatement.java:249)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:190)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:89)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
	at com.sun.proxy.$Proxy161.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80)
	at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:152)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:85)
	at com.sun.proxy.$Proxy183.findNeedForecastOldOrder(Unknown Source)
	at com.youpin.risk.data.collection.infrastructure.repository.impl.LeaseOrderRepositoryImpl.findNeedForecastOrder(LeaseOrderRepositoryImpl.java:40)
	at com.youpin.risk.data.collection.infrastructure.repository.impl.LeaseOrderRepositoryImpl$$FastClassBySpringCGLIB$$6d3b2673.invoke()
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.youpin.risk.data.collection.infrastructure.repository.impl.LeaseOrderRepositoryImpl$$EnhancerBySpringCGLIB$$7a9d5bb4.findNeedForecastOrder()
	at com.youpin.risk.data.collection.domain.threads.forecast.producter.ProducerThread.run(ProducerThread.java:35)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:278)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:421)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:721)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:662)
	at org.apache.shardingsphere.sql.parser.core.rule.jaxb.loader.extractor.ExtractorRuleDefinitionEntityLoader.load(ExtractorRuleDefinitionEntityLoader.java:39)
	at org.apache.shardingsphere.sql.parser.core.rule.registry.ParseRuleRegistry.initParseRuleDefinition(ParseRuleRegistry.java:69)
	at org.apache.shardingsphere.sql.parser.core.rule.registry.ParseRuleRegistry.(ParseRuleRegistry.java:65)
	at org.apache.shardingsphere.sql.parser.core.rule.registry.ParseRuleRegistry.(ParseRuleRegistry.java:61)
	... 53 more
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at javax.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:122)
	at javax.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:155)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:276)
	... 60 more

```

**Comment by azexcy** [comment]
Hi @zhangpan-soft , the version of sharding-jdbc-4.0.1 is deprecated, please try the latest version

**Comment by TeslaCN** [comment]
Obviously, the root cause is `java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory`
