### ISSUE TITLE
IndexOutOfBoundsException occured at ShardingDALResultMerger.merge() when sql has multi ResultSet

### ISSUE THREAD

**Issue by youlongchengfeng** [apache/shardingsphere#23325]
**Which version of ShardingSphere did you use?**
shardingshpere-jdbc-5.2.1

**Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?**
ShardingSphere-JDBC

**use sql**
```
set @num := 0, @areaId := 0;
select
  t.name, @num := if(@areaId = t.second_level_area_id, @num + 1, 1) as my_row_number,
	  @areaId := t.second_level_area_id as dummy
from
  t_device t
order by
  t.second_level_area_id asc
```

the sql have used mysql session variable, statement endwith semicolon so may be parsed by mysql to 2 sql statement.

because of **set @num := 0, @areaId := 0;** has no resultSet, cause the exception at resultset merge phase.

```
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.apache.shardingsphere.sharding.merge.dal.ShardingDALResultMerger.merge(ShardingDALResultMerger.java:79)
	at org.apache.shardingsphere.infra.merge.MergeEngine.executeMerge(MergeEngine.java:82)
	at org.apache.shardingsphere.infra.merge.MergeEngine.merge(MergeEngine.java:71)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.mergeQuery(ShardingSpherePreparedStatement.java:517)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.getResultSet(ShardingSpherePreparedStatement.java:465)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:69)
	at com.sun.proxy.$Proxy192.getResultSet(Unknown Source)
```

```
@RequiredArgsConstructor
public final class ShardingDALResultMerger implements ResultMerger {
    
    private final String databaseName;
    
    private final ShardingRule shardingRule;
    
    @Override
    public MergedResult merge(final List<QueryResult> queryResults, final SQLStatementContext<?> sqlStatementContext,
                              final ShardingSphereDatabase database, final ConnectionContext connectionContext) throws SQLException {
        SQLStatement dalStatement = sqlStatementContext.getSqlStatement();
        String schemaName = sqlStatementContext.getTablesContext().getSchemaName().orElseGet(() -> DatabaseTypeEngine.getDefaultSchemaName(sqlStatementContext.getDatabaseType(), database.getName()));
        if (dalStatement instanceof MySQLShowDatabasesStatement) {
            return new LocalDataMergedResult(Collections.singleton(new LocalDataQueryResultRow(databaseName)));
        }
        ShardingSphereSchema schema = database.getSchema(schemaName);
        if (dalStatement instanceof MySQLShowTablesStatement) {
            return new LogicTablesMergedResult(shardingRule, sqlStatementContext, schema, queryResults);
        }
        if (dalStatement instanceof MySQLShowTableStatusStatement) {
            return new ShowTableStatusMergedResult(shardingRule, sqlStatementContext, schema, queryResults);
        }
        if (dalStatement instanceof MySQLShowIndexStatement) {
            return new ShowIndexMergedResult(shardingRule, sqlStatementContext, schema, queryResults);
        }
        if (dalStatement instanceof MySQLShowCreateTableStatement) {
            return new ShowCreateTableMergedResult(shardingRule, sqlStatementContext, schema, queryResults);
        }
        return new TransparentMergedResult(queryResults.get(0));
    }
}
```

cause the exception's code is **queryResults.get(0)**,there has no size safety decide.

is this a bug?

**Comment by strongduanmu** [comment]
Hi @youlongchengfeng, thank you for your feedback. Can you provide your configuration?

**Comment by youlongchengfeng** [comment]
> Hi @youlongchengfeng, thank you for your feedback. Can you provide your configuration?

```
	<bean id="ds0" class="com.alibaba.druid.pool.DruidDataSource" init-method="init" destroy-method="close">
		<property name="url">
			<value>${jdbc.url}</value>
		</property>
		<property name="username">
			<value>${jdbc.username}</value>
		</property>
		<property name="password">
			<value>${jdbc.password}</value>
		</property>
		<property name="initialSize">
			<value>${jdbc.initialSize}</value>
		</property>
		<property name="maxActive">
			<value>${jdbc.maxActive}</value>
		</property>
	</bean>
	
	<sharding:sharding-algorithm id="myTableHintShardingAlgorithm" type="CLASS_BASED">
	    <props>
	        <prop key="strategy">hint</prop>
	        <prop key="algorithmClassName">com.oty.sys.sharding.algorithm.MyTableHintShardingAlgorithm</prop>
	    </props>
	</sharding:sharding-algorithm>
	
    <sharding:hint-strategy id="tableShardingStrategy" algorithm-ref="myTableHintShardingAlgorithm" />
	<sharding:rule id="shardingRule">
        <sharding:table-rules>
            <sharding:table-rule logic-table="t_device_param_record" actual-data-nodes="ds0.t_device_param_record_2022_06_01,ds0.t_device_param_record" table-strategy-ref="tableShardingStrategy" />
        </sharding:table-rules>
    </sharding:rule>
	
    <shardingsphere:data-source id="shardingDataSource" data-source-names="ds0" rule-refs="shardingRule">
        <props>
            <prop key="sql-show">true</prop>
        </props>
    </shardingsphere:data-source>
```
