### ISSUE TITLE
Startup failed when both have XA and BASE dependencies

### ISSUE THREAD

**Issue by FlyingZC** [apache/shardingsphere#23351]
## Bug Report
Startup failed when both have XA and BASE dependencies

### Which version of ShardingSphere did you use?
Master.

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
Proxy.

### Expected behavior
Start successfully.

### Actual behavior
```
Exception in thread "main" org.apache.shardingsphere.infra.util.spi.exception.ServiceProviderNotFoundServerException: SPI-00001: No implementation class load from SPI `org.apache.shardingsphere.transaction.xa.spi.XATransactionManagerProvider` with type `Seata`.
	at org.apache.shardingsphere.infra.util.spi.type.typed.TypedSPIRegistry.getRegisteredService(TypedSPIRegistry.java:117)
	at org.apache.shardingsphere.transaction.xa.XAShardingSphereTransactionManager.init(XAShardingSphereTransactionManager.java:67)
	at org.apache.shardingsphere.transaction.ShardingSphereTransactionManagerEngine.lambda$init$0(ShardingSphereTransactionManagerEngine.java:63)
	at java.util.Map.forEach(Map.java:630)
	at org.apache.shardingsphere.transaction.ShardingSphereTransactionManagerEngine.init(ShardingSphereTransactionManagerEngine.java:63)
	at org.apache.shardingsphere.transaction.rule.TransactionRule.createTransactionManagerEngine(TransactionRule.java:80)
	at org.apache.shardingsphere.transaction.rule.TransactionRule.<init>(TransactionRule.java:62)
	at org.apache.shardingsphere.transaction.rule.builder.TransactionRuleBuilder.build(TransactionRuleBuilder.java:36)
	at org.apache.shardingsphere.transaction.rule.builder.TransactionRuleBuilder.build(TransactionRuleBuilder.java:32)
	at org.apache.shardingsphere.infra.rule.builder.global.GlobalRulesBuilder.buildRules(GlobalRulesBuilder.java:54)
	at org.apache.shardingsphere.mode.metadata.MetaDataContextsFactory.create(MetaDataContextsFactory.java:92)
	at org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.build(ClusterContextManagerBuilder.java:56)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.createContextManager(BootstrapInitializer.java:73)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.init(BootstrapInitializer.java:60)
	at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:53)
```

### Reason analyze (If you can)
When I confiured `BASE` transaction
```yaml
transaction:
  defaultType: BASE
  providerType: Seata
```
`XAShardingSphereTransactionManager` wants to create `XATransactionManagerProvider` with type `Seata`.We need to exclude the type of `Seata` when init `XATransactionManagerProvider`.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Both have XA and BASE dependencies,then start fails.

**Comment by FlyingZC** [comment]
Now only the current transaction manager will be created,this problem will not occur again.Fixed by #25676
