### ISSUE TITLE
Transaction operations may fail while metadata is being refreshed

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#23366]
### Which version of ShardingSphere did you use?
master f44a4995

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
Transaction operation blocked or succeeded

### Actual behavior
```java
java.lang.NullPointerException: Cannot invoke "org.apache.shardingsphere.transaction.xa.spi.XATransactionManagerProvider.getTransactionManager()" because "this.xaTransactionManagerProvider" is null
	at org.apache.shardingsphere.transaction.xa.XAShardingSphereTransactionManager.rollback(XAShardingSphereTransactionManager.java:129)
	at org.apache.shardingsphere.proxy.backend.communication.jdbc.transaction.BackendTransactionManager.rollback(BackendTransactionManager.java:96)
	at org.apache.shardingsphere.proxy.backend.communication.ProxySQLExecutor.doExecuteWithImplicitCommitTransaction(ProxySQLExecutor.java:171)
	at org.apache.shardingsphere.proxy.backend.communication.ProxySQLExecutor.execute(ProxySQLExecutor.java:151)
	at org.apache.shardingsphere.proxy.backend.communication.DatabaseCommunicationEngine.execute(DatabaseCommunicationEngine.java:176)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:92)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:110)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:77)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

#### Configuration
- server.yaml
```yaml
#mode:
#  type: Cluster
#  repository:
#    type: ZooKeeper
#    props:
#      namespace: governance_ds
#      server-lists: localhost:2181
#      retryIntervalMilliseconds: 500
#      timeToLiveSeconds: 60
#      maxRetries: 3
#      operationTimeoutMilliseconds: 500
#
#authority:
#  users:
#    - user: root@%
#      password: root
#  privilege:
#    type: ALL_PERMITTED

transaction:
  defaultType: XA
  providerType: Atomikos
```
- config-sharding.yaml
```
# two dataSources.
```

#### Steps
1. Execute a RDL like `CREATE SHARDING TABLE RULE` or `ALTER SHARDING TABLE RULE`;
2. Execute DML statement immediately

**Comment by RaigorJiang** [comment]
@FlyingZC  Ok, let's wait for metadata improvements to fix this.

**Comment by FlyingZC** [comment]
Fixed by https://github.com/apache/shardingsphere/issues/25485

**Comment by cookiejoo** [comment]
But now I also have this problem, how can this problem be solved?

**Comment by RaigorJiang** [comment]
> But now I also have this problem, how can this problem be solved?

@cookiejoo Please describe the issue you encountered in detail: version, phenomenon, and how to reproduce it?
