### ISSUE TITLE
mysql add information_schema rule,but failed when query metadata use "Lower case" column 

### ISSUE THREAD

**Issue by bluerfish** [apache/shardingsphere#23547]
version : shardingproxy 5.3 (include 5.0,5.2)

question : we use dts  to access shardingproxy, it will send "select schema_name from information_schema.SCHEMATA"

here is mysql config:

databaseName: information_schema
dataSources:
  ds_0:
    url: jdbc:mysql://ip_address/information_schema?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root 
    password: ...
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

on proxy : 
when execute  select SCHEMA_NAME from information_schema.SCHEMATA or select * from information_schema.SCHEMATA it will return correct result . but when excute  select schema_name from  information_schema.SCHEMATA it will failed, output is 
ERROR: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 1 。

on actual db:
execute  select schema_name from  information_schema.SCHEMATA  it also return correct result.

here is logs:
---------------------------------------------------------------------------------------------------------------------------------------
[INFO ] 2023-01-13 19:19:35.488 [epollEventLoopGroup-3-1] o.a.s.p.b.h.a.e.AbstractDatabaseMetadataExecutor$DefaultDatabaseMetadataExecutor - Actual SQL: ds_0 ::: selec
t * from information_schema.SCHEMATA
[INFO ] 2023-01-13 19:19:35.492 [epollEventLoopGroup-3-1] o.a.s.p.b.h.a.e.AbstractDatabaseMetadataExecutor$DefaultDatabaseMetadataExecutor - Actual SQL: ds_0 ::: selec
t * from information_schema.SCHEMATA
[INFO ] 2023-01-13 19:19:43.737 [epollEventLoopGroup-3-1] o.a.s.p.b.h.a.e.AbstractDatabaseMetadataExecutor$DefaultDatabaseMetadataExecutor - Actual SQL: ds_0 ::: selec
t SCHEMA_NAME  from information_schema.SCHEMATA
[INFO ] 2023-01-13 19:19:43.741 [epollEventLoopGroup-3-1] o.a.s.p.b.h.a.e.AbstractDatabaseMetadataExecutor$DefaultDatabaseMetadataExecutor - Actual SQL: ds_0 ::: selec
t SCHEMA_NAME  from information_schema.SCHEMATA
[INFO ] 2023-01-13 19:19:53.885 [epollEventLoopGroup-3-1] o.a.s.p.b.h.a.e.AbstractDatabaseMetadataExecutor$DefaultDatabaseMetadataExecutor - Actual SQL: ds_0 ::: select schema_name from information_schema.SCHEMATA
[INFO ] 2023-01-13 19:19:53.889 [epollEventLoopGroup-3-1] o.a.s.p.b.h.a.e.AbstractDatabaseMetadataExecutor$DefaultDatabaseMetadataExecutor - Actual SQL: ds_0 ::: select schema_name from information_schema.SCHEMATA
[ERROR] 2023-01-13 19:19:53.892 [epollEventLoopGroup-3-1] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
java.sql.SQLException: java.lang.ArrayIndexOutOfBoundsException
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
        at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:437)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1020)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
        at org.apache.shardingsphere.proxy.backend.handler.admin.executor.AbstractDatabaseMetadataExecutor$DefaultDatabaseMetadataExecutor.getSourceData(AbstractDatabaseMetadataExecutor.java:216)
        at org.apache.shardingsphere.proxy.backend.handler.admin.executor.AbstractDatabaseMetadataExecutor.execute(AbstractDatabaseMetadataExecutor.java:76)
        at org.apache.shardingsphere.proxy.backend.handler.admin.DatabaseAdminQueryBackendHandler.execute(DatabaseAdminQueryBackendHandler.java:56)
        at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:94)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:111)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:78)

**Comment by RaigorJiang** [comment]
@bluerfish Thanks for your feedback, we will investigate.

**Comment by RaigorJiang** [comment]
Hi @tuichenchuxin , can you take a look at this question?

**Comment by tuichenchuxin** [comment]
From my point of view, the backend database should not be configured as `information_schema`, because ShardingSphere proxy is designed as a database proxy, so it maintains its own `information_schema`, which will have some conflicts with the real `information_schema`. This could be the root cause of the capitalization issue.
You can use debug to see the cause of this problem and try to fix it.

**Comment by RaigorJiang** [comment]
Closed due to no response.
If this problem persists, please reopen it or submit a new one.
