### ISSUE TITLE
Error connecting to ShardingSphere using sqlalchemy asyncpg for postgres.

### ISSUE THREAD

**Issue by windson** [apache/shardingsphere#23878]
## Bug Report
I am trying to connect to shardingsphere deployed on container that connects to postgresql. Through distsql the insert commands are working fine. But when I start leveraging this deployment to any application such as Python SQLAlchemy using Asyncpg, it shows the utf-8 error as detailed below in the stacktrace.

The demo code is used:

requirements.txt
```
alembic==1.9.2
asyncpg==0.27.0
greenlet==2.0.2
Mako==1.2.4
MarkupSafe==2.1.2
psycopg==3.1.8
SQLAlchemy==2.0.0
typing_extensions==4.4.0
```

```
## models.py
from sqlalchemy import Column, ForeignKey, Integer, String
from sqlalchemy import update as sqlalchemy_update
from sqlalchemy.future import select
from sqlalchemy.orm import relationship

from database import Base, async_db_session

class ModelAdmin:
    @classmethod
    async def create(cls, **kwargs):
        async_db_session.add(cls(**kwargs))
        await async_db_session.commit()

    @classmethod
    async def update(cls, id, **kwargs):
        query = (
            sqlalchemy_update(cls)
            .where(cls.id == id)
            .values(**kwargs)
            .execution_options(synchronize_session="fetch")
        )

        await async_db_session.execute(query)
        await async_db_session.commit()

    @classmethod
    async def get(cls, id):
        query = select(cls).where(cls.id == id)
        results = await async_db_session.execute(query)
        (result,) = results.one()
        return result


class User(Base, ModelAdmin):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, autoincrement=True)
    full_name = Column(String)
    # posts = relationship("Post")

    # required in order to acess columns with server defaults
    # or SQL expression defaults, subsequent to a flush, without
    # triggering an expired load
    __mapper_args__ = {"eager_defaults": True}

    def __repr__(self):
        return (
            f"<{self.__class__.__name__}("
            f"id={self.id}, "
            f"full_name={self.full_name}, "
            f"posts={self.posts}, "
            f")>"
        )
```

```
## database.py
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import declarative_base, sessionmaker

Base = declarative_base()


class AsyncDatabaseSession:
    def __init__(self):
        self._session = None
        self._engine = None

    def __getattr__(self, name):
        return getattr(self._session, name)

    async def init(self):
        
        self._engine = create_async_engine(
            # postgresql+asyncpg://<db_username>:<db_secret>@<db_host>:<db_port>/<db_name>
            "postgresql+asyncpg://root:root@0.0.0.0:13308/sharding_db",
            echo=True,
        )
        
        self._session = sessionmaker(
            self._engine, expire_on_commit=False, class_=AsyncSession
        )()

    async def create_all(self):
        print('4'*20)
        async with self._engine.begin() as conn:
            
            print(conn)
            await conn.run_sync(Base.metadata.drop_all)
            await conn.run_sync(Base.metadata.create_all)


async_db_session = AsyncDatabaseSession()
```

```
## main.py
import asyncio

from database import async_db_session
#from models import Post, User
from models import User


async def init_app():
    await async_db_session.init()
    await async_db_session.create_all()


async def create_user():
    await User.create(full_name="John Doe")
    user = await User.get(1)
    return user.id

async def update_user(id, full_name):
    await User.update(id, full_name="John Not Doe")
    user = await User.get(id)
    return user.full_name

async def async_main():
    await init_app()
    user_id = await create_user()
    await update_user(user_id, "John Not Doe")
    # await create_post(user_id, "hello world")


asyncio.run(async_main())
```
### Which version of ShardingSphere did you use?

5.3.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

It must establish connection via sqlalchemy.

### Actual behavior
Error as follows:

```
Traceback (most recent call last):
  File "/home/ec2-user/environment/pgspherealchemy/main.py", line 38, in <module>
    asyncio.run(async_main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/ec2-user/environment/pgspherealchemy/main.py", line 32, in async_main
    await init_app()
  File "/home/ec2-user/environment/pgspherealchemy/main.py", line 10, in init_app
    await async_db_session.create_all()
  File "/home/ec2-user/environment/pgspherealchemy/database.py", line 31, in create_all
    async with self._engine.begin() as conn:
  File "/usr/local/lib/python3.9/contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/engine.py", line 966, in begin
    async with conn:
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/base.py", line 140, in __aenter__
    return await self.start(is_ctxmanager=True)  # type: ignore
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/engine.py", line 221, in start
    await (greenlet_spawn(self.sync_engine.connect))
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 165, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3245, in connect
    return self._connection_cls(self)
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3269, in raw_connection
    return self.pool.connect()
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1255, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    self._dec_overflow()
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 166, in _do_get
    return self._create_connection()
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 903, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 640, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 580, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 821, in connect
    await_only(self.asyncpg.connect(*arg, **kw)),
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 102, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 160, in greenlet_spawn
    value = await result
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/asyncpg/connection.py", line 2092, in connect
    return await connect_utils._connect(
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 881, in _connect
    return await _connect_addr(
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 773, in _connect_addr
    return await __connect_addr(params, timeout, True, *args)
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 831, in __connect_addr
    await compat.wait_for(connected, timeout=timeout)
  File "/home/ec2-user/environment/pgspherealchemy/env/lib/python3.9/site-packages/asyncpg/compat.py", line 56, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
asyncpg.exceptions.PostgresSystemError: 'utf-8'
```

### Reason analyze (If you can)

Possible reasons: https://docs.sqlalchemy.org/en/14/errors.html#error-4xp6

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

```
docker run -d -v /home/ec2-user/environment/pgsphere/conf:/opt/shardingsphere-proxy/conf -e PORT=3308 -p13308:3308 apache/shardingsphere-proxy:latest
```

```
psql -U root -h 0.0.0.0 -p 13308 -d sharding_db
```

```
CREATE SHARDING TABLE RULE users(
STORAGE_UNITS(ds_0,ds_1),
SHARDING_COLUMN=id,
TYPE(NAME="hash_mod",PROPERTIES("sharding-count"="4")),
KEY_GENERATE_STRATEGY(COLUMN=id,TYPE(NAME="snowflake"))
);
```
```
CREATE TABLE users (
        id SERIAL NOT NULL, 
        full_name VARCHAR, 
        PRIMARY KEY (id)
);
```

And using the python `pip install -r requirements.txt` and then `python main.py`

**Comment by TeslaCN** [comment]
This may be caused by #23885.

**Comment by RaigorJiang** [comment]
Hi @windson ,
Is there an exception log in Proxy?

**Comment by TeslaCN** [comment]
Hi @windson 
Could you try the master branch? #23885 has been fixed.
