### ISSUE TITLE
 Error while starting hibernate application by connecting to lower version of postgres through ShardingSphere

### ISSUE THREAD

**Issue by jyotisharma7** [apache/shardingsphere#23948]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
ShardingSphere Proxy 5.3.2
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
With higher version of postgres hibernate application starts without any error. The application should start without any error for lower versions of postgres also.
### Actual behavior
With lower version of postgres error occurs.
### Reason analyze (If you can)
```
[INFO ] 2023-02-02 17:44:19.675 [Connection-1-ThreadExecutor] o.a.s.p.b.h.a.e.AbstractDatabaseMetaDataExecutor$DefaultDatabaseMetaDataExecutor - Actual SQL: oas_collaborators_invite_service_dev ::: SELECT typinput='array_in'::regproc as is_array, typtype, typname, pg_type.oid   FROM pg_catalog.pg_type   LEFT JOIN (select ns.oid as nspoid, ns.nspname, r.r           from pg_namespace as ns           join ( select s.r, (current_schemas(false))[s.r] as nspname                    from generate_series(1, array_upper(current_schemas(false), 1)) as s(r) ) as r          using ( nspname )        ) as sp     ON sp.nspoid = typnamespace  WHERE pg_type.oid = ?  ORDER BY sp.r, pg_type.oid DESC
[ERROR] 2023-02-02 17:44:19.682 [Connection-1-ThreadExecutor] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
org.postgresql.util.PSQLException: No value specified for parameter 1.
	at org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:284)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:340)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.apache.shardingsphere.proxy.backend.handler.admin.executor.AbstractDatabaseMetaDataExecutor$DefaultDatabaseMetaDataExecutor.getSourceData(AbstractDatabaseMetaDataExecutor.java:225)
	at org.apache.shardingsphere.proxy.backend.handler.admin.executor.AbstractDatabaseMetaDataExecutor.execute(AbstractDatabaseMetaDataExecutor.java:76)
	at org.apache.shardingsphere.proxy.backend.handler.admin.DatabaseAdminQueryBackendHandler.execute(DatabaseAdminQueryBackendHandler.java:56)
	at org.apache.shardingsphere.proxy.frontend.postgresql.command.query.extended.Portal.bind(Portal.java:103)
	at org.apache.shardingsphere.proxy.frontend.postgresql.command.query.extended.bind.PostgreSQLComBindExecutor.execute(PostgreSQLComBindExecutor.java:53)
	at org.apache.shardingsphere.proxy.frontend.postgresql.command.query.extended.PostgreSQLAggregatedCommandExecutor.execute(PostgreSQLAggregatedCommandExecutor.java:41)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:110)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:77)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Pace2Car** [comment]
It looks like your Actual SQL did not successfully replace the parameter to the placeholder: `?`, Have you checked to see if the problem is caused by the ORM framework? Execute the same SQL not through ShardingSphere

**Comment by jyotisharma7** [comment]
The problem is not caused by ORM framework as the same SQL goes through when we dont use ShardingSphere.

**Comment by Pace2Car** [comment]
Could you please provide a simple example to reproduce this problem?
> Include your configuration after desensitization and which version of Postgres are you using

**Comment by TeslaCN** [comment]
The root cause may be the same as https://github.com/apache/shardingsphere/issues/22341.

**Comment by jyotisharma7** [comment]
Hi @Pace2Car Here is a sample application https://github.com/jyotisharma7/HibernateSpring. You can run it with lower version of postgres.
It is a minor modification to https://github.com/minnela/SpringBootHibernateJPA in Spring.properties and a custom class.
It now points to ShardingSphere database and ignores select from information_schema sequences.

**Comment by RaigorJiang** [comment]
Hi @jyotisharma7 
I think #25258 has fixed this issue, you can try master now.
