### ISSUE TITLE
Support order by MySQL VARBINARY primary key

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#24107]
### Is your feature request related to a problem?
Yes

### Describe the feature you would like.
MySQL is used, table primary key is VARBINARY type, it could be ordered in MySQL, but failed in ShardingSphere proxy and JDBC driver.
The reason is VARBINARY column value type is byte array, it doesn't implement Comparable interface.

Exception example:
```
org.apache.shardingsphere.sharding.exception.data.NotImplementComparableValueException: Order by value must implements Comparable.
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.lambda$getOrderValues$0(OrderByValue.java:113)
	at org.apache.shardingsphere.infra.util.exception.ShardingSpherePreconditions.checkState(ShardingSpherePreconditions.java:41)
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.getOrderValues(OrderByValue.java:113)
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.next(OrderByValue.java:105)
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByStreamMergedResult.orderResultSetsToQueue(OrderByStreamMergedResult.java:57)
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByStreamMergedResult.<init>(OrderByStreamMergedResult.java:50)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.build(ShardingDQLResultMerger.java:100)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.merge(ShardingDQLResultMerger.java:71)
	at org.apache.shardingsphere.infra.merge.MergeEngine.executeMerge(MergeEngine.java:81)
	at org.apache.shardingsphere.infra.merge.MergeEngine.merge(MergeEngine.java:71)
```

Example table schema:
```
CREATE TABLE `t_order` (
  `order_id` varbinary(64) NOT NULL,
  `user_id` int(11) NOT NULL,
  `status` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

Example query SQL:
```
mysql> select * from t_order order by order_id limit 3;
ERROR 20024 (44000): Order by value must implements Comparable.
```

**Comment by Phixsura** [comment]
PR #38699.

Root cause: in `OrderByValue.getOrderValues`, the precondition `value instanceof Comparable` throws `NotImplementComparableValueException` when the value is a `byte[]`, because Java arrays do not implement `Comparable`. MySQL VARBINARY/BINARY columns surface as `byte[]` through JDBC, so any `ORDER BY` over such a column fails in the sharding merge layer even though native MySQL accepts the same query.

Fix wraps `byte[]` values in a small `ComparableByteArray` adapter that orders unsigned-lexicographically (matching MySQL's binary collation). Other types still flow through the existing precondition.

Tests: 5 cases on the new adapter (equal, single-byte diff, unsigned high byte, shorter-prefix-is-less, empty arrays) and an additional `OrderByValue` ASC scenario where `{1, 2}` sorts before `{0x80}` to confirm the unsigned ordering reaches the merge comparison.
