### ISSUE TITLE
DBeaver exec sql print error

### ISSUE THREAD

**Issue by wangjianme** [apache/shardingsphere#24330]
Bug Detail:

[INFO ] 2023-02-24 09:00:48.689 [Connection-14-ThreadExecutor] ShardingSphere-SQL - Logic SQL: SELECT * from stud
LIMIT 0, 200
[INFO ] 2023-02-24 09:00:48.689 [Connection-14-ThreadExecutor] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * from stud
LIMIT 0, 200
[ERROR] 2023-02-24 09:00:48.721 [Connection-13-ThreadExecutor] o.a.s.p.f.c.CommandExecutorTask - Exception occur:
java.lang.IndexOutOfBoundsException: Index 20 out of bounds for length 20
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:359)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at org.apache.shardingsphere.sqlfederation.advanced.resultset.SQLFederationResultSetMetaData.getColumnName(SQLFederationResultSetMetaData.java:111)
        at org.apache.shardingsphere.infra.executor.sql.execute.result.query.impl.driver.jdbc.metadata.JDBCQueryResultMetaData.getColumnName(JDBCQueryResultMetaData.java:47)
        at org.apache.shardingsphere.proxy.backend.response.header.query.QueryHeaderBuilderEngine.build(QueryHeaderBuilderEngine.java:51)
        at org.apache.shardingsphere.proxy.backend.communication.DatabaseCommunicationEngine.processExecuteFederation(DatabaseCommunicationEngine.java:226)
        at org.apache.shardingsphere.proxy.backend.communication.DatabaseCommunicationEngine.execute(DatabaseCommunicationEngine.java:168)
        at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:92)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:110)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:77)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

UI Tool:
![image](https://user-images.githubusercontent.com/26622668/221066862-0f897ed2-3dd2-47a3-9e49-46531c39192a.png)

Bug Png:
![image](https://user-images.githubusercontent.com/26622668/221066908-15a2d5a4-af1e-47d2-af47-bb0c65fce24b.png)

**Comment by tuichenchuxin** [comment]
We need more information to judge this issue. Such as configuration, version, reproduction steps, etc.

**Comment by xize0** [comment]
I have the same problem. Have you solved it yet？ @wangjianme  
Version ： sharding-proxy5.3.0

**Comment by crcjwice123** [comment]
<img width="1193" alt="image" src="https://github.com/apache/shardingsphere/assets/5734188/324310ff-b0e8-4ddb-91fa-7c177a20dd48">
when use dbreaver to connect and select from logical table, the sharding is successfully, but seeing IndexOutOfBoundsException
