### ISSUE TITLE
Questions About Version 5.3.1 Proxy Composite Sharding Algorithm

### ISSUE THREAD

**Issue by xxyxlyy** [apache/shardingsphere#24368]
I had a question about a custom compound sharding algorithm. After editing the shard algorithm, the middleware prompt does not implement the interface, but the interface is implemented in the program.

Error message is as follows

Exception in thread "main" java.lang.AbstractMethodError: Receiver class com.mysql.sharding.proxy.complex.OrderTableComplex does not define or inherit an implementation of the resolved method 'abstract void init(java.util.Properties)' of interface org.apache.shardingsphere.infra.util.spi.lifecycle.SPIPostProcessor.
 at org.apache.shardingsphere.infra.util.spi.type.typed.TypedSPIRegistry.findRegisteredService(TypedSPIRegistry.java:66)
 at org.apache.shardingsphere.infra.util.spi.type.typed.TypedSPIRegistry.getRegisteredService(TypedSPIRegistry.java:113)
 at org.apache.shardingsphere.infra.algorithm.ShardingSphereAlgorithmFactory.createAlgorithm(ShardingSphereAlgorithmFactory.java:41)
 at org.apache.shardingsphere.sharding.rule.ShardingRule.lambda$new$0(ShardingRule.java:120)
 at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
 at org.apache.shardingsphere.sharding.rule.ShardingRule.<init>(ShardingRule.java:120)
 at org.apache.shardingsphere.sharding.rule.builder.ShardingRuleBuilder.build(ShardingRuleBuilder.java:41)
 at org.apache.shardingsphere.sharding.rule.builder.ShardingRuleBuilder.build(ShardingRuleBuilder.java:35)
 at org.apache.shardingsphere.infra.rule.builder.database.DatabaseRulesBuilder.build(DatabaseRulesBuilder.java:64)
 at org.apache.shardingsphere.infra.metadata.database.ShardingSphereDatabase.create(ShardingSphereDatabase.java:87)
 at org.apache.shardingsphere.infra.metadata.database.ShardingSphereDatabasesFactory.createGenericDatabases(ShardingSphereDatabasesFactory.java:79)
 at org.apache.shardingsphere.infra.metadata.database.ShardingSphereDatabasesFactory.create(ShardingSphereDatabasesFactory.java:67)
 at org.apache.shardingsphere.mode.metadata.MetaDataContextsFactory.create(MetaDataContextsFactory.java:90)
 at org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.build(ClusterContextManagerBuilder.java:56)
 at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.createContextManager(BootstrapInitializer.java:73)
 at org.apach

Can you provide information on the use of the composite sharding algorithm in version 5.3.1

**Comment by FlyingZC** [comment]
Please use the issue template to describe your configuration and related implementation classes to provide more information.

**Comment by RaigorJiang** [comment]
Duplicated of #24373
