### ISSUE TITLE
Mybatis joint table INNER JOIN paging query execution count reported null exception

### ISSUE THREAD

**Issue by Python-IBM** [apache/shardingsphere#24393]
**1. Application version**
shardingsphere-jdbc：5.2.0
mysql：5.7
mybatis-plus: 3.4.1
Spring Boot: 2.3.12

**2.Query exception**
2023-03-01 09:47:05.665 DEBUG [http-nio-9702-exec-5][1630746447933083648] c.y.f.m.m.R.selectJoinForPage_mpCount ==>  Preparing: SELECT COUNT(*) FROM `reg_bill_info` rbi INNER JOIN `reg_bill_trans` rbt ON rbi.`BILL_ID` = rbt.`BILL_ID` WHERE rbi.`BILL_ID` = ?
2023-03-01 09:47:05.720 DEBUG [http-nio-9702-exec-5][1630746447933083648] c.y.f.m.m.R.selectJoinForPage_mpCount ==> Parameters: 1556603137911963649(String)
2023-03-01 09:47:05.728 INFO  [http-nio-9702-exec-5][1630746447933083648] ShardingSphere-SQL Logic SQL: SELECT COUNT(*) FROM `reg_bill_info` rbi INNER JOIN `reg_bill_trans` rbt ON rbi.`BILL_ID` = rbt.`BILL_ID` WHERE rbi.`BILL_ID` = ?
2023-03-01 09:47:05.729 INFO  [http-nio-9702-exec-5][1630746447933083648] ShardingSphere-SQL SQLStatement: MySQLSelectStatement(super=SelectStatement(super=AbstractSQLStatement(parameterCount=1, parameterMarkerSegments=[ParameterMarkerExpressionSegment(startIndex=128, stopIndex=128, parameterMarkerIndex=0, parameterMarkerType=QUESTION, alias=Optional.empty)], commentSegments=[]), projections=ProjectionsSegment(startIndex=7, stopIndex=14, projections=[AggregationProjectionSegment(startIndex=7, stopIndex=14, type=COUNT, innerExpression=(*), parameters=[], alias=Optional.empty)], distinctRow=false), from=JoinTableSegment(startIndex=21, stopIndex=104, alias=Optional.empty, left=SimpleTableSegment(tableName=TableNameSegment(startIndex=21, stopIndex=35, identifier=IdentifierValue(value=reg_bill_info, quoteCharacter=BACK_QUOTE)), owner=Optional.empty, alias=Optional[rbi]), joinType=INNER, right=SimpleTableSegment(tableName=TableNameSegment(startIndex=52, stopIndex=67, identifier=IdentifierValue(value=reg_bill_trans, quoteCharacter=BACK_QUOTE)), owner=Optional.empty, alias=Optional[rbt]), condition=BinaryOperationExpression(startIndex=76, stopIndex=104, left=ColumnSegment(startIndex=76, stopIndex=88, identifier=IdentifierValue(value=BILL_ID, quoteCharacter=BACK_QUOTE), owner=Optional[OwnerSegment(startIndex=76, stopIndex=78, identifier=IdentifierValue(value=rbi, quoteCharacter=NONE), owner=Optional.empty)]), right=ColumnSegment(startIndex=92, stopIndex=104, identifier=IdentifierValue(value=BILL_ID, quoteCharacter=BACK_QUOTE), owner=Optional[OwnerSegment(startIndex=92, stopIndex=94, identifier=IdentifierValue(value=rbt, quoteCharacter=NONE), owner=Optional.empty)]), operator==, text=rbi.`BILL_ID` = rbt.`BILL_ID`), using=[]), where=Optional[WhereSegment(startIndex=106, stopIndex=128, expr=BinaryOperationExpression(startIndex=112, stopIndex=128, left=ColumnSegment(startIndex=112, stopIndex=124, identifier=IdentifierValue(value=BILL_ID, quoteCharacter=BACK_QUOTE), owner=Optional[OwnerSegment(startIndex=112, stopIndex=114, identifier=IdentifierValue(value=rbi, quoteCharacter=NONE), owner=Optional.empty)]), right=ParameterMarkerExpressionSegment(startIndex=128, stopIndex=128, parameterMarkerIndex=0, parameterMarkerType=QUESTION, alias=Optional.empty), operator==, text=rbi.`BILL_ID` = ?))], groupBy=Optional.empty, having=Optional.empty, orderBy=Optional.empty, combines=[]), table=Optional.empty, limit=Optional.empty, lock=Optional.empty, window=Optional.empty)
2023-03-01 09:47:05.730 INFO  [http-nio-9702-exec-5][1630746447933083648] ShardingSphere-SQL Actual SQL: yk_sharding ::: SELECT COUNT(*) FROM `reg_bill_info_2021` rbi INNER JOIN `reg_bill_trans_2021` rbt ON rbi.`BILL_ID` = rbt.`BILL_ID` WHERE rbi.`BILL_ID` = ? ::: [1556603137911963649]
2023-03-01 09:47:05.730 INFO  [http-nio-9702-exec-5][1630746447933083648] ShardingSphere-SQL Actual SQL: yk_sharding ::: SELECT COUNT(*) FROM `reg_bill_info_2021` rbi INNER JOIN `reg_bill_trans_2022` rbt ON rbi.`BILL_ID` = rbt.`BILL_ID` WHERE rbi.`BILL_ID` = ? ::: [1556603137911963649]
2023-03-01 09:47:05.730 INFO  [http-nio-9702-exec-5][1630746447933083648] ShardingSphere-SQL Actual SQL: yk_sharding ::: SELECT COUNT(*) FROM `reg_bill_info_2021` rbi INNER JOIN `reg_bill_trans_2023` rbt ON rbi.`BILL_ID` = rbt.`BILL_ID` WHERE rbi.`BILL_ID` = ? ::: [1556603137911963649]
2023-03-01 09:47:05.730 INFO  [http-nio-9702-exec-5][1630746447933083648] ShardingSphere-SQL Actual SQL: yk_sharding ::: SELECT COUNT(*) FROM `reg_bill_info_2022` rbi INNER JOIN `reg_bill_trans_2021` rbt ON rbi.`BILL_ID` = rbt.`BILL_ID` WHERE rbi.`BILL_ID` = ? ::: [1556603137911963649]
2023-03-01 09:47:05.731 INFO  [http-nio-9702-exec-5][1630746447933083648] ShardingSphere-SQL Actual SQL: yk_sharding ::: SELECT COUNT(*) FROM `reg_bill_info_2022` rbi INNER JOIN `reg_bill_trans_2022` rbt ON rbi.`BILL_ID` = rbt.`BILL_ID` WHERE rbi.`BILL_ID` = ? ::: [1556603137911963649]
2023-03-01 09:47:05.731 INFO  [http-nio-9702-exec-5][1630746447933083648] ShardingSphere-SQL Actual SQL: yk_sharding ::: SELECT COUNT(*) FROM `reg_bill_info_2022` rbi INNER JOIN `reg_bill_trans_2023` rbt ON rbi.`BILL_ID` = rbt.`BILL_ID` WHERE rbi.`BILL_ID` = ? ::: [1556603137911963649]
2023-03-01 09:47:05.731 INFO  [http-nio-9702-exec-5][1630746447933083648] ShardingSphere-SQL Actual SQL: yk_sharding ::: SELECT COUNT(*) FROM `reg_bill_info_2023` rbi INNER JOIN `reg_bill_trans_2021` rbt ON rbi.`BILL_ID` = rbt.`BILL_ID` WHERE rbi.`BILL_ID` = ? ::: [1556603137911963649]
2023-03-01 09:47:05.731 INFO  [http-nio-9702-exec-5][1630746447933083648] ShardingSphere-SQL Actual SQL: yk_sharding ::: SELECT COUNT(*) FROM `reg_bill_info_2023` rbi INNER JOIN `reg_bill_trans_2022` rbt ON rbi.`BILL_ID` = rbt.`BILL_ID` WHERE rbi.`BILL_ID` = ? ::: [1556603137911963649]
2023-03-01 09:47:05.731 INFO  [http-nio-9702-exec-5][1630746447933083648] ShardingSphere-SQL Actual SQL: yk_sharding ::: SELECT COUNT(*) FROM `reg_bill_info_2023` rbi INNER JOIN `reg_bill_trans_2023` rbt ON rbi.`BILL_ID` = rbt.`BILL_ID` WHERE rbi.`BILL_ID` = ? ::: [1556603137911963649]
2023-03-01 09:47:05.780 ERROR [http-nio-9702-exec-5][] o.a.c.c.C.[.[.[.[dispatcherServlet] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.NullPointerException] with root cause
java.lang.NullPointerException: null
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.getValueCaseSensitiveFromTables(GroupByMemoryMergedResult.java:135)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.getValueCaseSensitive(GroupByMemoryMergedResult.java:125)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.init(GroupByMemoryMergedResult.java:73)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.init(GroupByMemoryMergedResult.java:53)
	at org.apache.shardingsphere.infra.merge.result.impl.memory.MemoryMergedResult.<init>(MemoryMergedResult.java:51)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.<init>(GroupByMemoryMergedResult.java:56)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.getGroupByMergedResult(ShardingDQLResultMerger.java:118)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.build(ShardingDQLResultMerger.java:88)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.merge(ShardingDQLResultMerger.java:66)
	at org.apache.shardingsphere.infra.merge.MergeEngine.executeMerge(MergeEngine.java:82)
	at org.apache.shardingsphere.infra.merge.MergeEngine.merge(MergeEngine.java:71)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.mergeQuery(ShardingSpherePreparedStatement.java:520)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.getResultSet(ShardingSpherePreparedStatement.java:462)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:69)
	at com.sun.proxy.$Proxy103.getResultSet(Unknown Source)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getFirstResultSet(DefaultResultSetHandler.java:237)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:187)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:65)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy101.query(Unknown Source)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doQuery(MybatisSimpleExecutor.java:69)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.query(MybatisCachingExecutor.java:165)
	at com.baomidou.mybatisplus.extension.plugins.inner.PaginationInnerInterceptor.willDoQuery(PaginationInnerInterceptor.java:134)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:59)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy100.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
	at com.sun.proxy.$Proxy79.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:223)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForIPage(MybatisMapperMethod.java:122)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:87)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy82.selectJoinForPage(Unknown Source)
	at com.demo.message.controller.DemoController.queryRegBillTransPage(DemoController.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)

**Comment by FlyingZC** [comment]
By the stacktrace, the NPE code is `ShardingSphereTable table = schema.getTable(tableName);`, please check whether the table exists in the shardingsphere metadata. If you manually create a physical table after starting ShardingSphere, ShardingSphere cannot detect it.

**Comment by Python-IBM** [comment]
> By the stacktrace, the NPE code is `ShardingSphereTable table = schema.getTable(tableName);`, please check whether the table exists in the shardingsphere metadata. If you manually create a physical table after starting ShardingSphere, ShardingSphere cannot detect it.

Ok, I understand. I'll check it again

**Comment by Python-IBM** [comment]
MySQL will not report an error, while Oracle will report an error. In the screenshot, the physical table "reg_bill_info" can be found in the mysql namespace metadata, but the physical table "reg_bill_info" is not found in the oracle namespace metadata
![image](https://user-images.githubusercontent.com/33851767/222897172-9ad9cfa6-2a40-4d70-aab2-0dac53f5bce0.png)

**Comment by Python-IBM** [comment]
Why does Oracle write all the physical tables in the database to the "/metadata/logic_db/schemas/logic_db/tables" directory when writing metadata by tables? In addition, the physical table to be split does not exist in this directory. Normally, this directory should store the name of the physical table to be split.
