### ISSUE TITLE
SHOW DIST VARIABLE CI Error

### ISSUE THREAD

**Issue by FlyingZC** [apache/shardingsphere#24539]
## Bug Report
SHOW DIST VARIABLE CI Error

<img width="616" alt="image" src="https://user-images.githubusercontent.com/19788130/224236372-338be124-35d4-4714-97eb-78c34dc6f1f9.png">

### Which version of ShardingSphere did you use?
Master.

### Expected behavior
SHOW DIST VARIABLE CI success

### Actual behavior
```log
Error:  2023-03-10 03:52:44.780 [main] o.a.s.t.e.f.watcher.E2EWatcher - Error case: assertExecute[proxy: empty_rules -> PostgreSQL -> Literal -> SHOW DIST VARIABLES;], message: java.lang.AssertionError: 
Expected: is "false"
     but: was "true"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at org.apache.shardingsphere.test.e2e.engine.ral.BaseRALE2EIT.assertObjectValue(BaseRALE2EIT.java:149)
	at org.apache.shardingsphere.test.e2e.engine.ral.BaseRALE2EIT.assertRow(BaseRALE2EIT.java:142)
	at org.apache.shardingsphere.test.e2e.engine.ral.BaseRALE2EIT.assertRows(BaseRALE2EIT.java:131)
	at org.apache.shardingsphere.test.e2e.engine.ral.BaseRALE2EIT.assertResultSet(BaseRALE2EIT.java:99)
	at org.apache.shardingsphere.test.e2e.engine.ral.GeneralRALE2EIT.assertResultSet(GeneralRALE2EIT.java:69)
	at org.apache.shardingsphere.test.e2e.engine.ral.GeneralRALE2EIT.assertResultSet(GeneralRALE2EIT.java:59)
	at org.apache.shardingsphere.test.e2e.engine.ral.GeneralRALE2EIT.assertExecute(GeneralRALE2EIT.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:142)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:117)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)

Error:  2023-03-10 03:52:44.780 [main] o.a.s.t.e.f.watcher.E2EWatcher - Error case: assertExecute[proxy: empty_rules -> PostgreSQL -> Literal -> SHOW DIST VARIABLES;], message: java.lang.AssertionError: 
Expected: is "false"
     but: was "true"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at org.apache.shardingsphere.test.e2e.engine.ral.BaseRALE2EIT.assertObjectValue(BaseRALE2EIT.java:149)
	at org.apache.shardingsphere.test.e2e.engine.ral.BaseRALE2EIT.assertRow(BaseRALE2EIT.java:142)
	at org.apache.shardingsphere.test.e2e.engine.ral.BaseRALE2EIT.assertRows(BaseRALE2EIT.java:131)
	at org.apache.shardingsphere.test.e2e.engine.ral.BaseRALE2EIT.assertResultSet(BaseRALE2EIT.java:99)
	at org.apache.shardingsphere.test.e2e.engine.ral.GeneralRALE2EIT.assertResultSet(GeneralRALE2EIT.java:69)
	at org.apache.shardingsphere.test.e2e.engine.ral.GeneralRALE2EIT.assertResultSet(GeneralRALE2EIT.java:59)
	at org.apache.shardingsphere.test.e2e.engine.ral.GeneralRALE2EIT.assertExecute(GeneralRALE2EIT.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:142)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:117)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)

Error:  2023-03-10 03:52:44.838 [main] o.a.s.t.e.f.watcher.E2EWatcher - Error case: assertExecute[proxy: empty_rules -> PostgreSQL -> Literal -> SHOW DIST VARIABLE WHERE name = sql_show;], message: java.lang.AssertionError: 
Expected: is "false"
     but: was "true"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at org.apache.shardingsphere.test.e2e.engine.ral.BaseRALE2EIT.assertObjectValue(BaseRALE2EIT.java:149)
	at org.apache.shardingsphere.test.e2e.engine.ral.BaseRALE2EIT.assertRow(BaseRALE2EIT.java:142)
	at org.apache.shardingsphere.test.e2e.engine.ral.BaseRALE2EIT.assertRows(BaseRALE2EIT.java:131)
	at org.apache.shardingsphere.test.e2e.engine.ral.BaseRALE2EIT.assertResultSet(BaseRALE2EIT.java:99)
	at org.apache.shardingsphere.test.e2e.engine.ral.GeneralRALE2EIT.assertResultSet(GeneralRALE2EIT.java:69)
	at org.apache.shardingsphere.test.e2e.engine.ral.GeneralRALE2EIT.assertResultSet(GeneralRALE2EIT.java:59)
	at org.apache.shardingsphere.test.e2e.engine.ral.GeneralRALE2EIT.assertExecute(GeneralRALE2EIT.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:142)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:117)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)

Error:  2023-03-10 03:52:44.838 [main] o.a.s.t.e.f.watcher.E2EWatcher - Error case: assertExecute[proxy: empty_rules -> PostgreSQL -> Literal -> SHOW DIST VARIABLE WHERE name = sql_show;], message: java.lang.AssertionError: 
Expected: is "false"
     but: was "true"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at org.apache.shardingsphere.test.e2e.engine.ral.BaseRALE2EIT.assertObjectValue(BaseRALE2EIT.java:149)
	at org.apache.shardingsphere.test.e2e.engine.ral.BaseRALE2EIT.assertRow(BaseRALE2EIT.java:142)
	at org.apache.shardingsphere.test.e2e.engine.ral.BaseRALE2EIT.assertRows(BaseRALE2EIT.java:131)
	at org.apache.shardingsphere.test.e2e.engine.ral.BaseRALE2EIT.assertResultSet(BaseRALE2EIT.java:99)
	at org.apache.shardingsphere.test.e2e.engine.ral.GeneralRALE2EIT.assertResultSet(GeneralRALE2EIT.java:69)
	at org.apache.shardingsphere.test.e2e.engine.ral.GeneralRALE2EIT.assertResultSet(GeneralRALE2EIT.java:59)
	at org.apache.shardingsphere.test.e2e.engine.ral.GeneralRALE2EIT.assertExecute(GeneralRALE2EIT.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:142)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:117)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)

Error:  Tests run: 25, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 46.336 s <<< FAILURE! - in JUnit Vintage
Error:  assertExecute[proxy: empty_rules -> PostgreSQL -> Literal -> SHOW DIST VARIABLES;]  Time elapsed: 0.064 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is "false"
     but: was "true"
	at org.apache.shardingsphere.test.e2e.engine.ral.GeneralRALE2EIT.assertResultSet(GeneralRALE2EIT.java:69)
	at org.apache.shardingsphere.test.e2e.engine.ral.GeneralRALE2EIT.assertResultSet(GeneralRALE2EIT.java:59)
	at org.apache.shardingsphere.test.e2e.engine.ral.GeneralRALE2EIT.assertExecute(GeneralRALE2EIT.java:52)

Error:  assertExecute[proxy: empty_rules -> PostgreSQL -> Literal -> SHOW DIST VARIABLE WHERE name = sql_show;]  Time elapsed: 0.026 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is "false"
     but: was "true"
	at org.apache.shardingsphere.test.e2e.engine.ral.GeneralRALE2EIT.assertResultSet(GeneralRALE2EIT.java:69)
	at org.apache.shardingsphere.test.e2e.engine.ral.GeneralRALE2EIT.assertResultSet(GeneralRALE2EIT.java:59)
	at org.apache.shardingsphere.test.e2e.engine.ral.GeneralRALE2EIT.assertExecute(GeneralRALE2EIT.java:52)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    GeneralRALE2EIT.assertExecute:52->assertResultSet:59->assertResultSet:69->BaseRALE2EIT.assertResultSet:99->BaseRALE2EIT.assertRows:131->BaseRALE2EIT.assertRow:142->BaseRALE2EIT.assertObjectValue:149 
Expected: is "false"
     but: was "true"
Error:    GeneralRALE2EIT.assertExecute:52->assertResultSet:59->assertResultSet:69->BaseRALE2EIT.assertResultSet:99->BaseRALE2EIT.assertRows:131->BaseRALE2EIT.assertRow:142->BaseRALE2EIT.assertObjectValue:149 
Expected: is "false"
     but: was "true"
```

**Comment by FlyingZC** [comment]
The same with #24540
