### ISSUE TITLE
GeneralRALE2EIT.assertExecute error when execute in empty rules scenario

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#24540]
### Which version of ShardingSphere did you use?

https://github.com/apache/shardingsphere/commit/ea06d6a506edc8186ab68e5dc6545b04ef510363

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Execute GeneralRALE2EIT.assertExecute successfully.

### Actual behavior

https://github.com/apache/shardingsphere/actions/runs/4371984794/jobs/7648493992#logs

```
Error:  Tests run: 28, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 83.105 s <<< FAILURE! - in JUnit Vintage
Error:  assertExecute[proxy: empty_rules -> MySQL -> Literal -> SHOW DIST VARIABLES;]  Time elapsed: 0.057 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is "false"
     but: was "true"
	at org.apache.shardingsphere.test.e2e.engine.ral.GeneralRALE2EIT.assertResultSet(GeneralRALE2EIT.java:69)
	at org.apache.shardingsphere.test.e2e.engine.ral.GeneralRALE2EIT.assertResultSet(GeneralRALE2EIT.java:59)
	at org.apache.shardingsphere.test.e2e.engine.ral.GeneralRALE2EIT.assertExecute(GeneralRALE2EIT.java:52)

Error:  assertExecute[proxy: empty_rules -> MySQL -> Literal -> SHOW DIST VARIABLE WHERE name = sql_show;]  Time elapsed: 0.015 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is "false"
     but: was "true"
	at org.apache.shardingsphere.test.e2e.engine.ral.GeneralRALE2EIT.assertResultSet(GeneralRALE2EIT.java:69)
	at org.apache.shardingsphere.test.e2e.engine.ral.GeneralRALE2EIT.assertResultSet(GeneralRALE2EIT.java:59)
	at org.apache.shardingsphere.test.e2e.engine.ral.GeneralRALE2EIT.assertExecute(GeneralRALE2EIT.java:52)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    GeneralRALE2EIT.assertExecute:52->assertResultSet:59->assertResultSet:69->BaseRALE2EIT.assertResultSet:99->BaseRALE2EIT.assertRows:131->BaseRALE2EIT.assertRow:142->BaseRALE2EIT.assertObjectValue:149 
Expected: is "false"
     but: was "true"
Error:    GeneralRALE2EIT.assertExecute:52->assertResultSet:59->assertResultSet:69->BaseRALE2EIT.assertResultSet:99->BaseRALE2EIT.assertRows:131->BaseRALE2EIT.assertRow:142->BaseRALE2EIT.assertObjectValue:149 
Expected: is "false"
     but: was "true"
[INFO] 
Error:  Tests run: 28, Failures: 2, Errors: 0, Skipped: 0
```

**Comment by zhaojinchao95** [comment]
Seems `GeneralRALE2EIT` it case has some problem, each case should be independent.
