### ISSUE TITLE
Official examples do not ask for advice in detail.

### ISSUE THREAD

**Issue by liruhui** [apache/shardingsphere#24671]
# 1.  Problem Description
## 1.1. Database Info
![image](https://user-images.githubusercontent.com/24687986/226081397-8c86025a-ea08-43e2-ae38-6348ff03bf21.png)
## 1.2. javaCode 
```java

  public static void main(String[] args) throws Exception {
        //setMode
        ModeConfiguration modeConfiguration = new ModeConfiguration("Standalone",new StandalonePersistRepositoryConfiguration("JDBC",new Properties()),true);
        //set dataSource
        Map<String, DataSource> map  = new HashMap<>();
        DruidDataSource  dataSource  = new DruidDataSource();
        dataSource.setDriverClassName(Driver.class.getName());
        dataSource.setUrl("jdbc:mysql://localhost:3306/aaaa?serverTimezone=UTC");
        dataSource.setUsername("root");
        dataSource.setPassword("rootroot");

        DruidDataSource  dataSource1  = new DruidDataSource();
        dataSource.setDriverClassName(Driver.class.getName());
        dataSource.setUrl("jdbc:mysql://localhost:3306/bbbb?serverTimezone=UTC");
        dataSource.setUsername("root");
        dataSource.setPassword("rootroot");
        //set dataSource
        map.put("xxxx",dataSource);
        map.put("yyyy",dataSource1);


        ShardingRuleConfiguration shardingRuleConfiguration  = new ShardingRuleConfiguration();
        //setTables
        ShardingTableRuleConfiguration configuration  = new ShardingTableRuleConfiguration("pppp","xxxx.t_grade");
        ShardingTableRuleConfiguration configuration1  = new ShardingTableRuleConfiguration("wwww","yyyy.t_stu");
        shardingRuleConfiguration.getTables().add(configuration);
        shardingRuleConfiguration.getTables().add(configuration1);

        DataSource abc = ShardingSphereDataSourceFactory.createDataSource("abc", modeConfiguration, map, Collections.singleton(shardingRuleConfiguration) , new Properties());
        Connection connection = abc .getConnection();

        //real table name
        //connection.prepareStatement("insert into t_grade values(2,'三班')").execute();
        //connection.prepareStatement("insert into t_stu values(2,'李四')").execute();

        connection.prepareStatement("insert into pppp values(2,'三班')").execute();
        connection.prepareStatement("insert into wwww values(2,'李四')").execute();
    }

```
## 1.3. Error 
```java
D:\JDK\bin\java.exe "-javaagent:D:\idea\IntelliJ IDEA 2022.2.2\lib\idea_rt.jar=6938:D:\idea\IntelliJ IDEA 2022.2.2\bin" -Dfile.encoding=UTF-8 -classpath E:\课程研发\sharding\sharding-master\sharding-master\target\classes;E:\repository\org\apache\shardingsphere\shardingsphere-jdbc-core\5.2.0\shardingsphere-jdbc-core-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-transaction-core\5.2.0\shardingsphere-transaction-core-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-transaction-api\5.2.0\shardingsphere-transaction-api-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-infra-executor\5.2.0\shardingsphere-infra-executor-5.2.0.jar;E:\repository\io\vertx\vertx-mysql-client\4.2.3\vertx-mysql-client-4.2.3.jar;E:\repository\io\vertx\vertx-core\4.2.3\vertx-core-4.2.3.jar;E:\repository\io\netty\netty-common\4.1.72.Final\netty-common-4.1.72.Final.jar;E:\repository\io\netty\netty-buffer\4.1.72.Final\netty-buffer-4.1.72.Final.jar;E:\repository\io\netty\netty-transport\4.1.72.Final\netty-transport-4.1.72.Final.jar;E:\repository\io\netty\netty-handler\4.1.72.Final\netty-handler-4.1.72.Final.jar;E:\repository\io\netty\netty-codec\4.1.72.Final\netty-codec-4.1.72.Final.jar;E:\repository\io\netty\netty-tcnative-classes\2.0.46.Final\netty-tcnative-classes-2.0.46.Final.jar;E:\repository\io\netty\netty-handler-proxy\4.1.72.Final\netty-handler-proxy-4.1.72.Final.jar;E:\repository\io\netty\netty-codec-socks\4.1.72.Final\netty-codec-socks-4.1.72.Final.jar;E:\repository\io\netty\netty-codec-http\4.1.72.Final\netty-codec-http-4.1.72.Final.jar;E:\repository\io\netty\netty-codec-http2\4.1.72.Final\netty-codec-http2-4.1.72.Final.jar;E:\repository\io\netty\netty-resolver\4.1.72.Final\netty-resolver-4.1.72.Final.jar;E:\repository\io\netty\netty-resolver-dns\4.1.72.Final\netty-resolver-dns-4.1.72.Final.jar;E:\repository\io\netty\netty-codec-dns\4.1.72.Final\netty-codec-dns-4.1.72.Final.jar;E:\repository\io\vertx\vertx-sql-client\4.2.3\vertx-sql-client-4.2.3.jar;E:\repository\org\apache\shardingsphere\shardingsphere-sql-parser-sql92\5.2.0\shardingsphere-sql-parser-sql92-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-sql-parser-engine\5.2.0\shardingsphere-sql-parser-engine-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-sql-parser-spi\5.2.0\shardingsphere-sql-parser-spi-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-sql-parser-statement\5.2.0\shardingsphere-sql-parser-statement-5.2.0.jar;E:\repository\org\antlr\antlr4-runtime\4.9.2\antlr4-runtime-4.9.2.jar;E:\repository\com\github\ben-manes\caffeine\caffeine\2.9.2\caffeine-2.9.2.jar;E:\repository\org\apache\shardingsphere\shardingsphere-sql-parser-mysql\5.2.0\shardingsphere-sql-parser-mysql-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-sql-parser-postgresql\5.2.0\shardingsphere-sql-parser-postgresql-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-sql-parser-oracle\5.2.0\shardingsphere-sql-parser-oracle-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-sql-parser-sqlserver\5.2.0\shardingsphere-sql-parser-sqlserver-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-sql-parser-opengauss\5.2.0\shardingsphere-sql-parser-opengauss-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-authority-core\5.2.0\shardingsphere-authority-core-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-authority-api\5.2.0\shardingsphere-authority-api-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-single-table-core\5.2.0\shardingsphere-single-table-core-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-single-table-api\5.2.0\shardingsphere-single-table-api-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-infra-route\5.2.0\shardingsphere-infra-route-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-traffic-core\5.2.0\shardingsphere-traffic-core-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-infra-common\5.2.0\shardingsphere-infra-common-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-infra-util\5.2.0\shardingsphere-infra-util-5.2.0.jar;E:\repository\org\yaml\snakeyaml\1.30\snakeyaml-1.30.jar;E:\repository\org\apache\groovy\groovy\4.0.3\groovy-4.0.3.jar;E:\repository\org\apache\shardingsphere\shardingsphere-infra-binder\5.2.0\shardingsphere-infra-binder-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-dialect-exception-core\5.2.0\shardingsphere-dialect-exception-core-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-traffic-api\5.2.0\shardingsphere-traffic-api-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-infra-context\5.2.0\shardingsphere-infra-context-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-distsql-parser\5.2.0\shardingsphere-distsql-parser-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-distsql-statement\5.2.0\shardingsphere-distsql-statement-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-sql-translator-core\5.2.0\shardingsphere-sql-translator-core-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-sql-translator-api\5.2.0\shardingsphere-sql-translator-api-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-standalone-mode-core\5.2.0\shardingsphere-standalone-mode-core-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-mode-core\5.2.0\shardingsphere-mode-core-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-schedule-core\5.2.0\shardingsphere-schedule-core-5.2.0.jar;E:\repository\org\apache\shardingsphere\elasticjob\elasticjob-lite-core\3.0.1\elasticjob-lite-core-3.0.1.jar;E:\repository\org\apache\shardingsphere\elasticjob\elasticjob-api\3.0.1\elasticjob-api-3.0.1.jar;E:\repository\org\apache\shardingsphere\elasticjob\elasticjob-infra-common\3.0.1\elasticjob-infra-common-3.0.1.jar;E:\repository\org\apache\shardingsphere\elasticjob\elasticjob-registry-center\3.0.1\elasticjob-registry-center-3.0.1.jar;E:\repository\org\apache\shardingsphere\elasticjob\elasticjob-simple-executor\3.0.1\elasticjob-simple-executor-3.0.1.jar;E:\repository\org\apache\shardingsphere\elasticjob\elasticjob-executor-kernel\3.0.1\elasticjob-executor-kernel-3.0.1.jar;E:\repository\org\apache\shardingsphere\elasticjob\elasticjob-error-handler-general\3.0.1\elasticjob-error-handler-general-3.0.1.jar;E:\repository\org\apache\shardingsphere\elasticjob\elasticjob-error-handler-spi\3.0.1\elasticjob-error-handler-spi-3.0.1.jar;E:\repository\org\apache\shardingsphere\elasticjob\elasticjob-dataflow-executor\3.0.1\elasticjob-dataflow-executor-3.0.1.jar;E:\repository\org\apache\shardingsphere\elasticjob\elasticjob-script-executor\3.0.1\elasticjob-script-executor-3.0.1.jar;E:\repository\org\apache\commons\commons-exec\1.3\commons-exec-1.3.jar;E:\repository\org\apache\shardingsphere\elasticjob\elasticjob-http-executor\3.0.1\elasticjob-http-executor-3.0.1.jar;E:\repository\org\apache\shardingsphere\elasticjob\elasticjob-tracing-rdb\3.0.1\elasticjob-tracing-rdb-3.0.1.jar;E:\repository\org\apache\shardingsphere\elasticjob\elasticjob-tracing-api\3.0.1\elasticjob-tracing-api-3.0.1.jar;E:\repository\com\google\code\gson\gson\2.6.1\gson-2.6.1.jar;E:\repository\org\quartz-scheduler\quartz\2.3.2\quartz-2.3.2.jar;E:\repository\com\mchange\mchange-commons-java\0.2.15\mchange-commons-java-0.2.15.jar;E:\repository\org\apache\shardingsphere\elasticjob\elasticjob-lite-lifecycle\3.0.1\elasticjob-lite-lifecycle-3.0.1.jar;E:\repository\org\apache\shardingsphere\shardingsphere-standalone-mode-repository-api\5.2.0\shardingsphere-standalone-mode-repository-api-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-standalone-mode-repository-jdbc-h2\5.2.0\shardingsphere-standalone-mode-repository-jdbc-h2-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-standalone-mode-repository-jdbc-core\5.2.0\shardingsphere-standalone-mode-repository-jdbc-core-5.2.0.jar;E:\repository\com\zaxxer\HikariCP\3.4.2\HikariCP-3.4.2.jar;E:\repository\org\apache\shardingsphere\shardingsphere-cluster-mode-core\5.2.0\shardingsphere-cluster-mode-core-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-cluster-mode-repository-api\5.2.0\shardingsphere-cluster-mode-repository-api-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-sharding-core\5.2.0\shardingsphere-sharding-core-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-sharding-api\5.2.0\shardingsphere-sharding-api-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-data-pipeline-core\5.2.0\shardingsphere-data-pipeline-core-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-data-pipeline-api\5.2.0\shardingsphere-data-pipeline-api-5.2.0.jar;E:\repository\org\apache\commons\commons-lang3\3.8\commons-lang3-3.8.jar;E:\repository\org\apache\shardingsphere\shardingsphere-cluster-mode-repository-zookeeper-curator\5.2.0\shardingsphere-cluster-mode-repository-zookeeper-curator-5.2.0.jar;E:\repository\org\apache\curator\curator-framework\5.1.0\curator-framework-5.1.0.jar;E:\repository\org\apache\curator\curator-client\5.1.0\curator-client-5.1.0.jar;E:\repository\org\apache\zookeeper\zookeeper\3.6.0\zookeeper-3.6.0.jar;E:\repository\org\apache\zookeeper\zookeeper-jute\3.6.0\zookeeper-jute-3.6.0.jar;E:\repository\org\apache\yetus\audience-annotations\0.5.0\audience-annotations-0.5.0.jar;E:\repository\io\netty\netty-transport-native-epoll\4.1.45.Final\netty-transport-native-epoll-4.1.45.Final.jar;E:\repository\io\netty\netty-transport-native-unix-common\4.1.45.Final\netty-transport-native-unix-common-4.1.45.Final.jar;E:\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;E:\repository\org\apache\curator\curator-recipes\5.1.0\curator-recipes-5.1.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-infra-rewrite\5.2.0\shardingsphere-infra-rewrite-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-sql-translator-native-provider\5.2.0\shardingsphere-sql-translator-native-provider-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-infra-merge\5.2.0\shardingsphere-infra-merge-5.2.0.jar;E:\repository\org\apache\calcite\calcite-linq4j\1.31.0\calcite-linq4j-1.31.0.jar;E:\repository\org\apiguardian\apiguardian-api\1.1.2\apiguardian-api-1.1.2.jar;E:\repository\org\apache\calcite\avatica\avatica-core\1.22.0\avatica-core-1.22.0.jar;E:\repository\org\apache\calcite\avatica\avatica-metrics\1.22.0\avatica-metrics-1.22.0.jar;E:\repository\org\apache\httpcomponents\client5\httpclient5\5.1.3\httpclient5-5.1.3.jar;E:\repository\org\apache\httpcomponents\core5\httpcore5-h2\5.1.3\httpcore5-h2-5.1.3.jar;E:\repository\org\apache\httpcomponents\core5\httpcore5\5.1.3\httpcore5-5.1.3.jar;E:\repository\org\apache\shardingsphere\shardingsphere-system-datetime\5.2.0\shardingsphere-system-datetime-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-infra-datetime-spi\5.2.0\shardingsphere-infra-datetime-spi-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-sharding-cosid\5.2.0\shardingsphere-sharding-cosid-5.2.0.jar;E:\repository\me\ahoo\cosid\cosid-core\1.14.4\cosid-core-1.14.4.jar;E:\repository\org\apache\shardingsphere\shardingsphere-sharding-nanoid\5.2.0\shardingsphere-sharding-nanoid-5.2.0.jar;E:\repository\com\aventrix\jnanoid\jnanoid\2.0.0\jnanoid-2.0.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-readwrite-splitting-core\5.2.0\shardingsphere-readwrite-splitting-core-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-readwrite-splitting-api\5.2.0\shardingsphere-readwrite-splitting-api-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-db-discovery-core\5.2.0\shardingsphere-db-discovery-core-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-db-discovery-api\5.2.0\shardingsphere-db-discovery-api-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-db-discovery-mysql\5.2.0\shardingsphere-db-discovery-mysql-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-db-discovery-opengauss\5.2.0\shardingsphere-db-discovery-opengauss-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-encrypt-core\5.2.0\shardingsphere-encrypt-core-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-encrypt-api\5.2.0\shardingsphere-encrypt-api-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-encrypt-sm\5.2.0\shardingsphere-encrypt-sm-5.2.0.jar;E:\repository\org\bouncycastle\bcprov-jdk15on\1.70\bcprov-jdk15on-1.70.jar;E:\repository\commons-codec\commons-codec\1.15\commons-codec-1.15.jar;E:\repository\org\apache\shardingsphere\shardingsphere-shadow-core\5.2.0\shardingsphere-shadow-core-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-shadow-api\5.2.0\shardingsphere-shadow-api-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-infra-federation-executor\5.2.0\shardingsphere-infra-federation-executor-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-infra-federation-optimizer\5.2.0\shardingsphere-infra-federation-optimizer-5.2.0.jar;E:\repository\org\apache\calcite\calcite-core\1.31.0\calcite-core-1.31.0.jar;E:\repository\com\esri\geometry\esri-geometry-api\2.2.0\esri-geometry-api-2.2.0.jar;E:\repository\com\fasterxml\jackson\core\jackson-annotations\2.13.2\jackson-annotations-2.13.2.jar;E:\repository\com\fasterxml\jackson\core\jackson-core\2.13.2\jackson-core-2.13.2.jar;E:\repository\com\fasterxml\jackson\core\jackson-databind\2.13.2.1\jackson-databind-2.13.2.1.jar;E:\repository\com\fasterxml\jackson\dataformat\jackson-dataformat-yaml\2.13.2\jackson-dataformat-yaml-2.13.2.jar;E:\repository\com\google\uzaygezen\uzaygezen-core\0.2\uzaygezen-core-0.2.jar;E:\repository\com\jayway\jsonpath\json-path\2.7.0\json-path-2.7.0.jar;E:\repository\net\minidev\json-smart\2.4.7\json-smart-2.4.7.jar;E:\repository\net\minidev\accessors-smart\2.4.7\accessors-smart-2.4.7.jar;E:\repository\org\ow2\asm\asm\9.1\asm-9.1.jar;E:\repository\com\yahoo\datasketches\sketches-core\0.9.0\sketches-core-0.9.0.jar;E:\repository\com\yahoo\datasketches\memory\0.9.0\memory-0.9.0.jar;E:\repository\net\hydromatic\aggdesigner-algorithm\6.0\aggdesigner-algorithm-6.0.jar;E:\repository\commons-lang\commons-lang\2.4\commons-lang-2.4.jar;E:\repository\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;E:\repository\org\apache\commons\commons-dbcp2\2.6.0\commons-dbcp2-2.6.0.jar;E:\repository\org\apache\commons\commons-pool2\2.6.1\commons-pool2-2.6.1.jar;E:\repository\commons-io\commons-io\2.11.0\commons-io-2.11.0.jar;E:\repository\org\codehaus\janino\commons-compiler\3.1.6\commons-compiler-3.1.6.jar;E:\repository\org\codehaus\janino\janino\3.1.6\janino-3.1.6.jar;E:\repository\org\apache\shardingsphere\shardingsphere-parser-core\5.2.0\shardingsphere-parser-core-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-parser-api\5.2.0\shardingsphere-parser-api-5.2.0.jar;E:\repository\org\apache\shardingsphere\shardingsphere-infra-parser\5.2.0\shardingsphere-infra-parser-5.2.0.jar;E:\repository\org\apache\commons\commons-collections4\4.4\commons-collections4-4.4.jar;E:\repository\com\h2database\h2\2.1.214\h2-2.1.214.jar;E:\repository\com\google\guava\guava\30.0-jre\guava-30.0-jre.jar;E:\repository\com\google\guava\failureaccess\1.0.1\failureaccess-1.0.1.jar;E:\repository\com\google\code\findbugs\jsr305\3.0.2\jsr305-3.0.2.jar;E:\repository\org\checkerframework\checker-qual\3.5.0\checker-qual-3.5.0.jar;E:\repository\com\google\errorprone\error_prone_annotations\2.3.4\error_prone_annotations-2.3.4.jar;E:\repository\org\slf4j\slf4j-api\1.7.7\slf4j-api-1.7.7.jar;E:\repository\org\slf4j\jcl-over-slf4j\1.7.7\jcl-over-slf4j-1.7.7.jar;E:\repository\org\slf4j\jul-to-slf4j\1.7.7\jul-to-slf4j-1.7.7.jar;E:\repository\com\alibaba\druid\1.2.8\druid-1.2.8.jar;E:\repository\javax\annotation\javax.annotation-api\1.3.2\javax.annotation-api-1.3.2.jar;E:\repository\mysql\mysql-connector-java\8.0.25\mysql-connector-java-8.0.25.jar;E:\repository\com\google\protobuf\protobuf-java\3.11.4\protobuf-java-3.11.4.jar com.shangma.cn.Main
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
log4j:WARN No appenders could be found for logger (com.alibaba.druid.pool.DruidDataSource).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" org.apache.shardingsphere.infra.util.exception.sql.SQLWrapperException
	at org.apache.shardingsphere.infra.database.type.DatabaseTypeEngine.getDatabaseType(DatabaseTypeEngine.java:113)
	at org.apache.shardingsphere.infra.database.type.DatabaseTypeEngine.getDatabaseType(DatabaseTypeEngine.java:102)
	at org.apache.shardingsphere.infra.database.type.DatabaseTypeEngine.getProtocolType(DatabaseTypeEngine.java:69)
	at org.apache.shardingsphere.infra.metadata.database.ShardingSphereDatabasesFactory.create(ShardingSphereDatabasesFactory.java:65)
	at org.apache.shardingsphere.mode.metadata.MetaDataContextsFactory.create(MetaDataContextsFactory.java:68)
	at org.apache.shardingsphere.mode.manager.standalone.StandaloneContextManagerBuilder.build(StandaloneContextManagerBuilder.java:52)
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.createContextManager(ShardingSphereDataSource.java:76)
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.<init>(ShardingSphereDataSource.java:64)
	at org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactory.createDataSource(ShardingSphereDataSourceFactory.java:93)
	at com.shangma.cn.Main.main(Main.java:46)
```

## 1.4. How to write correctly

**Comment by sandynz** [comment]
Hi @liruhui , looks you're running version 5.2.0, the latest version is 5.3.1, suggest to try 5.3.1.
Use ShardingSphereDriver and yaml, it could be simplified, refere to [ShardingSphere-JDBC]( https://shardingsphere.apache.org/document/5.3.1/en/quick-start/shardingsphere-jdbc-quick-start/ ) for more details.

**Comment by liruhui** [comment]
I find all the examples sharding database and sharding table names called in rule . for example ds_0, ds_1 ,ds_2 ,t_order_0, t_order_1
use inline expression like 'ds_>{}.t_order_>{}' , but i want to know ， if names not called in rule how i write code ?


-------------------------------------------like this -------------------------------------

//set dataSource names not in rule
map.put("xxxx",dataSource);
map.put("yyyy",dataSource1);


ShardingRuleConfiguration shardingRuleConfiguration = new ShardingRuleConfiguration();
ShardingAutoTableRuleConfiguration configuration = new ShardingAutoTableRuleConfiguration("wwww","xxxx.t_grade");
ShardingAutoTableRuleConfiguration configuration1 = new ShardingAutoTableRuleConfiguration("pppp","yyyy.t_stu");



At 2023-03-19 20:56:51, "Hongsheng Zhong" ***@***.***> wrote:

Hi @liruhui , looks you're running version 5.2.0, the latest version is 5.3.1, suggest to try 5.3.1.
Use ShardingSphereDriver and yaml, it could be simplified, refere to ShardingSphere-JDBC for more details.
