### ISSUE TITLE
vertical sharding table problems

### ISSUE THREAD

**Issue by liruhui** [apache/shardingsphere#24741]
# 1. vertical sharding table
```properties 
 table named t_admin has 13 column .  ---vertical sharding--->  three tables, each table with some column 
```

# 2. set and insert logic table  error 
```java
   public static void main(String[] args) throws SQLException {

        Map<String, DataSource> mapDatasource = new HashMap<>();
        DruidDataSource dataSource  = new DruidDataSource();
        dataSource.setDriverClassName(Driver.class.getName());
        dataSource.setUrl("jdbc:mysql://192.168.191.148:3306/admin_account?serverTimezone=UTC");
        dataSource.setUsername("root");
        dataSource.setPassword("rootroot");

        DruidDataSource dataSource1  = new DruidDataSource();
        dataSource1.setDriverClassName(Driver.class.getName());
        dataSource1.setUrl("jdbc:mysql://192.168.191.148:3307/admin_basic?serverTimezone=UTC");
        dataSource1.setUsername("root");
        dataSource1.setPassword("rootroot");

        DruidDataSource dataSource2  = new DruidDataSource();
        dataSource2.setDriverClassName(Driver.class.getName());
        dataSource2.setUrl("jdbc:mysql://192.168.191.148:3308/admin_contact?serverTimezone=UTC");
        dataSource2.setUsername("root");
        dataSource2.setPassword("rootroot");

        mapDatasource.put("xxxx",dataSource);
        mapDatasource.put("yyyy",dataSource1);
        mapDatasource.put("zzzz",dataSource2);

        ShardingRuleConfiguration shardingRuleConfiguration  = new ShardingRuleConfiguration();
        ShardingTableRuleConfiguration configuration  = new ShardingTableRuleConfiguration("t_admin","xxxx.t_admin_account,yyyy.t_admin_basic,zzzz.t_admin_contact");
        shardingRuleConfiguration.getTables().add(configuration);
       //how to set vertical Sharding Table rule ?
       //how to set vertical Sharding Table rule ?
       //how to set vertical Sharding Table rule ?
        DataSource abc = ShardingSphereDataSourceFactory.createDataSource("abc", null, mapDatasource, Collections.singleton(shardingRuleConfiguration), new Properties());

        String sql = "insert into t_admin(admin_id,admin_account,admin_name,admin_phone) values(1,'aaaaa','bbbbb','13333333333')";
        abc.getConnection().prepareStatement(sql).execute();
    }

```
# 3. error info 
```java
Exception in thread "main" java.sql.SQLException: Unknown exception: Insert statement does not support sharding table routing to multiple data nodes.
	at org.apache.shardingsphere.infra.util.exception.external.sql.ShardingSphereSQLException.toSQLException(ShardingSphereSQLException.java:62)
	at org.apache.shardingsphere.dialect.SQLExceptionTransformEngine.toSQLException(SQLExceptionTransformEngine.java:62)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.execute(ShardingSpherePreparedStatement.java:419)
```

# 4:  insert real table correctly

```java
   public static void main(String[] args) throws SQLException {

        Map<String, DataSource> mapDatasource = new HashMap<>();
        DruidDataSource dataSource  = new DruidDataSource();
        dataSource.setDriverClassName(Driver.class.getName());
        dataSource.setUrl("jdbc:mysql://192.168.191.148:3306/admin_account?serverTimezone=UTC");
        dataSource.setUsername("root");
        dataSource.setPassword("rootroot");

        DruidDataSource dataSource1  = new DruidDataSource();
        dataSource1.setDriverClassName(Driver.class.getName());
        dataSource1.setUrl("jdbc:mysql://192.168.191.148:3307/admin_basic?serverTimezone=UTC");
        dataSource1.setUsername("root");
        dataSource1.setPassword("rootroot");

        DruidDataSource dataSource2  = new DruidDataSource();
        dataSource2.setDriverClassName(Driver.class.getName());
        dataSource2.setUrl("jdbc:mysql://192.168.191.148:3308/admin_contact?serverTimezone=UTC");
        dataSource2.setUsername("root");
        dataSource2.setPassword("rootroot");

        mapDatasource.put("xxxx",dataSource);
        mapDatasource.put("yyyy",dataSource1);
        mapDatasource.put("zzzz",dataSource2);
 /////////////////////////////////////////set logic Table && insert logic table /////////////////////////////////////

//        ShardingRuleConfiguration shardingRuleConfiguration  = new ShardingRuleConfiguration();
//        ShardingTableRuleConfiguration configuration  = new ShardingTableRuleConfiguration("t_admin","xxxx.t_admin_account,yyyy.t_admin_basic,zzzz.t_admin_contact");
//        shardingRuleConfiguration.getTables().add(configuration);
//        DataSource abc = ShardingSphereDataSourceFactory.createDataSource("abc", null, mapDatasource, Collections.singleton(shardingRuleConfiguration), new Properties())/////////////////////////////// insert logic Table
//        String sql = "insert into t_admin(admin_id,admin_account,admin_name,admin_phone) values(1,'aaaaa','feizai','13333333333')";
//        abc.getConnection().prepareStatement(sql).execute();

        // insert into real table
        DataSource abc = ShardingSphereDataSourceFactory.createDataSource("abc", null, mapDatasource, null, new Properties());
        abc.getConnection().prepareStatement("insert into t_admin_account(admin_id,admin_account) values(1,'aaaaa')").execute();
        abc.getConnection().prepareStatement("insert into t_admin_basic(admin_id,admin_name) values(1,'bbbbb')").execute();
        abc.getConnection().prepareStatement("insert into t_admin_contact(admin_id,admin_phone) values(1,'cccccc')").execute();
    }
}

```
# 5. My question
``` properties
    vertical sharding table  Is it supported to insert logical tables， the data scattered among the three real tables?

   if support  How to write  
```

**Comment by RaigorJiang** [comment]
Duplicated with #24704.

@liruhui Can you discuss it in the same issue?
