### ISSUE TITLE
Error (HY000): Unable to start CDC correctly due to 'PipelineContext.getContextManager()' is null 

### ISSUE THREAD

**Issue by isHuangXin** [apache/shardingsphere#24869]
For discussion https://github.com/apache/shardingsphere/discussions/24097 （Add ShardingSphere Kafka source connector.）
- When I try to start `org/apache/shardingsphere/data/pipeline/cdc/client/example/Bootstrap.java` i.e. when using CDC (Change Data Capture) function. I found that CDC could not start normally because the code reported the following error message

`[ERROR] 2023-03-28 00:15:02.559 [nioEventLoopGroup-4-5] o.a.s.p.f.n.CDCChannelInboundHandler - caught CDC resolution error
java.lang.NullPointerException: Cannot invoke "org.apache.shardingsphere.mode.manager.ContextManager.getMetaDataContexts()" because the return value of "org.apache.shardingsphere.data.pipeline.core.context.PipelineContext.getContextManager()" is null
	at org.apache.shardingsphere.proxy.backend.handler.cdc.CDCBackendHandler.streamData(CDCBackendHandler.java:85)
	at org.apache.shardingsphere.proxy.frontend.netty.CDCChannelInboundHandler.processStreamDataRequest(CDCChannelInboundHandler.java:181)
	at org.apache.shardingsphere.proxy.frontend.netty.CDCChannelInboundHandler.channelRead(CDCChannelInboundHandler.java:120)`

- I found that the cause of the error is `org.apache.shardingsphere.data.pipeline.core.context.PipelineContext.getContextManager()` is null

- So I debug the code in the idea
I find that the `contextManager` always returns empty, which makes me very confused

<img width="1868" alt="Screenshot 2023-03-28 at 00 29 16" src="https://user-images.githubusercontent.com/57054352/228004764-dcedb76e-1e88-4660-91e5-40d8fb020b3e.png">

<img width="1868" alt="Screenshot 2023-03-28 at 00 25 24" src="https://user-images.githubusercontent.com/57054352/228003788-4d27ab7f-528c-4de8-b486-6f8c970e9e2d.png">
<img width="1868" alt="Screenshot 2023-03-28 at 00 26 10" src="https://user-images.githubusercontent.com/57054352/228003971-5b42e913-bf73-4568-b397-cfed7a256961.png">

**Comment by sandynz** [comment]
Hi @isHuangXin , could you paste your `server.yaml` here? Need to confirm which registry center you're running, it just support Cluster mode for now.

And I've updated `Local Test Steps` section in https://issues.apache.org/jira/browse/GSOC-140

**Comment by isHuangXin** [comment]
- This is my server.yaml
- I found that when using cluster mode, shardingsphere cannot connect to my local zookeeper correctly, I will fix this bug first

![image](https://user-images.githubusercontent.com/57054352/228103124-cf49863f-78a1-4acc-b143-c638dbce64c3.png)

![image](https://user-images.githubusercontent.com/57054352/228103145-fd418bea-fd7e-4b3e-9c38-c26400abf3ae.png)

- zookeeper connection error log

`Exception in thread "main" org.apache.shardingsphere.mode.repository.cluster.exception.ClusterPersistRepositoryException: Cluster persist repository error, reason is: KeeperErrorCode = OperationTimeout
	at org.apache.shardingsphere.mode.repository.cluster.zookeeper.handler.ZookeeperExceptionHandler.handleException(ZookeeperExceptionHandler.java:53)
	at org.apache.shardingsphere.mode.repository.cluster.zookeeper.ZookeeperRepository.initCuratorClient(ZookeeperRepository.java:124)
	at org.apache.shardingsphere.mode.repository.cluster.zookeeper.ZookeeperRepository.init(ZookeeperRepository.java:77)
	at org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.getClusterPersistRepository(ClusterContextManagerBuilder.java:68)
	at org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.build(ClusterContextManagerBuilder.java:49)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.createContextManager(BootstrapInitializer.java:69)
	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.init(BootstrapInitializer.java:59)
	at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:54)`

**Comment by azexcy** [comment]
Have you tried delete zookeeper metadata first, and execute `maven clean xxx` then try CDC again?

**Comment by isHuangXin** [comment]
- ShardingRule error means to configure config-sharding.yaml?

`[ERROR] 2023-03-28 20:35:07.754 [nioEventLoopGroup-4-1] o.a.s.p.f.n.CDCChannelInboundHandler - caught CDC resolution error
java.lang.IllegalStateException: Rule `ShardingRule` should have and only have one instance.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:589)
	at org.apache.shardingsphere.infra.metadata.database.rule.ShardingSphereRuleMetaData.getSingleRule(ShardingSphereRuleMetaData.java:91)
	at org.apache.shardingsphere.proxy.backend.handler.cdc.CDCBackendHandler.streamData(CDCBackendHandler.java:105)
	at org.apache.shardingsphere.proxy.frontend.netty.CDCChannelInboundHandler.processStreamDataRequest(CDCChannelInboundHandler.java:181)
	at org.apache.shardingsphere.proxy.frontend.netty.CDCChannelInboundHandler.channelRead(CDCChannelInboundHandler.java:120)`
	
	
![Screenshot 2023-03-28 at 20 44 49](https://user-images.githubusercontent.com/57054352/228240184-a4faf1f9-5330-4af8-8b1a-da5638ddd779.png)

![Screenshot 2023-03-28 at 20 50 57 1](https://user-images.githubusercontent.com/57054352/228241877-3eef175a-965e-4bbe-a1bf-6845a6d880bf.png)

**Comment by isHuangXin** [comment]
This bug (ShardingRule) is fixed~

**Comment by isHuangXin** [comment]
Thanks for all your help～

**Comment by sandynz** [comment]
@isHuangXin nice
