### ISSUE TITLE
get exception when using nacos

### ISSUE THREAD

**Issue by whaon** [apache/shardingsphere#24966]
![image](https://user-images.githubusercontent.com/2542483/229397862-7c028077-2df1-40bc-90e2-c6b9dcaa4b72.png)
![image](https://user-images.githubusercontent.com/2542483/229397937-703232e3-1c4a-4433-9707-626911988b14.png)

the config in docs is not consistent with the real code
and how do i config a serverLists？
the version is 5.2.1

**Comment by whaon** [comment]
got exception below
`java.lang.NullPointerException: null
	at java.util.Hashtable.put(Hashtable.java:460) ~[?:1.8.0_261]
	at java.util.Properties.setProperty(Properties.java:166) ~[?:1.8.0_261]
	at org.apache.shardingsphere.mode.repository.cluster.nacos.NacosRepository.createClient(NacosRepository.java:111) ~[shardingsphere-cluster-mode-repository-nacos-5.2.1.jar:5.2.1]
	at org.apache.shardingsphere.mode.repository.cluster.nacos.NacosRepository.init(NacosRepository.java:74) ~[shardingsphere-cluster-mode-repository-nacos-5.2.1.jar:5.2.1]
	at org.apache.shardingsphere.mode.repository.cluster.ClusterPersistRepositoryFactory.getInstance(ClusterPersistRepositoryFactory.java:45) ~[shardingsphere-cluster-mode-repository-api-5.2.1.jar:5.2.1]
	at org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.build(ClusterContextManagerBuilder.java:49) ~[shardingsphere-cluster-mode-core-5.2.1.jar:5.2.1]
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.createContextManager(ShardingSphereDataSource.java:76) ~[shardingsphere-jdbc-core-5.2.1.jar:5.2.1]
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.<init>(ShardingSphereDataSource.java:64) ~[shardingsphere-jdbc-core-5.2.1.jar:5.2.1]
	at org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactory.createDataSource(ShardingSphereDataSourceFactory.java:93) ~[shardingsphere-jdbc-core-5.2.1.jar:5.2.1]
	at org.apache.shardingsphere.driver.api.yaml.YamlShardingSphereDataSourceFactory.createDataSource(YamlShardingSphereDataSourceFactory.java:133) ~[shardingsphere-jdbc-core-5.2.1.jar:5.2.1]
	at org.apache.shardingsphere.driver.api.yaml.YamlShardingSphereDataSourceFactory.createDataSource(YamlShardingSphereDataSourceFactory.java:75) ~[shardingsphere-jdbc-core-5.2.1.jar:5.2.1]
`

**Comment by insist777** [comment]
@whaon You can find some basic configuration items for cluster mode on this page.
https://shardingsphere.apache.org/document/5.2.1/en/user-manual/shardingsphere-jdbc/yaml-config/mode/
