### ISSUE TITLE
I use shardingsphere-proxy to migrate data, but it seems that some tables do not take effect

### ISSUE THREAD

**Issue by liaojiexin** [apache/shardingsphere#25182]
sharding-proxy varsion：5.3.2

Here's what I did，
```bash
# 172.28.0.2为shardingsphere-proxy服务器的地址，最后postgres为数据库
psql -h 172.28.0.2 -p 3308 -U root postgres

# 创建sharding_db数据库
CREATE DATABASE sharding_db;

#进入数据库
\c sharding_db

# 配置好存储单元
REGISTER STORAGE UNIT ds_0 (
    URL="jdbc:postgresql://172.28.0.10:5432/postgres",
    USER="postgres",
    PASSWORD="201314",
    PROPERTIES("minPoolSize"="1","maxPoolSize"="20","idleTimeout"="60000")
), ds_1 (
    URL="jdbc:postgresql://172.28.0.20:5432/postgres",
    USER="postgres",
    PASSWORD="201314",
    PROPERTIES("minPoolSize"="1","maxPoolSize"="20","idleTimeout"="60000")
);

# 配置分片规则
# 配置ds_attach_node表的分片规则
CREATE SHARDING TABLE RULE ds_attach_node (
DATANODES("ds_${0..1}.ds_attach_node_${0..1}"),
DATABASE_STRATEGY(TYPE="standard",SHARDING_COLUMN=bimid,SHARDING_ALGORITHM(TYPE(NAME="inline",PROPERTIES("algorithm-expression"="ds_$->{(bimid.hashCode() & Integer.MAX_VALUE %4 ).intdiv(2)}")))),
TABLE_STRATEGY(TYPE="standard",SHARDING_COLUMN=bimid,SHARDING_ALGORITHM(TYPE(NAME="inline",PROPERTIES("algorithm-expression"="ds_attach_node_$->{bimid.hashCode() & Integer.MAX_VALUE %4-(((bimid.hashCode() & Integer.MAX_VALUE %4).intdiv(2)))*2}")))));
# 配置ds_attach_metadata的分片算法
CREATE SHARDING TABLE RULE ds_attach_metadata (
DATANODES("ds_${0..1}.ds_attach_metadata_${0..1}"),
DATABASE_STRATEGY(TYPE="standard",SHARDING_COLUMN=bimid,SHARDING_ALGORITHM(TYPE(NAME="inline",PROPERTIES("algorithm-expression"="ds_$->{(bimid.hashCode() & Integer.MAX_VALUE %4 ).intdiv(2)}")))),
TABLE_STRATEGY(TYPE="standard",SHARDING_COLUMN=bimid,SHARDING_ALGORITHM(TYPE(NAME="inline",PROPERTIES("algorithm-expression"="ds_attach_metadata_$->{bimid.hashCode() & Integer.MAX_VALUE %4-(((bimid.hashCode() & Integer.MAX_VALUE %4).intdiv(2)))*2}")))));
# 配置dl_attach_operate_log的分片算法
CREATE SHARDING TABLE RULE dl_attach_operate_log (
DATANODES("ds_${0..1}.dl_attach_operate_log_${0..1}"),
DATABASE_STRATEGY(TYPE="standard",SHARDING_COLUMN=bimid,SHARDING_ALGORITHM(TYPE(NAME="inline",PROPERTIES("algorithm-expression"="ds_$->{(bimid.hashCode() & Integer.MAX_VALUE %4 ).intdiv(2)}")))),
TABLE_STRATEGY(TYPE="standard",SHARDING_COLUMN=bimid,SHARDING_ALGORITHM(TYPE(NAME="inline",PROPERTIES("algorithm-expression"="dl_attach_operate_log_$->{bimid.hashCode() & Integer.MAX_VALUE %4-(((bimid.hashCode() & Integer.MAX_VALUE %4).intdiv(2)))*2}")))));
# 配置ds_attach_renamelog的分片算法
CREATE SHARDING TABLE RULE ds_attach_renamelog (
DATANODES("ds_${0..1}.ds_attach_renamelog_${0..1}"),
DATABASE_STRATEGY(TYPE="standard",SHARDING_COLUMN=bimid,SHARDING_ALGORITHM(TYPE(NAME="inline",PROPERTIES("algorithm-expression"="ds_$->{(bimid.hashCode() & Integer.MAX_VALUE %4 ).intdiv(2)}")))),
TABLE_STRATEGY(TYPE="standard",SHARDING_COLUMN=bimid,SHARDING_ALGORITHM(TYPE(NAME="inline",PROPERTIES("algorithm-expression"="ds_attach_renamelog_$->{bimid.hashCode() & Integer.MAX_VALUE %4-(((bimid.hashCode() & Integer.MAX_VALUE %4).intdiv(2)))*2}")))));
# 配置ds_attach_extend的分片算法
CREATE SHARDING TABLE RULE ds_attach_extend (
STORAGE_UNITS(ds_0,ds_1),
SHARDING_COLUMN=id,TYPE(NAME="hash_mod",PROPERTIES("sharding-count"="2"))
);
# 配置ds_attach_segment的分片算法
CREATE SHARDING TABLE RULE ds_attach_segment (
STORAGE_UNITS(ds_0,ds_1),
SHARDING_COLUMN=md5,TYPE(NAME="hash_mod",PROPERTIES("sharding-count"="2"))
);

# 配置源存储单元
REGISTER MIGRATION SOURCE STORAGE UNIT ds (
    URL="jdbc:postgresql://172.28.0.3:5432/postgres",
    USER="postgres",
    PASSWORD="201314",
    PROPERTIES("minPoolSize"="1","maxPoolSize"="20","idleTimeout"="60000")
);

# 启动数据迁移
MIGRATE TABLE ds.ds_attach_node into sharding_db.ds_attach_node;
MIGRATE TABLE ds.ds_attach_metadata into sharding_db.ds_attach_metadata;
MIGRATE TABLE ds.dl_attach_operate_log into sharding_db.dl_attach_operate_log;
MIGRATE TABLE ds.ds_attach_renamelog into sharding_db.ds_attach_renamelog;
MIGRATE TABLE ds.ds_attach_extend into sharding_db.ds_attach_extend;
MIGRATE TABLE ds.ds_attach_segment into sharding_db.ds_attach_segment;

# 数据迁移作业列表
SHOW MIGRATION LIST;
                  id                   |             tables              | job_item_count | active |     create_time     | stop_time 
---------------------------------------+---------------------------------+----------------+--------+---------------------+-----------
 j01012201fb9d7a83d2ebb66cff4296804f98 | ds.public.ds_attach_extend      | 1              | true   | 2023-04-16 13:04:35 | 
 j01012c3dbb074ebd2bf8befd6b248b6ebe25 | ds.public.ds_attach_metadata    | 1              | true   | 2023-04-16 13:04:35 | 
 j010154a3756a17017fa3f1f9da8f2558457a | ds.public.ds_attach_renamelog   | 1              | true   | 2023-04-16 13:04:35 | 
 j0101a5a65a89e9b474a4d206bfcdc24cc299 | ds.public.dl_attach_operate_log | 1              | true   | 2023-04-16 13:04:35 | 
 j0101cc68f73c67b7c2e23d3c2125da32fb05 | ds.public.ds_attach_segment     | 1              | true   | 2023-04-16 13:04:35 | 
 j0101d0166123c13a1feb02f2c0a366d48da8 | ds.public.ds_attach_node        | 1              | true   | 2023-04-16 13:04:35 | 
(6 rows)
```

But I have two problems
The first one is **ds_attach_metadata**
```bash
sharding_db=> SHOW MIGRATION STATUS 'j01012c3dbb074ebd2bf8befd6b248b6ebe25';
 item | data_source |            tables            |             status             | active | processed_records_count | inventory_finished_percentage | incremental_idle_seconds 
|                                                             error_message                                                             
------+-------------+------------------------------+--------------------------------+--------+-------------------------+-------------------------------+--------------------------
+---------------------------------------------------------------------------------------------------------------------------------------
 0    | ds          | ds.public.ds_attach_metadata | EXECUTE_INVENTORY_TASK_FAILURE | false  | 0                       | 0                             |                          
| org.apache.shardingsphere.data.pipeline.core.exception.job.PipelineImporterJobWriteException: Importer job write data failed.        +
      |             |                              |                                |        |                         |                               |                          
|         at org.apache.shardingsphere.infra.util.exception.ShardingSpherePreconditions.checkState(ShardingSpherePreconditions.java:41)+
      |             |                              |                                |        |                         |                               |                          
|         at org.apache.shardingsphere.data.pipeline.core.importer.DataSourceImporter.flushInternal(DataSourceImporter.java:134)       +
      |             |                              |                                |        |                         |                               |                          
|         at org.apache.shardingsphere.data.pipeline.core.importer.DataSourceImporter.flush(DataSourceImporter.java:123)               +
      |             |                              |                                |        |                         |                               |                          
|         at org.apache.shardingsphere.data.pipeline.core.importer.DataSourceImporter.runBlocking(DataSourceImporter.java:99)          +
      |             |                              |                                |        |                         |                               |                          
|         at org.apache.shardingsphere.data.pipeline.api.executor.AbstractLifecycleExecutor.start(AbstractLifecycleExecutor.java:52)   +
      |             |                              |                                |        |                         |                               |                          
|         at org.apache.shardingsphere.data.pipeline.api.executor.AbstractLifecycleExecutor.run(AbstractLifecycleExecutor.java:90)     +
      |             |                              |                                |        |                         |                               |                          
|         at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)                                +
      |             |                              |                                |        |                         |                               |                          
|         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)                                 +
      |             |                              |                                |        |                         |                               |                          
|         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)                                 +
      |             |                              |                                |        |                         |                               |                          
|         at java.base/java.lang.Thread.run(Thread.java:833)                                                                           +
      |             |                              |                                |        |                         |                               |                          
| 
(1 row)
```
The second is **ds_attach_segment** and **ds_attach_extend** seems to migrate successfully，but But I can't see the data in the ds_0 and ds_1,
```bash
sharding_db=> SHOW MIGRATION CHECK STATUS 'j0101cc68f73c67b7c2e23d3c2125da32fb05';
           tables            | result | check_failed_tables | finished_percentage | remaining_seconds |    check_begin_time     |     check_end_time      | duration_seconds | err
or_message 
-----------------------------+--------+---------------------+---------------------+-------------------+-------------------------+-------------------------+------------------+----
-----------
 ds.public.ds_attach_segment | true   |                     | 100                 | 0                 | 2023-04-16 14:02:35.413 | 2023-04-16 14:02:39.803 | 4                | 
(1 row)
```

Except that,  other table is normal

Please how should I deal with these two issues

**Comment by tuichenchuxin** [comment]
@azexcy hi, can you help to check it.

**Comment by azexcy** [comment]
Thanks for feedback @liaojiexin 
The first problem need to see the output error log of the Proxy (the problem fixed at the master now, you can see the really errror reason).
The second problem, can you provide create table SQL, help me try to reproduce the problem

**Comment by liaojiexin** [comment]
> Thanks for feedback @liaojiexin The first problem need to see the output error log of the Proxy (the problem fixed at the master now, you can see the really errror reason). The second problem, can you provide create table SQL, help me try to reproduce the problem

```sql
create table ds_attach_segment
(
	userid varchar(100) not null,
	md5 varchar(1000) not null,
	filename varchar(500),
	createtime timestamp(6),
	filepath varchar(1000) not null,
	partcount integer not null,
	uuid varchar(400) not null,
	isdelete boolean default false not null,
	length bigint,
	sid varchar(40) not null
		constraint ds_attach_segment_pk
			primary key
);

comment on table ds_attach_segment is '存储断点续传文件分片信息';

comment on column ds_attach_segment.userid is '上传人id';

comment on column ds_attach_segment.md5 is '文件md5标记（唯一性）';

comment on column ds_attach_segment.filename is '文件名';

comment on column ds_attach_segment.createtime is '分片生成时间';

comment on column ds_attach_segment.filepath is '碎片文件存储路径';

comment on column ds_attach_segment.partcount is '分片数量';

comment on column ds_attach_segment.uuid is 'uuid唯一标识符';

comment on column ds_attach_segment.isdelete is '是否删除';

comment on column ds_attach_segment.length is '文件长度';

comment on column ds_attach_segment.sid is '主键id';

alter table ds_attach_segment owner to postgres;

create index ds_attach_segment_md5_index
	on ds_attach_segment (md5);

create index ds_attach_segment_userid_index
	on ds_attach_segment (userid);

create index ds_attach_segment_uuid_index
	on ds_attach_segment (uuid);
```
```sql
create table ds_attach_extend
(
	id varchar(50) not null
		constraint ds_attach_extend_pkey
			primary key,
	nid varchar(50),
	bimid varchar(50),
	flowid varchar(50),
	confine_size bigint default 0,
	confine_ext varchar(1000) default '*'::character varying,
	confine_kind smallint,
	create_time timestamp(6),
	update_time timestamp(6),
	user_id varchar(50) not null,
	total_size numeric(20),
	template_id varchar(50),
	imagespath varchar(200)
);

comment on table ds_attach_extend is '附件拓展表';

comment on column ds_attach_extend.id is '文件拓展表ID';

comment on column ds_attach_extend.nid is '文件NID';

comment on column ds_attach_extend.bimid is '业务ID';

comment on column ds_attach_extend.flowid is '流程界定ID';

comment on column ds_attach_extend.confine_size is '限制大小(单位byte)';

comment on column ds_attach_extend.confine_ext is '限制拓展名';

comment on column ds_attach_extend.confine_kind is '限制类型';

comment on column ds_attach_extend.create_time is '创建时间';

comment on column ds_attach_extend.update_time is '更新时间';

comment on column ds_attach_extend.user_id is '用户ID';

comment on column ds_attach_extend.total_size is '总大小';

comment on column ds_attach_extend.template_id is '模板ID';

comment on column ds_attach_extend.imagespath is '图片路径(备用字段)';

alter table ds_attach_extend owner to postgres;
```

**Comment by liaojiexin** [comment]
> Thanks for feedback @liaojiexin The first problem need to see the output error log of the Proxy (the problem fixed at the master now, you can see the really errror reason). The second problem, can you provide create table SQL, help me try to reproduce the problem

PostgreSQL (Version 14.2 (Debian 14.2-1.pgdg110+1))

**Comment by azexcy** [comment]
I tested it locally, the  `ds_attach_segment` migration as expected

```
➜  ~ psql --host=localhost --port=3307 postgres root
Password for user root:
psql (14.7, server 12.3-ShardingSphere-Proxy 5.3.3-SNAPSHOT-dirty-dfb83fc)
Type "help" for help.

postgres=> CREATE DATABASE sharding_db;
CREATE DATABASE
postgres=> \c sharding_db
psql (14.7, server 12.3-ShardingSphere-Proxy 5.3.3-SNAPSHOT-dirty-dfb83fc)
You are now connected to database "sharding_db" as user "root".
sharding_db=> REGISTER STORAGE UNIT ds_0 (
sharding_db(>     URL="jdbc:postgresql://127.0.0.1:5432/ds_0",
sharding_db(>     USER="postgres",
sharding_db(>     PASSWORD="postgres"
sharding_db(> );
SUCCESS
sharding_db=>
sharding_db=> REGISTER STORAGE UNIT ds_1 (
sharding_db(>     URL="jdbc:postgresql://127.0.0.1:5432/ds_1",
sharding_db(>     USER="postgres",
sharding_db(>     PASSWORD="postgres"
sharding_db(> );
SUCCESS
sharding_db=> REGISTER MIGRATION SOURCE STORAGE UNIT ds (
sharding_db(>     URL="jdbc:postgresql://127.0.0.1:5432/cdc_db",
sharding_db(>     USER="postgres",
sharding_db(>     PASSWORD="201314",
sharding_db(>     PROPERTIES("minPoolSize"="1","maxPoolSize"="20","idleTimeout"="60000")
sharding_db(> );
SUCCESS
sharding_db=> CREATE SHARDING TABLE RULE ds_attach_segment (
sharding_db(> STORAGE_UNITS(ds_0,ds_1),
sharding_db(> SHARDING_COLUMN=md5,TYPE(NAME="hash_mod",PROPERTIES("sharding-count"="2"))
sharding_db(> );
SUCCESS
sharding_db=> MIGRATE TABLE ds.ds_attach_segment into sharding_db.ds_attach_segment;
SUCCESS
sharding_db=> SHOW MIGRATION LIST;
                     id                     |           tables            | job_item_count | active |     create_time     | stop_time
--------------------------------------------+-----------------------------+----------------+--------+---------------------+-----------
 j0102p0000de4d44121708195f51503f6c146053fd | ds.public.ds_attach_segment | 1              | true   | 2023-04-23 15:32:05 |
(1 row)

sharding_db=> select * from ds_attach_segment;
 userid | md5 | filename |      createtime       | filepath | partcount | uuid | isdelete | length | sid
--------+-----+----------+-----------------------+----------+-----------+------+----------+--------+-----
 1      | 2   | 3        | 2023-04-04 15:29:35.0 | cccc     |         1 | 123  | true     |   1111 | dd
(1 row)

sharding_db=>
```

**Comment by liaojiexin** [comment]
> I tested it locally, the `ds_attach_segment` migration as expected
> 
> ```
> ➜  ~ psql --host=localhost --port=3307 postgres root
> Password for user root:
> psql (14.7, server 12.3-ShardingSphere-Proxy 5.3.3-SNAPSHOT-dirty-dfb83fc)
> Type "help" for help.
> 
> postgres=> CREATE DATABASE sharding_db;
> CREATE DATABASE
> postgres=> \c sharding_db
> psql (14.7, server 12.3-ShardingSphere-Proxy 5.3.3-SNAPSHOT-dirty-dfb83fc)
> You are now connected to database "sharding_db" as user "root".
> sharding_db=> REGISTER STORAGE UNIT ds_0 (
> sharding_db(>     URL="jdbc:postgresql://127.0.0.1:5432/ds_0",
> sharding_db(>     USER="postgres",
> sharding_db(>     PASSWORD="postgres"
> sharding_db(> );
> SUCCESS
> sharding_db=>
> sharding_db=> REGISTER STORAGE UNIT ds_1 (
> sharding_db(>     URL="jdbc:postgresql://127.0.0.1:5432/ds_1",
> sharding_db(>     USER="postgres",
> sharding_db(>     PASSWORD="postgres"
> sharding_db(> );
> SUCCESS
> sharding_db=> REGISTER MIGRATION SOURCE STORAGE UNIT ds (
> sharding_db(>     URL="jdbc:postgresql://127.0.0.1:5432/cdc_db",
> sharding_db(>     USER="postgres",
> sharding_db(>     PASSWORD="201314",
> sharding_db(>     PROPERTIES("minPoolSize"="1","maxPoolSize"="20","idleTimeout"="60000")
> sharding_db(> );
> SUCCESS
> sharding_db=> CREATE SHARDING TABLE RULE ds_attach_segment (
> sharding_db(> STORAGE_UNITS(ds_0,ds_1),
> sharding_db(> SHARDING_COLUMN=md5,TYPE(NAME="hash_mod",PROPERTIES("sharding-count"="2"))
> sharding_db(> );
> SUCCESS
> sharding_db=> MIGRATE TABLE ds.ds_attach_segment into sharding_db.ds_attach_segment;
> SUCCESS
> sharding_db=> SHOW MIGRATION LIST;
>                      id                     |           tables            | job_item_count | active |     create_time     | stop_time
> --------------------------------------------+-----------------------------+----------------+--------+---------------------+-----------
>  j0102p0000de4d44121708195f51503f6c146053fd | ds.public.ds_attach_segment | 1              | true   | 2023-04-23 15:32:05 |
> (1 row)
> 
> sharding_db=> select * from ds_attach_segment;
>  userid | md5 | filename |      createtime       | filepath | partcount | uuid | isdelete | length | sid
> --------+-----+----------+-----------------------+----------+-----------+------+----------+--------+-----
>  1      | 2   | 3        | 2023-04-04 15:29:35.0 | cccc     |         1 | 123  | true     |   1111 | dd
> (1 row)
> 
> sharding_db=>
> ```

I've dealt with the second issue：I found that after executing the above ds_attach_segment rules,two new tables have been added，they are ds_0.ds_attach_segment_0 and ds_1.ds_attach_segment_1.I initially thought that the data was migrated to the ds_0.ds_attach_segment and ds_1.ds_attach_segment tables,so I changed to the following rule:
```sql
# 配置ds_attach_extend的分片算法
ALTER SHARDING TABLE RULE ds_attach_extend (
DATANODES("ds_${0..1}.ds_attach_extend"),
DATABASE_STRATEGY(TYPE="standard",SHARDING_COLUMN=id,SHARDING_ALGORITHM(TYPE(NAME="inline",PROPERTIES("algorithm-expression"="ds_$->{id.hashCode() & Integer.MAX_VALUE %2}")))));
# 配置ds_attach_segment的分片算法
ALTER SHARDING TABLE RULE ds_attach_segment (
DATANODES("ds_${0..1}.ds_attach_segment"),
DATABASE_STRATEGY(TYPE="standard",SHARDING_COLUMN=md5,SHARDING_ALGORITHM(TYPE(NAME="inline",PROPERTIES("algorithm-expression"="ds_$->{md5.hashCode() & Integer.MAX_VALUE %2}")))));
```

Also, regarding the first question, I saw the error message below
```log
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO public.ds_attach_metadata_0(id,fmd5,total,uuid,finished,progress,birthday,path,source_file_nid,pid,bimid) VALUES('CBklG3C4tRxRjZQW6Of', '4f91dcd437ff415eb1c8eeaa0941c381', 169752, 'ada7f8d7-a156-4a3b-a863-1c93665fdbc5', 1, 169752, '2022-04-21 20:38:54.57+00'::timestamp, '/2022/04/21', NULL, NULL, 'BM00004001') ON CONFLICT (id,fmd5) DO UPDATE SET total=EXCLUDED.total,uuid=EXCLUDED.uuid,finished=EXCLUDED.finished,progress=EXCLUDED.progress,birthday=EXCLUDED.birthday,path=EXCLUDED.path,source_file_nid=EXCLUDED.source_file_nid,pid=EXCLUDED.pid,bimid=EXCLUDED.bimid was aborted: ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification  Call getNextException to see other errors in the batch.
2023-04-23 20:42:22     at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
2023-04-23 20:42:22     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2367)
2023-04-23 20:42:22     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2099)
2023-04-23 20:42:22     at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1456)
2023-04-23 20:42:22     at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1481)
2023-04-23 20:42:22     at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:546)
2023-04-23 20:42:22     at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:887)
2023-04-23 20:42:22     at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:910)
2023-04-23 20:42:22     at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1663)
2023-04-23 20:42:22     at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127)
2023-04-23 20:42:22     at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
2023-04-23 20:42:22     at org.apache.shardingsphere.driver.executor.batch.BatchPreparedStatementExecutor$1.executeSQL(BatchPreparedStatementExecutor.java:143)
2023-04-23 20:42:22     at org.apache.shardingsphere.driver.executor.batch.BatchPreparedStatementExecutor$1.executeSQL(BatchPreparedStatementExecutor.java:139)
2023-04-23 20:42:22     at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutorCallback.execute(JDBCExecutorCallback.java:86)
2023-04-23 20:42:22     at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutorCallback.execute(JDBCExecutorCallback.java:65)
2023-04-23 20:42:22     at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.syncExecute(ExecutorEngine.java:133)
2023-04-23 20:42:22     at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.serialExecute(ExecutorEngine.java:119)
2023-04-23 20:42:22     at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.execute(ExecutorEngine.java:113)
2023-04-23 20:42:22     at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutor.execute(JDBCExecutor.java:67)
2023-04-23 20:42:22     at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutor.execute(JDBCExecutor.java:51)
2023-04-23 20:42:22     at org.apache.shardingsphere.driver.executor.batch.BatchPreparedStatementExecutor.executeBatch(BatchPreparedStatementExecutor.java:152)
2023-04-23 20:42:22     at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.executeBatch(ShardingSpherePreparedStatement.java:687)
2023-04-23 20:42:22     at org.apache.shardingsphere.data.pipeline.core.importer.DataSourceImporter.executeBatchInsert(DataSourceImporter.java:191)
2023-04-23 20:42:22     at org.apache.shardingsphere.data.pipeline.core.importer.DataSourceImporter.doFlush(DataSourceImporter.java:158)
2023-04-23 20:42:22     at org.apache.shardingsphere.data.pipeline.core.importer.DataSourceImporter.tryFlush(DataSourceImporter.java:140)
2023-04-23 20:42:22     at org.apache.shardingsphere.data.pipeline.core.importer.DataSourceImporter.flushInternal(DataSourceImporter.java:133)
2023-04-23 20:42:22     at org.apache.shardingsphere.data.pipeline.core.importer.DataSourceImporter.flush(DataSourceImporter.java:123)
2023-04-23 20:42:22     at org.apache.shardingsphere.data.pipeline.core.importer.DataSourceImporter.runBlocking(DataSourceImporter.java:99)
2023-04-23 20:42:22     at org.apache.shardingsphere.data.pipeline.api.executor.AbstractLifecycleExecutor.start(AbstractLifecycleExecutor.java:52)
2023-04-23 20:42:22     at org.apache.shardingsphere.data.pipeline.api.executor.AbstractLifecycleExecutor.run(AbstractLifecycleExecutor.java:90)
2023-04-23 20:42:22     at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
2023-04-23 20:42:22     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-04-23 20:42:22     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-04-23 20:42:22     at java.base/java.lang.Thread.run(Thread.java:833)
2023-04-23 20:42:22 Caused by: org.postgresql.util.PSQLException: ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification
2023-04-23 20:42:22     at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
2023-04-23 20:42:22     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
2023-04-23 20:42:22     ... 32 common frames omitted
```
This is the SQL that creates the ds_attach_metadata table
```sql
create table ds_attach_metadata
(
	id varchar(20) not null
		constraint ds_attach_metadata_pkey
			primary key,
	fmd5 varchar(40) default 'NULL'::character varying not null,
	total bigint default '0'::bigint,
	uuid varchar(40),
	finished smallint default '0'::smallint,
	progress bigint default '0'::bigint,
	birthday timestamp(6) default CURRENT_TIMESTAMP,
	path varchar(256),
	source_file_nid varchar(50),
	pid varchar(50),
	bimid varchar(32)
);

alter table ds_attach_metadata owner to postgres;

create unique index ds_attach_metadata_fmd5_uindex
	on ds_attach_metadata (fmd5);

create index ds_attach_metadata_bimid_index
	on ds_attach_metadata (bimid);
```

**Comment by azexcy** [comment]
@liaojiexin I guess the table without unique key (the unique key column default value can't be null) migration have problem at 5.3.2, please try master branch, I have already fix this problem

**Comment by liaojiexin** [comment]
> @liaojiexin I guess the table without unique key (the unique key column default value can't be null) migration have problem at 5.3.2, please try master branch, I have already fix this problem

Ok, thank you very much
