### ISSUE TITLE
Caused by: java.lang.ClassCastException: class java.math.BigInteger cannot be cast to class java.lang.Long (java.math.BigInteger and java.lang.Long are in module java.base of loader 'bootstrap')

### ISSUE THREAD

**Issue by wsky586** [apache/shardingsphere#25197]
environment shardingsphere 5.3.2 centos 8.7 mysql 8.0.26 mysql driver 8.0.1-8.0.32

Caused by: java.lang.ClassCastException: class java.math.BigInteger cannot be cast to class java.lang.Long (java.math.BigInteger and java.lang.Long are in module java.base of loader 'bootstrap')
	at java.base/java.lang.Long.compareTo(Long.java:59)
	at org.apache.shardingsphere.sharding.merge.dql.orderby.CompareUtil.compareTo(CompareUtil.java:56)
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.compareTo(OrderByValue.java:123)
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.compareTo(OrderByValue.java:44)
	at java.base/java.util.PriorityQueue.siftUpComparable(PriorityQueue.java:662)
	at java.base/java.util.PriorityQueue.siftUp(PriorityQueue.java:654)
	at java.base/java.util.PriorityQueue.offer(PriorityQueue.java:345)
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByStreamMergedResult.orderResultSetsToQueue(OrderByStreamMergedResult.java:58)
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByStreamMergedResult.<init>(OrderByStreamMergedResult.java:50)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.build(ShardingDQLResultMerger.java:100)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.merge(ShardingDQLResultMerger.java:71)
	at org.apache.shardingsphere.infra.merge.MergeEngine.executeMerge(MergeEngine.java:81)
	at org.apache.shardingsphere.infra.merge.MergeEngine.merge(MergeEngine.java:71)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.mergeQuery(ShardingSpherePreparedStatement.java:608)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.executeQuery(ShardingSpherePreparedStatement.java:270)

**Comment by linghengqian** [comment]
- I'd like to believe that this is a problem like https://github.com/apache/shardingsphere/issues/22736, that ResultSet lacks a corresponding transformation.  

- Can you provide a unit test? Or are you planning to submit a PR?

**Comment by treezhu** [comment]
I have the same question,help

**Comment by linghengqian** [comment]
> I have the same question,help

- Can you provide any unit tests that are convenient for debugging?

**Comment by wsky586** [comment]
> 

select * from tableName order by id.

**Comment by wsky586** [comment]
> * I'd like to believe that this is a problem like [The `getString()` function of `ShardingSphereResultSet` should try to convert the object before throwing an exception #22736](https://github.com/apache/shardingsphere/issues/22736), that ResultSet lacks a corresponding transformation.
> * Can you provide a unit test? Or are you planning to submit a PR?

select * from tableName order by id desc

**Comment by linghengqian** [comment]
> > * I'd like to believe that this is a problem like [The `getString()` function of `ShardingSphereResultSet` should try to convert the object before throwing an exception #22736](https://github.com/apache/shardingsphere/issues/22736), that ResultSet lacks a corresponding transformation.
> > * Can you provide a unit test? Or are you planning to submit a PR?
> 
> select * from tableName order by id desc

- I tested this SQL with ShardingSphere Proxy, but I didn't see the Error Log.  Can you provide an Example project?

**Comment by wsky586** [comment]
> > > * I'd like to believe that this is a problem like [The `getString()` function of `ShardingSphereResultSet` should try to convert the object before throwing an exception #22736](https://github.com/apache/shardingsphere/issues/22736), that ResultSet lacks a corresponding transformation.
> > > * Can you provide a unit test? Or are you planning to submit a PR?
> > 
> > 
> > select * from tableName order by id desc
> 
> * I tested this SQL with ShardingSphere Proxy, but I didn't see the Error Log.  Can you provide an Example project?

sorry,  Due to field type settings, bigint **unsigned**

**Comment by treezhu** [comment]
yes , id's type can't be 'bigint unsigned'
