### ISSUE TITLE
Use JDBC to execute cursor-related SQL. After closing the cursor, redefine the cursor with the same name. There is a problem with the cursor.

### ISSUE THREAD

**Issue by peilinqian** [apache/shardingsphere#25236]
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
we find java version: java8, full_version=1.8.0_282, full_path=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/bin/java
ShardingSphere-5.3.1

### Expected behavior
Use JDBC to execute cursor-related SQL. After closing the cursor, redefine the cursor with the same name. the cursor can be executed normally； 
### Actual behavior
Use JDBC to execute cursor-related SQL. After closing the cursor, redefine the cursor with the same name. There is a problem with the cursor. 
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1.javac -encoding utf-8 -cp opengauss-jdbc-5.0.0.jar CursorCase0024.java
2.java -cp ./*:./ CursorCase0024 7.212.123.28:11000 test_db root root

**Cursor names are same，the result is incorrect** 
```
createresult = 0
insert = 9
excute sql1: FETCH FORWARD 1 FROM cursor1;
1 | 1 | 
excute sql2: fetch 2 from cursor1;
1 | 2 | 
1 | 2 | 
excute sql3: fetch from cursor1;
2 | 1 | 
excute sql4: fetch next from cursor1;
2 | 2 | 
excute sql5: fetch forward all from cursor1;
2 | 3 | 
3 | 1 | 
3 | 3 | 
3 | 3 | 
excute sql6: FETCH cursor1;
excute sql1: FETCH FORWARD 1 FROM cursor1;
1 | 1 | Exception in thread "main" org.opengauss.util.PSQLException: 栏位索引超过许可范围：3，栏位数：2。
	at org.opengauss.jdbc.PgResultSet.checkColumnIndex(PgResultSet.java:2897)
	at org.opengauss.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2938)
	at org.opengauss.jdbc.PgResultSet.getString(PgResultSet.java:2012)
	at CursorCase0024.main(CursorCase0024.java:51)
```

**Cursor names are different，the result is correct**
```
createresult = false
insert = 9
excute sql1: FETCH FORWARD 1 FROM cursor1;
1 | 1 | 
excute sql2: fetch 2 from cursor1;
1 | 2 | 
1 | 2 | 
excute sql3: fetch from cursor1;
2 | 1 | 
excute sql4: fetch next from cursor1;
2 | 2 | 
excute sql5: fetch forward all from cursor1;
2 | 3 | 
3 | 1 | 
3 | 3 | 
3 | 3 | 
excute sql6: FETCH cursor1;
excute sql1: FETCH FORWARD 1 FROM cursor2;
1 | 1 | 10 | test1 | 
excute sql2: fetch 2 from cursor2;
1 | 2 | 10 | Test12 | 
1 | 2 | null | test12 | 
excute sql3: fetch from cursor2;
2 | 1 | 20 | test21 | 
excute sql4: fetch next from cursor2;
2 | 2 | 20 | test22 | 
excute sql5: fetch forward all from cursor2;
2 | 3 | null | Test22 | 
3 | 1 | null | test31 | 
3 | 3 | null | test3 | 
3 | 3 | null | test3 | 
excute sql6: FETCH cursor2;
```
### Example codes for reproduce this issue (such as a github link).

```
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

public class CursorCase0024 {
	public static void main(String[] args) throws Exception {
		if (args.length < 4) {
			System.out.print("指定连接参数不全，需要host:ip,db,user,password,4个参数");
			return;
		}
		Connection connection = DriverManager.getConnection("jdbc:opengauss://" + args[0] + "/" + args[1], args[2],
				args[3]);
		Statement stmt = null;
		String tb_name = "t_ssdb";
		stmt = connection.createStatement();
		int create = stmt.executeUpdate("drop table if exists " + tb_name + ";" + "create table " + tb_name
				+ "(id int,c_id int,a int,b text);");
		System.out.println("createresult = " + create);
		int insert = stmt.executeUpdate(
				"insert into " + tb_name + " values " + "(1,1,10,'test1'),(1,2,10,'Test12'),(1,2,null,'test12'),"
						+ "(2,1,20,'test21'),(2,2,20,'test22'),(2,3,null,'Test22'),"
						+ "(3,3,null,'test3'),(3,3,null,'test3'),(3,1,null,'test31');");
		System.out.println("insert = " + insert);

		stmt.execute("start transaction;");
		stmt.execute("cursor cursor1 for select id,c_id from " + tb_name + " order by 1,2;");
		String[] sqls = { "FETCH FORWARD 1 FROM cursor1;", "fetch 2 from cursor1;", "fetch from cursor1;",
				"fetch next from cursor1;", "fetch forward all from cursor1;", "FETCH cursor1;" };
		for (int i = 1; i < sqls.length + 1; ++i) {
			System.out.println("excute sql" + i + ": " + sqls[i - 1]);
			ResultSet resultSet = stmt.executeQuery(sqls[i - 1]);
			while (resultSet.next()) {
				System.out.print(resultSet.getInt(1) + " | ");
				System.out.println(resultSet.getInt(2) + " | ");
			}
		}
		stmt.execute("close cursor1;");
		stmt.execute("end;");

		stmt.execute("start transaction;");
		stmt.execute("cursor cursor1 for select * from " + tb_name + " order by 1,2;");
		String[] sqls1 = { "FETCH FORWARD 1 FROM cursor1;", "fetch 2 from cursor1;", "fetch from cursor1;",
				"fetch next from cursor1;", "fetch forward all from cursor1;", "FETCH cursor1;" };
		for (int i = 1; i < sqls1.length + 1; ++i) {
			System.out.println("excute sql" + i + ": " + sqls1[i - 1]);
			ResultSet resultSet = stmt.executeQuery(sqls1[i - 1]);
			while (resultSet.next()) {
				System.out.print(resultSet.getInt(1) + " | ");
				System.out.print(resultSet.getInt(2) + " | ");
				System.out.print(resultSet.getString(3) + " | ");
				System.out.println(resultSet.getString(4) + " | ");
			}
		}
		stmt.execute("close cursor1;");
		stmt.execute("end;");
		stmt.close();
		connection.close();
	}
}
```

**Comment by FlyingZC** [comment]
I want to investigate it. @strongduanmu

**Comment by strongduanmu** [comment]
@FlyingZC Assigned.

**Comment by FlyingZC** [comment]
Hi, this case is successfully executed locally.
```java
@Test
    public void testOgCursor() throws Exception {
        dataSource = xxx.getDataSource();
        Connection connection = dataSource.getConnection();
        String tb_name = "t_ssdb";
        Statement stmt = connection.createStatement();
        
        // creatTable(tb_name, stmt);

        for (int i = 0; i < 3; i++) {
            cursor(tb_name, stmt);
        }
        
        stmt.close();
        connection.close();
    }

    private static void creatTable(String tb_name, Statement stmt) throws SQLException {
        int create = stmt.executeUpdate("drop table if exists " + tb_name + ";" + "create table " + tb_name
                + "(id int,c_id int,a int,b text);");
        System.out.println("createresult = " + create);

        int insert = stmt.executeUpdate(
                "insert into " + tb_name + " values " + "(1,1,10,'test1'),(1,2,10,'Test12'),(1,2,null,'test12'),"
                        + "(2,1,20,'test21'),(2,2,20,'test22'),(2,3,null,'Test22'),"
                        + "(3,3,null,'test3'),(3,3,null,'test3'),(3,1,null,'test31');");
        System.out.println("insert = " + insert);
    }

    private static void cursor(String tb_name, Statement stmt) throws SQLException {
        System.out.println("=============================================================");
        stmt.execute("start transaction;");
        stmt.execute("cursor cursor1 for select id,c_id from " + tb_name + " order by 1,2;");
        String[] sqls = {"FETCH FORWARD 1 FROM cursor1;", "fetch 2 from cursor1;", "fetch from cursor1;",
                "fetch next from cursor1;", "fetch forward all from cursor1;", "FETCH cursor1;"};
        for (
                int i = 1;
                i < sqls.length + 1; ++i) {
            System.out.println("excute sql" + i + ": " + sqls[i - 1]);
            ResultSet resultSet = stmt.executeQuery(sqls[i - 1]);
            while (resultSet.next()) {
                System.out.print(resultSet.getInt(1) + " | ");
                System.out.println(resultSet.getInt(2) + " | ");
            }
        }
        stmt.execute("close cursor1;");
        stmt.execute("end;");
    }
```

Result is as follow:
```sql
=============================================================
excute sql1: FETCH FORWARD 1 FROM cursor1;
1 | 1 | 
excute sql2: fetch 2 from cursor1;
1 | 2 | 
1 | 2 | 
excute sql3: fetch from cursor1;
2 | 1 | 
excute sql4: fetch next from cursor1;
2 | 2 | 
excute sql5: fetch forward all from cursor1;
2 | 3 | 
3 | 1 | 
3 | 3 | 
3 | 3 | 
excute sql6: FETCH cursor1;
=============================================================
excute sql1: FETCH FORWARD 1 FROM cursor1;
1 | 1 | 
excute sql2: fetch 2 from cursor1;
1 | 2 | 
1 | 2 | 
excute sql3: fetch from cursor1;
2 | 1 | 
excute sql4: fetch next from cursor1;
2 | 2 | 
excute sql5: fetch forward all from cursor1;
2 | 3 | 
3 | 1 | 
3 | 3 | 
3 | 3 | 
excute sql6: FETCH cursor1;
=============================================================
excute sql1: FETCH FORWARD 1 FROM cursor1;
1 | 1 | 
excute sql2: fetch 2 from cursor1;
1 | 2 | 
1 | 2 | 
excute sql3: fetch from cursor1;
2 | 1 | 
excute sql4: fetch next from cursor1;
2 | 2 | 
excute sql5: fetch forward all from cursor1;
2 | 3 | 
3 | 1 | 
3 | 3 | 
3 | 3 | 
excute sql6: FETCH cursor1;
```

**Comment by FlyingZC** [comment]
The following case can also be successfully executed locally, start a transaction, and create a cursor with the same name.
```java
@Test
    public void testOgCursor() throws Exception {
        dataSource = xx.getDataSource();
        Connection connection = dataSource.getConnection();
        String tb_name = "t_ssdb";
        Statement stmt = connection.createStatement();
        
        // creatTable(tb_name, stmt);

        executeStatementWithLog(stmt, "start transaction;");
        for (int i = 0; i < 3; i++) {
            cursor(tb_name, stmt);
        }
        executeStatementWithLog(stmt, "end;");
        
        stmt.close();
        connection.close();
    }

    private static void executeStatementWithLog(Statement stmt, String sql) throws SQLException {
        System.out.println(sql);
        stmt.execute(sql);
    }

    private static void creatTable(String tb_name, Statement stmt) throws SQLException {
        int create = stmt.executeUpdate("drop table if exists " + tb_name + ";" + "create table " + tb_name
                + "(id int,c_id int,a int,b text);");
        System.out.println("createresult = " + create);

        int insert = stmt.executeUpdate(
                "insert into " + tb_name + " values " + "(1,1,10,'test1'),(1,2,10,'Test12'),(1,2,null,'test12'),"
                        + "(2,1,20,'test21'),(2,2,20,'test22'),(2,3,null,'Test22'),"
                        + "(3,3,null,'test3'),(3,3,null,'test3'),(3,1,null,'test31');");
        System.out.println("insert = " + insert);
    }

    private static void cursor(String tb_name, Statement stmt) throws SQLException {
        System.out.println("=============================================================");
        
        stmt.execute("cursor cursor1 for select id,c_id from " + tb_name + " order by 1,2;");
        String[] sqls = {"FETCH FORWARD 1 FROM cursor1;", "fetch 2 from cursor1;", "fetch from cursor1;",
                "fetch next from cursor1;", "fetch forward all from cursor1;", "FETCH cursor1;"};
        for (
                int i = 1;
                i < sqls.length + 1; ++i) {
            System.out.println("excute sql" + i + ": " + sqls[i - 1]);
            ResultSet resultSet = stmt.executeQuery(sqls[i - 1]);
            while (resultSet.next()) {
                System.out.print(resultSet.getInt(1) + " | ");
                System.out.println(resultSet.getInt(2) + " | ");
            }
        }
        stmt.execute("close cursor1;");
    }
```

```sql

start transaction;
=============================================================
excute sql1: FETCH FORWARD 1 FROM cursor1;
1 | 1 | 
excute sql2: fetch 2 from cursor1;
1 | 2 | 
1 | 2 | 
excute sql3: fetch from cursor1;
2 | 1 | 
excute sql4: fetch next from cursor1;
2 | 2 | 
excute sql5: fetch forward all from cursor1;
2 | 3 | 
3 | 1 | 
3 | 3 | 
3 | 3 | 
excute sql6: FETCH cursor1;
=============================================================
excute sql1: FETCH FORWARD 1 FROM cursor1;
1 | 1 | 
excute sql2: fetch 2 from cursor1;
1 | 2 | 
1 | 2 | 
excute sql3: fetch from cursor1;
2 | 1 | 
excute sql4: fetch next from cursor1;
2 | 2 | 
excute sql5: fetch forward all from cursor1;
2 | 3 | 
3 | 1 | 
3 | 3 | 
3 | 3 | 
excute sql6: FETCH cursor1;
=============================================================
excute sql1: FETCH FORWARD 1 FROM cursor1;
1 | 1 | 
excute sql2: fetch 2 from cursor1;
1 | 2 | 
1 | 2 | 
excute sql3: fetch from cursor1;
2 | 1 | 
excute sql4: fetch next from cursor1;
2 | 2 | 
excute sql5: fetch forward all from cursor1;
2 | 3 | 
3 | 1 | 
3 | 3 | 
3 | 3 | 
excute sql6: FETCH cursor1;
end;
```

**Comment by FlyingZC** [comment]
The reason why you encounter this error is: the query result has two columns, trying to get the third column.
```
excute sql1: FETCH FORWARD 1 FROM cursor1;
1 | 1 | Exception in thread "main" org.opengauss.util.PSQLException: 栏位索引超过许可范围：3，栏位数：2。
	at org.opengauss.jdbc.PgResultSet.checkColumnIndex(PgResultSet.java:2897)
	at org.opengauss.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2938)
	at org.opengauss.jdbc.PgResultSet.getString(PgResultSet.java:2012)
	at CursorCase0024.main(CursorCase0024.java:51)
```
