### ISSUE TITLE
Sharding startup failed after upgrading the snake yml component to version 2.0

### ISSUE THREAD

**Issue by sushuliang113** [apache/shardingsphere#25291]
sharding version：   
     <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core</artifactId>
            <version>5.3.2</version>	
       <dependency>
snakeYaml version：
     <dependency>
	<groupId>org.yaml</groupId>
	<artifactId>snakeyaml</artifactId>
	<version>2.0</version>  
     </dependency>

at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-2.7.10.jar:2.7.10]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164) ~[spring-boot-2.7.10.jar:2.7.10]
	at com.huawei.hdn.explorer.Application.main(Application.java:71) ~[classes/:?]
Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method <init>()V not found
	at org.apache.shardingsphere.infra.util.yaml.representer.ShardingSphereYamlRepresenter.<init>(ShardingSphereYamlRepresenter.java:42) ~[shardingsphere-infra-util-5.3.2.jar:5.3.2]
	at org.apache.shardingsphere.infra.util.yaml.YamlEngine.marshal(YamlEngine.java:113) ~[shardingsphere-infra-util-5.3.2.jar:5.3.2]
	at org.apache.shardingsphere.mode.metadata.persist.service.config.global.PropertiesPersistService.persist(PropertiesPersistService.java:45) ~[shardingsphere-mode-core-5.3.2.jar:5.3.2]
	at org.apache.shardingsphere.mode.metadata.persist.service.config.global.PropertiesPersistService.conditionalPersist(PropertiesPersistService.java:39) ~[shardingsphere-mode-core-5.3.2.jar:5.3.2]
	at org.apache.shardingsphere.mode.metadata.persist.MetaDataPersistService.persistConfigurations(MetaDataPersistService.java:86) ~[shardingsphere-mode-core-5.3.2.jar:5.3.2]
	at org.apache.shardingsphere.mode.manager.standalone.StandaloneContextManagerBuilder.persistConfigurations(StandaloneContextManagerBuilder.java:61) ~[shardingsphere-standalone-mode-core-5.3.2

**Comment by RaigorJiang** [comment]
ShardingSphere now uses snakeyaml 1.3.3, there may be compatibility problem with different versions.

**Comment by linghengqian** [comment]
- @sushuliang113 Hey, I've flagged this issue, which is https://github.com/apache/shardingsphere/issues/21476 and https://github.com/apache/shardingsphere/pull/24636 . 

- Due to the fact that modifying to Snapeyaml 2.0 functions would compromise the compatibility of all current versions of the Spring Framework, I tend to wait for the Spring Team to make the changes first.

**Comment by linghengqian** [comment]
> > * @sushuliang113 Hey, I've flagged this issue, which is [Markup SpringBoot users need to specify SnakeYAML version in Github Wiki #21476](https://github.com/apache/shardingsphere/issues/21476) and [Upgrade snakeyaml to 2.0 #24636](https://github.com/apache/shardingsphere/pull/24636) .
> > * Due to the fact that modifying to SnakeYaml 2.0 functions would compromise the compatibility of all current versions of the Spring Framework, I tend to wait for the Spring Team to make the changes first.
> 
> I am using 4.1.1, will this version support snakeyaml 2.0?

_ Considering the API changes in SnakeYAML in the last 2 years, I don't think this is possible.

**Comment by hsld9527** [comment]
> * @sushuliang113 Hey, I've flagged this issue, which is [Markup SpringBoot users need to specify SnakeYAML version in Github Wiki #21476](https://github.com/apache/shardingsphere/issues/21476) and [Upgrade snakeyaml to 2.0 #24636](https://github.com/apache/shardingsphere/pull/24636) .
> * Due to the fact that modifying to SnakeYaml 2.0 functions would compromise the compatibility of all current versions of the Spring Framework, I tend to wait for the Spring Team to make the changes first.

SpringBoot 2.7.10 alreadey supports SnakeYaml 2.0, but I see there is no Sharding 4.x to support SnakeYaml 2.0, and the problem still exists

**Comment by linghengqian** [comment]
> > * @sushuliang113 Hey, I've flagged this issue, which is [Markup SpringBoot users need to specify SnakeYAML version in Github Wiki #21476](https://github.com/apache/shardingsphere/issues/21476) and [Upgrade snakeyaml to 2.0 #24636](https://github.com/apache/shardingsphere/pull/24636) .
> > * Due to the fact that modifying to SnakeYaml 2.0 functions would compromise the compatibility of all current versions of the Spring Framework, I tend to wait for the Spring Team to make the changes first.
> 
> SpringBoot 2.7.10 alreadey supports SnakeYaml 2.0, but I see there is no Sharding 4.x to support SnakeYaml 2.0, and the problem still exists

- Considering that it is impossible to commit back to the ShardingSphere 4.x branch, I think this is an impossible thing.
