### ISSUE TITLE
ShardingSphere-JDBC Are there plans to support using functions in cross-library union queries?

### ISSUE THREAD

**Issue by China-Uncle** [apache/shardingsphere#25335]
ShardingSphere-JDBC Are there plans to support using functions in cross-library union queries?

**Comment by strongduanmu** [comment]
I can't get your point, can you describe your request in detail?

**Comment by China-Uncle** [comment]
> I can't get your point, can you describe your request in detail?

Use sql-federation-type
The use of mysql functions is not allowed
```
Caused by: org.apache.calcite.sql.validate.SqlValidatorException: No match found for function signature AES_ENCRYPT(<CHARACTER>, <CHARACTER>)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:505)
	at org.apache.calcite.runtime.Resources$ExInst.ex(Resources.java:599)
	... 150 more
```

**Comment by strongduanmu** [comment]
Thank you for your feedback. Currently, the federation query engine relies on Calcite, and some MySQL functions are not supported. We plan to gradually enhance function support in future releases, welcome to join us.

**Comment by shengdoupi** [comment]
> Thank you for your feedback. Currently, the federation query engine relies on Calcite, and some MySQL functions are not supported. We plan to gradually enhance function support in future releases, welcome to join us.

@strongduanmu Hi, I am interested in realizing this feature, but I think I need to get familiar with the federation query engine in ShardingSphere first. Can you give some instructions please?  Thanks.

**Comment by terrymanu** [comment]
I don't think "library" is a concept related to ShardingSphere. Due to the high cost of understanding, please allow me to close this issue.
