### ISSUE TITLE
Shradingsphere-proxy had a driver error while migrating data from the Postgres database

### ISSUE THREAD

**Issue by liaojiexin** [apache/shardingsphere#25405]
I'm having another issue while working on issue #25182
I tried the following two docker images
Deployment method：
```bash
docker pull ghcr.io/apache/shardingsphere-proxy:845d1007809d358965fc07fdbe451467eeb1f63e@sha256:3ae631cb87484e27c1255034ec0f228a1af4e613b526f6ad05c98c1123eda957

docker pull ghcr.io/apache/shardingsphere-proxy:7cc22179acab886cc9900954114cb3778d9cf701@sha256:55d115cde0b49c0366eea0fc5509e250b8c8af660dfd41580e71aee04a92a5f1
```
error info:
```log
java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:h2:mem:config;DB_CLOSE_DELAY=0;DATABASE_TO_UPPER=false;MODE=MYSQL
2023-04-28 17:23:53     at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:114)
2023-04-28 17:23:53     at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:331)
2023-04-28 17:23:53     at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:114)
2023-04-28 17:23:53     at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:108)
2023-04-28 17:23:53     at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
2023-04-28 17:23:53     at org.apache.shardingsphere.mode.repository.standalone.jdbc.JDBCRepository.init(JDBCRepository.java:65)
2023-04-28 17:23:53     at org.apache.shardingsphere.infra.util.spi.type.typed.TypedSPILoader.findService(TypedSPILoader.java:86)
2023-04-28 17:23:53     at org.apache.shardingsphere.infra.util.spi.type.typed.TypedSPILoader.findService(TypedSPILoader.java:70)
2023-04-28 17:23:53     at org.apache.shardingsphere.infra.util.spi.type.typed.TypedSPILoader.getService(TypedSPILoader.java:127)
2023-04-28 17:23:53     at org.apache.shardingsphere.mode.manager.standalone.StandaloneContextManagerBuilder.build(StandaloneContextManagerBuilder.java:47)
2023-04-28 17:23:53     at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.createContextManager(ShardingSphereDataSource.java:82)
2023-04-28 17:23:53     at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.<init>(ShardingSphereDataSource.java:69)
2023-04-28 17:23:53     at org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactory.createDataSource(ShardingSphereDataSourceFactory.java:93)
2023-04-28 17:23:53     at org.apache.shardingsphere.driver.api.yaml.YamlShardingSphereDataSourceFactory.createDataSource(YamlShardingSphereDataSourceFactory.java:153)
2023-04-28 17:23:53     at org.apache.shardingsphere.driver.api.yaml.YamlShardingSphereDataSourceFactory.createDataSourceWithoutCache(YamlShardingSphereDataSourceFactory.java:63)
2023-04-28 17:23:53     at org.apache.shardingsphere.driver.data.pipeline.datasource.creator.ShardingSpherePipelineDataSourceCreator.createPipelineDataSource(ShardingSpherePipelineDataSourceCreator.java:45)
2023-04-28 17:23:53     at org.apache.shardingsphere.data.pipeline.core.datasource.PipelineDataSourceFactory.newInstance(PipelineDataSourceFactory.java:46)
2023-04-28 17:23:53     at org.apache.shardingsphere.data.pipeline.core.datasource.DefaultPipelineDataSourceManager.getDataSource(DefaultPipelineDataSourceManager.java:53)
2023-04-28 17:23:53     at org.apache.shardingsphere.data.pipeline.core.prepare.datasource.AbstractDataSourcePreparer.getCachedDataSource(AbstractDataSourcePreparer.java:85)
2023-04-28 17:23:53     at org.apache.shardingsphere.data.pipeline.postgresql.prepare.datasource.PostgreSQLDataSourcePreparer.prepareTargetTables(PostgreSQLDataSourcePreparer.java:41)
2023-04-28 17:23:53     at org.apache.shardingsphere.data.pipeline.core.prepare.PipelineJobPreparerUtils.prepareTargetTables(PipelineJobPreparerUtils.java:120)
2023-04-28 17:23:53     at org.apache.shardingsphere.data.pipeline.scenario.migration.prepare.MigrationJobPreparer.prepareTarget(MigrationJobPreparer.java:153)
2023-04-28 17:23:53     at org.apache.shardingsphere.data.pipeline.scenario.migration.prepare.MigrationJobPreparer.prepareAndCheckTarget(MigrationJobPreparer.java:132)
2023-04-28 17:23:53     at org.apache.shardingsphere.data.pipeline.scenario.migration.prepare.MigrationJobPreparer.prepareAndCheckTargetWithLock(MigrationJobPreparer.java:118)
2023-04-28 17:23:53     at org.apache.shardingsphere.data.pipeline.scenario.migration.prepare.MigrationJobPreparer.prepare(MigrationJobPreparer.java:84)
2023-04-28 17:23:53     at org.apache.shardingsphere.data.pipeline.scenario.migration.MigrationJob.doPrepare(MigrationJob.java:74)
2023-04-28 17:23:53     at org.apache.shardingsphere.data.pipeline.core.job.AbstractPipelineJob.prepare(AbstractPipelineJob.java:71)
2023-04-28 17:23:53     at org.apache.shardingsphere.data.pipeline.core.job.AbstractSimplePipelineJob.execute(AbstractSimplePipelineJob.java:58)
2023-04-28 17:23:53     at org.apache.shardingsphere.elasticjob.simple.executor.SimpleJobExecutor.process(SimpleJobExecutor.java:33)
2023-04-28 17:23:53     at org.apache.shardingsphere.elasticjob.simple.executor.SimpleJobExecutor.process(SimpleJobExecutor.java:29)
2023-04-28 17:23:53     at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.process(ElasticJobExecutor.java:173)
2023-04-28 17:23:53     at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.process(ElasticJobExecutor.java:142)
2023-04-28 17:23:53     at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.execute(ElasticJobExecutor.java:124)
2023-04-28 17:23:53     at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.execute(ElasticJobExecutor.java:100)
2023-04-28 17:23:53     at org.apache.shardingsphere.elasticjob.lite.internal.schedule.LiteJob.execute(LiteJob.java:35)
2023-04-28 17:23:53     at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
2023-04-28 17:23:53     at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2023-04-28 17:23:53 Caused by: java.sql.SQLException: No suitable driver
2023-04-28 17:23:53     at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:299)
2023-04-28 17:23:53     at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:106)
2023-04-28 17:23:53     ... 36 common frames omitted
```
server.yml
```yml
mode:
 type: Cluster
 repository:
   type: ZooKeeper
   props:
     namespace: governance_ds
     server-lists: gateway.docker.internal:2181
     retryIntervalMilliseconds: 500
     timeToLiveSeconds: 60
     maxRetries: 3
     operationTimeoutMilliseconds: 500

authority:
 users:
   - user: root@%
     password: root
   - user: sharding
     password: sharding
 privilege:
   type: ALL_PERMITTED

props:
 proxy-frontend-database-protocol-type: PostgreSQL
 system-log-level: DEBUG
```

**Comment by liaojiexin** [comment]
> ```shell
> docker pull ghcr.io/apache/shardingsphere-proxy:845d1007809d358965fc07fdbe451467eeb1f63e@sha256:3ae631cb87484e27c1255034ec0f228a1af4e613b526f6ad05c98c1123eda957
> 
> docker pull ghcr.io/apache/shardingsphere-proxy:7cc22179acab886cc9900954114cb3778d9cf701@sha256:55d115cde0b49c0366eea0fc5509e250b8c8af660dfd41580e71aee04a92a5f1
> ```

5.3.3
I use these docker images
```bash
docker pull ghcr.io/apache/shardingsphere-proxy:845d1007809d358965fc07fdbe451467eeb1f63e@sha256:3ae631cb87484e27c1255034ec0f228a1af4e613b526f6ad05c98c1123eda957

docker pull ghcr.io/apache/shardingsphere-proxy:7cc22179acab886cc9900954114cb3778d9cf701@sha256:55d115cde0b49c0366eea0fc5509e250b8c8af660dfd41580e71aee04a92a5f1
```

**Comment by liaojiexin** [comment]
> @liaojiexin Hi, Which one your use ShardingSphere version?

5.3.3
I use these docker images
```bash
docker pull ghcr.io/apache/shardingsphere-proxy:845d1007809d358965fc07fdbe451467eeb1f63e@sha256:3ae631cb87484e27c1255034ec0f228a1af4e613b526f6ad05c98c1123eda957

docker pull ghcr.io/apache/shardingsphere-proxy:7cc22179acab886cc9900954114cb3778d9cf701@sha256:55d115cde0b49c0366eea0fc5509e250b8c8af660dfd41580e71aee04a92a5f1
```

**Comment by 13145512239** [comment]
> > @liaojiexin Hi, Which one your use ShardingSphere version?
> 
> 5.3.3 I use these docker images
> 
> ```shell
> docker pull ghcr.io/apache/shardingsphere-proxy:845d1007809d358965fc07fdbe451467eeb1f63e@sha256:3ae631cb87484e27c1255034ec0f228a1af4e613b526f6ad05c98c1123eda957
> 
> docker pull ghcr.io/apache/shardingsphere-proxy:7cc22179acab886cc9900954114cb3778d9cf701@sha256:55d115cde0b49c0366eea0fc5509e250b8c8af660dfd41580e71aee04a92a5f1
> ```

Hi，I also meet this question, Have you solved it ?

**Comment by liaojiexin** [comment]
> 

no

**Comment by liaojiexin** [comment]
> > > @liaojiexin Hi, Which one your use ShardingSphere version?
> > 
> > 
> > 5.3.3 I use these docker images
> > ```shell
> > docker pull ghcr.io/apache/shardingsphere-proxy:845d1007809d358965fc07fdbe451467eeb1f63e@sha256:3ae631cb87484e27c1255034ec0f228a1af4e613b526f6ad05c98c1123eda957
> > 
> > docker pull ghcr.io/apache/shardingsphere-proxy:7cc22179acab886cc9900954114cb3778d9cf701@sha256:55d115cde0b49c0366eea0fc5509e250b8c8af660dfd41580e71aee04a92a5f1
> > ```
> 
> Hi，I also meet this question, Have you solved it ?

no

**Comment by Pace2Car** [comment]
This should have been resolved in https://github.com/apache/shardingsphere/pull/25482.

**Comment by liaojiexin** [comment]
> This should have been resolved in #25482.

ok，thank you
