### ISSUE TITLE
sqlserver -> Unknown exception: Index: 2, Size: 2

### ISSUE THREAD

**Issue by perfree** [apache/shardingsphere#25923]
SQL: SELECT id, ginseng, type, content, log_level, check_id, create_time FROM ws_log ORDER BY create_time DESC OFFSET ? ROWS FETCH NEXT ? ROWS ONLY
```
Cause: java.sql.SQLException: Unknown exception: Index: 2, Size: 2
; uncategorized SQLException; SQL state [HY000]; error code [30000]; Unknown exception: Index: 2, Size: 2; nested exception is java.sql.SQLException: Unknown exception: Index: 2, Size: 2
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:89)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:88)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
	at com.sun.proxy.$Proxy102.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:223)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForIPage(MybatisMapperMethod.java:122)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:87)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy168.selectPage(Unknown Source)
	at com.xwt.service.impl.LogServiceImpl.pageList(LogServiceImpl.java:53)
	at com.xwt.service.impl.LogServiceImpl$$FastClassBySpringCGLIB$$22fe6400.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at com.xwt.service.impl.LogServiceImpl$$EnhancerBySpringCGLIB$$f01d6aa0.pageList(<generated>)
	at com.xwt.service.impl.LogServiceImpl$$FastClassBySpringCGLIB$$22fe6400.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at com.xwt.service.impl.LogServiceImpl$$EnhancerBySpringCGLIB$$c3afe73e.pageList(<generated>)
	at com.xwt.controller.LogController.list(LogController.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.github.xiaoymin.swaggerbootstrapui.filter.SecurityBasicAuthFilter.doFilter(SecurityBasicAuthFilter.java:84)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.github.xiaoymin.swaggerbootstrapui.filter.ProductionSecurityFilter.doFilter(ProductionSecurityFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
```
yaml
```yaml
dataSources:
  workstation:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://153.153.234.148:1433;DatabaseName=workstation_xc;useUnicode=true;characterEncoding=gbk;characterSetResults=utf8;
    username: sa
    password: Xwt123..
    initial-size: 5
    max-active: 1000
    min-idle: 5
    max-wait: 60000
    validation-query: SELECT 1
rules:
  - !SHARDING
    tables:
      WS_LOG:
        actualDataNodes: workstation.WS_LOG_$->{1..3}
        tableStrategy:
          standard:
            shardingColumn: type
            shardingAlgorithmName: log_inline

    shardingAlgorithms:
      log_inline:
        type: INLINE
        props:
          algorithm-expression: WS_LOG_$->{type}
props:
  sql-show: true
```

**Comment by terrymanu** [comment]
##  Problem Understanding

  - On SQLServer via ShardingSphere-JDBC (Druid datasource, sharded tables WS_LOG_1..3 with INLINE on column type), executing SELECT ... ORDER BY create_time DESC OFFSET ? ROWS FETCH NEXT ? ROWS ONLY in MyBatis-Plus pagination throws Unknown exception: Index: 2, Size: 2
    (HY000/30000), occurring in the JDBC/MyBatis stack.

##  Root Cause

  - The error indicates a pagination parameter index out of bounds: trying to access a 3rd parameter (index 2) when only 2 parameters exist. The SQL has two ?, so ShardingSphere’s pagination parsing/rewriter derived or recognized a parameter index that doesn’t match the
    actual parameter list. This often happens in SQLServer OFFSET/FETCH parsing or cross-shard pagination when a derived bound (e.g., row_number upper limit) is misindexed.

##  Issue Analysis

  - For SQLServer cross-shard pagination, ShardingSphere computes row_number/top bounds; if FETCH NEXT ? or a derived bound is assigned index 2 while only indexes 0 and 1 exist, an IndexOutOfBoundsException occurs and is wrapped as Unknown exception.
  - The SQL omits the sharding key type, triggering full-shard routing with pagination merge, which depends on ShardingSphere’s pagination rewrite; an incorrect parameter index (labeled 2 with only two params passed) surfaces in full-routing scenarios.
  - Need to distinguish between a SQLServer dialect indexing bug and external parameter modification (e.g., MyBatis-Plus pagination plugin). Current data is insufficient for a definitive root cause.

##  Conclusion

  - Evidence points to a mismatch between pagination parameter indexing and the provided argument list, leading to out-of-bounds access. It’s unclear whether this is a ShardingSphere pagination parse/rewrite defect or external parameter misalignment. Please provide:
      1. ShardingSphere version and SQLServer JDBC driver version
      2. Routed SQL and parameter list with props.sql-show: true (including rewritten SQL)
      3. Full stack trace showing the innermost exception origin (e.g., PaginationContext/ParameterBuilder)
      4. MyBatis layer parameter order/count (logs or debug), and whether extra ? conditions exist
      5. Deployment topology (JDBC vs Proxy) and SQLServer version (OFFSET/FETCH support)
  - Meanwhile, to follow sharding best practices and reduce rewrite complexity, include the sharding key type in the WHERE clause, and compare single-shard vs multi-shard behavior.
