### ISSUE TITLE
Create partitioned tables SQL parse failed of openGauss

### ISSUE THREAD

**Issue by azexcy** [apache/shardingsphere#25990]
## Bug Report

When create partitioned tables just like

```
CREATE TABLE t_sales
(
    order_id     INTEGER  NOT NULL,
    goods_name   CHAR(20) NOT NULL,
    sales_date   DATE     NOT NULL,
    sales_volume INTEGER,
    sales_store  CHAR(20),
    PRIMARY KEY ( order_id )
) PARTITION BY RANGE (sales_date)(
PARTITION season1 VALUES LESS THAN('2023-04-01 00:00:00'),
PARTITION season2 VALUES LESS THAN('2023-07-01 00:00:00'),
PARTITION season3 VALUES LESS THAN('2023-10-01 00:00:00'),
PARTITION season4 VALUES LESS THAN(MAXVALUE));
```

it's can't parse correctly, will get the SQLParsingException.

```
org.apache.shardingsphere.sql.parser.exception.SQLParsingException: You have an error in your SQL syntax: CREATE TABLE t_sales
(
    order_id     INTEGER  NOT NULL,
    goods_name   CHAR(20) NOT NULL,
    sales_date   DATE     NOT NULL,
    sales_volume INTEGER,
    sales_store  CHAR(20),
    PRIMARY KEY ( order_id )
) PARTITION BY RANGE (sales_date)(
PARTITION season1 VALUES LESS THAN('2023-04-01 00:00:00'),
PARTITION season2 VALUES LESS THAN('2023-07-01 00:00:00'),
PARTITION season3 VALUES LESS THAN('2023-10-01 00:00:00'),
PARTITION season4 VALUES LESS THAN(MAXVALUE));, null

	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.twoPhaseParse(SQLParserExecutor.java:69)
	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.parse(SQLParserExecutor.java:48)
	at org.apache.shardingsphere.sql.parser.api.SQLParserEngine.parse(SQLParserEngine.java:47)
	at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserExecutor.parse(SQLStatementParserExecutor.java:46)
	at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserEngine.parse(SQLStatementParserEngine.java:47)
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine.parse(ShardingSphereSQLParserEngine.java:52)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.createQueryContext(ShardingSphereStatement.java:536)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.execute0(ShardingSphereStatement.java:465)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.execute(ShardingSphereStatement.java:413)
	at org.apache.shardingsphere.test.e2e.da
```

### Which version of ShardingSphere did you use?

master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Expected behavior

No exception 

### Actual behavior

Have excpetion

**Comment by cardigan1008** [comment]
Hi @azexcy , can I have a try?
