### ISSUE TITLE
mysql Single table SQL error "select *"

### ISSUE THREAD

**Issue by hua74ni** [apache/shardingsphere#26012]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

5.2.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior

Execute a single table SQL Select *, MySQL table dictionary (5 fields), table dictionary add a field (**such as test, 6 fields**), service restart execution dictionary select * or keep reporting errors, cannot be automatically repaired, I need to delete the zk node to not report an error.

### Actual behavior

service restart execution dictionary select * or keep reporting errors, cannot be automatically repaired, I need to delete the zk node to not report an error.

### Reason analyze (If you can)

The shardingsphere zk metadata table DDL is inconsistent with mysql and is not automatically updated 

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

**springboot 1.5.22 + JPA + mysql + 5.2.1 ShardingSphere-JDBC(mode: zookeeper cluster)**

Start with table  `dictionary` DDL:

```
CREATE TABLE `dictionary` (
  `id` char(36) NOT NULL COMMENT '主键id',
  `name` varchar(63) NOT NULL COMMENT 'canal服务节点名称',
  `code` varchar(63) NOT NULL COMMENT 'canal服务节点ip',
  `time_create` bigint(20) NOT NULL COMMENT '创建时间',
  `time_update` bigint(20) NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='字典表';
```

Start the service, Execute `dictionary` SQL: `select * from dictionary where id=:id`

The MySQL dictionary table has a new field `test`: `ALTER TABLE dictionary ADD test VARCHAR(36) DEFAULT 'abc123' AFTER time_create;`

changed `dictionary` DDL: 
```
CREATE TABLE `dictionary` (
  `id` char(36) NOT NULL COMMENT '主键id',
  `name` varchar(63) NOT NULL COMMENT 'canal服务节点名称',
  `code` varchar(63) NOT NULL COMMENT 'canal服务节点ip',
  `time_create` bigint(20) NOT NULL COMMENT '创建时间',
  `test` varchar(36) DEFAULT 'abc123',
  `time_update` bigint(20) NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='字典表';
```

Adjust the code and Restart the service, Execute `dictionary` SQL: `select * from dictionary where id=:id`

**Shardingsphere reported an error**:

```
Caused by: java.sql.SQLFeatureNotSupportedException: Can not get index from column label `test`.
	at org.apache.shardingsphere.driver.jdbc.core.resultset.ShardingSphereResultSet.lambda$getIndexFromColumnLabelAndIndexMap$0(ShardingSphereResultSet.java:393) ~[shardingsphere-jdbc-core-5.2.1.jar:5.2.1]
	at org.apache.shardingsphere.infra.util.exception.ShardingSpherePreconditions.checkState(ShardingSpherePreconditions.java:41) ~[shardingsphere-infra-util-5.2.1.jar:5.2.1]
	at org.apache.shardingsphere.driver.jdbc.core.resultset.ShardingSphereResultSet.getIndexFromColumnLabelAndIndexMap(ShardingSphereResultSet.java:393) ~[shardingsphere-jdbc-core-5.2.1.jar:5.2.1]
	at org.apache.shardingsphere.driver.jdbc.core.resultset.ShardingSphereResultSet.getString(ShardingSphereResultSet.java:165) ~[shardingsphere-jdbc-core-5.2.1.jar:5.2.1]
	at org.hibernate.type.descriptor.sql.VarcharTypeDescriptor$2.doExtract(VarcharTypeDescriptor.java:62) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:238) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:234) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:224) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.type.AbstractStandardBasicType.hydrate(AbstractStandardBasicType.java:300) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:2790) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.loader.Loader.loadFromResultSet(Loader.java:1729) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.loader.Loader.instanceNotYetLoaded(Loader.java:1655) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.loader.Loader.getRow(Loader.java:1544) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:727) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.loader.Loader.processResultSet(Loader.java:972) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.loader.Loader.doQuery(Loader.java:930) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:336) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.loader.Loader.doList(Loader.java:2617) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	... 156 common frames omitted
```

zk node info, path: `metadata/logic_db/schemas/logic_db/tables/dictionary`
```
columns:
  id:
    caseSensitive: false
    dataType: 1
    generated: false
    name: id
    primaryKey: true
    visible: true
  name:
    caseSensitive: false
    dataType: 12
    generated: false
    name: name
    primaryKey: false
    visible: true
  code:
    caseSensitive: false
    dataType: 12
    generated: false
    name: code
    primaryKey: false
    visible: true
  time_create:
    caseSensitive: false
    dataType: -5
    generated: false
    name: time_create
    primaryKey: false
    visible: true
  time_update:
    caseSensitive: false
    dataType: -5
    generated: false
    name: time_update
    primaryKey: false
    visible: true
indexes:
  primary:
    name: PRIMARY
name: dictionary
```

### Manual repair method
**I need to delete the zk node(metadata) to not report an error.**

### How to fix
The way I plan to fix it: When the instance starts, it will check whether the zk metadata table and the actual mysql table DDL are consistent, and whether the inconsistency is consistent or needs to be persisted

**Comment by RaigorJiang** [comment]
Hi @hua74ni 
Did you execute `ALTER TABLE` statement through ShardingSphere-JDBC?

**Comment by hua74ni** [comment]
> Hi @hua74ni Did you execute `ALTER TABLE` statement through ShardingSphere-JDBC?

Not executed through ShardingSphere-JDBC（Business projects do not execute `ALTER TABLE` normally）, Execute `ALTER TABLE` directly in MySQL, Then restart the service

**Comment by RaigorJiang** [comment]
Then this is the problem, ShardingSphere scans the metadata and persists it, but if you do not execute DDL through ShardingSphere, it means that you have not notified ShardingSphere to make changes.

If so, it is recommended to deploy a proxy to execute the DDL, or execute the REFRESH DistSQL through proxy.
If there is no Proxy, you can only delete the data in zk, but this may cause configuration loss, which is not recommended.

> > Hi @hua74ni Did you execute `ALTER TABLE` statement through ShardingSphere-JDBC?
> 
> Not executed through ShardingSphere-JDBC（Business projects do not execute `ALTER TABLE` normally）, Execute `ALTER TABLE` directly in MySQL, Then restart the service

**Comment by hua74ni** [comment]
> Then this is the problem, ShardingSphere scans the metadata and persists it, but if you do not execute DDL through ShardingSphere, it means that you have not notified ShardingSphere to make changes.
> 
> If so, it is recommended to deploy a proxy to execute the DDL, or execute the REFRESH DistSQL through proxy. If there is no Proxy, you can only delete the data in zk, but this may cause configuration loss, which is not recommended.
> 
> > > Hi @hua74ni Did you execute `ALTER TABLE` statement through ShardingSphere-JDBC?
> > 
> > 
> > Not executed through ShardingSphere-JDBC（Business projects do not execute `ALTER TABLE` normally）, Execute `ALTER TABLE` directly in MySQL, Then restart the service


All right, I think When the instance starts, it will check whether the zk metadata table and the actual mysql table DDL are consistent, and whether the inconsistency is consistent or needs to be persisted

**Comment by hua74ni** [comment]
> If the number of tables is large, the cost of comparison will be very high.
> 
> In addition, in this case, each instance will compare tables, which is obviously not cost-effective.
Simply compare the number of tables in the database and the number of fields in a table in memory (I understand that the consumption is quite small)

**Comment by RaigorJiang** [comment]
The columns of each table need to be queried separately, and ShardingSphere persists this information just to reduce the number of database query operations.

**Comment by hua74ni** [comment]
> The columns of each table need to be queried separately, and ShardingSphere persists this information just to reduce the number of database query operations.

all right.
