### ISSUE TITLE
Column index out of range occurs when I exeucte subquery with encrypt feature

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#26028]
### Which version of ShardingSphere did you use?

[f93b777](https://github.com/apache/shardingsphere/commit/f93b777b8efa134cf700c680031cca2c9313a150)

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Execute `SELECT * FROM (SELECT id, user_id, order_id, (SELECT password FROM t_user LIMIT 1) password FROM t_encrypt) temp;` successfully.

### Actual behavior

```
[ERROR] 2023-06-03 13:05:42.405 [Connection-1-ThreadExecutor] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
java.sql.SQLException: Column index out of range.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetMetaData.getField(ResultSetMetaData.java:395)
	at com.mysql.jdbc.ResultSetMetaData.getColumnName(ResultSetMetaData.java:243)
	at org.apache.shardingsphere.infra.executor.sql.execute.result.query.impl.driver.jdbc.metadata.JDBCQueryResultMetaData.getColumnName(JDBCQueryResultMetaData.java:47)
	at org.apache.shardingsphere.proxy.backend.response.header.query.QueryHeaderBuilderEngine.getColumnName(QueryHeaderBuilderEngine.java:79)
	at org.apache.shardingsphere.proxy.backend.response.header.query.QueryHeaderBuilderEngine.build(QueryHeaderBuilderEngine.java:67)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.createQueryHeader(DatabaseConnector.java:589)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.createQueryHeaders(DatabaseConnector.java:565)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.processExecuteQuery(DatabaseConnector.java:555)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.doExecute(DatabaseConnector.java:323)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.doExecute(DatabaseConnector.java:296)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.execute(DatabaseConnector.java:243)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:92)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.doExecuteCommand(CommandExecutorTask.java:114)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:109)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:77)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[INFO ] 2023-06-03 13:05:56.238 [Connection-1-ThreadExecutor] ShardingSphere-SQL - Logic SQL: SELECT * FROM (SELECT id, user_id, order_id, (SELECT password FROM t_user LIMIT 1) password FROM t_encrypt) temp
[INFO ] 2023-06-03 13:05:56.238 [Connection-1-ThreadExecutor] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT temp.`id`, temp.`user_cipher` AS `user_id`, temp.`order_cipher` AS `order_id` FROM (SELECT id, user_cipher, user_plain, order_cipher, (SELECT password FROM t_user LIMIT 1) password FROM t_encrypt) temp



[ERROR] 2023-06-03 13:12:24.560 [Connection-1-ThreadExecutor] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
java.sql.SQLException: Column index out of range.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetMetaData.getField(ResultSetMetaData.java:395)
	at com.mysql.jdbc.ResultSetMetaData.getColumnName(ResultSetMetaData.java:243)
	at org.apache.shardingsphere.infra.executor.sql.execute.result.query.impl.driver.jdbc.metadata.JDBCQueryResultMetaData.getColumnName(JDBCQueryResultMetaData.java:47)
	at org.apache.shardingsphere.proxy.backend.response.header.query.QueryHeaderBuilderEngine.getColumnName(QueryHeaderBuilderEngine.java:79)
	at org.apache.shardingsphere.proxy.backend.response.header.query.QueryHeaderBuilderEngine.build(QueryHeaderBuilderEngine.java:67)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.createQueryHeader(DatabaseConnector.java:589)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.createQueryHeaders(DatabaseConnector.java:565)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.processExecuteQuery(DatabaseConnector.java:555)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.doExecute(DatabaseConnector.java:323)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.doExecute(DatabaseConnector.java:296)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.execute(DatabaseConnector.java:243)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:92)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.doExecuteCommand(CommandExecutorTask.java:114)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:109)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:77)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[INFO ] 2023-06-03 13:12:36.620 [Connection-1-ThreadExecutor] ShardingSphere-SQL - Logic SQL: SELECT * FROM (SELECT id, user_id, order_id, (SELECT password FROM t_user LIMIT 1) password FROM t_encrypt) temp
[INFO ] 2023-06-03 13:12:36.620 [Connection-1-ThreadExecutor] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT temp.`id`, temp.`user_cipher` AS `user_id`, temp.`order_cipher` AS `order_id` FROM (SELECT id, user_cipher, user_plain, order_cipher, (SELECT password FROM t_user LIMIT 1) password FROM t_encrypt) temp
[ERROR] 2023-06-03 13:13:24.593 [Connection-1-ThreadExecutor] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
java.sql.SQLException: Column index out of range.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetMetaData.getField(ResultSetMetaData.java:395)
	at com.mysql.jdbc.ResultSetMetaData.getColumnName(ResultSetMetaData.java:243)
	at org.apache.shardingsphere.infra.executor.sql.execute.result.query.impl.driver.jdbc.metadata.JDBCQueryResultMetaData.getColumnName(JDBCQueryResultMetaData.java:47)
	at org.apache.shardingsphere.proxy.backend.response.header.query.QueryHeaderBuilderEngine.getColumnName(QueryHeaderBuilderEngine.java:79)
	at org.apache.shardingsphere.proxy.backend.response.header.query.QueryHeaderBuilderEngine.build(QueryHeaderBuilderEngine.java:67)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.createQueryHeader(DatabaseConnector.java:589)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.createQueryHeaders(DatabaseConnector.java:565)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.processExecuteQuery(DatabaseConnector.java:555)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.doExecute(DatabaseConnector.java:323)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.doExecute(DatabaseConnector.java:296)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.execute(DatabaseConnector.java:243)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:92)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.doExecuteCommand(CommandExecutorTask.java:114)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:109)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:77)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Reason analyze (If you can)

Wrong sql rewrite result:

```
[INFO ] 2023-06-03 13:05:56.238 [Connection-1-ThreadExecutor] ShardingSphere-SQL - Logic SQL: SELECT * FROM (SELECT id, user_id, order_id, (SELECT password FROM t_user LIMIT 1) password FROM t_encrypt) temp
[INFO ] 2023-06-03 13:05:56.238 [Connection-1-ThreadExecutor] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT temp.`id`, temp.`user_cipher` AS `user_id`, temp.`order_cipher` AS `order_id` FROM (SELECT id, user_cipher, user_plain, order_cipher, (SELECT password FROM t_user LIMIT 1) password FROM t_encrypt) temp
```

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

```
rules:
- !ENCRYPT
  encryptors:
    aes_encryptor:
      type: AES
      props:
        aes-key-value: 123456abc
    md5_encryptor:
      type: MD5
  tables:
    t_encrypt:
      columns:
        user_id:
          plainColumn: user_plain
          cipherColumn: user_cipher
          encryptorName: aes_encryptor
        order_id:
          cipherColumn: order_cipher
          encryptorName: md5_encryptor
    t_user:
      columns:
        user_name:
          plainColumn: user_name_plain
          cipherColumn: user_name_cipher
          encryptorName: aes_encryptor
```

And then execute following sql with proxy.

```
create table t_encrypt (id int primary key, user_id varchar(200),order_id varchar(200), name varchar(200));

insert into t_encrypt(id, user_id, order_id, name) values(1, "123", "234", "zhangsan"), (2, "222", "333", "lisi");

CREATE TABLE t_user (id INT PRIMARY KEY, user_name varchar(200) DEFAULT NULL, password varchar(200) DEFAULT NULL);

insert into t_user(id, user_name, password) values(1, 'zhangsan', 'sdasdas');
```

Then execute `SELECT * FROM (SELECT id, user_id, order_id, (SELECT password FROM t_user LIMIT 1) password FROM t_encrypt) temp;`

**Comment by strongduanmu** [comment]
Test result:

```
mysql> SELECT * FROM (SELECT id, user_id, order_id, (SELECT password FROM t_user LIMIT 1) FROM t_encrypt) temp;
+----+---------+----------------------------------+---------------------------------------+
| id | user_id | order_id                         | (SELECT password FROM t_user LIMIT 1) |
+----+---------+----------------------------------+---------------------------------------+
|  1 | 123     | 289dff07669d7a23de0ef88d2f7129e7 | sdasdas                               |
|  2 | 222     | 310dcbbf4cce62f762a2aaa148d556bd | sdasdas                               |
+----+---------+----------------------------------+---------------------------------------+
2 rows in set (1 min 42.43 sec)

mysql> SELECT * FROM (SELECT id, user_id, order_id, (SELECT password FROM t_user LIMIT 1) password FROM t_encrypt) temp; 
+----+---------+----------------------------------+----------+
| id | user_id | order_id                         | password |
+----+---------+----------------------------------+----------+
|  1 | 123     | 289dff07669d7a23de0ef88d2f7129e7 | sdasdas  |
|  2 | 222     | 310dcbbf4cce62f762a2aaa148d556bd | sdasdas  |
+----+---------+----------------------------------+----------+
2 rows in set (5.28 sec)
```

**Comment by strongduanmu** [comment]
When subquery contains encrypt column, and not config subquery alias, it will throw exception.

```
[INFO ] 2023-06-03 15:18:19.429 [Connection-1-ThreadExecutor] ShardingSphere-SQL - Logic SQL: SELECT * FROM (SELECT id, user_id, order_id, (SELECT user_name FROM t_user LIMIT 1) FROM t_encrypt) temp
[INFO ] 2023-06-03 15:18:19.430 [Connection-1-ThreadExecutor] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT temp.`id`, temp.`user_cipher` AS `user_id`, temp.`order_cipher` AS `order_id`, (SELECT user_name FROM t_user LIMIT 1) AS `(SELECT user_name FROM t_user LIMIT 1)` FROM (SELECT id, user_cipher, user_plain, order_cipher, (SELECT user_name_cipher AS user_name FROM t_user LIMIT 1) FROM t_encrypt) temp
```

**Comment by strongduanmu** [comment]
Fixed by https://github.com/apache/shardingsphere/pull/26104
