### ISSUE TITLE
DM databases   Error reporting NullPointerException

### ISSUE THREAD

**Issue by 18781720664** [apache/shardingsphere#26258]
Problems with using DM database data

ext-lib/
dm8-oracle-jdbc16-wrapper.jar    DmJdbcDriver17.jar               DmJdbcDriver18.jar               mysql-connector-java-8.0.22.jar  

schemaName: SYSDBA
dataSources:
ds_0:
url: jdbc:dm://172.16.106.36:5237?comOra=oracle
username: mydb1
password: a123456789
rules:

!SHARDING
tables:
t_user:
actualDataNodes: ds_0.testtables
tableStrategy:
standard:
shardingColumn: id
shardingAlgorithmName: alg_hash_mod
databaseStrategy:
standard:
shardingColumn: id
shardingAlgorithmName: alg_mod
keyGenerateStrategy:
column: id
keyGeneratorName: snowflake
bindingTables:
t_user
shardingAlgorithms:
alg_mod:
type: MOD
props:
sharding-count: 2
alg_hash_mod:
type: HASH_MOD
props:
sharding-count: 2
keyGenerators:
snowflake:
type: SNOWFLAKE

---
Using version 5.1.1 will result in   NullPointerException
---
---
Using version 53.2 will result in    Exception in thread "main" org.apache.shardingsphere.infra.util.spi.exception.ServiceProviderNotFoundServerException: SPI-00001: No implementation class load from SPI `org.apache.shardingsphere.transaction.xa.jta.datasource.properties.XADataSourceDefinition`.
---
 5.1.1：
 
03:25:07.581 [main] INFO com.atomikos.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.oltp_retry_interval = 10000
03:25:07.581 [main] INFO com.atomikos.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.force_shutdown_on_vm_exit = false
03:25:07.581 [main] INFO com.atomikos.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.default_jta_timeout = 300000
03:25:07.582 [main] INFO com.atomikos.icatch.provider.imp.AssemblerImp - Using default (local) logging and recovery...
03:25:07.585 [main] DEBUG com.atomikos.recovery.fs.FileSystemRepository - baseDir ./logs
03:25:07.585 [main] DEBUG com.atomikos.recovery.fs.FileSystemRepository - baseName xa_tx
03:25:07.586 [main] DEBUG com.atomikos.recovery.fs.FileSystemRepository - LogFileLock com.atomikos.persistence.imp.LogFileLock@7718a40f
Exception in thread "main" java.lang.NullPointerException
at org.apache.shardingsphere.transaction.xa.jta.datasource.swapper.DataSourceSwapper.createXADataSource(DataSourceSwapper.java:64)
at org.apache.shardingsphere.transaction.xa.jta.datasource.swapper.DataSourceSwapper.swap(DataSourceSwapper.java:56)
at org.apache.shardingsphere.transaction.xa.jta.datasource.XADataSourceFactory.build(XADataSourceFactory.java:43)
at org.apache.shardingsphere.transaction.xa.jta.datasource.XATransactionDataSource.(XATransactionDataSource.java:64)
at org.apache.shardingsphere.transaction.xa.XAShardingSphereTransactionManager.newXATransactionDataSource(XAShardingSphereTransactionManager.java:63)
at org.apache.shardingsphere.transaction.xa.XAShardingSphereTransactionManager.lambda$init$0(XAShardingSphereTransactionManager.java:57)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.apache.shardingsphere.transaction.xa.XAShardingSphereTransactionManager.init(XAShardingSphereTransactionManager.java:57)
at org.apache.shardingsphere.transaction.ShardingSphereTransactionManagerEngine.lambda$init$0(ShardingSphereTransactionManagerEngine.java:71)
at java.util.Map.forEach(Map.java:630)
at org.apache.shardingsphere.transaction.ShardingSphereTransactionManagerEngine.init(ShardingSphereTransactionManagerEngine.java:71)
at org.apache.shardingsphere.transaction.context.TransactionContextsBuilder.build(TransactionContextsBuilder.java:54)
at org.apache.shardingsphere.mode.manager.memory.MemoryContextManagerBuilder.build(MemoryContextManagerBuilder.java:61)
at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.createContextManager(BootstrapInitializer.java:72)
at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.init(BootstrapInitializer.java:57)
at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:47)

5.3.2:
- tips & advice 
- working demos 
- access to the full documentation 
- special exclusive bonus offers not available to others 
- everything you need to get the most out of using Atomikos!
Exception in thread "main" org.apache.shardingsphere.infra.util.spi.exception.ServiceProviderNotFoundServerException: SPI-00001: No implementation class load from SPI `org.apache.shardingsphere.transaction.xa.jta.datasource.properties.XADataSourceDefinition`.
        at org.apache.shardingsphere.infra.util.spi.type.typed.TypedSPILoader.lambda$getService$2(TypedSPILoader.java:126)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at org.apache.shardingsphere.infra.util.spi.type.typed.TypedSPILoader.lambda$getService$3(TypedSPILoader.java:126)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at org.apache.shardingsphere.infra.util.spi.type.typed.TypedSPILoader.getService(TypedSPILoader.java:126)
        at org.apache.shardingsphere.infra.util.spi.type.typed.TypedSPILoader.getService(TypedSPILoader.java:113)
        at org.apache.shardingsphere.transaction.xa.jta.datasource.XATransactionDataSource.<init>(XATransactionDataSource.java:68)
        at org.apache.shardingsphere.transaction.xa.XAShardingSphereTransactionManager.newXATransactionDataSource(XAShardingSphereTransactionManager.java:74)
        at org.apache.shardingsphere.transaction.xa.XAShardingSphereTransactionManager.lambda$init$0(XAShardingSphereTransactionManager.java:60)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at org.apache.shardingsphere.transaction.xa.XAShardingSphereTransactionManager.init(XAShardingSphereTransactionManager.java:60)
        at org.apache.shardingsphere.transaction.ShardingSphereTransactionManagerEngine.lambda$init$0(ShardingSphereTransactionManagerEngine.java:64)
        at java.base/java.util.Map.forEach(Map.java:713)
        at org.apache.shardingsphere.transaction.ShardingSphereTransactionManagerEngine.init(ShardingSphereTransactionManagerEngine.java:64)
        at org.apache.shardingsphere.transaction.rule.TransactionRule.createTransactionManagerEngine(TransactionRule.java:80)
        at org.apache.shardingsphere.transaction.rule.TransactionRule.<init>(TransactionRule.java:62)
        at org.apache.shardingsphere.transaction.rule.builder.TransactionRuleBuilder.build(TransactionRuleBuilder.java:36)
        at org.apache.shardingsphere.transaction.rule.builder.TransactionRuleBuilder.build(TransactionRuleBuilder.java:32)
        at org.apache.shardingsphere.infra.rule.builder.global.GlobalRulesBuilder.buildRules(GlobalRulesBuilder.java:54)
        at org.apache.shardingsphere.mode.metadata.MetaDataContextsFactory.create(MetaDataContextsFactory.java:93)
        at org.apache.shardingsphere.mode.metadata.MetaDataContextsFactory.create(MetaDataContextsFactory.java:68)
        at org.apache.shardingsphere.mode.manager.standalone.StandaloneContextManagerBuilder.build(StandaloneContextManagerBuilder.java:53)
        at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.createContextManager(BootstrapInitializer.java:69)
        at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.init(BootstrapInitializer.java:59)
        at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:54)

**Comment by TeslaCN** [comment]
Sorry, commercial closed-source database is unsupported by an open source project. You may submit a PR if you are interested in fixing this issue. Or you may seek commercial support from companies.

**Comment by terrymanu** [comment]
Only open source database will be supported, no plan to support DM database
