### ISSUE TITLE
求求了 救救孩子吧 sharding-proxy，出现NullPointerException

### ISSUE THREAD

**Issue by 18781720664** [apache/shardingsphere#26257]
为提高效率，提问时请提供以下信息，问题描述清晰可优先响应。
【DM版本】:DM8
【操作系统】：Docker
【问题描述】*：
sharding 的jdk 版本 openjdk version "1.8.0_312"
JDBC已经换成了DM的了 每个版本都试过
用mysql 驱动 报错是
Exception in thread "main" java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:dm://172.16.106.36:5236?compatibleMode=oracle
用dm的驱动会报错空指针 已经创建了模式和用户
这是配置文件
schemaName: SYSDBA
dataSources:
ds_0:
url: jdbc:dm://172.16.106.36:5237?comOra=oracle
username: mydb1
password: a123456789
rules:

!SHARDING
tables:
t_user:
actualDataNodes: ds_0.testtables
tableStrategy:
standard:
shardingColumn: id
shardingAlgorithmName: alg_hash_mod
databaseStrategy:
standard:
shardingColumn: id
shardingAlgorithmName: alg_mod
keyGenerateStrategy:
column: id
keyGeneratorName: snowflake
bindingTables:
t_user
shardingAlgorithms:
alg_mod:
type: MOD
props:
sharding-count: 2
alg_hash_mod:
type: HASH_MOD
props:
sharding-count: 2
keyGenerators:
snowflake:
type: SNOWFLAKE
报错如下
03:25:07.581 [main] INFO com.atomikos.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.oltp_retry_interval = 10000
03:25:07.581 [main] INFO com.atomikos.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.force_shutdown_on_vm_exit = false
03:25:07.581 [main] INFO com.atomikos.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.default_jta_timeout = 300000
03:25:07.582 [main] INFO com.atomikos.icatch.provider.imp.AssemblerImp - Using default (local) logging and recovery...
03:25:07.585 [main] DEBUG com.atomikos.recovery.fs.FileSystemRepository - baseDir ./logs
03:25:07.585 [main] DEBUG com.atomikos.recovery.fs.FileSystemRepository - baseName xa_tx
03:25:07.586 [main] DEBUG com.atomikos.recovery.fs.FileSystemRepository - LogFileLock com.atomikos.persistence.imp.LogFileLock@7718a40f
Exception in thread "main" java.lang.NullPointerException
at org.apache.shardingsphere.transaction.xa.jta.datasource.swapper.DataSourceSwapper.createXADataSource(DataSourceSwapper.java:64)
at org.apache.shardingsphere.transaction.xa.jta.datasource.swapper.DataSourceSwapper.swap(DataSourceSwapper.java:56)
at org.apache.shardingsphere.transaction.xa.jta.datasource.XADataSourceFactory.build(XADataSourceFactory.java:43)
at org.apache.shardingsphere.transaction.xa.jta.datasource.XATransactionDataSource.<init>(XATransactionDataSource.java:64)
at org.apache.shardingsphere.transaction.xa.XAShardingSphereTransactionManager.newXATransactionDataSource(XAShardingSphereTransactionManager.java:63)
at org.apache.shardingsphere.transaction.xa.XAShardingSphereTransactionManager.lambda$init$0(XAShardingSphereTransactionManager.java:57)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.apache.shardingsphere.transaction.xa.XAShardingSphereTransactionManager.init(XAShardingSphereTransactionManager.java:57)
at org.apache.shardingsphere.transaction.ShardingSphereTransactionManagerEngine.lambda$init$0(ShardingSphereTransactionManagerEngine.java:71)
at java.util.Map.forEach(Map.java:630)
at org.apache.shardingsphere.transaction.ShardingSphereTransactionManagerEngine.init(ShardingSphereTransactionManagerEngine.java:71)
at org.apache.shardingsphere.transaction.context.TransactionContextsBuilder.build(TransactionContextsBuilder.java:54)
at org.apache.shardingsphere.mode.manager.memory.MemoryContextManagerBuilder.build(MemoryContextManagerBuilder.java:61)
at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.createContextManager(BootstrapInitializer.java:72)
at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.init(BootstrapInitializer.java:57)
at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:47)

**Comment by TeslaCN** [comment]
Duplicate with #26258.
