### ISSUE TITLE
Cannot invoke "String.toLowerCase()" because "databaseName" is null

### ISSUE THREAD

**Issue by zuohl** [apache/shardingsphere#26420]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.3.3-SNAPSHOT
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-Proxy
### Expected behavior

SHOW VARIABLES LIKE 'lower_case_%';
![image](https://github.com/apache/shardingsphere/assets/10548200/29270d17-7222-47a5-8242-eb7efd6f524b)

### Actual behavior
[ERROR] 2023-06-18 22:14:38.777 [ShardingSphere-Command-4] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "databaseName" is null
	at org.apache.shardingsphere.infra.metadata.ShardingSphereMetaData.getDatabase(ShardingSphereMetaData.java:91)
	at org.apache.shardingsphere.proxy.backend.handler.ProxyBackendHandlerFactory.newInstance(ProxyBackendHandlerFactory.java:163)
	at org.apache.shardingsphere.proxy.backend.handler.ProxyBackendHandlerFactory.newInstance(ProxyBackendHandlerFactory.java:112)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.<init>(MySQLComQueryPacketExecutor.java:70)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecutorFactory.newInstance(MySQLCommandExecutorFactory.java:84)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandExecutor(MySQLCommandExecuteEngine.java:63)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:120)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:78)
	at com.alibaba.ttl.TtlRunnable.run(TtlRunnable.java:60)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
![sharding](https://github.com/apache/shardingsphere/assets/10548200/a3c6aba1-2a68-4625-bae7-f4f2270ecf9c)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
SHOW VARIABLES LIKE 'lower_case_%';

**Comment by zuohl** [comment]
I'm getting this error because I'm using navicat to connect to the database

**Comment by RaigorJiang** [comment]
Hi  @zuohl 
Thanks for your feedback, and what is the SQL received by the Proxy when an exception occurs?
