### ISSUE TITLE
Shardingsphere proxy throws exception for class cast

### ISSUE THREAD

**Issue by xqianwang** [apache/shardingsphere#26765]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.3.2
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
Application starts successfully
### Actual behavior
 Unknown exception: class org.apache.shardingsphere.sql.parser.sql.common.segment.dml.item.AggregationProjectionSegment cannot be cast to class org.apache.shardingsphere.sql.parser.sql.common.segment.dml.item.ColumnProjectionSegment (org.apache.shardingsphere.sql.parser.sql.common.segment.dml.item.AggregationProjectionSegment and org.apache.shardingsphere.sql.parser.sql.common.segment.dml.item.ColumnProjectionSegment are in unnamed module of loader 'app')
### Reason analyze (If you can)
[ERROR] 2023-07-04 21:05:19.819 [ShardingSphere-Command-22] o.a.s.p.f.c.CommandExecutorTask - Exception occur:
java.lang.ClassCastException: class org.apache.shardingsphere.sql.parser.sql.common.segment.dml.item.AggregationProjectionSegment cannot be cast to class org.apache.shardingsphere.sql.parser.sql.common.segment.dml.item.ColumnProjectionSegment (org.apache.shardingsphere.sql.parser.sql.common.segment.dml.item.AggregationProjectionSegment and org.apache.shardingsphere.sql.parser.sql.common.segment.dml.item.ColumnProjectionSegment are in unnamed module of loader 'app')
	at org.apache.shardingsphere.proxy.backend.mysql.handler.admin.executor.information.SelectInformationSchemataExecutor.lambda$getTheDefaultRowData$11(SelectInformationSchemataExecutor.java:128)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.apache.shardingsphere.proxy.backend.mysql.handler.admin.executor.information.SelectInformationSchemataExecutor.getTheDefaultRowData(SelectInformationSchemataExecutor.java:128)
	at org.apache.shardingsphere.proxy.backend.mysql.handler.admin.executor.information.SelectInformationSchemataExecutor.fillSchemasWithoutDataSource(SelectInformationSchemataExecutor.java:113)
	at org.apache.shardingsphere.proxy.backend.mysql.handler.admin.executor.information.SelectInformationSchemataExecutor.getDatabaseNames(SelectInformationSchemataExecutor.java:90)
	at org.apache.shardingsphere.proxy.backend.handler.admin.executor.AbstractDatabaseMetaDataExecutor.execute(AbstractDatabaseMetaDataExecutor.java:74)
	at org.apache.shardingsphere.proxy.backend.handler.admin.DatabaseAdminQueryBackendHandler.execute(DatabaseAdminQueryBackendHandler.java:56)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:92)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.doExecuteCommand(CommandExecutorTask.java:114)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:109)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:77)
	at com.alibaba.ttl.TtlRunnable.run(TtlRunnable.java:60)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Try use flywaydb run db migrations.

**Comment by sandynz** [comment]
Hi @xqianwang , could you try latest version? If there's still error, could you help to get which SQL cause the error? Thanks.
