### ISSUE TITLE
NullPointerException caused by Non Compatible DataSource type

### ISSUE THREAD

**Issue by theodoretsai** [apache/shardingsphere#26805]
## Bug Report

NullPointerException caused by Non Compatible DataSource type.

I don't know if this reallty qualifies as a bug report or is a designed limitation of ShardingSphere, when using custom implementations of DataSource the framework might not correctly obtain metadata and cause NullPointerException.

### Which version of ShardingSphere did you use?

5.3.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Expected behavior

Create DataSource successfully

### Actual behavior

NullPointerException when trying to obtain ResourceMetaData at `ShardingSphereResourceMetaData.java:71`

### Reason analyze (If you can)
StackTrace
```
java.lang.NullPointerException: null
	at org.apache.shardingsphere.infra.metadata.database.resource.ShardingSphereResourceMetaData.createDataSourceMetaDataMap(ShardingSphereResourceMetaData.java:71)
	at org.apache.shardingsphere.infra.metadata.database.resource.ShardingSphereResourceMetaData.<init>(ShardingSphereResourceMetaData.java:55)
...
```
Database properties are obtained using reflection in `DataSourcePropertiesCreator.java`

```
    private static Map<String, Object> createProperties(final DataSource dataSource) {
        Map<String, Object> result = new LinkedHashMap<>();
        Optional<DataSourcePoolMetaData> poolMetaData = TypedSPIRegistry.findRegisteredService(DataSourcePoolMetaData.class, dataSource.getClass().getName());
        for (Entry<String, Object> entry : new DataSourceReflection(dataSource).convertToProperties().entrySet()) {
            String propertyName = entry.getKey();
            Object propertyValue = entry.getValue();
            if (!poolMetaData.isPresent() || isValidProperty(propertyName, propertyValue, poolMetaData.get()) && !poolMetaData.get().getTransientFieldNames().contains(propertyName)) {
                result.put(propertyName, propertyValue);
            }
        }
        return result;
    }
```

Getters are scanned and converted to properties.
From what I understand: for different implementations of DataSource a `DataSourcePoolMetaData` can be implemented for the DataSource Type and synonyms of fields can be provided in case there are no getters with standard names.

The Reflection implementation of finding properties doesn't account for DataSource implementation that can't directly obtain username and url via getters, resulting in NullpointerException at ShardingSphereResourceMetaData.java:71:

```
    private Map<String, DataSourceMetaData> createDataSourceMetaDataMap(final Map<String, DataSource> dataSources, final Map<String, DatabaseType> storageTypes) {
        Map<String, DataSourceMetaData> result = new LinkedHashMap<>(dataSources.size(), 1);
        for (Entry<String, DataSource> entry : dataSources.entrySet()) {
            Map<String, Object> standardProps = DataSourcePropertiesCreator.create(entry.getValue()).getConnectionPropertySynonyms().getStandardProperties();
            DatabaseType storageType = storageTypes.get(entry.getKey());
>>>>            result.put(entry.getKey(), storageType.getDataSourceMetaData(standardProps.get("url").toString(), standardProps.get("username").toString()));      
        }
        return result;
    }
```

To avoid this problem the solution I've found now is to wrap my DataSource with class that gives the DatabaseReflection some getters to Scan:
```
public class MyWorkaroudDataSource extends DynamicDataSource {

    // .... implementations

    @SuppressWarnings({"unused"})
    //used by ShardingSphere reflection to build metadata
    public String getUsername() {
        // implementation
    }

    @SuppressWarnings("unused")
    public String getUrl() {
    //used by ShardingSphere reflection to build metadata
        // implementation
    }
}
```
But is quite ugly.

Is there actually a correct way to do this that I've missed? 
Also what is the reason the url and username must be obtained in this way? Couldn't they be obtained from .getConnection().getMetaData() without resorting to reflection?

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

Wrap a DataSource Object with another DataSourceClass that doesn't have any getters for the DatabaseReflection to scan such as:

```
public class HiddenGettersDataSource implements DataSource {

    private final DataSource dataSource;

    public HiddenGettersDataSource (DataSource source) {
        this.dataSource = source;
    }

    @Override
    public Connection getConnection() throws SQLException {
        Connection connection = dataSource.getConnection();
        return connection;
    }

    @Override
    public Connection getConnection(String username, String password) throws SQLException {
        Connection connection = dataSource.getConnection(username, password);
        return connection;
    }

    @Override
    public PrintWriter getLogWriter() throws SQLException {
        return dataSource.getLogWriter();
    }

    @Override
    public void setLogWriter(PrintWriter out) throws SQLException {
        dataSource.setLogWriter(out);
    }

    @Override
    public void setLoginTimeout(int seconds) throws SQLException {
        dataSource.setLoginTimeout(seconds);
    }

    @Override
    public int getLoginTimeout() throws SQLException {
        return dataSource.getLoginTimeout();
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        return dataSource.unwrap(iface);
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return dataSource.isWrapperFor(iface);
    }

    @Override
    public Logger getParentLogger() throws SQLFeatureNotSupportedException {
        return dataSource.getParentLogger();
    }
}
```

### Example codes for reproduce this issue (such as a github link).

Sorry I can't provide code but should be clear enough from the description.

Thank you.

**Comment by terrymanu** [comment]
##  Problem Understanding
  You’re on 5.3.1 with ShardingSphere-JDBC, using a custom/wrapped DataSource that hides url/username getters. At startup, resource metadata construction throws an NPE, and you’re asking if there’s a correct way to avoid the reflection dependency.

##  Root Cause
  ShardingSphere gathers standard connection properties (url, username, etc.) via DataSourcePropertiesCreator/DataSourcePoolReflection or via a DataSourcePoolMetaData SPI mapping for that DataSource type. This avoids opening real connections during startup while still
  detecting database type/instance for routing checks. Your custom wrapper exposes neither standard getters nor a DataSourcePoolMetaData SPI, so standardProps.get("url")/get("username") are null and toString() causes the NPE. This is an unsupported custom DataSource usage
  rather than a generic framework bug.

##  Analysis

  - The design explicitly avoids getConnection().getMetaData() to prevent real connections at startup (some pools disallow it or it’s too costly) and keeps metadata acquisition in SPI/reflection.
  - Built-in pools (e.g., HikariCP) ship with DataSourcePoolMetaData so url/username are known. Custom or wrapped DataSources must supply that layer themselves.
  - Your current workaround (adding getUrl()/getUsername() getters on the wrapper) works because it supplies the missing metadata access points; the more standard approach is to implement the SPI.

##  Conclusion
  This is caused by a custom DataSource that hasn’t been adapted per ShardingSphere’s expectations, not a general bug.
