### ISSUE TITLE
Shardingsphere-Proxy failed to execute sql query for getting table and creating table if not exists.

### ISSUE THREAD

**Issue by xqianwang** [apache/shardingsphere#26893]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.3.2
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
Shardingsphere should be able to handle below query
`SELECT
    TABLE_SCHEMA AS TABLE_CAT,
    NULL AS TABLE_SCHEM,
    TABLE_NAME,
    CASE
        WHEN TABLE_TYPE = 'BASE TABLE' THEN
            CASE
                WHEN TABLE_SCHEMA = 'mysql' OR TABLE_SCHEMA = 'performance_schema' THEN 'SYSTEM TABLE'
                ELSE 'TABLE'
            END
        WHEN TABLE_TYPE = 'TEMPORARY' THEN 'LOCAL_TEMPORARY'
        ELSE TABLE_TYPE
    END AS TABLE_TYPE,
    TABLE_COMMENT AS REMARKS,
    NULL AS TYPE_CAT,
    NULL AS TYPE_SCHEM,
    NULL AS TYPE_NAME,
    NULL AS SELF_REFERENCING_COL_NAME,
    NULL AS REF_GENERATION
FROM
    INFORMATION_SCHEMA.TABLES
WHERE
    TABLE_SCHEMA = 'credentialing'
    AND TABLE_NAME LIKE 'CREDENTIALING_CHANGE_LOG'
HAVING
    TABLE_TYPE IN ('TABLE', NULL, NULL, NULL, NULL)
ORDER BY
    TABLE_TYPE, TABLE_SCHEMA, TABLE_NAME;`
### Actual behavior
Throws error:
`Caused by: java.sql.SQLException: Unknown exception: At line 0, column 0: Expression 'TABLE_TYPE' is not being grouped
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:970)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1020)
	at com.mysql.cj.jdbc.DatabaseMetaDataUsingInfoSchema.executeMetadataQuery(DatabaseMetaDataUsingInfoSchema.java:70)
	at com.mysql.cj.jdbc.DatabaseMetaDataUsingInfoSchema.getTables(DatabaseMetaDataUsingInfoSchema.java:847)
	at org.hibernate.tool.schema.extract.internal.InformationExtractorJdbcDatabaseMetaDataImpl.getTables(InformationExtractorJdbcDatabaseMetaDataImpl.java:329)`
### Reason analyze (If you can)
not sure

**Comment by terrymanu** [comment]
This exception is thrown from MySQL driver, please check your SQL

**Comment by terrymanu** [comment]
What is your configuration?
