### ISSUE TITLE
javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.

### ISSUE THREAD

**Issue by KouShenhai** [apache/shardingsphere#26896]
## Bug Report

```java  
javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:278)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:421)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:721)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:662)
	at org.apache.shardingsphere.mode.repository.standalone.jdbc.sql.JDBCRepositorySQLLoader.loadFromJar(JDBCRepositorySQLLoader.java:114)
	at org.apache.shardingsphere.mode.repository.standalone.jdbc.sql.JDBCRepositorySQLLoader.load(JDBCRepositorySQLLoader.java:72)
	at org.apache.shardingsphere.mode.repository.standalone.jdbc.JDBCRepository.init(JDBCRepository.java:59)
	at org.apache.shardingsphere.infra.util.spi.type.typed.TypedSPILoader.findService(TypedSPILoader.java:86)
	at org.apache.shardingsphere.infra.util.spi.type.typed.TypedSPILoader.findService(TypedSPILoader.java:70)
	at org.apache.shardingsphere.infra.util.spi.type.typed.TypedSPILoader.getService(TypedSPILoader.java:127) 

Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)

```

### Which version of ShardingSphere did you use?
ShardingSphere 5.4.0 + JDK 17

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

**Comment by xiaogang-github** [comment]
我也出现了这个问题，请问你是怎么处理的

**Comment by linghengqian** [comment]
- Can you provide an example?

- One issue that must be noted is that JDK 9 starts removing `java.xml.bind` packages. For JAXB's API, you can use glassfish or a third-party vendor's javax implementation of JAXB. I'm assuming you're using Maven, which is adding a specific version of the dependency to `pom.xml`.
```xml
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-runtime</artifactId>
    <version>2.3.8</version>
</dependency>
```
- Refer to  https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-with-Java-9-and-above#jaxb and https://github.com/ehcache/ehcache3/blob/v3.10.8/docs/src/docs/asciidoc/user/getting-started.adoc .
- `org.glassfish.jaxb:jaxb-runtime:3.0.0` starts with the jakarta namespace. Switching to a later version of the JAXB API is being discussed in https://github.com/apache/shardingsphere/issues/26041#issuecomment-1581880874.

**Comment by KouShenhai** [comment]
> * Can you provide an example?
> * One issue that must be noted is that JDK 9 starts removing `java.xml.bind` packages. For JAXB's API, you can use glassfish or a third-party vendor's javax implementation of JAXB. I'm assuming you're using Maven, which is adding a specific version of the dependency to `pom.xml`.
> 
> ```
> <dependency>
>     <groupId>org.glassfish.jaxb</groupId>
>     <artifactId>jaxb-runtime</artifactId>
>     <version>2.3.8</version>
> </dependency>
> ```
> 
> * Refer to  https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-with-Java-9-and-above#jaxb and https://github.com/ehcache/ehcache3/blob/v3.10.8/docs/src/docs/asciidoc/user/getting-started.adoc .
> * `org.glassfish.jaxb:jaxb-runtime:3.0.0` starts with the jakarta namespace. Switching to a later version of the JAXB API is being discussed in [Transition from Java EE to Jakarta EE #26041 (comment)](https://github.com/apache/shardingsphere/issues/26041#issuecomment-1581880874).

Thank you very much for answering my question. The following dependencies have been introduced, but an error has been reported. It may be due to a higher version of JDK, but I hope the official website can quickly transition to Jakarta EE

``` xml
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-runtime</artifactId>
    <version>2.3.8</version>
</dependency>
```

**Comment by KouShenhai** [comment]
> 我也出现了这个问题，请问你是怎么处理的

只能等官网过渡到Jakarta EE

**Comment by RaigorJiang** [comment]
Duplecated with #26041.

**Comment by linghengqian** [comment]
- @KouShenhai So I confirmed in #29211 that Spring Boot 2.2+ is excluding most javax dependencies via the enforcer plugin. Similar configurations are making a bigger impact on Spring Boot 3.0+.

**Comment by crazythinking** [comment]
If the Java API is used for manual configuration, can this problem be temporarily bypassed?

**Comment by linghengqian** [comment]
> If the Java API is used for manual configuration, can this problem be temporarily bypassed?

The current problem does not exist in the latest version of shardingsphere, because shardingsphere currently uses the jackson xml module to parse xml instead of JAXB.
