### ISSUE TITLE
oracle:  TableMetaDataLoaderEngine : Dialect load table meta data error

### ISSUE THREAD

**Issue by jianyuePro** [apache/shardingsphere#27224]
## maven
`

        
                <dependency>
                    <groupId>com.oracle.database.jdbc</groupId>
                    <artifactId>ojdbc8</artifactId>
                    <version>19.6.0.0</version>
                </dependency>
        
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.1.0</version>
        </dependency>

        
        <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-dbcp</artifactId>
            <version>10.0.16</version>
        </dependency>
`

## exception

`
2023-07-15 18:30:13.803 ERROR 2076 --- [           main] .a.s.i.m.s.b.l.TableMetaDataLoaderEngine : Dialect load table meta data error

org.apache.shardingsphere.infra.exception.ShardingSphereException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at org.apache.shardingsphere.infra.metadata.schema.builder.loader.TableMetaDataLoaderEngine.loadByDialect(TableMetaDataLoaderEngine.java:98) ~[shardingsphere-infra-common-5.1.0.jar:5.1.0]
	at org.apache.shardingsphere.infra.metadata.schema.builder.loader.TableMetaDataLoaderEngine.load(TableMetaDataLoaderEngine.java:65) ~[shardingsphere-infra-common-5.1.0.jar:5.1.0]
	at org.apache.shardingsphere.singletable.metadata.SingleTableMetaDataBuilder.load(SingleTableMetaDataBuilder.java:56) [shardingsphere-single-table-core-5.1.0.jar:5.1.0]
	at org.apache.shardingsphere.singletable.metadata.SingleTableMetaDataBuilder.load(SingleTableMetaDataBuilder.java:43) [shardingsphere-single-table-core-5.1.0.jar:5.1.0]
	at org.apache.shardingsphere.infra.metadata.schema.builder.TableMetaDataBuilder.load(TableMetaDataBuilder.java:64) [shardingsphere-infra-common-5.1.0.jar:5.1.0]
	at org.apache.shardingsphere.infra.metadata.schema.loader.SchemaLoader.load(SchemaLoader.java:53) [shardingsphere-infra-common-5.1.0.jar:5.1.0]
	at org.apache.shardingsphere.mode.metadata.MetaDataContextsBuilder.addSchema(MetaDataContextsBuilder.java:78) [shardingsphere-mode-core-5.1.0.jar:5.1.0]
	at org.apache.shardingsphere.mode.manager.ContextManager.buildChangedMetaDataContext(ContextManager.java:446) [shardingsphere-mode-core-5.1.0.jar:5.1.0]
	at org.apache.shardingsphere.mode.manager.ContextManager.alterRuleConfiguration(ContextManager.java:259) [shardingsphere-mode-core-5.1.0.jar:5.1.0]
`

**Comment by strongduanmu** [comment]
Hi @jianyuePro can you try the latest 5.4.0?

**Comment by jianyuePro** [comment]
> Hi @jianyuePro can you try the latest 5.4.0?

OK, thank you
