### ISSUE TITLE
The service starts the error when upgrade snakeyaml to version 2.0

### ISSUE THREAD

**Issue by hanyongchao007** [apache/shardingsphere#27370]
Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method <init>()V not found
	at org.apache.shardingsphere.underlying.common.yaml.representer.DefaultYamlRepresenter.<init>(DefaultYamlRepresenter.java:33) ~[shardingsphere-common-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.underlying.common.yaml.engine.YamlEngine.marshal(YamlEngine.java:170) ~[shardingsphere-common-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.core.log.ConfigurationLogger.log(ConfigurationLogger.java:65) ~[sharding-core-common-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.core.log.ConfigurationLogger.log(ConfigurationLogger.java:54) ~[sharding-core-common-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.context.AbstractRuntimeContext.<init>(AbstractRuntimeContext.java:58) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.context.MultipleDataSourcesRuntimeContext.<init>(MultipleDataSourcesRuntimeContext.java:50) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.context.ShardingRuntimeContext.<init>(ShardingRuntimeContext.java:49) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.datasource.ShardingDataSource.<init>(ShardingDataSource.java:54) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.api.ShardingDataSourceFactory.createDataSource(ShardingDataSourceFactory.java:48) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]

**Comment by linghengqian** [comment]
- Duplicate with https://github.com/apache/shardingsphere/issues/21476. 
- This actually needs to wait for the merge of https://github.com/apache/shardingsphere-elasticjob/pull/2216 . @TeslaCN Should https://github.com/apache/shardingsphere-elasticjob/pull/2216 be merged in the next ElasticJob release?

**Comment by hanyongchao007** [comment]
这个问题什么时候可以解决呢，比较着急

**Comment by Pinkman-oss** [comment]
Have you solved your problem?

**Comment by linghengqian** [comment]
> Have you solved your problem?

- @Pinkman-oss This first requires `ElasticJob` to initiate and vote on Release `3.0.4` on the mailing list, then update `ElasticJob` in the master branch of `ShardingSphere` and complete the Release of `ShardingSphere 5.4.1`. Given the breaking changes in `SnakeYAML 2.0`, this is not possible with the current `ShardingSphere 5.4.0`.

- If you have a need, you can go to the mailing list and ask if the community agrees to vote on the release of `ElasticJob 3.0.4` in the near future.

**Comment by shardcn** [comment]
you may write issues of version 4.1.1 here :https://gitee.com/shardcn/shardingsphere_4.1.1
