### ISSUE TITLE
I used proxy@5.4.0 startup faild

### ISSUE THREAD

**Issue by lifejwang11** [apache/shardingsphere#27431]
### Which version of ShardingSphere did you use?
5.4.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
i use [**examples/shardingsphere-proxy-example/shardingsphere-proxy-boot-mybatis-example/src/mian/resources/conf/***.yaml**](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-proxy-example/shardingsphere-proxy-boot-mybatis-example/src/main/resources/conf)
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
i copy **conf** to **sharding-proxy/config**,i start by **/bin/start.sh**

```
Exception in thread "main" Cannot create property=rules for JavaBean=org.apache.shardingsphere.proxy.backend.config.yaml.YamlProxyDatabaseConfiguration@212bf671
 in 'reader', line 113, column 1:
    databaseName: sharding_db
No single argument constructor found for interface org.apache.shardingsphere.infra.yaml.config.pojo.rule.YamlRuleConfiguration
 in 'reader', line 136, column 2:
     tables:
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:321)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:207)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:358)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:270)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:253)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:207)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:191)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:477)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:443)
	at org.apache.shardingsphere.infra.util.yaml.YamlEngine.unmarshal(YamlEngine.java:54)
	at org.apache.shardingsphere.proxy.backend.config.ProxyConfigurationLoader.loadDatabaseConfiguration(ProxyConfigurationLoader.java:127)
	at org.apache.shardingsphere.proxy.backend.config.ProxyConfigurationLoader.loadDatabaseConfigurations(ProxyConfigurationLoader.java:118)
	at org.apache.shardingsphere.proxy.backend.config.ProxyConfigurationLoader.load(ProxyConfigurationLoader.java:68)
	at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:52)
Caused by: org.yaml.snakeyaml.error.YAMLException: No single argument constructor found for interface org.apache.shardingsphere.infra.yaml.config.pojo.rule.YamlRuleConfiguration
	at org.yaml.snakeyaml.constructor.Constructor$ConstructScalar.construct(Constructor.java:417)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:270)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:253)
	at org.yaml.snakeyaml.constructor.SafeConstructor.processDuplicateKeys(SafeConstructor.java:108)
	at org.yaml.snakeyaml.constructor.SafeConstructor.flattenMapping(SafeConstructor.java:81)
	at org.yaml.snakeyaml.constructor.SafeConstructor.flattenMapping(SafeConstructor.java:76)
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructSet2ndStep(SafeConstructor.java:218)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructSet(BaseConstructor.java:545)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:199)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:270)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:253)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.newInstance(Constructor.java:333)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:298)
	... 13 more
```
### Example codes for reproduce this issue (such as a github link)
[conf](https://github.com/lifejwang11/shardingproxy-issuse)

**Comment by zhaojinchao95** [comment]
Plase ref #23796

**Comment by lifejwang11** [comment]
> Plase ref #23796

i see the question is a `snakeyaml` version, but my `snaleyaml` is correct.  so i think is not this question. @zhaojinchao95

**Comment by lifejwang11** [comment]
the issuse is odd,I take time to compile the soure code(5.4.0),but it is natural,so i copy `conf` to `the issuse conf`,it is run.

**Comment by lifejwang11** [comment]
the issuse is odd, my issuse is resolve
