### ISSUE TITLE
commons-dbcp连接池没法在5.3.1上运行，没法兼容sharding的包 #27496

### ISSUE THREAD

**Issue by heimao** [apache/shardingsphere#27497]
shariding版本是5.3.1，因为要集成到之前项目，之前项目连接池是org.apache.commons.dbcp.basicdatasource,(本地commons-dbpc版本是1.4),所以沿用这个，sharding文档也说支持的，但是一直报错，换成com.zaxxer.hikari.HikariDataSource 这个数据源就好了，是不支持还是bug？ 报错的堆栈如下：
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'createDataSourceRetailc' threw exception; nested exception is java.lang.AbstractMethodError: org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.getSchema()Ljava/lang/String;
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.2.0.RELEASE.jar:4.2.0.RELEASE]
at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.2.0.RELEASE.jar:4.2.0.RELEASE]
... 37 common frames omitted
Caused by: java.lang.AbstractMethodError: org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.getSchema()Ljava/lang/String;
at org.apache.shardingsphere.infra.database.type.DatabaseType.getSchema(DatabaseType.java:92) ~[shardingsphere-infra-common-5.3.1.jar:5.3.1]
at org.apache.shardingsphere.infra.metadata.database.schema.loader.adapter.MetaDataLoaderConnectionAdapter.getSchema(MetaDataLoaderConnectionAdapter.java:69) ~[shardingsphere-infra-common-5.3.1.jar:5.3.1]
at org.apache.shardingsphere.infra.metadata.database.schema.loader.common.SchemaMetaDataLoader.loadSchemaNames(SchemaMetaDataLoader.java:82) ~[shardingsphere-infra-common-5.3.1.jar:5.3.1]
at org.apache.shardingsphere.infra.metadata.database.schema.loader.common.SchemaMetaDataLoader.loadSchemaTableNames(SchemaMetaDataLoader.java:62) ~[shardingsphere-infra-common-5.3.1.jar:5.3.1]
at org.apache.shardingsphere.single.datanode.SingleTableDataNodeLoader.loadSchemaTableNames(SingleTableDataNodeLoader.java:88) ~[shardingsphere-single-core-5.3.1.jar:5.3.1]
at org.apache.shardingsphere.single.datanode.SingleTableDataNodeLoader.load(SingleTableDataNodeLoader.java:69) ~[shardingsphere-single-core-5.3.1.jar:5.3.1]
at org.apache.shardingsphere.single.datanode.SingleTableDataNodeLoader.load(SingleTableDataNodeLoader.java:56) ~[shardingsphere-single-core-5.3.1.jar:5.3.1]
at org.apache.shardingsphere.single.rule.SingleRule.(SingleRule.java:78) ~[shardingsphere-single-core-5.3.1.jar:5.3.1]
at org.apache.shardingsphere.single.rule.builder.SingleRuleBuilder.build(SingleRuleBuilder.java:39) ~[shardingsphere-single-core-5.3.1.jar:5.3.1]
at org.apache.shardingsphere.single.rule.builder.SingleRuleBuilder.build(SingleRuleBuilder.java:34) ~[shardingsphere-single-core-5.3.1.jar:5.3.1]
at org.apache.shardingsphere.infra.rule.builder.database.DatabaseRulesBuilder.build(DatabaseRulesBuilder.java:64) ~[shardingsphere-infra-common-5.3.1.jar:5.3.1]
at org.apache.shardingsphere.infra.metadata.database.ShardingSphereDatabase.create(ShardingSphereDatabase.java:87) ~[shardingsphere-infra-common-5.3.1.jar:5.3.1]
at org.apache.shardingsphere.infra.metadata.database.ShardingSphereDatabasesFactory.createGenericDatabases(ShardingSphereDatabasesFactory.java:79) ~[shardingsphere-infra-common-5.3.1.jar:5.3.1]
at org.apache.shardingsphere.infra.metadata.database.ShardingSphereDatabasesFactory.create(ShardingSphereDatabasesFactory.java:67) ~[shardingsphere-infra-common-5.3.1.jar:5.3.1]
at org.apache.shardingsphere.mode.metadata.MetaDataContextsFactory.create(MetaDataContextsFactory.java:90) ~[shardingsphere-mode-core-5.3.1.jar:5.3.1]
at org.apache.shardingsphere.mode.metadata.MetaDataContextsFactory.create(MetaDataContextsFactory.java:68) ~[shardingsphere-mode-core-5.3.1.jar:5.3.1]
at org.apache.shardingsphere.mode.manager.standalone.StandaloneContextManagerBuilder.build(StandaloneContextManagerBuilder.java:54) ~[shardingsphere-standalone-mode-core-5.3.1.jar:5.3.1]
at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.createContextManager(ShardingSphereDataSource.java:81) ~[shardingsphere-jdbc-core-5.3.1.jar:5.3.1]
at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.(ShardingSphereDataSource.java:66) ~[shardingsphere-jdbc-core-5.3.1.jar:5.3.1]
at org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactory.createDataSource(ShardingSphereDataSourceFactory.java:93) ~[shardingsphere-jdbc-core-5.3.1.jar:5.3.1]
at org.apache.shardingsphere.driver.api.yaml.YamlShardingSphereDataSourceFactory.createDataSource(YamlShardingSphereDataSourceFactory.java:133) ~[shardingsphere-jdbc-core-5.3.1.jar:5.3.1]
at org.apache.shardingsphere.driver.api.yaml.YamlShardingSphereDataSourceFactory.createDataSource(YamlShardingSphereDataSourceFactory.java:114) ~[shardingsphere-jdbc-core-5.3.1.jar:5.3.1]
at com.cmbc.bigdata.sds.personalfinance.custr.config.DatasourceConfig.createDataSourceRetailc(DatasourceConfig.java:41) ~[classes/:na]
at com.cmbc.bigdata.sds.personalfinance.custr.config.DatasourceConfig$$EnhancerBySpringCGLIB$$51bcbce8.CGLIB$createDataSourceRetailc$0() ~[spring-core-4.2.0.RELEASE.jar:na]
at com.cmbc.bigdata.sds.personalfinance.custr.config.DatasourceConfig$$EnhancerBySpringCGLIB$$51bcbce8$$FastClassBySpringCGLIB$$8d0724c0.invoke() ~[spring-core-4.2.0.RELEASE.jar:na]
at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.2.0.RELEASE.jar:4.2.0.RELEASE]
at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:318) ~[spring-context-4.2.0.RELEASE.jar:4.2.0.RELEASE]
at com.cmbc.bigdata.sds.personalfinance.custr.config.DatasourceConfig$$EnhancerBySpringCGLIB$$51bcbce8.createDataSourceRetailc() ~[spring-core-4.2.0.RELEASE.jar:na]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_162]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.2.0.RELEASE.jar:4.2.0.RELEASE]
... 38 common frames omitted

**Comment by chakkk309** [comment]
Hi @heimao, could you plz help update this issue into English? That can make more people understand and better help you, thanks a lot!

**Comment by zhaojinchao95** [comment]
Only ask question in English. i will close it, you can create a new issue in English.
