### ISSUE TITLE
Why the org.apache.shardingsphere.dialect.exception.syntax.table.NoSuchTableException Error Occurs When Accessing the Actual Table

### ISSUE THREAD

**Issue by Pik1031** [apache/shardingsphere#28019]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

When I run a SQL statement to access the actual table, the following error occurs:

Sharding -jdbc 5.40
`org.springframework.jdbc.datasource.init.UncategorizedScriptException: Failed to execute database script from resource [class path resource [init.sql]]; nested exception is org.apache.shardingsphere.dialect.exception.syntax.table.NoSuchTableException

	at org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript(ScriptUtils.java:304)
	at org.springframework.jdbc.datasource.init.ResourceDatabasePopulator.populate(ResourceDatabasePopulator.java:254)
	at org.springframework.jdbc.datasource.init.DatabasePopulatorUtils.execute(DatabasePopulatorUtils.java:49)
	at org.springframework.jdbc.datasource.init.ResourceDatabasePopulator.execute(ResourceDatabasePopulator.java:269)
	at org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener.lambda$executeSqlScripts$4(SqlScriptsTestExecutionListener.java:263)
	at org.springframework.transaction.support.TransactionOperations.lambda$executeWithoutResult$0(TransactionOperations.java:68)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.springframework.transaction.support.TransactionOperations.executeWithoutResult(TransactionOperations.java:67)
	at org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener.executeSqlScripts(SqlScriptsTestExecutionListener.java:263)
	at org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener.lambda$executeSqlScripts$0(SqlScriptsTestExecutionListener.java:185)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener.executeSqlScripts(SqlScriptsTestExecutionListener.java:185)
	at org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener.executeSqlScripts(SqlScriptsTestExecutionListener.java:147)
	at org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener.beforeTestMethod(SqlScriptsTestExecutionListener.java:117)
	at org.springframework.test.context.TestContextManager.beforeTestMethod(TestContextManager.java:293)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: org.apache.shardingsphere.dialect.exception.syntax.table.NoSuchTableException
	at org.apache.shardingsphere.sharding.route.engine.condition.engine.InsertClauseShardingConditionEngine.lambda$appendMissingShardingConditions$1(InsertClauseShardingConditionEngine.java:97)
	at org.apache.shardingsphere.infra.util.exception.ShardingSpherePreconditions.checkState(ShardingSpherePreconditions.java:41)
	at org.apache.shardingsphere.sharding.route.engine.condition.engine.InsertClauseShardingConditionEngine.appendMissingShardingConditions(InsertClauseShardingConditionEngine.java:97)
	at org.apache.shardingsphere.sharding.route.engine.condition.engine.InsertClauseShardingConditionEngine.createShardingConditionsWithInsertValues(InsertClauseShardingConditionEngine.java:89)
	at org.apache.shardingsphere.sharding.route.engine.condition.engine.InsertClauseShardingConditionEngine.createShardingConditions(InsertClauseShardingConditionEngine.java:74)
	at org.apache.shardingsphere.sharding.route.engine.condition.engine.ShardingConditionEngine.createShardingConditions(ShardingConditionEngine.java:53)
	at org.apache.shardingsphere.sharding.route.engine.ShardingSQLRouter.createShardingConditions(ShardingSQLRouter.java:80)
	at org.apache.shardingsphere.sharding.route.engine.ShardingSQLRouter.createRouteContext0(ShardingSQLRouter.java:65)
	at org.apache.shardingsphere.sharding.route.engine.ShardingSQLRouter.createRouteContext(ShardingSQLRouter.java:59)
	at org.apache.shardingsphere.sharding.route.engine.ShardingSQLRouter.createRouteContext(ShardingSQLRouter.java:47)
	at org.apache.shardingsphere.infra.route.engine.impl.PartialSQLRouteExecutor.route(PartialSQLRouteExecutor.java:69)
	at org.apache.shardingsphere.infra.route.engine.SQLRouteEngine.route(SQLRouteEngine.java:57)
	at org.apache.shardingsphere.infra.connection.kernel.KernelProcessor.route(KernelProcessor.java:60)
	at org.apache.shardingsphere.infra.connection.kernel.KernelProcessor.generateExecutionContext(KernelProcessor.java:51)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.createExecutionContext(ShardingSphereStatement.java:510)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.execute0(ShardingSphereStatement.java:441)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.execute(ShardingSphereStatement.java:376)
	at org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript(ScriptUtils.java:260)
	... 37 more

`

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

why？and how？

**Comment by strongduanmu** [comment]
If you want to access actual table, you should use `/* SHARDINGSPHERE_HINT: DATA_SOURCE_NAME=ds_0 */ SELECT * FROM t_order;`  to pass sql to some datasource. For more details, you can refer - https://shardingsphere.apache.org/document/current/en/user-manual/common-config/sql-hint/#datasource-pass-through

**Comment by Pinkman-oss** [comment]
> If you want to access actual table, you should use `/* SHARDINGSPHERE_HINT: DATA_SOURCE_NAME=ds_0 */ SELECT * FROM t_order;` to pass sql to some datasource. For more details, you can refer - https://shardingsphere.apache.org/document/current/en/user-manual/common-config/sql-hint/#datasource-pass-through
Thanks for the answer, but it didn't work.

**Comment by Pinkman-oss** [comment]
`dataSources:
  backup:
    dataSourceClassName: xxxx
    driverClassName: xxx
    url: xxxx
    username: xxx
    password: xx
    filters: stat
    initialSize: 5   #连接池初始化连接数
    minIdle: 3       #连接池最小连接数
    maxActive: 60   #连接池最大连接数
    maxWait: 60000 #配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000 
    minEvictableIdleTimeMillis : 300000 
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true #打开PSCache，并且指定每个连接上PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 20 
    removeAbandoned: true 
    removeAbandonedTimeout: 200 
    validationQueryTimeout: 200
    logAbandoned: true 


rules:
  - !SINGLE
    tables:
      - backup.*  # 加载该数据源的全部表
    defaultDataSource: backup
  - !SHARDING
    tables: # 数据分片规则配置
      t_user: # 逻辑表名称
        actualDataNodes : backup.t_user_$->{1..19}
        tableStrategy: # 分表策略，同分库策略
          hint: # 用于单分片键的hint分片场景
            shardingAlgorithmName: hint_rule # 分片算法名称
    # 分片算法配置
    shardingAlgorithms:
      hint_rule: # 分片算法名称
        type: HINT_SHARD # 分片算法类型
props:
  sql-show: true`
this is my yaml

**Comment by clay-f** [comment]
same error here. I'm learn about latest shardingsphere-jdbc and do some test follow tutorial can't get running
    
    uncategorized SQLException; SQL state [HY000]; error code [30000]; Unknown exception: null

read document from [t_order](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/yaml-config/rules/sharding/)

config.yml

    mode:
      type: Standalone
      repository:
        type: JDBC
    
    schemaName: SCOTT
    
    dataSources:
      ds_0:
        dataSourceClassName: com.zaxxer.hikari.HikariDataSource
        driverClassName: oracle.jdbc.OracleDriver
        jdbcUrl: jdbc:oracle:thin:@//127.0.0.1:1521/orcl
        username: scott
        password: 123456
    
    rules:
      - !SINGLE
        tables:
          - "*.*"
        defaultDataSource: db_0
      - !SHARDING
        tables:
          t_order:
            actualDataNodes: ds_0.t_order_$->{0..1}
            tableStrategy:
              standard:
                shardingColumn: id
                shardingAlgorithmName: t_order_inline
        bindingTables:
          - t_order
        defaultDatabaseStrategy:
          standard:
            shardingColumn: id
            shardingAlgorithmName: database_inline
        defaultTableStrategy:
          none:
    
        shardingAlgorithms:
          database_inline:
            type: INLINE
            props:
              algorithm-expression: ds_0->{id % 2}
          t_order_inline:
            type: INLINE
            props:
              algorithm-expression: t_order_$->{id % 2}
    
    props:
      sql-show: true

application.yml


    spring:
      datasource:
        driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
        url: jdbc:shardingsphere:classpath:config.yml
    
      main:
        banner-mode: off
    
    mybatis:
      type-aliases-package: com.f.sharedingjdbc.domain
      mapper-locations: classpath:mapper/*.xml
    
    logging:
      level:
        com.f.sharedingjdbc.mapper: debug


order table sql xml file 

        <?xml version="1.0" encoding="UTF-8" ?>
        <!DOCTYPE mapper
                PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
                "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
        <mapper namespace="com.f.sharedingjdbc.mapper.OrderMapper">
        
            <select id="list" resultType="com.f.sharedingjdbc.domain.TOrder">
               SELECT * FROM t_order
            </select>
        </mapper>

database have three table used for test query
1. t_order
2. t_order_0
3. t_order_1

**Comment by clay-f** [comment]
@Pinkman-oss  I may found problem. change your table name uppercase, I'm changed fixed that issue

**Comment by clay-f** [comment]
I'm found problem, oracle needs change table uppercase for me situation😂
