### ISSUE TITLE
sharding-jdbc5.4 without the default-data-source-name option, tables without configuration rules will report an exception that the table cannot be found

### ISSUE THREAD

**Issue by ymwfish** [apache/shardingsphere#28084]
sharding-jdbc5.4 without the default-data-source-name option, tables without configuration rules will report an exception that the table cannot be found

JDBC Connection [HikariProxyConnection@1848393149 wrapping org.apache.shardingsphere.driver.jdbc.core.connection.ShardingSphereConnection@6c7cfaa0] will not be managed by Spring
==>  Preparing: INSERT INTO t_user ( user_id, user_name, user_name_plain, pwd, assisted_query_pwd ) VALUES ( ?, ?, ?, ?, ? )
==> Parameters: 1691274278381072386(Long), zhangsan(String), plain(String), 123(String), 456(String)
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@7886a7a2]
2023-08-15T10:23:18.868+08:00 ERROR 14260 --- [nio-8081-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.jdbc.BadSqlGrammarException: 
### Cause: java.sql.SQLException: Table 't_user' doesn't exist
; bad SQL grammar []] with root cause

java.sql.SQLException: Table 't_user' doesn't exist
	at org.apache.shardingsphere.dialect.mysql.mapper.MySQLDialectExceptionMapper.toSQLException(MySQLDialectExceptionMapper.java:120) ~[shardingsphere-mysql-dialect-exception-5.4.0.jar:5.4.0]
	at org.apache.shardingsphere.dialect.mysql.mapper.MySQLDialectExceptionMapper.convert(MySQLDialectExceptionMapper.java:72) ~[shardingsphere-mysql-dialect-exception-5.4.0.jar:5.4.0]
	at org.apache.shardingsphere.dialect.SQLExceptionTransformEngine.toSQLException(SQLExceptionTransformEngine.java:59) ~[shardingsphere-dialect-exception-core-5.4.0.jar:5.4.0]
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.execute(ShardingSpherePreparedStatement.java:416) ~[shardingsphere-jdbc-core-5.4.0.jar:5.4.0]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-5.0.1.jar:na]

**Comment by ymwfish** [comment]
springboot配置：
spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shading-auto-tables-algorithm.yaml

**Comment by zhaojinchao95** [comment]
Maybe you need to set single table confiuration, please refer to: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/rules/single/

**Comment by ymwfish** [comment]
Refers to the only table that exists in all sharded data sources. Suitable for tables with a small amount of data and do not need to be sharded
