### ISSUE TITLE
java.lang.ClassNotFoundException: org.bouncycastle.pqc.math.linearalgebra.ByteUtils

### ISSUE THREAD

**Issue by lizongbo** [apache/shardingsphere#28173]
### Which version of ShardingSphere did you use?
5.2.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
encrypt ok
### Actual behavior
```
java.lang.ClassNotFoundException: org.bouncycastle.pqc.math.linearalgebra.ByteUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_382]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_382]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_382]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_382]
	at org.apache.shardingsphere.encrypt.sm.algorithm.SM3EncryptAlgorithm.encrypt(SM3EncryptAlgorithm.java:64) ~[shardingsphere-encrypt-sm-5.2.1.jar:5.2.1]
	at org.apache.shardingsphere.encrypt.sm.algorithm.SM3EncryptAlgorithm.encrypt(SM3EncryptAlgorithm.java:35) ~[shardingsphere-encrypt-sm-5.2.1.jar:5.2.1]
	at org.apache.shardingsphere.encrypt.rewrite.parameter.rewriter.EncryptInsertValueParameterRewriter.encryptInsertValue(EncryptInsertValueParameterRewriter.java:114) ~[shardingsphere-encrypt-core-5.2.1.jar:5.2.1]
	at org.apache.shardingsphere.encrypt.rewrite.parameter.rewriter.EncryptInsertValueParameterRewriter.encryptInsertValues(EncryptInsertValueParameterRewriter.java:88) ~[shardingsphere-encrypt-core-5.2.1.jar:5.2.1]
	at org.apache.shardingsphere.encrypt.rewrite.parameter.rewriter.EncryptInsertValueParameterRewriter.lambda$rewrite$1(EncryptInsertValueParameterRewriter.java:71) ~[shardingsphere-encrypt-core-5.2.1.jar:5.2.1]
```

### Reason analyze (If you can)
class removed。

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

1. dependencies use:
```
    implementation  'org.bouncycastle:bcprov-jdk18on:1.75'
    implementation 'org.apache.shardingsphere:shardingsphere-jdbc-spring-namespace-infra:5.2.1'
    implementation 'org.apache.shardingsphere:shardingsphere-encrypt-spring-namespace:5.2.1'
    implementation 'org.apache.shardingsphere:shardingsphere-sharding-spring-namespace:5.2.1'
    implementation 'org.apache.shardingsphere:shardingsphere-parser-spring-namespace:5.2.1'
    implementation 'org.apache.shardingsphere:shardingsphere-jdbc-core-spring-namespace:5.2.1
```

2. xml config:
 ```
 <encrypt:encrypt-algorithm id="pwd_sm3encryptor" type="SM3">
    </encrypt:encrypt-algorithm>
```
3.run test
so get the exception

4.check the jar, bcprov-jdk18on 
org.bouncycastle.pqc.math.linearalgebra.ByteUtils is moved to org.bouncycastle.pqc.legacy.math.linearalgebra.ByteUtils.

bug fix method:
use  org.apache.commons.codec.binary.Hex to get hex string.

test code:
 ```
    @Test
    void testToHexString() {
        String str = "shardingsm3";
        String hextStr1 = org.bouncycastle.pqc.legacy.math.linearalgebra.ByteUtils.toHexString(str.getBytes());
        System.out.println("hexStr1=" + hextStr1);
        String hexStr2 = org.apache.commons.codec.binary.Hex.encodeHexString(str.getBytes());
        System.out.println("hexStr2=" + hexStr2);
        assertEquals(hextStr1, hexStr2);
    }
 ```
test result:
 ```
hexStr1=7368617264696e67736d33
hexStr2=7368617264696e67736d33
 ```

**Comment by zhaojinchao95** [comment]
Hi, you can remove implementation  `'org.bouncycastle:bcprov-jdk18on:1.75'` and try it again, it has some problems?

**Comment by lizongbo** [comment]
> Hi, you can remove implementation `'org.bouncycastle:bcprov-jdk18on:1.75'` and try it again, it has some problems?

bcprov-jdk15on is not supported by bouncycastle.
see info from https://bouncycastle.org/latest_releases.html#LATEST
---------------

Java Version Details With the arrival of Java 15. jdk15 is not quite as unambiguous as it was. The jdk18on jars are compiled to work with anything from Java 1.8 up. They are also multi-release jars so do support some features that were introduced in Java 9, Java 11, and Java 15. If you have issues with multi-release jars see the jdk15to18 release jars below.
Packaging Change (users of 1.70 or earlier): BC 1.71 changed the jdk15on jars to jdk18on so the base has now moved to Java 8. For earlier JVMs, or containers/applications that cannot cope with multi-release jars, you should now use the jdk15to18 jars.
