### ISSUE TITLE
shardingsphere5.4.0 zooKeeper Cluster mode second startup error

### ISSUE THREAD

**Issue by 3265692906** [apache/shardingsphere#28281]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'shardingDataSource' threw exception; nested exception is Can't construct a java object for tag:yaml.org,2002:com.alibaba.druid.filter.stat.StatFilter; exception=Class `com.alibaba.druid.filter.stat.StatFilter` is not accepted
 in 'string', line 226, column 3:
    - !!com.alibaba.druid.filter.stat. ... 
      ^

	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:579)
	... 56 common frames omitted
Caused by: org.yaml.snakeyaml.constructor.ConstructorException: Can't construct a java object for tag:yaml.org,2002:com.alibaba.druid.filter.stat.StatFilter; exception=Class `com.alibaba.druid.filter.stat.StatFilter` is not accepted
 in 'string', line 226, column 3:
    - !!com.alibaba.druid.filter.stat. ... 
      ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:364)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:270)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:253)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequenceStep2(BaseConstructor.java:469)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequence(BaseConstructor.java:435)
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlSeq.construct(SafeConstructor.java:577)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:270)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:253)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:581)
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:213)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:557)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:193)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:358)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:270)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:253)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:207)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:191)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:477)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:457)
	at org.apache.shardingsphere.infra.util.yaml.YamlEngine.unmarshal(YamlEngine.java:82)
	at org.apache.shardingsphere.metadata.persist.service.config.database.NewDataSourcePersistService.load(NewDataSourcePersistService.java:92)
	at org.apache.shardingsphere.metadata.persist.NewMetaDataPersistService.getEffectiveDataSources(NewMetaDataPersistService.java:136)
	at org.apache.shardingsphere.mode.metadata.NewMetaDataContextsFactory.createEffectiveDatabaseConfiguration(NewMetaDataContextsFactory.java:120)
	at org.apache.shardingsphere.mode.metadata.NewMetaDataContextsFactory.lambda$createEffectiveDatabaseConfigurations$1(NewMetaDataContextsFactory.java:115)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.apache.shardingsphere.mode.metadata.NewMetaDataContextsFactory.createEffectiveDatabaseConfigurations(NewMetaDataContextsFactory.java:114)
	at org.apache.shardingsphere.mode.metadata.NewMetaDataContextsFactory.create(NewMetaDataContextsFactory.java:87)
	at org.apache.shardingsphere.mode.manager.cluster.NewClusterContextManagerBuilder.build(NewClusterContextManagerBuilder.java:59)
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.createContextManager(ShardingSphereDataSource.java:82)
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.<init>(ShardingSphereDataSource.java:69)
	at org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactory.createDataSource(ShardingSphereDataSourceFactory.java:95)
	at org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactory.createDataSource(ShardingSphereDataSourceFactory.java:111)
	at com.mdks.ShardingSphereDataSourceConfig.shardingDataSource(ShardingSphereDataSourceConfig.java:94)
	at com.mdks.ShardingSphereDataSourceConfig$$EnhancerBySpringCGLIB$$2a554313.CGLIB$shardingDataSource$6(<generated>)
	at com.mdks.ShardingSphereDataSourceConfig$$EnhancerBySpringCGLIB$$2a554313$$FastClassBySpringCGLIB$$f2c45b0f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361)
	at com.mdks.ShardingSphereDataSourceConfig$$EnhancerBySpringCGLIB$$2a554313.shardingDataSource(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 57 common frames omitted
Caused by: java.lang.IllegalArgumentException: Class `com.alibaba.druid.filter.stat.StatFilter` is not accepted
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:217)
	at org.apache.shardingsphere.infra.util.yaml.constructor.ShardingSphereYamlConstructor.getClassForName(ShardingSphereYamlConstructor.java:63)
	at org.yaml.snakeyaml.constructor.Constructor.getClassForNode(Constructor.java:683)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.getConstructor(Constructor.java:349)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:358)
	... 107 common frames omitted

**Comment by Pace2Car** [comment]
Looks similar to this: https://github.com/apache/shardingsphere/issues/28013

**Comment by linghengqian** [comment]
- Verify that this issue has been resolved at https://github.com/apache/shardingsphere/issues/21211#issuecomment-1932123528 . 
- You must provide unit tests.

**Comment by terrymanu** [comment]
Due to no feedback from the author for an long period, I am closing this issue for now.
