### ISSUE TITLE
You have an error in your SQL syntax With Aliase | SQL Server

### ISSUE THREAD

**Issue by Afsalmc** [apache/shardingsphere#28669]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
Correctly parse and execute.
### Actual behavior
Throws : org.apache.shardingsphere.sql.parser.exception.SQLParsingException: You have an error in your SQL syntax: SELECT 
    [Limit1].[AccountID] AS [AccountID]
    FROM ( SELECT TOP (1) 
        [AccountID] AS [AccountID]   FROM [Account] 
   )  AS [Limit1], null
	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.twoPhaseParse(SQLParserExecutor.java:69)
	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.parse(SQLParserExecutor.java:48)
	at org.apache.shardingsphere.sql.parser.api.SQLParserEngine.parse(SQLParserEngine.java:47)
	at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserExecutor.parse(SQLStatementParserExecutor.java:46)
	at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserEngine.parse(SQLStatementParserEngine.java:47)
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine.parse(ShardingSphereSQLParserEngine.java:52)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.createQueryContext(ShardingSphereStatement.java:499)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.execute0(ShardingSphereStatement.java:428)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.execute(ShardingSphereStatement.java:376)
### Reason analyze (If you can)
I think Problem lies on Unconventional SQL Server syntax.
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Just Execute the above query.
### Example codes for reproduce this issue (such as a github link).
Just execute the SQL using shardingsphere jdbc.

**Comment by terrymanu** [comment]
Problem Understanding

  - Running SELECT [Limit1].[AccountID] AS [AccountID] FROM ( SELECT TOP (1) [AccountID] AS [AccountID] FROM [Account] ) AS [Limit1], null on ShardingSphere-JDBC (SQLServer) throws SQLParsingException; user expected it to succeed.

  Root Cause

  - FROM ... , null is not valid SQL Server syntax; null cannot be a table source. ShardingSphere’s SQLServer parser enforces SQL Server rules and rightly errors on an invalid table source—this is expected behavior, not a defect.

  Issue Analysis

  - Native SQL Server also rejects bare null in the FROM clause (e.g., “Incorrect syntax near ','/NULL”).
  - ShardingSphere’s SQLParserExecutor.twoPhaseParse validates the SQLServer dialect and fails during parsing.
  - To include a constant row, rewrite the SQL:
      - Drop the meaningless , null, keeping only the subquery; or
      - Use CROSS JOIN (SELECT NULL AS dummy) AS t to inject a constant row.
      - If the SQL is generated by an ORM (EF/LINQ, etc.), adjust the ORM query/config so it doesn’t emit the invalid , null fragment.

  Conclusion

  - The observed error comes from invalid SQL input, not a ShardingSphere bug.
  - If you believe this SQL should pass on native SQL Server, please share: the exact result/error from running it directly on SQL Server (with version), and the SQL generation path (ORM and configuration) so we can verify any compatibility gap.
