### ISSUE TITLE
dynamic actual-data-nodes refresh  in join query is invalid

### ISSUE THREAD

**Issue by StarHuzy** [apache/shardingsphere#28704]
## Bug Report
I used a single database sharding tables use local transaction mode
I have configured some tables

> t_order
> t_order_time

What I designed is Automatically split `tableStrategy` by tenant_id
this is my configuration
   [my project address by github](https://github.com/StarHuzy/sharging-jdbc)

I customized the allocation calculation class `DataShardingAlgorithm `implements `StandardShardingAlgorithm`

`DataShardingAlgorithm.Java`
```
@Component
@Slf4j
public class DataShardingAlgorithm implements StandardShardingAlgorithm<Long> {
    @Override
    public Collection<String> doSharding(Collection<String> collection, RangeShardingValue<Long> rangeShardingValue) {
        return collection;
    }

    @Override
    public String doSharding(Collection<String> collection, PreciseShardingValue<Long> preciseShardingValue) {
        StringBuilder resultTableName = new StringBuilder();
        String logicTableName = preciseShardingValue.getLogicTableName();
        // 拼接的tenantId，格式为 表名_{tenant_id}
        resultTableName.append(logicTableName).append("_").append(preciseShardingValue.getValue());
        String newTableName = resultTableName.toString().toLowerCase();
        if (!collection.contains(newTableName)) {
            // 动态新增节点
            ShardingAlgorithmTool.copyTable(logicTableName,newTableName);
            collection.add(newTableName);
        }
        System.out.println("collection = " + collection);
        return newTableName;
    }
    @Override
    public String getType() {
        return null;
    }
    @Override
    public void init(Properties properties) {
    }
}
```

`sharding.yaml`

```
dataSources:
  testApp:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/app_test
    username: root
    password: 123456
rules:
  - !TRANSACTION
    defaultType: XA
    providerType: Atomikos
  - !SHARDING
    tables:
      t_order: # 分表，逻辑表名
        # 节点表添加下初始的表,后续会在新增租户的时候新增表且刷新节点
        actualDataNodes: testApp.t_order
        tableStrategy: # 配置分表策略
          standard: # 用于单分片键的标准分片场景
            shardingColumn: tenant_id
            shardingAlgorithmName: real-data-inline
      t_order_item: # 分表，逻辑表名
        # 节点表添加下初始的表,后续会在新增租户的时候新增表且刷新节点
        actualDataNodes: testApp.t_order_item
        tableStrategy: # 配置分表策略
          standard: # 用于单分片键的标准分片场景
            shardingColumn: tenant_id
            shardingAlgorithmName: real-data-inline
    # 分片算法配置
    shardingAlgorithms:
      real-data-inline: # 分片算法名称
        type: CLASS_BASED #自定义策略
        props:
          strategy: standard
          # 包名+类名
          algorithmClassName: com.hcyl.cloud.test.utils.DataShardingAlgorithm
    bindingTables:
      - t_order,t_order_item
props:
  sql-show: true
mode:
  type: Standalone
```
### Expected behavior
1. I will add, delete, modify, and check a single table
![image](https://github.com/apache/shardingsphere/assets/42610282/5e1748bd-ff46-4ebd-b7ed-6b3b37980c51)

I have added data for the `t_order` table with `tenant_id = 1` 
![image](https://github.com/apache/shardingsphere/assets/42610282/7646939f-5d12-4c9d-9cd0-76d954f9cdc4) 

 My database has automatically added  `t_order_1 ` 

![image](https://github.com/apache/shardingsphere/assets/42610282/7bb745bb-ffe1-43d6-bc3d-beda5cb9af39)

I haven't configured a actualDataNodes with t_order_1 , but I can query it

![image](https://github.com/apache/shardingsphere/assets/42610282/3e005cb8-ed7c-441e-b4b8-10aaa7ee4d41)

![image](https://github.com/apache/shardingsphere/assets/42610282/baead397-b83e-4dd0-9a32-03995721f608)

Similarly, this table  t_order_item also has the same result

![image](https://github.com/apache/shardingsphere/assets/42610282/598e9b07-f8ee-4147-b1fd-50bdd43d4e5b)

![image](https://github.com/apache/shardingsphere/assets/42610282/da9d1f07-4c8c-485e-aabd-cbcf893c0b64)

![image](https://github.com/apache/shardingsphere/assets/42610282/70aee918-adaa-47a9-870f-0f080d863e8b)

![image](https://github.com/apache/shardingsphere/assets/42610282/5fac35a6-4b1e-4e4b-a935-2e565d40c38d)

2. I will ` JOIN ` QUERY with two tables ， But the result is as expected

![image](https://github.com/apache/shardingsphere/assets/42610282/2458a66f-b214-4e57-b29c-ad2c84ebe51a)

![image](https://github.com/apache/shardingsphere/assets/42610282/db5aa663-e399-497b-a719-88e7f0da4c25)

```
### Error querying database.  Cause: java.sql.SQLException: Actual table `testApp.t_order_item_1` is not in table rule configuration.
### The error may exist in file [E:\sharging-jdbc\target\classes\mapper\OrderMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT o.order_no, SUM(i.price * i.count) AS amount         FROM t_order o JOIN t_order_item i ON o.order_no = i.order_no         where o.tenant_id = ? and i.tenant_id = ?         GROUP BY o.order_no
### Cause: java.sql.SQLException: Actual table `testApp.t_order_item_1` is not in table rule configuration.
; Actual table `testApp.t_order_item_1` is not in table rule configuration.; nested exception is java.sql.SQLException: Actual table `testApp.t_order_item_1` is not in table rule configuration.] with root cause

java.sql.SQLException: Actual table `testApp.t_order_item_1` is not in table rule configuration.
	at org.apache.shardingsphere.infra.util.exception.external.sql.ShardingSphereSQLException.toSQLException(ShardingSphereSQLException.java:62) ~[shardingsphere-infra-util-5.3.2.jar:5.3.2]
	at org.apache.shardingsphere.dialect.SQLExceptionTransformEngine.toSQLException(SQLExceptionTransformEngine.java:51) ~[shardingsphere-dialect-exception-core-5.3.2.jar:5.3.2]
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.execute(ShardingSpherePreparedStatement.java:448) ~[shardingsphere-jdbc-core-5.3.2.jar:5.3.2]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-4.0.3.jar:na]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64) ~[mybatis-3.5.3.jar:3.5.3]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79) ~[mybatis-3.5.3.jar:3.5.3]
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doQuery(MybatisSimpleExecutor.java:67) ~[mybatis-plus-core-3.3.1.jar:3.3.1]
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324) ~[mybatis-3.5.3.jar:3.5.3]
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156) ~[mybatis-3.5.3.jar:3.5.3]
	at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.query(MybatisCachingExecutor.java:163) ~[mybatis-plus-core-3.3.1.jar:3.3.1]
	at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.query(MybatisCachingExecutor.java:90) ~[mybatis-plus-core-3.3.1.jar:3.3.1]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147) ~[mybatis-3.5.3.jar:3.5.3]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140) ~[mybatis-3.5.3.jar:3.5.3]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426) ~[mybatis-spring-2.0.3.jar:2.0.3]
	at com.sun.proxy.$Proxy67.selectList(Unknown Source) ~[na:na]
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:223) ~[mybatis-spring-2.0.3.jar:2.0.3]
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:177) ~[mybatis-plus-core-3.3.1.jar:3.3.1]
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:78) ~[mybatis-plus-core-3.3.1.jar:3.3.1]
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:96) ~[mybatis-plus-core-3.3.1.jar:3.3.1]
	at com.sun.proxy.$Proxy68.getOrderAmount(Unknown Source) ~[na:na]
	at org.example.service.impl.OrderServiceImpl.getOrderAmount(OrderServiceImpl.java:68) ~[classes/:na]
	at org.example.service.impl.OrderServiceImpl$$FastClassBySpringCGLIB$$d2a06cee.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.29.jar:5.3.29]
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386) ~[spring-aop-5.3.29.jar:5.3.29]
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85) ~[spring-aop-5.3.29.jar:5.3.29]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704) ~[spring-aop-5.3.29.jar:5.3.29]
	at org.example.service.impl.OrderServiceImpl$$EnhancerBySpringCGLIB$$c745fd74.getOrderAmount(<generated>) ~[classes/:na]
	at org.example.controller.OrderController.getOrderAmount(OrderController.java:51) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.29.jar:5.3.29]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.29.jar:5.3.29]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.29.jar:5.3.29]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.29.jar:5.3.29]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.29.jar:5.3.29]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.29.jar:5.3.29]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072) ~[spring-webmvc-5.3.29.jar:5.3.29]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965) ~[spring-webmvc-5.3.29.jar:5.3.29]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.29.jar:5.3.29]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.29.jar:5.3.29]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555) ~[tomcat-embed-core-9.0.78.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.29.jar:5.3.29]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) ~[tomcat-embed-core-9.0.78.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209) ~[tomcat-embed-core-9.0.78.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.78.jar:9.0.78]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-9.0.78.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.78.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.78.jar:9.0.78]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.29.jar:5.3.29]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.29.jar:5.3.29]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.78.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.78.jar:9.0.78]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.29.jar:5.3.29]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.29.jar:5.3.29]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.78.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.78.jar:9.0.78]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.29.jar:5.3.29]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.29.jar:5.3.29]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.78.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.78.jar:9.0.78]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[tomcat-embed-core-9.0.78.jar:9.0.78]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) [tomcat-embed-core-9.0.78.jar:9.0.78]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) [tomcat-embed-core-9.0.78.jar:9.0.78]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) [tomcat-embed-core-9.0.78.jar:9.0.78]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) [tomcat-embed-core-9.0.78.jar:9.0.78]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.78.jar:9.0.78]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.78.jar:9.0.78]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) [tomcat-embed-core-9.0.78.jar:9.0.78]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) [tomcat-embed-core-9.0.78.jar:9.0.78]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926) [tomcat-embed-core-9.0.78.jar:9.0.78]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791) [tomcat-embed-core-9.0.78.jar:9.0.78]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) [tomcat-embed-core-9.0.78.jar:9.0.78]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-9.0.78.jar:9.0.78]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-9.0.78.jar:9.0.78]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.78.jar:9.0.78]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
```

### Which version of ShardingSphere did you use?
shardingsphere-jdbc 5.3.2 + JDK 17 + spring-boot 2.7.14

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC 

### Reason analyze (If you can)

`java.sql.SQLException: Actual table `testApp.t_order_item_1` is not in table rule configuration.`

`JOIN QUERY`  The `actualDataNodes `displaying the associated table is not configured
But the `actualDataNodes `of a single table seem to be automatically loaded

`DataShardingAlgorithm.java doSharding(Collection<String> collection) ` with  It seems that the current node can be obtained

### Which version of ShardingSphere did you use?
shardingsphere-jdbc 5.3.2 + JDK 17 + spring-boot 2.7.14

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

**Comment by linghengqian** [comment]
- late reply.  I won't have time to confirm the real problem until tomorrow.  This seems to be related to some issues on the ShardingSphere JDBC 5.4.1 milestone.

**Comment by StarHuzy** [comment]
> * late reply.  I won't have time to confirm the real problem until tomorrow.  This seems to be related to some issues on the ShardingSphere JDBC 5.4.1 milestone.

SpringBoot  seems to have no DataSource management in ShardingSphere-jdbc 5.3.2。
How to obtain the DataSource object when adjusting the configuration reading of the Driver to the SPI interface in ShardingSphere-jdbc 5.3.2 ？
But can we refresh the table rule actualDataNodes by obtaining the dataSource？
![image](https://github.com/apache/shardingsphere/assets/42610282/efd7881f-cd51-42ff-8a81-e8ad54acc6ec)

**Comment by linghengqian** [comment]
> > * late reply.  I won't have time to confirm the real problem until tomorrow.  This seems to be related to some issues on the ShardingSphere JDBC 5.4.1 milestone.
> 
> SpringBoot seems to have no DataSource management in ShardingSphere-jdbc 5.3.2。 How to obtain the DataSource object when adjusting the configuration reading of the Driver to the SPI interface in ShardingSphere-jdbc 5.3.2 ？ But can we refresh the table rule actualDataNodes by obtaining the dataSource？

- You must consider that ShardingSphere JDBC 5.3.2 refactors the upstream and downstream ContextManager for SPI extensions to third-party metadata centers.

- I wrote an article at https://github.com/apache/shardingsphere/discussions/12258#discussioncomment-3917927, which mentioned how to get the real ShardingSphereDataSource to use ContextManager on ShardingSphere JDBC 5.3.2, which You need to actively define a Spring Bean. I am trying to help the downstream understand from a beginner's perspective how ContextManager serves dynamic update requirements like DistSQL.

- This article also mentions how to obtain the ContextManager through Connection when configuring through JDBC Driver. But not long after I noticed that this particular example had a bug at https://github.com/linghengqian/shardingsphere-contextmanager-explore/issues/3. I haven't figured out how to fix it yet -- even though I'm a ShardingSphere Committer, I have my knowledge blind spots because the master branch's unit tests change very frequently.

- I plan to refactor this article in the foreseeable future and include Examples for ShardingSphere JDBC 5.4.0 and 5.4.1. This TODO is documented at https://www.yuque.com/linghengqian/meve2v/ykridze9nguvect5 . Considering that I'm a graduating college student, finding time is difficult for me.

- As a warning, I definitely don't think you should inject any Spring Beans into the algorithmic class implementation of ShardingSphere SPI, which conflicts with the definition of DistSQL. Because the algorithm class must actually be the final class, DistSQL can remove and recreate the algorithm class. 

- As a further extension, I exposed the Row Value Expressions SPI at https://github.com/apache/shardingsphere/issues/22899. This allows for a more flexible way of defining ActualDataNodes. This feature is on the pre-release branch of ShardingSphere 5.4.1.

**Comment by StarHuzy** [comment]
> * 迟回复。直到明天我才有时间确认真正的问题。这似乎与 ShardingSphere JDBC 5.4.1 里程碑上的一些问题有关。



> > > * 迟回复。直到明天我才有时间确认真正的问题。这似乎与 ShardingSphere JDBC 5.4.1 里程碑上的一些问题有关。
> > 
> > 
> > ShardingSphere-jdbc 5.3.2 中 SpringBoot 好像没有 DataSource 管理。 ShardingSphere-jdbc 5.3.2 中将 Driver 的配置读取调整为 SPI 接口时，如何获取 DataSource 对象？但是我们可以通过以下方式刷新表规则actualDataNodes吗？获取数据源？
> 
> * 需要考虑的是，ShardingSphere JDBC 5.3.2对SPI扩展的上下游ContextManager进行了重构，对第三方元数据中心进行了重构。
> * 我在[【文章投稿】欢迎在这里留下文章链接 #12258（评论）](https://github.com/apache/shardingsphere/discussions/12258#discussioncomment-3917927)，提到了如何在ShardingSphere JDBC 5.3.0上获取真正的ShardingSphereDataSource使用ContextManager，需要主动定义一个Spring Bean。我试图帮助下游从初学者的角度理解 ContextManager 如何满足像 DistSQL 这样的动态更新需求。
> * 本文还提到了通过 JDBC Driver 配置时如何通过 Connection 获取 ContextManager。但没过多久，我发现这个例子在修复[ linghengqian/shardingsphere-contextmanager-explore#3](https://github.com/linghengqian/shardingsphere-contextmanager-explore/issues/3)[示例中更新元数据后 JDBC Connection 集体失败的问题](https://github.com/linghengqian/shardingsphere-contextmanager-explore/issues/3)上有一个 bug 。我还没有弄清楚如何修复它——尽管我是 ShardingSphere Committer，但我也有知识盲点，因为 master 分支的单元测试变化非常频繁。[`shardingsphere-v530-jdk8-modern`](https://github.com/linghengqian/shardingsphere-contextmanager-explore/issues/3)
> * 我计划在不久的将来重构这篇文章，并包含ShardingSphere JDBC 5.3.1、5.3.2、5.4.0和5.4.1的示例。此 TODO 记录在https://www.yuque.com/linghengqian/meve2v/ykridze9nguvect5。考虑到我是一名即将毕业的大学生，找到时间对我来说很困难。
> * 作为警告，我绝对不认为您应该将任何 Spring Bean 注入到 ShardingSphere SPI 的算法类实现中，这与 DistSQL 的定义相冲突。因为算法类实际上必须是最终类，所以 DistSQL 可以删除并重新创建算法类。
> * [作为进一步的扩展，我在MakeactualDataNodes 公开](https://github.com/apache/shardingsphere/issues/22899)SPI 中公开了行值表达式 SPI ，该 SPI 可以使用自定义规则定义表达式并添加 GraalVM Truffle 实现[ #22899](https://github.com/apache/shardingsphere/issues/22899)。这允许以更灵活的方式定义 ActualDataNodes。该功能位于ShardingSphere 5.4.1预发布分支上。[](https://github.com/apache/shardingsphere/issues/22899)
> * 更新：我提到的这篇文章涉及到一个非常不幸的问题，我没有精力翻译成英文，这让我假设你懂中文。

您好，今天尝试了很多版本，最终在ShardingSphere JDBC 5.1.1版本中实现了这个功能，actual-data-nodes 只需要配置动态加载的逻辑表名即可，无论是对单表还是 JOIN QUERY多表执行SQL，但是似乎又出现了一个新问题关于@transactional()注解管理事务，当我的msyql连接驱动版本是mysql-connector-java-8.0.33时，事务失效，我降级8.0.20版本后，事务成功，这是版本新特性的原因吗？5.1.1这个版本我如果想使用分布式事务，上面的问题会导致这个问题吗

**Comment by StarHuzy** [comment]
> > > * late reply.  I won't have time to confirm the real problem until tomorrow.  This seems to be related to some issues on the ShardingSphere JDBC 5.4.1 milestone.
> > 
> > 
> > SpringBoot seems to have no DataSource management in ShardingSphere-jdbc 5.3.2。 How to obtain the DataSource object when adjusting the configuration reading of the Driver to the SPI interface in ShardingSphere-jdbc 5.3.2 ？ But can we refresh the table rule actualDataNodes by obtaining the dataSource？
> 
> * You must consider that ShardingSphere JDBC 5.3.2 refactors the upstream and downstream ContextManager for SPI extensions to third-party metadata centers.
> * I wrote an article at [[Article Contribution] Welcome to Leave Your Article Link Here #12258 (comment)](https://github.com/apache/shardingsphere/discussions/12258#discussioncomment-3917927), which mentioned how to get the real ShardingSphereDataSource to use ContextManager on ShardingSphere JDBC 5.3.0, which You need to actively define a Spring Bean. I am trying to help the downstream understand from a beginner's perspective how ContextManager serves dynamic update requirements like DistSQL.
> * This article also mentions how to obtain the ContextManager through Connection when configuring through JDBC Driver. But not long after I noticed that this particular example had a bug at [Fix the problem that JDBC Connection fails collectively after updating metadata in the example of `shardingsphere-v530-jdk8-modern` linghengqian/shardingsphere-contextmanager-explore#3](https://github.com/linghengqian/shardingsphere-contextmanager-explore/issues/3). I haven't figured out how to fix it yet -- even though I'm a ShardingSphere Committer, I have my knowledge blind spots because the master branch's unit tests change very frequently.
> * I plan to refactor this article in the foreseeable future and include Examples for ShardingSphere JDBC 5.3.1, 5.3.2, 5.4.0 and 5.4.1. This TODO is documented at https://www.yuque.com/linghengqian/meve2v/ykridze9nguvect5 . Considering that I'm a graduating college student, finding time is difficult for me.
> * As a warning, I definitely don't think you should inject any Spring Beans into the algorithmic class implementation of ShardingSphere SPI, which conflicts with the definition of DistSQL. Because the algorithm class must actually be the final class, DistSQL can remove and recreate the algorithm class.
> * As a further extension, I exposed the Row Value Expressions SPI at [Make actualDataNodes expose SPI that can define expression with custom rules and add GraalVM Truffle implementation #22899](https://github.com/apache/shardingsphere/issues/22899). This allows for a more flexible way of defining ActualDataNodes. This feature is on the pre-release branch of ShardingSphere 5.4.1.
> * Update: The article I mentioned touches on a very unfortunate problem that I have no energy to translate into English, which leads me to assume that you understand Chinese.

Hello, I tried many versions today and finally implemented this feature in ShardingSphere JDBC version 5.1.1. The actual data nodes only need to configure the dynamically loaded logical table names to execute SQL on single or JOIN QUERY multiple tables. However, there seems to be a new issue with @ transactional () annotation management transactions. When my msyql connection driver version is mysql connector java 8.0.33, the transaction fails, After I downgraded version 8.0.20, the transaction was successful. Is this the reason for the new features of the version? If I want to use distributed transactions in version 5.1.1, will the above issues cause this issue

**Comment by linghengqian** [comment]
> Hello, I tried many versions today and finally implemented this feature in ShardingSphere JDBC version 5.1.1. The actual data nodes only need to configure the dynamically loaded logical table names to execute SQL on single or JOIN QUERY multiple tables. However, there seems to be a new issue with @ transactional () annotation management transactions. When my msyql connection driver version is mysql connector java 8.0.33, the transaction fails, After I downgraded version 8.0.20, the transaction was successful. Is this the reason for the new features of the version? If I want to use distributed transactions in version 5.1.1, will the above issues cause this issue

- Considering https://github.com/apache/shardingsphere/issues/28451 , I feel like this might be something that some of the ShardingSphere PRs synchronizing MySQL changes, but since I haven't finished investigating the current issue, it's all unknown.

**Comment by linghengqian** [comment]
@StarHuzy 
## 1st
- Your Example has become a highly complicated step. Most of the classes have nothing to do with the issues mentioned in the issue, which makes it difficult to read.
- I deleted the `Controller` layer and `Service` layer, and deleted the parameters of the `DTO` layer and Mybatis `Mapper` layer to directly expose the core logic in the unit test.
- I deleted the configuration of `Atomikos` distributed transactions. What happens in `Atomikos` should be discussed separately, because it will even overlap with the transaction log automatically opened by `Mybatis Plus`, complicating error reporting.
- I used `testcontainers` instead of MySQL to expose problems earlier. If you really need `MySQL`, you should use `testcontainers` to create a `MySQL` container. I have previously added `testcontainer url` support in the `ShardingSphere 5.3.1` milestone.
- Without `Maven Wrapper`, I have no way of knowing which version of Maven you are using. Initialize `Wrapper` on the spot.
- I didn't see the `README.md` explaining this project and I simply removed all JSON handling.
- Your `app_test.sql` makes no sense at all. It is just a SQL file for some logical table. It does not involve SQL for real database tables, and unit tests cannot be written.
## 2nd
- I simplified yours logic at https://github.com/linghengqian/sharging-jdbc-star-huzy-test/tree/fix-by-lingh by https://github.com/linghengqian/sharging-jdbc-star-huzy-test/commit/c3b3db6d6456c7051c566a874ac06a9f4f984860 .
- Let's start discussing the problem in your example.
- Your 3 classes `DataShardingMapper`, `ShardingAlgorithmTool` and `SpringUtils` make no sense. These classes do not involve ShardingSphere's metadata changes at all, and naturally the metadata is not refreshed.
- All IMHO, your core logic only involves `org.example.ShardingJdbcTest#testIssues28704`.
- You must manually take out the `ContextManager` and complete a series of real metadata changes, which requires simulating the behavior of DistSQL. Just like the article I mentioned in the previous part of the issue.
- I did not include a simulated operation of DistSQL in the example, because if you don't understand how DistSQL is written, what you will see is **a lot of magic code**. I first need to know what you think in the context of example.

**Comment by linghengqian** [comment]
- There is no response from the creator of the issue, so I think there is no point in continuing to open this issue.
