### ISSUE TITLE
When using the JDK of IBM(openj9), shardingsphere-core-5.4.0 will throw an exception when running

### ISSUE THREAD

**Issue by getf** [apache/shardingsphere#28744]
When using IBM's openj9 JDK, shardingsphere core 5.4.0 will throw an exception when running.
When using Oracle jdk, shardingsphere core 5.4.0 runs normally

Exception logs:

Caused by: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: -8
	at org.apache.shardingsphere.infra.util.spi.ShardingSphereServiceLoader.getServiceInstances(ShardingSphereServiceLoader.java:88) ~[shardingsphere-infra-util-5.4.0.jar:5.4.0]
	at org.apache.shardingsphere.driver.jdbc.core.driver.ShardingSphereDriverURLManager.getContent(ShardingSphereDriverURLManager.java:39) ~[shardingsphere-jdbc-core-5.4.0.jar:5.4.0]
	at org.apache.shardingsphere.driver.jdbc.core.driver.DriverDataSourceCache.createDataSource(DriverDataSourceCache.java:51) ~[shardingsphere-jdbc-core-5.4.0.jar:5.4.0]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_332]
	at org.apache.shardingsphere.driver.jdbc.core.driver.DriverDataSourceCache.get(DriverDataSourceCache.java:45) ~[shardingsphere-jdbc-core-5.4.0.jar:5.4.0]
	at org.apache.shardingsphere.driver.ShardingSphereDriver.connect(ShardingSphereDriver.java:51) ~[shardingsphere-jdbc-core-5.4.0.jar:5.4.0]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-4.0.3.jar:na]

**Comment by zhaojinchao95** [comment]
I think this problem are fixed in` 5.4.1` version, you can wait for the official release to pick it up again.

**Comment by getf** [comment]
bug is fixed. thanks
