### ISSUE TITLE
UnsupportedStorageTypeException  Unsupported storage type

### ISSUE THREAD

**Issue by tuwh** [apache/shardingsphere#28748]
### Which version of ShardingSphere did you use?
5.4.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior

The official document says that the sql92 standard database is supported, but when I use db2 database connection, an error of Unsupported storage type is reported。

### Actual behavior

Caused by: org.apache.shardingsphere.infra.exception.UnsupportedStorageTypeException: Unsupported storage type of `shadingDb.slave1`.
	at org.apache.shardingsphere.infra.database.type.checker.DatabaseTypeChecker.lambda$checkSupportedStorageTypes$3(DatabaseTypeChecker.java:79) ~[shardingsphere-infra-common-5.4.0.jar:5.4.0]
	at org.apache.shardingsphere.infra.util.exception.ShardingSpherePreconditions.checkState(ShardingSpherePreconditions.java:41) ~[shardingsphere-infra-util-5.4.0.jar:5.4.0]
	at org.apache.shardingsphere.infra.database.type.checker.DatabaseTypeChecker.lambda$checkSupportedStorageTypes$4(DatabaseTypeChecker.java:78) ~[shardingsphere-infra-common-5.4.0.jar:5.4.0]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:1.8.0_131]
	at org.apache.shardingsphere.infra.database.type.checker.DatabaseTypeChecker.checkSupportedStorageTypes(DatabaseTypeChecker.java:78) ~[shardingsphere-infra-common-5.4.0.jar:5.4.0]
	at org.apache.shardingsphere.metadata.factory.ExternalMetaDataFactory.createGenericDatabases(ExternalMetaDataFactory.java:83) ~[shardingsphere-metadata-core-5.4.0.jar:5.4.0]

### Reason analyze (If you can)

the class DatabaseTypeChecker Specify database type in {"MySQL", "PostgreSQL", "openGauss", "Oracle", "SQLServer", "H2", "MariaDB"}

### Example codes for reproduce this issue (such as a github link).

My code is written according to the document jdbc demo sample。

**Comment by RaigorJiang** [comment]
@tuwh Please show your configuration.

**Comment by RaigorJiang** [comment]
Hi @tuwh 
The problem cannot be located from your code snippets, and they cannot be executed (the dependencies are incomplete). What does your jdbcUrl look like?

**Comment by tuwh** [comment]
> Hi @tuwh The problem cannot be located from your code snippets, and they cannot be executed (the dependencies are incomplete). What does your jdbcUrl look like?

jdbcurl=jdbc:db2://10.20.18.177:50000/bemp:currentSchema=DB2BEMP;
driver=com.ibm.db2.jcc.DB2Driver

**Comment by RaigorJiang** [comment]
Okay, `DB2` is also an unsupported type and I’m afraid it cannot be integrated.
