### ISSUE TITLE
Unsupported SQL operation: unsupported TableSegment type occurs when I execute `select * from t1,t2 where t1.id(+)=t2.id` with oracle

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#28799]
### Which version of ShardingSphere did you use?

[299fecc](https://github.com/apache/shardingsphere/commit/299fecc718ada7737f77b98d58caf5c3f70eb0f7)

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Expected behavior

Parse `select * from t1,t2 where t1.id(+)=t2.id` successfully.

### Actual behavior

```
org.apache.shardingsphere.infra.exception.core.external.sql.type.generic.UnsupportedSQLOperationException: Unsupported SQL operation: unsupported TableSegment type: class org.apache.shardingsphere.sql.parser.sql.common.segment.dml.expr.simple.ColumnWithJoinOperatorSegment.
	at org.apache.shardingsphere.sqlfederation.optimizer.converter.segment.expression.ExpressionConverter.convert(ExpressionConverter.java:147)
	at org.apache.shardingsphere.sqlfederation.optimizer.converter.segment.expression.impl.BinaryOperationExpressionConverter.convertSqlNodes(BinaryOperationExpressionConverter.java:128)
	at org.apache.shardingsphere.sqlfederation.optimizer.converter.segment.expression.impl.BinaryOperationExpressionConverter.convert(BinaryOperationExpressionConverter.java:105)
	at org.apache.shardingsphere.sqlfederation.optimizer.converter.segment.expression.ExpressionConverter.convert(ExpressionConverter.java:91)
	at org.apache.shardingsphere.sqlfederation.optimizer.converter.segment.where.WhereConverter.convert(WhereConverter.java:34)
	at org.apache.shardingsphere.sqlfederation.optimizer.converter.statement.select.SelectStatementConverter.lambda$convertSelect$3(SelectStatementConverter.java:68)
	at java.base/java.util.Optional.flatMap(Optional.java:294)
	at org.apache.shardingsphere.sqlfederation.optimizer.converter.statement.select.SelectStatementConverter.convertSelect(SelectStatementConverter.java:68)
	at org.apache.shardingsphere.sqlfederation.optimizer.converter.statement.select.SelectStatementConverter.convert(SelectStatementConverter.java:52)
	at org.apache.shardingsphere.sqlfederation.optimizer.converter.SQLNodeConverterEngine.convert(SQLNodeConverterEngine.java:53)
```

**Comment by terrymanu** [comment]
Hi @strongduanmu,

Support for Oracle's legacy `(+)` outer join syntax in SQL Federation is **not planned**.

The parser already recognizes this syntax. The exception occurs later because SQL Federation cannot convert `OuterJoinExpression` into Calcite SQL semantics directly. Supporting it would require an Oracle-specific semantic rewrite from `(+)` predicates to ANSI outer joins, which is outside the current SQL Federation support boundary.

The query is already rejected explicitly with `UnsupportedSQLOperationException`, so it will not be executed with incorrect semantics. Please use ANSI `LEFT JOIN` or `RIGHT JOIN` syntax when SQL Federation is required.

Therefore, I am closing this issue as **not planned**.
