### ISSUE TITLE
SQL syntax exception occurs when I execute `select listagg(val,',') within group(order by val) vals from t1 group by id` with oracle

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#28801]
### Which version of ShardingSphere did you use?

[299fecc](https://github.com/apache/shardingsphere/commit/299fecc718ada7737f77b98d58caf5c3f70eb0f7)

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Expected behavior

Parse `select listagg(val,',') within group(order by val) vals from t1 group by id` successfully.

### Actual behavior

```
java.sql.SQLException: You have an error in your SQL syntax: select listagg(val,',') within group(order by val) vals from t1 group by id, null

	at org.apache.shardingsphere.infra.exception.core.external.sql.ShardingSphereSQLException.toSQLException(ShardingSphereSQLException.java:62)
	at org.apache.shardingsphere.infra.exception.dialect.SQLExceptionTransformEngine.toSQLException(SQLExceptionTransformEngine.java:54)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.executeQuery(ShardingSphereStatement.java:230)
	at org.apache.shardingsphere.driver.ShardingSphereDriverTest.assertDualWrite(ShardingSphereDriverTest.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
```

**Comment by strongduanmu** [comment]
This problem occurred because I passed the wrong databaseType during testing. When I fixed the databaseType, the problem was fixed.
