### ISSUE TITLE
Repeated column when use encrypt with JPA + Springboot

### ISSUE THREAD

**Issue by KomachiSion** [apache/shardingsphere#2884]
### Which version of ShardingSphere did you use?

4.0.0-RC2-SNAPSHOT

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

Sharding-JDBC

### Expected behavior

Insert encrypt successfully.

### Actual behavior

```
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Column 'user_name_plain' specified twice
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2490)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.EncryptPreparedStatement.executeUpdate(EncryptPreparedStatement.java:120)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
	... 23 more
```

### Reason analyze (If you can)

Logic SQL: `insert into t_user (assisted_query_pwd, pwd, user_name, user_name_plain, user_id) values (?, ?, ?, ?, ?)`

actual SQL: `insert into t_user (assisted_query_pwd, pwd, user_name, user_name_plain, user_id, assisted_query_pwd, user_name_plain) values (?, ?, ?, ?, ?, ?, ?) `

SQL generated by JPA has included `user_name_plain `, but encrypt add `user_name_plain` again.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

clone example code.
run `sharding-jdbc-example/other-feature-example/encrypt-example/encrypt-spring-boot-example/src/main/java/org/apache/shardingsphere/example/encrypt/table/spring/boot/SpringBootExample.java`

### Example codes for reproduce this issue (such as a github link).

https://github.com/apache/incubator-shardingsphere-example

**Comment by yhsmy** [comment]
我之前和你遇到同样的问题，后来发现是配置写错了encrypt.tables.表名.colums下面的逻辑列明写错了

**Comment by RaigorJiang** [comment]
Is this issue still there?  I will study it.

**Comment by RaigorJiang** [comment]
Update,  it's now processing.

**Comment by KomachiSion** [comment]
@RaigorJiang , Thanks for your contributions.

**Comment by RaigorJiang** [comment]
By the way, he property `<shardingsphere.version>`  need to upgrade to '4.0.0-RC4-SNAPSHOT' in 
shardingsphere-example project.

**Comment by KomachiSion** [comment]
@RaigorJiang , I saw the version has been upgrade in 6 days ago.

**Comment by RaigorJiang** [comment]
@KomachiSion   I see, thanks.

**Comment by KomachiSion** [comment]
PR#3663 will cause new issue #3770 , so revert this PR and reopen this issue.

I think we should fix this issue with implementing the DDL of encrypt.

**Comment by terrymanu** [comment]
Fixed at #3340

**Comment by kimmking** [comment]
It still here.

**Comment by kimmking** [comment]
repeated column is okay now.
but example can't be running now.
I will fix it.

**Comment by AINewBegin** [comment]
> repeated column is okay now.
> but example can't be running now.
> I will fix it.

4.1.0 still has it
