### ISSUE TITLE
Sharding count can not be null.

### ISSUE THREAD

**Issue by ylu2Fish** [apache/shardingsphere#28931]
### Which version of ShardingSphere did you use?

shardingsphere 5.2.1  springboot 2.6.15  

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 

### Expected behavior
    rules:
      sharding:
        tables:
          DEMO_PERSON: 
            actualDataNodes: master.DEMO_PERSON_$->{1..2} 
            tableStrategy: 
              standard: 
                shardingColumn: shardingKey
                shardingAlgorithmName: table-inline
       
        sharding-algorithms:
          table-inline: 
            type: MOD
            props: 
              sharding-count: 2

### Actual behavior
Caused by: java.lang.IllegalArgumentException: Sharding count can not be null.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at org.apache.shardingsphere.sharding.algorithm.sharding.mod.ModShardingAlgorithm.getShardingCount(ModShardingAlgorithm.java:70)
	at org.apache.shardingsphere.sharding.algorithm.sharding.mod.ModShardingAlgorithm.init(ModShardingAlgorithm.java:62)
	at org.apache.shardingsphere.infra.util.spi.type.typed.TypedSPIRegistry.findRegisteredService(TypedSPIRegistry.java:66)
	at org.apache.shardingsphere.infra.util.spi.type.typed.TypedSPIRegistry.getRegisteredService(TypedSPIRegistry.java:113)
	at org.apache.shardingsphere.infra.config.algorithm.ShardingSphereAlgorithmFactory.createAlgorithm(ShardingSphereAlgorithmFactory.java:40)
	at org.apache.shardingsphere.sharding.factory.ShardingAlgorithmFactory.newInstance(ShardingAlgorithmFactory.java:45)
	at org.apache.shardingsphere.sharding.rule.ShardingRule.lambda$new$0(ShardingRule.java:120)

### Reason analyze (If you can)
I adjusted the fragmentation policy to inline and configured the expression, but the expression was still not configured。

ShardingAlgorithmProvidedBeanRegistry have read to the configuration content, but shardingRuleConfiguration rule did not contain this part

when use inline algorithm ，also can not read the props configuration

**Comment by RaigorJiang** [comment]
Hi @ylu2Fish 
Are you using cluster mode?

**Comment by zzc678** [comment]
@ylu2Fish 老哥你最后怎么解决的
