### ISSUE TITLE
SqlStatementCompiler Not Support  JDBC Function DATABASE()

### ISSUE THREAD

**Issue by yaosing** [apache/shardingsphere#28969]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
sharding-jdbc 
### Expected behavior
SqlStatementCompiler can compile DATABASE() Function
### Actual behavior
Throw Exception:  No match found for function signature DATABASE()
Detail:
```
org.apache.calcite.runtime.CalciteContextException: At line 0, column 0: No match found for function signature DATABASE()

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:505)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:948)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:933)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.newValidationError(SqlValidatorImpl.java:5469)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.handleUnresolvedFunction(SqlValidatorImpl.java:2002)
	at org.apache.calcite.sql.SqlFunction.deriveType(SqlFunction.java:340)
	at org.apache.calcite.sql.SqlFunction.deriveType(SqlFunction.java:231)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:6534)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:6521)
	at org.apache.calcite.sql.SqlCall.accept(SqlCall.java:166)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.deriveTypeImpl(SqlValidatorImpl.java:1916)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.deriveType(SqlValidatorImpl.java:1901)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.expandSelectItem(SqlValidatorImpl.java:484)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelectList(SqlValidatorImpl.java:4624)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3806)
	at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:61)
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:88)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1144)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1115)
	at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:282)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:1090)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:796)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertQuery(SqlToRelConverter.java:598)
	at org.apache.shardingsphere.sqlfederation.optimizer.statement.SQLStatementCompiler.compile(SQLStatementCompiler.java:55)
	at org.apache.shardingsphere.sqlfederation.optimizer.it.SQLStatementCompilerIT.testJDBCFunctionDataBaseEscape(SQLStatementCompilerIT.java:277)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
Caused by: org.apache.calcite.sql.validate.SqlValidatorException: No match found for function signature DATABASE()
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:505)
	at org.apache.calcite.runtime.Resources$ExInst.ex(Resources.java:599)
	... 27 more
```
### Reason analyze (If you can)
SQLStatementCompiler try to use calcite's SqlUtil to validate sql, but  it only try to match standard function and operator(not contains DATABASE() function)
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Try to use org.apache.shardingsphere.sqlfederation.optimizer.it.SQLStatementCompilerIT with these code to reproduce the problem:
```
    @Test
    void testJDBCFunctionDataBase() {
        String sql = "select DATABASE()";
        SQLStatement sqlStatement = sqlParserRule.getSQLParserEngine(TypedSPILoader.getService(DatabaseType.class, "MySQL")).parse(sql, false);
        SQLFederationExecutionPlan plan = sqlStatementCompiler.compile(sqlStatement, "MySQL");
    }

    @Test
    void testJDBCFunctionDataBaseEscape() {
        String sql = "select {fn DATABASE()}";
        SQLStatement sqlStatement = sqlParserRule.getSQLParserEngine(TypedSPILoader.getService(DatabaseType.class, "MySQL")).parse(sql, false);
        SQLFederationExecutionPlan plan = sqlStatementCompiler.compile(sqlStatement, "MySQL");
    }
```

**Comment by yaosing** [comment]
Also is there any document can show us, what kind of function that we can use in sharding-jdbc

**Comment by strongduanmu** [comment]
Hi @yaosing, thank you for testing sql federation. Currently, sql federation is an experimental feature and is still under development, so there is no detailed documentation. If you are interested, you are welcome to test sql federation, which will help to improve this feature.

**Comment by yaosing** [comment]
Hello @strongduanmu, thanks for your reply,  My real scenario is this:
```
select count(*) from information_schema.columns where table_schema = DATABASE()
```
When using sharding to execute this sql, isUsingFederation logic think it;s System Schema and route to use Federation Execute Engine, this caused the problem. I tried to set isUsingFederation to false, but there has another exception that I dont know how to fix.
In my scenario, I tried to use CURRENT_CATALOG to skip this problem and it worked, but I still confused why System Schema default to use Federation Execute Engine and the System Schema is higher priority than the SQLFederationRuleConfiguration.

**Comment by strongduanmu** [comment]
Because after using the sharding feature, ShardingSphere abstracts concepts such as logical databases and logical tables. However, these concepts do not exist on MySQL and need to be queried in the ShardingSphere computing layer. SQL federation is a powerful computing engine, it can support logical metadata query well.

**Comment by amirhmd** [comment]
hi @strongduanmu I quickly investigate where the fix can be applied. below is my finding:
under `org/apache/shardingsphere/sqlfederation/optimizer/function/mysql` we can do the following:
 - Create a Custom Database Function Class
- Register the Database Function
- Unit Test the Functionality

if it looks correct to you I can work on it tomorrow?

**Comment by strongduanmu** [comment]
@amirhmd This idea seems to be correct, you can try submitting a PR.

**Comment by amirhmd** [comment]
@strongduanmu I am exploring a way to fetch the currentDatabaseName within the optimizer module. I noticed that there is a context available in shardingsphere-sql-federation-executor that could potentially provide this information. However, using it would violate the dependency flow, making it unsuitable for this purpose. In the optimizer module, I have observed the presence of an OptimizerContext. Unfortunately, it does not hold any data related to the current database name. Additionally, executing a query at this stage (e.g., using a Connection object) seems inappropriate and likely against the design principles. Would you know if there is a Calcite-specific Context or another mechanism available in the optimizer that could be leveraged to access the currentDatabaseName?

**Comment by terrymanu** [comment]
Hi @yaosing,

This issue has been resolved by #39906, which adds MySQL `DATABASE()` support to SQL Federation. Both `SELECT DATABASE()` and `SELECT {fn DATABASE()}` are now supported, and `DATABASE()` returns the current logical database name.

The fix has been merged into `master`, so I am closing this issue as completed. Please let us know if the problem can still be reproduced with the latest master branch.

**Comment by terrymanu** [comment]
Hi @yaosing, thanks for the report.

After further review, supporting MySQL `DATABASE()` is not planned for the open-source SQL Federation engine. We are reverting the `DATABASE()` implementation introduced by [#39906](https://github.com/apache/shardingsphere/pull/39906).

`DATABASE()` depends on the current MySQL session and default database context. Calcite does not natively provide this MySQL-specific runtime semantics, and implementing it in ShardingSphere would introduce dialect-specific compatibility behavior outside the scope of the open-source SQL Federation engine.

The MySQL SQL Federation provider now explicitly classifies `DATABASE()` as unsupported. This issue should remain closed, but the resolution should be changed from completed to not planned.
