### ISSUE TITLE
Failed to get driver instance for jdbcUrl=jdbc:mysql

### ISSUE THREAD

**Issue by Yiluhuakai22** [apache/shardingsphere#28972]
apache/shardingsphere-proxy 5.4.1
mysql mysql:5.7.18

server.yaml
```
mode:
  type: Standalone
  repository:
    type: JDBC

authority:
  users:
    - user: test@%
      password: test
props:
  sql-show: true
```
config-sharding.yaml
```
databaseName: sharding_db

dataSources:
 ds_0:
  url: jdbc:mysql://127.0.0.1:3306/test
  username: test
  password: test
```
error log
```
dev_shardingsphere-proxy | we find java version: java17, full_version=17.0.8.1, full_path=/opt/java/openjdk/bin/java
dev_shardingsphere-proxy | The classpath is /opt/shardingsphere-proxy/conf:/opt/shardingsphere-proxy/conf:.:/opt/shardingsphere-proxy/lib/*:/opt/shardingsphere-proxy/ext-lib/*
dev_shardingsphere-proxy | main class org.apache.shardingsphere.proxy.Bootstrap -1 /opt/shardingsphere-proxy/conf 0.0.0.0 false
dev_shardingsphere-proxy | Exception in thread "main" java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:mysql://127.0.0.1:3306/test
dev_shardingsphere-proxy | 	at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:114)
dev_shardingsphere-proxy | 	at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:331)
dev_shardingsphere-proxy | 	at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:114)
dev_shardingsphere-proxy | 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:108)
dev_shardingsphere-proxy | 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
dev_shardingsphere-proxy | 	at org.apache.shardingsphere.infra.datasource.pool.CatalogSwitchableDataSource.getConnection(CatalogSwitchableDataSource.java:46)
dev_shardingsphere-proxy | 	at org.apache.shardingsphere.infra.state.datasource.DataSourceStateManager.checkState(DataSourceStateManager.java:86)
dev_shardingsphere-proxy | 	at org.apache.shardingsphere.infra.state.datasource.DataSourceStateManager.initState(DataSourceStateManager.java:81)
dev_shardingsphere-proxy | 	at org.apache.shardingsphere.infra.state.datasource.DataSourceStateManager.lambda$initStates$0(DataSourceStateManager.java:72)
dev_shardingsphere-proxy | 	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
dev_shardingsphere-proxy | 	at org.apache.shardingsphere.infra.state.datasource.DataSourceStateManager.initStates(DataSourceStateManager.java:72)
dev_shardingsphere-proxy | 	at org.apache.shardingsphere.mode.metadata.NewMetaDataContextsFactory.lambda$checkDataSourceStates$2(NewMetaDataContextsFactory.java:129)
dev_shardingsphere-proxy | 	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
dev_shardingsphere-proxy | 	at org.apache.shardingsphere.mode.metadata.NewMetaDataContextsFactory.checkDataSourceStates(NewMetaDataContextsFactory.java:127)
dev_shardingsphere-proxy | 	at org.apache.shardingsphere.mode.metadata.NewMetaDataContextsFactory.create(NewMetaDataContextsFactory.java:90)
dev_shardingsphere-proxy | 	at org.apache.shardingsphere.mode.metadata.NewMetaDataContextsFactory.create(NewMetaDataContextsFactory.java:71)
dev_shardingsphere-proxy | 	at org.apache.shardingsphere.mode.manager.standalone.NewStandaloneContextManagerBuilder.build(NewStandaloneContextManagerBuilder.java:53)
dev_shardingsphere-proxy | 	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.createContextManager(BootstrapInitializer.java:68)
dev_shardingsphere-proxy | 	at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.init(BootstrapInitializer.java:58)
dev_shardingsphere-proxy | 	at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:55)
dev_shardingsphere-proxy | Caused by: java.sql.SQLException: No suitable driver
dev_shardingsphere-proxy | 	at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:299)
dev_shardingsphere-proxy | 	at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:106)
dev_shardingsphere-proxy | 	... 19 more
```
help,please

**Comment by RaigorJiang** [comment]
Hi @Yiluhuakai22 
Please put mysql driver jar to `/lib` or `ext-lib` in Proxy.
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/startup/bin/

**Comment by Yiluhuakai22** [comment]
> Hi @Yiluhuakai22 Please put mysql driver jar to `/lib` or `ext-lib` in Proxy. https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/startup/bin/

I resolve it already，thank you very much
