### ISSUE TITLE
 java.lang.NullPointerException in props.getConnectionPropertySynonyms().getStandardProperties().get("url").toString()

### ISSUE THREAD

**Issue by rechardguo** [apache/shardingsphere#29116]
## Bug Report

version:  5.4.1

project :ShardingSphere-JDBC

### Expected behavior
run without error
### Actual behavior
2023-11-21 22:23:05 22:23:05,290 ERROR [stderr] (ServerService Thread Pool -- 72) java.lang.NullPointerException
2023-11-21 22:23:05 22:23:05,291 ERROR [stderr] (ServerService Thread Pool -- 72)       at org.apache.shardingsphere.infra.metadata.database.resource.StorageResourceUtils.getStorageUnitNodeMapper(StorageResourceUtils.java:70)
2023-11-21 22:23:05 22:23:05,292 ERROR [stderr] (ServerService Thread Pool -- 72)       at org.apache.shardingsphere.infra.metadata.database.resource.StorageResourceUtils.lambda$getStorageUnitNodeMappers$3(StorageResourceUtils.java:58)
2023-11-21 22:23:05 22:23:05,292 ERROR [stderr] (ServerService Thread Pool -- 72)       at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
2023-11-21 22:23:05 22:23:05,293 ERROR [stderr] (ServerService Thread Pool -- 72)       at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
2023-11-21 22:23:05 22:23:05,294 ERROR [stderr] (ServerService Thread Pool -- 72)       at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
2023-11-21 22:23:05 22:23:05,295 ERROR [stderr] (ServerService Thread Pool -- 72)       at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
2023-11-21 22:23:05 22:23:05,296 ERROR [stderr] (ServerService Thread Pool -- 72)       at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
2023-11-21 22:23:05 22:23:05,297 ERROR [stderr] (ServerService Thread Pool -- 72)       at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
2023-11-21 22:23:05 22:23:05,298 ERROR [stderr] (ServerService Thread Pool -- 72)       at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2023-11-21 22:23:05 22:23:05,299 ERROR [stderr] (ServerService Thread Pool -- 72)       at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
2023-11-21 22:23:05 22:23:05,299 ERROR [stderr] (ServerService Thread Pool -- 72)       at org.apache.shardingsphere.infra.metadata.database.resource.StorageResourceUtils.getStorageUnitNodeMappers(StorageResourceUtils.java:58)
2023-11-21 22:23:05 22:23:05,300 ERROR [stderr] (ServerService Thread Pool -- 72)       at org.apache.shardingsphere.infra.config.database.impl.DataSourceProvidedDatabaseConfiguration.<init>(DataSourceProvidedDatabaseConfiguration.java:51)
2023-11-21 22:23:05 22:23:05,300 ERROR [stderr] (ServerService Thread Pool -- 72)       at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.createContextManager(ShardingSphereDataSource.java:76)
2023-11-21 22:23:05 22:23:05,301 ERROR [stderr] (ServerService Thread Pool -- 72)       at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.<init>(ShardingSphereDataSource.java:66)
2023-11-21 22:23:05 22:23:05,302 ERROR [stderr] (ServerService Thread Pool -- 72)       at org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactory.createDataSource(ShardingSphereDataSourceFactory.java:95)

### Reason analyze (If you can)
StorageResourceUtils
```
    public static StorageUnitNodeMapper getStorageUnitNodeMapper(final String dataSourceName, final DataSource dataSource) {
        DataSourcePoolProperties props = DataSourcePoolPropertiesCreator.create(dataSource);
        String url = props.getConnectionPropertySynonyms().getStandardProperties().get("url").toString();
        return new StorageUnitNodeMapper(dataSourceName, new StorageNode(dataSourceName), url);
    }
```

this code is reflect to get property of getter and isxx field of datasource,
but javax.sql.DataSource don't have any getUrl ,so it get null.
 
### Example codes for reproduce this issue (such as a github link).
1. config 2 jndi datasource ( mine in jboss)
2. code as below
```
                  //java:jboss/jdbc/Database
                  DataSource db =// get from jndi
                  dataSourceMap.put("db", db);
		    
		    //java:jboss/jdbc/DatabaseDoc
		    DataSource dbdoc =// get from jndi
		    dataSourceMap.put("dbdoc", dbdoc );
		    
		    
		    ShardingRuleConfiguration ruleConfig = new ShardingRuleConfiguration();
		    ruleConfig.getTables().add(new ShardingTableRuleConfiguration("footable", "dbdoc.footable"));
		    try {
		    dataSource = ShardingSphereDataSourceFactory
    				.createDataSource(dataSourceMap, Arrays.asList(ruleConfig), new Properties());
		    }catch(Exception e) {
		    	e.printStackTrace();
		    }
```

**Comment by RaigorJiang** [comment]
Hi @rechardguo ,
Thanks for your feedback, I will investigate this issue.

**Comment by RaigorJiang** [comment]
@rechardguo 
In the master branch, `StorageResourceUtils` has been refactored. 
I tested with master and there was no problem. Can you try the master branch?
