### ISSUE TITLE
When canceling the CDC job, the CDC server prints an error messages.

### ISSUE THREAD

**Issue by peilinqian** [apache/shardingsphere#29250]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
```
/usr/bin/java
we find java version: java8, full_version=1.8.0_242, full_path=/usr/bin/java
ShardingSphere-5.4.2-SNAPSHOT
Commit ID: dirty-dc9d8bef0e5696e38b9dec665fb4a39cd29c1062
Commit Message: Improve stop_time display at show streaming list of CDC (#29090)
Branch: master
Build time: 2022-12-12T03:18:10+0800
```

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
When canceling the CDC job, the CDC server prints normal messages.

### Actual behavior
When canceling the CDC job, the CDC server prints error messages.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1.  cdc client job is active
2.  cancel cdc client job

### Example codes for reproduce this issue (such as a github link).
```
[INFO ] 2023-11-30 18:23:25.600 [epollEventLoopGroup-4-7] o.a.s.d.p.c.h.CDCBackendHandler - close CDC job, channel id: 072e0127
[INFO ] 2023-11-30 18:23:25.600 [epollEventLoopGroup-4-7] o.a.s.d.p.c.job.AbstractPipelineJob - stop tasks runner, jobId=j0302p00006c87714d271b0c405436afa8a7dec034
[INFO ] 2023-11-30 18:23:25.600 [epollEventLoopGroup-4-7] o.a.s.d.p.c.e.AbstractPipelineLifecycleRunnable - stop lifecycle executor org.apache.shardingsphere.data.pipeline.opengauss.ingest.OpenGaussWALDumper@7a76a91d, startTime=2023-11-30 14:53:01, cost 12623883 ms
[INFO ] 2023-11-30 18:23:25.600 [epollEventLoopGroup-4-7] o.a.s.d.p.c.e.AbstractPipelineLifecycleRunnable - stop lifecycle executor org.apache.shardingsphere.data.pipeline.cdc.core.importer.CDCImporter@5d237593, startTime=2023-11-30 14:53:01, cost 12623883 ms
[INFO ] 2023-11-30 18:23:27.625 [epollEventLoopGroup-4-7] org.quartz.core.QuartzScheduler - Scheduler j0302p00006c87714d271b0c405436afa8a7dec034_$_NON_CLUSTERED shutting down.
[INFO ] 2023-11-30 18:23:27.625 [epollEventLoopGroup-4-7] org.quartz.core.QuartzScheduler - Scheduler j0302p00006c87714d271b0c405436afa8a7dec034_$_NON_CLUSTERED paused.
[INFO ] 2023-11-30 18:23:27.641 [epollEventLoopGroup-4-7] org.quartz.core.QuartzScheduler - Scheduler j0302p00006c87714d271b0c405436afa8a7dec034_$_NON_CLUSTERED shutdown complete.
[ERROR] 2023-11-30 18:23:27.644 [ShardingSphere-pipeline-callback-0] o.a.s.d.p.c.task.TaskExecuteCallback - onFailure, task ID=ds_0
java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2020)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2054)
	at java.util.concurrent.ArrayBlockingQueue.put(ArrayBlockingQueue.java:353)
	at org.apache.shardingsphere.data.pipeline.common.ingest.channel.memory.SimpleMemoryPipelineChannel.pushRecords(SimpleMemoryPipelineChannel.java:49)
	at org.apache.shardingsphere.data.pipeline.opengauss.ingest.OpenGaussWALDumper.processEventWithTX(OpenGaussWALDumper.java:159)
	at org.apache.shardingsphere.data.pipeline.opengauss.ingest.OpenGaussWALDumper.dump(OpenGaussWALDumper.java:123)
	at org.apache.shardingsphere.data.pipeline.opengauss.ingest.OpenGaussWALDumper.runBlocking(OpenGaussWALDumper.java:93)
	at org.apache.shardingsphere.data.pipeline.common.execute.AbstractPipelineLifecycleRunnable.start(AbstractPipelineLifecycleRunnable.java:52)
	at org.apache.shardingsphere.data.pipeline.common.execute.AbstractPipelineLifecycleRunnable.run(AbstractPipelineLifecycleRunnable.java:83)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] 2023-11-30 18:23:27.645 [j0302p00006c87714d271b0c405436afa8a7dec034_Worker-1] o.a.s.d.pipeline.cdc.core.job.CDCJob - onFailure, incremental task execute failed.
java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2020)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2054)
	at java.util.concurrent.ArrayBlockingQueue.put(ArrayBlockingQueue.java:353)
	at org.apache.shardingsphere.data.pipeline.common.ingest.channel.memory.SimpleMemoryPipelineChannel.pushRecords(SimpleMemoryPipelineChannel.java:49)
	at org.apache.shardingsphere.data.pipeline.opengauss.ingest.OpenGaussWALDumper.processEventWithTX(OpenGaussWALDumper.java:159)
	at org.apache.shardingsphere.data.pipeline.opengauss.ingest.OpenGaussWALDumper.dump(OpenGaussWALDumper.java:123)
	at org.apache.shardingsphere.data.pipeline.opengauss.ingest.OpenGaussWALDumper.runBlocking(OpenGaussWALDumper.java:93)
	at org.apache.shardingsphere.data.pipeline.common.execute.AbstractPipelineLifecycleRunnable.start(AbstractPipelineLifecycleRunnable.java:52)
	at org.apache.shardingsphere.data.pipeline.common.execute.AbstractPipelineLifecycleRunnable.run(AbstractPipelineLifecycleRunnable.java:83)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] 2023-11-30 18:23:27.658 [j0302p00006c87714d271b0c405436afa8a7dec034_Worker-1] o.a.s.e.e.h.g.LogJobErrorHandler - Job 'j0302p00006c87714d271b0c405436afa8a7dec034' exception occur in job processing
java.lang.NullPointerException: null
	at org.apache.shardingsphere.data.pipeline.cdc.protocol.response.CDCResponse$Builder.setErrorMessage(CDCResponse.java:1677)
	at org.apache.shardingsphere.data.pipeline.cdc.generator.CDCResponseUtils.failed(CDCResponseUtils.java:86)
	at org.apache.shardingsphere.data.pipeline.cdc.core.job.CDCJob$CDCExecuteCallback.onFailure(CDCJob.java:210)
	at org.apache.shardingsphere.data.pipeline.common.execute.ExecuteEngine.trigger(ExecuteEngine.java:137)
	at org.apache.shardingsphere.data.pipeline.cdc.core.job.CDCJob.executeIncrementalTasks(CDCJob.java:173)
	at org.apache.shardingsphere.data.pipeline.cdc.core.job.CDCJob.execute(CDCJob.java:105)
	at org.apache.shardingsphere.elasticjob.simple.executor.SimpleJobExecutor.process(SimpleJobExecutor.java:33)
	at org.apache.shardingsphere.elasticjob.simple.executor.SimpleJobExecutor.process(SimpleJobExecutor.java:29)
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.process(ElasticJobExecutor.java:173)
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.process(ElasticJobExecutor.java:142)
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.execute(ElasticJobExecutor.java:124)
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.execute(ElasticJobExecutor.java:100)
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.LiteJob.execute(LiteJob.java:35)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[INFO ] 2023-11-30 18:23:27.692 [Pipeline-EventListener-21] o.a.s.d.p.c.m.n.e.h.i.ConfigMetaDataChangedEventHandler - UPDATED job configuration: /pipeline/jobs/j0302p00006c87714d271b0c405436afa8a7dec034/config, disabled=true
[INFO ] 2023-11-30 18:23:27.693 [j0302p00006c87714d271b0c405436afa8a7dec034_Worker-1] o.a.s.d.p.c.l.PipelineElasticJobListener - After j0302p00006c87714d271b0c405436afa8a7dec034 job execute 
[WARN ] 2023-11-30 18:23:40.563 [epollEventLoopGroup-4-8] o.a.s.d.p.cdc.api.impl.CDCJobAPI - CDC job already exists in registry center, ignore, jobConfigKey=/pipeline/jobs/j0302p00006c87714d271b0c405436afa8a7dec034/config
[INFO ] 2023-11-30 18:23:40.602 [Pipeline-EventListener-21] o.a.s.d.p.c.m.n.e.h.i.ConfigMetaDataChangedEventHandler - UPDATED job configuration: /pipeline/jobs/j0302p00006c87714d271b0c405436afa8a7dec034/config, disabled=false
[INFO ] 2023-11-30 18:23:40.605 [epollEventLoopGroup-4-8] org.quartz.impl.StdSchedulerFactory - Using default implementation for ThreadExecutor
[INFO ] 2023-11-30 18:23:40.606 [epollEventLoopGroup-4-8] o.quartz.core.SchedulerSignalerImpl - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
[INFO ] 2023-11-30 18:23:40.606 [epollEventLoopGroup-4-8] org.quartz.core.QuartzScheduler - Quartz Scheduler v.2.3.2 created.
[INFO ] 2023-11-30 18:23:40.606 [epollEventLoopGroup-4-8] o.a.s.e.l.i.s.JobShutdownHookPlugin - Registering Quartz shutdown hook. j0302p00006c87714d271b0c405436afa8a7dec034
[INFO ] 2023-11-30 18:23:40.606 [epollEventLoopGroup-4-8] org.quartz.simpl.RAMJobStore - RAMJobStore initialized.
[INFO ] 2023-11-30 18:23:40.606 [epollEventLoopGroup-4-8] org.quartz.core.QuartzScheduler - Scheduler meta-data: Quartz Scheduler (v2.3.2) 'j0302p00006c87714d271b0c405436afa8a7dec034' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 1 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

[INFO ] 2023-11-30 18:23:40.606 [epollEventLoopGroup-4-8] org.quartz.impl.StdSchedulerFactory - Quartz scheduler 'j0302p00006c87714d271b0c405436afa8a7dec034' initialized from an externally provided properties instance.
[INFO ] 2023-11-30 18:23:40.606 [epollEventLoopGroup-4-8] org.quartz.impl.StdSchedulerFactory - Quartz scheduler version: 2.3.2
[INFO ] 2023-11-30 18:23:40.842 [ListenerNotify-j0302p00006c87714d271b0c405436afa8a7dec034-0] org.quartz.core.QuartzScheduler - Scheduler j0302p00006c87714d271b0c405436afa8a7dec034_$_NON_CLUSTERED started.
[INFO ] 2023-11-30 18:23:40.907 [j0302p00006c87714d271b0c405436afa8a7dec034_Worker-1] o.a.s.d.pipeline.cdc.core.job.CDCJob - Execute job j0302p00006c87714d271b0c405436afa8a7dec034
[INFO ] 2023-11-30 18:23:40.921 [j0302p00006c87714d271b0c405436afa8a7dec034_Worker-1] o.a.s.d.pipeline.cdc.core.job.CDCJob - start tasks runner, jobId=j0302p00006c87714d271b0c405436afa8a7dec034, shardingItem=0
[INFO ] 2023-11-30 18:23:40.923 [j0302p00006c87714d271b0c405436afa8a7dec034_Worker-1] o.o.core.v3.ConnectionFactoryImpl - [2b1e0c58-756d-45b5-8cfd-c5b414f9d8e7] Try to connect. IP: 20.20.20.54:18000
[INFO ] 2023-11-30 18:23:40.950 [j0302p00006c87714d271b0c405436afa8a7dec034_Worker-1] o.o.core.v3.ConnectionFactoryImpl - [20.20.20.52:40314/20.20.20.54:18000] Connection is established. ID: 2b1e0c58-756d-45b5-8cfd-c5b414f9d8e7
[INFO ] 2023-11-30 18:23:40.955 [j0302p00006c87714d271b0c405436afa8a7dec034_Worker-1] o.o.core.v3.ConnectionFactoryImpl - Connect complete. ID: 2b1e0c58-756d-45b5-8cfd-c5b414f9d8e7
[INFO ] 2023-11-30 18:23:41.037 [j0302p00006c87714d271b0c405436afa8a7dec034_Worker-1] o.a.s.d.p.c.c.prepare.CDCJobPreparer - initInventoryTasks cost 115 ms
[INFO ] 2023-11-30 18:23:41.052 [j0302p00006c87714d271b0c405436afa8a7dec034_Worker-1] o.a.s.d.pipeline.cdc.core.job.CDCJob - execute incremental tasks, jobId=j0302p00006c87714d271b0c405436afa8a7dec034
[INFO ] 2023-11-30 18:23:41.070 [ShardingSphere-pipeline-Incremental-j0302p00006c87714d271b0c405436afa8a7dec034-0] o.o.core.v3.ConnectionFactoryImpl - [00cb36c5-907c-43d4-8b6d-dc9f74f64b58] Try to connect. IP: 20.20.20.54:18000
[INFO ] 2023-11-30 18:23:41.099 [ShardingSphere-pipeline-Incremental-j0302p00006c87714d271b0c405436afa8a7dec034-0] o.o.core.v3.ConnectionFactoryImpl - [20.20.20.52:40322/20.20.20.54:18000] Connection is established. ID: 00cb36c5-907c-43d4-8b6d-dc9f74f64b58
```

**Comment by azexcy** [comment]
it's improved at https://github.com/apache/shardingsphere/pull/29453
