### ISSUE TITLE
Unable to find property 'authority' on class

### ISSUE THREAD

**Issue by medivh666** [apache/shardingsphere#29299]
Unable to find property 'authority' on class

server.yaml
authority:
  users:
    - user: root@%
      password: 123456
    - user: sharding
      password: sharding
  privilege:
    type: ALL_PERMITTED

props:
  proxy-mysql-default-version: 8.0.35

but report this error:

Starting the Sharding-Proxy ...
The port is configured as 3308
Please check the STDOUT file: /opt/sharding-proxy/logs/stdout.log
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:410)
        at io.shardingsphere.shardingproxy.config.ShardingConfigurationLoader.loadServerConfiguration(ShardingConfigurationLoader.java:84)
        at io.shardingsphere.shardingproxy.config.ShardingConfigurationLoader.load(ShardingConfigurationLoader.java:61)
        at io.shardingsphere.shardingproxy.Bootstrap.main(Bootstrap.java:65)
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'authority' on class: io.shardingsphere.shardingproxy.config.yaml.YamlProxyServerConfiguration
        at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:132)
        at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:121)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.getProperty(Constructor.java:322)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:240)
        ... 10 more

**Comment by RaigorJiang** [comment]
Hi @medivh666 
I think no one can answer your issue because you did not provide enough information according to the template, such as ShardingSphere version.

**Comment by medivh666** [comment]
sorrry , I run it from an old document ，It ran successfully according to the latest documentation
