### ISSUE TITLE
 Unknown system variable 'query_cache_size'

### ISSUE THREAD

**Issue by medivh666** [apache/shardingsphere#29300]
apt-get install mysql-server

mysql> SELECT VERSION();
+-------------------------+
| VERSION()               |
+-------------------------+
| 8.0.35-0ubuntu0.22.04.1 |
+-------------------------+

I tried the following configuration,But an error is still reported

props:
  proxy-mysql-default-version: 8.0.35

or 

props:
  proxy-mysql-default-version: 8.0.35-0ubuntu0.22.04.1

======error======
[ERROR] 16:30:48.824 [main] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
java.sql.SQLException: Unknown system variable 'query_cache_size'
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2444)
        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381)
        at com.mysql.jdbc.ConnectionImpl.loadServerVariables(ConnectionImpl.java:3766)
        at com.mysql.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:3229)
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2238)

**Comment by RaigorJiang** [comment]
@medivh666 
What's the version of mysql-connector-java?

**Comment by medivh666** [comment]
sorrry , I run it from an old document ，It ran successfully according to the latest documentation
