### ISSUE TITLE
No implementation class load from SPI TestContainer Databases

### ISSUE THREAD

**Issue by ilyasahsan123** [apache/shardingsphere#29495]
## Bug Report

I encountered the following problems when running unittest on the `TestcontainersDatabaseTypeTest` class 

```
-------------------------------------------------------------------------------
Test set: org.apache.shardingsphere.infra.database.testcontainers.type.TestcontainersDatabaseTypeTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.094 s <<< FAILURE! -- in org.apache.shardingsphere.infra.database.testcontainers.type.TestcontainersDatabaseTypeTest
org.apache.shardingsphere.infra.database.testcontainers.type.TestcontainersDatabaseTypeTest.assertGetJdbcUrlPrefixes -- Time elapsed: 0.052 s <<< ERROR!
org.apache.shardingsphere.infra.spi.exception.ServiceProviderNotFoundException: SPI-00001: No implementation class load from SPI `org.apache.shardingsphere.infra.database.core.type.DatabaseType` with type `TestContainersClickHouse`.
	at org.apache.shardingsphere.infra.spi.type.typed.TypedSPILoader.lambda$getService$1(TypedSPILoader.java:110)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.apache.shardingsphere.infra.spi.type.typed.TypedSPILoader.lambda$getService$2(TypedSPILoader.java:110)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at org.apache.shardingsphere.infra.spi.type.typed.TypedSPILoader.getService(TypedSPILoader.java:110)
	at org.apache.shardingsphere.infra.spi.type.typed.TypedSPILoader.getService(TypedSPILoader.java:97)
	at 
```

### Which version of ShardingSphere did you use?
5.4.2-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere

### Expected behavior
Passed unittest on the `TestcontainersDatabaseTypeTest` class.

### Actual behavior
The unittest failed due to No implementation class load from SPI TestContainer Databases.

### Reason analyze (If you can)
The TestContainer Database type name is Invalid.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Run the unittest on the `TestcontainersDatabaseTypeTest` class

### Example codes for reproduce this issue (such as a github link).
[TestcontainersDatabaseTypeTest.java](https://github.com/apache/shardingsphere/blob/master/infra/database/type/testcontainers/src/test/java/org/apache/shardingsphere/infra/database/testcontainers/type/TestcontainersDatabaseTypeTest.java#L32)

**Comment by ilyasahsan123** [comment]
Never mind. It turns out the issue has resolved.
