### ISSUE TITLE
class java.time.LocalDateTime cannot be cast to class java.util.Date

### ISSUE THREAD

**Issue by xigongxiaoche** [apache/shardingsphere#29630]
## class java.time.LocalDateTime cannot be cast to class java.util.Date

shardingsphere proxy version: 5.3.2
mysql version: 8.0.28-230701

HuaWei CDM extracts data from mysql successfully, but extracts data from sharingsphere proxy failed, error：
`2024-01-02 19:25:59.346|ERROR|LocalJobRunner Map Task #1|[org.apache.sqoop.utils.JdbcSandbox:62]|occur exception, actual is :
java.sql.SQLException: Unknown exception: class java.time.LocalDateTime cannot be cast to class java.util.Date (java.time.LocalDateTime and java.util.Date are in module java.base of loader 'bootstrap')
	at com.mysql.cj.jdbc.exceptions.SQLERROR.createSQLException(SQLERROR.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.result.ResultSetImpl.next(ResultSetImpl.java:1828)
	at org.apache.sqoop.connector.jdbc.sql.impl.UnProtectedResultSet.next(UnProtectedResultSet.java:27)
	at org.apache.sqoop.connector.jdbc.GenericJdbcExtractor.extractObjectRecord(GenericJdbcExtractor.java:179)
	at org.apache.sqoop.connector.jdbc.GenericJdbcExtractor.lambda$extract$1(GenericJdbcExtractor.java:151)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.sqoop.utils.JdbcSandbox.doPrivileged(JdbcSandbox.java:53)
	at org.apache.sqoop.connector.jdbc.GenericJdbcExtractor.extract(GenericJdbcExtractor.java:150)
	at org.apache.sqoop.connector.jdbc.GenericJdbcExtractor.extract(GenericJdbcExtractor.java:65)
	at org.apache.sqoop.job.mr.SqoopMapper.runInternal(SqoopMapper.java:190)
	at org.apache.sqoop.job.mr.SqoopMapper.run(SqoopMapper.java:87)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:799)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:283)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.sqoop.submission.mapreduce.MapTaskExecutorService$MapTaskCallback.run(MapTaskExecutorService.java:260)
	at org.apache.sqoop.submission.mapreduce.SqoopJob$WrappedTask.run(SqoopJob.java:309)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)`

**Comment by linghengqian** [comment]
- I'm having a hard time understanding what this has to do with ShardingSphere, the stack doesn't involve ShardingSphere classes. Can you provide a unit test using testcontainers-java and upload it to a separate git?

**Comment by linghengqian** [comment]
- Due to lack of reproducible unit tests, I'm closing this issue.
