### ISSUE TITLE
error：There is no default constructor available in 'org.yaml.snakeyaml.representer.Representer'

### ISSUE THREAD

**Issue by xiohuchi** [apache/shardingsphere#29771]
## Bug Report

shardingsphere-jdbc-core 5.4.1
springboot 3.2.1  ( snakeyaml 2.2 )

error：There is no default constructor available in 'org.yaml.snakeyaml.representer.Representer'

at： org.apache.shardingsphere.infra.util.yaml.representer.ShardingSphereYamlRepresenter

## detail log

`
[2024-01-19 08:55:02.403][ERROR][][http-nio-18008-exec-6][o.a.c.c.C.[.[localhost].[/].[dispatcherServlet]][Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed: java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method 'void <init>()' not found] with root cause]

java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method 'void <init>()' not found

        at org.apache.shardingsphere.infra.util.yaml.representer.ShardingSphereYamlRepresenter.<init>(ShardingSphereYamlRepresenter.java:42)

        at org.apache.shardingsphere.infra.util.yaml.YamlEngine.marshal(YamlEngine.java:112)

        at org.apache.shardingsphere.metadata.persist.service.config.global.NewPropertiesPersistService.persist(NewPropertiesPersistService.java:51)        

`

**Comment by linghengqian** [comment]
- Fixes by https://github.com/apache/shardingsphere/pull/28805 .

**Comment by xiohuchi** [comment]
那咋搞，还没有修复版本

**Comment by linghengqian** [comment]
- You can manually compile the project by following the steps below, and upload the corresponding products in the local Maven repository to your private repository. This uses `SDKMAN!`.
```shell
sdk install java 21.0.2-graalce
sdk use java 21.0.2-graalce

git clone git@github.com:apache/shardingsphere.git
cd ./shardingsphere/

./mvnw clean install -Prelease -T1C -DskipTests -Djacoco.skip=true -Dcheckstyle.skip=true -Drat.skip=true -Dmaven.javadoc.skip=true -B
```

- I'm not the PMC for the project, so I can't make any subjective assumptions about when the next release will be. If you need a release sooner, you should start a discussion thread on the mailing list.

**Comment by linghengqian** [comment]
- Superseded by https://github.com/apache/shardingsphere/issues/30215 .
