### ISSUE TITLE
Streaming query shardingsphere-proxy always interrupted

### ISSUE THREAD

**Issue by GPF199541** [apache/shardingsphere#29989]
connect shard-proxy with jdbc
proxy version 5.40
jdbc:8.0.11
Connection connection = driver.connect(url, null);
PreparedStatement preparedStatement = connection.prepareStatement("use db1");
preparedStatement.setFetchSize(Integer.MIN_VALUE);
ResultSet resultSet = preparedStatement.executeQuery(sql);
error:
[ERROR] 2024-02-04 17:59:27.856 [ShardingSphere-Command-165] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
java.sql.SQLException: null
        at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.close(DatabaseConnector.java:404)
        at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.close(MySQLComQueryPacketExecutor.java:128)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.doExecuteCommand(CommandExecutorTask.java:139)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:121)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:78)
        at com.alibaba.ttl.TtlRunnable.run(TtlRunnable.java:60)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by GPF199541** [comment]
I want to stream query 50 million rows of data
