### ISSUE TITLE
org.yaml.snakeyaml.representer.Representer: method 'void <init>()' not found

### ISSUE THREAD

**Issue by chrismayday** [apache/shardingsphere#30815]
How to use shardingsphere jdbc version 5.4.1 and springboot 3.1.4 to implement data sharding?

error info:

java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method 'void <init>()' not found
	at org.apache.shardingsphere.infra.util.yaml.representer.ShardingSphereYamlRepresenter.<init>(ShardingSphereYamlRepresenter.java:42)
	at org.apache.shardingsphere.infra.util.yaml.YamlEngine.marshal(YamlEngine.java:113)
	at org.apache.shardingsphere.mode.metadata.persist.service.config.global.PropertiesPersistService.persist(PropertiesPersistService.java:45)
	at org.apache.shardingsphere.mode.metadata.persist.service.config.global.PropertiesPersistService.conditionalPersist(PropertiesPersistService.java:39)
	at org.apache.shardingsphere.mode.metadata.persist.MetaDataPersistService.persistConfigurations(MetaDataPersistService.java:86)
	at org.apache.shardingsphere.mode.manager.standalone.StandaloneContextManagerBuilder.persistConfigurations(StandaloneContextManagerBuilder.java:61)
	at org.apache.shardingsphere.mode.manager.standalone.StandaloneContextManagerBuilder.build(StandaloneContextManagerBuilder.java:50)
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.createContextManager(ShardingSphereDataSource.java:77)
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.<init>(ShardingSphereDataSource.java:65)
	at org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactory.createDataSource(ShardingSphereDataSourceFactory.java:93)
	at org.apache.shardingsphere.driver.api.yaml.YamlShardingSphereDataSourceFactory.createDataSource(YamlShardingSphereDataSourceFactory.java:153)
	at org.apache.shardingsphere.driver.api.yaml.YamlShardingSphereDataSourceFactory.createDataSource(YamlShardingSphereDataSourceFactory.java:95)
	at org.apache.shardingsphere.driver.jdbc.core.driver.DriverDataSourceCache.createDataSource(DriverDataSourceCache.java:51)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.apache.shardingsphere.driver.jdbc.core.driver.DriverDataSourceCache.get(DriverDataSourceCache.java:45)
	at org.apache.shardingsphere.driver.ShardingSphereDriver.connect(ShardingSphereDriver.java:51)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:160)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:118)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81)
	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:80)
	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:67)
	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:348)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:89)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:64)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:336)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:158)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:81)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:59)
	at jdk.proxy2/jdk.proxy2.$Proxy100.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:154)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:142)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:425)
	at jdk.proxy2/jdk.proxy2.$Proxy84.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:164)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:77)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:152)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at jdk.proxy2/jdk.proxy2.$Proxy88.selectList(Unknown Source)

yaml config_info

![image](https://github.com/apache/shardingsphere/assets/19649240/ab90b5d5-3e18-447e-9063-6bd556f6c68a)

version info:
    SpringB Version : 3.1.4
    JDK : jdk21
    snakeyaml : 2.2
    shardingsphere-jdbc-core: 5.4.1
    mybatis-plus-spring-boot3-starter : 3.5.5

**Comment by linghengqian** [comment]
- Fixed in #28805.

**Comment by chrismayday** [comment]
> * 在[将 ElasticJob 更新到 3.0.4 中进行了修复，以阻止 SnakeYAML 交付的 CVE  #28805](https://github.com/apache/shardingsphere/pull/28805)。

![image](https://github.com/apache/shardingsphere/assets/19649240/c2f546d7-127a-41de-ad70-62f9cc3664cd)
是否这样引入就行了

**Comment by linghengqian** [comment]
- The answer is that it doesn't make sense. shardingsphere uses methods that were removed in snakeyaml 2.0. So you have to either downgrade to snakeyaml 1.33 or manually compile the shardingsphere master branch. See https://github.com/apache/shardingsphere/issues/30318#issuecomment-2002341706 .

**Comment by linghengqian** [comment]
- In short, you can try explicitly specifying the snakeyaml version in maven. The 3.0.x branch of spring-boot retains some unit tests for serving snakeyaml 1.33.

```xml
<dependency>
    <groupId>org.yaml</groupId>
    <artifactId>snakeyaml</artifactId>
    <version>1.33</version>
</dependency>
```

**Comment by chrismayday** [comment]
> * In short, you can try explicitly specifying the snakeyaml version in maven. The 3.0.x branch of spring-boot retains some unit tests for serving snakeyaml 1.33.
> 
> ```
> <dependency>
>     <groupId>org.yaml</groupId>
>     <artifactId>snakeyaml</artifactId>
>     <version>1.33</version>
> </dependency>
> ```

OK。Will it be fixed in version 5.4.2?

**Comment by linghengqian** [comment]
- With snakeyaml 2.2 in shardingsphere 5.4.2-SNAPSHOT/5.5.0, there is no need to explicitly specify the snakeyaml version, unless you are using third-party dependencies that are using the deleted snakeyaml java api.

**Comment by chrismayday** [comment]
> * 对于shardingsphere 5.4.2-SNAPSHOT/5.5.0中的snakeyaml 2.2，无需显式指定snakeyaml版本，除非您使用的第三方依赖项正在使用已删除的snakeyaml java api。
![image](https://github.com/apache/shardingsphere/assets/19649240/b0f31f0c-f929-4dc4-8edd-6a89ce6db7a3)
![image](https://github.com/apache/shardingsphere/assets/19649240/abeaa6d0-5691-4a48-981f-5126ad4786a5)
![image](https://github.com/apache/shardingsphere/assets/19649240/f9ef92c0-ac40-4707-b2a3-a55907bfae9e)
I would like to ask what is causing this problem. Is it a configuration problem?
grateful

**Comment by linghengqian** [comment]
- Without an example git with unit tests, I have a hard time understanding the picture, and I don't have an ocr tool to identify logs to text. I suggest you rewrite the unit tests to h2database or testcontainers-java, and open a new issue.

**Comment by chrismayday** [comment]
> * 如果没有带有单元测试的示例 git，我很难理解图片，而且我没有 ocr 工具来识别日志到文本。我建议你将单元测试重写为 h2database 或 testcontainers-java，并打开一个新问题。

https://github.com/chrismayday/demo-sharding/blob/main/src/test/java/com/example/demo/DemoApplicationTests.java
Under this demo project
grateful

**Comment by linghengqian** [comment]
- You need to provide the SQL file that initializes the database and remove the suspicious jdbcURL. Referring to the documentation for testcontainers-java or h2database, this looks like an external issue.

**Comment by chrismayday** [comment]
> * You need to provide the SQL file that initializes the database and remove the suspicious jdbcURL. Referring to the documentation for testcontainers-java or h2database, this looks like an external issue.
Here is the initialization SQL file
https://github.com/chrismayday/demo-sharding/blob/main/db/init.sql

**Comment by linghengqian** [comment]
- I must admit I kind of don't understand what you're doing. So I made some assumptions at https://github.com/linghengqian/demo-sharding/commit/98181ab258317d74cbe11cb67a82317bcfff0137 to fix the unit tests.
1. Your `rules[1].tables.analytics_event.actualDataNodes` is not a legal GroovyShell expression, it looks like there is an extra `}`. Refer to https://shardingsphere.apache.org/document/current/en/user-manual/common-config/builtin-algorithm/expr/ .
2. Your `rules[1].shardingAlgorithms.analytics_event_inline.props.algorithm-expression` seems to expect to continue to configure the `Sharding` table on the `logical database` configured with `Read/write splitting`, but the context of `algorithm-expression` actually only knows `actual table` name, it doesn't know the `logical or actual database` name. You can try debugging into the algorithm class.

**Comment by chrismayday** [comment]
> * 我必须承认我有点不明白你在做什么。所以我在[linghengqian/demo-sharding@ 98181ab](https://github.com/linghengqian/demo-sharding/commit/98181ab258317d74cbe11cb67a82317bcfff0137)做了一些假设来修复单元测试。
> 
> 1. 您的`rules[1].tables.analytics_event.actualDataNodes`不是合法的 GroovyShell 表达式，看起来有一个额外的`}`.请参阅https://shardingsphere.apache.org/document/current/en/user-manual/common-config/builtin-algorithm/expr/。
> 2. 您`rules[1].shardingAlgorithms.analytics_event_inline.props.algorithm-expression`似乎期望继续在配置的`Sharding`表上配置表，但上下文实际上只知道名称，它不知道名称。您可以尝试调试算法类。`logical database``Read/write splitting``algorithm-expression``actual table``logical or actual database`

ok ,solved
Thank you so much

**Comment by James-Zou** [comment]
> * With snakeyaml 2.2 in shardingsphere 5.4.2-SNAPSHOT/5.5.0, there is no need to explicitly specify the snakeyaml version, unless you are using third-party dependencies that are using the deleted snakeyaml java api.

When was version 5.4.2 released?

**Comment by linghengqian** [comment]
> When was version 5.4.2 released?

- If you expect a faster release, you should leave a message in the mail thread at https://lists.apache.org/thread/0kwvkzclnhn312vjlcyyr02md995yfv9 .

- As a committer, I personally only have non-binding release voting right. In any case, according to ASF regulations, the release process must be completed on the mailing list, which has nothing to do with github.com.

**Comment by linghengqian** [comment]
Closed due to no response.
