### ISSUE TITLE
How to start Native test for jdbc-encrypt

### ISSUE THREAD

**Issue by zzyReal666** [apache/shardingsphere#30829]
## Question

How to start Native test for jdbc-encrypt?

- If I want to test a Mysql database, do I need to create the database myself and initialize the data?
-  I can't find the configuration file mentioned in the documentation.

   doc address : https://shardingsphere.apache.org/document/current/cn/test-manual/integration-test/  
<img width="1461" alt="image" src="https://github.com/apache/shardingsphere/assets/34822229/c2263c6f-5834-4a18-906a-af6ebd77550b">

![image](https://github.com/apache/shardingsphere/assets/34822229/91cf2324-45c4-4566-9e71-3cc33caf3da1)

**Comment by zzyReal666** [comment]
### Now the path of the engine is :
`test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type`,but when I run `GeneralDQLE2EIT`,the following error occurs: 

`[ERROR] 2024-04-10 16:31:04.132 [main] o.a.s.t.e2e.framework.E2EExtension - Error case: jdbc: encrypt -> MySQL -> Literal -> SELECT * FROM t_merchant WHERE business_code LIKE CONCAT('%', ?, '%'), message: java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:212)
	at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:135)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:171)
	at org.testcontainers.DockerClientFactory$1.getDockerClient(DockerClientFactory.java:89)
	at com.github.dockerjava.api.DockerClientDelegate.authConfig(DockerClientDelegate.java:108)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:321)
	at org.apache.shardingsphere.test.e2e.env.container.atomic.DockerITContainer.start(DockerITContainer.java:49)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1249)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.apache.shardingsphere.test.e2e.env.container.atomic.ITContainers.start(ITContainers.java:83)
	at org.apache.shardingsphere.test.e2e.container.compose.mode.StandaloneContainerComposer.start(StandaloneContainerComposer.java:63)
	at org.apache.shardingsphere.test.e2e.engine.composer.E2EContainerComposer.<init>(E2EContainerComposer.java:69)
`

### This is my engine config :
![image](https://github.com/apache/shardingsphere/assets/34822229/73fbf105-6bc3-4315-8589-d2db2649c4f3)

### It seems like  @ #19396
