### ISSUE TITLE
5.4.1  CHAR_DIGEST_LIKE error

### ISSUE THREAD

**Issue by songcheng1658** [apache/shardingsphere#30871]
apache-shardingsphere-5.4.1-shardingsphere-proxy-bin

【config】
- !ENCRYPT
  encryptors:
    aes_encryptor:
      type: AES
      props:
        aes-key-value: 123456abc
    assisted_encryptor:
      type: MD5
    like_encryptor:
      type: CHAR_DIGEST_LIKE

【error】

Starting the ShardingSphere-Proxy ...
OpenJDK 64-Bit Server VM warning: JVM cannot use large page memory because it does not have enough privilege to lock pages in memory.
Exception in thread "main" org.apache.shardingsphere.infra.spi.exception.ServiceProviderNotFoundException: SPI-00001: No implementation class load from SPI `org.apache.shardingsphere.encrypt.spi.EncryptAlgorithm` with type `CHAR_DIGEST_LIKE`.
        at org.apache.shardingsphere.infra.spi.type.typed.TypedSPILoader.lambda$getService$1(TypedSPILoader.java:110)
        at java.base/java.util.Optional.orElseThrow(Optional.java:408)
        at org.apache.shardingsphere.infra.spi.type.typed.TypedSPILoader.getService(TypedSPILoader.java:110)
        at org.apache.shardingsphere.encrypt.rule.EncryptRule.lambda$new$0(EncryptRule.java:63)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at org.apache.shardingsphere.encrypt.rule.EncryptRule.<init>(EncryptRule.java:62)
        at org.apache.shardingsphere.encrypt.rule.builder.EncryptRuleBuilder.build(EncryptRuleBuilder.java:39)
        at org.apache.shardingsphere.encrypt.rule.builder.EncryptRuleBuilder.build(EncryptRuleBuilder.java:34)
        at org.apache.shardingsphere.infra.rule.builder.database.DatabaseRulesBuilder.build(DatabaseRulesBuilder.java:65)
        at org.apache.shardingsphere.infra.metadata.database.ShardingSphereDatabase.create(ShardingSphereDatabase.java:88)
        at org.apache.shardingsphere.metadata.factory.ExternalMetaDataFactory.createGenericDatabases(ExternalMetaDataFactory.java:85)
        at org.apache.shardingsphere.metadata.factory.ExternalMetaDataFactory.create(ExternalMetaDataFactory.java:72)
        at org.apache.shardingsphere.mode.metadata.NewMetaDataContextsFactory.create(NewMetaDataContextsFactory.java:97)
        at org.apache.shardingsphere.mode.metadata.NewMetaDataContextsFactory.create(NewMetaDataContextsFactory.java:71)
        at org.apache.shardingsphere.mode.manager.standalone.NewStandaloneContextManagerBuilder.build(NewStandaloneContextManagerBuilder.java:53)
        at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.createContextManager(BootstrapInitializer.java:68)
        at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.init(BootstrapInitializer.java:58)
        at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:55)

【exist 5.4.0】
https://github.com/apache/shardingsphere/blob/5.4.0/features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/algorithm/like/CharDigestLikeEncryptAlgorithm.java

【not exist 5.4.1】
https://github.com/apache/shardingsphere/blob/5.4.1/features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/algorithm/like/CharDigestLikeEncryptAlgorithm.java

why?

**Comment by strongduanmu** [comment]
You can find this plugin in ShardingSphere plugin repository.

**Comment by zzyReal666** [comment]
step1:   git clone  https://github.com/apache/shardingsphere-plugin.git 
 
step2:   maven clean install this project

step3:   add this project maven to your project maven pom file.

**Comment by strongduanmu** [comment]
Hi @zzyReal666, I see you've been active in the community lately, would you like to get more involved with ShardingSphere?

**Comment by strongduanmu** [comment]
@zzyReal666 That’s great, could you email me your contact details? For example wechat number, I'm going to give you some help.

**Comment by strongduanmu** [comment]
Since this question has been answered, I will close this issue.

**Comment by Lukeluhh** [comment]
> Since this question has been answered, I will close this issue.

Can you show the solution？
<img width="1088" alt="image" src="https://github.com/apache/shardingsphere/assets/32117260/0c55fe91-a8ba-4f37-ad48-1a7527d1ef33">

**Comment by zzyReal666** [comment]
> > Since this question has been answered, I will close this issue.
> 
> Can you show the solution？ <img alt="image" width="1088" src="https://private-user-images.githubusercontent.com/32117260/323556964-0c55fe91-a8ba-4f37-ad48-1a7527d1ef33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0ODcwNjYsIm5iZiI6MTcxMzQ4Njc2NiwicGF0aCI6Ii8zMjExNzI2MC8zMjM1NTY5NjQtMGM1NWZlOTEtYThiYS00ZjM3LWFkNDgtMWE3NTI3ZDFlZjMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDAwMzI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmZDhiYzI3ZjFkZDQ2NTYzZjZhNzI2NjA4ODYzODYzYmM0OTViNWFkODk0MTYwMGEwZWViZmJhZTI2N2YwMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H39EX2D2LCDsesHAkjKY0Zji9GbLZja9-0Gngah8g3k">

https://github.com/apache/shardingsphere/issues/30871#issuecomment-2058422588
