### ISSUE TITLE
5.4.1 Error while one physic table has two rules

### ISSUE THREAD

**Issue by guhuining** [apache/shardingsphere#30922]
### Which version of ShardingSphere did you use?
5.4.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
You can find the demo project here: [https://github.com/guhuining/shardingSphereIssue](https://github.com/guhuining/shardingSphereIssue)

In version 5.3.2, this code runs perfectly, the output is:
```
22:55:36.939 [main] INFO ShardingSphere-SQL - Logic SQL: SELECT * FROM test_ WHERE id = 1
22:55:36.939 [main] INFO ShardingSphere-SQL - Actual SQL: sharding_test ::: SELECT * FROM test_1 WHERE id = 1
22:55:36.962 [main] INFO ShardingSphere-SQL - Logic SQL: SELECT * FROM test_hint_
22:55:36.962 [main] INFO ShardingSphere-SQL - Actual SQL: sharding_test ::: SELECT * FROM test_2
```

As you can see, here is an actual data node which is "sharding_test.test_{0..4}" and it has two rules. 
One is named as "test_", which has a standard sharding algorithm.
Another is named as "test_hint_" which has a hint sharding algorithm.

```yaml
rules:
  - !SHARDING
    tables:
      test_:
        actualDataNodes: sharding_test.test_$->{0..4}
        tableStrategy:
          standard:
            shardingColumn: id
            shardingAlgorithmName: ModAlgorithm
      test_hint_:
        actualDataNodes: sharding_test.test_$->{0..4}
        tableStrategy:
          hint:
            shardingAlgorithmName: HintAlgorithm
      # Algorithm
    shardingAlgorithms:
      ModAlgorithm:
        type: CLASS_BASED
        props:
          strategy: standard
          algorithmClassName: com.demo.ModAlgorithm
      HintAlgorithm:
        type: CLASS_BASED
        props:
          strategy: hint
          algorithmClassName: com.demo.HintAlgorithm
props:
  sql-show: true
```

And there is two sql need to execute, the code is :

```java
ds.getConnection()
    .prepareStatement("SELECT * FROM test_ WHERE id = 1")
    .executeQuery();

try (HintManager hintManager = HintManager.getInstance()) {
    hintManager.addTableShardingValue("test_hint_", 2);
    ds.getConnection()
        .prepareStatement("SELECT * FROM test_hint_")
        .executeQuery();
}
```

In version 5.3.2, both these rules can work.

### Actual behavior
But if you change the version of shardingsphere to 5.4.1, this code will raise an error:
```
23:10:33.551 [main] INFO ShardingSphere-SQL - Logic SQL: SELECT * FROM test_ WHERE id = 1
23:10:33.552 [main] INFO ShardingSphere-SQL - Actual SQL: sharding_test ::: SELECT * FROM test_1 WHERE id = 1
Exception in thread "main" org.apache.shardingsphere.infra.exception.TableNotExistsException: Table or view `test_hint_` does not exist.
	at org.apache.shardingsphere.infra.binder.segment.from.impl.SimpleTableSegmentBinder.lambda$checkTableExists$4(SimpleTableSegmentBinder.java:146)
	at org.apache.shardingsphere.infra.exception.core.ShardingSpherePreconditions.checkState(ShardingSpherePreconditions.java:41)
	at org.apache.shardingsphere.infra.binder.segment.from.impl.SimpleTableSegmentBinder.checkTableExists(SimpleTableSegmentBinder.java:143)
	at org.apache.shardingsphere.infra.binder.segment.from.impl.SimpleTableSegmentBinder.bind(SimpleTableSegmentBinder.java:82)
	at org.apache.shardingsphere.infra.binder.segment.from.TableSegmentBinder.bind(TableSegmentBinder.java:54)
	at org.apache.shardingsphere.infra.binder.statement.dml.SelectStatementBinder.bind(SelectStatementBinder.java:56)
	at org.apache.shardingsphere.infra.binder.statement.dml.SelectStatementBinder.bind(SelectStatementBinder.java:46)
	at org.apache.shardingsphere.infra.binder.engine.SQLBindEngine.bindDMLStatement(SQLBindEngine.java:100)
	at org.apache.shardingsphere.infra.binder.engine.SQLBindEngine.bind(SQLBindEngine.java:80)
	at org.apache.shardingsphere.infra.binder.engine.SQLBindEngine.bind(SQLBindEngine.java:71)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.<init>(ShardingSpherePreparedStatement.java:202)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.<init>(ShardingSpherePreparedStatement.java:167)
	at org.apache.shardingsphere.driver.jdbc.core.connection.ShardingSphereConnection.prepareStatement(ShardingSphereConnection.java:83)
	at com.demo.Main.main(Main.java:29)
```

It seems that the logical table named "test_hint_" can't be got by shardingsphere. 
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
change the version 5.3.2 to 5.4.1, the error will occur.
### Example codes for reproduce this issue (such as a github link).
[https://github.com/guhuining/shardingSphereIssue](https://github.com/guhuining/shardingSphereIssue)

**Comment by TherChenYang** [comment]
change the version 5.3.2 to 5.4.1, the error will occur.

**Comment by terrymanu** [comment]
Thank you for reporting this issue. After analysis, this is not a ShardingSphere bug, but rather a configuration that doesn't comply with ShardingSphere's design principles.

##  Root Cause Analysis

  Your configuration violates ShardingSphere's core design principle: one sharded table can only have one sharding strategy.

  In your configuration:
```yaml
  test_:
    actualDataNodes: sharding_test.test_$->{0..4}
    tableStrategy:
      standard:
        shardingColumn: id
        shardingAlgorithmName: ModAlgorithm

  test_hint_:
    actualDataNodes: sharding_test.test_$->{0..4}  # Same physical table
    tableStrategy:
      hint:
        shardingAlgorithmName: HintAlgorithm
```

  You configured two different logical tables and sharding strategies for the same physical table sharding_test.test_{0..4}, which is incorrect usage.

##  Key Concepts

  1. Logical Table: One logical table should only have one sharding strategy
  2. HintManager: Used to specify sharding values at runtime, not to configure multiple strategies for the same table
  3. Physical Tables: The actual tables test_0, test_1, test_2, test_3, test_4

##  Version Differences

  From 5.3.2 to 5.4.1, stricter table existence validation was added, which exposed this configuration issue. This is a reasonable improvement that helps users identify configuration errors early.

  We recommend configuring according to ShardingSphere's design principles - one sharded table should use only one logical table name and one sharding strategy.
