### ISSUE TITLE
5.5.0 start failed

### ISSUE THREAD

**Issue by dobet** [apache/shardingsphere#31193]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.5.0 

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

start success

### Actual behavior

start failed 

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

bin/start.sh 3306 conf/

```
OpenJDK 64-Bit Server VM warning: Setting LargePageSizeInBytes has no effect on this OS. Large page size is 2048K.
OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 12)
OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 12)
OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 12)
Exception in thread "main" java.util.ServiceConfigurationError: org.apache.shardingsphere.infra.yaml.config.swapper.rule.YamlRuleConfigurationSwapper: Provider org.apache.shardingsphere.shadow.yaml.swapper.YamlShadowRuleConfigurationSwapper could not be instantiated
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:804)
        at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:722)
        at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1395)
        at org.apache.shardingsphere.infra.spi.RegisteredShardingSphereSPI.load(RegisteredShardingSphereSPI.java:52)
        at org.apache.shardingsphere.infra.spi.RegisteredShardingSphereSPI.<init>(RegisteredShardingSphereSPI.java:42)
        at org.apache.shardingsphere.infra.spi.ShardingSphereServiceLoader.getRegisteredSPI(ShardingSphereServiceLoader.java:59)
        at org.apache.shardingsphere.infra.spi.ShardingSphereServiceLoader.getServiceInstances(ShardingSphereServiceLoader.java:46)
        at org.apache.shardingsphere.infra.yaml.config.shortcut.YamlRuleConfigurationShortcuts.getYamlShortcuts(YamlRuleConfigurationShortcuts.java:39)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1239)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at org.apache.shardingsphere.infra.util.yaml.constructor.ShardingSphereYamlConstructor.<init>(ShardingSphereYamlConstructor.java:45)
        at org.apache.shardingsphere.infra.util.yaml.YamlEngine.unmarshal(YamlEngine.java:56)
        at org.apache.shardingsphere.proxy.backend.config.ProxyConfigurationLoader.loadServerConfiguration(ProxyConfigurationLoader.java:104)
        at org.apache.shardingsphere.proxy.backend.config.ProxyConfigurationLoader.load(ProxyConfigurationLoader.java:84)
        at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:52)
Caused by: java.lang.NoClassDefFoundError: org/apache/shardingsphere/infra/algorithm/core/yaml/YamlAlgorithmConfigurationSwapper
        at org.apache.shardingsphere.shadow.yaml.swapper.YamlShadowRuleConfigurationSwapper.<init>(YamlShadowRuleConfigurationSwapper.java:40)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:780)
        ... 20 more
Caused by: java.lang.ClassNotFoundException: org.apache.shardingsphere.infra.algorithm.core.yaml.YamlAlgorithmConfigurationSwapper
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 26 more
```

**Comment by LuckJcr** [comment]
I have the same problem. How did you solve it

**Comment by CV-Devlau** [comment]
I encountered the same problem, how was it solved

**Comment by penghuazhou** [comment]
@CV-Devlau Do you solve it?

**Comment by penghuazhou** [comment]
@terrymanu Do need to support hugepages?

```
sudo tee -a /etc/sysctl.conf << EOF

vm.nr_hugepages = 512
vm.hugetlb_shm_group = 0      
# vm.nr_overcommit_hugepages = 256  
EOF

sudo sysctl -p

sudo grep Huge /proc/meminfo
```
