### ISSUE TITLE
oracle interval keyword parser failed, throw NoViableAltException

### ISSUE THREAD

**Issue by xigongxiaoche** [apache/shardingsphere#31236]
## Bug Report
  oracle sql parse failed,  but the failed sql can execute in oracle, the failed sql is vaild in antlr rule 
```
failed sql: 
select age from (select '0-1岁' age,count(*) countNum, '0' sortNum from T_EMPI_PATIENT_INFO t where t.birth > to_char((sysdate - interval '1' year(3)), 'yyyymmdd'))
success sql:
select '0-1岁' age,count(*) countNum, '0' sortNum from T_EMPI_PATIENT_INFO t where t.birth > to_char((sysdate - interval '1' year(3)), 'yyyymmdd')
select age from (select '0-1岁' age,count(*) countNum, '0' sortNum from T_EMPI_PATIENT_INFO t)
```

## version
shardingsphere version: 5.3.2
oracle verion: oracle 11g

## stacktrace
```
Exception in thread "main" org.apache.shardingsphere.sql.parser.exception.SQLParsingException: You have an error in your SQL syntax: select age from (select '0-1岁' age,count(*) countNum, '0' sortNum from T_EMPI_PATIENT_INFO t where t.birth > to_char((sysdate - interval '1' year(3)), 'yyyymmdd')), no viable alternative at input 'selectagefrom(select'0-1岁'age,count(*)countNum,'0'sortNumfromT_EMPI_PATIENT_INFOtwheret.birth>to_char((sysdate-interval'1'' at line 1, position 137, near [@30,137:139=''1'',<1001>,1:137]
	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.twoPhaseParse(SQLParserExecutor.java:70)
	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.parse(SQLParserExecutor.java:49)
	at org.apache.shardingsphere.sql.parser.api.SQLParserEngine.parse(SQLParserEngine.java:47)
	at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserExecutor.parse(SQLStatementParserExecutor.java:48)
	at org.apache.shardingsphere.infra.parser.cache.SQLStatementCacheLoader.load(SQLStatementCacheLoader.java:41)
	at org.apache.shardingsphere.infra.parser.cache.SQLStatementCacheLoader.load(SQLStatementCacheLoader.java:30)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$2(LocalLoadingCache.java:145)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2406)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2404)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2387)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:56)
	at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserEngine.parse(SQLStatementParserEngine.java:47)
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine.parse(ShardingSphereSQLParserEngine.java:58)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.<init>(ShardingSpherePreparedStatement.java:205)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.<init>(ShardingSpherePreparedStatement.java:171)
	at org.apache.shardingsphere.driver.jdbc.core.connection.ShardingSphereConnection.prepareStatement(ShardingSphereConnection.java:87)
```

**Comment by TherChenYang** [comment]
@xigongxiaoche Thank you for your feedback, I will check on this issue.

**Comment by xigongxiaoche** [comment]
can you give me some suggestion to solve the bug?

**Comment by xigongxiaoche** [comment]
At first I think it it because of sysdate keyword not in the antlr rule of 5.3.2 oracle. I add keyword sysdate, but it is invalid

**Comment by TherChenYang** [comment]
Hi @xigongxiaoche, can you test with master branch? After testing, the following SQL statement can be parsed correctly in the master.

```sql
select
    age
from
    (
        select
            '0-1岁'   age
          , count(*) countNum
          , '0'      sortNum
        from
            T_EMPI_PATIENT_INFO t
        where
            t.birth > to_char((sysdate - interval '1' year(3)), 'yyyymmdd')
    )
```

**Comment by xigongxiaoche** [comment]
Ok, I'll try it

**Comment by TherChenYang** [comment]
@xigongxiaoche You claim there are obvious errors here, the WHERE clause is in the subquery; the correct assertion should be
```xml
<select sql-case-id="select_interval_with_subquery">
        <projections start-index="7" stop-index="9">
            <column-projection name="age" start-index="7" stop-index="9"/>
        </projections>
        <from>
            <subquery-table>
                <subquery>
                    <select>
                        <projections start-index="24" stop-index="64">
                            <expression-projection text="0-1岁" start-index="24" stop-index="33" alias="age"/>
                            <aggregation-projection type="COUNT" start-index="35" stop-index="42" expression="count(*)" alias="countNum"/>
                            <expression-projection text="0" start-index="54" stop-index="64" alias="sortNum"/>
                        </projections>
                        <from start-index="71" stop-index="91">
                            <simple-table name="T_EMPI_PATIENT_INFO" start-index="71" stop-index="91" alias="t"/>
                        </from>
                        <where start-index="93" stop-index="161">
                            <expr>
                                <binary-operation-expression start-index="99" stop-index="161">
                                    <operator>&gt;</operator>
                                    <left>
                                        <column name="birth" start-index="99" stop-index="105">
                                            <owner name="t" start-index="99" stop-index="99"/>
                                        </column>
                                    </left>
                                    <right>
                                        <function text="to_char((sysdate - interval '1' year(3)), 'yyyymmdd')" function-name="to_char" start-index="109" stop-index="161">
                                            <parameter>
                                                <binary-operation-expression start-index="118" stop-index="147">
                                                    <operator>-</operator>
                                                    <left>
                                                        <column name="sysdate" start-index="118" stop-index="124"/>
                                                    </left>
                                                    <right>
                                                        <common-expression text="interval '1' year(3)" start-index="128" stop-index="147"/>
                                                    </right>
                                                </binary-operation-expression>
                                            </parameter>
                                            <parameter>
                                                <literal-expression value="yyyymmdd" start-index="151" stop-index="160"/>
                                            </parameter>
                                        </function>
                                    </right>
                                </binary-operation-expression>
                            </expr>
                        </where>
                    </select>
                </subquery>
            </subquery-table>
        </from>
    </select>
```

**Comment by xigongxiaoche** [comment]
I changed the select tag as follows, but it still failed.
```
    <select sql-case-id="select_interval_with_subquery">
        <projections start-index="7" stop-index="9">
            <column-projection name="age" start-index="7" stop-index="9"/>
        </projections>
        <from>
            <subquery-table>
                <subquery>
                    <select>
                        <projections start-index="24" stop-index="64">
                            <expression-projection text="0-1岁" start-index="24" stop-index="33" alias="age"/>
                            <aggregation-projection type="COUNT" start-index="35" stop-index="51" expression="count(*)" alias="countNum"/>
                            <expression-projection text="0" start-index="54" stop-index="64" alias="sortNum"/>
                        </projections>
                        <from start-index="71" stop-index="91">
                            <simple-table name="T_EMPI_PATIENT_INFO" start-index="71" stop-index="91" alias="t"/>
                        </from>
                        <where start-index="93" stop-index="161">
                            <expr>
                                <binary-operation-expression start-index="99" stop-index="161">
                                    <operator>&gt;</operator>
                                    <left>
                                        <column name="birth" start-index="99" stop-index="105">
                                            <owner name="t" start-index="99" stop-index="99"/>
                                        </column>
                                    </left>
                                    <right>
                                        <function text="to_char((sysdate - interval '1' year(3)), 'yyyymmdd')" function-name="to_char" start-index="109" stop-index="161">
                                            <parameter>
                                                <binary-operation-expression start-index="117" stop-index="148">
                                                    <operator>-</operator>
                                                    <left>
                                                        <column name="sysdate" start-index="118" stop-index="124"/>
                                                    </left>
                                                    <right>
                                                        <common-expression text="interval '1' year(3)" start-index="128" stop-index="147"/>
                                                    </right>
                                                </binary-operation-expression>
                                            </parameter>
                                            <parameter>
                                                <literal-expression value="yyyymmdd" start-index="152" stop-index="159"/>
                                            </parameter>
                                        </function>
                                    </right>
                                </binary-operation-expression>
                            </expr>
                        </where>
                    </select>
                </subquery>
            </subquery-table>
        </from>
    </select>
    <sql-case id="select_interval_with_subquery" value="select age from (select '0-1岁' age,count(*) countNum, '0' sortNum from T_EMPI_PATIENT_INFO t where t.birth &gt; to_char((sysdate - interval '1' year(3)), 'yyyymmdd'))" db-types="Oracle"  />
```

console failed message:
```
java.lang.AssertionError: 
SQL Case ID : select_interval_with_subquery
SQL         : select age from (select '0-1岁' age,count(*) countNum, '0' sortNum from T_EMPI_PATIENT_INFO t where t.birth > to_char((sysdate - interval '1' year(3)), 'yyyymmdd'))
`SubqueryTableSegment`'s start index assertion error: 

Expected: is <0>
     but: was <16>
<Click to see difference>


	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.apache.shardingsphere.test.it.sql.parser.internal.asserts.segment.SQLSegmentAssert.assertStartIndex(SQLSegmentAssert.java:50)
	at org.apache.shardingsphere.test.it.sql.parser.internal.asserts.segment.SQLSegmentAssert.assertIs(SQLSegmentAssert.java:44)
	at org.apache.shardingsphere.test.it.sql.parser.internal.asserts.segment.table.TableAssert.assertIs(TableAssert.java:170)
	at org.apache.shardingsphere.test.it.sql.parser.internal.asserts.segment.table.TableAssert.assertIs(TableAssert.java:81)
	at org.apache.shardingsphere.test.it.sql.parser.internal.asserts.statement.dml.impl.SelectStatementAssert.assertTable(SelectStatementAssert.java:115)
	at org.apache.shardingsphere.test.it.sql.parser.internal.asserts.statement.dml.impl.SelectStatementAssert.assertIs(SelectStatementAssert.java:76)
	at org.apache.shardingsphere.test.it.sql.parser.internal.asserts.statement.dml.DMLStatementAssert.assertIs(DMLStatementAssert.java:71)
	at org.apache.shardingsphere.test.it.sql.parser.internal.asserts.statement.SQLStatementAssert.assertIs(SQLStatementAssert.java:70)
	at org.apache.shardingsphere.test.it.sql.parser.internal.InternalSQLParserIT.assertSupportedSQL(InternalSQLParserIT.java:58)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by TherChenYang** [comment]
@xigongxiaoche This is just a standard format of an assertion. You need to supplement start-Index and stop-Index according to your SQL, which is not related to SQL parsing itself. This is just for testing.

**Comment by xigongxiaoche** [comment]
According to your advice, my unit tests passed on 5.4.1 and master. Thank you very much.
According to your advice, my unit tests passed on 5.4.1 and master. Thank you very much.
sql case:
```
    <select sql-case-id="select_interval_with_subquery">
        <projections start-index="7" stop-index="9">
            <column-projection name="age" start-index="7" stop-index="9"/>
        </projections>
        <from>
            <subquery-table start-index="16" stop-index="162">
                <subquery>
                    <select>
                        <projections start-index="24" stop-index="64">
                            <expression-projection text="0-1岁" start-index="24" stop-index="33" alias="age"/>
                            <aggregation-projection type="COUNT" start-index="35" stop-index="42" expression="count(*)" alias="countNum"/>
                            <expression-projection text="0" start-index="54" stop-index="64" alias="sortNum"/>
                        </projections>
                        <from start-index="71" stop-index="91">
                            <simple-table name="T_EMPI_PATIENT_INFO" start-index="71" stop-index="91" alias="t"/>
                        </from>
                        <where start-index="93" stop-index="161">
                            <expr>
                                <binary-operation-expression start-index="99" stop-index="161">
                                    <operator>&gt;</operator>
                                    <left>
                                        <column name="birth" start-index="99" stop-index="105">
                                            <owner name="t" start-index="99" stop-index="99"/>
                                        </column>
                                    </left>
                                    <right>
                                        <function text="to_char((sysdate - interval '1' year(3)), 'yyyymmdd')" function-name="to_char" start-index="109" stop-index="161">
                                            <parameter>
                                                <binary-operation-expression start-index="118" stop-index="147">
                                                    <operator>-</operator>
                                                    <left>
                                                        <column name="sysdate" start-index="118" stop-index="124"/>
                                                    </left>
                                                    <right>
                                                        <common-expression text="interval '1' year(3)" start-index="128" stop-index="147"/>
                                                    </right>
                                                </binary-operation-expression>
                                            </parameter>
                                            <parameter>
                                                <literal-expression value="yyyymmdd" start-index="151" stop-index="160"/>
                                            </parameter>
                                        </function>
                                    </right>
                                </binary-operation-expression>
                            </expr>
                        </where>
                    </select>
                </subquery>
            </subquery-table>
        </from>
    </select>
    <sql-case id="select_interval_with_subquery" value="select age from (select '0-1岁' age,count(*) countNum, '0' sortNum from T_EMPI_PATIENT_INFO t where t.birth &gt; to_char((sysdate - interval '1' year(3)), 'yyyymmdd'))" db-types="Oracle"  />
```

**Comment by xigongxiaoche** [comment]
This bug only occurs in version 5.3.2., version 5.4.1 and master all passed

**Comment by xigongxiaoche** [comment]
Currently, I am using version 5.3.2. If I want to address this bug based on this version, could you please inform me which parts need to be modified? Presently, my understanding is that the file requiring modification is sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4. @TherChenYang

**Comment by TherChenYang** [comment]
@xigongxiaoche You can refer to this link for processing. [parser module](https://mp.weixin.qq.com/s/p1ESy2YKEfyX3Rc6o2eFhw)

The main parts that need to be modified
- Oracle related g4 files
- oracle related visitor

**Comment by xigongxiaoche** [comment]
Thank you very much

**Comment by xigongxiaoche** [comment]
After 5.3.2 oracle BaseRule.g4, the bug fixed
