### ISSUE TITLE
使用5.5.0版本出现org.yaml.snakeyaml.LoaderOptions.setCodePointLimit(I)V

### ISSUE THREAD

**Issue by zhousennan** [apache/shardingsphere#31324]
## Question

使用5.5.0版本,报错

java.lang.NoSuchMethodError: org.yaml.snakeyaml.LoaderOptions.setCodePointLimit(I)V
	at org.apache.shardingsphere.infra.util.yaml.constructor.ShardingSphereYamlConstructor.createLoaderOptions(ShardingSphereYamlConstructor.java:53) ~[shardingsphere-infra-util-5.5.0.jar:5.5.0]
	at org.apache.shardingsphere.infra.util.yaml.constructor.ShardingSphereYamlConstructor.<init>(ShardingSphereYamlConstructor.java:42) ~[shardingsphere-infra-util-5.5.0.jar:5.5.0]
	at org.apache.shardingsphere.infra.util.yaml.YamlEngine.unmarshal(YamlEngine.java:73) ~[shardingsphere-infra-util-5.5.0.jar:5.5.0]

## 解决办法
升级yml依赖
<dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
            <version>1.33</version>
       </dependency>

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
