### ISSUE TITLE
5.4.1版本使用mariadb数据库时，连接提示Can not find builder rule: `MariaDB.shardingsphere`

### ISSUE THREAD

**Issue by zhengfengxu** [apache/shardingsphere#31345]
我使用的是shardingsphere 5.4.1版本，数据库是mariadb
配置文件截图

![c3e2119724b43c9f24e81b412787866](https://github.com/apache/shardingsphere/assets/55429967/01ece3b5-3c1b-4d50-b10a-f75635ece056)

程序具体错误信息：
2024-05-22 17:41:49.499  WARN 25220 --- [)-172.16.100.71] o.s.b.a.jdbc.DataSourceHealthIndicator   : DataSource health check failed

com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Can not find builder rule: `MariaDB.shardingsphere`
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-4.0.3.jar:na]
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159) ~[spring-jdbc-5.3.25.jar:5.3.25]
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117) ~[spring-jdbc-5.3.25.jar:5.3.25]
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80) ~[spring-jdbc-5.3.25.jar:5.3.25]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:330) ~[spring-jdbc-5.3.25.jar:5.3.25]
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.getProduct(DataSourceHealthIndicator.java:122) ~[spring-boot-actuator-2.7.9.jar:2.7.9]
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doDataSourceHealthCheck(DataSourceHealthIndicator.java:105) ~[spring-boot-actuator-2.7.9.jar:2.7.9]
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doHealthCheck(DataSourceHealthIndicator.java:100) ~[spring-boot-actuator-2.7.9.jar:2.7.9]
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82) ~[spring-boot-actuator-2.7.9.jar:2.7.9]
	at org.springframework.boot.actuate.health.HealthIndicator.getHealth(HealthIndicator.java:37) [spring-boot-actuator-2.7.9.jar:2.7.9]
	at org.springframework.boot.actuate.health.HealthEndpoint.getHealth(HealthEndpoin

如果是换为mysql的驱动，可以正常启动，但插入的数据会乱码

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
