### ISSUE TITLE
shardingsphere proxy execte group by sql throw exception

### ISSUE THREAD

**Issue by peiyongbin** [apache/shardingsphere#31342]
Hi friend，when execte group by sql in shardingsphere proxy v5.2.1，throw a exception，please help me. tks

The t_order  is logical table, range is 0~4095 。

db_xxx=> select state  from  t_order where update_time between now() - interval '1 min' and now() and state <>3 ;
    state
---------
        1
        1
(2 行记录)

db_xxx=>
db_xxx=> select state,count(1) as cnt  from  t_order where update_time between now() - interval '1 min' and now() and state <>3 group by state;
ERROR:  java.lang.NullPointerException

the log file is like:

tail -n 50 /opt/apache-shardingsphere-5.2.1-shardingsphere-proxy-bin/logs/stdout.log

[ERROR] 2024-05-22 16:42:23.797 [Connection-2-ThreadExecutor] o.a.s.p.f.c.CommandExecutorTask - Exception occur:
java.lang.NullPointerException: null
        at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.getOrderValuesCaseSensitiveFromTables(OrderByValue.java:74)
        at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.getOrderValuesCaseSensitive(OrderByValue.java:64)
        at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.<init>(OrderByValue.java:58)
        at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByStreamMergedResult.orderResultSetsToQueue(OrderByStreamMergedResult.java:56)
        at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByStreamMergedResult.<init>(OrderByStreamMergedResult.java:50)
        at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByStreamMergedResult.<init>(GroupByStreamMergedResult.java:52)
        at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.getGroupByMergedResult(ShardingDQLResultMerger.java:118)
        at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.build(ShardingDQLResultMerger.java:88)
        at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.merge(ShardingDQLResultMerger.java:66)
        at org.apache.shardingsphere.infra.merge.MergeEngine.executeMerge(MergeEngine.java:82)
        at org.apache.shardingsphere.infra.merge.MergeEngine.merge(MergeEngine.java:71)
        at org.apache.shardingsphere.proxy.backend.communication.DatabaseCommunicationEngine.mergeQuery(DatabaseCommunicationEngine.java:174)
        at org.apache.shardingsphere.proxy.backend.communication.DatabaseCommunicationEngine.processExecuteQuery(DatabaseCommunicationEngine.java:140)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:134)
        at org.apache.shardingsphere.proxy.frontend.postgresql.command.query.simple.PostgreSQLComQueryExecutor.execute(PostgreSQLComQueryExecutor.java:76)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:111)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by terrymanu** [comment]
The markdown format in your issue is incorrect. To facilitate reading, could you please revise it?
