### ISSUE TITLE
When using the mariadb database in version 5.4.1, the connection prompt is Can not find builder rule: `MariaDB.shardingsphere`

### ISSUE THREAD

**Issue by zhengfengxu** [apache/shardingsphere#31358]
I am using shardingsphere version 5.4.1 and the database is mariadb.
Screenshot of configuration file:
![c3e2119724b43c9f24e81b412787866](https://github.com/apache/shardingsphere/assets/55429967/203209b8-1067-4fed-b915-77b1f5f142e2)
Program specific error information:
2024-05-22 17:41:49.499  WARN 25220 --- [)-172.16.100.71] o.s.b.a.jdbc.DataSourceHealthIndicator   : DataSource health check failed

com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Can not find builder rule: `MariaDB.shardingsphere`
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-4.0.3.jar:na]
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159) ~[spring-jdbc-5.3.25.jar:5.3.25]
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117) ~[spring-jdbc-5.3.25.jar:5.3.25]
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80) ~[spring-jdbc-5.3.25.jar:5.3.25]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:330) ~[spring-jdbc-5.3.25.jar:5.3.25]
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.getProduct(DataSourceHealthIndicator.java:122) ~[spring-boot-actuator-2.7.9.jar:2.7.9]
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doDataSourceHealthCheck(DataSourceHealthIndicator.java:105) ~[spring-boot-actuator-2.7.9.jar:2.7.9]
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doHealthCheck(DataSourceHealthIndicator.java:100) ~[spring-boot-actuator-2.7.9.jar:2.7.9]
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82) ~[spring-boot-actuator-2.7.9.jar:2.7.9]
	at org.springframework.boot.actuate.health.HealthIndicator.getHealth(HealthIndicator.java:37) [spring-boot-actuator-2.7.9.jar:2.7.9]
	at org.springframework.boot.actuate.health.HealthEndpoint.getHealth(HealthEndpoin
If the driver is changed to MySQL, it can start normally, but the inserted data will be garbled

**Comment by TherChenYang** [comment]
@zhengfengxu Thank you for your feedback, but I cannot find any relevant configurations about ShardingSphere in your configuration file. Please provide more detailed configurations and usage so that we can solve the problem faster.

**Comment by zhangxuh** [comment]
I met same problem，my yaml configuration is
![image](https://github.com/apache/shardingsphere/assets/19343372/56c6863d-5796-4aac-bf04-753a066d4e51)
![image](https://github.com/apache/shardingsphere/assets/19343372/f33bdeb1-03c0-4de3-9803-e05922365f3b)

then give me an error:
![image](https://github.com/apache/shardingsphere/assets/19343372/4dc4dec7-bcb8-47cc-bda6-567dc4c67a2e)


when I  read the source code，I Found  that the SCHEMA_PATH_SYSTEM_SCHEMA_BUILDER_RULE_MAP only support
MYSQL_SHARDING_SPHERE、POSTGRESQL_SHARDING_SPHERE、OPEN_GAUSS_SHARDING_SPHERE

Did you provide support for Mariadb?


![image](https://github.com/apache/shardingsphere/assets/19343372/3e50b2c3-1ee6-45bb-b33f-0f86642c6244)

**Comment by zhangxuh** [comment]
Did it close without a response?

**Comment by matkwiatkowski** [comment]
I have the same issue. 
I was considering either changing the DB to MySQL (a lot of work, I wanted to avoid that) or adding a new record to SCHEMA_PATH_SYSTEM_SCHEMA_BUILDER_RULE_MAP using reflection. After a couple of tries, what worked for me was changing the URL to use mysql instead of mariadb: jdbc:mariadb://0.0.0.0:33022/vcemDataSource to jdbc:mysql://0.0.0.0:33022/dataSource. I know this is not ideal, however, it seems to be working fine as of right now. Hopefully, this will be fixed in newer versions. The highest version that I was able to check was 5.4.1 at the time, since there was no higher version of shardingsphere-jdbc-core available in Maven Central.
