### ISSUE TITLE
oracle not support batch update

### ISSUE THREAD

**Issue by xigongxiaoche** [apache/shardingsphere#31683]
### batch update sql is not support in shardingsphere, it report sql systax error
sharingsphere jdbc version:5.3.2
oracle version: 11g
sql:
```
begin 
update 
  T_EMPI_RULE_MATCH_GROUP 
set 
  status = '1', 
  BUILD_WAY = '0', 
  UPDATE_BY = '1', 
  priority = 10, 
  UPDATE_TIME = to_char(
    sysdate, 'yyyy-MM-dd hh24:mi:ss'
  ) 
where 
  rule_type = '0' 
  and id = '922B5C5CE166466D9505BFCE592D461C'; 
update 
  T_EMPI_RULE_MATCH_GROUP 
set 
  status = '1', 
  BUILD_WAY = '0', 
  UPDATE_BY = '1', 
  priority = 15, 
  UPDATE_TIME = to_char(
    sysdate, 'yyyy-MM-dd hh24:mi:ss'
  ) 
where 
  rule_type = '0' 
  and id = '3953BD247C2B49818F533DEC8ADE48BB'; 
update 
  T_EMPI_RULE_MATCH_GROUP 
set 
  status = '1', 
  BUILD_WAY = '0', 
  UPDATE_BY = '1', 
  priority = 20, 
  UPDATE_TIME = to_char(
    sysdate, 'yyyy-MM-dd hh24:mi:ss'
  ) 
where 
  rule_type = '0' 
  and id = '8F22D1F686CC48C68A5354B36D5AA1DA'; 
update 
  T_EMPI_RULE_MATCH_GROUP 
set 
  status = '1', 
  BUILD_WAY = '0', 
  UPDATE_BY = '1', 
  priority = 30, 
  UPDATE_TIME = to_char(
    sysdate, 'yyyy-MM-dd hh24:mi:ss'
  ) 
where 
  rule_type = '0' 
  and id = '08F29F541D3D4415A5E0672DEF936277'; 
update 
  T_EMPI_RULE_MATCH_GROUP 
set 
  status = '1', 
  BUILD_WAY = '1', 
  UPDATE_BY = '1', 
  priority = 65, 
  UPDATE_TIME = to_char(
    sysdate, 'yyyy-MM-dd hh24:mi:ss'
  ) 
where 
  rule_type = '0' 
  and id = '3FB76A70260143D7A8C46F5BBDB43E3F'; 
update 
  T_EMPI_RULE_MATCH_GROUP 
set 
  status = '1', 
  BUILD_WAY = '1', 
  UPDATE_BY = '1', 
  priority = 70, 
  UPDATE_TIME = to_char(
    sysdate, 'yyyy-MM-dd hh24:mi:ss'
  ) 
where 
  rule_type = '0' 
  and id = 'A4AC4D5C037043E79FB5EF5D993B5DE1'; end;
```

error:
```
org.apache.shardingsphere.sql.parser.exception.SQLParsingException: You have an error in your SQL syntax: begin update T_EMPI_RULE_MATCH_GROUP set status = '1', BUILD_WAY = '0', UPDATE_BY = '1', priority = 10, UPDATE_TIME = to_char(sysdate, 'yyyy-MM-dd hh24:mi:ss') where rule_type = '0' and id = '922B5C5CE166466D9505BFCE592D461C'; update T_EMPI_RULE_MATCH_GROUP set status = '1', BUILD_WAY = '0', UPDATE_BY = '1', priority = 15, UPDATE_TIME = to_char(sysdate, 'yyyy-MM-dd hh24:mi:ss') where rule_type = '0' and id = '3953BD247C2B49818F533DEC8ADE48BB'; update T_EMPI_RULE_MATCH_GROUP set status = '1', BUILD_WAY = '0', UPDATE_BY = '1', priority = 20, UPDATE_TIME = to_char(sysdate, 'yyyy-MM-dd hh24:mi:ss') where rule_type = '0' and id = '8F22D1F686CC48C68A5354B36D5AA1DA'; update T_EMPI_RULE_MATCH_GROUP set status = '1', BUILD_WAY = '0', UPDATE_BY = '1', priority = 30, UPDATE_TIME = to_char(sysdate, 'yyyy-MM-dd hh24:mi:ss') where rule_type = '0' and id = '08F29F541D3D4415A5E0672DEF936277'; update T_EMPI_RULE_MATCH_GROUP set status = '1', BUILD_WAY = '1', UPDATE_BY = '1', priority = 65, UPDATE_TIME = to_char(sysdate, 'yyyy-MM-dd hh24:mi:ss') where rule_type = '0' and id = '3FB76A70260143D7A8C46F5BBDB43E3F'; update T_EMPI_RULE_MATCH_GROUP set status = '1', BUILD_WAY = '1', UPDATE_BY = '1', priority = 70, UPDATE_TIME = to_char(sysdate, 'yyyy-MM-dd hh24:mi:ss') where rule_type = '0' and id = 'A4AC4D5C037043E79FB5EF5D993B5DE1'; end;, no viable alternative at input 'begin' at line 1, position 0, near [@0,0:4='begin',<129>,1:0]

	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.twoPhaseParse(SQLParserExecutor.java:70)
	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.parse(SQLParserExecutor.java:49)
	at org.apache.shardingsphere.sql.parser.api.SQLParserEngine.parse(SQLParserEngine.java:47)
	at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserExecutor.parse(SQLStatementParserExecutor.java:48)
	at org.apache.shardingsphere.infra.parser.cache.SQLStatementCacheLoader.load(SQLStatementCacheLoader.java:41)
	at org.apache.shardingsphere.infra.parser.cache.SQLStatementCacheLoader.load(SQLStatementCacheLoader.java:30)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$2(LocalLoadingCache.java:145)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2406)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2404)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2387)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:56)
	at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserEngine.parse(SQLStatementParserEngine.java:47)
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine.parse(ShardingSphereSQLParserEngine.java:58)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.<init>(ShardingSpherePreparedStatement.java:205)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.<init>(ShardingSpherePreparedStatement.java:171)
	at org.apache.shardingsphere.driver.jdbc.core.connection.ShardingSphereConnection.prepareStatement(ShardingSphereConnection.java:87)
	at org.example.AppTest.updateBatchTest(AppTest.java:76)
```

**Comment by xigongxiaoche** [comment]
I used 5.4.1, the bug is still exists

**Comment by strongduanmu** [comment]
Hi @xigongxiaoche, would you like to submit a PR to support this feature?

**Comment by xigongxiaoche** [comment]
@strongduanmu this sql is support in 5.5.0

**Comment by strongduanmu** [comment]
> @strongduanmu this sql is support in 5.5.0

It's a good news, you can try to upgrade to 5.5.0.
