### ISSUE TITLE
Can not get 36 connections one time, partition succeed connection(10) have released

### ISSUE THREAD

**Issue by wmfxly** [apache/shardingsphere#32033]
Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy 5.5.0

Expected behavior

I want to migrate data from the original database to the target database for table operation,
according to the creation time create_time table, 3 tables per month.

table  algorithm

```java
public class DateYYYYMMThreeTablePreciseAlgorithm implements StandardShardingAlgorithm<Date> {
    private final Logger log = LoggerFactory.getLogger(DateYYYYMMThreeTablePreciseAlgorithm.class);
    private Properties props=new Properties();

    @Override
    public String doSharding(Collection<String> availableTargetNames, PreciseShardingValue<Date> shardingValue) {
        String suffix = "";
        try {
            suffix = parseOne(shardingValue.getValue());
        } catch (Exception e) {
            log.error("Rana{}",shardingValue.getValue());
            throw new RuntimeException("querey time error [" + shardingValue.getValue() + "]!");
        }

        for (String each : availableTargetNames) {
            if (each.endsWith("_" + suffix)) {
                return each;
            }
        }
        throw new UnsupportedOperationException();
    }

    @Override
    public Collection<String> doSharding(Collection<String> availableTargetNames, RangeShardingValue<Date> shardingValue) {
        Collection<String> result = new LinkedHashSet<>();
        Range<Date> ranges = shardingValue.getValueRange();
        try {
            String tablePrefix = "";
            for (String each : availableTargetNames) {
                tablePrefix = each.substring(0, each.lastIndexOf("_"));
                break;
            }
            String startDay = "";
            if (ranges.hasLowerBound()) {
                startDay = ranges.lowerEndpoint().toString().substring(0, 10);
            } else {
                startDay = parseStartDay(availableTargetNames);
            }
            String endDay = "";
            if (ranges.hasUpperBound()) {
                endDay = ranges.upperEndpoint().toString().substring(0, 10);
            } else {
                endDay = parseLastDay(availableTargetNames);
            }
            Date startTime = DateUtils.parseDate(startDay, "yyyy-MM-dd");
            Date endTime = DateUtils.parseDate(endDay, "yyyy-MM-dd");
            Calendar cal = Calendar.getInstance();
            while (startTime.getTime() <= endTime.getTime()) {
                result.add(tablePrefix + "_" + parseOne(startTime));
                // set start time
                cal.setTime(startTime);
                cal.add(Calendar.DATE, 10);
                startTime = cal.getTime();
            }
            String endResult = tablePrefix + "_" + parseOne(endTime);
            if (!result.contains(endResult)) {
                result.add(endResult);
            }
        } catch (ParseException e) {
            log.error("doSharding ParseException", e);
        }
        return result;
    }

    /**
     * 0-9 store table 0，10-19 store table 1，20-31 store table 12
     *
     * @param date
     * @return
     */
    private static String parseOne(Date date) {
        String tableName = "";
        SimpleDateFormat sdf1 = new SimpleDateFormat("yyyyMM");
        tableName += sdf1.format(date);
        SimpleDateFormat sdf2 = new SimpleDateFormat("dd");
        int day = Integer.parseInt(sdf2.format(date));
        if (0 < day && day < 10) {
            tableName += "0";
        } else if (10 <= day && day < 20) {
            tableName += "1";
        } else if (20 <= day && day <= 31) {
            tableName += "2";
        } else {
            throw new RuntimeException("query time[" + new SimpleDateFormat("yyyyMMddHHmmss").format(date) + "]no config table!");
        }
        return tableName;
    }

   
    private String parseStartDay(Collection<String> availableTargetNames) {
        String startDay = "";
        for (String each : availableTargetNames) {
            String suffix = each.substring(each.lastIndexOf("_") + 1);
            startDay = suffix.substring(0, 4) + "-" + suffix.substring(4, 6) + "-01";
            break;
        }
        return startDay;
    }

  
    private String parseLastDay(Collection<String> availableTargetNames) {
        String lastDay = "";
        for (String each : availableTargetNames) {
            String suffix = each.substring(each.lastIndexOf("_") + 1);
            lastDay = suffix.substring(0, 4) + "-" + suffix.substring(4, 6) + "-31";
        }
        return lastDay;
    }

   
    @Override
    public String getType() {
        return "DATEYYYYMM_THREE_MOD";
    }

}
```

MIGRATION tabel data success.

Actual behavior

```
Caused by: java.sql.SQLException: Can not get 36 connections one time, partition succeed connection(10) have released. Please consider increasing the 'maxPoolSize' of the data sources or decreasing the 'max-connections-size-per-query' in properties.
More details: HikariPool-5 - Connection is not available, request timed out after 30009ms.
at org.apache.shardingsphere.infra.exception.core.external.sql.ShardingSphereSQLException.toSQLException(ShardingSphereSQLException.java:76)
at org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager.createConnections(DriverDatabaseConnectionManager.java:409)
at org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager.createConnections(DriverDatabaseConnectionManager.java:393)
at org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager.getConnections(
```

Reason analyze (If you can)

'maxPoolSize' of the data sources or decreasing the 'max-connections-size-per-query' config invalidate
max-connections-size-per-query default value 1

Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

```sql
-- MIGRATION SOURCE STORAGE
REGISTER MIGRATION SOURCE STORAGE UNIT yss_source_common_db (
URL="jdbc:mysql://ip:3306/xxx_common?serverTimezone=UTC&useSSL=false",
USER="user",
PASSWORD="user",
PROPERTIES("minPoolSize"="5","maxPoolSize"="50","idleTimeout"="60000")
);

-- add STORAGE UNIT
REGISTER STORAGE UNIT ds_0 (
URL="jdbc:mysql://ip:3306/proxy_demo_ds_0?useSSL=false",
USER="root",
PASSWORD="mysql",
PROPERTIES("maxPoolSize"=200,"idleTimeout"="30000","minPoolSize"=10,"maxLifetime"="1800000","connectionTimeout"="30000")
);
-- add sharding rule
CREATE SHARDING TABLE RULE app_notice_ind (
DATANODES(ds_0.app_notice_ind_$->{202401..202412}$->{0..2}),
TABLE_STRATEGY(TYPE="STANDARD",SHARDING_COLUMN=create_time,
SHARDING_ALGORITHM(TYPE(NAME="DATEYYYYMM_THREE_MOD",
PROPERTIES("algorithmClassName"="com.xxxxx.extend.proxy.algorithm.DateYYYYMMThreeTablePreciseAlgorithm",
"algorithm-expression"="app_notice_ind_$->{202401..202412}$->{0..2}")))),
AUDIT_STRATEGY (TYPE(NAME="DML_SHARDING_CONDITIONS"),ALLOW_HINT_DISABLE=true)
);

MIGRATE TABLE xxx.app_notice_ind INTO app_notice_ind;
```

Any help would be greatly appreciated.Thanks .

**Comment by terrymanu** [comment]
The markdown format in your issue is incorrect. To facilitate reading, could you please revise it?

**Comment by wmfxly** [comment]
I have fixed the formatting issue @terrymanu ,Any help would be greatly appreciated.Thanks .

**Comment by sandynz** [comment]
Hi @wmfxly , 1) Could you try to update `maxPoolSize` of `ds_0` to test? e.g. `1000`.
2) Could you help to supply the full exception stack trace? We'll analyze the possible problem.

**Comment by wmfxly** [comment]
I change maxPoolSize 1000
REGISTER STORAGE UNIT ds_0 (
    URL="jdbc:mysql://ip:3306/proxy_demo_ds_0?useSSL=false",
    USER="root",
    PASSWORD="mysql",
    PROPERTIES("maxPoolSize"=1000,"idleTimeout"="30000","minPoolSize"=10,"maxLifetime"="1800000","connectionTimeout"="30000")
);


and change SHARDING TABLE RULE,start date 202101 end date 202412

ALTER SHARDING TABLE RULE app_notice_ind (
DATANODES("ds_0.app_notice_ind_$->{202101..202412}$->{0..2}"),
TABLE_STRATEGY(TYPE="STANDARD",SHARDING_COLUMN=create_time,SHARDING_ALGORITHM(TYPE(NAME="DATEYYYYMM_THREE_MOD",
PROPERTIES("algorithmClassName"="com.kabao.extend.proxy.algorithm.DateYYYYMMThreeTablePreciseAlgorithm","algorithm-expression"="app_notice_ind_$->{202101..202412}$->{0..2}")))),
AUDIT_STRATEGY (TYPE(NAME="DML_SHARDING_CONDITIONS"),ALLOW_HINT_DISABLE=true)
);



error msg
[INFO ] 2024-07-10 02:56:45.137 [j0102p00004e364016e332a3d217ce95f03b4408e7_Worker-1] o.a.s.d.p.s.m.p.MigrationJobPreparer - unlock, jobId=j0102p00004e364016e332a3d217ce95f03b4408e7, shardingItem=0, cost 73913 ms
[ERROR] 2024-07-10 02:56:45.153 [j0102p00004e364016e332a3d217ce95f03b4408e7_Worker-1] o.a.s.d.p.c.j.AbstractSeparablePipelineJob - Job execution failed, j0102p00004e364016e332a3d217ce95f03b4408e7-0
org.apache.shardingsphere.data.pipeline.core.exception.PipelineInternalException: java.sql.SQLException: Can not get 936 connections one time, partition succeed connection(100) have released. Please consider increasing the 'maxPoolSize' of the data sources or decreasing the 'max-connections-size-per-query' in properties.
More details: HikariPool-12 - Connection is not available, request timed out after 30005ms.
  at org.apache.shardingsphere.data.pipeline.core.job.AbstractSeparablePipelineJob.prepare(AbstractSeparablePipelineJob.java:133)
  at org.apache.shardingsphere.data.pipeline.core.job.AbstractSeparablePipelineJob.execute(AbstractSeparablePipelineJob.java:117)
  at org.apache.shardingsphere.data.pipeline.core.job.AbstractSeparablePipelineJob.execute(AbstractSeparablePipelineJob.java:90)
  at org.apache.shardingsphere.elasticjob.simple.executor.SimpleJobExecutor.process(SimpleJobExecutor.java:33)
  at org.apache.shardingsphere.elasticjob.simple.executor.SimpleJobExecutor.process(SimpleJobExecutor.java:29)
  at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.process(ElasticJobExecutor.java:173)
  at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.process(ElasticJobExecutor.java:142)
  at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.execute(ElasticJobExecutor.java:124)
  at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.execute(ElasticJobExecutor.java:100)
  at org.apache.shardingsphere.elasticjob.lite.internal.schedule.LiteJob.execute(LiteJob.java:35)
  at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
  at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.sql.SQLException: Can not get 936 connections one time, partition succeed connection(100) have released. Please consider increasing the 'maxPoolSize' of the data sources or decreasing the 'max-connections-size-per-query' in properties.
More details: HikariPool-12 - Connection is not available, request timed out after 30005ms.
  at org.apache.shardingsphere.infra.exception.core.external.sql.ShardingSphereSQLException.toSQLException(ShardingSphereSQLException.java:76)
  at org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager.createConnections(DriverDatabaseConnectionManager.java:409)
  at org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager.createConnections(DriverDatabaseConnectionManager.java:393)
  at org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager.getConnections(DriverDatabaseConnectionManager.java:359)
  at org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager.getConnections(DriverDatabaseConnectionManager.java:340)
  at org.apache.shardingsphere.infra.executor.sql.prepare.driver.DriverExecutionPrepareEngine.group(DriverExecutionPrepareEngine.java:89)
  at org.apache.shardingsphere.infra.executor.sql.prepare.AbstractExecutionPrepareEngine.prepare(AbstractExecutionPrepareEngine.java:70)
  at org.apache.shardingsphere.infra.executor.sql.prepare.AbstractExecutionPrepareEngine.prepare(AbstractExecutionPrepareEngine.java:59)
  at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.createExecutionGroupContext(ShardingSphereStatement.java:528)
  at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.useDriverToExecute(ShardingSphereStatement.java:562)
  at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.executeWithExecutionContext(ShardingSphereStatement.java:541)
  at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.execute0(ShardingSphereStatement.java:466)
  at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.execute(ShardingSphereStatement.java:394)
  at org.apache.shardingsphere.data.pipeline.core.preparer.datasource.PipelineJobDataSourcePreparer.executeTargetTableSQL(PipelineJobDataSourcePreparer.java:123)
  at org.apache.shardingsphere.data.pipeline.core.preparer.datasource.PipelineJobDataSourcePreparer.prepareTargetTables(PipelineJobDataSourcePreparer.java:113)
  at org.apache.shardingsphere.data.pipeline.scenario.migration.preparer.MigrationJobPreparer.prepareTarget(MigrationJobPreparer.java:172)
  at org.apache.shardingsphere.data.pipeline.scenario.migration.preparer.MigrationJobPreparer.prepareAndCheckTarget(MigrationJobPreparer.java:155)
  at org.apache.shardingsphere.data.pipeline.scenario.migration.preparer.MigrationJobPreparer.prepareAndCheckTargetWithLock(MigrationJobPreparer.java:140)
  at org.apache.shardingsphere.data.pipeline.scenario.migration.preparer.MigrationJobPreparer.prepare(MigrationJobPreparer.java:104)
  at org.apache.shardingsphere.data.pipeline.scenario.migration.MigrationJob.doPrepare(MigrationJob.java:108)
  at org.apache.shardingsphere.data.pipeline.scenario.migration.MigrationJob.doPrepare(MigrationJob.java:54)
  at org.apache.shardingsphere.data.pipeline.core.job.AbstractSeparablePipelineJob.prepare(AbstractSeparablePipelineJob.java:129)
  ... 11 common frames omitted
Caused by: java.sql.SQLTransientConnectionException: HikariPool-12 - Connection is not available, request timed out after 30005ms.
  at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
  at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
  at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
  at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
  at org.apache.shardingsphere.infra.datasource.pool.CatalogSwitchableDataSource.getConnection(CatalogSwitchableDataSource.java:46)
  at org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager.createConnection(DriverDatabaseConnectionManager.java:419)
  at org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager.createConnections(DriverDatabaseConnectionManager.java:402)
  ... 31 common frames omitted
[ERROR] 2024-07-10 02:56:45.167 [j0102p00004e364016e332a3d217ce95f03b4408e7_Worker-1] o.a.s.e.e.h.g.LogJobErrorHandler - Job 'j0102p00004e364016e332a3d217ce95f03b4408e7' exception occur in job processing
org.apache.shardingsphere.data.pipeline.core.exception.PipelineInternalException: java.sql.SQLException: Can not get 936 connections one time, partition succeed connection(100) have released. Please consider increasing the 'maxPoolSize' of the data sources or decreasing the 'max-connections-size-per-query' in properties.
More details: HikariPool-12 - Connection is not available, request timed out after 30005ms.
  at org.apache.shardingsphere.data.pipeline.core.job.AbstractSeparablePipelineJob.prepare(AbstractSeparablePipelineJob.java:133)
  at org.apache.shardingsphere.data.pipeline.core.job.AbstractSeparablePipelineJob.execute(AbstractSeparablePipelineJob.java:117)
  at org.apache.shardingsphere.data.pipeline.core.job.AbstractSeparablePipelineJob.execute(AbstractSeparablePipelineJob.java:90)
  at org.apache.shardingsphere.elasticjob.simple.executor.SimpleJobExecutor.process(SimpleJobExecutor.java:33)
  at org.apache.shardingsphere.elasticjob.simple.executor.SimpleJobExecutor.process(SimpleJobExecutor.java:29)
  at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.process(ElasticJobExecutor.java:173)
  at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.process(ElasticJobExecutor.java:142)
  at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.execute(ElasticJobExecutor.java:124)
  at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.execute(ElasticJobExecutor.java:100)
  at org.apache.shardingsphere.elasticjob.lite.internal.schedule.LiteJob.execute(LiteJob.java:35)
  at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
  at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.sql.SQLException: Can not get 936 connections one time, partition succeed connection(100) have released. Please consider increasing the 'maxPoolSize' of the data sources or decreasing the 'max-connections-size-per-query' in properties.
More details: HikariPool-12 - Connection is not available, request timed out after 30005ms.
  at org.apache.shardingsphere.infra.exception.core.external.sql.ShardingSphereSQLException.toSQLException(ShardingSphereSQLException.java:76)
  at org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager.createConnections(DriverDatabaseConnectionManager.java:409)
  at org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager.createConnections(DriverDatabaseConnectionManager.java:393)
  at org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager.getConnections(DriverDatabaseConnectionManager.java:359)
  at org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager.getConnections(DriverDatabaseConnectionManager.java:340)
  at org.apache.shardingsphere.infra.executor.sql.prepare.driver.DriverExecutionPrepareEngine.group(DriverExecutionPrepareEngine.java:89)
  at org.apache.shardingsphere.infra.executor.sql.prepare.AbstractExecutionPrepareEngine.prepare(AbstractExecutionPrepareEngine.java:70)
  at org.apache.shardingsphere.infra.executor.sql.prepare.AbstractExecutionPrepareEngine.prepare(AbstractExecutionPrepareEngine.java:59)
  at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.createExecutionGroupContext(ShardingSphereStatement.java:528)
  at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.useDriverToExecute(ShardingSphereStatement.java:562)
  at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.executeWithExecutionContext(ShardingSphereStatement.java:541)
  at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.execute0(ShardingSphereStatement.java:466)
  at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.execute(ShardingSphereStatement.java:394)
  at org.apache.shardingsphere.data.pipeline.core.preparer.datasource.PipelineJobDataSourcePreparer.executeTargetTableSQL(PipelineJobDataSourcePreparer.java:123)
  at org.apache.shardingsphere.data.pipeline.core.preparer.datasource.PipelineJobDataSourcePreparer.prepareTargetTables(PipelineJobDataSourcePreparer.java:113)
  at org.apache.shardingsphere.data.pipeline.scenario.migration.preparer.MigrationJobPreparer.prepareTarget(MigrationJobPreparer.java:172)
  at org.apache.shardingsphere.data.pipeline.scenario.migration.preparer.MigrationJobPreparer.prepareAndCheckTarget(MigrationJobPreparer.java:155)
  at org.apache.shardingsphere.data.pipeline.scenario.migration.preparer.MigrationJobPreparer.prepareAndCheckTargetWithLock(MigrationJobPreparer.java:140)
  at org.apache.shardingsphere.data.pipeline.scenario.migration.preparer.MigrationJobPreparer.prepare(MigrationJobPreparer.java:104)
  at org.apache.shardingsphere.data.pipeline.scenario.migration.MigrationJob.doPrepare(MigrationJob.java:108)
  at org.apache.shardingsphere.data.pipeline.scenario.migration.MigrationJob.doPrepare(MigrationJob.java:54)
  at org.apache.shardingsphere.data.pipeline.core.job.AbstractSeparablePipelineJob.prepare(AbstractSeparablePipelineJob.java:129)
  ... 11 common frames omitted
Caused by: java.sql.SQLTransientConnectionException: HikariPool-12 - Connection is not available, request timed out after 30005ms.
  at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
  at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
  at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
  at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
  at org.apache.shardingsphere.infra.datasource.pool.CatalogSwitchableDataSource.getConnection(CatalogSwitchableDataSource.java:46)
  at org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager.createConnection(DriverDatabaseConnectionManager.java:419)
  at org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager.createConnections(DriverDatabaseConnectionManager.java:402)
  ... 31 common frames omitted
[INFO ] 2024-07-10 02:56:45.170 [j0102p00004e364016e332a3d217ce95f03b4408e7_Worker-1] o.a.s.d.p.c.l.PipelineElasticJobListener - After j0102p00004e364016e332a3d217ce95f03b4408e7 job execute 


@sandynz 
How do I set the max-connections-size-per-query configuration，in global.yaml config ?

**Comment by terrymanu** [comment]
Same request, the markdown format in your issue is incorrect. To facilitate reading, could you please revise it?

**Comment by sandynz** [comment]
@wmfxly You could not set `max-connections-size-per-query`.
I noticed `DATANODES` in rule is changed and there's much more shards than before, could you enlarge `maxPoolSize` again to test?

**Comment by wmfxly** [comment]
Production database links cannot be set to infinite size, this is just one of the migration tasks (there are other migration tasks that compete for database links), and adjusting maxPoolSize to a larger value does not solve the problem。 @sandynz

**Comment by helloworldtech1024** [comment]
我在分片规则里指定分片数量是20的时候不会报错，但是指定成1000就会报错，
```sql
CREATE SHARDING TABLE RULE property_fee_order_info(STORAGE_UNITS(destination_db),SHARDING_COLUMN=fee_order_id,TYPE(NAME="hash_mod",PROPERTIES("sharding-count"="20")),KEY_GENERATE_STRATEGY(COLUMN=id,TYPE(NAME="snowflake")));
```
```"sharding-count"="20" ```这个参数
