### ISSUE TITLE
with java api to create shardingSphereDatasource  ,logic_table will not  in  logic_db -> schemas->tables

### ISSUE THREAD

**Issue by caoweicw** [apache/shardingsphere#32166]
```
@Configuration
public class ShardingDatasource {

  @Bean
  @Primary
    public DataSource getDataSource() throws SQLException {
      List<RuleConfiguration> shardingRuleConfigurations  = new ArrayList<>();
      shardingRuleConfigurations.add(createShardingRuleConfiguration());
//      shardingRuleConfigurations.add(createBroadcastRuleConfiguration());
    DataSource dataSource = ShardingSphereDataSourceFactory.createDataSource(createDataSourceMap(),
        shardingRuleConfigurations, new Properties());
    return dataSource;
  }

    private ShardingRuleConfiguration createShardingRuleConfiguration() {
      ShardingRuleConfiguration result = new ShardingRuleConfiguration();
      result.getTables().add(getOrderTableRuleConfiguration());
      result.getTables().add(getOrderItemTableRuleConfiguration());
      result.getBindingTableGroups().add(new ShardingTableReferenceRuleConfiguration("foo", "t_order, t_order_item"));
      result.setDefaultDatabaseShardingStrategy(new StandardShardingStrategyConfiguration("user_id", "inline"));
      result.setDefaultTableShardingStrategy(new StandardShardingStrategyConfiguration("order_id", "standard_test_tbl"));
      Properties props = new Properties();
      props.setProperty("algorithm-expression", "demo_ds_${user_id % 2}");
      result.getShardingAlgorithms().put("inline", new AlgorithmConfiguration("INLINE", props));
      result.getShardingAlgorithms().put("standard_test_tbl", new AlgorithmConfiguration("STANDARD_TEST_TBL", new Properties()));
      result.getKeyGenerators().put("snowflake", new AlgorithmConfiguration("SNOWFLAKE", new Properties()));
      result.getAuditors().put("sharding_key_required_auditor", new AlgorithmConfiguration("DML_SHARDING_CONDITIONS", new Properties()));
      return result;
    }

    private ShardingTableRuleConfiguration getOrderTableRuleConfiguration() {
      ShardingTableRuleConfiguration result = new ShardingTableRuleConfiguration("t_order", "demo_ds_${0..1}.t_order_${[0, 1]}");
      result.setKeyGenerateStrategy(new KeyGenerateStrategyConfiguration("order_id", "snowflake"));
      result.setAuditStrategy(new ShardingAuditStrategyConfiguration(Collections.singleton("sharding_key_required_auditor"), true));
      return result;
    }

    private ShardingTableRuleConfiguration getOrderItemTableRuleConfiguration() {
      ShardingTableRuleConfiguration result = new ShardingTableRuleConfiguration("t_order_item", "demo_ds_${0..1}.t_order_item_${[0, 1]}");
      result.setKeyGenerateStrategy(new KeyGenerateStrategyConfiguration("order_item_id", "snowflake"));
      return result;
    }

    private Map<String, DataSource> createDataSourceMap() {
      Map<String, DataSource> result = new HashMap<>();
      result.put("demo_ds_0", createDataSource());
      result.put("demo_ds_1", createDataSource());
      return result;
    }

    private BroadcastRuleConfiguration createBroadcastRuleConfiguration() {
      return new BroadcastRuleConfiguration(Collections.singletonList("t_address"));
    }

    public DataSource createDataSource(){
      Map<String,Object> pro = new HashMap<>();
      pro.put("url","jdbc:mysql://localhost:3306/awei?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai");
      pro.put("username","root");
      pro.put("password","cw183989.");
      DataSourcePoolProperties poolProperties = new DataSourcePoolProperties("com.alibaba.druid.pool.DruidDataSource",pro);
      DataSource dataSource = DataSourcePoolCreator.create(poolProperties);
      return dataSource;
    }
}
```
shardingShpereDatasouce logic_db->schemas-tables:
![1721292032780](https://github.com/user-attachments/assets/23bf66a1-e297-414a-a166-f6a7998c609a)

when execute sql , it will checkTableExists  and throw exception 
![xxx](https://github.com/user-attachments/assets/9a697b46-1b32-4914-be63-f64d3438a045)

**Comment by terrymanu** [comment]
The markdown format in your issue is incorrect. To facilitate reading, could you please revise it?

**Comment by caoweicw** [comment]
> The markdown format in your issue is incorrect. To facilitate reading, could you please revise it?

ok

**Comment by terrymanu** [comment]
What is your version?

**Comment by terrymanu** [comment]
I believe it is very difficult to determine how to reproduce from a debug screenshot, as it hides too much information. 
For example: whether it is in a multi-threads, how the execution was performed, how many steps were taken after the breakpoint before entering this state, and how many times this breakpoint was hit. 

Anyway, could you please clarify the purpose of this issue, what error occurred during the process, and what operations were performed when the error was reported?

**Comment by caoweicw** [comment]
> I believe it is very difficult to determine how to reproduce from a debug screenshot, as it hides too much information. For example: whether it is in a multi-threads, how the execution was performed, how many steps were taken after the breakpoint before entering this state, and how many times this breakpoint was hit.
> 
> Anyway, could you please clarify the purpose of this issue, what error occurred during the process, and what operations were performed when the error was reported?


First,I create shardingSphereDatasource with java api,and set shardingrule with tb_order 
Sencond,I execute sql as follows:
![微信图片_1](https://github.com/user-attachments/assets/14f06122-70a5-49ea-966b-d82727554932)
it will throw exception as follows:
```
org.apache.shardingsphere.infra.exception.kernel.metadata.TableNotFoundException: Table or view 't_order' does not exist.
	at org.apache.shardingsphere.infra.binder.segment.from.impl.SimpleTableSegmentBinder.lambda$checkTableExists$4(SimpleTableSegmentBinder.java:151)
	at org.apache.shardingsphere.infra.exception.core.ShardingSpherePreconditions.checkState(ShardingSpherePreconditions.java:41)
	at org.apache.shardingsphere.infra.binder.segment.from.impl.SimpleTableSegmentBinder.checkTableExists(SimpleTableSegmentBinder.java:148)
	at org.apache.shardingsphere.infra.binder.segment.from.impl.SimpleTableSegmentBinder.bind(SimpleTableSegmentBinder.java:84)
	at org.apache.shardingsphere.infra.binder.segment.from.TableSegmentBinder.bind(TableSegmentBinder.java:55)
	at org.apache.shardingsphere.infra.binder.statement.dml.SelectStatementBinder.lambda$bind$1(SelectStatementBinder.java:60)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.apache.shardingsphere.infra.binder.statement.dml.SelectStatementBinder.bind(SelectStatementBinder.java:60)
	at org.apache.shardingsphere.infra.binder.statement.dml.SelectStatementBinder.bind(SelectStatementBinder.java:48)
	at org.apache.shardingsphere.infra.binder.engine.SQLBindEngine.bindDMLStatement(SQLBindEngine.java:82)
	at org.apache.shardingsphere.infra.binder.engine.SQLBindEngine.bind(SQLBindEngine.java:72)
	at org.apache.shardingsphere.infra.binder.engine.SQLBindEngine.bind(SQLBindEngine.java:63)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.<init>(ShardingSpherePreparedStatement.java:207)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.<init>(ShardingSpherePreparedStatement.java:172)
```
I debug and find in org.apache.shardingsphere.infra.binder.segment.from.impl.SimpleTableSegmentBinder.checkTableExists, the logic_db->shemas->tables is empty  ,it cause exeception。
```
private static void checkTableExists(String tableName, SQLStatementBinderContext statementBinderContext, String databaseName, String schemaName) {
    if (!"dual".equalsIgnoreCase(tableName)) {
      if (!SystemSchemaManager.isSystemTable(schemaName, tableName)) {
        if (!statementBinderContext.getExternalTableBinderContexts().containsKey(tableName)) {
          ShardingSpherePreconditions.checkState(statementBinderContext.getMetaData().containsDatabase(databaseName) && statementBinderContext.getMetaData().getDatabase(databaseName).containsSchema(schemaName) && statementBinderContext.getMetaData().getDatabase(databaseName).getSchema(schemaName).containsTable(tableName), () -> {
            return new TableNotFoundException(tableName);
          });
        }
      }
    }
  }
```

![微信图片_2](https://github.com/user-attachments/assets/aea965f5-bcd7-4e43-89d4-3e6b53eef78f)

**Comment by GeneralChaing** [comment]
I am having the same problem. I siad the log finding the impoint point that creating the H2 datasource first, but I didn't do it.
<img width="1688" alt="11be440867a7c690743887fe28d6f5f" src="https://github.com/user-attachments/assets/1c23da5d-88af-4ec9-a86f-f95f4bf3d6a2">

**Comment by wdyzpf** [comment]
遇到了同样的问题。我通过Spring dataSource + shardingSpher jdbc 做多数据源，需要使用 java api方式配置，配置的多数据源在访问物理库单表（无分片）和分表（分了128张表）时，有分表的访问正常，单表提示：
Caused by: org.apache.shardingsphere.infra.exception.kernel.metadata.TableNotFoundException: Table or view 'trade_risk_order' does not exist.
	at org.apache.shardingsphere.infra.binder.segment.from.impl.SimpleTableSegmentBinder.lambda$checkTableExists$4(SimpleTableSegmentBinder.java:151)
	at org.apache.shardingsphere.infra.exception.core.ShardingSpherePreconditions.checkState(ShardingSpherePreconditions.java:41)
	at org.apache.shardingsphere.infra.binder.segment.from.impl.SimpleTableSegmentBinder.checkTableExists(SimpleTableSegmentBinder.java:148)
	at org.apache.shardingsphere.infra.binder.segment.from.impl.SimpleTableSegmentBinder.bind(SimpleTableSegmentBinder.java:84)
	at org.apache.shardingsphere.infra.binder.segment.from.TableSegmentBinder.bind(TableSegmentBinder.java:55)
	at org.apache.shardingsphere.infra.binder.statement.dml.SelectStatementBinder.lambda$bind$1(SelectStatementBinder.java:60)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.apache.shardingsphere.infra.binder.statement.dml.SelectStatementBinder.bind(SelectStatementBinder.java:60)
	at org.apache.shardingsphere.infra.binder.statement.dml.SelectStatementBinder.bind(SelectStatementBinder.java:48)
	at org.apache.shardingsphere.infra.binder.engine.SQLBindEngine.bindDMLStatement(SQLBindEngine.java:82)
	at org.apache.shardingsphere.infra.binder.engine.SQLBindEngine.bind(SQLBindEngine.java:72)
	at org.apache.shardingsphere.infra.binder.engine.SQLBindEngine.bind(SQLBindEngine.java:63)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.<init>(ShardingSpherePreparedStatement.java:207)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.<init>(ShardingSpherePreparedStatement.java:172)
	at org.apache.shardingsphere.driver.jdbc.core.connection.ShardingSphereConnection.prepareStatement(ShardingSphereConnection.java:94)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.ibatis.logging.jdbc.ConnectionLogger.invoke(ConnectionLogger.java:53)
	at jdk.proxy3/jdk.proxy3.$Proxy122.prepareStatement(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:88)
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:90)

**Comment by caoweicw** [comment]
singletable need config as singletableConfiguration

**Comment by kuangziyang** [comment]
shardingsphere的一个坑来的，初始化的时候Shardingsphere会将你设置的表从数据库加载元数据加载到内存中，每次执行sql时都要校验你查询的表在内存中是否存在元数据，不存在则会抛出异常。你需要做以下设置便可：
// 设置ShardingDataSource表范围: "dataSourceName.*"
SingleRuleConfiguration singleRuleConfiguration = new SingleRuleConfiguration();
singleRuleConfiguration.getTables().add(datasourceName + ".*");
singleRuleConfiguration.setDefaultDataSource(datasourceName);

**Comment by terrymanu** [comment]
Is the question resolved?
