### ISSUE TITLE
Single Table Schema Issues in PostgreSQL 5.5.0

### ISSUE THREAD

**Issue by jdAction** [apache/shardingsphere#32188]
### Which version of ShardingSphere did you use?
5.5.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere JDBC
### Expected behavior
rules:
  - !SINGLE
    tables:
      - ds_0.other.*
    defaultDataSource: ds_0
Load the schema of a single table
### Actual behavior
The schema for loading a single table is public, and the configuration for yml is not effective
### Reason analyze (If you can)
private static IdentifierValue getSchemaName(final SimpleTableSegment segment, final SQLStatementBinderContext statementBinderContext) {
        if (segment.getOwner().isPresent()) {
            return segment.getOwner().get().getIdentifier();
        }
        // TODO getSchemaName according to search path
        DatabaseType databaseType = statementBinderContext.getDatabaseType();
        if ((databaseType instanceof PostgreSQLDatabaseType || databaseType instanceof OpenGaussDatabaseType)
                && SYSTEM_CATALOG_TABLES.contains(segment.getTableName().getIdentifier().getValue())) {
            return new IdentifierValue(PG_CATALOG);
        }
        return new IdentifierValue(new DatabaseTypeRegistry(databaseType).getDefaultSchemaName(statementBinderContext.getDefaultDatabaseName()));
Segment. getOwner() determines invalid
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Caused by: org.apache.shardingsphere.infra.exception.kernel.metadata.TableNotFoundException: Table or view 'xxx' does not exist.
	at org.apache.shardingsphere.infra.binder.segment.from.impl.SimpleTableSegmentBinder.lambda$checkTableExists$4(SimpleTableSegmentBinder.java:151)
	at org.apache.shardingsphere.infra.exception.core.ShardingSpherePreconditions.checkState(ShardingSpherePreconditions.java:41)
	at org.apache.shardingsphere.infra.binder.segment.from.impl.SimpleTableSegmentBinder.checkTableExists(SimpleTableSegmentBinder.java:148)
	at org.apache.shardingsphere.infra.binder.segment.from.impl.SimpleTableSegmentBinder.bind(SimpleTableSegmentBinder.java:84)
	at org.apache.shardingsphere.infra.binder.segment.from.TableSegmentBinder.bind(TableSegmentBinder.java:55)
	at org.apache.shardingsphere.infra.binder.statement.dml.SelectStatementBinder.lambda$bind$1(SelectStatementBinder.java:60)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.apache.shardingsphere.infra.binder.statement.dml.SelectStatementBinder.bind(SelectStatementBinder.java:60)
	at org.apache.shardingsphere.infra.binder.statement.dml.SelectStatementBinder.bind(SelectStatementBinder.java:48)
	at org.apache.shardingsphere.infra.binder.engine.SQLBindEngine.bindDMLStatement(SQLBindEngine.java:82)
	at org.apache.shardingsphere.infra.binder.engine.SQLBindEngine.bind(SQLBindEngine.java:72)
	at org.apache.shardingsphere.infra.binder.engine.SQLBindEngine.bind(SQLBindEngine.java:63)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.<init>(ShardingSpherePreparedStatement.java:207)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.<init>(ShardingSpherePreparedStatement.java:172)
	at org.apache.shardingsphere.driver.jdbc.core.connection.ShardingSphereConnection.prepareStatement(ShardingSphereConnection.java:94)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:88)
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:90)
	... 60 common frames omitted
![image](https://github.com/user-attachments/assets/dd856a23-c304-412b-b9cf-e465807f4439)
![image](https://github.com/user-attachments/assets/2133596d-e160-448a-ac21-3ea94f80df27)
![image](https://github.com/user-attachments/assets/df0ac2c1-34c2-491b-963f-eae9d5a70adf)
![image](https://github.com/user-attachments/assets/8cf0ba52-e214-44c5-bee8-166eb0164b59)
![image](https://github.com/user-attachments/assets/d0c96351-a37f-4068-88e6-521bca8278c7)
this schema why set null ?

**Comment by terrymanu** [comment]
The markdown format in your issue is incorrect. To facilitate reading, could you please revise it?

**Comment by terrymanu** [comment]
I believe it is very difficult to determine how to reproduce from a debug screenshot, as it hides too much information.
For example: whether it is in a multi-threads, how the execution was performed, how many steps were taken after the breakpoint before entering this state, and how many times this breakpoint was hit.

Anyway, could you please provide more details, such database structure, data source and other rule configurations?

**Comment by jdAction** [comment]
Without being in a multi-threaded state, the project encountered an error after startup, and the breakpoint only entered once. The reason is that PostgreSQL's database type only loads public schema by default, so I can only add other schemas by breaking the code

**Comment by terrymanu** [comment]
The markdown format in your issue is incorrect. To facilitate reading, could you please revise it?

**Comment by jdAction** [comment]
I don't know how to adjust the markdown format. Can't I fix and locate the problem by looking at my text and images?

**Comment by terrymanu** [comment]
The role of an issue is to address the author's problem and also to facilitate developers in getting key information, as well as to allow those with the same issue to search for it.
Therefore, making the issue effective, understandable, and compliant with standards is the most fundamental principle.

If you are not familiar with markdown, please take the time to learn about it.

**Comment by strongduanmu** [comment]
This issue is duplicate with #17204, we will consider support PostgreSQL SEARCH PATH in future.
