### ISSUE TITLE
custom datasource

### ISSUE THREAD

**Issue by severous** [apache/shardingsphere#32183]
I am getting the error shown below when using a custom data source:

```bash
Caused by: java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "java.util.Map.get(Object)" is null
	at org.apache.shardingsphere.infra.metadata.database.resource.unit.StorageUnit.<init>(StorageUnit.java:56)
	at org.apache.shardingsphere.infra.config.database.impl.DataSourceProvidedDatabaseConfiguration.getStorageUnits(DataSourceProvidedDatabaseConfiguration.java:73)
	at org.apache.shardingsphere.infra.config.database.impl.DataSourceProvidedDatabaseConfiguration.<init>(DataSourceProvidedDatabaseConfiguration.java:54)
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.createContextManager(ShardingSphereDataSource.java:77)
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.<init>(ShardingSphereDataSource.java:67)
	at org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactory.createDataSource(ShardingSphereDataSourceFactory.java:95)
	at org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactory.createDataSource(ShardingSphereDataSourceFactory.java:78)
	at org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactory.createDataSource(ShardingSphereDataSourceFactory.java:139)
```
<img width="1277" alt="截屏2024-07-18 21 41 27" src="https://github.com/user-attachments/assets/87ff2152-b85b-4cf9-ae7c-ae9bb02ec428">

The error occurs in the following line of code because of standardProps is null
```java
        Map<String, Object> standardProps = dataSourcePoolProperties.getConnectionPropertySynonyms().getStandardProperties();
        String url = standardProps.get("url").toString();
```
These properties are obtained from the DataSourcePoolReflection, which obtains them in a reflective manner. However, my custom datasource does not have these getter methods! I would like to know what conditions must be fulfilled for a custom data source

**Comment by terrymanu** [comment]
The title of this issue is not well enough, could you please update to a more understandable title by summarizing the content?

**Comment by severous** [comment]
I've updated the issue I'm asking. Please help.

**Comment by terrymanu** [comment]
What I mean is that the `title` isn't good enough for people with relevant expertise to get involved, as the title doesn't make it clear what the issue is about.
If the `title` cannot describe the relevant issue, then committers who will enter to view the content of this issue will correspondingly decrease.

**Comment by severous** [comment]
Okay. The title is updated

**Comment by terrymanu** [comment]
What is `custom data source`? 
Did you mean you develop an new data source pool, not use HikariCP or DBCP?

**Comment by severous** [comment]
Yes, our custom data sources provide the ability to dynamically switch between data sources.

**Comment by terrymanu** [comment]
Based on your description, the title should be modified. 
This is not related to dynamic switching; it is an issue of adapting to a custom data source pool, right?

**Comment by severous** [comment]
I will update the title to accommodate custom connection pooling

**Comment by terrymanu** [comment]
I apologize for the inconvenience, but apart from modifying the source code, ShardingSphere does not currently support custom data source pools.
Due to the wide variety and miss of standardization of data source pools, ShardingSphere can only support a few common ones and there are no plans at present to update this functionality.

However, ShardingSphere does support dynamic switching of data sources through the registry center.

**Comment by severous** [comment]
Thanks for your reply.  Could you give me some tutorial about this？
Another thing that needs to be verified is whether sharding-jdbc gets the data source configuration in a reflective way.

**Comment by terrymanu** [comment]
If not an issue, let's move it to discussion.
