### ISSUE TITLE
No value specified for parameter exception when sql is 'INSERT INTO tableName *** ON CONFLICT *** DO UPDATE set ** WHERE ***'

### ISSUE THREAD

**Issue by shijie-328931589** [apache/shardingsphere#32280]
## Bug Report

Before report a bug, make sure you have:
### Which version of ShardingSphere did you use?
5.4.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Actual behavior
Caused by: org.postgresql.util.PSQLException: 未设定参数值 3 的内容。
	at org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:275)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:307)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy122.execute(Unknown Source)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement$2.executeSQL(ShardingSpherePreparedStatement.java:490)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement$2.executeSQL(ShardingSpherePreparedStatement.java:486)
	at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutorCallback.execute(JDBCExecutorCallback.java:83)
	at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutorCallback.execute(JDBCExecutorCallback.java:62)
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
use postgresql,the sql is like this:
INSERT INTO tableName ( c1, c2, c3 ) VALUES ( ?, now(),  ? ) ON CONFLICT ( c1, c3 ) DO UPDATE set c2 = now() WHERE user_id= ?
when execute this sql, appear exception

**Comment by terrymanu** [comment]
What is the code for set parameters?

**Comment by shijie-328931589** [comment]
@Insert(" INSERT INTO user_little_secretary_read ( user_id, read_time, type ) " +
            "VALUES" +
            "( #{userId}, now(),  #{type} ) " +
            "ON CONFLICT ( user_id, type ) DO " +
            "UPDATE " +
            " set read_time = now() " +
            "WHERE " +
            "  user_id = #{userId}   " +
            " AND type = #{type} ")
        void insertUserLittleSecretaryRead(@Param("userId") long userId, @Param("type") long type);

**Comment by terrymanu** [comment]
The issue involves other third-party dependencies, but our focus is solely on ShardingSphere itself. Since ShardingSphere implements the JDBC interface, standard applications should be functional. We wish to allocate more effort towards enhancing the current version, and therefore will no longer handle such issues. Please read the documentation or provide more effective information when submitting an issue.

**Comment by shijie-328931589** [comment]
Have the same problem when use ShardingSphereDataSource. the code:

        String sql = " INSERT INTO user_little_secretary_read ( user_id, read_time, type )  VALUES ( ?, now(),  ? ) ON CONFLICT ( user_id, type ) DO UPDATE " +
                " set read_time = now() WHERE user_little_secretary_read.user_id = ? AND user_little_secretary_read.type = ? ";
        ShardingSphereDataSource dataSource = (ShardingSphereDataSource)RoutingDataSourceUtils.getCurrentShardingInfo().getRealDataSource();
        try {
            try(Connection connection = dataSource.getConnection()){
                PreparedStatement statement = connection.prepareStatement(sql);
                statement.setLong(1, userId);
                statement.setLong(2, type);
                statement.setLong(3, userId);
                statement.setLong(4, type);
                statement.execute();
            }
        }catch (Exception e){
            throw new RuntimeException(e);
        }

**Comment by terrymanu** [comment]
What is RoutingDataSourceUtils do, could you simplify your demo code again?

**Comment by shijie-328931589** [comment]
sorry, I mean this type of sql has the same problem:
   "ON CONFLICT DO UPDATE *** Where *** "
my real sql is second , and the exception is :
Caused by: org.postgresql.util.PSQLException: 未设定参数值 3 的内容。
at org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:275)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:307)
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
at com.sun.proxy.$Proxy122.execute(Unknown Source)
at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement$2.executeSQL(ShardingSpherePreparedStatement.java:490)
at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement$2.executeSQL(ShardingSpherePreparedStatement.java:486)
at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutorCallback.execute(JDBCExecutorCallback.java:83)
at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutorCallback.execute(JDBCExecutorCallback.java:62)

**Comment by omkar-shitole** [comment]
Hello, 
I investigated this particular bug report.

It is a bug. I successfully reproduced it. Also, I would like to let you know that this particular query -
*  The query executes successfully with `INSERT INTO` & `VALUES` when no `WHERE` statement is provided.
*  The query fails when extra parameter markers/placeholders are provided beyond those assigned to `VALUES`.
*  The `WHERE`  statement works well with the INSERT INTO` & `SELECT statements. 

I reviewed the ANTLR rules related to this issue, and they seem to be correctly implemented.

Any suggestions regarding the scope of the investigation and fix would be greatly appreciated.

Also, I would request you to assign this issue to me.

**Comment by omkar-shitole** [comment]
In this [PR](https://github.com/apache/shardingsphere/pull/34227) ,
I have added e2e test cases to cover similar and related queries for the  `ON CONFLICT` clause, as highlighted in the referenced [issue](https://github.com/apache/shardingsphere/pull/34227).
Additionally, I noticed that the current implementation fails to execute `ON CONFLICT ... DO NOTHING`, resulting in the following error:
<details>
  <summary>Click to expand error stack trace</summary>
  '''Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.antlr.v4.runtime.tree.ParseTree.accept(org.antlr.v4.runtime.tree.ParseTreeVisitor)" because "tree" is null
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.apache.shardingsphere.sql.parser.postgresql.visitor.statement.PostgreSQLStatementVisitor.visitOptOnConflict(PostgreSQLStatementVisitor.java:712)Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.antlr.v4.runtime.tree.ParseTree.accept(org.antlr.v4.runtime.tree.ParseTreeVisitor)" because "tree" is null
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.apache.shardingsphere.sql.parser.postgresql.visitor.statement.PostgreSQLStatementVisitor.visitOptOnConflict(PostgreSQLStatementVisitor.java:712)'''
  </details>
This PR  addresses both issues by fixing the error and ensures that queries with DO NOTHING are successfully executed.

 I kindly request you to proceed with the review and merge process.

**Comment by shijie-328931589** [comment]
The problem is getting worse on shardingshpere-jdbc 5.5.1。the sql "insert into TABLE(id,user_name) values (?,?) on conflict(id) do update set user_name = ?" execute failed。
exception：org.postgresql.util.PSQLException: 未设定参数值 3 的内容。

	at org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:275)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:307)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at jdk.proxy2/jdk.proxy2.$Proxy31.execute(Unknown Source)
	at org.apache.shardingsphere.driver.executor.callback.execute.ExecuteCallbackFactory$1.executeSQL(ExecuteCallbackFactory.java:55)
	at org.apache.shardingsphere.driver.executor.callback.execute.ExecuteCallbackFactory$1.executeSQL(ExecuteCallbackFactory.java:51)
	at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutorCallback.execute(JDBCExecutorCallback.java:85)
	at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutorCallback.execute(JDBCExecutorCallback.java:64)
	at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.syncExecute(ExecutorEngine.java:99)
	at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.parallelExecute(ExecutorEngine.java:95)
	at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.execute(ExecutorEngine.java:78)
	at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutor.execute(JDBCExecutor.java:66)
	at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutor.execute(JDBCExecutor.java:50)
	at org.apache.shardingsphere.driver.executor.engine.pushdown.jdbc.DriverJDBCPushDownExecuteExecutor.doExecute(DriverJDBCPushDownExecuteExecutor.java:102)
	at org.apache.shardingsphere.driver.executor.engine.pushdown.jdbc.DriverJDBCPushDownExecuteExecutor.lambda$execute$0(DriverJDBCPushDownExecuteExecutor.java:87)
	at org.apache.shardingsphere.driver.executor.engine.transaction.DriverTransactionalExecutor.execute(DriverTransactionalExecutor.java:56)
	at org.apache.shardingsphere.driver.executor.engine.pushdown.jdbc.DriverJDBCPushDownExecuteExecutor.execute(DriverJDBCPushDownExecuteExecutor.java:86)
	at org.apache.shardingsphere.driver.executor.engine.DriverExecuteExecutor.executePushDown(DriverExecuteExecutor.java:117)
	at org.apache.shardingsphere.driver.executor.engine.DriverExecuteExecutor.execute(DriverExecuteExecutor.java:105)
	at org.apache.shardingsphere.driver.executor.engine.facade.standard.StandardDriverExecutorFacade.execute(StandardDriverExecutorFacade.java:110)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.execute(ShardingSpherePreparedStatement.java:248)
	at com.zhaopin.common3.datasource.dao.ReadwriteDAO.executeSql2(ReadwriteDAO.java:108)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)


my code is：

    public void executeSql1(String index) throws Exception {
        ShardingInfo currentShardingInfo = RoutingDataSourceUtils.getCurrentShardingInfo();
        ShardingSphereDataSource wrappedDataSource = (ShardingSphereDataSource)currentShardingInfo.getWrappedDataSource();
        try(Connection connection = wrappedDataSource.getConnection()){
            String sql = "insert into transactional_table(id,user_name) values (?,?) on conflict(id) do update set user_name = ?";
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
            preparedStatement.setLong(1, 100L);
            preparedStatement.setString(2, "test");
            preparedStatement.setString(2, "test");
            preparedStatement.execute();
        }
    }

**Comment by terrymanu** [comment]
## Problem Understanding

  - Executing INSERT ... ON CONFLICT ... DO UPDATE ... WHERE ... with placeholders in PostgreSQL triggers No value specified for parameter (e.g., “parameter 3 not set”).
  - Placeholders appear across VALUES, SET, and the ON CONFLICT WHERE clause; some samples also show duplicated or missing setXxx bindings.

  ## Root Cause

  - The PostgreSQL visitor’s visitOptOnConflict only collects setClauseList and does not traverse the ON CONFLICT target and its WHERE. Placeholders inside that WHERE are never added to parameterMarkerSegments, so fewer parameters are passed than the SQL requires, causing
    the error.
  - If application code skips a binding (e.g., sets parameter 2 twice and never sets parameter 3), the same exception occurs and should be checked in parallel.

  ## Analysis

  - Parameter pushdown relies on the parser to collect every placeholder position; missing placeholders inside ON CONFLICT ... WHERE ... is a parser gap.
  - Official syntax reference (placeholders must be fully bound): https://www.postgresql.org/docs/current/sql-insert.html#SQL-ON-CONFLICT

  ## Conclusion

  - Missing traversal in ON CONFLICT leads to uncounted placeholders and mismatched bindings. Applications should also ensure every placeholder is bound exactly once.
  - Fix suggestion: in parser/sql/engine/dialect/postgresql/.../PostgreSQLStatementVisitor.java, extend visitOptOnConflict to traverse the ON CONFLICT target and WHERE, adding their parameter markers to parameterMarkerSegments; add unit/E2E tests covering placeholders in
    VALUES, SET, and WHERE to validate counts.
  - We warmly welcome community contributors to submit a PR with the parser enhancement and tests; we’ll gladly review and appreciate your help.
