### ISSUE TITLE
LOCK TABLES `table` write failed

### ISSUE THREAD

**Issue by dobet** [apache/shardingsphere#32289]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

5.5.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

do this success
```
lock tables `sbtest` write;
```

### Actual behavior

SQL 错误 [1146] [42S02]: Table 'sbtest_1.sbtest1' doesn't exist

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

```
create database sbtest;

use sbtest;

REGISTER STORAGE UNIT ds_0 (
	HOST="192.168.116.12",
	PORT=3306,
	DB="sbtest_0",
	USER="root",
	PASSWORD="Qwer1234"
);

REGISTER STORAGE UNIT ds_1 (
	HOST="192.168.116.12",
	PORT=3306,
	DB="sbtest_1",
	USER="root",
	PASSWORD="Qwer1234"
);

create sharding table rule sbtest1 (
	STORAGE_UNITS(ds_0,ds_1),
	SHARDING_COLUMN=id,
	TYPE(NAME="hash_mod",PROPERTIES("sharding-count"="2")),
	KEY_GENERATE_STRATEGY(COLUMN=order_id,TYPE(NAME="snowflake"))
)

create table sbtest1 (id int)

lock tables sbtest1 write;
```

**Comment by dobet** [comment]
the stack is:
```
[INFO ] 2024-07-27 00:51:27.190 [ShardingSphere-Command-0] ShardingSphere-SQL - Logic SQL: /* ApplicationName=DBeaver 24.0.0 - SQLEditor <Script-1.sql> */ create table sbtest1 (id int)
[INFO ] 2024-07-27 00:51:27.190 [ShardingSphere-Command-0] ShardingSphere-SQL - Actual SQL: ds_1 ::: /* ApplicationName=DBeaver 24.0.0 - SQLEditor <Script-1.sql> */ create table sbtest1_1 (id int)
[INFO ] 2024-07-27 00:51:27.190 [ShardingSphere-Command-0] ShardingSphere-SQL - Actual SQL: ds_0 ::: /* ApplicationName=DBeaver 24.0.0 - SQLEditor <Script-1.sql> */ create table sbtest1_0 (id int)
[INFO ] 2024-07-27 00:51:31.888 [ShardingSphere-Command-0] ShardingSphere-SQL - Logic SQL: /* ApplicationName=DBeaver 24.0.0 - SQLEditor <Script-1.sql> */ lock tables sbtest1 write
[INFO ] 2024-07-27 00:51:31.888 [ShardingSphere-Command-0] ShardingSphere-SQL - Actual SQL: ds_1 ::: /* ApplicationName=DBeaver 24.0.0 - SQLEditor <Script-1.sql> */ lock tables sbtest1 write
[INFO ] 2024-07-27 00:51:31.888 [ShardingSphere-Command-0] ShardingSphere-SQL - Actual SQL: ds_0 ::: /* ApplicationName=DBeaver 24.0.0 - SQLEditor <Script-1.sql> */ lock tables sbtest1 write
[ERROR] 2024-07-27 00:51:31.898 [ShardingSphere-Command-0] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
java.sql.SQLSyntaxErrorException: Table 'sbtest_1.sbtest1' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:770)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:787)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:102)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at org.apache.shardingsphere.proxy.backend.connector.jdbc.executor.callback.impl.ProxyStatementExecutorCallback.execute(ProxyStatementExecutorCallback.java:44)
	at org.apache.shardingsphere.proxy.backend.connector.jdbc.executor.callback.ProxyJDBCExecutorCallback.executeSQL(ProxyJDBCExecutorCallback.java:69)
	at org.apache.shardingsphere.proxy.backend.connector.jdbc.executor.callback.ProxyJDBCExecutorCallback.executeSQL(ProxyJDBCExecutorCallback.java:46)
	at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutorCallback.execute(JDBCExecutorCallback.java:85)
	at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutorCallback.execute(JDBCExecutorCallback.java:64)
	at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.syncExecute(ExecutorEngine.java:99)
	at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.parallelExecute(ExecutorEngine.java:95)
	at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.execute(ExecutorEngine.java:78)
	at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutor.execute(JDBCExecutor.java:66)
	at org.apache.shardingsphere.proxy.backend.connector.jdbc.executor.ProxyJDBCExecutor.execute(ProxyJDBCExecutor.java:73)
	at org.apache.shardingsphere.proxy.backend.connector.ProxySQLExecutor.useDriverToExecute(ProxySQLExecutor.java:217)
	at org.apache.shardingsphere.proxy.backend.connector.ProxySQLExecutor.execute(ProxySQLExecutor.java:176)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.doExecute(DatabaseConnector.java:220)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.execute(DatabaseConnector.java:173)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:86)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.doExecuteCommand(CommandExecutorTask.java:126)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:121)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:78)
	at com.alibaba.ttl.TtlRunnable.run(TtlRunnable.java:60)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

```

**Comment by dobet** [comment]
maybe is sql router error,  because get an " Table 'sbtest_1.sbtest1' doesn't exist", real table is sbtest_1.sbtest1_1.

**Comment by terrymanu** [comment]
###  Issue Understanding

  - You want ShardingSphere-Proxy (5.5.0) to truly support MySQL LOCK/UNLOCK TABLES on sharded tables instead of returning 1146 or “unsupported”.

###  Root Cause

  - Proxy currently lacks sharding semantics for LOCK/UNLOCK TABLES: table names are not rewritten and locks are not managed across shards, so the logical table is sent to each shard and the physical DB cannot find it.

###  Problem Analysis

  - The SQL is parsed as LockStatement/UnlockStatement, but rewrite does not replace logical table names with physical shards.
  - MySQL table locks require the same session/connection to hold the lock. Proxy uses per-SQL connections in autocommit; even with rewrite, the lock would be lost once the connection is returned.
  - Therefore, to support it we need both table-name rewrite/all-shard execution and connection retention during the lock lifetime.

###  Problem Conclusion (Improvement: support lock)

  - Plan highlights:
      1. Routing + rewrite: route Lock/Unlock across shards, enumerate all data nodes, and rewrite logical table names to actual shard tables.
      2. Connection lifecycle: after LOCK TABLES, pin the involved backend connections to the session (like a transaction) until UNLOCK TABLES or session close; subsequent DML/DQL reuse these connections to keep the lock.
      3. UNLOCK: also route/rewrite to all shards, execute, then release held connections.
      4. Tests & docs: add coverage for rewrite and lock effectiveness; document scope/limitations (e.g., incompatible with cross-database routing).

  Reference Implementation Sketch (Java-like pseudocode)

```java
  // 1) Add a token generator so Lock/Unlock participates in table rewrite
  class LockTableTokenGenerator implements SQLTokenGenerator<LockStatementContext> {
      @Override
      public Collection<SQLToken> generateSQLTokens(LockStatementContext ctx) {
          // generate TableToken for each SimpleTableSegment -> actual shard table
      }
  }
  // register in StandardTokenGeneratorsBuilder / ShardingTokenGeneratorsBuilder

  // 2) Ensure routing covers Lock/Unlock in ShardingRouteEngineFactory
  // produce RouteUnits over all shards

  // 3) Pin connections during lock
  if (sqlStatement instanceof LockStatement) {
      connectionSession.getTransactionStatus().setInTransaction(true);
      lockContext.bind(routeContext.getRouteUnits()); // remember and retain backend connections
  }
  if (sqlStatement instanceof UnlockStatement) {
      lockContext.release(); // release/close retained backend connections
      connectionSession.getTransactionStatus().setInTransaction(false);
  }
```

###  Testing Suggestions

  - Unit:
      - Rewrite: LOCK TABLES t_order WRITE -> LOCK TABLES t_order_0 WRITE, t_order_1…
      - Routing: Lock/Unlock produces correct RouteUnits for shards.
      - Connection pinning: Lock + subsequent DML use the same backend connection; after Unlock, it is released.
  - Integration: with two MySQL shards, run LOCK TABLES, then DML, then UNLOCK TABLES; expect no 1146 and DML succeeds.

###  Documentation

  - Update official docs (e.g., https://shardingsphere.apache.org/document/current/en/features/sharding/appendix/ and the CN counterpart) to describe sharded-table LOCK/UNLOCK TABLES support, same-session requirement, backend-connection pinning, and incompatibility with
    cross-logic-database routing.

###  Community Invitation

  - Contributions welcome: split PRs into routing/rewrite, connection pinning, and tests/docs. We’ll gladly help review and validate—thanks in advance for any PRs!
