### ISSUE TITLE
NPE occurs when selecting from db.table

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#32637]
### Which version of ShardingSphere did you use?
master 93973e3c

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Actual behavior
<img width="772" alt="image" src="https://github.com/user-attachments/assets/b1281c4e-5d1d-472c-8da7-c6cc52578c4e">

### Proxy log
```plain
java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at com.cedarsoftware.util.CaseInsensitiveMap.get(CaseInsensitiveMap.java:166)
	at org.apache.shardingsphere.infra.metadata.ShardingSphereMetaData.getDatabase(ShardingSphereMetaData.java:88)
	at org.apache.shardingsphere.proxy.backend.connector.ProxySQLExecutor.<init>(ProxySQLExecutor.java:108)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.<init>(DatabaseConnector.java:134)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnectorFactory.newInstance(DatabaseConnectorFactory.java:52)
	at org.apache.shardingsphere.proxy.backend.handler.data.DatabaseBackendHandlerFactory.newInstance(DatabaseBackendHandlerFactory.java:64)
	at org.apache.shardingsphere.proxy.backend.handler.ProxyBackendHandlerFactory.lambda$newInstance$0(ProxyBackendHandlerFactory.java:154)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at org.apache.shardingsphere.proxy.backend.handler.ProxyBackendHandlerFactory.newInstance(ProxyBackendHandlerFactory.java:154)
	at org.apache.shardingsphere.proxy.backend.handler.ProxyBackendHandlerFactory.newInstance(ProxyBackendHandlerFactory.java:97)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.<init>(MySQLComQueryPacketExecutor.java:66)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecutorFactory.newInstance(MySQLCommandExecutorFactory.java:84)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandExecutor(MySQLCommandExecuteEngine.java:59)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:120)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:78)
```

**Comment by RaigorJiang** [comment]
Fixed by #32639, #32675
