### ISSUE TITLE
connection disabled when use com.alibaba.druid.pool.DruidDataSource

### ISSUE THREAD

**Issue by HuLaLaGa** [apache/shardingsphere#32765]
### Which version of ShardingSphere did you use?

5.2.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Expected behavior

SQL normally run

### Actual behavior

SQL throw Exception(connection disabled) when use com.alibaba.druid.pool.DruidDataSource

### Reason analyze (If you can)

1. DruidConnection will disable itself when sql throw fatal exception(like 'java.sql.SQLSyntaxErrorException: INSERT command denied to user 'test_test'@'localhost' for table 'test'')。
> com.alibaba.druid.pool.DruidDataSource#handleFatalError
2. ShardingSphere don't determine if the connection is closed。
> org.apache.shardingsphere.driver.jdbc.core.connection.ConnectionManager#getConnections
3. Reuse this disabled connection will throw Exception(connection disabled)。
> com.alibaba.druid.pool.DruidPooledConnection#checkStateInternal

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

```xml
<!-- pom.xml -->
<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere-jdbc-core</artifactId>
    <version>5.2.1</version>
</dependency>
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>druid</artifactId>
    <version>1.1.23</version>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-jdbc</artifactId>
    <version>2.3.12.RELEASE</version>
</dependency>
```

```yaml
# application.yaml
spring:
  datasource:
    druid:
      driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
      url: jdbc:shardingsphere:classpath:shardingsphere.yaml
```

```yaml
# shardingsphere.yaml
databaseName: test_test
mode:
  type: Standalone
  repository:
    type: JDBC
dataSources:
  read:
    url: "jdbc:mysql://localhost:3306/test_test?characterEncoding=utf-8&useSSL=false"
    # GRANT SELECT ON test_test.* TO 'test'@'localhost';
    # GRANT SELECT ON test_test.* TO 'test'@'%';
    # test only have SELECT privilege
    username: test
    password: test
rules:
  - !READWRITE_SPLITTING
    dataSources:
      dev:
        staticStrategy:
          writeDataSourceName: read
          readDataSourceNames:
            - read
    loadBalancers:
      random:
        type: RANDOM
```

```java
// test.java
final ExecutorService threadPool = Executors.newFixedThreadPool(10);
for (int i = 0; i < 100; i++) {
  threadPool.execute(() -> {
      jdbcTemplate.execute("select ''");
      jdbcTemplate.execute("insert into test_test.the_table(name) values('test')");
  });
}
```

```text
// Exception
Exception in thread "pool-3-thread-12" org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [select '']; SQL state [null]; error code [0]; connection disabled; nested exception is java.sql.SQLException: connection disabled
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:89)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1443)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:388)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:418)
	at com.test.controller.Controller.lambda$init2$1(Controller.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: connection disabled
	at com.alibaba.druid.pool.DruidPooledConnection.checkStateInternal(DruidPooledConnection.java:1169)
	at com.alibaba.druid.pool.DruidPooledConnection.checkState(DruidPooledConnection.java:1154)
	at com.alibaba.druid.pool.DruidPooledConnection.createStatement(DruidPooledConnection.java:657)
	at org.apache.shardingsphere.driver.jdbc.core.statement.StatementManager.createStorageResource(StatementManager.java:46)
	at org.apache.shardingsphere.driver.jdbc.core.statement.StatementManager.createStorageResource(StatementManager.java:37)
	at org.apache.shardingsphere.infra.executor.sql.prepare.driver.jdbc.builder.StatementExecutionUnitBuilder.createStatement(StatementExecutionUnitBuilder.java:44)
	at org.apache.shardingsphere.infra.executor.sql.prepare.driver.jdbc.builder.StatementExecutionUnitBuilder.build(StatementExecutionUnitBuilder.java:39)
	at org.apache.shardingsphere.infra.executor.sql.prepare.driver.jdbc.builder.StatementExecutionUnitBuilder.build(StatementExecutionUnitBuilder.java:34)
	at org.apache.shardingsphere.infra.executor.sql.prepare.driver.DriverExecutionPrepareEngine.createExecutionGroup(DriverExecutionPrepareEngine.java:103)
	at org.apache.shardingsphere.infra.executor.sql.prepare.driver.DriverExecutionPrepareEngine.group(DriverExecutionPrepareEngine.java:91)
	at org.apache.shardingsphere.infra.executor.sql.prepare.AbstractExecutionPrepareEngine.prepare(AbstractExecutionPrepareEngine.java:62)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.createExecutionContext(ShardingSphereStatement.java:527)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.execute0(ShardingSphereStatement.java:473)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.execute(ShardingSphereStatement.java:384)
	at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:633)
	at org.springframework.jdbc.core.JdbcTemplate$1ExecuteStatementCallback.doInStatement(JdbcTemplate.java:409)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:376)
	... 5 more
Caused by: java.sql.SQLSyntaxErrorException: INSERT command denied to user 'test_test'@'localhost' for table 'the_table'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:762)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:646)
	at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:633)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.lambda$execute$13(ShardingSphereStatement.java:384)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement$2.executeSQL(ShardingSphereStatement.java:442)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement$2.executeSQL(ShardingSphereStatement.java:438)
	at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutorCallback.execute(JDBCExecutorCallback.java:95)
	at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutorCallback.execute(JDBCExecutorCallback.java:75)
	at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.syncExecute(ExecutorEngine.java:135)
	at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.parallelExecute(ExecutorEngine.java:131)
	at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.execute(ExecutorEngine.java:116)
	at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutor.execute(JDBCExecutor.java:65)
	at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutor.execute(JDBCExecutor.java:49)
	at org.apache.shardingsphere.driver.executor.DriverJDBCExecutor.doExecute(DriverJDBCExecutor.java:156)
	at org.apache.shardingsphere.driver.executor.DriverJDBCExecutor.execute(DriverJDBCExecutor.java:145)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.execute(ShardingSphereStatement.java:450)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.execute0(ShardingSphereStatement.java:475)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.execute(ShardingSphereStatement.java:384)
	at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:633)
	at org.springframework.jdbc.core.JdbcTemplate$1ExecuteStatementCallback.doInStatement(JdbcTemplate.java:409)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:376)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:418)
	at com.test.controller.Controller.lambda$init2$1(Controller.java:126)
	... 3 more
```

> **The Exception SQL[insert into test_test.the_table(name) values('test')] cause normal SQL[select ''] can't work**

**Comment by comecny** [comment]
It seems to be a MySQL permission issue ?

**Comment by HuLaLaGa** [comment]
> It seems to be a MySQL permission issue ?

In this case, The Exception SQL[insert into test_test.test(name) values('test')] cause normal SQL[select ''] can't work

**Comment by linghengqian** [comment]
- I introduced how to use Alibaba Druid's `StatViewServlet`, `WebStatFilter`, and custom `Filter` to monitor the logical data source and real data source of ShardingSphere JDBC at https://github.com/apache/shardingsphere/discussions/12258#discussioncomment-10427297 and https://www.yuque.com/linghengqian/meve2v/zoy35sivtf6nzp90 .
- In the relevant example, I used some virtual threads to execute the inevitable `insert` SQL with the `H2database` database instance managed by `Alibaba Druid` at a frequency of once per second, and I was completely unable to reproduce your problem. All connections pooled by `Druid` can continue to be used.
- I have noticed at least 3 `Alibaba Druid` bugs, and these bugs have existed for at least 8 years. But these bugs are actually irrelevant to your description.

1. According to https://github.com/alibaba/druid/pull/6128, alibaba/druid should not set the default value of `testWhileIdle` to true.
2. According to https://github.com/alibaba/druid/issues/5158, alibaba/druid mistakenly hard-coded `/druid/login.html`.
3. According to https://github.com/alibaba/druid/pull/6132, when Spring AOP is configured to use `CGLib` proxy, `alibaba/druid`'s Spring Boot Starter does not actively create the Spring Bean of `DefaultAdvisorAutoProxyCreator`.

- The master branch of shardingsphere contains unit tests for transactions on mysql managed by hikaricp, which cannot be reproduced from hotspot jdk or graalvm native image.
- @HuLaLaGa  I now suspect that there is a bug in the mysql jdbc driver you are using. Or there is a bug in the mysql server. I think it's necessary for you to provide a git containing unit tests, where the database should be initialized via testcontainers-java and junit5 .

**Comment by HuLaLaGa** [comment]
https://github.com/HuLaLaGa/shardingsphere-test
This project reproduce 'connection disabled' Exception when use both ShardingSphere and Druid @linghengqian

**Comment by terrymanu** [comment]
Can not support Druid, the connection pool supported list please see: shardingsphere-infra-data-source-pool-type

**Comment by linghengqian** [comment]
- `alibaba/druid` has changed in https://github.com/alibaba/druid/pull/5796 , which makes the behavior of `com.alibaba:druid-spring-boot-starter:1.2.23` actually close to `brettwooldridge/HikariCP`, although I am sure that due to the deliberate design of `apache/hive`, you can't actually use `alibaba/druid` to connect to HiveServer2 using the configuration file in ShardingSphere. 
- I am observing whether it is because `org.apache.shardingsphere.infra.datasource.pool.destroyer.DataSourcePoolActiveDetector` is not implemented. By the way, the version of `com.alibaba:druid-spring-boot-starter` you are using in https://github.com/HuLaLaGa/shardingsphere-test is too old. It registers multiple problematic Spring Beans.

**Comment by linghengqian** [comment]
- **I would say that `alibaba/druid` is weaker than I thought.** The JDBC Driver parsing method of `alibaba/druid` is hard-coded, which makes it impossible for `alibaba/druid` to use the testcontainers-java style JDBC URL. Based on this alone, I would never support adding integration tests for `alibaba/druid` in the master branch of shardingsphere, because this absolutely breaks the best practices defined by testcontainers-java. 🫠
```shell
11:28:57.213 [main] ERROR com.alibaba.druid.pool.DruidDataSource - {dataSource-1} init error
java.sql.SQLException: unknown jdbc driver : jdbc:tc:mysql:5.7.34://test-databases-mysql/the_database&TC_INITSCRIPT=init-schema.sql
	at com.alibaba.druid.util.JdbcUtils.getDriverClassName(JdbcUtils.java:545)
	at com.alibaba.druid.pool.DruidDataSource.resolveDriver(DruidDataSource.java:1255)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:885)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1471)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1463)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:83)
	at org.apache.shardingsphere.infra.datasource.pool.CatalogSwitchableDataSource.getConnection(CatalogSwitchableDataSource.java:46)
```
- @HuLaLaGa  I made some changes to your unit test at https://github.com/linghengqian/shardingsphere-test/commit/9a78f43b83e930668817dbe9f8f4e7189855785b . I can't reproduce the problem on shardingsphere 5.5.0 and druid 1.2.23 .
```shell
sdk install java 8.0.422-tem
git clone git@github.com:linghengqian/shardingsphere-test.git
cd ./shardingsphere-test/
sdk use java 8.0.422-tem
./mvnw -T 1C clean test 
```
- The unit tests execute fine.
```shell
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.55 s -- in com.hulalaga.ShardingSphereTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.956 s
[INFO] Finished at: 2024-09-25T12:06:17+08:00
[INFO] ------------------------------------------------------------------------
```
- There is a problem with your `init-schema.sql`. You are trying to execute `revoke all privileges, grant option from 'test'@'%';` as a non-root user. This obviously violates the discussion of https://github.com/testcontainers/testcontainers-java/discussions/4545. But I don't see you initialize the root user of mysql server.

**Comment by linghengqian** [comment]
- We can certainly put aside MySQL permissions to narrow the scope of discussion. I deliberately executed the problematic insert SQL `INSERT INTO t_order_item_does_not_exist (test_id_does_not_exist) VALUES (2024)` in https://github.com/linghengqian/shardingsphere-test/commit/aa2365a38f9eba2250f1f1a4a839777c1dddb4a0. The `t_order_item_does_not_exist` table does not exist at all.
- The unit tests still work fine.
```shell
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.55 s -- in com.hulalaga.ShardingSphereTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.236 s (Wall Clock)
[INFO] Finished at: 2024-09-25T12:25:36+08:00
[INFO] ------------------------------------------------------------------------
```

**Comment by HuLaLaGa** [comment]
> * We can certainly put aside MySQL permissions to narrow the scope of discussion. I deliberately executed the problematic insert SQL `INSERT INTO t_order_item_does_not_exist (test_id_does_not_exist) VALUES (2024)` in [linghengqian/shardingsphere-test@aa2365a](https://github.com/linghengqian/shardingsphere-test/commit/aa2365a38f9eba2250f1f1a4a839777c1dddb4a0). The `t_order_item_does_not_exist` table does not exist at all.
> * The unit tests still work fine.
> 
> ```shell
> [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.55 s -- in com.hulalaga.ShardingSphereTest
> [INFO] 
> [INFO] Results:
> [INFO] 
> [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
> [INFO] 
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  16.236 s (Wall Clock)
> [INFO] Finished at: 2024-09-25T12:25:36+08:00
> [INFO] ------------------------------------------------------------------------
> ```

TableNotExist Exception is not regarded as fatal error by Druid，instead of AccessDenied Exception is regarded as fatal error。And only fatal error can trigger 'connection disabled' Exception。

**Comment by HuLaLaGa** [comment]
> * **I would say that `alibaba/druid` is weaker than I thought.** The JDBC Driver parsing method of `alibaba/druid` is hard-coded, which makes it impossible for `alibaba/druid` to use the testcontainers-java style JDBC URL. Based on this alone, I would never support adding integration tests for `alibaba/druid` in the master branch of shardingsphere, because this absolutely breaks the best practices defined by testcontainers-java. 🫠
> 
> ```shell
> 11:28:57.213 [main] ERROR com.alibaba.druid.pool.DruidDataSource - {dataSource-1} init error
> java.sql.SQLException: unknown jdbc driver : jdbc:tc:mysql:5.7.34://test-databases-mysql/the_database&TC_INITSCRIPT=init-schema.sql
> 	at com.alibaba.druid.util.JdbcUtils.getDriverClassName(JdbcUtils.java:545)
> 	at com.alibaba.druid.pool.DruidDataSource.resolveDriver(DruidDataSource.java:1255)
> 	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:885)
> 	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1471)
> 	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1463)
> 	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:83)
> 	at org.apache.shardingsphere.infra.datasource.pool.CatalogSwitchableDataSource.getConnection(CatalogSwitchableDataSource.java:46)
> ```
> 
> * @HuLaLaGa  I made some changes to your unit test at [linghengqian/shardingsphere-test@9a78f43](https://github.com/linghengqian/shardingsphere-test/commit/9a78f43b83e930668817dbe9f8f4e7189855785b) . I can't reproduce the problem on shardingsphere 5.5.0 and druid 1.2.23 .
> 
> ```shell
> sdk install java 8.0.422-tem
> git clone git@github.com:linghengqian/shardingsphere-test.git
> cd ./shardingsphere-test/
> sdk use java 8.0.422-tem
> ./mvnw -T 1C clean test 
> ```
> 
> ```java
> IntStream.range(0, 50).forEachOrdered(i -> {
>             assertDoesNotThrow(() -> JDBC_TEMPLATE.execute("select ''"));
>             assertDoesNotThrow(() -> JDBC_TEMPLATE.execute("insert into the_table(id) values(1)"));
>         });
> ```
> 
> * The unit tests execute fine.
> 
> ```shell
> [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.55 s -- in com.hulalaga.ShardingSphereTest
> [INFO] 
> [INFO] Results:
> [INFO] 
> [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
> [INFO] 
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  16.956 s
> [INFO] Finished at: 2024-09-25T12:06:17+08:00
> [INFO] ------------------------------------------------------------------------
> ```
> 
> * There is a problem with your `init-schema.sql`. You are trying to execute `revoke all privileges, grant option from 'test'@'%';` as a non-root user. This obviously violates the discussion of [Access denied; you need (at least one of) the CREATE USER privilege(s) for this operation testcontainers/testcontainers-java#4545](https://github.com/testcontainers/testcontainers-java/discussions/4545). But I don't see you initialize the root user of mysql server.

**Reproduce 'connection disabled' Exception need these steps as listed below**

1. Use DruidConnection to execute 'Fatal Exception' SQL，such as AccessDenied...
2. Reuse this DruidConnection to execute any SQL, will produce 'connection disabled' Exception

> 'Fatal Exception' defined in Class com.alibaba.druid.pool.vendor.MySqlExceptionSorter

**Comment by linghengqian** [comment]
> * @linghengqian I updated ShardingSphere version to 5.50，and made changes follow your code at [HuLaLaGa/shardingsphere-test](https://github.com/HuLaLaGa/shardingsphere-test/tree/main)

- I have reproduced the current issue at https://github.com/linghengqian/shardingsphere-test/commit/240dfe75848179430abed11667c6da980a55da62 . I started mysql server directly with `root` account and empty password, and created `readonly` user dynamically. I also added unit test without shardingsphere to prove that it was a bug of shardingsphere.
- After implementing the SPI of `org.apache.shardingsphere.infra.datasource.pool.destroyer.DataSourcePoolActiveDetector`, I found a very strange thing. According to debugging, `org.apache.shardingsphere.infra.datasource.pool.destroyer.DataSourcePoolDestroyer` has never been called.🤯
- ![image](https://github.com/user-attachments/assets/95a107a4-b1a1-435c-bb46-2e4dfd1fc257)
- Let me think what happened, it means that `org.apache.shardingsphere:shardingsphere-infra-data-source-pool-core` is not playing its role at all. Of course I also assume that some friends have prepared PR. I have no idea about this phenomenon.

**Comment by linghengqian** [comment]
- As part of testing ShardingSphere 5.5.1-SNAPSHOT at https://github.com/linghengqian/shardingsphere-test/commit/d7261e1c57feaada4bdf85c460bb101c7f047905 , I think it is necessary to generate Source JAR when building shardingsphere to facilitate debugging. I have opened #33000.

**Comment by linghengqian** [comment]
- That being said, if you replace `com.alibaba.druid.pool.DruidDataSource` with `com.alibaba.druid.pool.DruidDataSource` in `src/test/resources/shardingsphere.yaml`, this problem does not exist.😅The logic of Druid actively closing connections was introduced through https://github.com/alibaba/druid/commit/882470b1ce7a51a94f3525beceec91384ccd425f . At least the Spring Boot community and the Flyway community believe that HikariCP's processing is more intuitive.
- See https://github.com/alibaba/druid/blob/1.2.23/core/src/main/java/com/alibaba/druid/pool/DruidDataSource.java#L1937 .
```java
if ((!conn.closed) && !conn.disable) {
                conn.disable(error);
                requireDiscard = true;
}
```

**Comment by linghengqian** [comment]
- Once alibaba druid approves the PR and releases a new version, I will update the shardingsphere documentation.

**Comment by linghengqian** [comment]
Since no druid committer has reviewed the corresponding PR for more than two weeks, I believe this is a bug that is intentionally buried in druid. I will not update the shardingsphere document for the current issue because it will take longer to wait.

**Comment by linghengqian** [comment]
This is actually 6 known issues on the druid side, no point trying to track it on the shardingsphere side.

**Comment by wangsansan** [comment]
spring:
  datasource:
    druid:
      test-on-borrow: true
      validation-query: SELECT 1


=========================================
i add above config, fixed my problem. 
here is my blog about this problem: https://blog.csdn.net/liangsheng_g/article/details/163125300?spm=1001.2014.3001.5501

**Comment by linghengqian** [comment]
You can simply address the issue on the Druid side. Even if you were to fix ShardingSphere without fixing Druid, you would still encounter similar problems with Flyway.
