### ISSUE TITLE
5.5.0 version，oracle Federation mode failed

### ISSUE THREAD

**Issue by zhouxinhai** [apache/shardingsphere#32802]
I use 5.5.0 version，run in Federation mode。

sql is simple:   "SELECT count(1)  FROM USER_INFO A1, USER_COMPANY B1 where A1.USER_ID = B1.USER_ID and A1.USER_ID = 10001000"

table USER_INFO and USER_COMPANY  are in different datasouce
If database is mysql, run success. But if database is oracle run failed

```
14:39:15.725 [main] INFO ShardingSphere-SQL - Logic SQL: SELECT * FROM `logic_db`.`USER_INFO` WHERE CAST(`USER_ID` AS SIGNED) = 10001000
14:39:15.725 [main] INFO ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `USER_INFO` WHERE CAST(`USER_ID` AS SIGNED) = 10001000
14:39:15.728 [main] INFO ShardingSphere-SQL - Logic SQL: SELECT * FROM `logic_db`.`USER_COMPANY` WHERE CAST(`USER_ID` AS SIGNED) = 10001000
14:39:15.728 [main] INFO ShardingSphere-SQL - Actual SQL: ds_1 ::: SELECT * FROM `USER_COMPANY` WHERE CAST(`USER_ID` AS SIGNED) = 10001000
Exception in thread "main" java.sql.SQLException: SQL federation does not support SQL 'SELECT count(1)  FROM USER_INFO A1, USER_COMPANY B1 where A1.USER_ID = B1.USER_ID and A1.USER_ID = 10001000'.
	at org.apache.shardingsphere.infra.exception.core.external.sql.ShardingSphereSQLException.toSQLException(ShardingSphereSQLException.java:76)
	at org.apache.shardingsphere.infra.exception.dialect.SQLExceptionTransformEngine.toSQLException(SQLExceptionTransformEngine.java:54)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.executeQuery(ShardingSpherePreparedStatement.java:253)
	at indi.zhouxh.main.singleTest(main.java:109)
	at indi.zhouxh.main.main(main.java:28)
```

shardingsphere.yml:

```
sqlFederation:
  sqlFederationEnabled: true
  allQueryUseSQLFederation: false
  executionPlanCache:
    initialCapacity: 2000
    maximumSize: 65535
```

**Comment by strongduanmu** [comment]
Yes, SQL Federation just support MySQL, PostgreSQL and openGauss. Other databases are not yet compatible.

**Comment by zhouxinhai** [comment]
> Yes, SQL Federation just support MySQL, PostgreSQL and openGauss. Other databases are not yet compatible.

In the future, is there any plan to support Oracle? Which version will be supported?

**Comment by strongduanmu** [comment]
There is no plan to support Oracle yet. Open source MySQL and PostgreSQL are given higher priority. If you are interested, you are welcome to participate in the development of SQL Federation.
