### ISSUE TITLE
After integrating shardingsphere-jdbc-core 5.3.0 and flowable 6.6.8 into a project, an error occurs when starting the project.

### ISSUE THREAD

**Issue by yanwencheng** [apache/shardingsphere#32812]
After integrating shardingsphere-jdbc-core 5.3.0 and flowable 6.6.8 into a project, an error occurs when starting the project.
```
Caused by: org.flowable.common.engine.api.FlowableException: couldn't check if tables are already present using metadata: getStatement
	at org.flowable.common.engine.impl.db.AbstractSqlScriptBasedDbSchemaManager.isTablePresent(AbstractSqlScriptBasedDbSchemaManager.java:176)
	at org.flowable.common.engine.impl.db.AbstractSqlScriptBasedDbSchemaManager.getProperty(AbstractSqlScriptBasedDbSchemaManager.java:191)
	at org.flowable.common.engine.impl.db.ServiceSqlScriptBasedDbSchemaManager.getSchemaVersion(ServiceSqlScriptBasedDbSchemaManager.java:116)
	at org.flowable.idm.engine.impl.db.IdmDbSchemaManager.schemaCheckVersion(IdmDbSchemaManager.java:75)
	at org.flowable.idm.engine.impl.db.IdmDbSchemaManager.performSchemaOperationsIdmEngineBuild(IdmDbSchemaManager.java:148)
	at org.flowable.idm.engine.impl.SchemaOperationsIdmEngineBuild.execute(SchemaOperationsIdmEngineBuild.java:29)
	at org.flowable.idm.engine.impl.SchemaOperationsIdmEngineBuild.execute(SchemaOperationsIdmEngineBuild.java:24)
	at org.flowable.common.engine.impl.interceptor.DefaultCommandInvoker.execute(DefaultCommandInvoker.java:22)
	at org.flowable.common.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:53)
	at org.flowable.common.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:105)
	at org.flowable.common.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30)
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56)
	at org.flowable.idm.engine.impl.IdmEngineImpl.<init>(IdmEngineImpl.java:46)
	at org.flowable.idm.engine.IdmEngineConfiguration.buildIdmEngine(IdmEngineConfiguration.java:164)
	at org.flowable.idm.engine.configurator.IdmEngineConfigurator.configure(IdmEngineConfigurator.java:57)
	at org.flowable.common.engine.impl.AbstractEngineConfiguration.configuratorsAfterInit(AbstractEngineConfiguration.java:1121)
	at org.flowable.engine.impl.cfg.ProcessEngineConfigurationImpl.init(ProcessEngineConfigurationImpl.java:1022)
	at org.flowable.engine.impl.cfg.ProcessEngineConfigurationImpl.buildProcessEngine(ProcessEngineConfigurationImpl.java:906)
	at org.flowable.spring.SpringProcessEngineConfiguration.buildProcessEngine(SpringProcessEngineConfiguration.java:76)
	at org.flowable.spring.ProcessEngineFactoryBean.getObject(ProcessEngineFactoryBean.java:59)
	at org.flowable.spring.ProcessEngineFactoryBean.getObject(ProcessEngineFactoryBean.java:32)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:171)
	... 78 common frames omitted
Caused by: java.sql.SQLFeatureNotSupportedException: getStatement
	at org.apache.shardingsphere.driver.jdbc.unsupported.AbstractUnsupportedDatabaseMetaDataResultSet.getStatement(AbstractUnsupportedDatabaseMetaDataResultSet.java:92)
	at com.zaxxer.hikari.pool.ProxyDatabaseMetaData.getTables(ProxyDatabaseMetaData.java:70)
	at com.zaxxer.hikari.pool.HikariProxyDatabaseMetaData.getTables(HikariProxyDatabaseMetaData.java)
	at org.flowable.common.engine.impl.db.AbstractSqlScriptBasedDbSchemaManager.isTablePresent(AbstractSqlScriptBasedDbSchemaManager.java:163)
	... 99 common frames omitted
```

**Comment by linghengqian** [comment]
- You need to provide git with reproducible unit tests. In unit tests, database and middleware should be started via `testcontainers-java`.

**Comment by yanwencheng** [comment]
> * You need to provide git with reproducible unit tests. In unit tests, database and middleware should be started via `testcontainers-java`.

How do you do the unit tests you are talking about? Do you have an example?

**Comment by linghengqian** [comment]
You showed the Error Log, but I didn't. You need to provide reproducible steps for your Error Log. The master branch currently does not have any unit tests for flowable.

**Comment by yanwencheng** [comment]
> You showed the Error Log, but I didn't. You need to provide reproducible steps for your Error Log. The master branch currently does not have any unit tests for flowable.

Hello, the project integrates flowable 6.6.8, an error is reported at startup, and the current breakpoint is found to be because the url configured by spring's datasource is the sharding configuration file address, resulting in the initial data source error of flowable, and the solution is to manually set the data source when flowable is configured. The question is how can I get the default data source for sharding?

**Comment by linghengqian** [comment]
> > You showed the Error Log, but I didn't. You need to provide reproducible steps for your Error Log. The master branch currently does not have any unit tests for flowable.
> 
> Hello, the project integrates flowable 6.6.8, an error is reported at startup, and the current breakpoint is found to be because the url configured by spring's datasource is the sharding configuration file address, resulting in the initial data source error of flowable, and the solution is to manually set the data source when flowable is configured. The question is how can I get the default data source for sharding?

- If you can't provide a reproducible unit test, I would say it's not related to shardingsphere. You should ask the flowable community about the problem you encountered. Because it will obviously become a bug in flowable.
- shardingsphere intentionally blocks operations on the real database, and all operations are only for the logical database.

**Comment by linghengqian** [comment]
I think this is a design flaw in flowable. They are intentionally incompatible with the shardingsphere.
