### ISSUE TITLE
AES  encrypt   bug

### ISSUE THREAD

**Issue by 15102552479** [apache/shardingsphere#33026]
AES  encrypt   bug:sharding-sphere4.1.1
1.table 
CREATE TABLE `test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `patient_id` varchar(255) DEFAULT NULL,
  `visit_sn` varchar(255) DEFAULT NULL,
  `visit_en` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;
//2. use sql: select * from (select ISNULL(GROUP_CONCAT(id)) as ids ,patient_id, visit_sn from test GROUP BY patient_id) a;
//3.encrypt   column  visit_sn
//4.Exception
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.apache.shardingsphere.encrypt.merge.dql.EncryptorMetaData.findEncryptor(EncryptorMetaData.java:49)
	at org.apache.shardingsphere.encrypt.merge.dql.EncryptMergedResult.getValue(EncryptMergedResult.java:51)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.resultset.ShardingResultSet.getString(ShardingResultSet.java:161)
	at com.roy.demo.ShardingJDBCDemo.querycourse(ShardingJDBCDemo.java:148)
	at com.roy.demo.ShardingJDBCDemo.main(ShardingJDBCDemo.java:115)

**Comment by 15102552479** [comment]
1.table

**Comment by terrymanu** [comment]
The version is out of service, please try new version.
