### ISSUE TITLE
Table or view 'not support' does not exist.

### ISSUE THREAD

**Issue by MyHeart0** [apache/shardingsphere#33342]
[javaCode.md](https://github.com/user-attachments/files/17469554/javaCode.md)

This is a ShardingSphere configured using Java code, version 5.5.0. In the above code, there is a user table that does not require the use of ShardingSphere. It is a single table, and I have configured

SingleRuleConfiguration ruleConfig=new SingleRuleConfiguration();
ruleConfig.setTables(Arrays.asList("ds_2024.user"));

Why does the error 'Table or view' not support 'do not exist

**Comment by strongduanmu** [comment]
Hi, can you try the latest 5.5.1? we have fixed this bug.

**Comment by MyHeart0** [comment]
> 嗨，您可以试用最新的 5.5.1 吗？我们已修复此错误。
The latest version on GitHub is only 5.5.0, I haven't seen 5.5.1

**Comment by self-made-boy** [comment]
我试了 5.5.0 和5.5.1 都有相同问题。
具体信息如下：

pom 如下依赖
```xml
 <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc</artifactId>
<!--            <version>5.5.0</version>-->
            <version>5.5.1</version>
        </dependency>
```
 使用 yaml配置的方式，配置如下：
 
```yml
mode:
  type: Standalone
  repository:
    type: JDBC

# 数据源配置
dataSources:
  master:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql:xxxx:3306/xxxxx?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: xxxx
    password: xxxxx
  slave:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql:xxxx:3306/xxxxx?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: xxxx
    password: xxxxx
    

rules:
  - !READWRITE_SPLITTING
    dataSourceGroups:
      readwrite_ds:
        writeDataSourceName: master
        readDataSourceNames:
          - slave
        loadBalancerName: round_robin
    loadBalancers:
      round_robin:
        type: ROUND_ROBIN
props:
  sql.show: true
```

详细报错如下：
```
Caused by: org.apache.ibatis.executor.ExecutorException: Error preparing statement.  Cause: org.apache.shardingsphere.infra.exception.kernel.metadata.TableNotFoundException: Table or view 'perms_operation' does not exist.
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:99) ~[mybatis-3.5.16.jar:3.5.16]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:60) ~[mybatis-3.5.16.jar:3.5.16]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:569) ~[na:na]
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:61) ~[mybatis-3.5.16.jar:3.5.16]
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:106) ~[mybatis-plus-extension-3.5.7.jar:3.5.7]
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:59) ~[mybatis-3.5.16.jar:3.5.16]
	at jdk.proxy2/jdk.proxy2.$Proxy127.prepare(Unknown Source) ~[na:na]
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:90) ~[mybatis-3.5.16.jar:3.5.16]
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:64) ~[mybatis-3.5.16.jar:3.5.16]
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:336) ~[mybatis-3.5.16.jar:3.5.16]
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:158) ~[mybatis-3.5.16.jar:3.5.16]
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:110) ~[mybatis-3.5.16.jar:3.5.16]
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:81) ~[mybatis-plus-extension-3.5.7.jar:3.5.7]
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:59) ~[mybatis-3.5.16.jar:3.5.16]
	at jdk.proxy2/jdk.proxy2.$Proxy126.query(Unknown Source) ~[na:na]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:154) ~[mybatis-3.5.16.jar:3.5.16]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147) ~[mybatis-3.5.16.jar:3.5.16]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:142) ~[mybatis-3.5.16.jar:3.5.16]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:569) ~[na:na]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:425) ~[mybatis-spring-3.0.3.jar:3.0.3]
	... 48 common frames omitted
Caused by: org.apache.shardingsphere.infra.exception.kernel.metadata.TableNotFoundException: Table or view 'perms_operation' does not exist.
	at org.apache.shardingsphere.infra.binder.engine.segment.from.type.SimpleTableSegmentBinder.lambda$checkTableExists$3(SimpleTableSegmentBinder.java:130) ~[shardingsphere-infra-binder-5.5.1.jar:5.5.1]
	at org.apache.shardingsphere.infra.exception.core.ShardingSpherePreconditions.checkState(ShardingSpherePreconditions.java:44) ~[shardingsphere-infra-exception-core-5.5.1.jar:5.5.1]
	at org.apache.shardingsphere.infra.binder.engine.segment.from.type.SimpleTableSegmentBinder.checkTableExists(SimpleTableSegmentBinder.java:127) ~[shardingsphere-infra-binder-5.5.1.jar:5.5.1]
	at org.apache.shardingsphere.infra.binder.engine.segment.from.type.SimpleTableSegmentBinder.bind(SimpleTableSegmentBinder.java:84) ~[shardingsphere-infra-binder-5.5.1.jar:5.5.1]
	at org.apache.shardingsphere.infra.binder.engine.segment.from.TableSegmentBinder.bind(TableSegmentBinder.java:57) ~[shardingsphere-infra-binder-5.5.1.jar:5.5.1]
	at org.apache.shardingsphere.infra.binder.engine.statement.dml.SelectStatementBinder.lambda$bind$0(SelectStatementBinder.java:54) ~[shardingsphere-infra-binder-5.5.1.jar:5.5.1]
	at java.base/java.util.Optional.map(Optional.java:260) ~[na:na]
	at org.apache.shardingsphere.infra.binder.engine.statement.dml.SelectStatementBinder.bind(SelectStatementBinder.java:54) ~[shardingsphere-infra-binder-5.5.1.jar:5.5.1]
	at org.apache.shardingsphere.infra.binder.engine.type.DMLStatementBindEngine.bind(DMLStatementBindEngine.java:52) ~[shardingsphere-infra-binder-5.5.1.jar:5.5.1]
	at org.apache.shardingsphere.infra.binder.engine.SQLBindEngine.bindSQLStatement(SQLBindEngine.java:63) ~[shardingsphere-infra-binder-5.5.1.jar:5.5.1]
	at org.apache.shardingsphere.infra.binder.engine.SQLBindEngine.bind(SQLBindEngine.java:53) ~[shardingsphere-infra-binder-5.5.1.jar:5.5.1]
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.<init>(ShardingSpherePreparedStatement.java:146) ~[shardingsphere-jdbc-5.5.1.jar:5.5.1]
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.<init>(ShardingSpherePreparedStatement.java:117) ~[shardingsphere-jdbc-5.5.1.jar:5.5.1]
	at org.apache.shardingsphere.driver.jdbc.core.connection.ShardingSphereConnection.prepareStatement(ShardingSphereConnection.java:111) ~[shardingsphere-jdbc-5.5.1.jar:5.5.1]
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:328) ~[HikariCP-5.1.0.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java) ~[HikariCP-5.1.0.jar:na]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:88) ~[mybatis-3.5.16.jar:3.5.16]
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:90) ~[mybatis-3.5.16.jar:3.5.16]
	... 73 common frames omitted
```

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by MyHeart0** [comment]
How should I use version 5.5.1

**Comment by MyHeart0** [comment]
Sorry, I just upgraded to version 5.5.1 and configured the name and default data source for each table according to the official documentation, but it still prompts me

Table or view 'not support' does not exist.

May I ask why this is? The name of a single table is' user ', but why is the error reported as the name of another non-existent table? Here is the code

    SingleRuleConfiguration ruleConfig = new SingleRuleConfiguration();
    ruleConfig.setTables(Arrays.asList("ds_2024.user"));
    ruleConfig.setDefaultDataSource("ds_2024");

**Comment by MyHeart0** [comment]
Ladies and gentlemen, the above issue has been resolved. The reason is that the single table name I created in the PostgreSQL database was' user ', which can be used normally by changing it to' tb_user '. However, I have consulted the PostgreSQL documentation and found that the naming convention for table names does not require an underline, but in reality, adding an underline is necessary to use the single table properly
