### ISSUE TITLE
 Cannot invoke "String.split(String)" because "attributes" is null

### ISSUE THREAD

**Issue by wuqiong818** [apache/shardingsphere#33566]
## Bug Report
 [ERROR] 2024-11-06 09:19:45.994 [Etcd-EventListener-0] o.a.s.m.r.c.etcd.EtcdRepository - Dispatch event failed
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "String.split(String)" because "attributes" is null
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException: Cannot invoke "String.split(String)" because "attributes" is null
        at org.apache.shardingsphere.infra.instance.metadata.proxy.ProxyInstanceMetaData.<init>(ProxyInstanceMetaData.java:52)
        at org.apache.shardingsphere.infra.instance.metadata.InstanceMetaDataFactory.create(InstanceMetaDataFactory.java:41)
        at org.apache.shardingsphere.mode.manager.cluster.event.builder.ComputeNodeOnlineDispatchEventBuilder.createInstanceEvent(ComputeNodeOnlineDispatchEventBuilder.java:66)
        at org.apache.shardingsphere.mode.manager.cluster.event.builder.ComputeNodeOnlineDispatchEventBuilder.build(ComputeNodeOnlineDispatchEventBuilder.java:57)
        at org.apache.shardingsphere.mode.manager.cluster.listener.GlobalMetaDataChangedListener.onChange(GlobalMetaDataChangedListener.java:39)
        at org.apache.shardingsphere.mode.repository.cluster.etcd.EtcdRepository.lambda$dispatchEvent$3(EtcdRepository.java:191)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        ... 3 common frames omitted

**Comment by wuqiong818** [comment]
my configuratioin
**global.yaml**

`mode:
  type: Cluster
  repository:
    type: etcd
    props:
      namespace: governance_ds
      server-lists: http://124.156.192.247:11094
      props:
        timeToLiveSeconds: 30
        connectionTimeout: 30
        
authority:
  users:
    - user: root@%
      password: root
  privilege:
    type: ALL_PERMITTED

props:
  sql-show: true`

**Comment by wuqiong818** [comment]
my use version is ShardingSphere-Proxy:5.5.1

**Comment by terrymanu** [comment]
How to reproduce it?

**Comment by wuqiong818** [comment]
An error was reported while I was loading the following configuration file in cluster mode.
I used ShardingSphere-Proxy:5.5.1
global.yaml

`mode:
type: Cluster
repository:
type: etcd
props:
namespace: governance_ds
server-lists: http://124.156.192.247:11094/
props:
timeToLiveSeconds: 30
connectionTimeout: 30

authority:
users:
- user: root@%
password: root
privilege:
type: ALL_PERMITTED

props:
sql-show: true`

**Comment by terrymanu** [comment]
What's mean `I was loading the following configuration file in cluster mode.`?
What are the actual reproduce steps?

**Comment by wuqiong818** [comment]
i'm run k8s environment。
Below is my startup file
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    k8s.kuboard.cn/displayName: ShardingSphere测试学习版
  labels:
    k8s.kuboard.cn/layer: cloud
    k8s.kuboard.cn/name: shardingsphere01
  name: shardingsphere01
  namespace: sharding
  resourceVersion: '11745742'
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: cloud
      k8s.kuboard.cn/name: shardingsphere01
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2024-11-07T11:56:06+08:00'
      creationTimestamp: null
      labels:
        k8s.kuboard.cn/layer: cloud
        k8s.kuboard.cn/name: shardingsphere01
        pod-template-hash: 54568c578f
    spec:
      containers:
        - env:
            - name: JVM_OPTS
              value: '"-Xms256m -Xmx400m -Xss1m"'
          image: 'yiwuqiong/sharding-etcd:3.0'
          imagePullPolicy: Always
          name: shardingproxy
          ports:
            - containerPort: 3307
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 400Mi
            requests:
              cpu: 200m
              memory: 200Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/shardingsphere-proxy/conf
              name: volume-3zhmw
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: shardingproxyconf
          name: volume-3zhmw
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2024-11-07T03:56:08Z'
      lastUpdateTime: '2024-11-07T03:56:08Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2024-10-25T08:25:40Z'
      lastUpdateTime: '2024-11-07T03:56:08Z'
      message: ReplicaSet "shardingsphere01-79cf67c5fb" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 146
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/layer: cloud
    k8s.kuboard.cn/name: shardingsphere01
  name: shardingsphere01
  namespace: sharding
  resourceVersion: '11346122'
spec:
  clusterIP: 10.43.228.205
  clusterIPs:
    - 10.43.228.205
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: phpwwx
      nodePort: 1226
      port: 3307
      protocol: TCP
      targetPort: 3307
  selector:
    k8s.kuboard.cn/layer: cloud
    k8s.kuboard.cn/name: shardingsphere01
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
