### ISSUE TITLE
Caused by: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.

### ISSUE THREAD

**Issue by WangYehen** [apache/shardingsphere#33674]
## Bug Report

**For English only**, other languages will not accept.
Dear experts, please help solve the problem. My springboot project version is 3.2.4, JDK version is 17, and shardingsphere jdbc core Maven dependency version is 5.4.1. The project startup error is as follows:

2024-11-15 06:57:32.645 renpho-wms sharding 1552 -ERROR [28011009355278264705024,] - [XNIO-1 task-2] com.zaxxer.hikari.pool.HikariPool : HikariPool-1 - Exception during pool initialization.
javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:278)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:421)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:721)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:662)
	at org.apache.shardingsphere.mode.repository.standalone.jdbc.sql.JDBCRepositorySQLLoader.loadFromJar(JDBCRepositorySQLLoader.java:113)
	at org.apache.shardingsphere.mode.repository.standalone.jdbc.sql.JDBCRepositorySQLLoader.load(JDBCRepositorySQLLoader.java:72)
	at org.apache.shardingsphere.mode.repository.standalone.jdbc.JDBCRepository.init(JDBCRepository.java:59)
	at org.apache.shardingsphere.infra.spi.type.typed.TypedSPILoader.findDefaultService(TypedSPILoader.java:73)
	at org.apache.shardingsphere.infra.spi.type.typed.TypedSPILoader.findService(TypedSPILoader.java:57)
	at org.apache.shardingsphere.infra.spi.type.typed.TypedSPILoader.getService(TypedSPILoader.java:110)

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core</artifactId>
            <version>5.4.1</version>
        </dependency>
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

**Comment by linghengqian** [comment]
- Fixed by https://github.com/apache/shardingsphere/pull/29384 . Just use 5.5.0 or 5.5.1.

**Comment by WangYehen** [comment]
> * 修复者[删除了通过 jackson-dataformat-xml 的 JAXB API 的使用 #29384](https://github.com/apache/shardingsphere/pull/29384).只需使用 5.5.0 或 5.5.1。

thank u
