### ISSUE TITLE
Intermittent Emoji Storage Error with MySQL while using sharding sphere proxy.

### ISSUE THREAD

**Issue by ashish19977** [apache/shardingsphere#33888]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
i want to store emojies in my database.

### Actual behavior
It is failing intermittently to store emojies. And when i restart ShardingSphere-Proxy it solves the issue for a while but onces error starts coming it continues to comes until next restart.

_Error - Incorrect string value: '\xF0\x9F\x8C\xBB' for column 'appointment_data' at row 1_

### Reason analyze (If you can)

[solutions i have tried](https://github.com/apache/shardingsphere/issues/13023)

I have applied all the solutions mentioned above, but the problem still persists in my case. Sometimes it gives an error, and sometimes it works when I'm storing emojis. The issue gets resolved temporarily when I restart the proxy; after the restart, the error disappears for a while, but it reappears after some time. Once the error starts occurring, it continues to happen until I restart again.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

Here are my JDBC URLs for both datasources:
`jdbc:mysql://127.0.0.1:3306/portal-uat-1?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&character_set_server=utf8mb4&connectionCollation=utf8mb4_bin`

`jdbc:mysql://127.0.0.1:3306/portal-uat2?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&character_set_server=utf8mb4&connectionCollation=utf8mb4_bin`

Column charset and table charset is same across both the datasources.
```
Column schema charset - appointment_data longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin
Table schema charset - CHARSET=utf8mb4
```

**Comment by terrymanu** [comment]
The markdown format in your issue is incorrect. To facilitate reading, could you please revise it?

**Comment by terrymanu** [comment]
What is the rule configuration?

**Comment by ashish19977** [comment]
**Rule Configuration is** - sharding rule

**And this is how it looks in sharding rules table -** 

`{table : "appointment_data",
  actual_data_nodes : "ds_${0..1}.appointment_data",
  actual_data_sources : "",
  database_strategy_type : "STANDARD",
  database_sharding_column : "practice_id",
  database_sharding_algorithm_type : "custom",
  database_sharding_algorithm_props : "",
  table_strategy_type : "",
  table_sharding_column : "",
  table_sharding_algorithm_type : "",
  table_sharding_algorithm_props : "",
  key_generate_column : "",
  key_generator_type : "",
  key_generator_props : "",
  auditor_types : "",
  allow_hint_disable : ""}`
  
  
  
  **Stack Trace -** 

`	at java.base/java.lang.Thread.run(Thread.java:833)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at com.alibaba.ttl.TtlRunnable.run(TtlRunnable.java:60)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java)
	at org.apache.shardingsphere.agent.core.advisor.executor.type.InstanceMethodAdviceExecutor.advice(InstanceMethodAdviceExecutor.java:72)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask$auxiliary$GRzNAd9S.call(Unknown Source)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run$original$jVmEVyYw$accessor$7Fi0ZaHR(CommandExecutorTask.java)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run$original$jVmEVyYw(CommandExecutorTask.java:78)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:121)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.doExecuteCommand(CommandExecutorTask.java)
	at org.apache.shardingsphere.agent.core.advisor.executor.type.InstanceMethodAdviceExecutor.advice(InstanceMethodAdviceExecutor.java:72)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask$auxiliary$Mw5hCGz1.call(Unknown Source)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.doExecuteCommand$original$jVmEVyYw$accessor$7Fi0ZaHR(CommandExecutorTask.java)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.doExecuteCommand$original$jVmEVyYw(CommandExecutorTask.java:126)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:99)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.execute(DatabaseConnector.java:169)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.doExecute(DatabaseConnector.java:218)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.doExecute(DatabaseConnector.java:232)
	at org.apache.shardingsphere.proxy.backend.connector.ProxySQLExecutor.execute(ProxySQLExecutor.java:176)
	at org.apache.shardingsphere.proxy.backend.connector.ProxySQLExecutor.useDriverToExecute(ProxySQLExecutor.java:217)
	at org.apache.shardingsphere.proxy.backend.connector.jdbc.executor.ProxyJDBCExecutor.execute(ProxyJDBCExecutor.java:73)
	at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutor.execute(JDBCExecutor.java:67)
	at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.execute(ExecutorEngine.java:76)
	at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.parallelExecute(ExecutorEngine.java:91)
	at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.syncExecute(ExecutorEngine.java:95)
	at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutorCallback.execute(JDBCExecutorCallback.java:62)
	at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutorCallback.execute(JDBCExecutorCallback.java:83)
	at org.apache.shardingsphere.proxy.backend.connector.jdbc.executor.callback.ProxyJDBCExecutorCallback.executeSQL(ProxyJDBCExecutorCallback.java:46)
	at org.apache.shardingsphere.proxy.backend.connector.jdbc.executor.callback.ProxyJDBCExecutorCallback.executeSQL(ProxyJDBCExecutorCallback.java:69)
	at org.apache.shardingsphere.proxy.backend.connector.jdbc.executor.callback.impl.ProxyStatementExecutorCallback.execute(ProxyStatementExecutorCallback.java:44)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:102)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:939)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2449)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
`

**Comment by terrymanu** [comment]
Can you find the hint with `Incorrect string value: '\xEF\xBF\xBDe' for column 'appointment_data' at row 17 `?
