### ISSUE TITLE
 Column index out of range.

### ISSUE THREAD

**Issue by HADESCH9** [apache/shardingsphere#34084]
## Bug Report

When integrating Seata with ShardingSphere-JDBC version 5.5.1, the following error occurred:
```
2024-12-17 10:04:50.627 ERROR   o.a.s.r.d.s.s.c.AbstractTableMetaCache:   71 lambda$getTableMeta$0 - get table meta of the table `vehicle_blacklist` error: Column index out of range. java.sql.SQLException: Column index out of range.
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.16.jar!/:8.0.16]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.16.jar!/:8.0.16]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.16.jar!/:8.0.16]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.16.jar!/:8.0.16]
        at com.mysql.cj.jdbc.result.ResultSetMetaData.getField(ResultSetMetaData.java:221) ~[mysql-connector-java-8.0.16.jar!/:8.0.16]
        at com.mysql.cj.jdbc.result.ResultSetMetaData.isCaseSensitive(ResultSetMetaData.java:325) ~[mysql-connector-java-8.0.16.jar!/:8.0.16]
        at org.apache.shardingsphere.driver.jdbc.core.resultset.ShardingSphereResultSetMetaData.isCaseSensitive(ShardingSphereResultSetMetaData.java:61) ~[shardingsphere-jdbc-5.5.1.jar!/:5.5.1]
        at org.apache.seata.rm.datasource.sql.struct.cache.MysqlTableMetaCache.resultSetMetaToSchema(MysqlTableMetaCache.java:147) ~[seata-all-2.2.0.jar!/:2.2.0]
        at org.apache.seata.rm.datasource.sql.struct.cache.MysqlTableMetaCache.fetchSchema(MysqlTableMetaCache.java:83) ~[seata-all-2.2.0.jar!/:2.2.0]
        at org.apache.seata.rm.datasource.sql.struct.cache.AbstractTableMetaCache.lambda$getTableMeta$0(AbstractTableMetaCache.java:69) ~[seata-all-2.2.0.jar!/:2.2.0]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2379) ~[caffeine-2.8.0.jar!/:?]
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1892) ~[?:1.8.0_241]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2377) ~[caffeine-2.8.0.jar!/:?]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2360) ~[caffeine-2.8.0.jar!/:?]
        at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108) ~[caffeine-2.8.0.jar!/:?]
        at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62) ~[caffeine-2.8.0.jar!/:?]
        at org.apache.seata.rm.datasource.sql.struct.cache.AbstractTableMetaCache.getTableMeta(AbstractTableMetaCache.java:67) ~[seata-all-2.2.0.jar!/:2.2.0]
        at org.apache.seata.rm.datasource.exec.BaseTransactionalExecutor.getTableMeta(BaseTransactionalExecutor.java:325) ~[seata-all-2.2.0.jar!/:2.2.0]
        at org.apache.seata.rm.datasource.exec.DeleteExecutor.beforeImage(DeleteExecutor.java:57) ~[seata-all-2.2.0.jar!/:2.2.0]
        at org.apache.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitFalse(AbstractDMLBaseExecutor.java:98) ~[seata-all-2.2.0.jar!/:2.2.0]
        at org.apache.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:85) ~[seata-all-2.2.0.jar!/:2.2.0]
        at org.apache.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:127) ~[seata-all-2.2.0.jar!/:2.2.0]
        at org.apache.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:168) ~[seata-all-2.2.0.jar!/:2.2.0]
        at org.apache.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:63) ~[seata-all-2.2.0.jar!/:2.2.0]
        at org.apache.seata.rm.datasource.PreparedStatementProxy.execute(PreparedStatementProxy.java:55) ~[seata-all-2.2.0.jar!/:2.2.0]
        at sun.reflect.GeneratedMethodAccessor292.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_241]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_241]
        at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59) ~[mybatis-3.5.2.jar!/:3.5.2]
        at com.sun.proxy.$Proxy291.execute(Unknown Source) ~[?:?]
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47) ~[mybatis-3.5.2.jar!/:3.5.2]
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74) ~[mybatis-3.5.2.jar!/:3.5.2]
        at sun.reflect.GeneratedMethodAccessor1120.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_241]
```

### Which version of ShardingSphere did you use?

5.5.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

 ShardingSphere-JDBC

### Actual behavior
error
```
2024-12-17 10:04:50.627 ERROR   o.a.s.r.d.s.s.c.AbstractTableMetaCache:   71 lambda$getTableMeta$0 - get table meta of the table `vehicle_blacklist` error: Column index out of range. java.sql.SQLException: Column index out of range.
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.16.jar!/:8.0.16]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.16.jar!/:8.0.16]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.16.jar!/:8.0.16]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.16.jar!/:8.0.16]
        at com.mysql.cj.jdbc.result.ResultSetMetaData.getField(ResultSetMetaData.java:221) ~[mysql-connector-java-8.0.16.jar!/:8.0.16]
        at com.mysql.cj.jdbc.result.ResultSetMetaData.isCaseSensitive(ResultSetMetaData.java:325) ~[mysql-connector-java-8.0.16.jar!/:8.0.16]
        at org.apache.shardingsphere.driver.jdbc.core.resultset.ShardingSphereResultSetMetaData.isCaseSensitive(ShardingSphereResultSetMetaData.java:61) ~[shardingsphere-jdbc-5.5.1.jar!/:5.5.1]
        at org.apache.seata.rm.datasource.sql.struct.cache.MysqlTableMetaCache.resultSetMetaToSchema(MysqlTableMetaCache.java:147) ~[seata-all-2.2.0.jar!/:2.2.0]
        at org.apache.seata.rm.datasource.sql.struct.cache.MysqlTableMetaCache.fetchSchema(MysqlTableMetaCache.java:83) ~[seata-all-2.2.0.jar!/:2.2.0]
        at org.apache.seata.rm.datasource.sql.struct.cache.AbstractTableMetaCache.lambda$getTableMeta$0(AbstractTableMetaCache.java:69) ~[seata-all-2.2.0.jar!/:2.2.0]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2379) ~[caffeine-2.8.0.jar!/:?]
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1892) ~[?:1.8.0_241]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2377) ~[caffeine-2.8.0.jar!/:?]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2360) ~[caffeine-2.8.0.jar!/:?]
        at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108) ~[caffeine-2.8.0.jar!/:?]
        at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62) ~[caffeine-2.8.0.jar!/:?]
        at org.apache.seata.rm.datasource.sql.struct.cache.AbstractTableMetaCache.getTableMeta(AbstractTableMetaCache.java:67) ~[seata-all-2.2.0.jar!/:2.2.0]
        at org.apache.seata.rm.datasource.exec.BaseTransactionalExecutor.getTableMeta(BaseTransactionalExecutor.java:325) ~[seata-all-2.2.0.jar!/:2.2.0]
        at org.apache.seata.rm.datasource.exec.DeleteExecutor.beforeImage(DeleteExecutor.java:57) ~[seata-all-2.2.0.jar!/:2.2.0]
        at org.apache.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitFalse(AbstractDMLBaseExecutor.java:98) ~[seata-all-2.2.0.jar!/:2.2.0]
        at org.apache.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:85) ~[seata-all-2.2.0.jar!/:2.2.0]
        at org.apache.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:127) ~[seata-all-2.2.0.jar!/:2.2.0]
        at org.apache.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:168) ~[seata-all-2.2.0.jar!/:2.2.0]
        at org.apache.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:63) ~[seata-all-2.2.0.jar!/:2.2.0]
        at org.apache.seata.rm.datasource.PreparedStatementProxy.execute(PreparedStatementProxy.java:55) ~[seata-all-2.2.0.jar!/:2.2.0]
        at sun.reflect.GeneratedMethodAccessor292.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_241]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_241]
        at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59) ~[mybatis-3.5.2.jar!/:3.5.2]
        at com.sun.proxy.$Proxy291.execute(Unknown Source) ~[?:?]
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47) ~[mybatis-3.5.2.jar!/:3.5.2]
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74) ~[mybatis-3.5.2.jar!/:3.5.2]
        at sun.reflect.GeneratedMethodAccessor1120.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_241]
```
### Reason analyze (If you can)

I suspect that the issue arises from the "like" column configured for fuzzy search in the table.

**Comment by strongduanmu** [comment]
@HADESCH9 Can you modify this issue according to issue template?

**Comment by HADESCH9** [comment]
> @HADESCH9 Can you modify this issue according to issue template?

ok

**Comment by terrymanu** [comment]
What is your SQL and configuration?

**Comment by HADESCH9** [comment]
Field mapping configuration file is as follows
```xml
rules:
  - !SINGLE
    tables:
      - "ds1.*"
  - !ENCRYPT
    tables:
      vehicle_blacklist:
        columns:
          license_plate_number:
            name: license_plate_number
            cipher:
              name: license_plate_number_cipher
              encryptorName: aes_encryptor
            likeQuery:
              name: license_plate_number_cipher_col
              encryptorName: like_queyr_encryptor
```
Error occurred before and after updating the SQL, when Seata tried to retrieve the data before the update, an error was reported

Error content as follows
![image](https://github.com/user-attachments/assets/36428e02-171c-4e99-81c2-b2e0bdb79ada)

**Comment by terrymanu** [comment]
What is the database configuration and SQL details and table metadata?
