### ISSUE TITLE
NPE at org.apache.shardingsphere.proxy.frontend.mysql.command.query.binary.prepare.MySQLComStmtPrepareParameterMarkerExtractor.findColumnsOfParameterMarkersForInsert

### ISSUE THREAD

**Issue by Horriber** [apache/shardingsphere#34104]
use shardingSphere-porxy 
version:5.5.0
executre insert sql before throw NPE
![image](https://github.com/user-attachments/assets/b5696e31-af0f-4c49-ae03-7170fffa1f7f)

**Comment by terrymanu** [comment]
What is your configuration and exception details?

**Comment by Horriber** [comment]
# global.yaml
mode:
  type: Standalone
  repository:
    type: JDBC
    props:
      provider: H2
      jdbc_url: jdbc:h2:file:./conf/config_data;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
      username: root
      password: qwe123
authority:
  users:
    - user: root@%
      password: root
    - user: sharding
      password: sharding
  privilege:
    type: ALL_PERMITTED

# error info

[ERROR] 2024-12-19 10:44:39.972 [ShardingSphere-Command-28] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
java.lang.NullPointerException: null
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.binary.prepare.MySQLComStmtPrepareParameterMarkerExtractor.findColumnsOfParameterMarkersForInsert(MySQLComStmtPrepareParameterMarkerExtractor.java:67)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.binary.prepare.MySQLComStmtPrepareParameterMarkerExtractor.findColumnsOfParameterMarkers(MySQLComStmtPrepareParameterMarkerExtractor.java:52)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.binary.prepare.MySQLComStmtPrepareExecutor.createParameterColumnDefinition41Packets(MySQLComStmtPrepareExecutor.java:130)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.binary.prepare.MySQLComStmtPrepareExecutor.createPackets(MySQLComStmtPrepareExecutor.java:113)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.binary.prepare.MySQLComStmtPrepareExecutor.execute(MySQLComStmtPrepareExecutor.java:92)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.doExecuteCommand$original$wK23x1MT(CommandExecutorTask.java:126)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.doExecuteCommand$original$wK23x1MT$accessor$90iBKg8r(CommandExecutorTask.java)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask$auxiliary$oGyeGFZk.call(Unknown Source)
	at org.apache.shardingsphere.agent.core.advisor.executor.type.InstanceMethodAdviceExecutor.advice(InstanceMethodAdviceExecutor.java:69)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.doExecuteCommand(CommandExecutorTask.java)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:121)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run$original$wK23x1MT(CommandExecutorTask.java:78)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run$original$wK23x1MT$accessor$90iBKg8r(CommandExecutorTask.java)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask$auxiliary$WSNQZSQ3.call(Unknown Source)
	at org.apache.shardingsphere.agent.core.advisor.executor.type.InstanceMethodAdviceExecutor.advice(InstanceMethodAdviceExecutor.java:69)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java)
	at com.alibaba.ttl.TtlRunnable.run(TtlRunnable.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by terrymanu** [comment]
What is the rule configuration, SQL and table metadata？
