### ISSUE TITLE
Failed to switch schema, please terminate current transaction

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#3546]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC3-SNAPSHOT
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy
### Expected behavior
Transaction terminate correctly.
### Actual behavior
[WARN ] 13:56:35.511 [ShardingSphere-Command-7] o.a.s.s.b.c.j.c.BackendConnection - Current transaction have not terminated, retry count:[3].
[WARN ] 13:56:35.712 [ShardingSphere-Command-7] o.a.s.s.b.c.j.c.BackendConnection - Current transaction have not terminated, retry count:[4].
[WARN ] 13:56:35.912 [ShardingSphere-Command-7] o.a.s.s.b.c.j.c.BackendConnection - Current transaction have not terminated, retry count:[5].
[ERROR] 13:56:35.912 [ShardingSphere-Command-7] o.a.s.s.b.c.j.c.BackendConnection - Cannot do switch, exceed maximum retry count:[5].
[ERROR] 13:56:35.912 [ShardingSphere-Command-7] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
org.apache.shardingsphere.core.exception.ShardingException: Failed to switch schema, please terminate current transaction.
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.setCurrentSchema(BackendConnection.java:107)
	at org.apache.shardingsphere.shardingproxy.backend.text.admin.BroadcastBackendHandler.execute(BroadcastBackendHandler.java:53)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:72)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:86)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
### Reason analyze (If you can)
This pr(https://github.com/apache/incubator-shardingsphere/pull/2119/files) add setCurrentSchema() which will throw exception when a transaction is not terminated.

**Comment by cherrylzhao** [comment]
@tuohai666 reproduce step is not enough, I need to know how to trigger this exception in user side

**Comment by xmddl369** [comment]
[INFO ] 15:25:01.718 [ShardingSphere-Command-3] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM QRTZ_SCHEDULER_STATE WHERE SCHED_NAME = 'quartzScheduler'
[INFO ] 15:25:01.742 [ShardingSphere-Command-0] ShardingSphere-SQL - Rule Type: sharding
[INFO ] 15:25:01.744 [ShardingSphere-Command-0] ShardingSphere-SQL - Logic SQL: UPDATE QRTZ_SCHEDULER_STATE SET LAST_CHECKIN_TIME = 1583479503241 WHERE SCHED_NAME = 'quartzScheduler' AND INSTANCE_NAME = 'DESKTOP-5I2DG1F1583479299950'
[INFO ] 15:25:01.744 [ShardingSphere-Command-0] ShardingSphere-SQL - SQLStatement: CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.UpdateStatement@6e1b653, tablesContext=TablesContext(tables=[Table(name=QRTZ_SCHEDULER_STATE, alias=Optional.absent())], schema=Optional.absent()))
[INFO ] 15:25:01.744 [ShardingSphere-Command-0] ShardingSphere-SQL - Actual SQL: ds_0 ::: UPDATE QRTZ_SCHEDULER_STATE SET LAST_CHECKIN_TIME = 1583479503241 WHERE SCHED_NAME = 'quartzScheduler' AND INSTANCE_NAME = 'DESKTOP-5I2DG1F1583479299950'
[WARN ] 15:25:07.940 [ShardingSphere-Command-2] o.a.s.s.b.c.j.c.BackendConnection - Current transaction have not terminated, retry count:[1].
[WARN ] 15:25:08.141 [ShardingSphere-Command-2] o.a.s.s.b.c.j.c.BackendConnection - Current transaction have not terminated, retry count:[2].
[WARN ] 15:25:08.342 [ShardingSphere-Command-2] o.a.s.s.b.c.j.c.BackendConnection - Current transaction have not terminated, retry count:[3].
[WARN ] 15:25:08.542 [ShardingSphere-Command-2] o.a.s.s.b.c.j.c.BackendConnection - Current transaction have not terminated, retry count:[4].
[WARN ] 15:25:08.743 [ShardingSphere-Command-2] o.a.s.s.b.c.j.c.BackendConnection - Current transaction have not terminated, retry count:[5].
[ERROR] 15:25:08.743 [ShardingSphere-Command-2] o.a.s.s.b.c.j.c.BackendConnection - Cannot do switch, exceed maximum retry count:[5].
[ERROR] 15:25:08.746 [ShardingSphere-Command-2] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
org.apache.shardingsphere.core.exception.ShardingException: Failed to switch schema, please terminate current transaction.
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.setCurrentSchema(BackendConnection.java:116)
	at org.apache.shardingsphere.shardingproxy.backend.text.admin.BroadcastBackendHandler.execute(BroadcastBackendHandler.java:53)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:73)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:92)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by kimmking** [comment]
duplicated with #5531
