### ISSUE TITLE
sharding-jdbc-test run error while using oracle database

### ISSUE THREAD

**Issue by lookingsky2020** [apache/shardingsphere#4611]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.2-SNAPSHOT

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

### Expected behavior
sharding-jdbc-test should work well while using oracle

### Actual behavior
sharding-jdbc-test run error while using oracle

### Reason analyze (If you can)
[ERROR] 14:00:10.895 [main] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
java.sql.SQLSyntaxErrorException: ORA-00923: 

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:445)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:879)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:450)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:193)
	at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:873)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1167)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1289)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1909)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1871)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:318)
	at com.zaxxer.hikari.pool.PoolBase.executeSql(PoolBase.java:522)
	at com.zaxxer.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:414)
	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:382)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:346)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:428)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:499)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:112)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72)
	at org.apache.shardingsphere.dbtest.env.datasource.DataSourceUtil.createHikariCP(DataSourceUtil.java:102)
	at org.apache.shardingsphere.dbtest.env.datasource.DataSourceUtil.createDataSource(DataSourceUtil.java:65)
	at org.apache.shardingsphere.dbtest.env.schema.SchemaEnvironmentManager.dropDatabase(SchemaEnvironmentManager.java:92)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
run sharding-jdbc-test project GeneralDQLIT:assertExecuteQuery 

### Example codes for reproduce this issue (such as a github link)
run sharding-jdbc-test project GeneralDQLIT:assertExecuteQuery

**Comment by kimmking** [comment]
can you show the sql when query failed.

**Comment by ligengzeng** [comment]
run sharding-integration-test\sharding-jdbc-test\src\test\java\org\apache\shardingsphere\dbtest\engine\dql\GeneralDQLIT.java assertExecuteQuery method
when call DataSourceUtil:createHikariCP method

at org.apache.shardingsphere.dbtest.env.datasource.DataSourceUtil.createHikariCP(DataSourceUtil.java:102)

demo code  connectionTestQuery is not collect for oracle . and dataSourceName is empty  as default value .

[cid:image001.png@01D5F3BB.BE3E8560]



发件人: kimmking [mailto:notifications@github.com]
发送时间: 2020年3月6日 星期五 13:01
收件人: apache/incubator-shardingsphere
抄送: 曾力耕ZengLiGeng0027001313; Author
主题: Re: [apache/incubator-shardingsphere] sharding-jdbc-test run error while using oracle database (#4611)


can you show the sql when query failed.

**Comment by ligengzeng** [comment]
Before going to the step of executing SQL, an error is reported when the data source connection is acquired

https://github.com/apache/incubator-shardingsphere.git

run sharding-integration-test\sharding-jdbc-test\src\test\java\org\apache\shardingsphere\dbtest\engine\dql\GeneralDQLIT.java assertExecuteQuery method

when call DataSourceUtil:createHikariCP method

org.apache.shardingsphere.dbtest.env.datasource.DataSourceUtil.createHikariCP(DataSourceUtil.java:102)

such as  result.setConnectionTestQuery("SELECT 1"); // is not collect for using oracle



org.apache.shardingsphere.dbtest.env.schema.SchemaEnvironmentManager: dropDatabase

dataSource = DataSourceUtil.createDataSource(each, null);  // input parameter dataSourceName is null , so create dataSource connection error










发件人: kimmking [mailto:notifications@github.com]
发送时间: 2020年3月6日 星期五 13:01
收件人: apache/incubator-shardingsphere
抄送: 曾力耕ZengLiGeng0027001313; Author
主题: Re: [apache/incubator-shardingsphere] sharding-jdbc-test run error while using oracle database (#4611)


can you show the sql when query failed.

**Comment by lookingsky2020** [comment]
Before going to the step of executing SQL, an error is reported when the data source connection is acquired

https://github.com/apache/incubator-shardingsphere.git

run sharding-integration-test\sharding-jdbc-test\src\test\java\org\apache\shardingsphere\dbtest\engine\dql\GeneralDQLIT.java assertExecuteQuery method

when call DataSourceUtil:createHikariCP method

org.apache.shardingsphere.dbtest.env.datasource.DataSourceUtil.createHikariCP(DataSourceUtil.java:102)

such as  result.setConnectionTestQuery("SELECT 1"); // is not collect for using oracle



org.apache.shardingsphere.dbtest.env.schema.SchemaEnvironmentManager: dropDatabase

dataSource = DataSourceUtil.createDataSource(each, null);  // input parameter dataSourceName is null , so create dataSource connection error

**Comment by terrymanu** [comment]
The subquery and pagination of rownum in oracle are not correct now.
We are doing the subquery now, so I just pending this issue after we finish the subquery.

**Comment by kimmking** [comment]
@lookingsky2020 
IMO, such as 
> result.setConnectionTestQuery("SELECT 1"); // is not collect for using oracle

should be `select 1 from dual` in Oracle.
Could you do something to fix it in integration- tests.

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 1 year, we will close it. 
If you still have related questions, please submit a new issue, thank you.
