### ISSUE TITLE
sharding throws NullPointerException when sql don't have sharding key and db column type is INT and its value is null

### ISSUE THREAD

**Issue by funnything2014** [apache/shardingsphere#4755]
java.lang.NullPointerException: null
        at org.apache.shardingsphere.core.execute.sql.execute.result.MemoryQueryResult.getRowValue(MemoryQueryResult.java:88) ~[sharding-core-execute-4.0.0.jar:4.0.0]
        at org.apache.shardingsphere.core.execute.sql.execute.result.MemoryQueryResult.getRows(MemoryQueryResult.java:63) ~[sharding-core-execute-4.0.0.jar:4.0.0]
        at org.apache.shardingsphere.core.execute.sql.execute.result.MemoryQueryResult.<init>(MemoryQueryResult.java:55) ~[sharding-core-execute-4.0.0.jar:4.0.0]
        at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.getQueryResult(PreparedStatementExecutor.java:116) ~[sharding-jdbc-core-4.0.0.jar:4.0.0]
        at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.access$200(PreparedStatementExecutor.java:50) ~[sharding-jdbc-core-4.0.0.jar:4.0.0]
        at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor$2.executeSQL(PreparedStatementExecutor.java:106) ~[sharding-jdbc-core-4.0.0.jar:4.0.0]
        at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor$2.executeSQL(PreparedStatementExecutor.java:102) ~[sharding-jdbc-core-4.0.0.jar:4.0.0]
        at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteCallback.execute0(SQLExecuteCallback.java:79) ~[sharding-core-execute-4.0.0.jar:4.0.0]
        at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteCallback.execute(SQLExecuteCallback.java:61) ~[sharding-core-execute-4.0.0.jar:4.0.0]
        at org.apache.shardingsphere.core.execute.engine.ShardingExecuteEngine.syncGroupExecute(ShardingExecuteEngine.java:125) ~[sharding-core-execute-4.0.0.jar:4.0.0]
        at org.apache.shardingsphere.core.execute.engine.ShardingExecuteEngine.parallelExecute(ShardingExecuteEngine.java:102) ~[sharding-core-execute-4.0.0.jar:4.0.0]
        at org.apache.shardingsphere.core.execute.engine.ShardingExecuteEngine.groupExecute(ShardingExecuteEngine.java:83) ~[sharding-core-execute-4.0.0.jar:4.0.0]
        at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteTemplate.executeGroup(SQLExecuteTemplate.java:73) ~[sharding-core-execute-4.0.0.jar:4.0.0]
        at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteTemplate.executeGroup(SQLExecuteTemplate.java:56) ~[sharding-core-execute-4.0.0.jar:4.0.0]
        at org.apache.shardingsphere.shardingjdbc.executor.AbstractStatementExecutor.executeCallback(AbstractStatementExecutor.java:140) ~[sharding-jdbc-core-4.0.0.jar:4.0.0]
        at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.executeQuery(PreparedStatementExecutor.java:109) ~[sharding-jdbc-core-4.0.0.jar:4.0.0]
        at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.executeQuery(ShardingPreparedStatement.java:123) ~[sharding-jdbc-core-4.0.0.jar:4.0.0]

**Comment by terrymanu** [comment]
Do you use getInt to get the null filed?

**Comment by funnything2014** [comment]
I use hibernate to get my own object（some field with Int\Long\Timestamp type, but its default value is null）, it just throw NullPointerException; this is not happen when sharding key is assigned.I trace the stack, and find in MemoryQueryResult class, private Object getRowValue(final ResultSet resultSet, final int columnIndex) this method,should check resultSet.getObject(columnIndex) whether is null and then convert to different type.

**Comment by tuohai666** [comment]
Hi @funnything2014, the information you provided is not enough. Please fill in the template below.

It's better to have a logic SQL and an actual SQL from the log. (via sql.show : true)

## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by tuohai666** [comment]
Duplicated with #5467.
