### ISSUE TITLE
Single table query with subquery  can not parse with sharding

### ISSUE THREAD

**Issue by phoema** [apache/shardingsphere#4963]
## Bug Report
V5.0.0-RC1

SELECT COUNT(1) FROM ( SELECT assignee, flow_def_id, task_def_key, count(*) AS total FROM v_flow_history_dis WHERE (task_end_time BETWEEN ? AND ? AND rownum = ? AND case_id IS NOT NULL) GROUP BY assignee, flow_def_id, task_def_key ORDER BY assignee ASC, flow_def_id ASC, task_def_key ASC ) TOTAL

this sql is a single table query
but it can not parse when I make a hitmanger

**Comment by kimmking** [comment]
@phoema 
Change the title for friendly search, please.
Subquery is not supported well now. See https://github.com/apache/incubator-shardingsphere/issues/4696

**Comment by phoema** [comment]
can I write some other sqls when it does not work well and link 4696?

**Comment by terrymanu** [comment]
Pending for subquery

**Comment by Boomkeeper** [comment]
**Is there a temporary solution or emergency solution please？**
I have encountered a same problem about 'subquery'  recently，and the process of my task also delayed.

something here maybe helpful:
**version**

> <dependency>
     <groupId>org.apache.shardingsphere</groupId>
     <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
     <version>4.0.1</version>
</dependency>

**SQL**
> SELECT COUNT(1) FROM ( 
    SELECT  id, pin, status, created_time, created_by, delete_flag  
    FROM t_table_123
    WHERE  delete_flag = 1
    AND pin IN (?) 
) TOTAL

**configuration**

> spring.shardingsphere.encrypt.tables.t_table_123.columns.pin.encryptor=default_encryptor
spring.shardingsphere.encrypt.tables.t_table_123.columns.pin.plainColumn=pin
spring.shardingsphere.encrypt.tables.t_table_123.columns.pin.cipherColumn=pin_encrypt

**exception**

> Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -3
	at java.lang.String.substring(String.java:1967)
	at org.apache.shardingsphere.underlying.rewrite.sql.impl.AbstractSQLBuilder.getConjunctionText(AbstractSQLBuilder.java:58)
	at org.apache.shardingsphere.underlying.rewrite.sql.impl.AbstractSQLBuilder.toSQL(AbstractSQLBuilder.java:50)
	at org.apache.shardingsphere.underlying.rewrite.engine.impl.DefaultSQLRewriteEngine.rewrite(DefaultSQLRewriteEngine.java:34)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.EncryptPreparedStatement.getSQLUnit(EncryptPreparedStatement.java:171)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.EncryptPreparedStatement.execute(EncryptPreparedStatement.java:138)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doQuery(MybatisSimpleExecutor.java:67)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	... 41 more

So, what can I do now to avoid exception?
Thanks.

**Comment by phoema** [comment]
When will the issue can  be processed?

**Comment by kimmking** [comment]
It will be supported in version 5.x.
