### ISSUE TITLE
Does it have cancel request function？

### ISSUE THREAD

**Issue by nevereverever** [apache/shardingsphere#5189]
sharding-proxy version: 4.0.1

If a query takes too long and I want to terminate，I can't stop it.

**Comment by tuohai666** [comment]
I'll check this later.

**Comment by nevereverever** [comment]
order by string cannot cancel request,I just found out this bug is fixed by tuohai666,I haven't tried yet.But cancel request is not normal yet.

I debug the code,I find that navicat cancel request by using the SQL(type is COM_QUERY) which is "kill 1".   
error code:
```java
line 1:0 no viable alternative at input 'KILL'
line 1:0 mismatched input 'KILL' expecting {SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, TRUNCATE, GRANT, REVOKE, SET, WITH, DESC, BEGIN, COMMIT, ROLLBACK, SAVEPOINT, CALL, USE, DESCRIBE, SHOW, REPLACE, START, RENAME}
[ERROR] 14:08:37.435 [ShardingSphere-Command-13] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
org.apache.shardingsphere.sql.parser.exception.SQLParsingException: Unsupported SQL of `KILL 1`
	at org.apache.shardingsphere.sql.parser.core.parser.SQLParserEngine.parse(SQLParserEngine.java:73)
	at org.apache.shardingsphere.sql.parser.core.SQLParseKernel.parse(SQLParseKernel.java:58)
	at org.apache.shardingsphere.shardingproxy.backend.text.TextProtocolBackendHandlerFactory.newInstance(TextProtocolBackendHandlerFactory.java:70)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.<init>(MySQLComQueryPacketExecutor.java:65)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.MySQLCommandExecutorFactory.newInstance(MySQLCommandExecutorFactory.java:72)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandExecutor(MySQLCommandExecuteEngine.java:60)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:91)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Hope to help you.THK.

**Comment by tuohai666** [comment]
@nevereverever You information is very helpful, thanks.

**Comment by xbkaishui** [comment]
Can't do this in proxy side, the main reason is, the backend of sharding-proxy may have multi physical databases.  it hard to know the kill {processId} should send to which db. even more the different physical db may have same processId at some time.

**Comment by kimmking** [comment]
Any update or close this issue?>

**Comment by tuohai666** [comment]
@kimmking I'll investigate later.
