### ISSUE TITLE
Error attempting to get column 'create_time' from result set.  Cause: java.sql.SQLFeatureNotSupportedException: getObject with type

### ISSUE THREAD

**Issue by phpdragon** [apache/shardingsphere#5203]
Environment：

mybatis-plus-boot-starter：3.3.1
druid: 1.1.22
mysql-connector-java: 8.0.19
spring-boot-starter-parent: 2.1.7.RELEASE

Downgrading to 3.1.0 does not have this problem！！！

-----------------------------------------------------------------------------------

Throws below exception when executed a query sql statement by Mybatis Plus.

2020-04-15 19:50:00.489[http-nio-8080-exec-2]|INFO|ShardingSphere-SQL - Logic SQL: SELECT  id,mobile,ip,ture_ip,create_time  FROM t_user_ip
2020-04-15 19:50:00.489[http-nio-8080-exec-2]|INFO|ShardingSphere-SQL - SQLStatement: SelectSQLStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.SelectStatement@74312c28, tablesContext=TablesContext(tables=[Table(name=t_risk_user_ip, alias=Optional.absent())], schema=Optional.absent())), projectionsContext=ProjectionsContext(startIndex=8, stopIndex=39, distinctRow=false, projections=[ColumnProjection(owner=null, name=id, alias=Optional.absent()), ColumnProjection(owner=null, name=mobile, alias=Optional.absent()), ColumnProjection(owner=null, name=ip, alias=Optional.absent()), ColumnProjection(owner=null, name=ture_ip, alias=Optional.absent()), ColumnProjection(owner=null, name=create_time, alias=Optional.absent())], columnLabels=[id, mobile, ip, ture_ip, create_time]), groupByContext=org.apache.shardingsphere.sql.parser.relation.segment.select.groupby.GroupByContext@15bb7ccd, orderByContext=org.apache.shardingsphere.sql.parser.relation.segment.select.orderby.OrderByContext@717614c0, paginationContext=org.apache.shardingsphere.sql.parser.relation.segment.select.pagination.PaginationContext@35ebcabb, containsSubquery=false)
2020-04-15 19:50:00.489[http-nio-8080-exec-2]|INFO|ShardingSphere-SQL - Actual SQL: ds_master_0_slave_0 ::: SELECT  id,mobile,ip,ture_ip,create_time  FROM t_risk_user_ip
2020-04-15 19:50:03.454[http-nio-8080-exec-2]|ERROR|com.zzc.cloud.rest.ExceptionAdvice - 服务器内部错误
org.springframework.dao.InvalidDataAccessApiUsageException: Error attempting to get column 'create_time' from result set.  Cause: java.sql.SQLFeatureNotSupportedException: getObject with type
; getObject with type; nested exception is java.sql.SQLFeatureNotSupportedException: getObject with type
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:96)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:88)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
	at com.sun.proxy.$Proxy140.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:223)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:177)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:78)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:96)
	at com.sun.proxy.$Proxy141.selectList(Unknown Source)
	at com.baomidou.mybatisplus.extension.service.IService.list(IService.java:275)
	at com.baomidou.mybatisplus.extension.service.IService.list(IService.java:284)
	at com.baomidou.mybatisplus.extension.service.IService$$FastClassBySpringCGLIB$$f8525d18.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at com.jyblife.risk.commons.db.mybatis.service.impl.RiskUserIpServiceImpl$$EnhancerBySpringCGLIB$$95470790.list(<generated>)
	at com.jyblife.risk.analysis.controller.UserController.find1(UserController.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.zalando.logbook.servlet.NormalStrategy.doFilter(NormalStrategy.java:38)
	at org.zalando.logbook.servlet.LogbookFilter.doFilter(LogbookFilter.java:39)
	at org.zalando.logbook.servlet.HttpFilter.doFilter(HttpFilter.java:31)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLFeatureNotSupportedException: getObject with type
	at org.apache.shardingsphere.shardingjdbc.jdbc.unsupported.AbstractUnsupportedOperationResultSet.getObject(AbstractUnsupportedOperationResultSet.java:223)
	at org.apache.ibatis.type.LocalDateTimeTypeHandler.getNullableResult(LocalDateTimeTypeHandler.java:38)
	at org.apache.ibatis.type.LocalDateTimeTypeHandler.getNullableResult(LocalDateTimeTypeHandler.java:28)
	at org.apache.ibatis.type.BaseTypeHandler.getResult(BaseTypeHandler.java:81)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.applyAutomaticMappings(DefaultResultSetHandler.java:521)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getRowValue(DefaultResultSetHandler.java:402)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValuesForSimpleResultMap(DefaultResultSetHandler.java:354)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValues(DefaultResultSetHandler.java:328)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSet(DefaultResultSetHandler.java:301)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:194)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:65)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doQuery(MybatisSimpleExecutor.java:67)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:136)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
	... 81 common frames omitted

-----------------------------------------------------------------------------------

![1](https://user-images.githubusercontent.com/1559608/79335027-ed642d80-7f53-11ea-980d-84dcc250a36e.png)
![2](https://user-images.githubusercontent.com/1559608/79335104-0a98fc00-7f54-11ea-8232-1e2222c50b46.png)
![3](https://user-images.githubusercontent.com/1559608/79335110-0cfb5600-7f54-11ea-86d0-172d7952cdd3.png)
![4](https://user-images.githubusercontent.com/1559608/79335114-0d93ec80-7f54-11ea-8f65-dd0e40c185a0.png)
![5](https://user-images.githubusercontent.com/1559608/79335120-0ff64680-7f54-11ea-9e3f-e37ff68374fe.png)
![6](https://user-images.githubusercontent.com/1559608/79335122-108edd00-7f54-11ea-896a-0c7e4c864f99.png)
![7](https://user-images.githubusercontent.com/1559608/79335126-1258a080-7f54-11ea-836e-e96e6f13ffc1.png)

**Comment by kimmking** [comment]
please modify the title for user searching friendly.

**Comment by kimmking** [comment]
downgrade your mysql-connector-java: 8.0.19 to 5.1.47

**Comment by phpdragon** [comment]
> try to downgrade your mysql-connector-java: 8.0.19 to 5.1.47
更换了版本也是不行的，这不是一个mysql-connector-java版本的问题！
根本原因是你的类库不支持localDateTime吧？！

**Comment by kimmking** [comment]
Duplicated https://github.com/apache/incubator-shardingsphere/issues/3203

The jdbc method getObject with type doesn't support yet. But  you can convert by your application side.

**Comment by kimmking** [comment]
@phpdragon any more questions/details here?

**Comment by hjdongxuxu** [comment]
I found that in 4.0.0 RC2, getObject will not use AbstractUnsupportedOperationResultSet.getObjject(), but when use 4.0.0 getObject uses the method "AbstractUnsupportedOperationResultSet.getObjject()";

Why change this? Will the latest version support the  latest version mybatis？
PS：https://github.com/apache/shardingsphere/issues/5203

If not I think a lot of people can not update to the latest version 4.0.0 or 4.0.1.

**Comment by zyg166** [comment]
> 4.0.0 and 4.0.1 is not compatible with mybatis-3.5.1 or upper
> 
> I found that in 4.0.0 RC2, getObject will not use AbstractUnsupportedOperationResultSet.getObjject() （will user the mehtod：ResultSetImpl.getObjec in mysql-connector-java）, but when use 4.0.0 getObject uses the method "AbstractUnsupportedOperationResultSet.getObjject()";
> 
> Why change this? Will the latest version support the latest version mybatis？
> PS：https://github.com/mybatis/mybatis-3/releases/tag/mybatis-3.5.1
> 
> If not I think a lot of people can not update to the latest version 4.0.0 or 4.0.1.

you are right. i am in the same situation.  i downgrade sharding-jdbc version to 4.0.0-RC2,problem solved.

**Comment by alterhu2020** [comment]
Yes, It seems that latest shardingsphere not support the LocalDate,LocalTime,LocalDateTime....

**Comment by tuohai666** [comment]
Fixed via https://github.com/apache/shardingsphere/pull/6202 .

**Comment by 191824852** [comment]
try import 

```
                <dependency>
			<groupId>org.mybatis</groupId>
			<artifactId>mybatis-typehandlers-jsr310</artifactId>
			<version>${mybatis-typeHandlers.version}</version>
		</dependency>
```

**Comment by lixaviers** [comment]
> Yes, It seems that latest shardingsphere not support the LocalDate,LocalTime,LocalDateTime....

I am using version 4.1.0 and this is also the case.
How do you deal with this problem？
I'm customizing a converter

**Comment by wzhjqeds** [comment]
> try import
> 
> ```
>                 <dependency>
> 			<groupId>org.mybatis</groupId>
> 			<artifactId>mybatis-typehandlers-jsr310</artifactId>
> 			<version>${mybatis-typeHandlers.version}</version>
> 		</dependency>
> ```

sharding-jdbc-4.1.1 添加此依赖后有用

**Comment by beareverse** [comment]
> > try import
> > ```
> >                 <dependency>
> > 			<groupId>org.mybatis</groupId>
> > 			<artifactId>mybatis-typehandlers-jsr310</artifactId>
> > 			<version>${mybatis-typeHandlers.version}</version>
> > 		</dependency>
> > ```
> 
> sharding-jdbc-4.1.1 添加此依赖后有用

用哪个版本呢，我引入了1.0.2还是不行

**Comment by Demekeayal** [comment]
i cann't get solution for this error

**Comment by ImLinCY** [comment]
<dependency>
	<groupId>org.apache.shardingsphere</groupId>
	<artifactId>sharding-jdbc-spring-boot-starter</artifactId>
	<version>4.1.1</version>
</dependency>
必须引入
<dependency>
	<groupId>org.mybatis</groupId>
	<artifactId>mybatis-typehandlers-jsr310</artifactId>
	<version>1.0.2</version>
</dependency>
才能够将数据库时间转换成LocalDateTime
