### ISSUE TITLE
replace into can not execute

### ISSUE THREAD

**Issue by nevereverever** [apache/shardingsphere#5330]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-SNAPSHOT
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
sharding-proxy

### behavior

Using replace will occur error:
```
replace INTO `psn_insu_rlts_d` (`PSN_INSU_RLTS_ID`, `INSU_PSN_MGT_EID`, `ADMDVS`, `ADMDVS_NAME`, `POOLAREA`, `INSU_IDET`, `EMP_NO`, `FM_ID`, `PSN_NO`, `PSN_TYPE`, `PSN_CERT_TYPE`, `CERTNO`, `PSN_INSU_STAS`, `EMP_FOM`, `PSN_CLCT_STAS`, `BEGN_YM`, `END_YM`, `PSN_INSU_DATE`, `FST_INSU_YM`, `ACCT_CRTN_YM`, `CRT_INSU_DATE`, `PAUS_INSU_DATE`, `MAX_ACCTPRD`, `INSU_OPTINS`, `CLCT_RULE_TYPE_CODG`, `CLCTSTD_CRTF_RULE_CODG`, `QUTS_TYPE`, `HI_TYPE`, `INSUTYPE`, `INSUTYPE_RETR_FLAG`, `CLCT_WAY`, `CRT_PATC_JOB_DATE`, `AS_CLCT_MONTH`, `THISTIME_BEGN_DATE`, `SYS_CODE`, `CRTER`, `CRTER_NAME`, `CRTE_TIME`, `CRTE_OPTINS`, `OPTER`, `OPTER_NAME`, `OPT_TIME`, `OPTINS`, `UPDT_TIME`) VALUES (NULL,NULL,'湖南省省本级','439900','439900','11','633','-1','118134','42','01','1111111111111','1','91','1','200004','999912','2000-04-01',200004,NULL,NULL,NULL,NULL,NULL,'-1',NULL,'3','1','320','1','2','1968-12-01',0,NULL,'4399003100',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2020-03-14')
> 10002 - 2Unknown exception: [org.apache.shardingsphere.sql.parser.sql.statement.dml.InsertStatement cannot be cast to org.apache.shardingsphere.sql.parser.sql.statement.dml.ReplaceStatement]
```

**Comment by terrymanu** [comment]
Low priority and no plan to it now, I just open this issue for serval days. If somebody interest this issue, please contact us.

**Comment by strongduanmu** [comment]
@kimmking @terrymanu Can you assign it to me? I want to solve this issue. Thx😀

**Comment by strongduanmu** [comment]
@nevereverever Hi, can you provide the definition of the table psn_insu_rlts_d?

**Comment by trydofor** [comment]
sharding-sphere.version = 4.1.0

```
replace into `tst_中文也分表` (`id`,`create_dt`,`modify_dt`,`delete_dt`,`commit_id`,`login_info`,`other_info`) values (?,?,?,?,?,?,?)

java.lang.ClassCastException: org.apache.shardingsphere.sql.parser.sql.statement.dml.InsertStatement cannot be cast to org.apache.shardingsphere.sql.parser.sql.statement.dml.ReplaceStatement
	at org.jooq_3.12.4.MYSQL.debug(Unknown Source) ~[na:na]
	at org.apache.shardingsphere.sql.parser.mysql.visitor.impl.MySQLDMLVisitor.visitReplace(MySQLDMLVisitor.java:163) ~[shardingsphere-sql-parser-mysql-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.sql.parser.mysql.visitor.impl.MySQLDMLVisitor.visitReplace(MySQLDMLVisitor.java:127) ~[shardingsphere-sql-parser-mysql-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$ReplaceContext.accept(MySQLStatementParser.java:1471) ~[shardingsphere-sql-parser-mysql-4.1.0.jar:4.1.0]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18) ~[antlr4-runtime-4.7.2.jar:4.7.2]
```

**Comment by terrymanu** [comment]
@strongduanmu, Hi, any update for this issue?

**Comment by strongduanmu** [comment]
> @strongduanmu, Hi, any update for this issue?

@terrymanu I am so sorry😔, because of my busy work recently, the work of this issue was interrupted. If this issue is not very urgent, I want to continue to complete it.
