### ISSUE TITLE
（err）pgadmin4 v4 connect shardingsphere 4.0.1 pg10.12

### ISSUE THREAD

**Issue by licyclone** [apache/shardingsphere#5356]
hello everyone！when i usepgadmin4 v4 connect to shardingsphere 4.0.1  in pg10.12。the error report in the server logfile ，how can i do?ths very much!
 o.a.s.s.f.c.CommandExecutorTask - Exception occur:
org.apache.shardingsphere.core.config.ShardingConfigurationException: Cannot find table rule and default data source with logic table: 'pg_class'
        at org.apache.shardingsphere.core.rule.ShardingRule.getTableRule(ShardingRule.java:191)
        at org.apache.shardingsphere.core.route.type.unicast.UnicastRoutingEngine.route(UnicastRoutingEngine.java:78)
        at org.apache.shardingsphere.core.route.router.sharding.ShardingRouter.route(ShardingRouter.java:113)
        at org.apache.shardingsphere.core.route.StatementRoutingEngine.route(StatementRoutingEngine.java:54)
        at org.apache.shardingsphere.core.SimpleQueryShardingEngine.route(SimpleQueryShardingEngine.java:58)
        at org.apache.shardingsphere.core.BaseShardingEngine.executeRoute(BaseShardingEngine.java:85)
        at org.apache.shardingsphere.core.BaseShardingEngine.shard(BaseShardingEngine.java:68)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.wrapper.StatementExecutorWrapper.doShardingRoute(StatementExecutorWrapper.java:79)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.wrapper.StatementExecutorWrapper.route(StatementExecutorWrapper.java:65)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:83)
        at org.apache.shardingsphere.shardingproxy.backend.text.query.QueryBackendHandler.execute(QueryBackendHandler.java:54)
        at org.apache.shardingsphere.shardingproxy.frontend.postgresql.command.query.text.PostgreSQLComQueryExecutor.execute(PostgreSQLComQueryExecutor.java:68)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:92)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:72)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by cherrylzhao** [comment]
at first please provide your sharding configuration, make sure actual table existed in pg.

**Comment by terrymanu** [comment]
Closed because of no response anymore.
