### ISSUE TITLE
How do I connect sharding-proxy in the springboot project?

### ISSUE THREAD

**Issue by huntunshule** [apache/shardingsphere#5375]
How do I connect sharding-proxy in the springboot project? Do I need to rely on it? I did not find relevant documents.
Thank you very much!!

**Comment by terrymanu** [comment]
FYI: https://shardingsphere.apache.org/document/current/en/quick-start/sharding-proxy-quick-start/

**Comment by kimmking** [comment]
1. config and start sharding-proxy like above link
2. use jdbc connecting to sharding-proxy just as a real mysql server

**Comment by huntunshule** [comment]
> 1. config and start sharding-proxy like above link
> 2. use jdbc connecting to sharding-proxy just as a real mysql server

I have almost followed the steps you mentioned, but there is the following error
```
 2020-04-29 13:25:03.834 ERROR 7960 [] [main] com.alibaba.druid.pool.DruidDataSource init datasource error, url: jdbc:mysql://192.168.1.211:3312/cloud-master?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:906)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:831)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156)
	at com.alibaba.druid.filter.FilterAdapter.connection_connect(FilterAdapter.java:787)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
...
 ERROR 7960 [] [main] com.alibaba.druid.pool.DruidDataSource {dataSource-1} init error
```

**Comment by huntunshule** [comment]
this is mysql application.yaml
```
spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          username: ${aic.datasource.username}
          password: ${aic.datasource.password}
          url: jdbc:mysql://192.168.1.211:3312/cloud-master?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
```

**Comment by kimmking** [comment]
Proxy in 3312 is launched successfully?

**Comment by kimmking** [comment]
you can try it with mysql command first:
> mysql -h192.168.1.211 -P3312 -uroot -ppassword

**Comment by huntunshule** [comment]
> you can try it with mysql command first:
> 
> > mysql -h192.168.1.211 -P3312 -uroot -ppassword

Yes, he did, but the springboot didn't work. I had no problem connecting with navicat

**Comment by cherrylzhao** [comment]
what version of your mysql-java-connector in spring-boot? sharding-proxy don't support mysql8 client before 4.1.0

**Comment by cherrylzhao** [comment]
the log shows the version is 8.x, please use 5.x version.

**Comment by huntunshule** [comment]
> the log shows the version is 8.x, please use 5.x version.

According to your suggestion I hooked up, but I try to start 4.1.0 version, this website can't open it, there is no https://dist.apache.org/repos/dist/release/shardingsphere/

**Comment by huntunshule** [comment]
> the log shows the version is 8.x, please use 5.x version.

What to do if I want to use version 4.1.0 now

**Comment by cherrylzhao** [comment]
you can download it from `https://dist.apache.org/repos/dist/dev/shardingsphere/4.1.0/apache-shardingsphere-4.1.0-sharding-proxy-bin.tar.gz`, we will release it recently

**Comment by huntunshule** [comment]
> you can download it from `https://dist.apache.org/repos/dist/dev/shardingsphere/4.1.0/apache-shardingsphere-4.1.0-sharding-proxy-bin.tar.gz`, we will release it recently

Now, all runs perfectly, thanks
This is my Dockerfile
```
FROM java:8
COPY ./apache-shardingsphere-4.1.0-sharding-proxy-bin.tar.gz /opt/ 
RUN  cd /opt && tar -zxvf apache-shardingsphere-4.1.0-sharding-proxy-bin.tar.gz && \
     rm -f sharding-proxy.tar.gz && \
     mv apache-shardingsphere-4.1.0-sharding-proxy-bin sharding-proxy && \
     mkdir -p /opt/sharding-proxy/ext-lib
COPY ./mysql-connector-java-8.0.17.jar /opt/sharding-proxy/lib
ENTRYPOINT /opt/sharding-proxy/bin/start.sh  && tail -f /opt/sharding-proxy/logs/stdout.log
```
