### ISSUE TITLE
How to solve that DATA MASKING  can’t work with subquery when query conditions contains masking column ?

### ISSUE THREAD

**Issue by tanglujun** [apache/shardingsphere#5402]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
select SQL execute successfully.
### Actual behavior
`Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at org.apache.shardingsphere.underlying.rewrite.sql.impl.AbstractSQLBuilder.getConjunctionText(AbstractSQLBuilder.java:58)
	at org.apache.shardingsphere.underlying.rewrite.sql.impl.AbstractSQLBuilder.toSQL(AbstractSQLBuilder.java:50)
	at org.apache.shardingsphere.sharding.rewrite.engine.ShardingSQLRewriteEngine.rewrite(ShardingSQLRewriteEngine.java:53)
	at org.apache.shardingsphere.core.BaseShardingEngine.rewriteAndConvert(BaseShardingEngine.java:113)
	at org.apache.shardingsphere.core.BaseShardingEngine.shard(BaseShardingEngine.java:69)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.shard(ShardingPreparedStatement.java:249)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:190)`
### Reason analyze (If you can)
It cause the rewrited SQL tokens are repeated, and the rewrite indexs are error.
### Example codes for reproduce this issue (such as a github link).
SELECT count(1) FROM (SELECT id FROM user where phone=? ) table_count

**Comment by kimmking** [comment]
subquery is in plan
