### ISSUE TITLE
When will the libraries be updated? org.yaml:snakeyaml:1.16

### ISSUE THREAD

**Issue by Leinariys** [apache/shardingsphere#5506]
When will the libraries be updated?
I have a conflict in the spring  = org.yaml:snakeyaml:1.25
In org.apache.shardingsphere   =   org.yaml:snakeyaml:1.16

java.lang.NoSuchMethodError: org.yaml.snakeyaml.Yaml.<init>(Lorg/yaml/snakeyaml/constructor/BaseConstructor;Lorg/yaml/snakeyaml/representer/Representer;Lorg/yaml/snakeyaml/DumperOptions;Lorg/yaml/snakeyaml/LoaderOptions;Lorg/yaml/snakeyaml/resolver/Resolver;)V
	at org.springframework.boot.env.OriginTrackedYamlLoader.createYaml(OriginTrackedYamlLoader.java:70)
	at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:132)
	at org.springframework.boot.env.OriginTrackedYamlLoader.load(OriginTrackedYamlLoader.java:75)
	at org.springframework.boot.env.YamlPropertySourceLoader.load(YamlPropertySourceLoader.java:50)

**Comment by yu199195** [comment]
show you configuration in YAML。

**Comment by terrymanu** [comment]
Please resolve conflicts by the application side.
If ShardingSphere upgrade the yaml lib, the same problem will occur when developer use the old version?.
