### ISSUE TITLE
"AS" does not work in  select sql

### ISSUE THREAD

**Issue by hqhangyu** [apache/shardingsphere#5600]
when i connect proxy via psql,and i execute sql  that blew:
 select rtl_cont_inf.cst_nm  as bbb from rtl_cont_inf rtl_cont_inf
and the get result like this
              cst_nm
----------------------------------
 0401-01
 20204030002
 202004030003
 20204030002

column name can not change to "bbb".
i don not why
somebody can help me?

**Comment by hqhangyu** [comment]
db is postgresql

**Comment by kimmking** [comment]
do you show more details.

**Comment by hqhangyu** [comment]
![无标题](https://user-images.githubusercontent.com/24414552/81922321-85fed380-960e-11ea-9774-5a78819d39d4.jpg)

**Comment by kimmking** [comment]
what's the actual sql in proxy console logs?

**Comment by hqhangyu** [comment]
![无标题](https://user-images.githubusercontent.com/24414552/81923636-90ba6800-9610-11ea-9cfb-0ff206dd0697.jpg)

**Comment by kimmking** [comment]
can you show the text logs, image can't be loaded.

**Comment by psh882003** [comment]
[INFO ] 18:19:12.653 [pool-1216-thread-1] ShardingSphere-SQL - Logic SQL: select rtl_cont_inf.cst_nm as bbb from rtl_cont_inf rtl_cont_inf;
[INFO ] 18:19:12.654 [pool-1216-thread-1] ShardingSphere-SQL - SQLStatement: SelectStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.SelectStatement@71d2323c, tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@50dce60), tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@50dce60, projectionsContext=ProjectionsContext(startIndex=7, stopIndex=32, distinctRow=false, projections=[ColumnProjection(owner=rtl_cont_inf, name=cst_nm, alias=Optional[bbb])]), groupByContext=org.apache.shardingsphere.sql.parser.binder.segment.select.groupby.GroupByContext@36cd01f1, orderByContext=org.apache.shardingsphere.sql.parser.binder.segment.select.orderby.OrderByContext@af51a80, paginationContext=org.apache.shardingsphere.sql.parser.binder.segment.select.pagination.PaginationContext@6ad69a30, containsSubquery=false)
[INFO ] 18:19:12.654 [pool-1216-thread-1] ShardingSphere-SQL - Actual SQL: default ::: select rtl_cont_inf.cst_nm as bbb from rtl_cont_inf rtl_cont_inf;

**Comment by kimmking** [comment]
which version? oracle or mysql?

**Comment by psh882003** [comment]
PG



psh882003@163.com 
 
From: kimmking
Date: 2020-05-15 13:06
To: apache/shardingsphere
CC: psh882003; Comment
Subject: Re: [apache/shardingsphere] "AS" does not work in select sql (#5600)
which version? oracle or mysql?

**Comment by hqhangyu** [comment]
> which version of proxy? oracle or mysql, and version?

version of proxy is  410 and db is postgresql 10.12 on x86_64-pc-linux-gnu

**Comment by psh882003** [comment]
yes



psh882003@163.com 
 
From: hqhangyu
Date: 2020-05-15 14:34
To: apache/shardingsphere
CC: psh882003; Comment
Subject: Re: [apache/shardingsphere] "AS" does not work in select sql (#5600)
which version of proxy? oracle or mysql, and version?
version of proxy is 410 and db is postgresql 10.12 on x86_64-pc-linux-gnu

**Comment by hqhangyu** [comment]
i got this exception.when i tried again,it may be  useful
[ERROR] 18:25:04.378 [pool-6-thread-1] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
java.lang.NullPointerException: null
 at org.apache.shardingsphere.shardingproxy.backend.response.query.QueryHeader.<init>(QueryHeader.java:85)
 at org.apache.shardingsphere.shardingproxy.backend.response.query.QueryHeader.<init>(QueryHeader.java:67)
 at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.callback.ProxySQLExecuteCallback.getQueryHeaders(ProxySQLExecuteCallback.java:101)
 at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.callback.ProxySQLExecuteCallback.getQueryHeaders(ProxySQLExecuteCallback.java:93)
 at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.callback.ProxySQLExecuteCallback.executeSQL(ProxySQLExecuteCallback.java:86)
 at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.callback.ProxySQLExecuteCallback.executeSQL(ProxySQLExecuteCallback.java:77)
 at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.callback.ProxySQLExecuteCallback.executeSQL(ProxySQLExecuteCallback.java:46)
 at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteCallback.execute0(SQLExecuteCallback.java:82)
 at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteCallback.execute(SQLExecuteCallback.java:58)
 at org.apache.shardingsphere.underlying.executor.engine.ExecutorEngine.syncExecute(ExecutorEngine.java:97)
 at org.apache.shardingsphere.underlying.executor.engine.ExecutorEngine.parallelExecute(ExecutorEngine.java:93)
 at org.apache.shardingsphere.underlying.executor.engine.ExecutorEngine.execute(ExecutorEngine.java:76)
 at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteTemplate.execute(SQLExecuteTemplate.java:68)
 at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.JDBCExecuteEngine.execute(JDBCExecuteEngine.java:78)
 at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCD

**Comment by licyclone** [comment]
in jdbcDrived for pg ,ResultSetMetaData.getColumnName  return the aliasName of colunm ，not actualName of colunm.how can we fix this？

**Comment by hqhangyu** [comment]
> in jdbcDrived for pg ,ResultSetMetaData.getColumnName return the aliasName of colunm ，not actualName of colunm.how can we fix this？

yes,that is why "AS" does not work,i also found the reason.

**Comment by kimmking** [comment]
@hqhangyu @psh882003 
It has been fixed in 4.1.1

https://github.com/apache/shardingsphere/pull/5907
