### ISSUE TITLE
the service method is select readonly transaction report the  error "Expected command status BEGIN, got ."

### ISSUE THREAD

**Issue by psh882003** [apache/shardingsphere#5626]
## Bug Report
[2020-05-15 16:22:27.980][ERROR][http-nio-8987-exec-10][tansun-tcp-
### Cause: org.postgresql.util.PSQLException: Expected command status BEGIN, got .
; SQL []; Expected command status BEGIN, got .; nested exception is org.postgresql.util.PSQLException: Expected command status BEGIN, got .
org.springframework.dao.DataAccessResourceFailureException: 
### Cause: org.postgresql.util.PSQLException: Expected command status BEGIN, got .
; SQL []; Expected command status BEGIN, got .; nested exception is org.postgresql.util.PSQLException: Expected command status BEGIN, got .
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:105) ~[spring-jdbc-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73) ~[spring-jdbc-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:82) ~[spring-jdbc-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:82) ~[spring-jdbc-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:75) ~[mybatis-spring-1.3.0.jar:1.3.0]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:447) ~[mybatis-spring-1.3.0.jar:1.3.0]
	at com.sun.proxy.$Proxy133.selectList(Unknown Source) ~[?:?]
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:231) ~[mybatis-spring-1.3.0.jar:1.3.0]
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:137) ~[mybatis-3.4.1.jar:3.4.1]
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:75) ~[mybatis-3.4.1.jar:3.4.1]
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:53) ~[mybatis-3.4.1.jar:3.4.1]
	at com.sun.proxy.$Proxy134.findDicts(Unknown Source) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at com.jeedev.msdp.core.interceptor.BaseDMLInterceptor.invoke(BaseDMLInterceptor.java:191) ~[classes/:?]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at com.sun.proxy.$Proxy135.findDicts(Unknown Source) ~[?:?]
	at com.jeedev.msdp.base.dict.service.impl.DictServiceImpl.findDicts(DictServiceImpl.java:50) ~[msdp-dict-service-2.3.1-xdyf-SNAPSHOT.jar:?]
	at com.jeedev.msdp.base.dict.utlis.DictUtil.initDictList(DictUtil.java:130) ~[msdp-dict-service-2.3.1-xdyf-SNAPSHOT.jar:?]
	at com.jeedev.msdp.base.dict.utlis.DictUtil.initDictsMap(DictUtil.java:100) ~[msdp-dict-service-2.3.1-xdyf-SNAPSHOT.jar:?]
	at com.jeedev.msdp.base.dict.utlis.DictUtil.getDictValue(DictUtil.java:83) ~[msdp-dict-service-2.3.1-xdyf-SNAPSHOT.jar:?]
	at com.tansun.tcp.usecredit.rtlcontract.flow.api.impl.RtlContractFlowApiImpl.initUseCreditData(RtlContractFlowApiImpl.java:140) ~[classes/:?]
	at com.tansun.tcp.usecredit.rtlcontract.common.api.impl.CommonUseCreditFlowApiImpl.handlProcessStart(CommonUseCreditFlowApiImpl.java:531) ~[classes/:?]
	at com.tansun.tcp.usecredit.rtlcontract.flow.api.impl.RtlContractFlowApiImpl.startFlowTrans(RtlContractFlowApiImpl.java:101) ~[classes/:?]
	at com.tansun.tcp.usecredit.rtlcontract.flow.api.impl.RtlContractFlowApiImpl$$FastClassBySpringCGLIB$$e289150d.invoke(<generated>) ~[classes/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282) ~[spring-tx-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:84) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at com.jeedev.msdp.trace.RpcServiceMethodAspect.invoke(RpcServiceMethodAspect.java:73) ~[msdp-utils-2.3.1-xdyf-SNAPSHOT.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:627) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:616) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at com.tansun.tcp.usecredit.rtlcontract.flow.api.impl.RtlContractFlowApiImpl$$EnhancerBySpringCGLIB$$3d5bdbf4.startFlowTrans(<generated>) ~[classes/:?]
	at com.tansun.tcp.usecredit.rtlcontract.exports.api.impl.IRtlContractFlowForOutApiImpl.startFlowTrans(IRtlContractFlowForOutApiImpl.java:28) ~[classes/:?]
	at com.tansun.tcp.usecredit.rtlcontract.exports.api.impl.IRtlContractFlowForOutApiImpl$$FastClassBySpringCGLIB$$cd5c99ac.invoke(<generated>) ~[classes/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282) ~[spring-tx-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:84) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at com.jeedev.msdp.trace.RpcServiceMethodAspect.invoke(RpcServiceMethodAspect.java:73) ~[msdp-utils-2.3.1-xdyf-SNAPSHOT.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:627) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:616) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671) ~[spring-aop-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at com.tansun.tcp.usecredit.rtlcontract.exports.api.impl.IRtlContractFlowForOutApiImpl$$EnhancerBySpringCGLIB$$39c2c531.startFlowTrans(<generated>) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
 sharding-proxy 4.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
 sharding-proxy 4.1.0
### Expected behavior
not report the error
### Actual behavior
n report the  error "Expected command status BEGIN, got ."
### Reason analyze (If you can)
sharding-proxy not surport the PG  local transaction 
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
"Expected command status BEGIN, got ."
### Example codes for reproduce this issue (such as a github link).
"Expected command status BEGIN, got ."

**Comment by cherrylzhao** [comment]
please tell us
1. Which version of ShardingSphere did you use?
2. Which project did you use? Sharding-JDBC or Sharding-Proxy?
3.Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

**Comment by hqhangyu** [comment]
> please tell us
> 
> 1. Which version of ShardingSphere did you use?
> 2. Which project did you use? Sharding-JDBC or Sharding-Proxy?
> 3. Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

sharding-proxy 4.1.0 and db is postgreSQL 10
i found that  when jdbc driver sent command  "BEGIN"  to proxy for transaction ,and  receive nothing from proxy.  but directly sent  it to pg, pg reply  "BEGIN". i don't why.

**Comment by cherrylzhao** [comment]
As you see, the response packet of `Begin command` is wrong currently, so transaction operation could not been supported.
