### ISSUE TITLE
What's the matter with this configuration in my 'yml' suffix file?

### ISSUE THREAD

**Issue by gfYaya** [apache/shardingsphere#5700]
I build my sharding-jdbc project according to this page:https://shardingsphere.apache.org/document/current/cn/manual/shardingsphere-jdbc/configuration/config-spring-boot/   .
It's only effective in the 'properties' suffix configuration file, and the console prints these exception info as the project with a 'yml' suffix configuration file.

Exception info:
2020-05-20 14:16:01.114 [main] INFO  com.alibaba.druid.pool.DruidDataSource -
				{dataSource-1} inited
2020-05-20 14:16:01.132 [Druid-ConnectionPool-Create-730935981] ERROR com.alibaba.druid.pool.DruidDataSource -
				create connection SQLException, url: null, errorCode 0, state 08001
java.sql.SQLNonTransientConnectionException: Cannot load connection class because of underlying exception: com.mysql.cj.exceptions.WrongArgumentException: The database URL cannot be null.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:79)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:131)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:219)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1596)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1662)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2601)
Caused by: com.mysql.cj.exceptions.UnableToConnectException: Cannot load connection class because of underlying exception: com.mysql.cj.exceptions.WrongArgumentException: The database URL cannot be null.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	... 4 common frames omitted
Caused by: com.mysql.cj.exceptions.WrongArgumentException: The database URL cannot be null.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.conf.ConnectionUrlParser.isConnectionStringSupported(ConnectionUrlParser.java:149)
	at com.mysql.cj.conf.ConnectionUrl.acceptsUrl(ConnectionUrl.java:258)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:187)
	... 3 common frames omitted

The same exception printed recursively.
This is my 'yml' configuration:
spring:
    #spring sharding jdbc 配置
    shardingsphere:
      datasource:
        names: dataaudit
        dataaudit:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://XXX:3306/jiaanpei_dataudit?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
          username: 
          password: 
      sharding:
        tables:
          # janpb_goods_supp_standard_snapshot表分片策略
          janpb_goods_supp_standard_snapshot:
            table-strategy:
              inline:
                # 根据companyCode 进行分片
                sharding-column: companyCode
                algorithm-expression: dataaudit.janpb_goods_supp_standard_snapshot_$->{companyCode % 32}
                ###分表的总数 0到31   janpb_goods_supp_standard_snapshot_0, .... janpb_goods_supp_standard_snapshot_31
            actual-data-nodes: dataaudit.janpb_goods_supp_standard_snapshot_$->{0..31}
      props:
        sql:
          ### 开启分片日志
          show: true

The core pom infos:
         <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.15</version>
        </dependency>
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>${sharding-jdbc.version}</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
            <version>1.1.16</version>
        </dependency>

I have tried to config that:
    'type: !!com.alibaba.druid.pool.DruidDataSource '  with double  excalmatory marks instead of  'type: com.alibaba.druid.pool.DruidDataSource' according to the https://shardingsphere.apache.org/document/current/cn/manual/shardingsphere-jdbc/configuration/config-yaml/, I failed again.

So, how to correct my 'yml' configurations.
Thank you very much.

**Comment by gfYaya** [comment]
![image](https://user-images.githubusercontent.com/10221432/82414209-479f6380-9aa9-11ea-9e37-f0b7d6c498c0.png)

**Comment by gfYaya** [comment]
![微信截图_20200520145204](https://user-images.githubusercontent.com/10221432/82415839-b1207180-9aab-11ea-831e-c5ff92c204fd.png)

**Comment by gfYaya** [comment]
![微信截图_20200520145204](https://user-images.githubusercontent.com/10221432/82416032-fe044800-9aab-11ea-9e31-7e6c8d85debe.png)

**Comment by kimmking** [comment]
remove druid-spring-boot-starter and try again.

**Comment by gfYaya** [comment]
> remove druid-spring-boot-starter and try again.

It does not work...
emmm.
I guess, the matter is in the Sharding-jdbc datasource proxy.

**Comment by gfYaya** [comment]
Thank your for your help.I find the matter.It's jar confict,though I don't know the reason.
thanks.
