### ISSUE TITLE
shardingJDBC-4.0.0-RC3+spring-4.3+mybatis-3.3  java.lang.NoClassDefFoundError: org/antlr/v4/runtime/CharStreams

### ISSUE THREAD

**Issue by JOYS369** [apache/shardingsphere#5723]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
shardingJDBC-4.0.0-RC3

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Actual behavior
Could not deserialize ATN with UUID 59627784-3be5-417a-b9eb-8131a7286089 (expected aadb8d7e-aeef-4415-ad2b-8204d6cf042e or a legacy UUID).

I can't start my project

### Reason analyze (If you can)
1、dataSource or SQL parse is error
2、shadingJDBC require the  specify antlr version ? example 4.7.1?

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
pom.xml :

        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-core</artifactId>
            <version>4.0.0-RC3</version>
        </dependency>

        
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-namespace</artifactId>
            <version>4.0.0-RC3</version>
        </dependency>

spring context.xml:

<bean id="master" class="org.springframework.jndi.JndiObjectFactoryBean">
        <property name="jndiName" value="${db.master.jndiName}"/>
    </bean>

    <bean id="slave_1" class="org.springframework.jndi.JndiObjectFactoryBean">
        <property name="jndiName" value="${db.slave1.jndiName}"/>
    </bean>

    <master-slave:load-balance-algorithm id="randomStrategy" type="ROUND_ROBIN" />

    <master-slave:data-source id="dataSource" master-data-source-name="master" slave-data-source-names="slave_1" strategy-ref="randomStrategy">
        <master-slave:props>
            <prop key="sql.show">true</prop>
            <prop key="executor.size">10</prop>
            <prop key="foo">bar</prop>
        </master-slave:props>
    </master-slave:data-source>

config.properties:
db.master.jndiName=java:comp/env/jdbc/mdm_master
db.slave1.jndiName=java:comp/env/jdbc/mdm_slave1

tomcat context.xml ....

**Comment by kimmking** [comment]
log details and what sql you executed?

**Comment by JOYS369** [comment]
> log details and what sql you executed?

I can't start my project.

log details:
[antlr version is : 4.5.3]:
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
	... 244 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.antlr.v4.runtime.CharStreams
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1308)
[2020-05-22 04:11:51,701] Artifact core:war: Error during artifact deployment. See server log for details.
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1142)
	... 260 common frames omitted




[antlr version is : 4.8]:
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:408)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:474)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:484)
	at com.hand.hap.core.impl.LanguageProviderImpl.reload(LanguageProviderImpl.java:62)
	at com.hand.hap.core.impl.LanguageProviderImpl.afterPropertiesSet(LanguageProviderImpl.java:54)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
	... 244 common frames omitted
Caused by: java.lang.UnsupportedOperationException: java.io.InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with UUID 59627784-3be5-417a-b9eb-8131a7286089 (expected aadb8d7e-aeef-4415-ad2b-8204d6cf042e or a legacy UUID).
	at org.antlr.v4.runtime.atn.ATNDeserializer.deserialize(ATNDeserializer.java:153)
	at org.apache.shardingsphere.core.parse.autogen.MySQLStatementLexer.<clinit>(MySQLStatementLexer.java:3096)
	... 264 common frames omitted
Caused by: java.io.InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with UUID 59627784-3be5-417a-b9eb-8131a7286089 (expected aadb8d7e-aeef-4415-ad2b-8204d6cf042e or a legacy UUID).
	... 266 common frames omitted

**Comment by terrymanu** [comment]
ShardingSphere use antlr 4.7.2.
If you want to customize your dependencies' version, please resolve conflict by yourself.

**Comment by JOYS369** [comment]
my project use antlr 4.5.3，but the same error 。project can't start
