### ISSUE TITLE
sqlserver， when

### ISSUE THREAD

**Issue by zhaolin81** [apache/shardingsphere#5725]
Caused by: java.lang.NullPointerException: null
	at org.apache.shardingsphere.sql.parser.binder.metadata.table.TableMetaData.getIndexes(TableMetaData.java:72) ~[shardingsphere-sql-parser-binder-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.sql.parser.binder.metadata.table.TableMetaData.<init>(TableMetaData.java:53) ~[shardingsphere-sql-parser-binder-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.sql.parser.binder.metadata.schema.SchemaMetaDataLoader.load(SchemaMetaDataLoader.java:84) ~[shardingsphere-sql-parser-binder-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.sql.parser.binder.metadata.schema.SchemaMetaDataLoader.load(SchemaMetaDataLoader.java:76) ~[shardingsphere-sql-parser-binder-4.1.0.jar:4.1.0]

**Comment by kimmking** [comment]
jdbc? which version? what sql/operation did you do?

**Comment by zhaolin81** [comment]
> jdbc? which version? what sql/operation did you do?

i found that the master branch fixed this issue。

IndexMetaDataLoader：
                ...
                if(null != indexName) {
                    result.add(new IndexMetaData(indexName));
                }
            }

**Comment by zhaolin81** [comment]
> jdbc? which version? what sql/operation did you do?

北京的兄弟啊，你好哈

**Comment by zhaolin81** [comment]
fixed by https://github.com/apache/shardingsphere/pull/5436
