### ISSUE TITLE
mssqlserver ，when "select top 1 <column> from <table>" ，throws NullPointException

### ISSUE THREAD

**Issue by zhaolin81** [apache/shardingsphere#5782]
I changed to "select top (1)"  to sovle the problem，i think that was a bug。

**Comment by kimmking** [comment]
can you show the full exception stack?

**Comment by zhaolin81** [comment]
line 1:15 no viable alternative at input 'from'
line 1:15 extraneous input 'from' expecting {'!', '~', '+', '-', '(', '{', '?', TRUNCATE, FUNCTION, TRIGGER, CASE, CAST, IF, NULL, TRUE, FALSE, EXISTS, LIMIT, OFFSET, SAVEPOINT, BOOLEAN, CHAR, ARRAY, INTERVAL, DATE, TIME, TIMESTAMP, LOCALTIME, LOCALTIMESTAMP, QUARTER, WEEK, MICROSECOND, MAX, MIN, SUM, COUNT, AVG, ENABLE, DISABLE, INSTANCE, DO, DEFINER, SQL, CASCADED, LOCAL, NEXT, NAME, INTEGER, TYPE, BINARY, HIDDEN_, MOD, PARTITION, PARTITIONS, TOP, ROW, XOR, ALWAYS, ROLE, START, ALGORITHM, AUTO, BLOCKERS, CLUSTERED, NONCLUSTERED, COLUMNSTORE, CONTENT, CONVERT, DATABASE, YEARS, MONTHS, WEEKS, DAYS, MINUTES, DENY, DETERMINISTIC, DISTRIBUTION, DOCUMENT, DURABILITY, ENCRYPTED, FILESTREAM, FILETABLE, FILLFACTOR, FOLLOWING, HASH, HEAP, INBOUND, OUTBOUND, UNBOUNDED, INFINITE, LOGIN, MASKED, MAXDOP, MOVE, NOCHECK, OBJECT, OFF, ONLINE, OVER, PAGE, PAUSED, PERIOD, PERSISTED, PRECEDING, RANDOMIZED, RANGE, REBUILD, REPLICATE, REPLICATION, RESUMABLE, ROWGUIDCOL, SAVE, SELF, SPARSE, SWITCH, TRAN, TRANCOUNT, CONTROL, TAKE, OWNERSHIP, DEFINITION, APPLICATION, ASSEMBLY, SYMMETRIC, ASYMMETRIC, SERVER, RECEIVE, CHANGE, TRACE, TRACKING, RESOURCES, SETTINGS, STATE, AVAILABILITY, CREDENTIAL, ENDPOINT, EVENT, NOTIFICATION, LINKED, AUDIT, DDL, XML, IMPERSONATE, SECURABLES, AUTHENTICATE, EXTERNAL, ACCESS, ADMINISTER, BULK, OPERATIONS, UNSAFE, SHUTDOWN, SCOPED, CONFIGURATION, DATASPACE, SERVICE, CERTIFICATE, CONTRACT, ENCRYPTION, MASTER, DATA, SOURCE, FILE, FORMAT, LIBRARY, FULLTEXT, MASK, UNMASK, MESSAGE, REMOTE, BINDING, ROUTE, SECURITY, POLICY, AGGREGATE, QUEUE, RULE, SYNONYM, COLLECTION, SCRIPT, KILL, BACKUP, LOG, SHOWPLAN, SUBSCRIBE, QUERY, NOTIFICATIONS, CHECKPOINT, SEQUENCE, ABORT_AFTER_WAIT, ALLOW_PAGE_LOCKS, ALLOW_ROW_LOCKS, ALL_SPARSE_COLUMNS, BUCKET_COUNT, COLUMNSTORE_ARCHIVE, COLUMN_ENCRYPTION_KEY, COLUMN_SET, COMPRESSION_DELAY, DATABASE_DEAULT, DATA_COMPRESSION, DATA_CONSISTENCY_CHECK, ENCRYPTION_TYPE, SYSTEM_TIME, SYSTEM_VERSIONING, TEXTIMAGE_ON, WAIT_AT_LOW_PRIORITY, STATISTICS_INCREMENTAL, STATISTICS_NORECOMPUTE, ROUND_ROBIN, SCHEMA_AND_DATA, SCHEMA_ONLY, SORT_IN_TEMPDB, IGNORE_DUP_KEY, IMPLICIT_TRANSACTIONS, MAX_DURATION, MEMORY_OPTIMIZED, MIGRATION_STATE, PAD_INDEX, REMOTE_DATA_ARCHIVE, FILESTREAM_ON, FILETABLE_COLLATE_FILENAME, FILETABLE_DIRECTORY, FILETABLE_FULLPATH_UNIQUE_CONSTRAINT_NAME, FILETABLE_PRIMARY_KEY_CONSTRAINT_NAME, FILETABLE_STREAMID_UNIQUE_CONSTRAINT_NAME, FILTER_PREDICATE, HISTORY_RETENTION_PERIOD, HISTORY_TABLE, LOCK_ESCALATION, DROP_EXISTING, ROW_NUMBER, FIRST, DATETIME2, IDENTIFIER_, STRING_, NUMBER_, HEX_DIGIT_, BIT_NUM_}
line 1:34 mismatched input '<EOF>' expecting {')', ROW_NUMBER}
2020-05-26 09:10:02.294 ERROR 38396 --- [nio-8080-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18) ~[antlr4-runtime-4.7.2.jar:4.7.2]
	at org.apache.shardingsphere.sql.parser.sqlserver.visitor.impl.SQLServerDMLVisitor.createProjection(SQLServerDMLVisitor.java:344) ~[shardingsphere-sql-parser-sqlserver-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.sql.parser.sqlserver.visitor.impl.SQLServerDMLVisitor.visitProjection(SQLServerDMLVisitor.java:332) ~[shardingsphere-sql-parser-sqlserver-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.sql.parser.sqlserver.visitor.impl.SQLServerDMLVisitor.visitProjection(SQLServerDMLVisitor.java:103) ~[shardingsphere-sql-parser-sqlserver-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.sql.parser.autogen.SQLServerStatementParser$ProjectionContext.accept(SQLServerStatementParser.java:2602) ~[shardingsphere-sql-parser-sqlserver-4.1.0.jar:4.1.0]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18) ~[antlr4-runtime-4.7.2.jar:4.7.2]
	at org.apache.shardingsphere.sql.parser.sqlserver.visitor.impl.SQLServerDMLVisitor.visitProjections(SQLServerDMLVisitor.java:308) ~[shardingsphere-sql-parser-sqlserver-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.sql.parser.sqlserver.visitor.impl.SQLServerDMLVisitor.visitProjections(SQLServerDMLVisitor.java:103) ~[shardingsphere-sql-parser-sqlserver-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.sql.parser.autogen.SQLServerStatementParser$ProjectionsContext.accept(SQLServerStatementParser.java:2282) ~[shardingsphere-sql-parser-sqlserver-4.1.0.jar:4.1.0]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18) ~[antlr4-runtime-4.7.2.jar:4.7.2]
	at org.apache.shardingsphere.sql.parser.sqlserver.visitor.impl.SQLServerDMLVisitor.visitSelectClause(SQLServerDMLVisitor.java:250) ~[shardingsphere-sql-parser-sqlserver-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.sql.parser.sqlserver.visitor.impl.SQLServerDMLVisitor.visitSelectClause(SQLServerDMLVisitor.java:103) ~[shardingsphere-sql-parser-sqlserver-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.sql.parser.autogen.SQLServerStatementParser$SelectClauseContext.accept(SQLServerStatementParser.java:2129) ~[shardingsphere-sql-parser-sqlserver-4.1.0.jar:4.1.0]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18) ~[antlr4-runtime-4.7.2.jar:4.7.2]
	at org.apache.shardingsphere.sql.parser.sqlserver.visitor.impl.SQLServerDMLVisitor.visitUnionClause(SQLServerDMLVisitor.java:243) ~[shardingsphere-sql-parser-sqlserver-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.sql.parser.sqlserver.visitor.impl.SQLServerDMLVisitor.visitUnionClause(SQLServerDMLVisitor.java:103) ~[shardingsphere-sql-parser-sqlserver-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.sql.parser.autogen.SQLServerStatementParser$UnionClauseContext.accept(SQLServerStatementParser.java:2039) ~[shardingsphere-sql-parser-sqlserver-4.1.0.jar:4.1.0]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18) ~[antlr4-runtime-4.7.2.jar:4.7.2]
	at org.apache.shardingsphere.sql.parser.sqlserver.visitor.impl.SQLServerDMLVisitor.visitSelect(SQLServerDMLVisitor.java:235) ~[shardingsphere-sql-parser-sqlserver-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.sql.parser.sqlserver.visitor.impl.SQLServerDMLVisitor.visitSelect(SQLServerDMLVisitor.java:103) ~[shardingsphere-sql-parser-sqlserver-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.sql.parser.autogen.SQLServerStatementParser$SelectContext.accept(SQLServerStatementParser.java:1988) ~[shardingsphere-sql-parser-sqlserver-4.1.0.jar:4.1.0]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18) ~[antlr4-runtime-4.7.2.jar:4.7.2]
	at org.apache.shardingsphere.sql.parser.SQLParserEngine.parse0(SQLParserEngine.java:80) ~[shardingsphere-sql-parser-engine-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.sql.parser.SQLParserEngine.parse(SQLParserEngine.java:61) ~[shardingsphere-sql-parser-engine-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.underlying.route.DataNodeRouter.createRouteContext(DataNodeRouter.java:97) ~[shardingsphere-route-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.underlying.route.DataNodeRouter.executeRoute(DataNodeRouter.java:89) ~[shardingsphere-route-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.underlying.route.DataNodeRouter.route(DataNodeRouter.java:76) ~[shardingsphere-route-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.underlying.pluggble.prepare.SimpleQueryPrepareEngine.route(SimpleQueryPrepareEngine.java:54) ~[shardingsphere-pluggable-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.underlying.pluggble.prepare.BasePrepareEngine.executeRoute(BasePrepareEngine.java:96) ~[shardingsphere-pluggable-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.underlying.pluggble.prepare.BasePrepareEngine.prepare(BasePrepareEngine.java:83) ~[shardingsphere-pluggable-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.EncryptStatement.getRewriteSQL(EncryptStatement.java:90) ~[sharding-jdbc-core-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.EncryptStatement.executeQuery(EncryptStatement.java:77) ~[sharding-jdbc-core-4.1.0.jar:4.1.0]

**Comment by tristaZero** [comment]
@zhaolin81 Hi thanks for your feedback, this feature is ongoing by @SteNicholas .
Please wait for his good news for us!
