### ISSUE TITLE
ERROR 1054 (42S22): Unknown column 't_order.order_id' in 'field list'

### ISSUE THREAD

**Issue by hongfuli** [apache/shardingsphere#5857]
Which version of ShardingSphere did you use?
4.1.0

Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy

Steps to reproduce the behavior

when executing the follow sql: 
```sql
SELECT `t_order`.`user_id`, `t_order`.`order_id`, `t_order`.`name` FROM `t_order` ORDER BY `t_order`.`order_id` ASC  ;
```
the follow error is raised:
```bash
ERROR 1054 (42S22): Unknown column 't_order.order_id' in 'field list'
```

the actual sql is wrong:
```sql
SELECT `t_order_0`.`user_id`, `t_order_0`.`order_id`, `t_order_0`.`name` , `t_order`.`order_id` AS ORDER_BY_DERIVED_0 FROM `t_order_0` ORDER BY `t_order_0`.`order_id` ASC
```

**Comment by yu199195** [comment]
please.show you sharding config,  and  you use db  is mysql ,pgsql?

**Comment by hongfuli** [comment]
default configuration of the official release without any changes, and mysql

**Comment by hongfuli** [comment]
meanwhile, I found that `shardingsphere` is not good dealt with the sql style with schema prefix, for example:

```sql
DELETE FROM t_order WHERE order_id IN (1);
```
is ok, but
```sql
DELETE FROM `t_order` WHERE `t_order`.`order_id` IN (1);
```
is not work with the follow error:
```java
org.apache.shardingsphere.underlying.common.exception.ShardingSphereException: Cannot support Multiple-Table for 'org.apache.shardingsphere.sql.parser.sql.statement.dml.DeleteStatement@3293c2dc'.
	at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.route(ShardingStandardRoutingEngine.java:72)
	at org.apache.shardingsphere.sharding.route.engine.ShardingRouteDecorator.decorate(ShardingRouteDecorator.java:69)
	at org.apache.shardingsphere.sharding.route.engine.ShardingRouteDecorator.decorate(ShardingRouteDecorator.java:53)
	at org.apache.shardingsphere.underlying.route.DataNodeRouter.executeRoute(DataNodeRouter.java:91)
	at org.apache.shardingsphere.underlying.route.DataNodeRouter.route(DataNodeRouter.java:76)
	at org.apache.shardingsphere.underlying.pluggble.prepare.SimpleQueryPrepareEngine.route(SimpleQueryPrepareEngine.java:54)
	at org.apache.shardingsphere.underlying.pluggble.prepare.BasePrepareEngine.executeRoute(BasePrepareEngine.java:96)
	at org.apache.shardingsphere.underlying.pluggble.prepare.BasePrepareEngine.prepare(BasePrepareEngine.java:83)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.wrapper.StatementExecutorWrapper.doShardingRoute(StatementExecutorWrapper.java:80)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.wrapper.StatementExecutorWrapper.route(StatementExecutorWrapper.java:63)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:74)
	at org.apache.shardingsphere.shardingproxy.backend.text.query.QueryBackendHandler.execute(QueryBackendHandler.java:52)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:73)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:93)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by yu199195** [comment]
ok,we'll keep track of it and fix it in the near future, you can use unprefixed ones for the time being.

**Comment by hongfuli** [comment]
very unfortunately I use orm framework to access db, I can't completely control the style of sql. :(

**Comment by yu199195** [comment]
> very unfortunately I use orm framework to access db, I can't completely control the style of sql

you can use shrding-jdbc. sharding-proxy,  I'm not sure I support that now.

**Comment by hongfuli** [comment]
the project is not based java.

**Comment by kimmking** [comment]
I reproduce it now.
And will fix it in 4.1.1.

**Comment by hongfuli** [comment]
Great, thank you

**Comment by kimmking** [comment]
Cases as we know:

- [ ] `select t_order.status from t_order order by t_order.id asc;`
- [ ] `select t_order.status from t_order,t_order_item where t_order.order_id=t_order_item.order_id order by t_order.id asc;`
- [ ] `select status,t_order.order_id+1 from t_order;`

**Comment by kimmking** [comment]
@hongfuli  As an alternative choice, we suggest:
- Plan A: You can remove all prefix of column: SELECT `user_id`, `order_id`, `name` FROM `t_order` ORDER BY `order_id` ASC  ;
- Plan B: You also can add an alias for  table: SELECT `t_order`.`user_id`, `t_order`.`order_id`, `t_order`.`name` FROM `t_order` as `t_order`  ORDER BY `t_order`.`order_id` ASC  ;

**Comment by hongfuli** [comment]
thanks for your suggestion.
But I use the orm framework based python, the generated SQL is not under my control

**Comment by kimmking** [comment]
After make a deep investigation, it need to make more time to fix it, so we will pending it for the latest release version, and move to version 5.0.0.

**Comment by hongfuli** [comment]
ok, thanks

**Comment by kimmking** [comment]
@jingshanglu will track it.

**Comment by jingshanglu** [comment]
I'll track it.
