### ISSUE TITLE
select case when throws nullpoint exception

### ISSUE THREAD

**Issue by zhaolin81** [apache/shardingsphere#5870]
select case when 1=1 then 1 else 0 end

java.lang.NullPointerException: null
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18) ~[antlr4-runtime-4.7.2.jar:4.7.2]
	at org.apache.shardingsphere.sql.parser.mysql.visitor.MySQLVisitor.visitCaseExpression(MySQLVisitor.java:585) ~[shardingsphere-sql-parser-mysql-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.sql.parser.mysql.visitor.MySQLVisitor.visitCaseExpression(MySQLVisitor.java:121) ~[shardingsphere-sql-parser-mysql-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$CaseExpressionContext.accept(MySQLStatementParser.java:17875) ~[shardingsphere-sql-parser-mysql-4.1.0.jar:4.1.0]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18) ~[antlr4-runtime-4.7.2.jar:4.7.2]
	at org.apache.shardingsphere.sql.parser.mysql.visitor.MySQLVisitor.visitRemainSimpleExpr(MySQLVisitor.java:572) ~[shardingsphere-sql-parser-mysql-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.sql.parser.mysql.visitor.MySQLVisitor.visitSimpleExpr(MySQLVisitor.java:431) ~[shardingsphere-sql-parser-mysql-4.1.0.jar:4.1.0]
	at org.apache.shardingsphere.sql.parser.mysql.visitor.MySQLVisitor.visitSimpleExpr(MySQLVisitor.java:121) ~[shardingsphere-sql-parser-mysql-4.1.0.jar:4.1.0]

**Comment by kimmking** [comment]
![image](https://user-images.githubusercontent.com/807508/83393596-9e058e00-a429-11ea-9609-097311d020fa.png)

It test ok in master branch.

**Comment by zhaolin81** [comment]
> ![image](https://user-images.githubusercontent.com/807508/83393596-9e058e00-a429-11ea-9609-097311d020fa.png)
> 
> It test ok in master branch.

thanks , i'm using release 4.1.0

**Comment by kimmking** [comment]
@jingshanglu could you test this and carry to dev-4.x?

**Comment by jingshanglu** [comment]
@kimmking  @zhaolin81 This issue has been fixed,new version will be ok.
