### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.shardingsphere.orchestration.center.yaml.config.YamlCenterRepositoryConfiguration

### ISSUE THREAD

**Issue by ganzr** [apache/shardingsphere#5947]
sharding-proxy version: 4.1.0
mysql version: 5.7.29
os: windows
when start sharding-proxy, exception thrown like below:

Starting the Sharding-Proxy ...
Exception in thread "main" Cannot create property=authentication for JavaBean=org.apache.shardingsphere.shardingproxy.config.yaml.YamlProxyServerConfiguration@270421f5
 in 'reader', line 36, column 1:
    authentication:
    ^
Type org.apache.shardingsphere.orchestration.center.yaml.config.YamlCenterRepositoryConfiguration not present
 in 'reader', line 37, column 3:
      users:
      ^

        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:312)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:345)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:410)
        at org.apache.shardingsphere.underlying.common.yaml.engine.YamlEngine.unmarshal(YamlEngine.java:74)
        at org.apache.shardingsphere.underlying.common.yaml.engine.YamlEngine.unmarshal(YamlEngine.java:56)
        at org.apache.shardingsphere.shardingproxy.config.ShardingConfigurationLoader.loadServerConfiguration(ShardingConfigurationLoader.java:72)
        at org.apache.shardingsphere.shardingproxy.config.ShardingConfigurationLoader.load(ShardingConfigurationLoader.java:56)
        at org.apache.shardingsphere.shardingproxy.Bootstrap.main(Bootstrap.java:82)
Caused by: java.lang.TypeNotPresentException: Type org.apache.shardingsphere.orchestration.center.yaml.config.YamlCenterRepositoryConfiguration not present
        at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
        at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
        at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
        at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
        at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
        at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
        at sun.reflect.generics.repository.ConstructorRepository.getParameterTypes(ConstructorRepository.java:94)
        at java.lang.reflect.Executable.getGenericParameterTypes(Executable.java:279)
        at java.lang.reflect.Method.getGenericParameterTypes(Method.java:268)
        at java.beans.FeatureDescriptor.getParameterTypes(FeatureDescriptor.java:387)
        at java.beans.MethodDescriptor.setMethod(MethodDescriptor.java:116)
        at java.beans.MethodDescriptor.<init>(MethodDescriptor.java:72)
        at java.beans.MethodDescriptor.<init>(MethodDescriptor.java:56)
        at java.beans.Introspector.getTargetMethodInfo(Introspector.java:1163)
        at java.beans.Introspector.getBeanInfo(Introspector.java:426)
        at java.beans.Introspector.getBeanInfo(Introspector.java:173)
        at org.yaml.snakeyaml.introspector.PropertyUtils.getPropertiesMap(PropertyUtils.java:63)
        at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:126)
        at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:121)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.getProperty(Constructor.java:322)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:240)
        ... 12 more
Caused by: java.lang.ClassNotFoundException: org.apache.shardingsphere.orchestration.center.yaml.config.YamlCenterRepositoryConfiguration
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:344)
        at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
        ... 32 more

it seems that some package is not present in the lib?

**Comment by ganzr** [comment]
the lib directory:
![image](https://user-images.githubusercontent.com/20966436/84014677-4b8a1b80-a9ad-11ea-8ffd-51be47613947.png)

**Comment by menghaoranss** [comment]
Some jar files were truncated，you need to unzip again with other tools.

**Comment by ganzr** [comment]
Thanks! it works.

**Comment by gengzi** [comment]
thanks
