### ISSUE TITLE
java.lang.IllegalStateException: Database type inconsistent with 'org.apache.shardingsphere.underlying.common.database.type.dialect.SQL92DatabaseType@5d7dd549' and 'org.apache.shardingsphere.underlying.common.database.type.dialect.MySQLDatabaseType@65600fb3'

### ISSUE THREAD

**Issue by guoyzh** [apache/shardingsphere#6020]
user vsrsion4.1.1 with srpingBoot on demo start appearance this:
`Caused by: java.lang.IllegalStateException: Database type inconsistent with 'org.apache.shardingsphere.underlying.common.database.type.dialect.SQL92DatabaseType@5d7dd549' and 'org.apache.shardingsphere.underlying.common.database.type.dialect.MySQLDatabaseType@65600fb3'
	at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
	at org.apache.shardingsphere.shardingjdbc.jdbc.adapter.AbstractDataSourceAdapter.createDatabaseType(AbstractDataSourceAdapter.java:66)
	at org.apache.shardingsphere.shardingjdbc.jdbc.adapter.AbstractDataSourceAdapter.<init>(AbstractDataSourceAdapter.java:53)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.datasource.ShardingDataSource.<init>(ShardingDataSource.java:52)
	at org.apache.shardingsphere.shardingjdbc.api.ShardingDataSourceFactory.createDataSource(ShardingDataSourceFactory.java:48)
	at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration.shardingDataSource(SpringBootConfiguration.java:103)
	at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration$$EnhancerBySpringCGLIB$$fbfb8eb2.CGLIB$shardingDataSource$2(<generated>)
	at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration$$EnhancerBySpringCGLIB$$fbfb8eb2$$FastClassBySpringCGLIB$$f6a99bba.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration$$EnhancerBySpringCGLIB$$fbfb8eb2.shardingDataSource(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 45 common frames omitted`

**Comment by menghaoranss** [comment]
@guoyzh Please provide your configuration , this exception is caused by configuring different db.

**Comment by terrymanu** [comment]
Can you change the title for search friendly?

**Comment by terrymanu** [comment]
Closed because of no response anymore.

**Comment by guoyzh** [comment]
Thank you for your efforts

**Comment by guoyzh** [comment]
Thank you for your efforts

**Comment by edminy** [comment]
vsrsion4.1.1 Do not support configuring different databases?
