### ISSUE TITLE
SQLFeatureNotSupportedException: setSavepoint name

### ISSUE THREAD

**Issue by keepsupers** [apache/shardingsphere#6021]
I use the transaction:Propagation.NESTED, But the result is error;
error message is :SQLFeatureNotSupportedException: setSavepoint name

Caused by: java.sql.SQLFeatureNotSupportedException: setSavepoint name
	at org.apache.shardingsphere.shardingjdbc.jdbc.unsupported.AbstractUnsupportedOperationConnection.setSavepoint(AbstractUnsupportedOperationConnection.java:71)
	at org.springframework.jdbc.datasource.ConnectionHolder.createSavepoint(ConnectionHolder.java:187)
	at org.springframework.jdbc.datasource.JdbcTransactionObjectSupport.createSavepoint(JdbcTransactionObjectSupport.java:119)

**Comment by menghaoranss** [comment]
`setSavepoint` is not yet supported, if you are interested, you can try to achieve.

**Comment by terrymanu** [comment]
For sharding + distributed transaction is not easy to support, we have no plan to do it for now
