### ISSUE TITLE
liquibase  used setFetchSize,   Hope to support soon

### ISSUE THREAD

**Issue by HanKaiqiang** [apache/shardingsphere#6101]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?

Using liquibase and shardingsphere at the project will be problematic because liquibase will used
setFetchSize

liquibase version 3.6.3

sharding-jdbc-spring-boot-starter  version  4.1.1

### Describe the feature you would like.
support setFetchSize

**Comment by kimmking** [comment]
can you make a pr for it?

**Comment by HanKaiqiang** [comment]
@kimmking   sorry,  no

**Comment by tuohai666** [comment]
Thanks for your report. Can you provide more information?

Please provide the actual behavior originally, rawly and straightforwardly without any analysis. It means raw input/output data, or raw log, config...

You didn't fill in the bug report template, so I have to ask you here what's the release version? What's application(ShardingSphere-JDBC or ShardingSphere-Proxy)?

When you use setFetchSize, what's the value you set?

You mentioned you haven met problem when use setFetchSize, what is the exact problem?

At last, if you have some findings and want to analyze, please do it in a separate section.

**Comment by tuohai666** [comment]
Above is my comment 11 days ago in https://github.com/apache/shardingsphere/issues/5986. I don't know why you just ignored and open this duplicated issue. I this issue, you still have to answer these questions.

**Comment by HanKaiqiang** [comment]
> 感谢您的举报。您能否提供更多信息？
> 
> 请原始，直接且未经任何分析地提供实际行为。这意味着原始输入/输出数据或原始日志，配置...
> Caused by: liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.DatabaseException: java.sql.SQLFeatureNotSupportedException: setFetchSize
	at liquibase.changelog.StandardChangeLogHistoryService.init(StandardChangeLogHistoryService.java:111)
	at liquibase.Liquibase.checkLiquibaseTables(Liquibase.java:1219)
	at liquibase.Liquibase.update(Liquibase.java:193)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:353)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:305)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774)
	... 16 common frames omitted
Caused by: liquibase.exception.DatabaseException: java.sql.SQLFeatureNotSupportedException: setFetchSize
	at liquibase.snapshot.ResultSetCache.get(ResultSetCache.java:101)
	at liquibase.snapshot.JdbcDatabaseSnapshot$CachingDatabaseMetaData.getTables(JdbcDatabaseSnapshot.java:791)
	at liquibase.snapshot.jvm.TableSnapshotGenerator.snapshotObject(TableSnapshotGenerator.java:33)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:66)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:69)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:69)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:69)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:69)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:69)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:69)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
	at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:286)
	at liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:102)
	at liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:59)
	at liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:38)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:217)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:246)
	at liquibase.snapshot.SnapshotGeneratorFactory.getDatabaseChangeLogTable(SnapshotGeneratorFactory.java:254)
	at liquibase.changelog.StandardChangeLogHistoryService.init(StandardChangeLogHistoryService.java:108)
	... 23 common frames omitted
Caused by: java.sql.SQLFeatureNotSupportedException: setFetchSize
	at org.apache.shardingsphere.shardingjdbc.jdbc.unsupported.AbstractUnsupportedDatabaseMetaDataResultSet.setFetchSize(AbstractUnsupportedDatabaseMetaDataResultSet.java:123)
	at liquibase.snapshot.ResultSetCache$ResultSetExtractor.extract(ResultSetCache.java:293)
	at liquibase.snapshot.ResultSetCache$ResultSetExtractor.extract(ResultSetCache.java:288)
	at liquibase.snapshot.JdbcDatabaseSnapshot$CachingDatabaseMetaData$4.fastFetchQuery(JdbcDatabaseSnapshot.java:832)
	at liquibase.snapshot.ResultSetCache$SingleResultSetExtractor.fastFetch(ResultSetCache.java:347)
	at liquibase.snapshot.ResultSetCache.get(ResultSetCache.java:70)
	... 47 common frames omitted

> 您没有填写错误报告模板，所以我必须问您这里是什么发行版本？什么是应用程序（ShardingSphere-JDBC或ShardingSphere-Proxy）？
> sharding-jdbc-spring-boot-starter version 4.1.1
   liquibase version 3.6.3

> 使用setFetchSize时，设置的值是多少？
>  

> 您提到使用setFetchSize时遇到问题，确切的问题是什么？
>  I didn’t use setFetchSize directly. I used setFetchSize internally in liquibase. I get an error when using both liquibase and Sharding Sphere in the project.

> 最后，如果您有发现并要分析，请在单独的部分中进行。

**Comment by HanKaiqiang** [comment]
> Above is my comment 11 days ago in #5986. I don't know why you just ignored and open this duplicated issue. I this issue, you still have to answer these questions.

Sorry, I didn’t notice it at the time

**Comment by HanKaiqiang** [comment]
> Thanks for your report. Can you provide more information?
> 
> Please provide the actual behavior originally, rawly and straightforwardly without any analysis. It means raw input/output data, or raw log, config...
> 
Caused by: liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.DatabaseException: java.sql.SQLFeatureNotSupportedException: setFetchSize
  at liquibase.changelog.StandardChangeLogHistoryService.init(StandardChangeLogHistoryService.java:111)
  at liquibase.Liquibase.checkLiquibaseTables(Liquibase.java:1219)
  at liquibase.Liquibase.update(Liquibase.java:193)
  at liquibase.Liquibase.update(Liquibase.java:179)
  at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:353)
  at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:305)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774)
... 16 common frames omitted
Caused by: liquibase.exception.DatabaseException: java.sql.SQLFeatureNotSupportedException: setFetchSize
  at liquibase.snapshot.ResultSetCache.get(ResultSetCache.java:101)
  at liquibase.snapshot.JdbcDatabaseSnapshot$CachingDatabaseMetaData.getTables(JdbcDatabaseSnapshot.java:791)
  at liquibase.snapshot.jvm.TableSnapshotGenerator.snapshotObject(TableSnapshotGenerator.java:33)
  at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:66)
  at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
  at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:69)
  at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
  at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:69)
  at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
  at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:69)
  at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
  at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:69)
  at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
  at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:69)
  at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
  at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:69)
  at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
  at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:286)
  at liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:102)
  at liquibase.snapshot.DatabaseSnapshot.(DatabaseSnapshot.java:59)
  at liquibase.snapshot.JdbcDatabaseSnapshot.(JdbcDatabaseSnapshot.java:38)
  at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:217)
  at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:246)
  at liquibase.snapshot.SnapshotGeneratorFactory.getDatabaseChangeLogTable(SnapshotGeneratorFactory.java:254)
  at liquibase.changelog.StandardChangeLogHistoryService.init(StandardChangeLogHistoryService.java:108)
... 23 common frames omitted
Caused by: java.sql.SQLFeatureNotSupportedException: setFetchSize
  at org.apache.shardingsphere.shardingjdbc.jdbc.unsupported.AbstractUnsupportedDatabaseMetaDataResultSet.setFetchSize(AbstractUnsupportedDatabaseMetaDataResultSet.java:123)
  at liquibase.snapshot.ResultSetCache$ResultSetExtractor.extract(ResultSetCache.java:293)
  at liquibase.snapshot.ResultSetCache$ResultSetExtractor.extract(ResultSetCache.java:288)
  at liquibase.snapshot.JdbcDatabaseSnapshot$CachingDatabaseMetaData$4.fastFetchQuery(JdbcDatabaseSnapshot.java:832)
  at liquibase.snapshot.ResultSetCache$SingleResultSetExtractor.fastFetch(ResultSetCache.java:347)
  at liquibase.snapshot.ResultSetCache.get(ResultSetCache.java:70)
... 47 common frames omitted


> You didn't fill in the bug report template, so I have to ask you here what's the release version? What's application(ShardingSphere-JDBC or ShardingSphere-Proxy)?
> 
  sharding-jdbc-spring-boot-starter version 4.1.1
  liquibase version 3.6.3

> When you use setFetchSize, what's the value you set?
> 
> You mentioned you haven met problem when use setFetchSize, what is the exact problem?
> 
  I didn’t use setFetchSize directly. I used setFetchSize internally in liquibase. I get an error when using both liquibase and Shardingsphere in the project.

> At last, if you have some findings and want to analyze, please do it in a separate section.
