### ISSUE TITLE
cannot support  @ColumnTransformer for AES_DECRYPT AES_ENCRYPT

### ISSUE THREAD

**Issue by larry0592** [apache/shardingsphere#6195]
## Bug Report
```
@Entity
@Table(name = "t_order")
public class Order implements Serializable {
    
    private static final long serialVersionUID = 661434701950670670L;
    
    @Id
    @Column(name = "order_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long orderId;
    
    @Column(name = "user_id")
    private int userId;
    
    @Column(name = "status")
    private String status;

    @Column(name = "remote_time")
    private Long remoteTime;

    @Column(name = "remote_time_str",length = 32)
    private String remoteTimeStr;

    @Column(name = "create_time")
    private Long createTime;

    @Column(name = "create_time_str",length = 32)
    private String createTimeStr;

    @Column(name = "corp_id",length = 32)
    private String corpId;

    @Basic
    @Column(name = "content",nullable=true ,length=128)
    @ColumnTransformer(
            read = "CAST(AES_DECRYPT(UNHEX(content), 'biocloud0592') AS CHAR)",
            write = "HEX(AES_ENCRYPT(?, 'biocloud0592'))"
    )
    private String content;

    @Column(name="info_type")
    private int infoType;
```
```
Hibernate: insert into t_order (content, corp_id, create_time, create_time_str, info_type, remote_time, remote_time_str, status, user_id) values (HEX(AES_ENCRYPT(?, 'biocloud0592')), ?, ?, ?, ?, ?, ?, ?, ?)
2020-06-28 15:42:36.696  INFO 18292 --- [           main] ShardingSphere-SQL                       : Logic SQL: insert into t_order (content, corp_id, create_time, create_time_str, info_type, remote_time, remote_time_str, status, user_id) values (HEX(AES_ENCRYPT(?, 'biocloud0592')), ?, ?, ?, ?, ?, ?, ?, ?)
2020-06-28 15:42:36.696  INFO 18292 --- [           main] ShardingSphere-SQL                       : SQLStatement: InsertStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.InsertStatement@1c8a2bec, tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@140db646), tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@140db646, columnNames=[content, corp_id, create_time, create_time_str, info_type, remote_time, remote_time_str, status, user_id], insertValueContexts=[InsertValueContext(parametersCount=8, valueExpressions=[org.apache.shardingsphere.sql.parser.sql.segment.dml.item.ExpressionProjectionSegment@4e5d611f, ParameterMarkerExpressionSegment(startIndex=172, stopIndex=172, parameterMarkerIndex=1), ParameterMarkerExpressionSegment(startIndex=175, stopIndex=175, parameterMarkerIndex=2), ParameterMarkerExpressionSegment(startIndex=178, stopIndex=178, parameterMarkerIndex=3), ParameterMarkerExpressionSegment(startIndex=181, stopIndex=181, parameterMarkerIndex=4), ParameterMarkerExpressionSegment(startIndex=184, stopIndex=184, parameterMarkerIndex=5), ParameterMarkerExpressionSegment(startIndex=187, stopIndex=187, parameterMarkerIndex=6), ParameterMarkerExpressionSegment(startIndex=190, stopIndex=190, parameterMarkerIndex=7), ParameterMarkerExpressionSegment(startIndex=193, stopIndex=193, parameterMarkerIndex=8)], parameters=[cmpId:0,value:a7570c0ad6514543ab56c37b9e28ef0b, a7570c0ad6514543ab56c37b9e28ef0b, 1593243754, null, 0, null, null, a7570c0ad6514543ab56c37b9e28ef0b])], generatedKeyContext=Optional.empty)
2020-06-28 15:42:36.697  INFO 18292 --- [           main] ShardingSphere-SQL                       : Actual SQL: ds ::: insert into t_order (content, corp_id, create_time, create_time_str, info_type, remote_time, remote_time_str, status, user_id) values (HEX(AES_ENCRYPT(?,'biocloud0592')), ?, ?, ?, ?, ?, ?, ?, ?) ::: [cmpId:0,value:a7570c0ad6514543ab56c37b9e28ef0b, a7570c0ad6514543ab56c37b9e28ef0b, 1593243754, null, 0, null, null, a7570c0ad6514543ab56c37b9e28ef0b]
2020-06-28 15:42:36.846  WARN 18292 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 07001
2020-06-28 15:42:36.847 ERROR 18292 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : No value specified for parameter 9
```
```
Caused by: java.sql.SQLException: No value specified for parameter 9
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1117) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1042) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1345) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1027) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeUpdate(DruidPooledPreparedStatement.java:255) ~[druid-1.1.21.jar:1.1.21]
	at org.apache.shardingsphere.shardingjdbc.executor.SQLExecuteCallbackFactory$1.executeSQL(SQLExecuteCallbackFactory.java:45) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.executor.SQLExecuteCallbackFactory$1.executeSQL(SQLExecuteCallbackFactory.java:41) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteCallback.execute0(SQLExecuteCallback.java:82) ~[sharding-core-execute-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteCallback.execute(SQLExecuteCallback.java:58) ~[sharding-core-execute-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.underlying.executor.engine.ExecutorEngine.syncExecute(ExecutorEngine.java:97) ~[shardingsphere-executor-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.underlying.executor.engine.ExecutorEngine.serialExecute(ExecutorEngine.java:82) ~[shardingsphere-executor-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.underlying.executor.engine.ExecutorEngine.execute(ExecutorEngine.java:76) ~[shardingsphere-executor-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteTemplate.execute(SQLExecuteTemplate.java:68) ~[sharding-core-execute-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteTemplate.execute(SQLExecuteTemplate.java:51) ~[sharding-core-execute-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.executor.AbstractStatementExecutor.executeCallback(AbstractStatementExecutor.java:129) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.executeUpdate(PreparedStatementExecutor.java:123) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.executeUpdate(ShardingPreparedStatement.java:133) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175) ~[hibernate-core-5.3.10.Final.jar:5.3.10.Final]
	... 59 common frames omitted
```

**Comment by tristaZero** [comment]
@larry0592 Hi 
Sorry to say currently we do not support this annotation, however, we welcome you or others to light up your mind and contribute it to this community. :)

Best wishes,
Trista

**Comment by larry0592** [comment]
@tristaZero 
I modify version 4.1.1 sourcecode   org.apache.shardingsphere.sql.parser.binder.segment.insert.values.InsertValueContext **can work well**

**can you merge or fix  it?**

```
  private int calculateParametersCount(final Collection<ExpressionSegment> assignments) {
        int result = 0;
        for (ExpressionSegment each : assignments) {
            if (each instanceof ParameterMarkerExpressionSegment) {
                result++;
            }
            // add by larry 2020-06-30  修复增加 each instanceof ExpressionProjectionSegment
            if (each instanceof ExpressionProjectionSegment) {
                String text = ((ExpressionProjectionSegment) each).getText();
                if (text !=null && text.contains("?")) {
                    result++;
                }
            }
        }
        return result;
    }
```

**Comment by tristaZero** [comment]
Hi @larry0592 thanks for your feedback.
I looked at the log you provided once again. I guessed the key point is that ShardingPaser did not parse out the parameter in function properly, which has been fixed on our master branch already.

**Do you think my assumption is right or not?**
> insert into t_order (content, corp_id, create_time, create_time_str, info_type, remote_time, remote_time_str, status, user_id) values (HEX(AES_ENCRYPT(**?**, 'biocloud0592')), ?, ?, ?, ?, ?, ?, ?, ?)
