### ISSUE TITLE
Running a strange exception to the project exception.tomcat7 and tomcat8 

### ISSUE THREAD

**Issue by 65725738** [apache/shardingsphere#6347]
```
java.lang.NullPointerException
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
        at org.apache.shardingsphere.sql.parser.mysql.visitor.MySQLVisitor.visitPredicate(MySQLVisitor.java:316)
        at org.apache.shardingsphere.sql.parser.mysql.visitor.MySQLVisitor.visitPredicate(MySQLVisitor.java:121)
        at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$PredicateContext.accept(MySQLStatementParser.java:11690)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
        at org.apache.shardingsphere.sql.parser.mysql.visitor.MySQLVisitor.visitBooleanPrimary(MySQLVisitor.java:273)
        at org.apache.shardingsphere.sql.parser.mysql.visitor.MySQLVisitor.visitBooleanPrimary(MySQLVisitor.java:121)
        at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$BooleanPrimaryContext.accept(MySQLStatementParser.java:11463)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
        at org.apache.shardingsphere.sql.parser.mysql.visitor.MySQLVisitor.visitExpr(MySQLVisitor.java:258)
        at org.apache.shardingsphere.sql.parser.mysql.visitor.MySQLVisitor.visitExpr(MySQLVisitor.java:121)
        at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$ExprContext.accept(MySQLStatementParser.java:11241)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
        at org.apache.shardingsphere.sql.parser.mysql.visitor.impl.MySQLDMLVisitor.visitAssignmentValue(MySQLDMLVisitor.java:250)
        at org.apache.shardingsphere.sql.parser.mysql.visitor.impl.MySQLDMLVisitor.visitAssignmentValue(MySQLDMLVisitor.java:127)
        at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$AssignmentValueContext.accept(MySQLStatementParser.java:1941)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
        at org.apache.shardingsphere.sql.parser.mysql.visitor.impl.MySQLDMLVisitor.visitAssignment(MySQLDMLVisitor.java:242)
        at org.apache.shardingsphere.sql.parser.mysql.visitor.impl.MySQLDMLVisitor.visitAssignment(MySQLDMLVisitor.java:127)
        at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$AssignmentContext.accept(MySQLStatementParser.java:1753)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
        at org.apache.shardingsphere.sql.parser.mysql.visitor.impl.MySQLDMLVisitor.visitSetAssignmentsClause(MySQLDMLVisitor.java:225)
        at org.apache.shardingsphere.sql.parser.mysql.visitor.impl.MySQLDMLVisitor.visitSetAssignmentsClause(MySQLDMLVisitor.java:127)
        at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$SetAssignmentsClauseContext.accept(MySQLStatementParser.java:1801)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
        at org.apache.shardingsphere.sql.parser.mysql.visitor.impl.MySQLDMLVisitor.visitUpdate(MySQLDMLVisitor.java:213)
        at org.apache.shardingsphere.sql.parser.mysql.visitor.impl.MySQLDMLVisitor.visitUpdate(MySQLDMLVisitor.java:127)
        at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$UpdateContext.accept(MySQLStatementParser.java:1622)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
        at org.apache.shardingsphere.sql.parser.SQLParserEngine.parse0(SQLParserEngine.java:80)
        at org.apache.shardingsphere.sql.parser.SQLParserEngine.parse(SQLParserEngine.java:61)
        at org.apache.shardingsphere.underlying.route.DataNodeRouter.createRouteContext(DataNodeRouter.java:97)
        at org.apache.shardingsphere.underlying.route.DataNodeRouter.executeRoute(DataNodeRouter.java:89)
        at org.apache.shardingsphere.underlying.route.DataNodeRouter.route(DataNodeRouter.java:76)
        at org.apache.shardingsphere.underlying.pluggble.prepare.SimpleQueryPrepareEngine.route(SimpleQueryPrepareEngine.java:54)
        at org.apache.shardingsphere.underlying.pluggble.prepare.BasePrepareEngine.executeRoute(BasePrepareEngine.java:96)
        at org.apache.shardingsphere.underlying.pluggble.prepare.BasePrepareEngine.prepare(BasePrepareEngine.java:83)
        at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingStatement.prepare(ShardingStatement.java:224)
        at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingStatement.executeUpdate(ShardingStatement.java:101)
        at org.springframework.jdbc.core.JdbcTemplate$1UpdateStatementCallback.doInStatement(JdbcTemplate.java:532)
        at org.springframework.jdbc.core.JdbcTemplate$1UpdateStatementCallback.doInStatement(JdbcTemplate.java:529)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:408)
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:544)
        at com.badu.bdsaas.aa.service.impl.AbstractSubjectServiceImpl.updateLastLgnInfo(AbstractSubjectServiceImpl.java:158)
        at com.badu.bdsaas.aa.service.impl.AbstractSubjectServiceImpl.logon(AbstractSubjectServiceImpl.java:253)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
```

why?

**Comment by 65725738** [comment]
The Eclipse Tomcat7 Maven plug-in can be run.But packaging under Tomcat is not good, report an error.Neither Tomcat7 nor Tomcat8 works.

**Comment by kimmking** [comment]
It seems sql syntax error.

**Comment by 65725738** [comment]
The Eclipse Tomcat7 Maven plug-in can be run. if  sql syntax error，Why it works？

**Comment by 65725738** [comment]
2020-07-15 09:23:41,137 INFO http-bio-8080-exec-3 ShardingSphere-SQL - SQLStatement: InsertStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.InsertStatement@2a48199c, tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@4a651eab), tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@4a651eab, columnNames=[principal, profile_id, soptype_cd, app_cd, usr_type_cd, is_success], insertValueContexts=[InsertValueContext(parametersCount=6, valueExpressions=[ParameterMarkerExpressionSegment(startIndex=228, stopIndex=228, parameterMarkerIndex=0), ParameterMarkerExpressionSegment(startIndex=253, stopIndex=253, parameterMarkerIndex=1), ParameterMarkerExpressionSegment(startIndex=278, stopIndex=278, parameterMarkerIndex=2), ParameterMarkerExpressionSegment(startIndex=303, stopIndex=303, parameterMarkerIndex=3), ParameterMarkerExpressionSegment(startIndex=328, stopIndex=328, parameterMarkerIndex=4), ParameterMarkerExpressionSegment(startIndex=353, stopIndex=353, parameterMarkerIndex=5)], parameters=[admin, 1, LGN, CONOSLE, E, true])], generatedKeyContext=Optional.empty)
   2020-07-15 09:23:41,138 INFO http-bio-8080-exec-3 ShardingSphere-SQL - Actual SQL: ds_master ::: insert into aa_subject_log
     ( principal,
      
      
        profile_id,
      
      
        soptype_cd,
      
      
        app_cd,
      
      
        usr_type_cd,
      
      
        is_success ) 
     values (?, ?, ?, ?, ?, ?) ::: [admin, 1, LGN, CONOSLE, E, true]
   2020-07-15 09:23:41,178 DEBUG http-bio-8080-exec-3 com.badu.bdsaas.aa.dao.SubjectLogMapper.insertSelective - <==    Updates: 1
   2020-07-15 09:23:41,205 INFO http-bio-8080-exec-3 com.badu.bdsaas.aa.service.impl.AbstractAAService - strategy:2
   2020-07-15 09:23:42,929 ERROR http-bio-8080-exec-3 fmp-runtime-exception - 
   java.lang.NullPointerException
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
        at org.apache.shardingsphere.sql.parser.mysql.visitor.MySQLVisitor.visitPredicate(MySQLVisitor.java:316)
        at org.apache.shardingsphere.sql.parser.mysql.visitor.MySQLVisitor.visitPredicate(MySQLVisitor.java:121)
        at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$PredicateContext.accept(MySQLStatementParser.java:11690)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
        at org.apache.shardingsphere.sql.parser.mysql.visitor.MySQLVisitor.visitBooleanPrimary(MySQLVisitor.java:273)
        at org.apache.shardingsphere.sql.parser.mysql.visitor.MySQLVisitor.visitBooleanPrimary(MySQLVisitor.java:121)
        at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$BooleanPrimaryContext.accept(MySQLStatementParser.java:11463)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
        at org.apache.shardingsphere.sql.parser.mysql.visitor.MySQLVisitor.visitExpr(MySQLVisitor.java:258)
        at org.apache.shardingsphere.sql.parser.mysql.visitor.MySQLVisitor.visitExpr(MySQLVisitor.java:121)


Data has been stored in mysql. and then error!


> 
> 
> It seems sql syntax error.
> So can you show your logic sql.

   2020-07-15 09:23:41,137 INFO http-bio-8080-exec-3 ShardingSphere-SQL - SQLStatement: InsertStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.InsertStatement@2a48199c, tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@4a651eab), tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@4a651eab, columnNames=[principal, profile_id, soptype_cd, app_cd, usr_type_cd, is_success], insertValueContexts=[InsertValueContext(parametersCount=6, valueExpressions=[ParameterMarkerExpressionSegment(startIndex=228, stopIndex=228, parameterMarkerIndex=0), ParameterMarkerExpressionSegment(startIndex=253, stopIndex=253, parameterMarkerIndex=1), ParameterMarkerExpressionSegment(startIndex=278, stopIndex=278, parameterMarkerIndex=2), ParameterMarkerExpressionSegment(startIndex=303, stopIndex=303, parameterMarkerIndex=3), ParameterMarkerExpressionSegment(startIndex=328, stopIndex=328, parameterMarkerIndex=4), ParameterMarkerExpressionSegment(startIndex=353, stopIndex=353, parameterMarkerIndex=5)], parameters=[admin, 1, LGN, CONOSLE, E, true])], generatedKeyContext=Optional.empty)
   2020-07-15 09:23:41,138 INFO http-bio-8080-exec-3 ShardingSphere-SQL - Actual SQL: ds_master ::: insert into aa_subject_log
     ( principal,
      
      
        profile_id,
      
      
        soptype_cd,
      
      
        app_cd,
      
      
        usr_type_cd,
      
      
        is_success ) 
     values (?, ?, ?, ?, ?, ?) ::: [admin, 1, LGN, CONOSLE, E, true]
   2020-07-15 09:23:41,178 DEBUG http-bio-8080-exec-3 com.badu.bdsaas.aa.dao.SubjectLogMapper.insertSelective - <==    Updates: 1
   2020-07-15 09:23:41,205 INFO http-bio-8080-exec-3 com.badu.bdsaas.aa.service.impl.AbstractAAService - strategy:2
   2020-07-15 09:23:42,929 ERROR http-bio-8080-exec-3 fmp-runtime-exception - 
   java.lang.NullPointerException
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
        at org.apache.shardingsphere.sql.parser.mysql.visitor.MySQLVisitor.visitPredicate(MySQLVisitor.java:316)
        at org.apache.shardingsphere.sql.parser.mysql.visitor.MySQLVisitor.visitPredicate(MySQLVisitor.java:121)
        at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$PredicateContext.accept(MySQLStatementParser.java:11690)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
        at org.apache.shardingsphere.sql.parser.mysql.visitor.MySQLVisitor.visitBooleanPrimary(MySQLVisitor.java:273)
        at org.apache.shardingsphere.sql.parser.mysql.visitor.MySQLVisitor.visitBooleanPrimary(MySQLVisitor.java:121)
        at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$BooleanPrimaryContext.accept(MySQLStatementParser.java:11463)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
        at org.apache.shardingsphere.sql.parser.mysql.visitor.MySQLVisitor.visitExpr(MySQLVisitor.java:258)
        at org.apache.shardingsphere.sql.parser.mysql.visitor.MySQLVisitor.visitExpr(MySQLVisitor.java:121)


Data has been stored in mysql. and then error!

**Comment by 65725738** [comment]
String SQL = " update usr_profile set lgn_cnt = lgn_cnt + 1, last_lgn_time = CURRENT_TIMESTAMP where profile_id =" + credential.getProfileId();
        jdbcTemplate.update(SQL);

Is this SQL supported?

**Comment by tristaZero** [comment]
Hi @65725738 Your log convinced us it is something with SQL parsing issue.
Which version is your app using?

@jingshanglu Could you give this SQL a look? I am not sure whether it is supported in our previous releases.

**Comment by jingshanglu** [comment]
> Hi @65725738 Your log convinced us it is something with SQL parsing issue.
> Which version is your app using?
> 
> @jingshanglu Could you give this SQL a look? I am not sure whether it is supported in our previous releases.

Now, master branch is ok @tristaZero @65725738 
![image](https://user-images.githubusercontent.com/16559542/87501385-8ad51780-c691-11ea-942a-80213c2ee286.png)
