### ISSUE TITLE
I think SQLParser is an error

### ISSUE THREAD

**Issue by slowquery** [apache/shardingsphere#6363]
## Bug Report

i try sharding on Amaon RDS with mysql, but isn't not supported error
also example code is mysql, what is a problem?

```
java.lang.UnsupportedOperationException: Cannot support database type 'MySQL'
	at org.apache.shardingsphere.sql.parser.core.parser.SQLParserFactory.newInstance(SQLParserFactory.java:55)
	at org.apache.shardingsphere.sql.parser.core.parser.SQLParserExecutor.towPhaseParse(SQLParserExecutor.java:55)
	at org.apache.shardingsphere.sql.parser.core.parser.SQLParserExecutor.execute(SQLParserExecutor.java:47)
	at org.apache.shardingsphere.sql.parser.SQLParserEngine.parse0(SQLParserEngine.java:79)
	at org.apache.shardingsphere.sql.parser.SQLParserEngine.parse(SQLParserEngine.java:61)
	at org.apache.shardingsphere.underlying.route.DataNodeRouter.createRouteContext(DataNodeRouter.java:97)
	at org.apache.shardingsphere.underlying.route.DataNodeRouter.executeRoute(DataNodeRouter.java:89)
	at org.apache.shardingsphere.underlying.route.DataNodeRouter.route(DataNodeRouter.java:76)
	at org.apache.shardingsphere.underlying.pluggble.prepare.PreparedQueryPrepareEngine.route(PreparedQueryPrepareEngine.java:54)
	at org.apache.shardingsphere.underlying.pluggble.prepare.BasePrepareEngine.executeRoute(BasePrepareEngine.java:96)
	at org.apache.shardingsphere.underlying.pluggble.prepare.BasePrepareEngine.prepare(BasePrepareEngine.java:83)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.prepare(ShardingPreparedStatement.java:183)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.executeUpdate(ShardingPreparedStatement.java:131)
```

**Comment by slowquery** [comment]
yaml & java same this.
mysql connect is successfully, but SQL execute error

**Comment by tristaZero** [comment]
@slowquery Hi
What is your SQL inputted?

**Comment by slowquery** [comment]
```
 String createBlockSQL = "INSERT INTO Block (DomainId, BlockName, BlockTimestamp)" +
      "VALUES (?, ?, ?, ?)";
      PreparedStatement createBlockQuery = conn.prepareStatement(createBlockSQL, Statement.RETURN_GENERATED_KEYS);

      Timestamp ts = new Timestamp(this.BlockTimestamp);

      createBlockQuery.setInt(1, this.DomainId);
      createBlockQuery.setInt(2, this.BlockName);
      createBlockQuery.setTimestamp(3, ts);

      int createBlockResult = createBlockQuery.executeUpdate();
```

createBlockQuery.executeUpdate(); this function execute, an error occurred

**Comment by kimmking** [comment]
you can try:
>  String createBlockSQL = "INSERT INTO Block (DomainId, BlockName, BlockTimestamp)" +
      " VALUES (?, ?, ?)";

**Comment by slowquery** [comment]
it is same problem
can you check 'Cannot support database type' Exception throw logic check?

**Comment by slowquery** [comment]
Sorry, i mistake.

i'm not added build.gradle
```
implementation 'org.apache.shardingsphere:shardingsphere-sql-parser-mysql:4.1.1'
```

close issue
