### ISSUE TITLE
sharding-jdbc 4.1.1 与mybatis-plus 3.3.1 druid 版本1.1.23 集成报错

### ISSUE THREAD

**Issue by pearina** [apache/shardingsphere#6428]
Caused by: java.sql.SQLFeatureNotSupportedException: getObject with type
	at org.apache.shardingsphere.shardingjdbc.jdbc.unsupported.AbstractUnsupportedOperationResultSet.getObject(AbstractUnsupportedOperationResultSet.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.ResultSetLogger.invoke(ResultSetLogger.java:69)
	at com.sun.proxy.$Proxy205.getObject(Unknown Source)
	at org.apache.ibatis.type.LocalDateTimeTypeHandler.getNullableResult(LocalDateTimeTypeHandler.java:38)
	at org.apache.ibatis.type.LocalDateTimeTypeHandler.getNullableResult(LocalDateTimeTypeHandler.java:28)
	at org.apache.ibatis.type.BaseTypeHandler.getResult(BaseTypeHandler.java:81)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.applyAutomaticMappings(DefaultResultSetHandler.java:521)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getRowValue(DefaultResultSetHandler.java:402)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValuesForSimpleResultMap(DefaultResultSetHandler.java:354)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValues(DefaultResultSetHandler.java:328)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSet(DefaultResultSetHandler.java:301)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:194)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:65)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)

**Comment by tristaZero** [comment]
Hi @pearina 
This information here is inadequate. See, there is no any keyword about ShardingSphere. I suggest you give more stack log.

**Comment by tristaZero** [comment]
Plush, please rename this title in English. Thx

**Comment by Yogurt-lei** [comment]
I find this question too.

env:
mysql-connector-java: 8.0.20
mybatis-plus-boot-starter: 3.3.2
sharding-jdbc-spring-boot-starter: 4.1.1

when your entity is LocalDateTime ,so the `MyBatis  TypeHandler` is `LocalDateTimeTypeHandler#getNullableResult`,

but this is a unsupport operation in ShardingJdbc `AbstractUnsupportedOperationResultSet#getObject(columnIndex,type) throws SQLFeatureNotSupportedException` 


to resolve this question must override method in `ShardingResultSet` but the parent method is final tag  

Is this under repair ？

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by EricLye** [comment]
what is the reason that closing this issue?

**Comment by afallenhero** [comment]
How do I fix it
