### ISSUE TITLE
Actual sql parsing error when inserting mysql keyword usage

### ISSUE THREAD

**Issue by awnurrk** [apache/shardingsphere#6429]
2020-07-24 09:27:00.557  INFO 4660 --- [           main] ShardingSphere-SQL                       : Rule Type: sharding
2020-07-24 09:27:00.557  INFO 4660 --- [           main] ShardingSphere-SQL                       : Logic SQL: INSERT INTO template_sickness_detail_temporary  ( price,
`usage`,
frequency,
doctor_advice )  VALUES  ( ?,
?,
?,
? )
2020-07-24 09:27:00.558  INFO 4660 --- [           main] ShardingSphere-SQL                       : SQLStatement: InsertStatement(super=DMLStatement(super=AbstractSQLStatement(type=DML, tables=Tables(tables=[Table(name=template_sickness_detail_temporary, alias=Optional.absent())]), routeConditions=Conditions(orCondition=OrCondition(andConditions=[AndCondition(conditions=[])])), encryptConditions=Conditions(orCondition=OrCondition(andConditions=[])), sqlTokens=[TableToken(tableName=template_sickness_detail_temporary, quoteCharacter=NONE, schemaNameLength=0), SQLToken(startIndex=48)], parametersIndex=4, logicSQL=INSERT INTO template_sickness_detail_temporary  ( price,
`usage`,
frequency,
doctor_advice )  VALUES  ( ?,
?,
?,
? )), deleteStatement=false, updateTableAlias={}, updateColumnValues={}, whereStartIndex=0, whereStopIndex=0, whereParameterStartIndex=0, whereParameterEndIndex=0), columnNames=[price, usage, frequency, doctor_advice], values=[InsertValue(columnValues=[org.apache.shardingsphere.core.parse.old.parser.expression.SQLPlaceholderExpression@62cfb51a, org.apache.shardingsphere.core.parse.old.parser.expression.SQLPlaceholderExpression@6b542adc, org.apache.shardingsphere.core.parse.old.parser.expression.SQLPlaceholderExpression@45ca07cf, org.apache.shardingsphere.core.parse.old.parser.expression.SQLPlaceholderExpression@14676d59])])
2020-07-24 09:27:00.558  INFO 4660 --- [           main] ShardingSphere-SQL                       : Actual SQL: master0 ::: INSERT INTO template_sickness_detail_temporary   (price, usage, frequency, doctor_advice) VALUES (?, ?, ?, ?) ::: [56, dddd, deee, good]

org.springframework.jdbc.BadSqlGrammarException: 
### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'usage, frequency, doctor_advice) VALUES (56, 'dddd', 'deee', 'good')' at line 1
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'usage, frequency, doctor_advice) VALUES (56, 'dddd', 'deee', 'good')' at line 1

	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:235)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:88)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
	at com.sun.proxy.$Proxy167.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:271)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:60)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:96)
	at com.sun.proxy.$Proxy311.insert(Unknown Source)
	at com.keyi.base.TestMapper.test1(TestMapper.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'usage, frequency, doctor_advice) VALUES (56, 'dddd', 'deee', 'good')' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:498)
	at org.apache.shardingsphere.shardingjdbc.executor.SQLExecuteCallbackFactory$2.executeSQL(SQLExecuteCallbackFactory.java:65)
	at org.apache.shardingsphere.shardingjdbc.executor.SQLExecuteCallbackFactory$2.executeSQL(SQLExecuteCallbackFactory.java:61)
	at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteCallback.execute0(SQLExecuteCallback.java:69)
	at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteCallback.execute(SQLExecuteCallback.java:58)
	at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.syncGroupExecute(ShardingExecuteEngine.java:126)
	at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.parallelExecute(ShardingExecuteEngine.java:103)
	at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.groupExecute(ShardingExecuteEngine.java:83)
	at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteTemplate.executeGroup(SQLExecuteTemplate.java:73)
	at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteTemplate.executeGroup(SQLExecuteTemplate.java:56)
	at org.apache.shardingsphere.shardingjdbc.executor.AbstractStatementExecutor.executeCallback(AbstractStatementExecutor.java:128)
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.execute(PreparedStatementExecutor.java:156)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:172)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy383.update(Unknown Source)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doUpdate(MybatisSimpleExecutor.java:54)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.update(MybatisCachingExecutor.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at com.baomidou.mybatisplus.extension.plugins.OptimisticLockerInterceptor.intercept(OptimisticLockerInterceptor.java:69)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy382.update(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
	... 36 more

2020-07-24 09:27:00.713  INFO 4660 --- [      Thread-10] org.quartz.core.QuartzScheduler          : Scheduler quartzScheduler_$_NON_CLUSTERED paused.
2020-07-24 09:27:00.727  INFO 4660 --- [      Thread-10] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2020-07-24 09:27:00.727  INFO 4660 --- [      Thread-10] o.s.s.quartz.SchedulerFactoryBean        : Shutting down Quartz Scheduler
2020-07-24 09:27:00.727  INFO 4660 --- [      Thread-10] org.quartz.core.QuartzScheduler          : Scheduler quartzScheduler_$_NON_CLUSTERED shutting down.
2020-07-24 09:27:00.727  INFO 4660 --- [      Thread-10] org.quartz.core.QuartzScheduler          : Scheduler quartzScheduler_$_NON_CLUSTERED paused.
2020-07-24 09:27:00.728  INFO 4660 --- [      Thread-10] org.quartz.core.QuartzScheduler          : Scheduler quartzScheduler_$_NON_CLUSTERED shutdown complete.
2020-07-24 09:27:00.759  INFO 4660 --- [      Thread-10] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'threadpool'
2020-07-24 09:27:00.789  INFO 4660 --- [      Thread-10] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService
2020-07-24 09:27:00.811  INFO 4660 --- [      Thread-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} closed
2020-07-24 09:27:00.813  INFO 4660 --- [      Thread-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-2} closed
Disconnected from the target VM, address: '127.0.0.1:58350', transport: 'socket'
2020-07-24 09:27:00.815  INFO 4660 --- [      Thread-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-3} closed

Process finished with exit code -1

**Comment by prefect1005** [comment]
usage is mysql keyword 
if you used it in one column, you should add `` surround usage, like `usage`

**Comment by awnurrk** [comment]
2020-07-24 10:04:35.916&nbsp; INFO 10204 --- [&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;main] c.a.nacos.client.config.impl.CacheData&nbsp; &nbsp;: [fixed-localhost_8848] [add-listener] ok, tenant=, dataId=keyi-module-base.yml, group=DEFAULT_GROUP, cnt=1
2020-07-24 10:04:36.820&nbsp; INFO 10204 --- [&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;main] ShardingSphere-SQL&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;: Rule Type: sharding
2020-07-24 10:04:36.821&nbsp; INFO 10204 --- [&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;main] ShardingSphere-SQL&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;: Logic SQL: INSERT INTO template_sickness_detail_temporary (
&nbsp; price,
&nbsp; `usage`,
&nbsp; frequency,
&nbsp; doctor_advice
)
VALUES
&nbsp; (56, 'dddd', 'deee', 'good')
2020-07-24 10:04:36.821&nbsp; INFO 10204 --- [&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;main] ShardingSphere-SQL&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;: SQLStatement: InsertStatement(super=DMLStatement(super=AbstractSQLStatement(type=DML, tables=Tables(tables=[Table(name=template_sickness_detail_temporary, alias=Optional.absent())]), routeConditions=Conditions(orCondition=OrCondition(andConditions=[AndCondition(conditions=[])])), encryptConditions=Conditions(orCondition=OrCondition(andConditions=[])), sqlTokens=[TableToken(tableName=template_sickness_detail_temporary, quoteCharacter=NONE, schemaNameLength=0), SQLToken(startIndex=47)], parametersIndex=0, logicSQL=INSERT INTO template_sickness_detail_temporary (
&nbsp; price,
&nbsp; `usage`,
&nbsp; frequency,
&nbsp; doctor_advice
)
VALUES
&nbsp; (56, 'dddd', 'deee', 'good')), deleteStatement=false, updateTableAlias={}, updateColumnValues={}, whereStartIndex=0, whereStopIndex=0, whereParameterStartIndex=0, whereParameterEndIndex=0), columnNames=[price, usage, frequency, doctor_advice], values=[InsertValue(columnValues=[org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@3cbe75ce, org.apache.shardingsphere.core.parse.old.parser.expression.SQLTextExpression@b945c43, org.apache.shardingsphere.core.parse.old.parser.expression.SQLTextExpression@9bd2d60, org.apache.shardingsphere.core.parse.old.parser.expression.SQLTextExpression@69052034])])
2020-07-24 10:04:36.821&nbsp; INFO 10204 --- [&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;main] ShardingSphere-SQL&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;: Actual SQL: master0 ::: INSERT INTO template_sickness_detail_temporary&nbsp; (price, usage, frequency, doctor_advice) VALUES (56, 'dddd', 'deee', 'good')


org.springframework.jdbc.BadSqlGrammarException:&nbsp;
### Error updating database.&nbsp; Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'usage, frequency, doctor_advice) VALUES (56, 'dddd', 'deee', 'good')' at line 1
### The error may exist in file [E:\developcode\could_master_0608\internet_hospital_could\keyi-module\keyi-module-base\target\classes\mapper\TemplateSicknessDetailTemporaryMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: INSERT INTO template_sickness_detail_temporary (&nbsp; &nbsp;price,&nbsp; &nbsp;`usage`,&nbsp; &nbsp;frequency,&nbsp; &nbsp;doctor_advice ) VALUES&nbsp; &nbsp;(56, 'dddd', 'deee', 'good')
### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'usage, frequency, doctor_advice) VALUES (56, 'dddd', 'deee', 'good')' at line 1
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'usage, frequency, doctor_advice) VALUES (56, 'dddd', 'deee', 'good')' at line 1


	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:235)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:88)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
	at com.sun.proxy.$Proxy167.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:271)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:60)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:96)
	at com.sun.proxy.$Proxy311.insertByMySelf(Unknown Source)
	at com.keyi.base.TestMapper.test5(TestMapper.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'usage, frequency, doctor_advice) VALUES (56, 'dddd', 'deee', 'good')' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:498)
	at org.apache.shardingsphere.shardingjdbc.executor.SQLExecuteCallbackFactory$2.executeSQL(SQLExecuteCallbackFactory.java:65)
	at org.apache.shardingsphere.shardingjdbc.executor.SQLExecuteCallbackFactory$2.executeSQL(SQLExecuteCallbackFactory.java:61)
	at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteCallback.execute0(SQLExecuteCallback.java:69)
	at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteCallback.execute(SQLExecuteCallback.java:58)
	at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.syncGroupExecute(ShardingExecuteEngine.java:126)
	at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.parallelExecute(ShardingExecuteEngine.java:103)
	at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.groupExecute(ShardingExecuteEngine.java:83)
	at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteTemplate.executeGroup(SQLExecuteTemplate.java:73)
	at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteTemplate.executeGroup(SQLExecuteTemplate.java:56)
	at org.apache.shardingsphere.shardingjdbc.executor.AbstractStatementExecutor.executeCallback(AbstractStatementExecutor.java:128)
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.execute(PreparedStatementExecutor.java:156)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:172)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy383.update(Unknown Source)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doUpdate(MybatisSimpleExecutor.java:54)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.update(MybatisCachingExecutor.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at com.baomidou.mybatisplus.extension.plugins.OptimisticLockerInterceptor.intercept(OptimisticLockerInterceptor.java:69)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy382.update(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
	... 36 more


2020-07-24 10:04:36.997&nbsp; INFO 10204 --- [&nbsp; &nbsp; &nbsp; Thread-10] org.quartz.core.QuartzScheduler&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; : Scheduler quartzScheduler_$_NON_CLUSTERED paused.
2020-07-24 10:04:37.009&nbsp; INFO 10204 --- [&nbsp; &nbsp; &nbsp; Thread-10] o.s.s.c.ThreadPoolTaskScheduler&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; : Shutting down ExecutorService 'taskScheduler'
2020-07-24 10:04:37.009&nbsp; INFO 10204 --- [&nbsp; &nbsp; &nbsp; Thread-10] o.s.s.quartz.SchedulerFactoryBean&nbsp; &nbsp; &nbsp; &nbsp; : Shutting down Quartz Scheduler
2020-07-24 10:04:37.009&nbsp; INFO 10204 --- [&nbsp; &nbsp; &nbsp; Thread-10] org.quartz.core.QuartzScheduler&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; : Scheduler quartzScheduler_$_NON_CLUSTERED shutting down.
2020-07-24 10:04:37.010&nbsp; INFO 10204 --- [&nbsp; &nbsp; &nbsp; Thread-10] org.quartz.core.QuartzScheduler&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; : Scheduler quartzScheduler_$_NON_CLUSTERED paused.
2020-07-24 10:04:37.010&nbsp; INFO 10204 --- [&nbsp; &nbsp; &nbsp; Thread-10] org.quartz.core.QuartzScheduler&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; : Scheduler quartzScheduler_$_NON_CLUSTERED shutdown complete.
2020-07-24 10:04:37.054&nbsp; INFO 10204 --- [&nbsp; &nbsp; &nbsp; Thread-10] o.s.s.concurrent.ThreadPoolTaskExecutor&nbsp; : Shutting down ExecutorService 'threadpool'
2020-07-24 10:04:37.084&nbsp; INFO 10204 --- [&nbsp; &nbsp; &nbsp; Thread-10] o.s.s.concurrent.ThreadPoolTaskExecutor&nbsp; : Shutting down ExecutorService
2020-07-24 10:04:37.103&nbsp; INFO 10204 --- [&nbsp; &nbsp; &nbsp; Thread-10] com.alibaba.druid.pool.DruidDataSource&nbsp; &nbsp;: {dataSource-1} closed
2020-07-24 10:04:37.104&nbsp; INFO 10204 --- [&nbsp; &nbsp; &nbsp; Thread-10] com.alibaba.druid.pool.DruidDataSource&nbsp; &nbsp;: {dataSource-2} closed
2020-07-24 10:04:37.105&nbsp; INFO 10204 --- [&nbsp; &nbsp; &nbsp; Thread-10] com.alibaba.druid.pool.DruidDataSource&nbsp; &nbsp;: {dataSource-3} closed
Disconnected from the target VM, address: '127.0.0.1:64317', transport: 'socket'

**Comment by awnurrk** [comment]
I have already added it, and the sql actually executed will be removed.

**Comment by awnurrk** [comment]
It can be executed when querying, updating, and deleting the mysql keyword usage, and an error will only be reported when inserting

**Comment by tristaZero** [comment]
Hi guy, Thanks for your comment. @prefect1005 
@awnurrk Which version do you adopt?
I get your point here.

> Actual SQL: INSERT INTO template_sickness_detail_temporary&nbsp; (price, usage, frequency, doctor_advice) VALUES (56, 'dddd', 'deee', 'good')

**Comment by awnurrk** [comment]
<!--sharding jdbc--&gt;
<dependency&gt;
   <groupId&gt;org.apache.shardingsphere</groupId&gt;
   <artifactId&gt;sharding-jdbc-spring-boot-starter</artifactId&gt;
   <version&gt;4.0.0-RC1</version&gt;
</dependency&gt;

**Comment by tristaZero** [comment]
@awnurrk Do you think a version upgrade is possible?

@jingshanglu Do you have any impression about this similar issue? I guess our `master branch` works well, right?

**Comment by awnurrk** [comment]
Is it a problem with my version? Which version should I use to solve this problem

**Comment by jingshanglu** [comment]
@awnurrk @tristaZero Now, master branch is ok.

**Comment by awnurrk** [comment]
Sincerely thank you for your tips, I changed the version to 4.1.1 and this problem was solved

**Comment by awnurrk** [comment]
Okay thank you
