### ISSUE TITLE
When I used the sub table in Oracle, there appeared "cause: java.lang.UnsupportedOperationException : cannot support database type 'SQL92' "

### ISSUE THREAD

**Issue by a312983516** [apache/shardingsphere#6464]
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.UnsupportedOperationException: Cannot support database type 'SQL92'
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy133.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at com.baomidou.mybatisplus.core.override.PageMapperMethod.executeForMany(PageMapperMethod.java:173)
	at com.baomidou.mybatisplus.core.override.PageMapperMethod.execute(PageMapperMethod.java:86)
	at com.baomidou.mybatisplus.core.override.PageMapperProxy.invoke(PageMapperProxy.java:64)
	at com.sun.proxy.$Proxy136.selectList(Unknown Source)
	at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.getOne(ServiceImpl.java:276)
	at com.baomidou.mybatisplus.extension.service.IService.getOne(IService.java:209)

**Comment by tristaZero** [comment]
@a312983516 Thanks for the issue.
1. Which version of ShardingSphere in your project?
2. Could you provide more stack information?

**Comment by terrymanu** [comment]
Closed because of no response anymore
