### ISSUE TITLE
Write Amplification Issue with Hibernate (for shard migrations)

### ISSUE THREAD

**Issue by darkpssngr** [apache/shardingsphere#6469]
I'm trying to see if we can perform zero downtime shard migration using ShardingSphere-jdbc itself. I tried returning 2 datasources from my HintShardingAlgorithm class. Although shardingsphere executes the query properly, hibernate returns an error as the expected resultcount is not the same as the actual resultCount.
is this a valid use-case to try and achieve with ShardingSphere? If not is there a recommended way to achieve this?

**Comment by jingshanglu** [comment]
@darkpssngr 

1. Which version of ShardingSphere in your project?
1. Could you provide stack info?

**Comment by darkpssngr** [comment]
sorry for the late reply. I'm using version 4.1.1 of shardingSphere. The error is not from shardingSphere but from JPA itself. 

    org.springframework.orm.jpa.JpaSystemException: Batch update returned unexpected row count from update [0]; actual row count: 2; expected: 1; nested exception is org.hibernate.jdbc.BatchedTooManyRowsAffectedException: Batch update returned unexpected row count from update [0]; actual row count: 2; expected: 1
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:351)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:253)
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:536)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:746)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:714)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:534)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:305)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)</pre>

**Comment by darkpssngr** [comment]
@jingshanglu added the info you requested. please let me know if more information is needed?

**Comment by darkpssngr** [comment]
@jingshanglu can you please help me with this?

**Comment by jingshanglu** [comment]
@darkpssngr Sorry for late reply, can you show the sql?

**Comment by terrymanu** [comment]
Closed because of no response anymore
