### ISSUE TITLE
Unsupported SQL of sctl:explain

### ISSUE THREAD

**Issue by lwtdev** [apache/shardingsphere#6482]
### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
```
mysql> sctl:explain select 1;
+-----------------+----------+
| datasource_name | sql      |
+-----------------+----------+
| ds_0            | select 1 |
+-----------------+----------+
```
### Actual behavior
```
mysql>  sctl:explain select 1;
ERROR 10002 (C1000): 2Unknown exception: [Unsupported SQL of `sctl:explain select 1`]
```
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
```sql
sctl:explain select 1;
```

**Comment by jingshanglu** [comment]
@lwtdev plz show stack info.

**Comment by lwtdev** [comment]
@jingshanglu 
```
[ERROR] 13:41:34.897 [ShardingSphere-Command-5] o.a.s.p.f.c.CommandExecutorTask - Exception occur:
org.apache.shardingsphere.sql.parser.exception.SQLParsingException: Unsupported SQL of `sctl:explain select 1`
        at org.apache.shardingsphere.sql.parser.core.parser.SQLParserExecutor.execute(SQLParserExecutor.java:49)
        at org.apache.shardingsphere.sql.parser.SQLParserEngine.parse0(SQLParserEngine.java:78)
        at org.apache.shardingsphere.sql.parser.SQLParserEngine.parse(SQLParserEngine.java:60)
        at org.apache.shardingsphere.proxy.backend.text.sctl.explain.ShardingCTLExplainBackendHandler.execute(ShardingCTLExplainBackendHandle
r.java:60)
        at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExe
cutor.java:78)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:105)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:80)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by jingshanglu** [comment]
@lwtdev I run the sql directly on mysql , it is also not support.

**Comment by lwtdev** [comment]
@jingshanglu You may try with sharding-proxy
SCTL (ShardingSphere-Proxy control language) 
https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/usage/sctl/

**Comment by tristaZero** [comment]
@lwtdev Hi thanks for your feedback.
@jingshanglu is working on the test for your SQL.
@cherrylzhao Could you give it a look as well?

**Comment by kimmking** [comment]
```
mysql> sctl:explain select * from test;
+-----------------+----------------------+
| datasource_name | sql                  |
+-----------------+----------------------+
| test            | select * from test00 |
| test            | select * from test01 |
| test            | select * from test02 |
| test            | select * from test03 |
+-----------------+----------------------+
4 rows in set (0.01 sec)

mysql> sctl:explain select 1;
+-----------------+----------+
| datasource_name | sql      |
+-----------------+----------+
| test            | select 1 |
+-----------------+----------+
1 row in set (0.01 sec)

```

**Comment by tristaZero** [comment]
@lwtdev Hi It has been fixed already, welcome your further test.
