### ISSUE TITLE
10002-2Unknown exception: [No signature of method: java.lang.String.mod() is applicable for argument types...

### ISSUE THREAD

**Issue by cay914** [apache/shardingsphere#6539]
Now, i use the navicat 11.1 version.

Ok, this time i can connect to sharding-proxy server.
Now, sharding-proxy shocking me.
![image](https://user-images.githubusercontent.com/6037435/88952030-6a2fd300-d2c9-11ea-89f8-395c405671e8.png)

the table 't_order' ddl

CREATE TABLE `t_order` (  `order_id` int(20) NOT NULL COMMENT '自动编号',  `user_id` bigint(20) NOT NULL COMMENT '客户编号',  `shop_id` bigint(20) NOT NULL COMMENT '商店编号',  `product_count` int(11) NOT NULL COMMENT '商品数量',  `product_amount_total` decimal(5,2) NOT NULL COMMENT '商品总价',  `order_amount_total` decimal(5,2) NOT NULL COMMENT '订单金额',  `logistics_fee` decimal(5,2) DEFAULT NULL COMMENT '运费金额',  `is_unpacking_inspection` tinyint(1) DEFAULT NULL COMMENT '是否开箱验货',  `is_invoice` tinyint(1) DEFAULT NULL COMMENT '是否开具发票',  `invoice_no` varchar(50) DEFAULT NULL COMMENT '发票编号',  `address_id` bigint(20) DEFAULT NULL COMMENT '收货地址编号',  `logistics_id` bigint(20) DEFAULT NULL COMMENT '订单物流编号',  `pay_channel` varchar(50) DEFAULT NULL COMMENT '订单支付渠道',  `escrow_trade_no` varchar(50) DEFAULT NULL COMMENT '订单支付单号',  `create_time` datetime DEFAULT NULL COMMENT '创建时间/下单时间',  `pay_time` datetime DEFAULT NULL COMMENT '付款时间',  `deliver_time` datetime DEFAULT NULL COMMENT '发货时间',  `settlement_status` varchar(20) DEFAULT NULL COMMENT '货到付款、分期付款会使用',  `settlement_time` datetime DEFAULT NULL COMMENT '订单结算时间',  PRIMARY KEY (`order_id`),  KEY `user_id` (`user_id`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
--

insert data:
INSERT INTO `t_order` (
	`order_id`,
	`user_id`,
	`shop_id`,
	`product_count`,
	`product_amount_total`,
	`order_amount_total`,
	`logistics_fee`,
	`is_unpacking_inspection`,
	`is_invoice`,
	`invoice_no`,
	`address_id`,
	`logistics_id`,
	`pay_channel`,
	`escrow_trade_no`,
	`create_time`,
	`pay_time`,
	`deliver_time`,
	`settlement_status`,
	`settlement_time`
)
VALUES
	(
		'1',
		'1',
		'1',
		'1',
		'1',
		'1',
		'1',
		NULL,
		'1',
		'xxx',
		'1',
		'1',
		'微信支付',
		'xxxx',
		'2020-07-31 00:56:41',
		'2020-07-31 00:56:44',
		'2020-07-31 00:56:46',
		NULL,
		NULL
	);

the error message: 

[Err] 10002 - 2Unknown exception: [No signature of method: java.lang.String.mod() is applicable for argument types: (java.lang.Integer) values: [2]
Possible solutions: drop(int), find(), any(), find(java.lang.CharSequence), find(groovy.lang.Closure), use([Ljava.lang.Object;)]

the setting file is:
[sharding-proxy.zip](https://github.com/apache/shardingsphere/files/5002715/sharding-proxy.zip)

conclusion:
Creating table is ok, but inserting data is **TOO BAD**。

**Comment by tristaZero** [comment]
Hi @cay914 Thanks for your feedback.

Which version do you use?
Could you provide a more detailed stack log?

**Comment by caiglee** [comment]
[ERROR] 11:09:41.556 [ShardingSphere-Command-3] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
groovy.lang.MissingMethodException: No signature of method: java.lang.String.mod() is applicable for argument types: (java.lang.Integer) values: [2]
Possible solutions: drop(int), find(), any(), find(java.lang.CharSequence), use([Ljava.lang.Object;), take(int)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
        at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at Script5$_run_closure1.doCall(Script5.groovy:1)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
        at groovy.lang.Closure.call(Closure.java:426)
        at groovy.lang.Closure.call(Closure.java:420)
        at org.apache.shardingsphere.core.strategy.route.inline.InlineShardingStrategy.execute(InlineShardingStrategy.java:94)
        at org.apache.shardingsphere.core.strategy.route.inline.InlineShardingStrategy.doSharding(InlineShardingStrategy.java:76)
        at org.apache.shardingsphere.core.strategy.route.inline.InlineShardingStrategy.doSharding(InlineShardingStrategy.java:63)
        at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.routeDataSources(ShardingStandardRoutingEngine.java:204)
        at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.route0(ShardingStandardRoutingEngine.java:192)
        at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.routeByShardingConditionsWithCondition(ShardingStandardRoutingEngine.java:121)
        at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.routeByShardingConditions(ShardingStandardRoutingEngine.java:115)
        at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.getDataNodes(ShardingStandardRoutingEngine.java:96)
        at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.route(ShardingStandardRoutingEngine.java:74)
        at org.apache.shardingsphere.sharding.route.engine.ShardingRouteDecorator.decorate(ShardingRouteDecorator.java:69)
        at org.apache.shardingsphere.sharding.route.engine.ShardingRouteDecorator.decorate(ShardingRouteDecorator.java:53)
        at org.apache.shardingsphere.underlying.route.DataNodeRouter.executeRoute(DataNodeRouter.java:91)
        at org.apache.shardingsphere.underlying.route.DataNodeRouter.route(DataNodeRouter.java:76)
        at org.apache.shardingsphere.underlying.pluggble.prepare.SimpleQueryPrepareEngine.route(SimpleQueryPrepareEngine.java:54)
        at org.apache.shardingsphere.underlying.pluggble.prepare.BasePrepareEngine.executeRoute(BasePrepareEngine.java:96)
        at org.apache.shardingsphere.underlying.pluggble.prepare.BasePrepareEngine.prepare(BasePrepareEngine.java:83)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.wrapper.StatementExecutorWrapper.doShardingRoute(StatementExecutorWrapper.java:80)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.wrapper.StatementExecutorWrapper.route(StatementExecutorWrapper.java:63)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:74)
        at org.apache.shardingsphere.shardingproxy.backend.text.query.QueryBackendHandler.execute(QueryBackendHandler.java:52)
        at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:78)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:93)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by caiglee** [comment]
[SQL] insert into t_order values(2,1,1);
受影响的行: 1
时间: 0.031s

[Err] 1055 - Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'information_schema.PROFILING.SEQ' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by cay914** [comment]
Hello, my navicat version:
![image](https://user-images.githubusercontent.com/6037435/89002275-3d160b80-d32f-11ea-8519-4f907a7894b7.png)

sharding-proxy version:
4.1.1

And I have encounted another problem when i refresh 3 （or more) time with navicat.
some time good, some time wrong. you can see the picture.
![image](https://user-images.githubusercontent.com/6037435/89002419-99792b00-d32f-11ea-83fa-64ce0a3de8b9.png)

**Comment by tristaZero** [comment]
@caiglee @cay914 Thanks for detailed information.
Firstly @caiglee Which SQL did you execute to get the exception? Also, the related `sharding rule` is required, since I found this exception was caused by `InlineShardingStrategy`.
> at org.apache.shardingsphere.core.strategy.route.inline.InlineShardingStrategy.execute(InlineShardingStrategy.java:94)

**Comment by tristaZero** [comment]
For @cay914 's image, It seems another issue, right?

@tuohai666 Do you think this user needs to provide more detail for us to look into?

**Comment by cay914** [comment]
The same environment, simply refresh from navicat.

**Comment by tuohai666** [comment]
@cay914 

> And I have encounted another problem when i refresh 3 （or more) time with navicat.
> some time good, some time wrong. you can see the picture.

The picture already told the reason **order1.t_order_0 doesn't exist.**

All actual tables in your rule as follows:
`actualDataNodes: order0.t_order_$->{[0,2,4,6]}, order1.t_order_$->{[1,3,5,7]}`

**Comment by tuohai666** [comment]
For the previous Exception, please change the sharding value user_id from '1' to 1 .

**Comment by cay914** [comment]
I have try remove bindingTables. But it take no effect.
**order1.t_order_0 doesn't exist** problem is the same.

my test data is flow, can you have a    @tuohai666 
[order.zip](https://github.com/apache/shardingsphere/files/5010263/order.zip)

**Comment by tuohai666** [comment]
@cay914 Set sql.show: true and upload the log for this problem. Let's find out what's the SQL need routing to order1.t_order_0.

**Comment by tuohai666** [comment]
![image](https://user-images.githubusercontent.com/24643893/89140681-e437b480-d574-11ea-9e57-da8151501fab.png)

You should use actual SQL via a ShardingSphere-Proxy, change the actual SQL to logical SQL please.

**Comment by cay914** [comment]
I create the table use sharding-proxy and it divide 2 db and 4 table each. I just give you the actual data. You know?
The actual Table DLL is:
CREATE TABLE `t_order` (
  `order_id` int(20) NOT NULL COMMENT '自动编号',
  `user_id` bigint(20) NOT NULL COMMENT '客户编号',
  `shop_id` bigint(20) NOT NULL COMMENT '商店编号',
  `product_count` int(11) NOT NULL COMMENT '商品数量',
  `product_amount_total` decimal(5,2) NOT NULL COMMENT '商品总价',
  `order_amount_total` decimal(5,2) NOT NULL COMMENT '订单金额',
  `logistics_fee` decimal(5,2) DEFAULT NULL COMMENT '运费金额',
  `is_unpacking_inspection` tinyint(1) DEFAULT NULL COMMENT '是否开箱验货',
  `is_invoice` tinyint(1) DEFAULT NULL COMMENT '是否开具发票',
  `invoice_no` varchar(50) DEFAULT NULL COMMENT '发票编号',
  `address_id` bigint(20) DEFAULT NULL COMMENT '收货地址编号',
  `logistics_id` bigint(20) DEFAULT NULL COMMENT '订单物流编号',
  `pay_channel` varchar(50) DEFAULT NULL COMMENT '订单支付渠道',
  `escrow_trade_no` varchar(50) DEFAULT NULL COMMENT '订单支付单号',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间/下单时间',
  `pay_time` datetime DEFAULT NULL COMMENT '付款时间',
  `deliver_time` datetime DEFAULT NULL COMMENT '发货时间',
  `settlement_status` varchar(20) DEFAULT NULL COMMENT '货到付款、分期付款会使用',
  `settlement_time` datetime DEFAULT NULL COMMENT '订单结算时间',
  PRIMARY KEY (`order_id`),
  KEY `user_id` (`user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

**Comment by tuohai666** [comment]
Again.
Set sql.show: true and upload the log for this problem. Let's find out what's the SQL need routing to order1.t_order_0.

I can't try to reproduce for I don't have an available Navicat. So, please provide the log.

**Comment by cay914** [comment]
stacktrace :(((((

org.springframework.dao.InvalidDataAccessResourceUsageException: could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:280)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:254)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:528)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:153)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:144)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$ExposeRepositoryInvocationInterceptor.invoke(CrudMethodMetadataPostProcessor.java:364)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy140.save(Unknown Source)
	at com.codebattery.service.OrderService.create(OrderService.java:29)
	at com.codebattery.service.OrderService$$FastClassBySpringCGLIB$$49ca46bb.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:750)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor$1.execute(GlobalTransactionalInterceptor.java:150)
	at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:104)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:147)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:122)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$$Lambda$1080/2141522478.call(Unknown Source)
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:276)
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport$$Lambda$1081/340464612.get(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1582)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:63)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:69)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2265)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2028)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1990)
	at org.hibernate.loader.Loader.doQuery(Loader.java:949)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:351)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:321)
	at org.hibernate.loader.Loader.loadEntity(Loader.java:2379)
	at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:64)
	at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:54)
	at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:4289)
	at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:597)
	at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:565)
	at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:226)
	at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:350)
	at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:127)
	at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:93)
	at org.hibernate.internal.SessionImpl.fireLoadNoChecks(SessionImpl.java:1288)
	at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1276)
	at org.hibernate.internal.SessionImpl.access$2000(SessionImpl.java:208)
	at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.doLoad(SessionImpl.java:2912)
	at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.load(SessionImpl.java:2886)
	at org.hibernate.internal.SessionImpl.get(SessionImpl.java:1102)
	at org.hibernate.event.internal.DefaultMergeEventListener.entityIsDetached(DefaultMergeEventListener.java:322)
	at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:188)
	at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:72)
	at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:905)
	at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:891)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:310)
	at com.sun.proxy.$Proxy138.merge(Unknown Source)
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.save(SimpleJpaRepository.java:538)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:359)
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:200)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:644)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:608)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$invoke$3(RepositoryFactorySupport.java:595)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor$$Lambda$1099/668229115.get(Unknown Source)
	at org.springframework.data.repository.util.QueryExecutionConverters$$Lambda$1098/738441650.apply(Unknown Source)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:595)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.transaction.interceptor.TransactionInterceptor$$Lambda$1097/104749982.proceedWithInvocation(Unknown Source)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:295)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	... 30 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'order0.t_order_1' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2011)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
	at io.seata.rm.datasource.PreparedStatementProxy.lambda$executeQuery$1(PreparedStatementProxy.java:60)
	at io.seata.rm.datasource.PreparedStatementProxy$$Lambda$1128/1935821459.execute(Unknown Source)
	at io.seata.rm.datasource.exec.PlainExecutor.execute(PlainExecutor.java:49)
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:113)
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:51)
	at io.seata.rm.datasource.PreparedStatementProxy.executeQuery(PreparedStatementProxy.java:60)
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.getQueryResult(PreparedStatementExecutor.java:109)
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.access$200(PreparedStatementExecutor.java:45)
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor$2.executeSQL(PreparedStatementExecutor.java:101)
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor$2.executeSQL(PreparedStatementExecutor.java:97)
	at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteCallback.execute0(SQLExecuteCallback.java:82)
	at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteCallback.execute(SQLExecuteCallback.java:58)
	at org.apache.shardingsphere.underlying.executor.engine.ExecutorEngine.syncExecute(ExecutorEngine.java:97)
	at org.apache.shardingsphere.underlying.executor.engine.ExecutorEngine.serialExecute(ExecutorEngine.java:84)
	at org.apache.shardingsphere.underlying.executor.engine.ExecutorEngine.execute(ExecutorEngine.java:76)
	at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteTemplate.execute(SQLExecuteTemplate.java:68)
	at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteTemplate.execute(SQLExecuteTemplate.java:51)
	at org.apache.shardingsphere.shardingjdbc.executor.AbstractStatementExecutor.executeCallback(AbstractStatementExecutor.java:129)
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.executeQuery(PreparedStatementExecutor.java:104)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.executeQuery(ShardingPreparedStatement.java:118)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:60)
	... 85 more

**Comment by tuohai666** [comment]
You response is meaningless. And you ignored my response completely over and over. 
I suggest close this issue and tag invalid.
If somebody else like to continue this issue, please reopen and assign to whose-self.

**Comment by cay914** [comment]
我错了哥，给次机会。
