### ISSUE TITLE
information_schema and sys relevant SQLs can't parse or route

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#6693]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Get the result from the following SQLs:

```
show full processlist;
select * from information_schema.processlist ;
select * from information_schema.INNODB_TRX;
select * from sys.schema_redundant_indexes;
```

### Actual behavior

```
mysql> show full processlist;
Query OK, 0 rows affected (0.06 sec)
```

```
Exception in log: 
line 1:10 no viable alternative at input 'showfullprocesslist'
```

```
mysql> select * from information_schema.processlist;
ERROR 10002 (C1000): 2Unknown exception: [Can not route tables for `[processlist]`, please make sure the tables are in same schema.]
```

```
Exception in log:
[ERROR] 18:09:12.379 [ShardingSphere-Command-5] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
org.apache.shardingsphere.infra.exception.ShardingSphereException: Can not route tables for `[processlist]`, please make sure the tables are in same schema.
	at org.apache.shardingsphere.sharding.route.engine.type.unconfigured.ShardingUnconfiguredTablesRoutingEngine.route(ShardingUnconfiguredTablesRoutingEngine.java:50)
	at org.apache.shardingsphere.sharding.route.engine.ShardingRouteDecorator.decorate(ShardingRouteDecorator.java:72)
	at org.apache.shardingsphere.sharding.route.engine.ShardingRouteDecorator.decorate(ShardingRouteDecorator.java:55)
	at org.apache.shardingsphere.infra.route.DataNodeRouter.executeRoute(DataNodeRouter.java:89)
	at org.apache.shardingsphere.infra.route.DataNodeRouter.route(DataNodeRouter.java:74)
	at org.apache.shardingsphere.proxy.backend.communication.jdbc.wrapper.StatementExecutorWrapper.execute(StatementExecutorWrapper.java:67)
	at org.apache.shardingsphere.proxy.backend.communication.jdbc.execute.engine.jdbc.JDBCExecuteEngine.execute(JDBCExecuteEngine.java:80)
	at org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:85)
	at org.apache.shardingsphere.proxy.backend.text.query.QueryBackendHandler.execute(QueryBackendHandler.java:55)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:78)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:105)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```
### Reason analyze (If you can)

```
Parse error:
show full processlist;
```

```
Route error:
select * from information_schema.processlist;
```

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

Execute these SQLs straightforwardly.

**Comment by sandynz** [comment]
Hibernate 5.4 + ShardingSphere JDBC 5.0.0-RC1-SNAPSHOT + MySQL 5.7, has similar exception: `ShardingSphereException: Can not route tables for `[sequences]`, please make sure the tables are in same schema`.

Hibernate settings:
- hibernate.hbm2ddl.auto = update

SQL executed by hibernate automatically: `select * from information_schema.sequences`

**Comment by tuohai666** [comment]
The exception caused by parse and route procedure. @tristaZero , can you have a look?

**Comment by kimmking** [comment]
any update?

**Comment by mark4z** [comment]
Mysql has same problem here.

**Comment by tristaZero** [comment]
Hi thanks for your attention.
It is an important but challenging feature definitely. We need to make a schedule to support it step by step. Once there is any plan, I will update it here.

**Comment by linchers** [comment]
org.apache.shardingsphere.sharding.route.engine.type.unconfigured.ShardingUnconfiguredTablesRoutingEngine#findDataSourceName
 `    private Optional<String> findDataSourceName() {
        for (Entry<String, Collection<String>> entry : unconfiguredSchemaMetaDataMap.entrySet()) {
            if (entry.getValue().containsAll(logicTables)) {
                return Optional.of(entry.getKey());
            }
        }
        return Optional.empty();
    }`

entry.getValue() tablenames is  upcase  but logicTables is  lowercase

**Comment by leeey111** [comment]
Any news? 
Without this feature support,it is inconvenienced to use "SQL complement" in some SQL clients like DBeaver.

**Comment by lcxywfe** [comment]
Any news? phpmyadmin also need information_schema.

**Comment by terrymanu** [comment]
Close because of staled.
