### ISSUE TITLE
Cannot load JDBC driver class `com.mysql.jdbc.Driver`, make sure it in Sharding-Proxy's classpath

### ISSUE THREAD

**Issue by qiaojiang2** [apache/shardingsphere#6764]
## Bug Report

Exception in thread "main" org.apache.shardingsphere.underlying.common.exception.ShardingSphereException: Can not build data source, name is `ds_0`.
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.createDataSources(JDBCBackendDataSource.java:74)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.<init>(JDBCBackendDataSource.java:62)
	at org.apache.shardingsphere.shardingproxy.backend.schema.LogicSchema.<init>(LogicSchema.java:54)
	at org.apache.shardingsphere.shardingproxy.backend.schema.impl.ShardingSchema.<init>(ShardingSchema.java:77)
	at org.apache.shardingsphere.shardingproxy.backend.schema.LogicSchemaFactory.newInstance(LogicSchemaFactory.java:56)
	at org.apache.shardingsphere.shardingproxy.backend.schema.LogicSchemas.initSchemas(LogicSchemas.java:102)
	at org.apache.shardingsphere.shardingproxy.backend.schema.LogicSchemas.init(LogicSchemas.java:91)
	at org.apache.shardingsphere.shardingproxy.backend.schema.LogicSchemas.init(LogicSchemas.java:75)
	at org.apache.shardingsphere.shardingproxy.Bootstrap.startWithoutRegistryCenter(Bootstrap.java:123)
	at org.apache.shardingsphere.shardingproxy.Bootstrap.main(Bootstrap.java:85)
Caused by: org.apache.shardingsphere.underlying.common.exception.ShardingSphereException: Cannot load JDBC driver class `com.mysql.jdbc.Driver`, make sure it in Sharding-Proxy's classpath.
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCRawBackendDataSourceFactory.validateDriverClassName(JDBCRawBackendDataSourceFactory.java:81)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCRawBackendDataSourceFactory.build(JDBCRawBackendDataSourceFactory.java:51)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.createDataSources(JDBCBackendDataSource.java:70)

**Comment by terrymanu** [comment]
Just make sure `com.mysql.jdbc.Driver` in Sharding-Proxy's classpath

**Comment by Lucas-307** [comment]
`com.mysql.jdbc.Driver` is in `mysql-connector-java-xxx.jar` you should download and put into your classpath.

**Comment by qiaojiang2** [comment]
"If the backend database is PostgreSQL, there’s no need for additional dependencies.

If the backend database is MySQL, download MySQL Connector/J and decompress, then copy mysql-connector-java-5.1.47.jar to %SHARDINGSPHERE_PROXY_HOME%/lib directory."

Why not support Mysql directly？
