### ISSUE TITLE
### Error updating database.  Cause: java.lang.NullPointerException

### ISSUE THREAD

**Issue by jameszhongsq** [apache/shardingsphere#6775]
<dependency>
      <groupId>org.apache.shardingsphere</groupId>
      <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
      <version>4.1.1</version>
    </dependency>

When I test insert， I get the following error:

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.NullPointerException

	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:278)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:58)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at cn.tsign.sealmanager.service.optlog.OptlogServiceTest.test01(OptlogServiceTest.java:31)
	at 

the sql :  insert into msg_produce_log (id,topic, group, tag, msg_id, msg_body, send_result) values (?,?, ?, ?, ?, ?, ? )。
the key，value can match it。

**Comment by tristaZero** [comment]
@jameszhongsq Hi, Firstly, please search our issue list with your keyword since there some similar issues solved.
Secondly, please give more stack log, it is not enough to find the reason.
