### ISSUE TITLE
java.lang.RuntimeException: markPosition error

### ISSUE THREAD

**Issue by qiaojiang2** [apache/shardingsphere#6777]
## Bug Report

#Create migration job:
curl -X POST --url http://localhost:8888/shardingscaling/job/start \
--header 'content-type: application/json' \
--data '{
	"ruleConfiguration": {
		"sourceDatasource": "ds_0: !!org.apache.shardingsphere.orchestration.core.configuration.YamlDataSourceConfiguration\n  dataSourceClassName: com.zaxxer.hikari.HikariDataSource\n  properties:\n    jdbcUrl: jdbc:mysql://127.0.0.1:3306/order?serverTimezone=UTC&useSSL=false&zeroDateTimeBehavior=convertToNull\n    driverClassName: com.mysql.jdbc.Driver\n    username: root\n    password: 123456\n    connectionTimeout: 30000\n    idleTimeout: 60000\n    maxLifetime: 1800000\n    maxPoolSize: 100\n    minPoolSize: 10\n    maintenanceIntervalMilliseconds: 30000\n    readOnly: false\n",
		"sourceRule": "tables:\n  t_order:\n    actualDataNodes: ds_0.t_order\n    keyGenerator:\n      column: order_id\n      type: SNOWFLAKE",
		"destinationDataSources": {
			"name": "dt_1",
			"password": "123456",
			"url": "jdbc:mysql://127.0.0.1:3307/order?serverTimezone=UTC&useSSL=false",
			"username": "root"
		}
	},
	"jobConfiguration": {
		"concurrency": 1
	}
}'

“Exception in thread "Thread-5" java.lang.RuntimeException: markPosition error
	at org.apache.shardingsphere.shardingscaling.mysql.MySQLLogPositionManager.getCurrentPositionFromSource(MySQLLogPositionManager.java:58)
	at org.apache.shardingsphere.shardingscaling.mysql.MySQLLogPositionManager.getCurrentPosition(MySQLLogPositionManager.java:42)
	at org.apache.shardingsphere.shardingscaling.mysql.MySQLLogPositionManager.getCurrentPosition(MySQLLogPositionManager.java:32)
	at org.apache.shardingsphere.shardingscaling.core.synctask.realtime.RealtimeDataSyncTask.prepare(RealtimeDataSyncTask.java:70)
	at org.apache.shardingsphere.shardingscaling.core.controller.task.SyncTaskController.run(SyncTaskController.java:93)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Illegal operation on empty result set.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.checkRowPos(ResultSetImpl.java:790)
	at com.mysql.jdbc.ResultSetImpl.getStringInternal(ResultSetImpl.java:5213)
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5136)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getString(HikariProxyResultSet.java)
	at org.apache.shardingsphere.shardingscaling.mysql.MySQLLogPositionManager.getCurrentPositionFromSource(MySQLLogPositionManager.java:52)
	... 5 more”

**Comment by tristaZero** [comment]
Hi @qiaojiang2 thanks for your issue. I presume @Lucas-307 can give it a look.

**Comment by Lucas-307** [comment]
Hi, @qiaojiang2:
First, I suggest you update your code that is not up-to-date.
And, from you stack log. I guess it's because mysql user do not have enought right or mysql version is unexpected.

you can check it.

use current mysql user execute this sql, see what result return.

```sql
SHOW MASTER STATUS;
SHOW VARIABLES LIKE 'server_id';
SHOW VARIABLES LIKE 'version';
```

**Comment by qiaojiang2** [comment]
Thanks for your reply. I installed mysql through Docker and did not turn on binlog！In addition, taking this opportunity, I would like to ask what is the maximum data size and test time of the current scaling+ Proxy data migration scheme? If it is an online system, if the data migration is not completed, if the data sharding rules are changed, the service will be unavailable! Any better advice in practice?

**Comment by Lucas-307** [comment]
There are some rules in scaling execute. 
We can't change sharding rules during do scaling. If you do it, we should clear completed data(currently should do it by yourself, we will enhance it in the future), and rescaling.
About data size and time, 3*10^10 data cost 2 weeks for reference only.(it's deeply depends on you environment.)

**Comment by kimmking** [comment]
@qiaojiang2  
 >  If it is an online system, if the data migration is not completed, if the data sharding rules are changed, the service will be unavailable! 

You are right. migration is a big issue and lock all rule-changes, util migratition is finished.
