### ISSUE TITLE
scaling can't create sync job in latest master branch

### ISSUE THREAD

**Issue by dmbj** [apache/shardingsphere#6833]
### Which version of ShardingSphere did you use?
master 5.0.0-RC1-SNAPSHOT commitId:613e4a8ab3e7b2ebd378503996f222f8c913f367
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
scaling&proxy
### Expected behavior
create sync job and sync data
### Actual behavior
can't create sync job and list job occur exception
```
[WARN ] 14:15:52.473 [nioEventLoopGroup-3-2] o.a.s.scaling.web.HttpServerHandler - Http request handle occur error:
java.lang.NoSuchMethodError: io.netty.buffer.ByteBuf.isContiguous()Z
	at io.netty.handler.codec.ByteToMessageDecoder$1.cumulate(ByteToMessageDecoder.java:83)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:274)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
### Reason analyze (If you can)
scaling dependency io.netty.jar may conflict trigger NoSuchMethodError error?
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1.start proxy,scaling well,zk3.6.1
2.start a scaling job request,got an exception,then request list job same error
### Example codes for reproduce this issue (such as a github link).
POST `http://192.168.100.217:8888/scaling/job/start`，request body:
```
{
   "ruleConfiguration": {
      "sourceDatasource": "ds_0: !!org.apache.shardingsphere.orchestration.core.common.yaml.config.YamlDataSourceConfiguration\n  dataSourceClassName: com.zaxxer.hikari.HikariDataSource\n  props:\n    jdbcUrl: jdbc:mysql://192.168.100.218:3306/appbiz_data_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true\n    username: ybbuser\n    password: 'ybbuser123!@#'\n    connectionTimeout: 30000\n    idleTimeout: 60000\n    maxLifetime: 1800000\n    maxPoolSize: 200\n    minPoolSize: 10\n    maintenanceIntervalMilliseconds: 30000\n    readOnly: false\n",
      "sourceRule": "tables:\n  t_qrcode_consume_details:\n    actualDataNodes: ds_0.t_qrcode_consume_details\n",
      "destinationDataSources": {
         "name": "dt_0",
         "password": "sharding",
         "url": "jdbc:mysql://192.168.100.217:3307/sharding_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false",
         "username": "sharding"
      }
   },
   "jobConfiguration": {
      "concurrency": 10
   }
}
```
http response:
`{"success":false,"errorCode":500,"errorMsg":"java.lang.NoSuchMethodError: io.netty.buffer.ByteBuf.isContiguous()Z","model":null}`
scaling server log error

**Comment by Lucas-307** [comment]
let me check.

**Comment by Lucas-307** [comment]
Hi, @dmbj what's your io.netty.jar version?  4.1.42.Final or others?

**Comment by dmbj** [comment]
@Lucas-307 io.netty.jar version in scaling lib:netty-all-4.1.42.Final.jar
pom.xml in master branch:
```
        <groovy.version>2.4.19</groovy.version>
        <snakeyaml.version>1.16</snakeyaml.version>

        <netty.version>4.1.42.Final</netty.version>
        <commons-codec.version>1.10</commons-codec.version>
        <commons-cli.version>1.4</commons-cli.version>
        <commons-collections4.version>4.2</commons-collections4.version>
```

**Comment by Lucas-307** [comment]
@dmbj NoSuchMethodError usually cause by wrong jar version. Could you please check it, or debug it if you can.

**Comment by dmbj** [comment]
> @dmbj NoSuchMethodError usually cause by wrong jar version. Could you please check it, or debug it if you can.

because git clone too slow,I direct replace scaling lib `netty-all-4.1.42.Final.jar`->`netty-all-4.1.45.Final.jar` 
it's work now,however i didn't get exact reason ，i suggest you could recheck maven dependency, hope it's helpful.

then i got an another MYSQL connection exception.
Gosh ,would you give some configuration guidance for me in this temp version? tks a lots~
```
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 1 milliseconds ago.  The last packet sent successfully to the server was 1 milliseconds ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3462)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3905)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2199)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2230)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2025)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:354)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:554)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at org.apache.shardingsphere.scaling.core.job.preparer.checker.AbstractDataSourceChecker.checkConnection(AbstractDataSourceChecker.java:35)
	... 34 common frames omitted
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3014)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3472)
	... 59 common frames omitted
```

**Comment by dmbj** [comment]
so proxy has same problem,need fix netty conflict jar problem

**Comment by Lucas-307** [comment]
Sorry , i still can't reproduce this problem

**Comment by kimmking** [comment]
Hi @dmbj  you should fix netty issue and try a go.
If there is anything wrong, plz open a new issue.
