### ISSUE TITLE
ss-proxy failed to handle tables which have minor difference in table name when retrieving table metadata.

### ISSUE THREAD

**Issue by zhaopinglu** [apache/shardingsphere#6890]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
ss-proxy-5.0.0.RC1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ss-proxy-5.0.0.RC1

### Expected behavior
ss-proxy start up successfully

### Actual behavior
ss-proxy failed to start up. Process quit with the following error:

[INFO ] 16:09:12.287 [main] c.a.d.xa.XATransactionalResource - resource-1-master_ds: refreshed XAResource
[INFO ] 16:09:12.296 [main] c.a.d.xa.XATransactionalResource - resource-2-slave_ds_0: refreshed XAResource
[INFO ] 16:09:12.307 [main] c.a.d.xa.XATransactionalResource - resource-3-slave_ds_1: refreshed XAResource
[INFO ] 16:09:12.373 [ShardingSphere-0] ShardingSphere-metadata - Loading 2 tables' meta data.
Exception in thread "main" org.apache.shardingsphere.infra.exception.ShardingSphereException: RuleSchemaMetaData load failed
        at org.apache.shardingsphere.infra.metadata.schema.RuleSchemaMetaDataLoader.lambda$asyncLoad$2(RuleSchemaMetaDataLoader.java:164)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
        at org.apache.shardingsphere.infra.metadata.schema.RuleSchemaMetaDataLoader.asyncLoad(RuleSchemaMetaDataLoader.java:160)
        at org.apache.shardingsphere.infra.metadata.schema.RuleSchemaMetaDataLoader.load(RuleSchemaMetaDataLoader.java:88)
        at org.apache.shardingsphere.kernel.context.SchemaContextsBuilder.createMetaData(SchemaContextsBuilder.java:130)
        at org.apache.shardingsphere.kernel.context.SchemaContextsBuilder.createShardingSphereSchema(SchemaContextsBuilder.java:124)
        at org.apache.shardingsphere.kernel.context.SchemaContextsBuilder.createSchemaContext(SchemaContextsBuilder.java:102)
        at org.apache.shardingsphere.kernel.context.SchemaContextsBuilder.build(SchemaContextsBuilder.java:93)
        at org.apache.shardingsphere.proxy.Bootstrap.initSchemaContexts(Bootstrap.java:86)
        at org.apache.shardingsphere.proxy.Bootstrap.init(Bootstrap.java:76)
        at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:67)
Caused by: java.util.concurrent.ExecutionException: org.apache.shardingsphere.infra.exception.ShardingSphereException: RuleSchemaMetaData load failed
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:564)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:545)
        at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:88)
        at org.apache.shardingsphere.infra.metadata.schema.RuleSchemaMetaDataLoader.lambda$asyncLoad$2(RuleSchemaMetaDataLoader.java:162)
        ... 19 more
Caused by: org.apache.shardingsphere.infra.exception.ShardingSphereException: RuleSchemaMetaData load failed
        at org.apache.shardingsphere.infra.metadata.schema.RuleSchemaMetaDataLoader.lambda$null$0(RuleSchemaMetaDataLoader.java:158)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Column 'ID' not found.
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
        at com.mysql.cj.jdbc.result.ResultSetImpl.findColumn(ResultSetImpl.java:556)
        at com.zaxxer.hikari.pool.HikariProxyResultSet.findColumn(HikariProxyResultSet.java)
        at org.apache.shardingsphere.sql.parser.binder.metadata.column.ColumnMetaDataLoader.load(ColumnMetaDataLoader.java:73)
        at org.apache.shardingsphere.sql.parser.binder.metadata.schema.SchemaMetaDataLoader.load(SchemaMetaDataLoader.java:100)
        at org.apache.shardingsphere.sql.parser.binder.metadata.schema.SchemaMetaDataLoader.load(SchemaMetaDataLoader.java:92)
        at org.apache.shardingsphere.infra.metadata.schema.RuleSchemaMetaDataLoader.lambda$null$0(RuleSchemaMetaDataLoader.java:153)
        ... 7 more

### Reason analyze (If you can)
ss-proxy failed to handle tables which have minor difference in table name when retrieving table metadata.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. Create 2 tables as below:

drop table if exists TEST_01;
CREATE TABLE `TEST_01` (
  `ID` varchar(32) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

drop table if exists TEST__1;
CREATE TABLE `TEST__1` (
  `ID1` varchar(32) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

2. Start up ss-proxy, the error will be triggered.
### Example codes for reproduce this issue (such as a github link).

My Configuration files:

### server.yaml:

props:
  max.connections.size.per.query: 1
  acceptor.size: 16  # The default value is available processors count * 2.
  executor.size: 16  # Infinite by default.
  proxy.frontend.flush.threshold: 128  # The default value is 128.
    # LOCAL: Proxy will run with LOCAL transaction.
    # XA: Proxy will run with XA transaction.
    # BASE: Proxy will run with B.A.S.E transaction.
  proxy.transaction.type: LOCAL
  proxy.opentracing.enabled: false
  proxy.cluster.enabled: false
  proxy.hint.enabled: false
  query.with.cipher.column: true
  sql.show: true
  allow.range.query.with.inline.sharding: false
  check.table.metadata.enabled: false

### config-master_slave.yaml

schemaName: test
dataSources:
  master_ds:
    url: jdbc:mysql://hhh1:3306/test?serverTimezone=UTC&useSSL=false
    username: root
    password: xxx
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  slave_ds_0:
    url: jdbc:mysql://hhh2:3306/test?serverTimezone=UTC&useSSL=false
    username: root
    password: xxx
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  slave_ds_1:
    url: jdbc:mysql://hhh3:3306/test?serverTimezone=UTC&useSSL=false
    username: root
    password: xxx
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50

rules:
- !MASTER_SLAVE
  dataSources:
    ms_ds:
      name: ms_ds
      masterDataSourceName: master_ds
      slaveDataSourceNames:
        - slave_ds_0
        - slave_ds_1

**Comment by tristaZero** [comment]
Hi @zhaopinglu 
Are both `TEST_01` and `TEST__1 `  actual tables for a `logic table`? If so, `TEST_01` and `TEST__1 ` are supposed to have the same table structure, aren't they?

**Comment by zhaopinglu** [comment]
TEST_01 and TEST__1 are 2 actual tables. They  don't have any relationship. I guess when matching table name, ss-proxy forgot to escape the "_" char which actually match any single char.

**Comment by tristaZero** [comment]
Hi @zhaopinglu Do you think it is possible to give it a deep debugging? Since we do not have the same test scenario with you, it is inefficient to look into this issue.
If you have any progress, welcome to share them here. Therefore we can locate the problem soon. :-)

Best,
Trista

**Comment by zhaopinglu** [comment]
It's very easy to replicate this issue. Just create 2 tables then start up ss-proxy, you will see the error in log right away.

1. Create 2 tables as below:
drop table if exists TEST_01;
CREATE TABLE TEST_01 (
ID varchar(32) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

drop table if exists TEST__1;
CREATE TABLE TEST__1 (
ID1 varchar(32) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

2. Start up ss-proxy, the error will be triggered.

Please let me know if you need any more information. Thanks.

**Comment by tristaZero** [comment]
@wcsoft Could you give it a look using the master branch?

**Comment by kimmking** [comment]
Can you show your config rule>?

**Comment by tristaZero** [comment]
@wcsoft Ping for a test. Thanks

**Comment by wcsoft** [comment]
@zhaopinglu 

Do you use logical table named "TEST**" within config of proxy? could you provide your yaml, thx a lot?

**Comment by zhaopinglu** [comment]
Thanks for response. I didn't do any special configuration for those test* tables. As I said they are 2 standalone tables without any relationship.

**Comment by wcsoft** [comment]
@zhaopinglu 
could you provide me your yaml files for ShardingProxy? Thx a lot.

**Comment by zhaopinglu** [comment]
Please see the yaml files in the 1st post.

**Comment by kimmking** [comment]
It has been fixed in master branch.
