### ISSUE TITLE
PostgreSQL dedicated column missed in t_order cause GeneralDQLIT.assertExecuteQuery failed

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#7010]
### Which version of ShardingSphere did you use?
master branch, 5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
Related dql-test-case pass.

### Actual behavior
Test failed, exception thrown:
```
org.postgresql.util.PSQLException: ERROR: column "rule" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:224)
	at com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:111)
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java)
	at org.apache.shardingsphere.driver.executor.StatementExecutor$1.createQueryResult(StatementExecutor.java:81)
	at org.apache.shardingsphere.driver.executor.StatementExecutor$1.executeSQL(StatementExecutor.java:77)
	at org.apache.shardingsphere.driver.executor.StatementExecutor$1.executeSQL(StatementExecutor.java:73)
	at org.apache.shardingsphere.infra.executor.sql.resourced.jdbc.executor.impl.DefaultSQLExecutorCallback.execute0(DefaultSQLExecutorCallback.java:75)
	at org.apache.shardingsphere.infra.executor.sql.resourced.jdbc.executor.impl.DefaultSQLExecutorCallback.execute(DefaultSQLExecutorCallback.java:57)
	at org.apache.shardingsphere.infra.executor.kernel.ExecutorKernel.syncExecute(ExecutorKernel.java:99)
	at org.apache.shardingsphere.infra.executor.kernel.ExecutorKernel.parallelExecute(ExecutorKernel.java:95)
	at org.apache.shardingsphere.infra.executor.kernel.ExecutorKernel.execute(ExecutorKernel.java:78)
	at org.apache.shardingsphere.infra.executor.sql.resourced.jdbc.executor.SQLExecutor.execute(SQLExecutor.java:66)
	at org.apache.shardingsphere.infra.executor.sql.resourced.jdbc.executor.SQLExecutor.execute(SQLExecutor.java:50)
	at org.apache.shardingsphere.driver.executor.StatementExecutor.executeQuery(StatementExecutor.java:85)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.executeQuery(ShardingSphereStatement.java:127)
	at org.apache.shardingsphere.dbtest.engine.dql.GeneralDQLIT.assertExecuteQueryForStatement(GeneralDQLIT.java:70)
	at org.apache.shardingsphere.dbtest.engine.dql.GeneralDQLIT.assertExecuteQuery(GeneralDQLIT.java:60)
```

### Reason analyze (If you can)
`rule` and `start_point` columns doesn't exist in `t_order` table.
Since they're special column type, we can't add these columns for all types of database. Possible solution:
- Make `schema.xml > table-create > sql` support `db-types` definition, e.g. `db-types=PostgreSQL`, then the same name tables that have different columns will be created for different database.

**Comment by sandynz** [comment]
After some testing, I found solution 1 is not suitable, since added table columns will affect other test cases (columnCount assertion), there're too much related test cases need to update.

Considering possible solution 2:
If it could add columns before executing sql for every test case, and also drop columns after executing sql, the table structure change will be isolated to current test case.
Example test case:
```
    <dql-test-case
            sql="SELECT * FROM t_order WHERE rule = ?::jsonb AND start_point=ST_GeographyFromText('SRID=4326;POINT('||?||' '||?||')') AND user_id = ? AND order_id = ?"
            column-create="CREATE EXTENSION postgis; ALTER TABLE t_order ADD COLUMN rule ...;"
            column-drop="ALTER TABLE t_order DROP COLUMN rule"
            db-types="PostgreSQL">
```
`column-create` and `column-drop` are added attributes.

It might need some underlying base classes change.

**Comment by sandynz** [comment]
Another thing to memtion:
It need to install [PostGIS](https://postgis.net), and enable it in PostgreSQL.

> PostGIS is an optional extension that must be enabled in EVERY database you want to use it in.
CREATE EXTENSION postgis;
CREATE EXTENSION postgis_raster;

**Comment by tuohai666** [comment]
This test case is for parser test only, and should be removed from integration test.
