### ISSUE TITLE
In version 5.0.0, the namespace mode configuration issue

### ISSUE THREAD

**Issue by Hilary0511** [apache/shardingsphere#7061]
## Question

The following configuration will report an error
![image](https://user-images.githubusercontent.com/33475609/91157403-dbf81280-e6f7-11ea-960c-ccb4b108c8d0.png)

```
Error creating bean with name 'dataSourceMap' defined in class path resource [main-config.xml]: Cannot resolve reference to bean 'shardingDataSource' while setting constructor argument with key [TypedStringValue: value [shardingDataSource], target type [null]]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shardingDataSource': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource]: Constructor threw exception; nested exception is org.apache.shardingsphere.infra.exception.ShardingSphereException: RuleSchemaMetaData load failed

Error creating bean with name 'shardingDataSource': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource]: Constructor threw exception; nested exception is org.apache.shardingsphere.infra.exception.ShardingSphereException: RuleSchemaMetaData load failed
```

The sharding strategy is as follows
![image](https://user-images.githubusercontent.com/33475609/91157783-5c1e7800-e6f8-11ea-852d-d0c3bfd848bc.png)
![image](https://user-images.githubusercontent.com/33475609/91157862-79534680-e6f8-11ea-891e-0a250f0e1200.png)

**Comment by terrymanu** [comment]
```
ShardingSphereException: RuleSchemaMetaData load failed
```

It looks like your data source or rule config failure

**Comment by kimmking** [comment]
Can you show more exception logs?

**Comment by Hilary0511** [comment]
> ```
> ShardingSphereException: RuleSchemaMetaData load failed
> ```
> 
> 看起来您的数据源或规则配置失败



> ```
> ShardingSphereException: RuleSchemaMetaData load failed
> ```
> 
> It looks like your data source or rule config failure



> ```
> ShardingSphereException: RuleSchemaMetaData load failed
> ```
> 
> It looks like your data source or rule config failure

Well, I configured it this way in version 4.1.1 but configured it wrong in version 5.0.0. I'm not sure how to configure this sharding policy class reference right now

**Comment by Hilary0511** [comment]
> Can you show more exception logs?

17:23:56.776 [localhost-startStop-1] ERROR com.hhwy.fweb.framework.mvc.MainDispather - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'txManager' defined in class path resource [sys-kernel-config.xml]: Cannot resolve reference to bean 'dataSource' while setting bean property 'dataSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [sys-kernel-config.xml]: Cannot resolve reference to bean 'dataSourceMap' while setting bean property 'targetDataSources'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceMap' defined in class path resource [main-config.xml]: Cannot resolve reference to bean 'shardingDataSource' while setting constructor argument with key [TypedStringValue: value [shardingDataSource], target type [null]]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shardingDataSource': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource]: Constructor threw exception; nested exception is org.apache.shardingsphere.infra.exception.ShardingSphereException: RuleSchemaMetaData load failed
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:378)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:110)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1681)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1433)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:701)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:667)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:715)
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:590)
	at com.hhwy.fweb.framework.mvc.MainDispather.initWebApplicationContext(MainDispather.java:88)
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:529)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:169)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at com.hhwy.fweb.framework.mvc.MainDispather.init(MainDispather.java:54)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1091)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:985)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4883)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5197)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:614)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1822)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [sys-kernel-config.xml]: Cannot resolve reference to bean 'dataSourceMap' while setting bean property 'targetDataSources'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceMap' defined in class path resource [main-config.xml]: Cannot resolve reference to bean 'shardingDataSource' while setting constructor argument with key [TypedStringValue: value [shardingDataSource], target type [null]]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shardingDataSource': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource]: Constructor threw exception; nested exception is org.apache.shardingsphere.infra.exception.ShardingSphereException: RuleSchemaMetaData load failed
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:378)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:110)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1681)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1433)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:367)
	... 37 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceMap' defined in class path resource [main-config.xml]: Cannot resolve reference to bean 'shardingDataSource' while setting constructor argument with key [TypedStringValue: value [shardingDataSource], target type [null]]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shardingDataSource': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource]: Constructor threw exception; nested exception is org.apache.shardingsphere.infra.exception.ShardingSphereException: RuleSchemaMetaData load failed
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:378)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:110)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.lambda$resolveManagedMap$1(BeanDefinitionValueResolver.java:426)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveManagedMap(BeanDefinitionValueResolver.java:424)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:167)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:676)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:188)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1187)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:367)
	... 47 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shardingDataSource': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource]: Constructor threw exception; nested exception is org.apache.shardingsphere.infra.exception.ShardingSphereException: RuleSchemaMetaData load failed
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:304)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:285)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1187)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:367)
	... 63 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource]: Constructor threw exception; nested exception is org.apache.shardingsphere.infra.exception.ShardingSphereException: RuleSchemaMetaData load failed
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:184)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:300)
	... 73 common frames omitted
Caused by: org.apache.shardingsphere.infra.exception.ShardingSphereException: RuleSchemaMetaData load failed
	at org.apache.shardingsphere.infra.metadata.schema.RuleSchemaMetaDataLoader.lambda$asyncLoad$2(RuleSchemaMetaDataLoader.java:164)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.apache.shardingsphere.infra.metadata.schema.RuleSchemaMetaDataLoader.asyncLoad(RuleSchemaMetaDataLoader.java:160)
	at org.apache.shardingsphere.infra.metadata.schema.RuleSchemaMetaDataLoader.load(RuleSchemaMetaDataLoader.java:88)
	at org.apache.shardingsphere.kernel.context.SchemaContextsBuilder.createMetaData(SchemaContextsBuilder.java:130)
	at org.apache.shardingsphere.kernel.context.SchemaContextsBuilder.createShardingSphereSchema(SchemaContextsBuilder.java:124)
	at org.apache.shardingsphere.kernel.context.SchemaContextsBuilder.createSchemaContext(SchemaContextsBuilder.java:102)
	at org.apache.shardingsphere.kernel.context.SchemaContextsBuilder.build(SchemaContextsBuilder.java:93)
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.<init>(ShardingSphereDataSource.java:61)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172)
	... 75 common frames omitted
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.apache.shardingsphere.sql.parser.binder.metadata.schema.SchemaMetaDataLoader.load(Ljavax/sql/DataSource;ILjava/lang/String;Ljava/util/Collection;)Lorg/apache/shardingsphere/sql/parser/binder/metadata/schema/SchemaMetaData;
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:455)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
	at org.apache.shardingsphere.infra.metadata.schema.RuleSchemaMetaDataLoader.lambda$asyncLoad$2(RuleSchemaMetaDataLoader.java:162)
	... 97 common frames omitted
Caused by: java.lang.NoSuchMethodError: org.apache.shardingsphere.sql.parser.binder.metadata.schema.SchemaMetaDataLoader.load(Ljavax/sql/DataSource;ILjava/lang/String;Ljava/util/Collection;)Lorg/apache/shardingsphere/sql/parser/binder/metadata/schema/SchemaMetaData;
	at org.apache.shardingsphere.infra.metadata.schema.RuleSchemaMetaDataLoader.lambda$null$0(RuleSchemaMetaDataLoader.java:153)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	... 3 common frames omitted

**Comment by Hilary0511** [comment]
> Can you show more exception logs?

This is the complete error reporting log

**Comment by terrymanu** [comment]
The version 5.x is not released yet, it is still in dev model.
So welcome if you want to contribute something, for how to using, please waiting for the version release.

**Comment by Hilary0511** [comment]
> The version 5.x is not released yet, it is still in dev model.
> So welcome if you want to contribute something, for how to using, please waiting for the version release.

When will the next version be released
