### ISSUE TITLE
4.1.1mapper.xml use ognl cause ClassCastException

### ISSUE THREAD

**Issue by vinceLin054** [apache/shardingsphere#7118]
Insert sql value using ognl ${@com.alibaba.fastjson.JSON@toJSONString(address)}

The error message:
`Caused by: java.lang.ClassCastException: org.apache.shardingsphere.sql.parser.sql.segment.dml.column.ColumnSegment cannot be cast to org.apache.shardingsphere.sql.parser.sql.segment.dml.expr.ExpressionSegment
	at org.apache.shardingsphere.sql.parser.mysql.visitor.impl.MySQLDMLVisitor.visitAssignmentValues(MySQLDMLVisitor.java:234)
	at org.apache.shardingsphere.sql.parser.mysql.visitor.impl.MySQLDMLVisitor.visitAssignmentValues(MySQLDMLVisitor.java:127)
	at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$AssignmentValuesContext.accept(MySQLStatementParser.java:1865)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.apache.shardingsphere.sql.parser.mysql.visitor.impl.MySQLDMLVisitor.createInsertValuesSegments(MySQLDMLVisitor.java:191)
	at org.apache.shardingsphere.sql.parser.mysql.visitor.impl.MySQLDMLVisitor.visitInsertValuesClause(MySQLDMLVisitor.java:184)
	at org.apache.shardingsphere.sql.parser.mysql.visitor.impl.MySQLDMLVisitor.visitInsertValuesClause(MySQLDMLVisitor.java:127)
	at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$InsertValuesClauseContext.accept(MySQLStatementParser.java:1259)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.apache.shardingsphere.sql.parser.mysql.visitor.impl.MySQLDMLVisitor.visitInsert(MySQLDMLVisitor.java:144)
	at org.apache.shardingsphere.sql.parser.mysql.visitor.impl.MySQLDMLVisitor.visitInsert(MySQLDMLVisitor.java:127)
	at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$InsertContext.accept(MySQLStatementParser.java:1090)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.apache.shardingsphere.sql.parser.SQLParserEngine.parse0(SQLParserEngine.java:80)
	at org.apache.shardingsphere.sql.parser.SQLParserEngine.parse(SQLParserEngine.java:61)`

**Comment by kimmking** [comment]
plz show your original sql and actual sql

**Comment by vinceLin054** [comment]
Original sql:
`INSERT INTO
 uc_users
(username, connection_id, email, phone_number, address)
 VALUES
(#{username}, #{connectionId}, #{email},#{phoneNumber}, ${@com.alibaba.fastjson.JSON@toJSONString(address)address})

This exception happened before actual sql generate.

**Comment by kimmking** [comment]
> ${@com.alibaba.fastjson.JSON@toJSONString(address)address} 

should be a concrete value before passed to shardingspehre.

**Comment by vinceLin054** [comment]
` ${@com.alibaba.fastjson.JSON@toJSONString(address)})`
This is the hashMap type.
```
Map<String,String> map = new HashMap();
map.put("province", 230);
map.put("city", 75);
```
concrete value:
{"province":"230","city":"75"}

**Comment by vinceLin054** [comment]
This exception happened  again when I using string({"province":"230","city":"75"})  replace that ognl.

**Comment by vinceLin054** [comment]
I think ${} cause this exception.

**Comment by kimmking** [comment]
```
INSERT INTO
uc_users
(username, connection_id, email, phone_number, address)
VALUES
(1, 1, '1111',1111, '{"province":"230","city":"75"}')
```

**Comment by vinceLin054** [comment]
Yep, this way can make success.I hope you can be compatible with this situation.
