### ISSUE TITLE
load balance url is not supportted

### ISSUE THREAD

**Issue by johnny2002** [apache/shardingsphere#7123]
### Which version of ShardingSphere did you use?
4.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
JDBC
### Probleam:
We need to support load balance and failover throw jdbc driver, so our jdbc url contains 2 ip and ports, the url works in JDBC, while sharding-sphere throws exception.
### our url sample: 
 jdbc:postgresql://ip1:5432,ip2:5432/postgres?loadBalanceHosts=true
### the exception says:
Caused by: org.apache.shardingsphere.core.exception.ShardingException: The URL of JDBC is not supported. Please refer to this pattern: jdbc:postgresql://([\w\-\.]+):?([0-9]*)/([\w\-]+).
	at org.apache.shardingsphere.core.metadata.datasource.dialect.PostgreSQLDataSourceMetaData.<init>(PostgreSQLDataSourceMetaData.java:53) ~[sharding-core-common-4.0.0-RC1.jar:4.0.0-RC1]
	at org.apache.shardingsphere.core.metadata.datasource.DataSourceMetaDataFactory.newInstance(DataSourceMetaDataFactory.java:53) ~[sharding-core-common-4.0.0-RC1.jar:4.0.0-RC1]
	at org.apache.shardingsphere.core.metadata.datasource.ShardingDataSourceMetaData.getDataSourceMetaDataMapForSharding(ShardingDataSourceMetaData.java:52) ~[sharding-core-common-4.0.0-RC1.jar:4.0.0-RC1]

**Comment by johnny2002** [comment]
I think it isn't sharding-sphere's reponsibility to valid jdbc url, just leave it to underlying layer.

**Comment by kimmking** [comment]
5.0.0+ will support loadbalance JDBC Urls.

**Comment by johnny2002** [comment]
so, you won't fix it in 4.x?

> 5.0.0+ will support loadbalance JDBC Urls.

**Comment by kimmking** [comment]
there is no release plan for 4.x
