### ISSUE TITLE
Unsupported SQL of `CREATE PROCEDURE` and `CREATE FUNCTION`

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#7137]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Support SQL:

```
delimiter $$

CREATE PROCEDURE delete_matches(IN p_playerno INTEGER)      BEGIN DELETE FROM t_order WHERE id = p_playerno; 
END$$

CREATE FUNCTION fun1(v_id INT) RETURNS varchar(50) begin DECLARE v_userName varchar(50); select c into v_userName FROM t_order where id=v_id; return v_userName;
END$$

delimiter ;
```

### Actual behavior

```
line 1:54 no viable alternative at input '<EOF>'
line 1:54 no viable alternative at input '<EOF>'
line 1:7 no viable alternative at input 'CREATEPROCEDURE'
line 1:7 no viable alternative at input 'CREATEPROCEDURE'
[ERROR] 21:52:32.117 [ShardingSphere-Command-5] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
org.apache.shardingsphere.sql.parser.exception.SQLParsingException: Unsupported SQL of `CREATE PROCEDURE delete_matches(IN p_playerno INTEGER)`
	at org.apache.shardingsphere.rdl.parser.engine.executor.RDLSQLParserExecutor.execute(RDLSQLParserExecutor.java:55)
	at org.apache.shardingsphere.rdl.parser.engine.engine.RDLSQLParserEngine.parse0(RDLSQLParserEngine.java:70)
	at org.apache.shardingsphere.rdl.parser.engine.engine.RDLSQLParserEngine.parse(RDLSQLParserEngine.java:52)
	at org.apache.shardingsphere.rdl.parser.engine.ShardingSphereSQLParserEngine.parse(ShardingSphereSQLParserEngine.java:47)
	at org.apache.shardingsphere.proxy.backend.text.TextProtocolBackendHandlerFactory.newInstance(TextProtocolBackendHandlerFactory.java:75)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.<init>(MySQLComQueryPacketExecutor.java:71)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecutorFactory.newInstance(MySQLCommandExecutorFactory.java:70)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandExecutor(MySQLCommandExecuteEngine.java:60)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:94)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:73)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
line 1:87 no viable alternative at input 'beginDECLAREv_userNamevarchar(50)'
line 1:87 no viable alternative at input 'beginDECLAREv_userNamevarchar(50)'
line 1:7 no viable alternative at input 'CREATEFUNCTION'
line 1:7 no viable alternative at input 'CREATEFUNCTION'
[ERROR] 21:53:21.147 [ShardingSphere-Command-6] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
org.apache.shardingsphere.sql.parser.exception.SQLParsingException: Unsupported SQL of `CREATE FUNCTION fun1(v_id INT) RETURNS varchar(50) begin DECLARE v_userName varchar(50)`
	at org.apache.shardingsphere.rdl.parser.engine.executor.RDLSQLParserExecutor.execute(RDLSQLParserExecutor.java:55)
	at org.apache.shardingsphere.rdl.parser.engine.engine.RDLSQLParserEngine.parse0(RDLSQLParserEngine.java:70)
	at org.apache.shardingsphere.rdl.parser.engine.engine.RDLSQLParserEngine.parse(RDLSQLParserEngine.java:52)
	at org.apache.shardingsphere.rdl.parser.engine.ShardingSphereSQLParserEngine.parse(ShardingSphereSQLParserEngine.java:47)
	at org.apache.shardingsphere.proxy.backend.text.TextProtocolBackendHandlerFactory.newInstance(TextProtocolBackendHandlerFactory.java:75)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.<init>(MySQLComQueryPacketExecutor.java:71)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecutorFactory.newInstance(MySQLCommandExecutorFactory.java:70)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandExecutor(MySQLCommandExecuteEngine.java:60)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:94)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:73)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tuohai666** [comment]
The exception caused by parser. @tristaZero , can you have a look?

**Comment by strongduanmu** [comment]
@tuohai666 Hi, what does the `&&` symbol in the SQL mean? This symbol is not included in the official MySQL syntax——[CREATE PROCEDURE and CREATE FUNCTION Statements](https://dev.mysql.com/doc/refman/8.0/en/create-procedure.html).

**Comment by lidonghai11** [comment]
@strongduanmu    when you create a procedure, you must  change the statement delimiter from ; to $$ (or anything else) first.Then you issue "CREATE PROCEDURE STATEMENT".

**Comment by tuohai666** [comment]
@strongduanmu 
Agree with @lidonghai11 .
We can find how to use delimiter in the official document:
![image](https://user-images.githubusercontent.com/24643893/91829797-803c0500-ec74-11ea-915b-3a40776f2975.png)

**Comment by strongduanmu** [comment]
@tuohai666 @lidonghai11 Thank you very much, I will test again.

**Comment by strongduanmu** [comment]
@tuohai666 I have used delimiter to create function and procedure, but there was no exception. How can I reproduce this exception?

**Comment by lidonghai11** [comment]
@strongduanmu mine doesn't work.
![f](https://user-images.githubusercontent.com/66629133/92560093-61f18d00-f2a4-11ea-8188-6bf154fb89f4.png)
![l](https://user-images.githubusercontent.com/66629133/92560107-67e76e00-f2a4-11ea-8e2b-91dbf1517738.png)
Meybe there are some differences  between yours and mine, I will let @tuohai666   help  me to check that if there are sometings missing  in my environment.

**Comment by tuohai666** [comment]
@lidonghai11 Can you move `END` to a separate line, and have a try?

**Comment by lidonghai11** [comment]
The latest version  of proxy supports the '`CREATE PROCEDURE` and `CREATE FUNCTION`',so this issue can be closed
