### ISSUE TITLE
Unsupported SQL of `CREATE VIEW`

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#7138]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Support SQL:

`create view view1 as select * from t_order where id!=1;`

### Actual behavior

```
line 1:7 no viable alternative at input 'createview'
line 1:7 no viable alternative at input 'createview'
line 1:7 no viable alternative at input 'createview'
line 1:7 no viable alternative at input 'createview'
[ERROR] 22:20:05.284 [ShardingSphere-Command-7] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
org.apache.shardingsphere.sql.parser.exception.SQLParsingException: Unsupported SQL of `create view view1 as select * from t_order where id!=1`
	at org.apache.shardingsphere.rdl.parser.engine.executor.RDLSQLParserExecutor.execute(RDLSQLParserExecutor.java:55)
	at org.apache.shardingsphere.rdl.parser.engine.engine.RDLSQLParserEngine.parse0(RDLSQLParserEngine.java:70)
	at org.apache.shardingsphere.rdl.parser.engine.engine.RDLSQLParserEngine.parse(RDLSQLParserEngine.java:52)
	at org.apache.shardingsphere.rdl.parser.engine.ShardingSphereSQLParserEngine.parse(ShardingSphereSQLParserEngine.java:47)
	at org.apache.shardingsphere.proxy.backend.text.TextProtocolBackendHandlerFactory.newInstance(TextProtocolBackendHandlerFactory.java:75)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.<init>(MySQLComQueryPacketExecutor.java:71)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecutorFactory.newInstance(MySQLCommandExecutorFactory.java:70)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandExecutor(MySQLCommandExecuteEngine.java:60)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:94)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:73)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tuohai666** [comment]
The exception caused by parser. @tristaZero , can you have a look?

**Comment by kimmking** [comment]
Hi, guys,
any update now?

**Comment by strongduanmu** [comment]
@kimmking @tuohai666 I have tried to submit a [PR](https://github.com/apache/shardingsphere/pull/7150) before, but there are some limitations, and it cannot perfectly support view create, modify, delete and query when including logic table.

After discussing with @tristaZero , we think that the priority of view is not high, and users can get the same result of view through table join query, so we do not plan to support view now.

**Comment by tristaZero** [comment]
Hi @strongduanmu Just to confirm, currently `create view` is partly support? Or completely unsupported?

**Comment by strongduanmu** [comment]
> Hi @strongduanmu Just to confirm, currently `create view` is partly support? Or completely unsupported?

@tristaZero Currently `create view` is completely unsupported, and the following exception will be thrown: SQLParsingException: Unsupported SQL of `create view view1 as select * from t_order where id!=1`
