### ISSUE TITLE
Bug: Property read with '.'

### ISSUE THREAD

**Issue by 291277058** [apache/shardingsphere#7163]
## Bug Report
`
Caused by: java.lang.IllegalArgumentException: aes.key.value can not be null.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142) ~[guava-29.0-jre.jar:na]
	at org.apache.shardingsphere.encrypt.algorithm.AESEncryptAlgorithm.createSecretKey(AESEncryptAlgorithm.java:57) ~[shardingsphere-encrypt-common-5.0.0-RC1-SNAPSHOT.jar:5.0.0-RC1-SNAPSHOT]
	at org.apache.shardingsphere.encrypt.algorithm.AESEncryptAlgorithm.init(AESEncryptAlgorithm.java:53) ~[shardingsphere-encrypt-common-5.0.0-RC1-SNAPSHOT.jar:5.0.0-RC1-SNAPSHOT]
	at org.apache.shardingsphere.spring.boot.registry.AbstractAlgorithmProvidedBeanRegistry.postProcessAfterInitialization(AbstractAlgorithmProvidedBeanRegistry.java:84) ~[shardingsphere-jdbc-spring-boot-starter-infra-5.0.0-RC1-SNAPSHOT.jar:5.0.0-RC1-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:430) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1798) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	... 93 common frames omitted

`

### Which version of ShardingSphere did you use?

5.0.0-RC1

springboot version 2.3.3

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Expected behavior

Project start init error

### Reason analyze (If you can)

`Map<String, Object> propsMap = PropertyUtil.handle(environment, preFix + key + ".props", Map.class);`
props all read as Map

![image](https://user-images.githubusercontent.com/33279488/91679620-72ef1f80-eb7b-11ea-8020-4f2323d939bf.png)
Read it as string key, than get the following error

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

Project init

**Comment by 291277058** [comment]
There are lots of property config like aes.key.value. It will cause error with spingboot.

**Comment by 291277058** [comment]
If swittch '.' to '-' could be better.

**Comment by tristaZero** [comment]
Hi @291277058 
My impression is that there was this issue before. The solution for that is to upgrade the version of springBoot if my memory serves. Do you think that can answer your question? Else, you can take a keyword search in the issue list for the similar ones.

**Comment by 291277058** [comment]
> Hi @291277058
> My impression is that there was this issue before. The solution for that is to upgrade the version of springBoot if my memory serves. Do you think that can answer your question? Else, you can take a keyword search in the issue list for the similar ones.

I am allready use the newest version of spingboot, when use the appliction.property config, this bug always happened.I did not found any test to cover this problem.

**Comment by tristaZero** [comment]
@291277058 Hi Sorry for my mistake.
`.` is supported by 2.0.0 and the previous version. The latest version will throw the exception as yours.
Here is the version ShardingSphere using

```
<spring-boot.version>[1.5.20.RELEASE,2.0.0.M1)</spring-boot.version>
```
However, a discussion about changing all the properties with `-` is required for the community, since that is a considerable modification.

Again, thanks for your issue. :-)

Trista

**Comment by kimmking** [comment]
@yu199195 can you track this issue?

**Comment by tristaZero** [comment]
Sorry, @kimmking @yu199195 an update here.
@291277058 is one the way fixing this one. Let us wait for his good news!
