### ISSUE TITLE
Multi netty version caused connect fail 

### ISSUE THREAD

**Issue by xbkaishui** [apache/shardingsphere#7293]
## Bug Report
I compiler the master branch,  and test the latest ShardingSphere-Proxy, found it start ok, but can't connect, caused by multi netty version problem. 
 
**For English only**, other languages will not accept.
Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
connect successfully 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 2
Server version: 8.0.18-ShardingSphere-Proxy 5.0.0-RC1

### Actual behavior
throws exception 
`
[INFO ] 18:31:53.289 [nioEventLoopGroup-2-1] i.n.handler.logging.LoggingHandler - [id: 0x0221e17b, L:/0.0.0.0:3307] READ: [id: 0x981666e9, L:/127.0.0.1:3307 - R:/127.0.0.1:60604]
[INFO ] 18:31:53.308 [nioEventLoopGroup-2-1] i.n.handler.logging.LoggingHandler - [id: 0x0221e17b, L:/0.0.0.0:3307] READ COMPLETE
[WARN ] 18:31:53.374 [nioEventLoopGroup-3-1] i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NoSuchMethodError: io.netty.buffer.ByteBuf.isContiguous()Z
	at io.netty.handler.codec.ByteToMessageDecoder$1.cumulate(ByteToMessageDecoder.java:83)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:274)
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
`

### Reason analyze (If you can)

**I check the maven dependency. it is caused by curator-client which required high netty version** 
 +- org.apache.curator:curator-client:jar:5.1.0:compile
[INFO] |  |  \- org.apache.zookeeper:zookeeper:jar:3.6.0:compile
[INFO] |  |     +- commons-lang:commons-lang:jar:2.6:compile
[INFO] |  |     +- org.apache.zookeeper:zookeeper-jute:jar:3.6.0:compile
[INFO] |  |     +- org.apache.yetus:audience-annotations:jar:0.5.0:compile
[INFO] |  |     +- io.netty:netty-handler:jar:4.1.45.Final:compile
[INFO] |  |     |  +- io.netty:netty-common:jar:4.1.45.Final:compile
[INFO] |  |     |  +- io.netty:netty-buffer:jar:4.1.45.Final:compile
[INFO] |  |     |  +- io.netty:netty-transport:jar:4.1.45.Final:compile
[INFO] |  |     |  |  \- io.netty:netty-resolver:jar:4.1.45.Final:compile
[INFO] |  |     |  \- io.netty:netty-codec:jar:4.1.45.Final:compile
[INFO] |  |     +- io.netty:netty-transport-native-epoll:jar:4.1.45.Final:compile
[INFO] |  |     |  \- io.netty:netty-transport-native-unix-common:jar:4.1.45.Final:compile
[INFO] |  |     \- log4j:log4j:jar:1.2.17:compile

**the default netty version is 4.1.42, which caused the problem..** 

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
start proxy successfully , try use mysql client to login proxy , it hung, logs show error 
mysql -h127.0.0.1 -P3307 -usharding -p

**Comment by xbkaishui** [comment]
please assign to me if it is acceptable ?
