### ISSUE TITLE
 CREATE TABLE IF NOT EXISTS  execute fail

### ISSUE THREAD

**Issue by xbkaishui** [apache/shardingsphere#7323]
## Bug Report
```
### SQL: CREATE TABLE IF NOT EXISTS t_order (order_id BIGINT AUTO_INCREMENT, user_id INT NOT NULL, address_id BIGINT NOT NULL, status VARCHAR(50), PRIMARY KEY (order_id));
### Cause: org.apache.shardingsphere.sharding.route.engine.exception.TableExistsException: Table 't_order' already exists.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:434)
	... 17 more
Caused by: org.apache.shardingsphere.sharding.route.engine.exception.TableExistsException: Table 't_order' already exists.
	at org.apache.shardingsphere.sharding.route.engine.validator.impl.ShardingCreateTableStatementValidator.preValidate(ShardingCreateTableStatementValidator.java:40)
	at org.apache.shardingsphere.sharding.route.engine.ShardingRouteDecorator.lambda$decorate$0(ShardingRouteDecorator.java:66)
```

**For English only**, other languages will not accept.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
run and finish successfully 
### Actual behavior
throws an exception 

### Reason analyze (If you can)
The logic is in ShardingCreateTableStatementValidator.preValidate.  I think for it should not check if the create table contains   IF NOT EXISTS statement 

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Run any the example module , with pre created table

**Comment by tristaZero** [comment]
Hi @xbkaishui 

Thanks for your feedback. It is unsupported at present, but it is not a difficult one from my perspective. Here is a simple solution from me.

1. Add a boolean member like `isNotExisted` to `CreateTableStatement`
2. Check this new table in `ShardingCreateTableStatementValidator` with `ShardingSphereMetaData`

Welcome anyone interested in it to have a try!

BTW, @strongduanmu Would you like to take charge of this one? 
This is just a kind inquiry since I knew you are working on another important issue. If you are out of the time, we can ask the bits of help from the community. :-)

Best,
Trista

**Comment by xbkaishui** [comment]
Please let me try, I am not familiar with the sql parser part.

**Comment by tristaZero** [comment]
@xbkaishui It is not a very easy job for a newbie, but welcome to your initiative!
If you need any help, please tell me.

**Comment by xbkaishui** [comment]
Ok, thanks

**Comment by strongduanmu** [comment]
@tristaZero I am very sorry for the late reply and I think @xbkaishui  can do a great job on this issue. 😀

**Comment by tristaZero** [comment]
> @tristaZero I am very sorry for the late reply and I think @xbkaishui can do a great job on this issue. 😀

Yep, I believe that.
Both of you are the significant force for the community. I hope you can enjoy yourselves with the OS community. :-)
