### ISSUE TITLE
提交的时候报空指针异常

### ISSUE THREAD

**Issue by pengliaoye** [apache/shardingsphere#7347]
spring cloud version: Hoxton.SR8
spring cloud alibaba: 2.2.1.RELEASE
spring boot version: 2.3.3.RELEASE
shardingsphere : 4.1.1
seata: 1.2.0
jdk: 8

[ERROR] 2020-09-09 14:52:56,839 --reactor-http-nio-2-- [io.seata.rm.datasource.ConnectionProxy] process connectionProxy commit error: null 
java.lang.NullPointerException: null
	at org.apache.shardingsphere.transaction.base.seata.at.SeataATShardingTransactionManager.commit(SeataATShardingTransactionManager.java:110)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.connection.ShardingConnection.commit(ShardingConnection.java:155)
	at io.seata.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:222)
	at io.seata.rm.datasource.ConnectionProxy.doCommit(ConnectionProxy.java:196)
	at io.seata.rm.datasource.ConnectionProxy.lambda$commit$0(ConnectionProxy.java:184)
	at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.execute(ConnectionProxy.java:289)
	at io.seata.rm.datasource.ConnectionProxy.commit(ConnectionProxy.java:183)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.lambda$executeAutoCommitTrue$0(AbstractDMLBaseExecutor.java:106)
	at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.doRetryOnLockConflict(ConnectionProxy.java:299)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$LockRetryPolicy.execute(AbstractDMLBaseExecutor.java:149)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:104)

**Comment by kimmking** [comment]
Hi,  @pengliaoye  English only here.
And can you show how to reproduce this issue?

**Comment by pengliaoye** [comment]
@kimmking  first execute, seata server log:
![1](https://user-images.githubusercontent.com/2573426/92670875-894d6600-f347-11ea-8cb5-f9d15394e941.png)
and sencond execute same code, seata server log:
![2](https://user-images.githubusercontent.com/2573426/92670903-99654580-f347-11ea-9d38-616fb375ec62.png)

![3](https://user-images.githubusercontent.com/2573426/92671256-5657a200-f348-11ea-8ab6-e529b9b5d07f.png)


my code snippet。same code， different port。 
Service A： 8080
Service B： 8081

Service A：  invoke insertOrderA，and using feigin invoke Service B   insertOrderB method
Service B： has insertOrderB method

    @GlobalTransactional
    @ShardingTransactionType(TransactionType.BASE)
    public void insertOrderA(Order order) {
        System.out.println("全局事务id 1 ：" + RootContext.getXID() + TransactionTypeHolder.get());
        orderMapper.insert(order);
        System.out.println("全局事务id 2 ：" + RootContext.getXID()  + TransactionTypeHolder.get());
        demoClient.testInsertB();
    }

    @ShardingTransactionType(TransactionType.BASE)
    public void insertOrderB(Order order) {
        System.out.println("全局事务id 3 ：" + RootContext.getXID()  + TransactionTypeHolder.get());
        orderMapper.insert(order);
        System.out.println("全局事务id 4 ：" + RootContext.getXID()  + TransactionTypeHolder.get());
        throw new RuntimeException("mock transaction failed");
    }

**Comment by niudadan** [comment]
![image](https://user-images.githubusercontent.com/11550882/97578278-860f5600-1a2b-11eb-95be-9b5cbd3b29c3.png)
I reproduced the same problem as you. How did you solve it

**Comment by pengliaoye** [comment]
not resolved

**Comment by niudadan** [comment]
Are you integrated now，seata+sharding jdbc

**Comment by niudadan** [comment]
i need you help

**Comment by pengliaoye** [comment]
i don't resolve this problem

**Comment by pdyg** [comment]
It seems that the primary key is not set to increase by itself. Please check

**Comment by pdyg** [comment]
![image](https://user-images.githubusercontent.com/18324792/111275740-6cd11400-8671-11eb-8c33-bd29255a4035.png)
![image](https://user-images.githubusercontent.com/18324792/111275772-78243f80-8671-11eb-97d8-8200445558aa.png)
@pengliaoye

**Comment by pdyg** [comment]
The column name of the data table does not conform to the specification .It can also lead to the whole mistake

![image](https://user-images.githubusercontent.com/18324792/111275970-c1748f00-8671-11eb-90fd-6ac07ca7788e.png)

**Comment by medoer** [comment]
![image](https://user-images.githubusercontent.com/20471718/112611811-39546d80-8e59-11eb-82be-8612e94853ac.png)

get seata GlobalTransaction is NULL
