### ISSUE TITLE
Manually open the transaction and commit the transaction successfully, but the commit transaction still reports an error

### ISSUE THREAD

**Issue by lianghuaibin** [apache/shardingsphere#7357]
I started the transaction manually, and manually committed the transaction successfully, but the returned result reported an exception error.
Occasionally, this error occurs when batch updating more than 10W pieces of data

The error report is as follows：

```
**org.springframework.transaction.TransactionSystemException: Could not commit JDBC transaction; nested exception is java.sql.SQLException 
at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:270) ~[spring-jdbc-3.2.0.RELEASE.jar:3.2.0.RELEASE] 
at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754) ~[spring-tx-3.2.0.RELEASE.jar:3.2.0.RELEASE] 
at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723) ~[spring-tx-3.2.0.RELEASE.jar:3.2.0.RELEASE] 
at com.jd.finsetts.common.frame.BaseService.commitTransactionManager(BaseService.java:50) ~[finsettsJsf-common-2.0.0.jar:na] at com.jd.finsetts.service.settBizHandler2.DefaultSettHandler2.saveFinSettInfo(DefaultSettHandler2.java:326) ~[finsettsJsf-service-2.0.0.jar:na] at com.jd.finsetts.service.settBizHandler2.settBiz.Sett103Handler.execute(Sett103Handler.java:67) [finsettsJsf-service-2.0.0.jar:na] at com.jd.finsetts.service.settBizHandler2.settBiz.Sett103Handler$$FastClassByCGLIB$$823e1aa4.invoke() [spring-core-3.2.0.RELEASE.jar:na] at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-3.2.0.RELEASE.jar:3.2.0.RELEASE] 
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:698) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] 
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] 
at com.alibaba.druid.support.spring.stat.DruidStatInterceptor.invoke(DruidStatInterceptor.java:72) [druid-1.0.29.jar:1.0.29] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:631) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at com.jd.finsetts.service.settBizHandler2.settBiz.Sett103AHandler$$EnhancerByCGLIB$$1274000f.execute() [spring-core-3.2.0.RELEASE.jar:na] 
at com.jd.finsetts.jsf.impl.FinAutoSettApiServiceImpl.autoSett2(FinAutoSettApiServiceImpl.java:120) [finsettsJsf-service-2.0.0.jar:na] 
at com.jd.finsetts.jsf.impl.FinAutoSettApiServiceImpl$$FastClassByCGLIB$$72020d5b.invoke() [spring-core-3.2.0.RELEASE.jar:na] 
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-3.2.0.RELEASE.jar:3.2.0.RELEASE] 
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:698) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] 
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:80) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at com.jd.ump.annotation.JAnnotation.execJAnnotation(JAnnotation.java:96) [jannotation-2.1.0.jar:na] at sun.reflect.GeneratedMethodAccessor1462.invoke(Unknown Source) ~[na:na] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_71] at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_71] at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at com.alibaba.druid.support.spring.stat.DruidStatInterceptor.invoke(DruidStatInterceptor.java:72) [druid-1.0.29.jar:1.0.29] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:631) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] 
at com.jd.finsetts.jsf.impl.FinAutoSettApiServiceImpl$$EnhancerByCGLIB$$1ac9bf89.autoSett2() [spring-core-3.2.0.RELEASE.jar:na] at com.jd.finsetts.jsf.impl.settGeneralApiHandler.handler.SettGeneralApiMainHandler.autoSett4JSFAPI(SettGeneralApiMainHandler.java:99) [finsettsJsf-service-2.0.0.jar:na]
 at com.jd.finsetts.jsf.impl.settGeneralApiHandler.handler.SettGeneralApiMainHandler$$FastClassByCGLIB$$2b3c0d35.invoke() [spring-core-3.2.0.RELEASE.jar:na] 
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:698) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at com.alibaba.druid.support.spring.stat.DruidStatInterceptor.invoke(DruidStatInterceptor.java:72) [druid-1.0.29.jar:1.0.29] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:631) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at com.jd.finsetts.jsf.impl.settGeneralApiHandler.handler.SettGeneralApiMainHandler$$EnhancerByCGLIB$$cd19d6f5.autoSett4JSFAPI() [spring-core-3.2.0.RELEASE.jar:na] at com.jd.finsetts.jsf.impl.FinSettGeneralApiImpl.autoSett4JSFAPI(FinSettGeneralApiImpl.java:190) [finsettsJsf-service-2.0.0.jar:na] at com.jd.finsetts.jsf.impl.FinSettGeneralApiImpl$$FastClassByCGLIB$$72dde223.invoke() [spring-core-3.2.0.RELEASE.jar:na] at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:698) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at com.alibaba.druid.support.spring.stat.DruidStatInterceptor.invoke(DruidStatInterceptor.java:72) [druid-1.0.29.jar:1.0.29] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:631) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at com.jd.finsetts.jsf.impl.FinSettGeneralApiImpl$$EnhancerByCGLIB$$c56dac23.autoSett4JSFAPI() [spring-core-3.2.0.RELEASE.jar:na] at com.jdd.finsetts.controller.FinFeeDetailController.applySett(FinFeeDetailController.java:837) [FinFeeDetailController.class:na] at com.jdd.finsetts.controller.FinFeeDetailController$$FastClassByCGLIB$$4491ca73.invoke() [spring-core-3.2.0.RELEASE.jar:na] at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:698) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:50) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:55) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:50) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:631) [spring-aop-3.2.0.RELEASE.jar:3.2.0.RELEASE] at com.jdd.finsetts.controller.FinFeeDetailController$$EnhancerByCGLIB$$9656e24e.applySett() [spring-core-3.2.0.RELEASE.jar:na] at sun.reflect.GeneratedMethodAccessor4285.invoke(Unknown Source) ~[na:na] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_71] at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_71] at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:219) [spring-web-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132) [spring-web-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) [spring-webmvc-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:746) [spring-webmvc-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:687) [spring-webmvc-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80) [spring-webmvc-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:925) [spring-webmvc-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856) [spring-webmvc-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:915) [spring-webmvc-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:822) [spring-webmvc-3.2.0.RELEASE.jar:3.2.0.RELEASE] at javax.servlet.http.HttpServlet.service(HttpServlet.java:650) [servlet-api.jar:na] at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:796) [spring-webmvc-3.2.0.RELEASE.jar:3.2.0.RELEASE] at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) [servlet-api.jar:na] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [catalina.jar:7.0.61] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.61] at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat7-websocket.jar:7.0.61] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.61] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.61] at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:239) [javamelody-core-1.74.0.jar:1.74.0] at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:215) [javamelody-core-1.74.0.jar:1.74.0] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.61] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.61] at com.jdd.finsetts.controller.interceptor.CorsFilter.doFilter(CorsFilter.java:39) [CorsFilter.class:na] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.61] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.61] at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88) [spring-web-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-3.2.0.RELEASE.jar:3.2.0.RELEASE] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.61] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.61] at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [catalina.jar:7.0.61] at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [catalina.jar:7.0.61] at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505) [catalina.jar:7.0.61] at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) [catalina.jar:7.0.61] at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [catalina.jar:7.0.61] at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) [catalina.jar:7.0.61] at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.61] at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423) [catalina.jar:7.0.61] at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079) [tomcat-coyote.jar:7.0.61] at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620) [tomcat-coyote.jar:7.0.61] at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316) [tomcat-coyote.jar:7.0.61] at com.alibaba.mtc.MtContextRunnable.run(MtContextRunnable.java:46) [multithread.context-1.2.1.jar:na] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71] at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote.jar:7.0.61] 
at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71] Caused by: java.sql.SQLException: null 
at org.apache.shardingsphere.shardingjdbc.jdbc.adapter.executor.ForceExecuteTemplate.throwSQLExceptionIfNecessary(ForceExecuteTemplate.java:56) ~[sharding-jdbc-core-4.0.1.jar:4.0.1] 
at org.apache.shardingsphere.shardingjdbc.jdbc.adapter.executor.ForceExecuteTemplate.execute(ForceExecuteTemplate.java:49) ~[sharding-jdbc-core-4.0.1.jar:4.0.1] 
at org.apache.shardingsphere.shardingjdbc.jdbc.adapter.AbstractConnectionAdapter.commit(AbstractConnectionAdapter.java:184) ~[sharding-jdbc-core-4.0.1.jar:4.0.1] 
at org.apache.shardingsphere.shardingjdbc.jdbc.core.connection.ShardingConnection.commit(ShardingConnection.java:164) ~[sharding-jdbc-core-4.0.1.jar:4.0.1] 
at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:267) ~[spring-jdbc-3.2.0.RELEASE.jar:3.2.0.RELEASE] ... 114 common frames omitted**
```

**Comment by kimmking** [comment]
which version do you use?

**Comment by lianghuaibin** [comment]
version  4.0.1

**Comment by lianghuaibin** [comment]
Caused by: java.sql.SQLException: null
    at org.apache.shardingsphere.shardingjdbc.jdbc.adapter.executor.ForceExecuteTemplate.throwSQLExceptionIfNecessary(ForceExecuteTemplate.java:56) ~[sharding-jdbc-core-4.0.1.jar:4.0.1]
    at org.apache.shardingsphere.shardingjdbc.jdbc.adapter.executor.ForceExecuteTemplate.execute(ForceExecuteTemplate.java:49) ~[sharding-jdbc-core-4.0.1.jar:4.0.1]
    at org.apache.shardingsphere.shardingjdbc.jdbc.adapter.AbstractConnectionAdapter.commit(AbstractConnectionAdapter.java:184) ~[sharding-jdbc-core-4.0.1.jar:4.0.1]
    at org.apache.shardingsphere.shardingjdbc.jdbc.core.connection.ShardingConnection.commit(ShardingConnection.java:164) ~[sharding-jdbc-core-4.0.1.jar:4.0.1]
    at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:267) ~[spring-jdbc-3.2.0.RELEASE.jar:3.2.0.RELEASE]
    ... 114 common frames omitted

**Comment by cherrylzhao** [comment]
please paste the sharding configuration and batch updating transaction code here.

**Comment by hylyLLL** [comment]
@lianghuaibin Caused by: java.sql.SQLException: null
at org.apache.shardingsphere.shardingjdbc.jdbc.adapter.executor.ForceExecuteTemplate.throwSQLExceptionIfNecessary(ForceExecuteTemplate.java:56) ~[sharding-jdbc-core-4.0.1.jar:4.0.1]


請問你解決了嘛？

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 6 months, we will close it. 
If you still have related questions, please submit a new issue, thank you.
