### ISSUE TITLE
Failed to get all Tables from Predicate

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#7366]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Expected behavior

Correctly execute SQL:

`select * from t_order where status="\"";`

### Actual behavior

```

java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:492)
	at org.apache.shardingsphere.sql.parser.sql.common.util.TableExtractUtils.getAllTablesFromPredicate(TableExtractUtils.java:249)
	at org.apache.shardingsphere.sql.parser.sql.common.util.TableExtractUtils.getAllTablesFromWhere(TableExtractUtils.java:214)
	at org.apache.shardingsphere.sql.parser.sql.common.util.TableExtractUtils.getTablesFromSelect(TableExtractUtils.java:67)
	at org.apache.shardingsphere.sql.parser.binder.statement.dml.SelectStatementContext.getAllTables(SelectStatementContext.java:181)
	at org.apache.shardingsphere.sharding.rewrite.token.generator.impl.TableTokenGenerator.generateSQLTokens(TableTokenGenerator.java:53)
	at org.apache.shardingsphere.sharding.rewrite.token.generator.impl.TableTokenGenerator.generateSQLTokens(TableTokenGenerator.java:48)
	at org.apache.shardingsphere.infra.rewrite.sql.token.generator.SQLTokenGenerators.generateSQLTokens(SQLTokenGenerators.java:82)
	at org.apache.shardingsphere.infra.rewrite.context.SQLRewriteContext.generateSQLTokens(SQLRewriteContext.java:83)
	at org.apache.shardingsphere.infra.rewrite.SQLRewriteEntry.createSQLRewriteContext(SQLRewriteEntry.java:75)
	at org.apache.shardingsphere.infra.rewrite.SQLRewriteEntry.rewrite(SQLRewriteEntry.java:67)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.createExecutionContext(ShardingSphereStatement.java:289)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.executeQuery(ShardingSphereStatement.java:122)
```

### Reason analyze (If you can)

The Exception is from here:

TableExtractUtils

```
        if (predicate.getRightValue() instanceof ColumnSegment) {
            Preconditions.checkState(((ColumnSegment) predicate.getRightValue()).getOwner().isPresent());
            OwnerSegment segment = ((ColumnSegment) predicate.getRightValue()).getOwner().get();
            result.add(new SimpleTableSegment(segment.getStartIndex(), segment.getStopIndex(), segment.getIdentifier()));
        }
```

**Comment by jingshanglu** [comment]
@tuohai666 Now, #7353 has refactored TableExtractUtils, will fix it.
