### ISSUE TITLE
Unable to find property 'dataSourceCommon' on class: org.apache.shardingsphere.shardingproxy.config.yaml.YamlProxyRuleConfiguration

### ISSUE THREAD

**Issue by bjo2008cnx** [apache/shardingsphere#7450]
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'dataSourceCommon' on class: org.apache.shardingsphere.shardingproxy.config.yaml.YamlProxyRuleConfiguration
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:132)
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:121)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.getProperty(Constructor.java:322)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:240)
	... 11 more

I see there is dataSourceCommon configuration in shrdingshere doc. which version is it supported?Many thanks.

**Comment by menghaoranss** [comment]
@bjo2008cnx  `dataSourceCommon` is supported in master branch, and the new version 5.0.0-alpha will be released soon.

**Comment by bjo2008cnx** [comment]
get it. thank you very much
