### ISSUE TITLE
Error in 'update' operation using shardingshpere

### ISSUE THREAD

**Issue by cbxiaorenwu** [apache/shardingsphere#7523]
### Which version of ShardingSphere did you use?
4.1.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere JDBC
Connect two MySQL databases (DS_ 0,ds_ 1) , the table names in the library are consistent (test), and there is a unique primary key for distinguishing,

Odd primary key in DS_ In the 0 library, the even number of primary keys is in DS_ 1

### Expected behavior
The modification is successful and only one SQL statement is executed;

### Actual behavior

Cannot support Multiple-Table for 'org.apache.shardingsphere.sql.parser.sql.statement.dml.UpdateStatement@3f7f9d3f'.

```

}{FATAL=Bright red, ERROR=Red, WARN=Bright yellow, INFO=Bright green, DEBUG=green, TRACE=cyan} java.lang.IllegalStateException: Failed to execute CommandLineRunner
at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784) [spring-boot-2.1.15.RELEASE.jar:2.1.15.RELEASE]
at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:765) [spring-boot-2.1.15.RELEASE.jar:2.1.15.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:319) [spring-boot-2.1.15.RELEASE.jar:2.1.15.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.1.15.RELEASE.jar:2.1.15.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204) [spring-boot-2.1.15.RELEASE.jar:2.1.15.RELEASE]
at net.engining.rrr.init.InitApplication.main(InitApplication.java:19) [classes/:?]
Caused by: org.apache.shardingsphere.underlying.common.exception.ShardingSphereException: Cannot support Multiple-Table for 'org.apache.shardingsphere.sql.parser.sql.statement.dml.UpdateStatement@3f7f9d3f'.
at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.route(ShardingStandardRoutingEngine.java:72) ~[sharding-core-route-4.1.1.jar:4.1.1]
at org.apache.shardingsphere.sharding.route.engine.ShardingRouteDecorator.decorate(ShardingRouteDecorator.java:69) ~[sharding-core-route-4.1.1.jar:4.1.1]
at org.apache.shardingsphere.sharding.route.engine.ShardingRouteDecorator.decorate(ShardingRouteDecorator.java:53) ~[sharding-core-route-4.1.1.jar:4.1.1]
at org.apache.shardingsphere.underlying.route.DataNodeRouter.executeRoute(DataNodeRouter.java:91) ~[shardingsphere-route-4.1.1.jar:4.1.1]
at org.apache.shardingsphere.underlying.route.DataNodeRouter.route(DataNodeRouter.java:76) ~[shardingsphere-route-4.1.1.jar:4.1.1]
at org.apache.shardingsphere.underlying.pluggble.prepare.PreparedQueryPrepareEngine.route(PreparedQueryPrepareEngine.java:54) ~[shardingsphere-pluggable-4.1.1.jar:4.1.1]
at org.apache.shardingsphere.underlying.pluggble.prepare.BasePrepareEngine.executeRoute(BasePrepareEngine.java:96) ~[shardingsphere-pluggable-4.1.1.jar:4.1.1]
at org.apache.shardingsphere.underlying.pluggble.prepare.BasePrepareEngine.prepare(BasePrepareEngine.java:83) ~[shardingsphere-pluggable-4.1.1.jar:4.1.1]
at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.prepare(ShardingPreparedStatement.java:183) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.executeUpdate(ShardingPreparedStatement.java:131) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
at net.engining.rrr.init.data.example.QueryDslDemoInit.update_aroundBody2(QueryDslDemoInit.java:124) ~[classes/:?]
```
### Reason analyze (If you can)
nothing
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
    nothing
### Example codes for reproduce this issue (such as a github link).
   nothing

**Comment by menghaoranss** [comment]
@cbxiaorenwu please show your sharding rule and logic sql.

**Comment by kimmking** [comment]
Update/Insert/Delete statement with `Multiple-Table` doesn't supported.

**Comment by cbxiaorenwu** [comment]
What if you want to do Update operation with sharding? Is sharding not supported? Can only be used for query?

**Comment by cbxiaorenwu** [comment]
> Update/Insert/Delete statement with `Multiple-Table` doesn't supported.

What if you want to do Update operation with sharding? Is sharding not supported? Can only be used for query?

**Comment by crazythinking** [comment]
same problem, how should I do when you need to update a table that has already used the sharding rule? only one way to specify table names with sharding directly?

**Comment by crazythinking** [comment]
![image](https://user-images.githubusercontent.com/5145888/93764880-7fc8d580-fc46-11ea-9cb4-4c4d9ba4df2b.png)
The Official documentation guidance can be supported "Update ... Where ...."

**Comment by Joker1995** [comment]
There is my situation:
the sharding configuration as follow:
![image](https://user-images.githubusercontent.com/12840349/109117816-74da1a00-777d-11eb-93eb-074d80696836.png)

the error message as follow:
### Error updating database.  Cause: org.apache.shardingsphere.underlying.common.exception.ShardingSphereException: Can not update sharding key, logic table: [ad_user], column: [org.apache.shardingsphere.sql.parser.sql.segment.dml.assignment.AssignmentSegment@6c68540a].
### The error may exist in com/xxxx/xxxx/mapper/UserMapper.java (best guess)
### The error may involve com.xxxx.xxx.mapper.UserMapper.updateById-Inline
### The error occurred while setting parameters
### SQL: UPDATE ad_user  SET code=?,  province_id=?, province_name=?, city_id=?, city_name=?, terminal=?, project_name=?,  site_id=?, tenant_id=?,    create_ts=?, update_ts=?  WHERE id=?
### Cause: org.apache.shardingsphere.underlying.common.exception.ShardingSphereException: Can not update sharding key, logic table: [ad_user], column: [org.apache.shardingsphere.sql.parser.sql.segment.dml.assignment.AssignmentSegment@6c68540a].

i don't modify multipart tables,why this problem occur?
