### ISSUE TITLE
Caused by: java.sql.SQLFeatureNotSupportedException: isValid

### ISSUE THREAD

**Issue by cielswift** [apache/shardingsphere#7564]
sharding 4.11
spring boot 2.3
mysql 5.7

Caused by: java.sql.SQLFeatureNotSupportedException: isValid
	at org.apache.shardingsphere.shardingjdbc.jdbc.unsupported.AbstractUnsupportedOperationConnection.isValid(AbstractUnsupportedOperationConnection.java:157) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
	at org.springframework.jdbc.core.JdbcTemplate$CloseSuppressingInvocationHandler.invoke(JdbcTemplate.java:1525) ~[spring-jdbc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at com.sun.proxy.$Proxy264.isValid(Unknown Source) ~[?:?]
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.isConnectionValid(DataSourceHealthIndicator.java:134) ~[spring-boot-actuator-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:328) ~[spring-jdbc-5.2.8.RELEASE.jar:5.2.8.RELEASE]

org.apache.shardingsphere.shardingjdbc.jdbc.core.connection.ShardingConnection  not implements  org.apache.shardingsphere.shardingjdbc.jdbc.unsupported.AbstractUnsupportedOperationConnection #isValid(arg)  so
 @Override
    public final boolean isValid(final int timeout) throws SQLException {
        throw new SQLFeatureNotSupportedException("isValid");
    }

An error occurred

org.apache.shardingsphere.shardingjdbc.jdbc.core.connection.ShardingConnection 没有实现org.apache.shardingsphere.shardingjdbc.jdbc.unsupported.AbstractUnsupportedOperationConnection的isValid 方法, 所以jdbc想要关闭的时候报错了;

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by SmiMi** [comment]
The same problem occurred

**Comment by icesugar** [comment]
Sharding Sphere does not support DB health check,  Turn off the actuate DB health  check.
Sharding Sphere 不支持数据库健康检查，关闭actuate 的数据库健康检查即可。
```yaml
management:
  health:
    db:
      enabled: false
```

**Comment by Orange-apples** [comment]
Have you solved this problem？
