### ISSUE TITLE
too many keyworks

### ISSUE THREAD

**Issue by YXxy1002** [apache/shardingsphere#7580]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Example codes for reproduce this issue (such as a github link).

There are too many keywords that cannot be use
role, position, point, unlock....
when i user these words in code will proruce 'table xxxx doesn't exist' exception
how to solve this problems?

**Comment by flycoolman** [comment]
Could you please share your original code with the error information?

**Comment by YXxy1002** [comment]
![image](https://user-images.githubusercontent.com/36941654/94016036-34e2c580-fde0-11ea-8aff-1e365b3d3062.png)
![image](https://user-images.githubusercontent.com/36941654/94016052-3ad8a680-fde0-11ea-95d5-96ec2d9831d6.png)
![image](https://user-images.githubusercontent.com/36941654/94016078-4330e180-fde0-11ea-857e-90f62d98fc47.png)
![image](https://user-images.githubusercontent.com/36941654/94016131-5643b180-fde0-11ea-82af-5f88b6658dca.png)
![image](https://user-images.githubusercontent.com/36941654/94016131-5643b180-fde0-11ea-82af-5f88b6658dca.png)

**Comment by YXxy1002** [comment]
`@Data
@TableName("t_test")
public class Test implements Serializable {
    private static final long serialVersionUID = 1L;
    @TableId("idx")
    private Long idx;

    @TableField("position")
    private String position;

    @TableField("Drole")
    private String role;

    @TableField("point")
    private String point;

    @TableField("Dunlock")
    private String unlock;

    @TableField("Duid")
    private String uid;
}`

`spring:
  aop:
    auto: true
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    props:
      sql:
        show: true
    sharding:
      default-data-source-name: normal
      tables:
        user_record_visit:
          actual-data-nodes: water.user_record_visit
          table-strategy:
            standard:
              sharding-column: Dvisit_time
              precise-algorithm-class-name: com.task.config.YYYYMMShardingAlgorithm # 单库月表
        t_visit_me:
          actual-data-nodes: water.t_visit_me
          table-strategy:
            standard:
              sharding-column: Duid
              precise-algorithm-class-name: com.task.config.UidShardingAlgorithm # 单库十表
        t_test:
          actual-data-nodes: water.t_test
          table-strategy:
            standard:
              sharding-column: Duid
              precise-algorithm-class-name: com.task.config.UidShardingAlgorithm # 单库十表
`
`names: normal,water
      normal:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql:
        username: 
        password: 
      water:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql:
        username: 
        password: 
`
`Test t = new Test();
        t.setUid("1230");
        t.setPoint("12312");
        t.setPosition("23321");
        t.setRole("321");
        t.setUnlock("213213213");
        testDao.insert(t);`
`org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: Table 'doger_water_db.t_test' doesn't exist
### The error may exist in com/task/modules/generator/dao/TestDao.java (best guess)
### The error may involve com.task.modules.generator.dao.TestDao.insert-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO t_test  ( Duid, Dunlock, Drole, position, point )  VALUES  ( ?, ?, ?, ?, ? )
### Cause: java.sql.SQLSyntaxErrorException: Table 'doger_water_db.t_test' doesn't exist
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Table 'doger_water_db.t_test' doesn't exist
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:234)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:74)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
	at com.sun.proxy.$Proxy105.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:271)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:58)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:61)
	at com.sun.proxy.$Proxy126.insert(Unknown Source)
	at com.task.modules.generator.FreeController.login(FreeController.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)`

**Comment by YXxy1002** [comment]
![1600866514(1)](https://user-images.githubusercontent.com/36941654/94016652-f6013f80-fde0-11ea-9e2c-820da4bf337e.jpg)
![image](https://user-images.githubusercontent.com/36941654/94016682-01ed0180-fde1-11ea-88e8-eb57ba2a96d5.png)
![image](https://user-images.githubusercontent.com/36941654/94016697-07e2e280-fde1-11ea-9b32-4fd06ccb4ff6.png)
![image](https://user-images.githubusercontent.com/36941654/94016706-0a453c80-fde1-11ea-8e49-9b8975a296b5.png)

**Comment by YXxy1002** [comment]
when i remove these fileds, it works success
![image](https://user-images.githubusercontent.com/36941654/94016830-3c569e80-fde1-11ea-8e73-5f4eb1c89d34.png)
![image](https://user-images.githubusercontent.com/36941654/94016846-3fea2580-fde1-11ea-892b-f8d1b7c2bb51.png)
![image](https://user-images.githubusercontent.com/36941654/94016854-424c7f80-fde1-11ea-9dab-c40852fa7703.png)

**Comment by flycoolman** [comment]
It seems that the table 'doger_water_db.t_test' was not created successfully.

bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Table 'doger_water_db.t_test' doesn't exist

**Comment by YXxy1002** [comment]
![image](https://user-images.githubusercontent.com/36941654/94021740-f0a6f380-fde6-11ea-9666-ec505a384e7f.png)
because it didnt use the shardingAlgorithm,is should use UidShardingAlgorithm so that tableName will be 't_test'+'0'='t_test_0'
when i delete the field 'position'  it will use UidShardingAlgorithm

**Comment by flycoolman** [comment]
Test other words in your code, like 'thisistestword'

**Comment by tristaZero** [comment]
Hi @flycoolman, Your concern is about the `keywords` of MySQL, isn't it?
Which version of ShardingSphere?
Actually, the master branch has a significant improvement in `keywords`. Would you like to have a try?

**Comment by jingshanglu** [comment]
@YXxy1002 @tristaZero It is because of the rewrite error for table, has been fixed on master branch, new version wiil be ok.

**Comment by YXxy1002** [comment]
has been solved when i use the latest version
![Uploading image.png…]()
