### ISSUE TITLE
Run HttpServerHandlerTest.assertShardingSphereJDBCTargetChannelReadStartSuccess throw exception

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#7706]
[WARN ] 11:05:32.916 [main] com.zaxxer.hikari.HikariConfig - HikariPool-1 - idleTimeout has been set but has no effect because the pool is operating as a fixed size pool.
[INFO ] 11:05:33.354 [main] ShardingSphere-metadata - Loading 0 tables' meta data.
[ERROR] 11:05:33.503 [ShardingSphere-ShardingScaling-execute-1] o.a.s.s.c.s.ScalingTaskScheduler - Inventory task execute failed.
org.apache.shardingsphere.scaling.core.exception.SyncTaskExecuteException: get estimated rows error.
	at org.apache.shardingsphere.scaling.core.job.task.inventory.InventoryDataScalingTask.getEstimatedRows(InventoryDataScalingTask.java:118)
	at org.apache.shardingsphere.scaling.core.job.task.inventory.InventoryDataScalingTask.start(InventoryDataScalingTask.java:87)
	at org.apache.shardingsphere.scaling.core.job.task.inventory.InventoryDataScalingTaskGroup.start(InventoryDataScalingTaskGroup.java:46)
	at org.apache.shardingsphere.scaling.core.execute.executor.AbstractShardingScalingExecutor.run(AbstractShardingScalingExecutor.java:53)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLException: Table "t1" not found; SQL statement:
SELECT COUNT(*) FROM t1  [42102-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.readTableOrView(Parser.java:5552)
	at org.h2.command.Parser.readTableFilter(Parser.java:1266)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1946)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:2095)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1940)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1755)
	at org.h2.command.Parser.parseSelect(Parser.java:1743)
	at org.h2.command.Parser.parsePrepared(Parser.java:449)
	at org.h2.command.Parser.parse(Parser.java:321)
	at org.h2.command.Parser.parse(Parser.java:293)
	at org.h2.command.Parser.prepareCommand(Parser.java:258)
	at org.h2.engine.Session.prepareLocal(Session.java:578)
	at org.h2.engine.Session.prepareCommand(Session.java:519)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:316)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at org.apache.shardingsphere.scaling.core.job.task.inventory.InventoryDataScalingTask.getEstimatedRows(InventoryDataScalingTask.java:111)
	... 10 common frames omitted

**Comment by Lucas-307** [comment]
Please assign to me.
