### ISSUE TITLE
sharding-jdbc how to reference variables in the yaml file

### ISSUE THREAD

**Issue by dwyane3011** [apache/shardingsphere#7729]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

dataSources:
ds0: !!com.alibaba.druid.pool.DruidDataSource
driverClassName: com.mysql.jdbc.Driver
url: ${resource.jdbc.url}
username: ${resource.jdbc.username}
password: ${resource.jdbc.password}

as indicated above, when I start the service：
2020-10-10 10:23:09.498 INFO 16164 --- [ main] com.alibaba.druid.pool.DruidDataSource : {dataSource-1} inited
2020-10-10 10:23:09.504 ERROR 16164 --- [eate-2004947954] com.alibaba.druid.pool.DruidDataSource : create connection error, url: ${resource.jdbc.url}

java.sql.SQLException: connect error, url ${resource.jdbc.url}, driverClass com.mysql.jdbc.Driver
at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1434) ~[druid-1.0.11.jar:1.0.11]
at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1857) ~[druid-1.0.11.jar:1.0.11]

**Comment by dwyane3011** [comment]
Somebody has used it？

**Comment by kimmking** [comment]
yaml configuration doesn't support placeholder now.
you can use spring-boot-starter for placeholder.
