### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by sunOnly** [apache/shardingsphere#7752]
## java.lang.NullPointerException

[ERROR] 19:30:41.082 [ShardingSphere-Command-15] o.a.s.s.f.c.CommandExecutorTask - Exception occur:
java.lang.NullPointerException: null
        at org.apache.shardingsphere.shardingproxy.frontend.mysql.MySQLErrPacketFactory.newInstance(MySQLErrPacketFactory.java:50)
        at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.createErrorPacket(MySQLComQueryPacketExecutor.java:92)
        at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:81)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:93)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by kimmking** [comment]
You should try the master branch for latest codes.
Your branch is out of date.
