### ISSUE TITLE
Add test case for MetaDataConnectionAdapter.getSchema with SPI

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#7761]

**Comment by jiang2015** [comment]
assin to me

**Comment by strongduanmu** [comment]
@jiang2015 Assigned, and welcome to join the SS community. 😀

**Comment by jiang2015** [comment]
sorry, I have no idea how to add the TestCase for this issue;
In 【MetaDataConnectionAdapterTest】  I add one function as follows：

```
private final DatabaseType **databaseType4Oracle** = DatabaseTypes.getTrunkDatabaseType("Oracle");

    @Test
    public void assertGetSchema4Oracle() throws SQLException {
        when(connection.getSchema()).thenReturn(TEST_SCHEMA);
        MetaDataConnectionAdapter connectionAdapter = new MetaDataConnectionAdapter(**databaseType4Oracle**, connection);
        assertThat(connectionAdapter.getSchema(), is(TEST_SCHEMA));
    }
```

when test, NullPointerException occured as follow 

java.lang.NullPointerException
	at org.apache.shardingsphere.infra.metadata.model.physical.jdbc.handler.impl.OracleJDBCSchemaHandler.getSchema(OracleJDBCSchemaHandler.java:46)
	at org.apache.shardingsphere.infra.metadata.model.physical.jdbc.MetaDataConnectionAdapter.getSchema(MetaDataConnectionAdapter.java:79)
	at org.apache.shardingsphere.infra.metadata.model.physical.jdbc.MetaDataConnectionAdapterTest.assertGetSchema4Oracle(MetaDataConnectionAdapterTest.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:68)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:74)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:161)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

the reason:
OracleJDBCSchemaHandler 

`    public String getSchema(final Connection connection) {
        try {
            return Optional.ofNullable(connection.getMetaData().getUserName()).map(String::toUpperCase).orElse(null);
        } catch (final SQLException ignored) {
            return null;
        }
    }`

connection.getMetaData() is null, this issue how to add testcase ,please give me advice ，thanks。

**Comment by taojintianxia** [comment]
@jiang2015 hi there

after check the source code of `OracleDatabaseMetaDataDialectHandler` we could find out that the handler implementation for Oracle is different than MySQL like followings : 

```java

    @Override
    public String getSchema(final Connection connection) {
        try {
            return Optional.ofNullable(connection.getMetaData().getUserName()).map(String::toUpperCase).orElse(null);
        } catch (final SQLException ignored) {
            return null;
        }
    }
``` 

in your test case, you just mock the getSchema, but the schema for Oracle is from userName in metadata. ^_^
