### ISSUE TITLE
CURRENT_TIMESTAMP SQL NullException

### ISSUE THREAD

**Issue by WilliamShoww** [apache/shardingsphere#7900]
### SQL contain CURRENT_TIMESTAMP will exception
```mysql
update a set
        
            a.enter_num = IF(a.enter_num + 1 < 0, 0, a.enter_num + 1),
	
        a.update_time = CURRENT_TIMESTAMP
        where id = 42908
```
line 6:8 no viable alternative at input 'CURRENT_TIMESTAMPwhere'
line 6:8 no viable alternative at input 'CURRENT_TIMESTAMPwhere'
2020-10-23 20:02:33,225 [http-nio-8084-exec-1] ERROR c.g.a.exception.ExceptionController [ExceptionController.java : 73] - Server is error: 
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.executor.ExecutorException: Error preparing statement.  Cause: java.lang.NullPointerException
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:92)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
	at com.sun.proxy.$Proxy118.update(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:287)
**But 3.x version not exception**

**Comment by strongduanmu** [comment]
@WilliamShoww Hi, thank you very much for your feedback. 😁 This exception is a SQL parsing bug in version 4.1.1 and has been fixed in the master branch. Please be patient and wait for the 5.x version, it will be released soon.

**Comment by WilliamShoww** [comment]
use CURRENT_TIMESTAMP() replace CURRENT_TIMESTAMP not exception.
