### ISSUE TITLE
ZLjava/lang/String cannot be converted to Ljava/lang/Object;)V 

### ISSUE THREAD

**Issue by booingdu** [apache/shardingsphere#8240]
Version：5.0.0-alpha

execute：select * from t_user t where t.phone=#{phone}   Exception

![image](https://user-images.githubusercontent.com/62653261/99772593-0403e000-2b46-11eb-91a3-6187acf81a2b.png)

```
2020-11-20 15:31:08.214 [1;31mERROR[m[http-nio-10024-exec-1] [36morg.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet][m : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V] with root cause
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V
	at org.apache.shardingsphere.driver.jdbc.adapter.AbstractConnectionAdapter.getConnections(AbstractConnectionAdapter.java:97) ~[shardingsphere-jdbc-core-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.infra.executor.sql.resourced.group.ResourceManagedExecuteGroupEngine.generateSQLExecuteGroups(ResourceManagedExecuteGroupEngine.java:66) ~[shardingsphere-infra-executor-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.infra.executor.sql.group.AbstractExecuteGroupEngine.generate(AbstractExecuteGroupEngine.java:58) ~[shardingsphere-infra-executor-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.getInputGroups(ShardingSpherePreparedStatement.java:216) ~[shardingsphere-jdbc-core-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.execute(ShardingSpherePreparedStatement.java:200) ~[shardingsphere-jdbc-core-5.0.0-alpha.jar:5.0.0-alpha]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59) ~[mybatis-3.4.4.jar:3.4.4]
	at com.sun.proxy.$Proxy257.execute(Unknown Source) ~[?:?]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63) ~[mybatis-3.4.4.jar:3.4.4]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79) ~[mybatis-3.4.4.jar:3.4.4]
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63) ~[mybatis-3.4.4.jar:3.4.4]
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324) ~[mybatis-3.4.4.jar:3.4.4]
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156) ~[mybatis-3.4.4.jar:3.4.4]
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109) ~[mybatis-3.4.4.jar:3.4.4]
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83) ~[mybatis-3.4.4.jar:3.4.4]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49) ~[mybatis-3.4.4.jar:3.4.4]
```

**Comment by kimmking** [comment]
The version of Guava in your project conflicts with ShardingSphere.
Please check and ensure Guava 29.0-jre with ShardingSphere 5.x.

**Comment by booingdu** [comment]
Guava 19.0 was used in the project, but when I saw that the Dependency of ShardingSphere was 18.0, I removed my own Guava dependency, but the error still occurred. @kimmking

**Comment by kimmking** [comment]
ShardingSphere must use Guava 29.0-jre

**Comment by wuguanyu** [comment]
Caused by: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V

shardingsphere-jdbc-core-spring-namespace 5.0.0

**Comment by wuguanyu** [comment]
@kimmking  Why ShardingSphere 5.x need guava 29.0-jre ?
guava  18.0 also have public static void checkArgument(boolean expression, @Nullable String errorMessageTemplate, @Nullable Object... errorMessageArgs) {
