### ISSUE TITLE
when i insert the data into the broadcast table, it throws the exception.

### ISSUE THREAD

**Issue by luckleemon** [apache/shardingsphere#8436]
**when i insert the data into the broadcasttable, it throws the exception.**

[INFO ] 14:16:44.882 [ShardingSphere-Command-14] ShardingSphere-SQL - Logic SQL: SET PROFILING=1;
[INFO ] 14:16:44.883 [ShardingSphere-Command-14] ShardingSphere-SQL - SQLStatement: MySQLSetStatement()
[INFO ] 14:16:44.883 [ShardingSphere-Command-14] ShardingSphere-SQL - Actual SQL: ds_0 ::: SET PROFILING=1;
[INFO ] 14:16:44.883 [ShardingSphere-Command-14] ShardingSphere-SQL - Actual SQL: ds_1 ::: SET PROFILING=1;
[INFO ] 14:16:44.913 [ShardingSphere-Command-15] ShardingSphere-SQL - Logic SQL: SHOW STATUS
[INFO ] 14:16:44.913 [ShardingSphere-Command-15] ShardingSphere-SQL - SQLStatement: MySQLShowOtherStatement()
[INFO ] 14:16:44.913 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SHOW STATUS
[INFO ] 14:16:44.954 [ShardingSphere-Command-0] ShardingSphere-SQL - Logic SQL: SHOW STATUS
[INFO ] 14:16:44.955 [ShardingSphere-Command-0] ShardingSphere-SQL - SQLStatement: MySQLShowOtherStatement()
[INFO ] 14:16:44.955 [ShardingSphere-Command-0] ShardingSphere-SQL - Actual SQL: ds_0 ::: SHOW STATUS
[ERROR] 14:16:45.009 [ShardingSphere-Command-1] o.a.s.p.f.c.CommandExecutorTask - Exception occur:
java.util.NoSuchElementException: null
        at java.util.ArrayList$Itr.next(ArrayList.java:854)
        at org.apache.shardingsphere.sharding.route.engine.condition.engine.impl.InsertClauseShardingConditionEngine.createShardingCondition(InsertClauseShardingConditionEngine.java:91)
        at org.apache.shardingsphere.sharding.route.engine.condition.engine.impl.InsertClauseShardingConditionEngine.createShardingConditionsWithInsertValues(InsertClauseShardingConditionEngine.java:72)
        at org.apache.shardingsphere.sharding.route.engine.condition.engine.impl.InsertClauseShardingConditionEngine.createShardingConditions(InsertClauseShardingConditionEngine.java:62)
        at org.apache.shardingsphere.sharding.route.engine.condition.engine.impl.InsertClauseShardingConditionEngine.createShardingConditions(InsertClauseShardingConditionEngine.java:52)
        at org.apache.shardingsphere.sharding.route.engine.ShardingSQLRouter.createShardingConditions(ShardingSQLRouter.java:80)
        at org.apache.shardingsphere.sharding.route.engine.ShardingSQLRouter.createRouteContext(ShardingSQLRouter.java:64)
        at org.apache.shardingsphere.sharding.route.engine.ShardingSQLRouter.createRouteContext(ShardingSQLRouter.java:55)
        at org.apache.shardingsphere.infra.route.engine.impl.PartialSQLRouteExecutor.route(PartialSQLRouteExecutor.java:59)
        at org.apache.shardingsphere.infra.route.engine.SQLRouteEngine.route(SQLRouteEngine.java:57)
        at org.apache.shardingsphere.infra.context.kernel.KernelProcessor.generateExecutionContext(KernelProcessor.java:52)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:77)
        at org.apache.shardingsphere.proxy.backend.text.query.QueryBackendHandler.execute(QueryBackendHandler.java:61)
        at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:62)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:100)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:76)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

what is the problem?

**Comment by tuohai666** [comment]
Please fill in the template:

```

## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

```

**Comment by tristaZero** [comment]
@luckleemon 
1. If this table is not a broadcast table, does `insert` work well?
2. Have you ever tried to execute other SQLs, like `select` with `broadcast table`?

**Comment by terrymanu** [comment]
Closed because of no response
