### ISSUE TITLE
Application does not start when using data masking with sharding.

### ISSUE THREAD

**Issue by Lonor** [apache/shardingsphere#8503]
## Bug Report

I followed the [official document to configure SpringBoot app with ShardingSphere](https://shardingsphere.apache.org/document/legacy/4.x/document/cn/manual/sharding-jdbc/configuration/config-spring-boot/#数据分片--数据脱敏) to **use the encryption and sharding together**. A problem occurred.

### Which version of ShardingSphere did you use?
4.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 

### Expected behavior
The SpringBoot application starting and running well.

### Actual behavior
Exception happened. Here's the log:
```log
020-12-04 14:59:16.023 [main] ERROR org.springframework.boot.SpringApplication - Application run failed 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.userServiceImpl': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'spring.shardingsphere.encrypt.encryptors.encryptor_aes.props.aes.key.value' in value "${spring.shardingsphere.encrypt.encryptors.encryptor_aes.props.aes.key.value}"
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:380)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1411)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$1(AbstractBeanFactory.java:356)
	at org.springframework.cloud.context.scope.GenericScope$BeanLifecycleWrapper.getBean(GenericScope.java:389)
	at org.springframework.cloud.context.scope.GenericScope.get(GenericScope.java:186)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:353)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1105)
	at org.springframework.cloud.context.scope.refresh.RefreshScope.eagerlyInitialize(RefreshScope.java:134)
	at org.springframework.cloud.context.scope.refresh.RefreshScope.start(RefreshScope.java:125)
	at org.springframework.cloud.context.scope.refresh.RefreshScope.onApplicationEvent(RefreshScope.java:119)
	at org.springframework.cloud.context.scope.refresh.RefreshScope.onApplicationEvent(RefreshScope.java:73)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:896)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:163)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.test.consumer.server.ConsumerServerApplication.main(ConsumerServerApplication.java:28)
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'spring.shardingsphere.encrypt.encryptors.encryptor_aes.props.aes.key.value' in value "${spring.shardingsphere.encrypt.encryptors.encryptor_aes.props.aes.key.value}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:172)
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:124)
	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:237)
	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:211)
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.lambda$processProperties$0(PropertySourcesPlaceholderConfigurer.java:175)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:851)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1188)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
	... 28 common frames omitted
```

### Reason analyze (If you can)
When the SpringBoot app starting, ShardingSphere uses the key `spring.shardingsphere.encrypt.encryptors.encryptor_aes.props.aes.key.value` to set up. However, after started, it uses the other key `spring.shardingsphere.sharding.encrypt-rule.encryptors.encryptor_aes.props.aes.key.value`  to take part in encryption.

The weird thing is this log:
```
2020-12-04 14:59:04.735 [main] INFO  o.a.shardingsphere.core.log.ConfigurationLogger - ShardingRuleConfiguration:
encryptRule:
  encryptors:
    encryptor_aes:
      props:
        aes.key.value: '123456'
      type: aes
```
It actually got the value with `spring.shardingsphere.sharding.encrypt-rule.encryptors.encryptor_aes.props.aes.key.value` key.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
SpringBoot config file (it just used one data source):

```properties
# _DataSource_
spring.shardingsphere.datasource.names=ds-2020
spring.shardingsphere.datasource.ds-2020.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.ds-2020.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.ds-2020.jdbc-url=jdbc:mysql://127.0.0.1:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
spring.shardingsphere.datasource.ds-2020.username=root
spring.shardingsphere.datasource.ds-2020.password=root

# _Sharding_
spring.shardingsphere.sharding.tables.user.actual-data-nodes=ds-2020.user_$->{0..1}
spring.shardingsphere.sharding.tables.user.table-strategy.inline.sharding-column=id
spring.shardingsphere.sharding.tables.user.table-strategy.inline.algorithm-expression=user_$->{id % 2}

# _Encryption with Sharding_
spring.shardingsphere.props.query.with.cipher.column=true
spring.shardingsphere.sharding.encrypt-rule.encryptors.encryptor_aes.type=aes
# _these two lines below cause problems:_
# spring.shardingsphere.encrypt.encryptors.encryptor_aes.props.aes.key.value=123456
spring.shardingsphere.sharding.encrypt-rule.encryptors.encryptor_aes.props.aes.key.value=123456
spring.shardingsphere.sharding.encrypt-rule.tables.user.columns.phone.plainColumn=phone
spring.shardingsphere.sharding.encrypt-rule.tables.user.columns.phone.cipherColumn=cipher_phone
spring.shardingsphere.sharding.encrypt-rule.tables.user.columns.phone.encryptor=encryptor_aes
```

My solution now is adding both line to the config file and it works. If either of the two rows is missing, SpringBoot application cannot be started.

**Comment by terrymanu** [comment]
Please read 4.x doc if you are using version 4.x

**Comment by Lonor** [comment]
> Please read 4.x doc if you are using version 4.x

I read the 4.x version docs exactly.

**Comment by Lonor** [comment]
Please try this configuration and confirm whether this problem is **invalid** or not. Thanks.
