### ISSUE TITLE
sharding replica query exception: java.lang.reflect.InvocationTargetException: null

### ISSUE THREAD

**Issue by suikenungleung** [apache/shardingsphere#8514]
Spring Boot: 2.3.6
ShardingSphere-JDBC: 5.0.0-alph

The configuration is as follows:

Example 1

Refer to the official example: [application-sharding-replica-query.properties](https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/sharding-example/sharding-spring-boot-mybatis-example/src/main/resources/application-sharding-replica-query.properties)

```
spring.shardingsphere.datasource.names=ds-p0,ds-p0-r0,ds-p0-r1,ds-p1,ds-p1-r0,ds-p1-r1

spring.shardingsphere.datasource.common.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.common.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.common.username=root
spring.shardingsphere.datasource.common.password=123456

spring.shardingsphere.datasource.ds-p0.jdbc-url=jdbc:mysql://192.168.177.135:3306/sugus?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
spring.shardingsphere.datasource.ds-p0-r0.jdbc-url=jdbc:mysql://192.168.177.135:3307/sugus?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
spring.shardingsphere.datasource.ds-p0-r1.jdbc-url=jdbc:mysql://192.168.177.135:3308/sugus?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8

spring.shardingsphere.datasource.ds-p1.jdbc-url=jdbc:mysql://192.168.177.135:3310/sugus?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
spring.shardingsphere.datasource.ds-p1-r0.jdbc-url=jdbc:mysql://192.168.177.135:3311/sugus?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
spring.shardingsphere.datasource.ds-p1-r1.jdbc-url=jdbc:mysql://192.168.177.135:3312/sugus?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8

spring.shardingsphere.rules.sharding.tables.user.actual-data-nodes=ds-$->{0..1}.user_$->{0..2}

spring.shardingsphere.rules.sharding.binding-tables=user
spring.shardingsphere.rules.sharding.broadcast-tables=address

spring.shardingsphere.rules.sharding.tables.user.key-generate-strategy.column=id
spring.shardingsphere.rules.sharding.tables.user.key-generate-strategy.key-generator-name=snowflake

spring.shardingsphere.rules.sharding.tables.user.table-strategy.standard.sharding-column=id
spring.shardingsphere.rules.sharding.tables.user.table-strategy.standard.sharding-algorithm-name=user-inline

spring.shardingsphere.rules.sharding.tables.user.table-strategy.inline.sharding-column=id
spring.shardingsphere.rules.sharding.tables.user.table-strategy.inline.algorithm-expression=user_$->{id % 3}

spring.shardingsphere.rules.sharding.default-database-strategy.inline.sharding-column=id
spring.shardingsphere.rules.sharding.default-database-strategy.inline.algorithm-expression=ds-$->{id % 2}

spring.shardingsphere.rules.sharding.key-generators.snowflake.type=SNOWFLAKE
spring.shardingsphere.rules.sharding.key-generators.snowflake.props.worker-id=123

spring.shardingsphere.rules.replica-query.load-balancers.robin-0.type=ROUND_ROBIN
spring.shardingsphere.rules.replica-query.load-balancers.robin-0.props.sql-show=true
spring.shardingsphere.rules.replica-query.data-sources.ds-0.primary-data-source-name=ds-p0
spring.shardingsphere.rules.replica-query.data-sources.ds-0.replica-data-source-names=ds-p0-r0,ds-p0-r1
spring.shardingsphere.rules.replica-query.data-sources.ds-0.load-balancer-name=robin-0

spring.shardingsphere.rules.replica-query.load-balancers.robin-1.type=ROUND_ROBIN
spring.shardingsphere.rules.replica-query.load-balancers.robin-1.props.sql-show=true
spring.shardingsphere.rules.replica-query.data-sources.ds-1.primary-data-source-name=ds-p1
spring.shardingsphere.rules.replica-query.data-sources.ds-1.replica-data-source-names=ds-p1-r0,ds-p1-r1
spring.shardingsphere.rules.replica-query.data-sources.ds-1.load-balancer-name=robin-1
```

Runtime error: java.lang.reflect.InvocationTargetException: null.

Example 2

combined: [application-replica-query.properties](https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/sharding-example/sharding-spring-boot-mybatis-example/src/main/resources/application-replica-query.properties) and [application-sharding-databases-tables.properties](https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/sharding-example/sharding-spring-boot-mybatis-example/src/main/resources/application-sharding-databases-tables.properties) operating normally and read and write normally.

```
spring.shardingsphere.datasource.names=ds-p0,ds-p0-r0,ds-p0-r1,ds-p1,ds-p1-r0,ds-p1-r1

spring.shardingsphere.datasource.common.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.common.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.common.username=root
spring.shardingsphere.datasource.common.password=123456

spring.shardingsphere.datasource.ds-p0.jdbc-url=jdbc:mysql://192.168.177.135:3306/sugus?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
spring.shardingsphere.datasource.ds-p0-r0.jdbc-url=jdbc:mysql://192.168.177.135:3307/sugus?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
spring.shardingsphere.datasource.ds-p0-r1.jdbc-url=jdbc:mysql://192.168.177.135:3308/sugus?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8

spring.shardingsphere.datasource.ds-p1.jdbc-url=jdbc:mysql://192.168.177.135:3310/sugus?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
spring.shardingsphere.datasource.ds-p1-r0.jdbc-url=jdbc:mysql://192.168.177.135:3311/sugus?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
spring.shardingsphere.datasource.ds-p1-r1.jdbc-url=jdbc:mysql://192.168.177.135:3312/sugus?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8

spring.shardingsphere.rules.sharding.tables.user.actual-data-nodes=ds-$->{0..1}.user_$->{0..2}

spring.shardingsphere.rules.sharding.binding-tables=user
#spring.shardingsphere.rules.sharding.broadcast-tables=address

spring.shardingsphere.rules.sharding.tables.user.key-generate-strategy.column=id
spring.shardingsphere.rules.sharding.tables.user.key-generate-strategy.key-generator-name=snowflake

spring.shardingsphere.rules.sharding.tables.user.table-strategy.standard.sharding-column=id
spring.shardingsphere.rules.sharding.tables.user.table-strategy.standard.sharding-algorithm-name=user-inline

spring.shardingsphere.rules.sharding.sharding-algorithms.user-inline.type=INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.user-inline.props.algorithm-expression=user_$->{id % 3}

spring.shardingsphere.rules.sharding.default-database-strategy.standard.sharding-column=id
spring.shardingsphere.rules.sharding.default-database-strategy.standard.sharding-algorithm-name=database-inline

spring.shardingsphere.rules.sharding.sharding-algorithms.database-inline.type=INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.database-inline.props.algorithm-expression=ds-$->{id % 2}

spring.shardingsphere.rules.sharding.key-generators.snowflake.type=SNOWFLAKE
spring.shardingsphere.rules.sharding.key-generators.snowflake.props.worker-id=123

spring.shardingsphere.rules.replica-query.load-balancers.robin-0.type=ROUND_ROBIN
spring.shardingsphere.rules.replica-query.load-balancers.robin-0.props.sql-show=true
spring.shardingsphere.rules.replica-query.data-sources.ds-0.primary-data-source-name=ds-p0
spring.shardingsphere.rules.replica-query.data-sources.ds-0.replica-data-source-names=ds-p0-r0,ds-p0-r1
spring.shardingsphere.rules.replica-query.data-sources.ds-0.load-balancer-name=robin-0

spring.shardingsphere.rules.replica-query.load-balancers.robin-1.type=ROUND_ROBIN
spring.shardingsphere.rules.replica-query.load-balancers.robin-1.props.sql-show=true
spring.shardingsphere.rules.replica-query.data-sources.ds-1.primary-data-source-name=ds-p1
spring.shardingsphere.rules.replica-query.data-sources.ds-1.replica-data-source-names=ds-p1-r0,ds-p1-r1
spring.shardingsphere.rules.replica-query.data-sources.ds-1.load-balancer-name=robin-1
```

Two questions:
1. Example 1 why wrong.
2. Example 2 configuration is it right or not, whether exist hidden danger.

**Comment by tristaZero** [comment]
Hi, @suikenungleung,
Could you provide more detailed log about the following exception?
> Runtime error: java.lang.reflect.InvocationTargetException: null.

**Comment by suikenungleung** [comment]
@tristaZero 

```
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_261]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_261]
	at org.apache.shardingsphere.spring.boot.util.PropertyUtil.v2(PropertyUtil.java:111) ~[shardingsphere-jdbc-spring-boot-starter-infra-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.spring.boot.util.PropertyUtil.handle(PropertyUtil.java:75) ~[shardingsphere-jdbc-spring-boot-starter-infra-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.spring.boot.registry.AbstractAlgorithmProvidedBeanRegistry.registerBean(AbstractAlgorithmProvidedBeanRegistry.java:50) ~[shardingsphere-jdbc-spring-boot-starter-infra-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.sharding.spring.boot.algorithm.ShardingAlgorithmProvidedBeanRegistry.postProcessBeanDefinitionRegistry(ShardingAlgorithmProvidedBeanRegistry.java:38) ~[shardingsphere-sharding-spring-boot-starter-5.0.0-alpha.jar:5.0.0-alpha]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:280) ~[spring-context-5.2.11.RELEASE.jar:5.2.11.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:126) ~[spring-context-5.2.11.RELEASE.jar:5.2.11.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:707) ~[spring-context-5.2.11.RELEASE.jar:5.2.11.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:533) ~[spring-context-5.2.11.RELEASE.jar:5.2.11.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.6.RELEASE.jar:2.3.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.3.6.RELEASE.jar:2.3.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.3.6.RELEASE.jar:2.3.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405) [spring-boot-2.3.6.RELEASE.jar:2.3.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.3.6.RELEASE.jar:2.3.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.6.RELEASE.jar:2.3.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.6.RELEASE.jar:2.3.6.RELEASE]
	at com.lrq.sharding.ShardingApplication.main(ShardingApplication.java:12) [classes/:na]
Caused by: java.util.NoSuchElementException: No value bound
	at org.springframework.boot.context.properties.bind.BindResult.get(BindResult.java:55) ~[spring-boot-2.3.6.RELEASE.jar:2.3.6.RELEASE]
	... 20 common frames omitted

Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
	at org.springframework.util.ReflectionUtils.rethrowRuntimeException(ReflectionUtils.java:147)
	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:821)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:325)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at com.lrq.sharding.ShardingApplication.main(ShardingApplication.java:12)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.shardingsphere.spring.boot.util.PropertyUtil.v2(PropertyUtil.java:111)
	at org.apache.shardingsphere.spring.boot.util.PropertyUtil.handle(PropertyUtil.java:75)
	at org.apache.shardingsphere.spring.boot.registry.AbstractAlgorithmProvidedBeanRegistry.registerBean(AbstractAlgorithmProvidedBeanRegistry.java:50)
	at org.apache.shardingsphere.sharding.spring.boot.algorithm.ShardingAlgorithmProvidedBeanRegistry.postProcessBeanDefinitionRegistry(ShardingAlgorithmProvidedBeanRegistry.java:38)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:280)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:126)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:707)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:533)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	... 3 more
Caused by: java.util.NoSuchElementException: No value bound
	at org.springframework.boot.context.properties.bind.BindResult.get(BindResult.java:55)
	... 20 more

Process finished with exit code 1
```

**Comment by tristaZero** [comment]
Hi @suikenungleung 
I could not find any definition of `user-inline` in your example 1, while it is defined in example 2.

```xml
spring.shardingsphere.rules.sharding.tables.user.table-strategy.standard.sharding-column=id
spring.shardingsphere.rules.sharding.tables.user.table-strategy.standard.sharding-algorithm-name=user-inline
```

**Comment by tristaZero** [comment]
Hi @yu199195 
I suggest looking at the `catch exception` of `PropertyUtil` and throwing a wrapped exception to users.

**Comment by yu199195** [comment]
@suikenungleung  we fix it in  #8331 ， you can see #8459

**Comment by suikenungleung** [comment]
@tristaZero 

According to [application-sharding-replica-query.properties](https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/sharding-example/sharding-spring-boot-mybatis-example/src/main/resources/application-sharding-replica-query.properties) Delete redundant configuration,The same error after modification.

```
spring.shardingsphere.datasource.names=ds-p0,ds-p0-r0,ds-p0-r1,ds-p1,ds-p1-r0,ds-p1-r1

spring.shardingsphere.datasource.common.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.common.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.common.username=root
spring.shardingsphere.datasource.common.password=123456

spring.shardingsphere.datasource.ds-p0.jdbc-url=jdbc:mysql://192.168.177.135:3306/sugus?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
spring.shardingsphere.datasource.ds-p0-r0.jdbc-url=jdbc:mysql://192.168.177.135:3307/sugus?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
spring.shardingsphere.datasource.ds-p0-r1.jdbc-url=jdbc:mysql://192.168.177.135:3308/sugus?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8

spring.shardingsphere.datasource.ds-p1.jdbc-url=jdbc:mysql://192.168.177.135:3310/sugus?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
spring.shardingsphere.datasource.ds-p1-r0.jdbc-url=jdbc:mysql://192.168.177.135:3311/sugus?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
spring.shardingsphere.datasource.ds-p1-r1.jdbc-url=jdbc:mysql://192.168.177.135:3312/sugus?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8

spring.shardingsphere.rules.sharding.tables.user.actual-data-nodes=ds-$->{0..1}.user_$->{0..2}

spring.shardingsphere.rules.sharding.binding-tables=user
#spring.shardingsphere.rules.sharding.broadcast-tables=address

spring.shardingsphere.rules.sharding.tables.user.key-generate-strategy.column=id
spring.shardingsphere.rules.sharding.tables.user.key-generate-strategy.key-generator-name=snowflake

spring.shardingsphere.rules.sharding.tables.user.table-strategy.inline.sharding-column=id
spring.shardingsphere.rules.sharding.tables.user.table-strategy.inline.algorithm-expression=user_$->{id % 3}

spring.shardingsphere.rules.sharding.default-database-strategy.inline.sharding-column=id
spring.shardingsphere.rules.sharding.default-database-strategy.inline.algorithm-expression=ds-$->{id % 2}

spring.shardingsphere.rules.sharding.key-generators.snowflake.type=SNOWFLAKE
spring.shardingsphere.rules.sharding.key-generators.snowflake.props.worker-id=123

spring.shardingsphere.rules.replica-query.data-sources.ds-0.primary-data-source-name=ds-p0
spring.shardingsphere.rules.replica-query.data-sources.ds-0.replica-data-source-names=ds-p0-r0,ds-p0-r1

spring.shardingsphere.rules.replica-query.data-sources.ds-1.primary-data-source-name=ds-p1
spring.shardingsphere.rules.replica-query.data-sources.ds-1.replica-data-source-names=ds-p1-r0,ds-p1-r1
```

**Comment by tristaZero** [comment]
Hi @suikenungleung ,

> According to application-sharding-replica-query.properties Delete redundant configuration,The same error after modification.

That's a misunderstanding. What I want you to try is to use the following items to add `sharding algorithm` configurations.

```xml
spring.shardingsphere.rules.sharding.sharding-algorithms.database-inline.type=INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.database-inline.props.algorithm-expression=ds-$->{id % 2}
```

**Comment by suikenungleung** [comment]
```
...

spring.shardingsphere.rules.sharding.tables.user.actual-data-nodes=ds-$->{0..1}.user_$->{0..2}

spring.shardingsphere.rules.sharding.binding-tables=user
#spring.shardingsphere.rules.sharding.broadcast-tables=address

spring.shardingsphere.rules.sharding.tables.user.key-generate-strategy.column=id
spring.shardingsphere.rules.sharding.tables.user.key-generate-strategy.key-generator-name=snowflake

spring.shardingsphere.rules.sharding.tables.user.table-strategy.inline.sharding-column=id
spring.shardingsphere.rules.sharding.tables.user.table-strategy.inline.sharding-algorithm-name=user-inline

spring.shardingsphere.rules.sharding.sharding-algorithms.user-inline.type=INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.user-inline.props.algorithm-expression=user_$->{id % 3}

spring.shardingsphere.rules.sharding.default-database-strategy.inline.sharding-column=id
spring.shardingsphere.rules.sharding.default-database-strategy.inline.sharding-algorithm-name=database-inline

spring.shardingsphere.rules.sharding.sharding-algorithms.database-inline.type=INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.database-inline.props.algorithm-expression=ds-$->{id % 2}

spring.shardingsphere.rules.sharding.key-generators.snowflake.type=SNOWFLAKE
spring.shardingsphere.rules.sharding.key-generators.snowflake.props.worker-id=123

spring.shardingsphere.rules.replica-query.load-balancers.robin-0.type=ROUND_ROBIN
spring.shardingsphere.rules.replica-query.load-balancers.robin-0.props.sql-show=true
spring.shardingsphere.rules.replica-query.data-sources.ds-0.primary-data-source-name=ds-p0
spring.shardingsphere.rules.replica-query.data-sources.ds-0.replica-data-source-names=ds-p0-r0,ds-p0-r1
spring.shardingsphere.rules.replica-query.data-sources.ds-0.load-balancer-name=robin-0

spring.shardingsphere.rules.replica-query.load-balancers.robin-1.type=ROUND_ROBIN
spring.shardingsphere.rules.replica-query.load-balancers.robin-1.props.sql-show=true
spring.shardingsphere.rules.replica-query.data-sources.ds-1.primary-data-source-name=ds-p1
spring.shardingsphere.rules.replica-query.data-sources.ds-1.replica-data-source-names=ds-p1-r0,ds-p1-r1
spring.shardingsphere.rules.replica-query.data-sources.ds-1.load-balancer-name=robin-1
```

Configuration is running normally, But the data is distributed equally to all tables.

Insert 40 data, all tables have been inserted 40 data. This is not correct.

One more question? [application-sharding-replica-query.properties](https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/sharding-example/sharding-spring-boot-mybatis-example/src/main/resources/application-sharding-replica-query.properties) Configuration  `spring.shardingsphere.rules.sharding.tables.t_order.table-strategy.inline.sharding-colum` This `inline` what is it? I did not see in the configuration item description.

```
dataSources: # Omit data source configuration
rules:
- !SHARDING
  tables: # Sharding table configuration
    <logic-table-name> (+): # Logic table name
      actualDataNodes (?): # Describe data source names and actual tables, delimiter as point, multiple data nodes separated with comma, support inline expression. Absent means sharding databases only.
      databaseStrategy (?): # Databases sharding strategy, use default databases sharding strategy if absent. sharding strategy below can choose only one.
        standard: # For single sharding column scenario
          shardingColumn: # Sharding column name
          shardingAlgorithmName: # Sharding algorithm name
        complex: # For multiple sharding columns scenario
          shardingColumns: # Sharding column names, multiple columns separated with comma
          shardingAlgorithmName: # Sharding algorithm name
        hint: # Sharding by hint
          shardingAlgorithmName: # Sharding algorithm name
        none: # Do not sharding
      tableStrategy: # Tables sharding strategy, same as database sharding strategy
      keyGenerateStrategy: # Key generator strategy
        column: # Column name of key generator
        keyGeneratorName: # Key generator name
  autoTables: # Auto Sharding table configuration
    t_order_auto: # Logic table name
      actualDataSources (?): # Data source names
      shardingStrategy: # Sharding strategy
        standard: # For single sharding column scenario
          shardingColumn: # Sharding column name
          shardingAlgorithmName: # Auto sharding algorithm name
  bindingTables (+): # Binding tables
    - <logic_table_name_1, logic_table_name_2, ...> 
  broadcastTables (+): # Broadcast tables
    - <table-name>
  defaultDatabaseStrategy: # Default strategy for database sharding
  defaultTableStrategy: # Default strategy for table sharding
  defaultKeyGenerateStrategy: # Default Key generator strategy

  # Sharding algorithm configuration
  shardingAlgorithms:
    <sharding-algorithm-name> (+): # Sharding algorithm name
      type: # Sharding algorithm type
      props: # Sharding algorithm properties
      # ...
  
  # Key generate algorithm configuration
  keyGenerators:
    <key-generate-algorithm-name> (+): # Key generate algorithm name
      type: # Key generate algorithm type
      props: # Key generate algorithm properties
      # ...

props:
  # ...
```

**Comment by tristaZero** [comment]
Hi,
FYI, [SpringBoot configuration](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/configuration/spring-boot-starter/sharding/)

**Comment by suikenungleung** [comment]
> 嗨，
> 仅供参考，[SpringBoot配置](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/configuration/spring-boot-starter/sharding/)

Ok! Thank you and try again when the new version is released.
