### ISSUE TITLE
shardingjdbc 5.0.0-alpha namespace After configuring the read-write separation, the null pointer is reported when the item is started

### ISSUE THREAD

**Issue by wxp651** [apache/shardingsphere#8534]
## Bug Report
When I configured read-write separation, an error occurred when I started the project. There is a bean org.redisson.config . config ා 0 $created ා 0 I did not actively import this bean, and null pointer was reported in getbeandefinition() method
**For English only**, other languages will not accept.
class ShardingSphereAlgorithmBeanRegistry the line 25

	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at org.apache.shardingsphere.spring.namespace.registry.ShardingSphereAlgorithmBeanRegistry.getAlgorithmBeanReferences(ShardingSphereAlgorithmBeanRegistry.java:48)
	at org.apache.shardingsphere.replicaquery.spring.namespace.parser.ReplicaQueryRuleBeanDefinitionParser.parseInternal(ReplicaQueryRuleBeanDefinitionParser.java:47)
	at org.springframework.beans.factory.xml.AbstractBeanDefinitionParser.parse(AbstractBeanDefinitionParser.java:61)
	at org.springframework.beans.factory.xml.NamespaceHandlerSupport.parse(NamespaceHandlerSupport.java:74)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1411)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1401)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:168)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:138)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:94)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:508)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:392)
	... 58 common frames omitted

**Comment by menghaoranss** [comment]
Please show your configurations.

**Comment by tristaZero** [comment]
Hi @wxp651 ,
Could you check your configuration with [Examples](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-proxy-example)?

**Comment by wxp651** [comment]
> 请显示您的配置。

There are too many configuration files. Here, only the relevant ones are displayed

1、rediscluster

[shardingjdbc.docx](https://github.com/apache/shardingsphere/files/5664065/shardingjdbc.docx)
[spring-daorw.docx](https://github.com/apache/shardingsphere/files/5664066/spring-daorw.docx)

-config.xml

<redisson:client id="redissonClient" netty-threads="20" threads="20">
<redisson:cluster-servers
                idle-connection-timeout="${redisson.idleConnectionTime}"
                connect-timeout="${redisson.connectTimeout}"
                timeout="${redisson.timeout}"
                retry-attempts="${redisson.retryAttempts}"
                retry-interval="${redisson.retryInterval}"
                scan-interval="${redisson.scanInterval}">
<redisson:node-address value="${redisson.hostAndPort1}" />
<redisson:node-address value="${redisson.hostAndPort2}" />
<redisson:node-address value="${redisson.hostAndPort3}" />
<redisson:node-address value="${redisson.hostAndPort4}" />
<redisson:node-address value="${redisson.hostAndPort5}" />
<redisson:node-address value="${redisson.hostAndPort6}" />
</redisson:cluster-servers>
</redisson:client>

**Comment by wxp651** [comment]
> @ wxp651，您好：
> 您可以使用“[示例”](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-proxy-example)检查您的配置吗？

Yes, I wrote it according to the example  ，but it just can't start

**Comment by tristaZero** [comment]
Hi,

Do you think [#8555](https://github.com/apache/shardingsphere/issues/8555) can solve your issue?

**Comment by terrymanu** [comment]
Closed because of no response
