### ISSUE TITLE
no viable alternative at input 

### ISSUE THREAD

**Issue by zosimer** [apache/shardingsphere#8623]
line 9:13 no viable alternative at input 'selectmember_id,mobile,nickname,`name`,icard,photo,sex,birthday,platform,province,city,district,college_id,college_name,member_state,member_type,invite_code,rank_points,pay_points,money,frozen_money,gold,frozen_gold,login_ip,login_date,login_flag,sign,is_special,is_service,remarks,del_flag,create_by,create_date,update_by,update_datefrommember'
line 9:13 no viable alternative at input 'selectmember_id,mobile,nickname,`name`,icard,photo,sex,birthday,platform,province,city,district,college_id,college_name,member_state,member_type,invite_code,rank_points,pay_points,money,frozen_money,gold,frozen_gold,login_ip,login_date,login_flag,sign,is_special,is_service,remarks,del_flag,create_by,create_date,update_by,update_datefrommember'
[ERROR] 14:33:09.333 [ShardingSphere-Command-0] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
org.antlr.v4.runtime.misc.ParseCancellationException: null
        at org.antlr.v4.runtime.BailErrorStrategy.recover(BailErrorStrategy.java:51)
        at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser.select(MySQLStatementParser.java:3631)
        at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser.execute(MySQLStatementParser.java:936)
        at org.apache.shardingsphere.sql.parser.mysql.parser.MySQLParser.parse(MySQLParser.java:37)
        at org.apache.shardingsphere.sql.parser.core.parser.SQLParserExecutor.twoPhaseParse(SQLParserExecutor.java:84)
        at org.apache.shardingsphere.sql.parser.core.parser.SQLParserExecutor.parse(SQLParserExecutor.java:59)
        at org.apache.shardingsphere.sql.parser.core.parser.SQLParserExecutor.parse(SQLParserExecutor.java:53)
        at org.apache.shardingsphere.sql.parser.api.SQLParserEngine.parse(SQLParserEngine.java:46)
        at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserEngine.parse(SQLStatementParserEngine.java:65)
        at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserEngine.parse(SQLStatementParserEngine.java:53)
        at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine.parse0(ShardingSphereSQLParserEngine.java:74)
        at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine.parse(ShardingSphereSQLParserEngine.java:60)
        at org.apache.shardingsphere.proxy.backend.text.TextProtocolBackendHandlerFactory.newInstance(TextProtocolBackendHandlerFactory.java:63)
        at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.<init>(MySQLComQueryPacketExecutor.java:54)
        at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecutorFactory.newInstance(MySQLCommandExecutorFactory.java:70)
        at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandExecutor(MySQLCommandExecuteEngine.java:60)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:99)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:76)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.antlr.v4.runtime.NoViableAltException: null
        at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:2026)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:467)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:393)
        at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser.select(MySQLStatementParser.java:3594)
        ... 19 common frames omitted

**Comment by zosimer** [comment]
Shardingproxy5.0 SQL parsing removes the space, resulting in data errors, but mybatis's SQL is correct

**Comment by zosimer** [comment]
![image](https://user-images.githubusercontent.com/19589632/102180390-c0518b80-3ee3-11eb-9b71-c667f5a29344.png)

**Comment by zosimer** [comment]
![image](https://user-images.githubusercontent.com/19589632/102180620-23432280-3ee4-11eb-8965-1bad0659fa00.png)

**Comment by tristaZero** [comment]
Hi @zosimer ，
Thanks for feedback, could you set `sql-show` = `true` so as to get the actual SQLs and logic SQLs from the log?

**Comment by zosimer** [comment]
> Hi @zosimer ，
> Thanks for feedback, could you set `sql-show` = `true` so as to get the actual SQLs and logic SQLs from the log?

selectmember_id,mobile,nickname,`name`,icard,photo,sex,birthday,platform,province,city,distri
ct,college_id,college_name,member_state,member_type,invite_code,rank_points,pay_points,money,frozen_money,gold,frozen_gold,login_ip,log
in_date,login_flag,sign,is_special,is_service,remarks,del_flag,create_by,create_date,update_by,update_datefrommember'
line 9:13 no viable alternative at input 'selectmember_id,mobile,nickname,`name`,icard,photo,sex,birthday,platform,province,city,distri
ct,college_id,college_name,member_state,member_type,invite_code,rank_points,pay_points,money,frozen_money,gold,frozen_gold,login_ip,log
in_date,login_flag,sign,is_special,is_service,remarks,del_flag,create_by,create_date,update_by,update_datefrommember'

**Comment by zosimer** [comment]
> > Hi @zosimer ，
> > Thanks for feedback, could you set `sql-show` = `true` so as to get the actual SQLs and logic SQLs from the log?
> 
> selectmember_id,mobile,nickname,`name`,icard,photo,sex,birthday,platform,province,city,distri
> ct,college_id,college_name,member_state,member_type,invite_code,rank_points,pay_points,money,frozen_money,gold,frozen_gold,login_ip,log
> in_date,login_flag,sign,is_special,is_service,remarks,del_flag,create_by,create_date,update_by,update_datefrommember'
> line 9:13 no viable alternative at input 'selectmember_id,mobile,nickname,`name`,icard,photo,sex,birthday,platform,province,city,distri
> ct,college_id,college_name,member_state,member_type,invite_code,rank_points,pay_points,money,frozen_money,gold,frozen_gold,login_ip,log
> in_date,login_flag,sign,is_special,is_service,remarks,del_flag,create_by,create_date,update_by,update_datefrommember'

![image](https://user-images.githubusercontent.com/19589632/102300061-20e9d280-3f8f-11eb-92bc-a6d6ba645eb1.png)

**Comment by zosimer** [comment]
> Hi @zosimer ，
> Thanks for feedback, could you set `sql-show` = `true` so as to get the actual SQLs and logic SQLs from the log?

Why did he remove the blanks

**Comment by tristaZero** [comment]
`sql-show = true` will show us what happen inner ShardngSphere.

**Comment by zosimer** [comment]
> `sql-show = true` will show us what happen inner ShardngSphere.

Can't you see the picture above? The error message is from the shardingproxy log
https://user-images.githubusercontent.com/19589632/102300061-20e9d280-3f8f-11eb-92bc-a6d6ba645eb1.png

**Comment by zosimer** [comment]
> `sql-show = true` will show us what happen inner ShardngSphere.

The top log of this page is output by shrdingproxy

**Comment by strongduanmu** [comment]
@zosimer Hi, this error is reported because member is a keyword in mysql. You can rewrite it in a way like this:

```sql
select member_id,mobile,nickname,name,icard,photo,sex,birthday,platform,province,city,distri
ct,college_id,college_name,member_state,member_type,invite_code,rank_points,pay_points,money,frozen_money,gold,frozen_gold,login_ip,log
in_date,login_flag,sign,is_special,is_service,remarks,del_flag,create_by,create_date,update_by,update_date from `member`;
```

**Comment by zosimer** [comment]
> @zosimer Hi, this error is reported because member is a keyword in mysql. You can rewrite it like this:
> 
> ```sql
> select member_id,mobile,nickname,name,icard,photo,sex,birthday,platform,province,city,distri
> ct,college_id,college_name,member_state,member_type,invite_code,rank_points,pay_points,money,frozen_money,gold,frozen_gold,login_ip,log
> in_date,login_flag,sign,is_special,is_service,remarks,del_flag,create_by,create_date,update_by,update_date from `member`;
> ```

But I didn't report this error in mysql5.7. I have been running this project for three years and won't change this word

**Comment by KSMASTERS** [comment]
I have the same problem！

**Comment by tristaZero** [comment]
Hi @KSMASTERS  could you try 5.0.0-alpha?
