### ISSUE TITLE
【shardingproxy-5.0.0-alpha】Can I change the actualDataNodes online?

### ISSUE THREAD

**Issue by orchids-li** [apache/shardingsphere#8779]
## Question

I have tables , sharding by  datetime, eg: t_order_202010, t_order_202011,
Can I add the table t_order_202012 to the actualDataNodes  without restart ?

**Comment by yu199195** [comment]
you can config governance.   

and then you can update sharding rule on the  shadingshpere-ui

**Comment by tristaZero** [comment]
Hi @orchids-li ,

Definitely, please refer to [Management](https://shardingsphere.apache.org/document/current/cn/features/governance/management/) for details.

**Comment by orchids-li** [comment]
> you can config governance.
> 
> and then you can update sharding rule on the shadingshpere-ui

when I config  governance, it has errors, used zookeeper-3.4.9.jar :

> Caused by: java.lang.NoClassDefFoundError: org/apache/zookeeper/admin/ZooKeeperAdmin
	at org.apache.curator.framework.CuratorFrameworkFactory.<clinit>(CuratorFrameworkFactory.java:65) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.shardingsphere.governance.repository.zookeeper.CuratorZookeeperRepository.buildCuratorClient(CuratorZookeeperRepository.java:80) ~[shardingsphere-governance-repository-zookeeper-curator-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.governance.repository.zookeeper.CuratorZookeeperRepository.init(CuratorZookeeperRepository.java:70) ~[shardingsphere-governance-repository-zookeeper-curator-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.governance.core.facade.repository.GovernanceRepositoryFacade.createRegistryRepository(GovernanceRepositoryFacade.java:53) ~[shardingsphere-governance-core-facade-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.governance.core.facade.repository.GovernanceRepositoryFacade.<init>(GovernanceRepositoryFacade.java:45) ~[shardingsphere-governance-core-facade-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.governance.core.facade.GovernanceFacade.init(GovernanceFacade.java:60) ~[shardingsphere-governance-core-facade-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.driver.governance.internal.datasource.GovernanceShardingSphereDataSource.createGovernanceFacade(GovernanceShardingSphereDataSource.java:78) ~[shardingsphere-jdbc-governance-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.driver.governance.internal.datasource.GovernanceShardingSphereDataSource.<init>(GovernanceShardingSphereDataSource.java:70) ~[shardingsphere-jdbc-governance-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.driver.governance.api.yaml.YamlGovernanceShardingSphereDataSourceFactory.createDataSourceWithRules(YamlGovernanceShardingSphereDataSourceFactory.java:115) ~[shardingsphere-jdbc-governance-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.driver.governance.api.yaml.YamlGovernanceShardingSphereDataSourceFactory.createDataSource(YamlGovernanceShardingSphereDataSourceFactory.java:103) ~[shardingsphere-jdbc-governance-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.driver.governance.api.yaml.YamlGovernanceShardingSphereDataSourceFactory.createDataSource(YamlGovernanceShardingSphereDataSourceFactory.java:54) ~[shardingsphere-jdbc-governance-5.0.0-alpha.jar:5.0.0-alpha]
	at com.foresee.sznf.hcp.report.config.YamlDataSourceFactory.newInstance(YamlDataSourceFactory.java:44) ~[classes/:?]

**Comment by tristaZero** [comment]
Hi, It looks that here is something wrong, could you give it a check or refer to [examples](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/governance-example)?

> Caused by: java.lang.NoClassDefFoundError: org/apache/zookeeper/admin/ZooKeeperAdmin
at org.apache.curator.framework.CuratorFrameworkFactory.

**Comment by terrymanu** [comment]
Please see the document: https://shardingsphere.apache.org/document/current/en/features/governance/management/dependency/

ZooKeeper need 3.6.x at least.
