### ISSUE TITLE
Transaction support issue

### ISSUE THREAD

**Issue by Simbafa** [apache/shardingsphere#8903]
### Which version of ShardingSphere did you use?
The latest version, 5.0.0-alpha
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
Multiple connections commit transactions correctly.
### Actual behavior
ShardingSphere-Proxy stops working, has no response for any requests.
### Reason analyze (If you can)
```
"ShardingSphere-Command-0" Id=18 RUNNABLE (in native)
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
    at java.net.SocketInputStream.read(SocketInputStream.java:171)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:101)
    at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:144)
    at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:174)
    at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3008)
    at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3469)
    at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3459)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3900)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
    at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1281)
    at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:782)
    at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)
    at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
    at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
    at org.apache.shardingsphere.proxy.backend.communication.jdbc.statement.accessor.impl.PreparedStatementAccessor.execute(PreparedStatementAccessor.java:45)
    at org.apache.shardingsphere.proxy.backend.communication.jdbc.execute.engine.jdbc.ProxySQLExecutorCallback.executeSQL(ProxySQLExecutorCallback.java:84)
    at org.apache.shardingsphere.proxy.backend.communication.jdbc.execute.engine.jdbc.ProxySQLExecutorCallback.executeSQL(ProxySQLExecutorCallback.java:77)
    at org.apache.shardingsphere.proxy.backend.communication.jdbc.execute.engine.jdbc.ProxySQLExecutorCallback.executeSQL(ProxySQLExecutorCallback.java:48)
    at org.apache.shardingsphere.infra.executor.sql.resourced.jdbc.executor.impl.DefaultSQLExecutorCallback.execute0(DefaultSQLExecutorCallback.java:75)
    at org.apache.shardingsphere.infra.executor.sql.resourced.jdbc.executor.impl.DefaultSQLExecutorCallback.execute(DefaultSQLExecutorCallback.java:57)
    at org.apache.shardingsphere.infra.executor.kernel.ExecutorKernel.syncExecute(ExecutorKernel.java:99)
    at org.apache.shardingsphere.infra.executor.kernel.ExecutorKernel.serialExecute(ExecutorKernel.java:84)
    at org.apache.shardingsphere.infra.executor.kernel.ExecutorKernel.execute(ExecutorKernel.java:78)
    at org.apache.shardingsphere.infra.executor.sql.resourced.jdbc.executor.SQLExecutor.execute(SQLExecutor.java:65)
    at org.apache.shardingsphere.proxy.backend.communication.jdbc.execute.engine.jdbc.JDBCExecuteEngine.executeWithManagedResource(JDBCExecuteEngine.java:130)
    at org.apache.shardingsphere.proxy.backend.communication.jdbc.execute.engine.jdbc.JDBCExecuteEngine.execute(JDBCExecuteEngine.java:123)
    at org.apache.shardingsphere.proxy.backend.communication.jdbc.execute.engine.jdbc.JDBCExecuteEngine.execute(JDBCExecuteEngine.java:103)
    at org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.doExecute(JDBCDatabaseCommunicationEngine.java:93)
    at org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:79)
    at org.apache.shardingsphere.proxy.frontend.mysql.command.query.binary.execute.MySQLComStmtExecuteExecutor.execute(MySQLComStmtExecuteExecutor.java:71)
    at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:100)
    at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:76)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

```
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

- 1. modify conf/server.yaml
    - set acceptor.size: 1
- 2. create test app
    - create n threads , where n>acceptor.size
    - if n<=acceptor.size, ShardingSphere works well.
    - In the threads, start transaction, do some things, and then commit
        -  conn.setAutoCommit(false);
        - select * from table1 where fid=1 for update
        - update table1 set fint=fint+1 where fid=1
        - conn.commit()
        - repeat above steps

The most important thing is that the threads number must bigger than the acceptor.size.

**Comment by Simbafa** [comment]
Hi @tuohai666 , 
Sorry to bother you. But this issue affect us much.
When do you plan to check this issue?
Thank you very much.

**Comment by tuohai666** [comment]
@Simbafa What kind of transaction of Proxy?
Please show the full server.yaml and config-.*.yaml.
Set sql.show: true and provide logs with more details.

**Comment by Simbafa** [comment]
![error](https://user-images.githubusercontent.com/37646009/106217597-84168800-6210-11eb-83f7-c0c3982760c5.jpg)

**Comment by Simbafa** [comment]
config-sharding.yaml
```
 13 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 14 # See the License for the specific language governing permissions and
 15 # limitations under the License.
 16 # 
 17 
 18 ######################################################################################################
 19 # 
 20 # Here you can configure the rules for the proxy.
 21 # This example is configuration of sharding rule.
 22 # 
 23 ######################################################################################################
 24 #
 25 schemaName: test           
 26 #
 27 dataSourceCommon:          
 28   username: root
 29   password: test
 30   connectionTimeoutMilliseconds: 30000
 31   idleTimeoutMilliseconds: 60000  
 32   maxLifetimeMilliseconds: 1800000
 33   maxPoolSize: 50
 34   minPoolSize: 1
 35   maintenanceIntervalMilliseconds: 30000
 36 
 37 dataSources:
 38   ds_0:
 39      url: jdbc:mysql://192.168.1.46:3306/test?serverTimezone=UTC&useSSL=false
 40 #    url: jdbc:postgresql://127.0.0.1:5432/demo_ds_0?serverTimezone=UTC&useSSL=false
 41 #  ds_1:
 42 #    url: jdbc:postgresql://127.0.0.1:5432/demo_ds_1?serverTimezone=UTC&useSSL=false
 43 #
 44 rules:
 45 - !SHARDING
 46   tables:                                                                                                                                                                                                                                                                 
 47     t_order:
 48       actualDataNodes: ds_${0}.t_order_${0}
 49       tableStrategy:
 50         standard:
 51           shardingColumn: order_id        
 52           shardingAlgorithmName: t_order_inline
 53 #      keyGenerateStrategy:
 54 #        column: order_id
 55 #        keyGeneratorName: snowflake
 56 #    t_order_item:
 57 #      actualDataNodes: ds_${0..1}.t_order_item_${0..1}
 58 #      tableStrategy:

```

**Comment by Simbafa** [comment]
server.yaml

```
 23 #
 24 #governance:               
 25 #  name: governance_ds     
 26 #  registryCenter:         
 27 #    type: ZooKeeper
 28 #    serverLists: localhost:2181
 29 #    props:
 30 #      retryIntervalMilliseconds: 500
 31 #      timeToLiveSeconds: 60
 32 #      maxRetries: 3
 33 #      operationTimeoutMilliseconds: 500
 34 #  overwrite: false
 35 
 36 authentication:
 37   users:
 38     root:
 39       password: test
 40 #    sharding:
 41 #      password: sharding 
 42 #      authorizedSchemas: sharding_db
 43 
 44 props:
 45   max-connections-size-per-query: 1
 46   acceptor-size: 1  # The default value is available processors count * 2.
 47   executor-size: 16  # Infinite by default.
 48 #  proxy-frontend-flush-threshold: 128  # The default value is 128.
 49 #    # LOCAL: Proxy will run with LOCAL transaction.
 50 #    # XA: Proxy will run with XA transaction.
 51 #    # BASE: Proxy will run with B.A.S.E transaction.
 52 #  proxy-transaction-type: LOCAL
 53 #  proxy-opentracing-enabled: false
 54 #  proxy-hint-enabled: false
 55 #  query-with-cipher-column: true
 56   sql-show: true                                                                                                                                                                                                                                                          
 57 #  check-table-metadata-enabled: false

```

**Comment by Simbafa** [comment]
output:
```
bash shardingsphere-proxy-distribution-5.0.0-alpha-shardingsphere-proxy-bin/bin/start.sh 
Starting the ShardingSphere-Proxy ...
The classpath is .:/root/Downloads/shardingsphere-proxy-distribution-5.0.0-alpha-shardingsphere-proxy-bin/lib/*:/root/Downloads/shardingsphere-proxy-distribution-5.0.0-alpha-shardingsphere-proxy-bin/ext-lib/*
[INFO ] 08:53:43.336 [main] ShardingSphere-metadata - Loading 56 tables' meta data for unconfigured tables.
[INFO ] 08:53:43.357 [main] ShardingSphere-metadata - Loading 57 tables' meta data for unconfigured tables.
[INFO ] 08:53:43.368 [main] o.a.s.i.c.s.SchemaContextsBuilder - Load meta data for schema test finished, cost 511 milliseconds.
Thanks for using Atomikos! Evaluate http://www.atomikos.com/Main/ExtremeTransactions for advanced features and professional support
or register at http://www.atomikos.com/Main/RegisterYourDownload to disable this message and receive FREE tips & advice
[INFO ] 08:53:43.500 [main] o.a.s.p.i.i.AbstractBootstrapInitializer - Database name is `MySQL`, version is `5.7.26`
[INFO ] 08:53:43.751 [main] o.a.s.p.frontend.ShardingSphereProxy - ShardingSphere-Proxy start success.
[INFO ] 08:53:50.135 [ShardingSphere-Command-0] ShardingSphere-SQL - Logic SQL: /* mysql-connector-java-5.1.47 ( Revision: fe1903b1ecb4a96a917f7ed3190d80c049b1de29 ) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@transaction_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout
[INFO ] 08:53:50.135 [ShardingSphere-Command-0] ShardingSphere-SQL - SQLStatement: MySQLSelectStatement(limit=Optional.empty, lock=Optional.empty)
[INFO ] 08:53:50.135 [ShardingSphere-Command-0] ShardingSphere-SQL - Actual SQL: ds_0 ::: /* mysql-connector-java-5.1.47 ( Revision: fe1903b1ecb4a96a917f7ed3190d80c049b1de29 ) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@transaction_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout
[INFO ] 08:53:50.210 [ShardingSphere-Command-0] ShardingSphere-SQL - Logic SQL: /* mysql-connector-java-5.1.47 ( Revision: fe1903b1ecb4a96a917f7ed3190d80c049b1de29 ) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@transaction_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout
[INFO ] 08:53:50.212 [ShardingSphere-Command-0] ShardingSphere-SQL - SQLStatement: MySQLSelectStatement(limit=Optional.empty, lock=Optional.empty)
[INFO ] 08:53:50.212 [ShardingSphere-Command-0] ShardingSphere-SQL - Actual SQL: ds_0 ::: /* mysql-connector-java-5.1.47 ( Revision: fe1903b1ecb4a96a917f7ed3190d80c049b1de29 ) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@transaction_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout
[INFO ] 08:53:50.268 [ShardingSphere-Command-0] ShardingSphere-SQL - Logic SQL: SET NAMES utf8
[INFO ] 08:53:50.268 [ShardingSphere-Command-0] ShardingSphere-SQL - SQLStatement: MySQLSetStatement()
[INFO ] 08:53:50.268 [ShardingSphere-Command-0] ShardingSphere-SQL - Actual SQL: ds_0 ::: SET NAMES utf8
[INFO ] 08:53:50.274 [ShardingSphere-Command-0] ShardingSphere-SQL - Logic SQL: SET NAMES utf8
[INFO ] 08:53:50.275 [ShardingSphere-Command-0] ShardingSphere-SQL - SQLStatement: MySQLSetStatement()
[INFO ] 08:53:50.275 [ShardingSphere-Command-0] ShardingSphere-SQL - Actual SQL: ds_0 ::: SET NAMES utf8
[INFO ] 08:53:50.368 [ShardingSphere-Command-0] ShardingSphere-SQL - Logic SQL: select fint, ftext from forupdate where fid = 1 for update 
[INFO ] 08:53:50.368 [ShardingSphere-Command-0] ShardingSphere-SQL - SQLStatement: MySQLSelectStatement(limit=Optional.empty, lock=Optional[org.apache.shardingsphere.sql.parser.sql.common.segment.dml.predicate.LockSegment@6e9bbf34])
[INFO ] 08:53:50.369 [ShardingSphere-Command-0] ShardingSphere-SQL - Actual SQL: ds_0 ::: select fint, ftext from forupdate where fid = 1 for update 
[INFO ] 08:53:50.374 [ShardingSphere-Command-0] ShardingSphere-SQL - Logic SQL: select fint, ftext from forupdate where fid = 1 for update 
[INFO ] 08:53:50.374 [ShardingSphere-Command-0] ShardingSphere-SQL - SQLStatement: MySQLSelectStatement(limit=Optional.empty, lock=Optional[org.apache.shardingsphere.sql.parser.sql.common.segment.dml.predicate.LockSegment@13a5357d])
[INFO ] 08:53:50.374 [ShardingSphere-Command-0] ShardingSphere-SQL - Actual SQL: ds_0 ::: select fint, ftext from forupdate where fid = 1 for update 
[ERROR] 08:54:41.430 [ShardingSphere-Command-0] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:951)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.nextRow(MysqlIO.java:1996)
	at com.mysql.jdbc.RowDataDynamic.nextRecord(RowDataDynamic.java:374)
	at com.mysql.jdbc.RowDataDynamic.next(RowDataDynamic.java:354)
	at com.mysql.jdbc.ResultSetImpl.next(ResultSetImpl.java:6309)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.next(HikariProxyResultSet.java)
	at org.apache.shardingsphere.infra.executor.sql.resourced.jdbc.queryresult.StreamQueryResult.next(StreamQueryResult.java:56)
	at org.apache.shardingsphere.sharding.merge.dql.iterator.IteratorStreamMergedResult.next(IteratorStreamMergedResult.java:41)
	at org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.next(JDBCDatabaseCommunicationEngine.java:148)
	at org.apache.shardingsphere.proxy.backend.text.query.QueryBackendHandler.next(QueryBackendHandler.java:66)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.next(MySQLComQueryPacketExecutor.java:80)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecuteEngine.writeQueryData(MySQLCommandExecuteEngine.java:82)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:106)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO ] 08:54:41.527 [ShardingSphere-Command-0] ShardingSphere-SQL - Logic SQL: /* mysql-connector-java-5.1.47 ( Revision: fe1903b1ecb4a96a917f7ed3190d80c049b1de29 ) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS char

```

**Comment by tuohai666** [comment]
It seems like the 1st SQL (2 in total) locked the rows and it lead to the 2nd SQL fire a timeout Exception. The Exception burst 50 seconds (innodb_lock_wait_timeout) after execution.
Can you tell me whether fid is the key? Or how many rows will return for this SQL?
What the return result looks like? And how your test codes process the  ResultSet?

**Comment by Simbafa** [comment]
It's not that the 1st SQL blocked 2nd SQL.
If the client threads < acceptor.size, the tests can run correctly.
The most important thing in this test case is that "CLIENT THREADS > ACCEPTOR.SIZE"

Which field is the key has no matter to this issue. 
In your test, you can pick any field as the key.

In my test case,  only one row will be returned for the SQL.
```
CREATE TABLE `forupdate` (
	`fid` INT(11) NULL DEFAULT NULL,
	`fint` INT(11) NULL DEFAULT NULL,
	`ftext` TEXT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
```

**Comment by tuohai666** [comment]
@Simbafa You are right, it's because only 1 (ACCEPTOR.SIZE: 1) thread executing between two transactions. One of the transaction occupy the row but not commit, then the thread execute another transaction which will not go on due to updating the same row, the thread will be blocked and all the two transactions will not commit. I have found the root cause and will fix it in several days. Before that I suggest you to comment acceptor.size(infinite by default), and let the test proceed.
