### ISSUE TITLE
Not sure how to avoid conflict with Skywalking

### ISSUE THREAD

**Issue by lhcxj576** [apache/shardingsphere#8943]
![image](https://user-images.githubusercontent.com/73157467/103912859-c5040b00-5142-11eb-88b7-f0cd40470fe0.png)

**Comment by yu199195** [comment]
My advice : 
1. you can  use  -javaagent:  skywalking-agent.jar   because we provide plugin in skywalking。
2. this module will be remove in next version

**Comment by wu-sheng** [comment]
I think the simple answer is, you don't need the OT-SkyWalking bridge. Install the SkyWalking agent, shardingsphere native plugin should take care of all things automatically.

**Comment by lhcxj576** [comment]
Now we have a reference to ShardingSphere in our application, version 4.1.1。
I've also introduced Skywalking, but Skywalking keeps reporting errors, and it says。
But the application is working;




ERROR 2021-01-07 21:08:49:080 DubboServerHandler-10.0.21.195:7041-thread-193 InstMethodsInter : class[class org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor] before method[executeCallback] intercept failure 

java.lang.NoClassDefFoundError: org/apache/shardingsphere/core/execute/ShardingExecuteDataMap

	at org.apache.skywalking.apm.plugin.shardingsphere.v4.JDBCRootInvokeInterceptor.beforeMethod(JDBCRootInvokeInterceptor.java:41)

	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:76)

	at org.apache.shardingsphere.shardingjdbc.executor.AbstractStatementExecutor.executeCallback(AbstractStatementExecutor.java)

	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.execute(PreparedStatementExecutor.java:148)

	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:145)

	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63)

	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)

	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)

	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:326)

	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)

	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)

	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)

	at sun.reflect.GeneratedMethodAccessor266.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:497)

	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)

	at com.sun.proxy.$Proxy168.query(Unknown Source)

	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)

	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)

	at sun.reflect.GeneratedMethodAccessor265.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:497)

	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)

	at com.sun.proxy.$Proxy122.selectList(Unknown Source)

	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)

	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:139)

	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:76)

	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)

	at com.sun.proxy.$Proxy142.selectBySysCodes(Unknown Source)

	at com.sr.center.inservice.impl.PurBrandQueryInServiceImpl.getByCodes(PurBrandQueryInServiceImpl.java:96)

	at com.sr.center.inservice.impl.PurBrandQueryInServiceImpl$$FastClassBySpringCGLIB$$cf087586.invoke(<generated>)

	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)

	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)

	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)

	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)

	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:55)

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)

	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)

	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)

	at com.sr.center.inservice.impl.PurBrandQueryInServiceImpl$$EnhancerBySpringCGLIB$$d063f7de.getByCodes(<generated>)

	at com.sr.center.inservice.impl.PurSupSkuPoolQueryInServiceImpl.getPurBrand(PurSupSkuPoolQueryInServiceImpl.java:194)

	at com.sr.center.inservice.impl.PurSupSkuPoolQueryInServiceImpl.getPoolDetailBySysPoolCode(PurSupSkuPoolQueryInServiceImpl.java:124)

	at com.sr.center.inservice.impl.PurSupSkuPoolQueryInServiceImpl$$FastClassBySpringCGLIB$$b4f2e11c.invoke(<generated>)

	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)

	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)

	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)

	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)

	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:55)

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)

	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)

	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)

	at com.sr.center.inservice.impl.PurSupSkuPoolQueryInServiceImpl$$EnhancerBySpringCGLIB$$3a02860.getPoolDetailBySysPoolCode(<generated>)

	at com.sr.center.remote.PurSupSkuPoolQueryServiceImpl.getPoolDetailBySysPoolCode(PurSupSkuPoolQueryServiceImpl.java:35)

	at com.sr.center.remote.PurSupSkuPoolQueryServiceImpl$$FastClassBySpringCGLIB$$959a3569.invoke(<generated>)

	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)

	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)

	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)

	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)

	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:55)

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)

	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)

	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)

	at com.sr.center.remote.QueryServiceImpl$$EnhancerBySpringCGLIB$$b492bd67.getPoolDetailBySysPoolCode(<generated>)

	at com.alibaba.dubbo.common.bytecode.Wrapper19.invokeMethod(Wrapper19.java)

	at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:47)

	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:76)

	at com.alibaba.dubbo.config.invoker.DelegateProviderMetaDataInvoker.invoke(DelegateProviderMetaDataInvoker.java:52)

	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)

	at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:62)

	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)

	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke$original$TxtEFbb5(MonitorFilter.java:75)

	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke$original$TxtEFbb5$accessor$JJa3xu0R(MonitorFilter.java)

	at com.alibaba.dubbo.monitor.support.MonitorFilter$auxiliary$HPhJcK1f.call(Unknown Source)

	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)

	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java)

	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)

	at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42)

	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)

	at com.sr.center.config.filter.LogDubboFilter.invoke(LogDubboFilter.java:48)

	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)

	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78)

	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)

	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:72)

	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)

	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:131)

	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)

	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)

	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)

	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)

	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)

	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:103)

	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:96)

	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:172)

	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)

	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:80)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

	at java.lang.Thread.run(Thread.java:745)

**Comment by wu-sheng** [comment]
Do you use the latest SkyWalking release? The ShardingSphere internal APIs have done some incompatible upgrade in recent several months, SkyWalking community has accepted the PRs to support 4.1.1, which is included in 8.1.0;s https://github.com/apache/skywalking/pull/4921

Check our test case, https://github.com/apache/skywalking/blob/master/test/plugin/scenarios/shardingsphere-4.x-scenario/support-version.list.
