### ISSUE TITLE
Shardingproxy sctl is not usable 

### ISSUE THREAD

**Issue by traceming2** [apache/shardingsphere#8949]
The sctl commands cannot be processed by JDBC.
```
        Connection conn = dataSource.getConnection();
        Statement stmt = conn.createStatement();
        stmt.execute("sctl:hint set addDatabaseShardingValue my_table=0");
        stmt.execute("sctl:hint set addTableShardingValue my_table=0");
```
```
java.sql.SQLException: 1Could not support sctl type [sctl:hint set addDatabaseShardingValue account_tab_hinted=0].

	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
```

**Comment by traceming2** [comment]
no `set` after `sctl:hint`
