### ISSUE TITLE
When using 'left join'，If you query multiple tables，error will be reported when merging results

### ISSUE THREAD

**Issue by singlemonkey** [apache/shardingsphere#9016]
dependency:
```
<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
    <version>5.0.0-alpha</version>
</dependency>
```

application.properties:
```
spring.shardingsphere.datasource.names=sharding-person
spring.shardingsphere.datasource.common.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.common.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.common.username=root
spring.shardingsphere.datasource.common.password=Jykj@123

spring.shardingsphere.datasource.sharding-person.url=jdbc:mysql://192.168.50.144:3306/person?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull

# ps_t_history_result
spring.shardingsphere.rules.sharding.tables.ps_t_history_result.actual-data-nodes=sharding-person.ps_t_history_result
spring.shardingsphere.rules.sharding.tables.ps_t_history_result.tableStrategy.standard.shardingColumn=ps_mine_entertime
spring.shardingsphere.rules.sharding.tables.ps_t_history_result.tableStrategy.standard.sharding-algorithm-name=sharding-by-month

# ps_t_history_result_track
spring.shardingsphere.rules.sharding.tables.ps_t_history_result_track.actual-data-nodes=sharding-person.ps_t_history_result_track
spring.shardingsphere.rules.sharding.tables.ps_t_history_result_track.tableStrategy.standard.shardingColumn=ps_mine_entertime
spring.shardingsphere.rules.sharding.tables.ps_t_history_result_track.tableStrategy.standard.sharding-algorithm-name=sharding-by-month

# ps_t_history_mine
spring.shardingsphere.rules.sharding.tables.ps_t_history_mine.actual-data-nodes=sharding-person.ps_t_history_mine
spring.shardingsphere.rules.sharding.tables.ps_t_history_mine.tableStrategy.standard.shardingColumn=cs_data_time
spring.shardingsphere.rules.sharding.tables.ps_t_history_mine.tableStrategy.standard.sharding-algorithm-name=sharding-by-month

spring.shardingsphere.rules.sharding.sharding-algorithms.sharding-by-month.type=RANGE
spring.shardingsphere.rules.sharding.sharding-algorithms.sharding-by-month.props.strategy=STANDARD
spring.shardingsphere.rules.sharding.sharding-algorithms.sharding-by-month.props.algorithm-class-name=com.jylink.csrapadscs.common.config.sharding.algorithms.RangeAlgorithms
spring.shardingsphere.rules.sharding.sharding-algorithms.sharding-by-month.props.sharding=true
spring.shardingsphere.rules.sharding.sharding-algorithms.sharding-by-month.props.range-type=month
spring.shardingsphere.rules.sharding.sharding-algorithms.sharding-by-month.props.datetime-lower=2020-04-01 00:00:00
spring.shardingsphere.rules.sharding.sharding-algorithms.sharding-by-month.props.datetime-upper=

spring.shardingsphere.rules.sharding.key-generators.snowflake.type=SNOWFLAKE
spring.shardingsphere.rules.sharding.key-generators.snowflake.props.worker-id=123

spring.shardingsphere.props.sql-show=true
```

sql:
```
select
  t.cs_mine_code,
  t.cs_mine_shortname,
  t.ps_person_card,
  t.ps_person_name,
  t.ps_person_post,
  t.ps_person_duty,
  t.ps_person_dept,
  t.ps_class_code,
  t.ps_mine_entertime,
  t.ps_mine_outtime,
  t.ps_enter_duration,
  t.ps_is_lose,
  t1.ps_class_name as class_name
from ps_t_history_result t
left join ps_t_info_class t1
  on t1.cs_mine_code=t.cs_mine_code and t1.ps_class_code=t.ps_class_code
<where>
  <if test="query.startTime!=null">
    AND t.ps_mine_entertime &gt;=#{query.startTime}
  </if>
  <if test="query.endTime!=null">
    AND t.ps_mine_entertime &lt;=#{query.endTime}
  </if>
</where>
```
It works will when the query scope does not involve multiple tables,but an error will be reported when the query results of multiple tables are merged。Error message like this:
```
Caused by: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : 
 SELECT COUNT(1) FROM ps_t_history_result t LEFT JOIN ps_t_info_class t1 ON t1.cs_mine_code = t.cs_mine_code AND t1.ps_class_code = t.ps_class_code WHERE t.ps_mine_entertime >= ? AND t.ps_mine_entertime <= ? 

	at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:39)
	at com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor.queryTotal(PaginationInterceptor.java:253)
	at com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor.intercept(PaginationInterceptor.java:201)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy268.prepare(Unknown Source)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.prepareStatement(MybatisSimpleExecutor.java:92)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doQuery(MybatisSimpleExecutor.java:66)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.query(MybatisCachingExecutor.java:163)
	at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.query(MybatisCachingExecutor.java:90)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	... 141 more
Caused by: java.lang.NullPointerException
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.getValueCaseSensitiveFromTables(GroupByMemoryMergedResult.java:132)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.getValueCaseSensitive(GroupByMemoryMergedResult.java:122)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.init(GroupByMemoryMergedResult.java:72)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.init(GroupByMemoryMergedResult.java:52)
	at org.apache.shardingsphere.infra.merge.result.impl.memory.MemoryMergedResult.<init>(MemoryMergedResult.java:51)
	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.<init>(GroupByMemoryMergedResult.java:55)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.getGroupByMergedResult(ShardingDQLResultMerger.java:108)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.build(ShardingDQLResultMerger.java:78)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.merge(ShardingDQLResultMerger.java:63)
	at org.apache.shardingsphere.infra.merge.MergeEngine.executeMerge(MergeEngine.java:87)
	at org.apache.shardingsphere.infra.merge.MergeEngine.merge(MergeEngine.java:77)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.mergeQuery(ShardingSpherePreparedStatement.java:283)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.executeQuery(ShardingSpherePreparedStatement.java:167)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:56)
	at com.sun.proxy.$Proxy270.executeQuery(Unknown Source)
	at com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor.queryTotal(PaginationInterceptor.java:242)
	... 151 more
```
When I track code execution，I found that the error was due to the failure to find the associated table “ps_t_info_class” from "schemametadata",The details are as follows:
<img width="1339" alt="截屏2021-01-13 下午6 23 44" src="https://user-images.githubusercontent.com/13411315/104440002-c57e2500-55cc-11eb-8355-62727ae5410a.png">

The "PhysicalTableMetaData tableMetaData" will be null and throw an NullPointerException.
How can I solve this problem？

**Comment by tristaZero** [comment]
Hi @singlemonkey ,

Thanks for your feedback. It looks like a bug. Could you show us where this function is called? 

@terrymanu I saw you made some changes recently, could you give this issue a look?

**Comment by JiekerTime** [comment]
Hi~The part about the sharding algorithm in your configuration file seems a bit confusing. Could you please give more detailed information, or try to modify your configuration file by referring to the configuration on the official website.

**Comment by JiekerTime** [comment]
Hi~ The part of sharding algorithm in your configuration file seems a bit confusing. Could you please give more detailed information, or try to modify your configuration file by referring to the [SHARDING ALGORITHM configuration](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/configuration/built-in-algorithm/sharding/)

**Comment by terrymanu** [comment]
No response
