### ISSUE TITLE
ShardingSphere JDBC 5.0.0-alpha use Etcd config center error

### ISSUE THREAD

**Issue by YanlongMa** [apache/shardingsphere#9121]
## Question

config and error info , is jetcd version reason ?

pom.xml
```
<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere-jdbc-governance-spring-boot-starter</artifactId>
    <version>5.0.0-alpha</version>
    <exclusions>
        <exclusion>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-test</artifactId>
        </exclusion>
    </exclusions>
</dependency>

<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere-governance-repository-etcd</artifactId>
    <version>5.0.0-alpha</version>
</dependency>
```

application.properties
```
spring.shardingsphere.datasource.names=primary,replica0,replica1

spring.shardingsphere.datasource.common.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.common.driver-class-name=com.mysql.cj.jdbc.Driver

# primary
spring.shardingsphere.datasource.primary.jdbc-url=jdbc:mysql://127.0.0.1:3306/primary?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
spring.shardingsphere.datasource.primary.username=root
spring.shardingsphere.datasource.primary.password=123456

# replica0
spring.shardingsphere.datasource.replica0.jdbc-url=jdbc:mysql://127.0.0.1:3306/replica0?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
spring.shardingsphere.datasource.replica0.username=root
spring.shardingsphere.datasource.replica0.password=123456

# replica1
spring.shardingsphere.datasource.replica1.jdbc-url=jdbc:mysql://127.0.0.1:3306/replica1?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
spring.shardingsphere.datasource.replica1.username=root
spring.shardingsphere.datasource.replica1.password=123456

spring.shardingsphere.rules.replica-query.load-balancers.taishan-basic.type=ROUND_ROBIN
spring.shardingsphere.rules.replica-query.load-balancers.taishan-basic.props.test=test
spring.shardingsphere.rules.replica-query.data-sources.taishan-basic.primary-data-source-name=primary
spring.shardingsphere.rules.replica-query.data-sources.taishan-basic.replica-data-source-names=replica0,replica1
spring.shardingsphere.rules.replica-query.data-sources.taishan-basic.load-balancer-name=taishan-basic

spring.shardingsphere.props.sql-show=true

spring.shardingsphere.governance.name=taishan-basic
spring.shardingsphere.governance.registry-center.type=etcd
spring.shardingsphere.governance.registry-center.server-lists=localhost:2379
spring.shardingsphere.governance.registry-center.props.xxx=meiyou
spring.shardingsphere.governance.additional-config-center.type=etcd
spring.shardingsphere.governance.additional-config-center.server-lists=localhost:2379
spring.shardingsphere.governance.additional-config-center.props.xxx=meiyou
spring.shardingsphere.governance.overwrite=true
```

run , then error info :
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-01-21 19:43:59.388 ERROR 67232 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    io.etcd.jetcd.ClientConnectionManager.defaultChannelBuilder(ClientConnectionManager.java:190)

The following method did not exist:

    io.grpc.netty.NettyChannelBuilder.nameResolverFactory(Lio/grpc/NameResolver$Factory;)Lio/grpc/internal/AbstractManagedChannelImplBuilder;

The method's class, io.grpc.netty.NettyChannelBuilder, is available from the following locations:

    jar:file:/Users/marko/.m2/repository/io/grpc/grpc-netty/1.33.0/grpc-netty-1.33.0.jar!/io/grpc/netty/NettyChannelBuilder.class

The class hierarchy was loaded from the following locations:

    io.grpc.netty.NettyChannelBuilder: file:/Users/marko/.m2/repository/io/grpc/grpc-netty/1.33.0/grpc-netty-1.33.0.jar
    io.grpc.ForwardingChannelBuilder: file:/Users/marko/.m2/repository/io/grpc/grpc-api/1.33.0/grpc-api-1.33.0.jar
    io.grpc.ManagedChannelBuilder: file:/Users/marko/.m2/repository/io/grpc/grpc-api/1.33.0/grpc-api-1.33.0.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of io.grpc.netty.NettyChannelBuilder


Process finished with exit code 0
```

**Comment by dongzl** [comment]
Hi @YanlongMa , I test it with `etcd`, it's OK.

I doubt the `grpc` jar conflict cause this problem.

For `grpc`, ShardingSphere's version is `1.27.1`. and your version is `1.33.0`.  You can check them.

**Comment by YanlongMa** [comment]
I add dependency in pom.xml
```
<dependency>
    <groupId>io.grpc</groupId>
    <artifactId>grpc-core</artifactId>
    <version>1.27.1</version>
</dependency>
<dependency>
    <groupId>io.grpc</groupId>
    <artifactId>grpc-netty</artifactId>
    <version>1.27.1</version>
</dependency>
<dependency>
    <groupId>io.grpc</groupId>
    <artifactId>grpc-protobuf</artifactId>
    <version>1.27.1</version>
</dependency>
<dependency>
    <groupId>io.grpc</groupId>
    <artifactId>grpc-stub</artifactId>
    <version>1.27.1</version>
</dependency>
<dependency>
    <groupId>io.grpc</groupId>
    <artifactId>grpc-grpclb</artifactId>
    <version>1.27.1</version>
</dependency>
<dependency>
    <groupId>io.grpc</groupId>
    <artifactId>grpc-api</artifactId>
    <version>1.27.1</version>
</dependency>
<dependency>
    <groupId>io.grpc</groupId>
    <artifactId>grpc-context</artifactId>
    <version>1.27.1</version>
</dependency>
```

run，and then error report info，What should I do?
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'codeMapper' defined in file [/Users/marko/javaspace/kushu-taishan/basic/basic-svc/target/classes/cn/ku52/taishan/basic/mapper/CodeMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.class]: Unsatisfied dependency expressed through method 'sqlSessionFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'localShardingSphereDataSource' defined in class path resource [org/apache/shardingsphere/spring/boot/governance/GovernanceSpringBootConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'localShardingSphereDataSource' threw exception; nested exception is org.apache.shardingsphere.infra.spi.exception.ServiceProviderNotFoundException: No implementation class load from SPI `org.apache.shardingsphere.governance.repository.api.ConfigurationRepository` with type `etcd`.
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1420) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405) [spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at cn.ku52.taishan.basic.BasicApplication.main(BasicApplication.java:13) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_231]

Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.class]: Unsatisfied dependency expressed through method 'sqlSessionFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'localShardingSphereDataSource' defined in class path resource [org/apache/shardingsphere/spring/boot/governance/GovernanceSpringBootConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'localShardingSphereDataSource' threw exception; nested exception is org.apache.shardingsphere.infra.spi.exception.ServiceProviderNotFoundException: No implementation class load from SPI `org.apache.shardingsphere.governance.repository.api.ConfigurationRepository` with type `etcd`.
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:799) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:540) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1176) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireByType(AbstractAutowireCapableBeanFactory.java:1509) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	... 49 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'localShardingSphereDataSource' defined in class path resource [org/apache/shardingsphere/spring/boot/governance/GovernanceSpringBootConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'localShardingSphereDataSource' threw exception; nested exception is org.apache.shardingsphere.infra.spi.exception.ServiceProviderNotFoundException: No implementation class load from SPI `org.apache.shardingsphere.governance.repository.api.ConfigurationRepository` with type `etcd`.
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:657) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:637) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1176) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:886) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:790) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	... 62 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'localShardingSphereDataSource' threw exception; nested exception is org.apache.shardingsphere.infra.spi.exception.ServiceProviderNotFoundException: No implementation class load from SPI `org.apache.shardingsphere.governance.repository.api.ConfigurationRepository` with type `etcd`.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:652) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	... 76 common frames omitted
Caused by: org.apache.shardingsphere.infra.spi.exception.ServiceProviderNotFoundException: No implementation class load from SPI `org.apache.shardingsphere.governance.repository.api.ConfigurationRepository` with type `etcd`.
	at org.apache.shardingsphere.infra.spi.typed.TypedSPIRegistry.getRegisteredService(TypedSPIRegistry.java:50) ~[shardingsphere-infra-common-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.governance.core.facade.repository.GovernanceRepositoryFacade.createConfigurationRepository(GovernanceRepositoryFacade.java:60) ~[shardingsphere-governance-core-facade-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.governance.core.facade.repository.GovernanceRepositoryFacade.<init>(GovernanceRepositoryFacade.java:46) ~[shardingsphere-governance-core-facade-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.governance.core.facade.GovernanceFacade.init(GovernanceFacade.java:60) ~[shardingsphere-governance-core-facade-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.driver.governance.internal.datasource.GovernanceShardingSphereDataSource.createGovernanceFacade(GovernanceShardingSphereDataSource.java:78) ~[shardingsphere-jdbc-governance-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.driver.governance.internal.datasource.GovernanceShardingSphereDataSource.<init>(GovernanceShardingSphereDataSource.java:70) ~[shardingsphere-jdbc-governance-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.spring.boot.governance.GovernanceSpringBootConfiguration.createDataSourceWithRules(GovernanceSpringBootConfiguration.java:119) ~[shardingsphere-jdbc-governance-spring-boot-starter-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.spring.boot.governance.GovernanceSpringBootConfiguration.localShardingSphereDataSource(GovernanceSpringBootConfiguration.java:97) ~[shardingsphere-jdbc-governance-spring-boot-starter-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.spring.boot.governance.GovernanceSpringBootConfiguration$$EnhancerBySpringCGLIB$$e8c0e588.CGLIB$localShardingSphereDataSource$2(<generated>) ~[shardingsphere-jdbc-governance-spring-boot-starter-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.spring.boot.governance.GovernanceSpringBootConfiguration$$EnhancerBySpringCGLIB$$e8c0e588$$FastClassBySpringCGLIB$$b1e37afe.invoke(<generated>) ~[shardingsphere-jdbc-governance-spring-boot-starter-5.0.0-alpha.jar:5.0.0-alpha]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.apache.shardingsphere.spring.boot.governance.GovernanceSpringBootConfiguration$$EnhancerBySpringCGLIB$$e8c0e588.localShardingSphereDataSource(<generated>) ~[shardingsphere-jdbc-governance-spring-boot-starter-5.0.0-alpha.jar:5.0.0-alpha]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_231]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	... 77 common frames omitted


Process finished with exit code 0

```

**Comment by dongzl** [comment]
`No implementation class load from SPI  org.apache.shardingsphere.governance.repository.api.ConfigurationRepository with type etcd.`

It maybe short of jar package.  

@YanlongMa , can you provider a github project and reproduce this problem, and I check it.

**Comment by YanlongMa** [comment]
Hi @dongzl,  
I create a repository : `https://github.com/yanlongma/shardingsphere-example`.

repository have a readme, you need create database and table.

**Comment by dongzl** [comment]
Hi @YanlongMa , I check your project. This governance config can work well.

```
# 配置中心
# 治理名称
spring.shardingsphere.governance.name=kushu-taishan-baisc
# 治理持久化类型。如：Zookeeper, etcd, Apollo, Nacos
spring.shardingsphere.governance.registry-center.type=etcd
# 治理服务列表。包括 IP 地址和端口号。多个地址用逗号分隔。如: host1:2181,host2:2181
spring.shardingsphere.governance.registry-center.server-lists=http://localhost:2379
# 其它配置
#spring.shardingsphere.governance.registry-center.props=www
#spring.shardingsphere.governance.registry-center.props.name=www
# 可选的配置中心类型。如：Zookeeper, etcd, Apollo, Nacos
#spring.shardingsphere.governance.additional-config-center.type=etcd
# 可选的配置中心服务列表。包括 IP 地址和端口号。多个地址用逗号分隔。如: host1:2181,host2:2181
#spring.shardingsphere.governance.additional-config-center.server-lists=localhost:2379
# 可选的配置中心其它配置
#spring.shardingsphere.governance.additional-config-center.props=www
#spring.shardingsphere.governance.additional-config-center.props.name=www
# 本地配置是否覆盖配置中心配置。如果可覆盖，每次启动都以本地配置为准.
spring.shardingsphere.governance.overwrite=false
```

First, should remove this tow config, because we can use `etcd` as `registry center` and  `config center`, doesn't need `additional-config-center` config.

`spring.shardingsphere.governance.additional-config-center.type=etcd`
`spring.shardingsphere.governance.additional-config-center.server-lists=localhost:2379`

second,  `spring.shardingsphere.governance.registry-center.server-lists=http://localhost:2379`

`etcd` URL must start with `http://`.

You can try it.

**Comment by YanlongMa** [comment]
Hi @dongzl , I try this config, it can work well. 3Q

But i have a question, use config center , why need remove these config?
```
spring.shardingsphere.governance.additional-config-center.type=etcd
spring.shardingsphere.governance.additional-config-center.server-lists=http://localhost:2379
```
