### ISSUE TITLE
Sharding JDBC4.1.1 integration mybatis3.5.4 localdatetime type cannot be resolved

### ISSUE THREAD

**Issue by 13998475189** [apache/shardingsphere#9187]
When querying sharding JDBC 4.1.1 integration mybatis 3.5.4, there is a time type field of localdatetime in the return value set, and an error is reported.

After research, this error is that mybatis version 3.5.4 calls the GetObject method to process the localdatetime time time lattice, while sharding JDBC version 4.1.1 does not implement the processing of this object. I hope the official will rewrite resultset in version 4.1.1 to solve the bug.

The error is as follows:
error message：java.sql.SQLFeatureNotSupportedException: getObject with type
at org.apache.shardingsphere.shardingjdbc.jdbc.unsupported.AbstractUnsupportedOperationResultSet.getObject(AbstractUnsupportedOperationResultSet.java:221) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_251]

**Comment by JiekerTime** [comment]
Hi~ @13998475189 
Can you give more detailed information? For example, how do you configure JDBC, and what is the specific code logic?

**Comment by RaigorJiang** [comment]
Is the problem still exists?  I'll make a check.

**Comment by RaigorJiang** [comment]
Hello @13998475189 
I tried ShardingJDBC(5.0.0-RC1-SNAPSHOT) with Mybatis(3.5.4), it works well.  Can you try the latest version of ShardingJDBC?  Thank you!

![image](https://user-images.githubusercontent.com/5668787/113876469-5c343980-97ea-11eb-8de5-78c7c2ab86ff.png)

**Comment by terrymanu** [comment]
Closed because of no response anymore.
