### ISSUE TITLE
sharding-proxy 5.0 not can running

### ISSUE THREAD

**Issue by MikelPan** [apache/shardingsphere#9193]
sharding-proxy 5.0.0-alpha is not running ?  

Exception in thread "main" java.lang.NullPointerException
	at org.apache.shardingsphere.infra.metadata.model.physical.model.table.PhysicalTableMetaDataLoader.load(PhysicalTableMetaDataLoader.java:50)
	at org.apache.shardingsphere.sharding.metadata.ShardingMetaDataLoader.load(ShardingMetaDataLoader.java:84)
	at org.apache.shardingsphere.sharding.metadata.ShardingMetaDataLoader.load(ShardingMetaDataLoader.java:67)
	at org.apache.shardingsphere.sharding.metadata.ShardingMetaDataLoader.load(ShardingMetaDataLoader.java:55)
	at org.apache.shardingsphere.infra.metadata.model.logic.LogicSchemaMetaDataLoader.load(LogicSchemaMetaDataLoader.java:72)
	at org.apache.shardingsphere.infra.context.schema.SchemaContextsBuilder.createMetaData(SchemaContextsBuilder.java:108)
	at org.apache.shardingsphere.infra.context.schema.SchemaContextsBuilder.createSchema(SchemaContextsBuilder.java:102)
	at org.apache.shardingsphere.infra.context.schema.SchemaContextsBuilder.build(SchemaContextsBuilder.java:93)
	at org.apache.shardingsphere.proxy.initializer.impl.AbstractBootstrapInitializer.createSchemaContexts(AbstractBootstrapInitializer.java:75)
	at org.apache.shardingsphere.proxy.initializer.impl.AbstractBootstrapInitializer.init(AbstractBootstrapInitializer.java:63)
	at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:48)

**Comment by tristaZero** [comment]
Hi, could you firstly start Proxy with the example yaml configuration? 
It is senseless to say proxy can run but we still need more detail to verify there is a bug or not.

**Comment by terrymanu** [comment]
No response

**Comment by MingxingLAI** [comment]
> Hi, could you firstly start Proxy with the example yaml configuration?
> It is senseless to say proxy can run but we still need more detail to verify there is a bug or not.

I ran into the same problem and there are no more logs。
