### ISSUE TITLE
Proxy with empty configuration restart failed after creating database via RDL when governance enabled

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#9282]
### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT, commit: 2770484c6a0a13d8401eb309d0dac38c373a4c30

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
Started with no exception

### Actual behavior
```
Exception in thread "main" java.lang.NullPointerException
	at org.apache.shardingsphere.proxy.initializer.impl.AbstractBootstrapInitializer.findBackendMySQLDataSource(AbstractBootstrapInitializer.java:114)
	at org.apache.shardingsphere.proxy.initializer.impl.AbstractBootstrapInitializer.setDatabaseServerInfo(AbstractBootstrapInitializer.java:103)
	at org.apache.shardingsphere.proxy.initializer.impl.AbstractBootstrapInitializer.init(AbstractBootstrapInitializer.java:63)
	at org.apache.shardingsphere.test.integration.ProxyBootstrapTest.main(ProxyBootstrapTest.java:47)
```

### Reason analyze (If you can)
Proxy start when remote configuration is incomplete

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1, Enable governance in `server.yaml`
```
governance:
  name: governance_ds
  registryCenter:
    type: ZooKeeper
    serverLists: localhost:2181
    props:
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
  overwrite: false
```

2, Clean configuration, include `config-sharding.yaml` and remote configuration in ZooKeeper governance_ds

3, Client connect to proxy, run `CREATE DATABASE sharding_db;`

4, Restart proxy

**Comment by menghaoranss** [comment]
@sandynz Thanks for your feedback, this issue has been fixed in the master branch.
