### ISSUE TITLE
Database type inconsistent with 'org.apache.shardingsphere.underlying.common.database.type.dialect.MySQLDatabaseType@2d21d12b' and 'org.apache.shardingsphere.underlying.common.database.type.dialect.SQL92DatabaseType@671c71e8'

### ISSUE THREAD

**Issue by bianrenwei** [apache/shardingsphere#9347]
配置多个不同类型的数据源，项目启动报错
Caused by: java.lang.IllegalStateException: Database type inconsistent with 'org.apache.shardingsphere.underlying.common.database.type.dialect.MySQLDatabaseType@2d21d12b' and 'org.apache.shardingsphere.underlying.common.database.type.dialect.SQL92DatabaseType@671c71e8'
	at com.google.common.base.Preconditions.checkState(Preconditions.java:511)
	at org.apache.shardingsphere.shardingjdbc.jdbc.adapter.AbstractDataSourceAdapter.createDatabaseType(AbstractDataSourceAdapter.java:66)
	at org.apache.shardingsphere.shardingjdbc.jdbc.adapter.AbstractDataSourceAdapter.<init>(AbstractDataSourceAdapter.java:53)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.datasource.ShardingDataSource.<init>(ShardingDataSource.java:52)
	at org.apache.shardingsphere.shardingjdbc.api.ShardingDataSourceFactory.createDataSource(ShardingDataSourceFactory.java:48)
	at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration.shardingDataSource(SpringBootConfiguration.java:103)
	at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration$$EnhancerBySpringCGLIB$$27708b99.CGLIB$shardingDataSource$0(<generated>)
	at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration$$EnhancerBySpringCGLIB$$27708b99$$FastClassBySpringCGLIB$$a74c1ded.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration$$EnhancerBySpringCGLIB$$27708b99.shardingDataSource(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 74 common frames omitted

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
