### ISSUE TITLE
 ExpressionProjectionSegment  canot be cast to LiteralExpressionSegment

### ISSUE THREAD

**Issue by eschh19** [apache/shardingsphere#9399]
1、Which version of ShardingSphere did you use?
shardingsphere-jdbc:5.0.0-alpha

2、Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
shardingsphere-jdbc

3、Expected behavior:
excute sql like "INSERT INTO user_info ( id, name, sex, updateTime) VALUES ( ?, ?, ?) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),updateTime=VALUES(updateTime);",
I want the `name` colume encrypted update

4、Actual behavior:
when excute this sql,throw some exceptions like this:
Caused by: java.lang.ClassCastException: org.apache.shardingsphere.sql.parser.sql.common.segment.dml.item.ExpressionProjectionSegment cannot be cast to org.apache.shardingsphere.sql.parser.sql.common.segment.dml.expr.simple.LiteralExpressionSegment
	at org.apache.shardingsphere.infra.binder.segment.insert.values.OnDuplicateUpdateContext.getValue(OnDuplicateUpdateContext.java:87) ~[shardingsphere-infra-binder-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.encrypt.rewrite.parameter.impl.EncryptInsertOnDuplicateKeyUpdateValueParameterRewriter.lambda$rewrite$0(EncryptInsertOnDuplicateKeyUpdateValueParameterRewriter.java:59) ~[shardingsphere-encrypt-rewrite-5.0.0-alpha.jar:5.0.0-alpha]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_73]
	at org.apache.shardingsphere.encrypt.rewrite.parameter.impl.EncryptInsertOnDuplicateKeyUpdateValueParameterRewriter.rewrite(EncryptInsertOnDuplicateKeyUpdateValueParameterRewriter.java:58) ~[shardingsphere-encrypt-rewrite-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.encrypt.rewrite.parameter.impl.EncryptInsertOnDuplicateKeyUpdateValueParameterRewriter.rewrite(EncryptInsertOnDuplicateKeyUpdateValueParameterRewriter.java:40) ~[shardingsphere-encrypt-rewrite-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.encrypt.rewrite.context.EncryptSQLRewriteContextDecorator.decorate(EncryptSQLRewriteContextDecorator.java:42) ~[shardingsphere-encrypt-rewrite-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.encrypt.rewrite.context.EncryptSQLRewriteContextDecorator.decorate(EncryptSQLRewriteContextDecorator.java:34) ~[shardingsphere-encrypt-rewrite-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.infra.rewrite.SQLRewriteEntry.lambda$decorate$0(SQLRewriteEntry.java:83) ~[shardingsphere-infra-rewrite-engine-5.0.0-alpha.jar:5.0.0-alpha]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676) ~[?:1.8.0_73]
	at org.apache.shardingsphere.infra.rewrite.SQLRewriteEntry.decorate(SQLRewriteEntry.java:83) ~[shardingsphere-infra-rewrite-engine-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.infra.rewrite.SQLRewriteEntry.createSQLRewriteContext(SQLRewriteEntry.java:76) ~[shardingsphere-infra-rewrite-engine-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.infra.rewrite.SQLRewriteEntry.rewrite(SQLRewriteEntry.java:69) ~[shardingsphere-infra-rewrite-engine-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.infra.context.kernel.KernelProcessor.generateExecutionContext(KernelProcessor.java:54) ~[shardingsphere-infra-context-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.createExecutionContext(ShardingSpherePreparedStatement.java:266) ~[shardingsphere-jdbc-core-5.0.0-alpha.jar:5.0.0-alpha]
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.execute(ShardingSpherePreparedStatement.java:198) ~[shardingsphere-jdbc-core-5.0.0-alpha.jar:5.0.0-alpha]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_73]
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59) ~[mybatis-3.4.0.jar:3.4.0]
	at com.sun.proxy.$Proxy77.execute(Unknown Source) ~[?:?]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46) ~[mybatis-3.4.0.jar:3.4.0]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74) ~[mybatis-3.4.0.jar:3.4.0]
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50) ~[mybatis-3.4.0.jar:3.4.0]
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117) ~[mybatis-3.4.0.jar:3.4.0]
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76) ~[mybatis-3.4.0.jar:3.4.0]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198) ~[mybatis-3.4.0.jar:3.4.0]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185) ~[mybatis-3.4.0.jar:3.4.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_73]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:434) ~[mybatis-spring-1.3.0.jar:1.3.0]
	... 45 more

5、Reason analyze (If you can):
when excute on line 59 in class EncryptInsertOnDuplicateKeyUpdateValueParameterRewriter and  on line 87 in class OnDuplicateUpdateContext,this exception appeared, valueExpression instance of ExpressionProjectionSegment , canot be cast to 
LiteralExpressionSegment

6、Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc:
the table DDL is:
CREATE TABLE `anchor_info_1` (
  `id` bigint(20) NOT NULL COMMENT '主键id',
  `source` varchar(16) NOT NULL COMMENT '主播来源，yy（yy）；后续扩展',
  `anchorId` varchar(64) NOT NULL COMMENT '主播id',
  `name` varchar(64) NOT NULL DEFAULT '' COMMENT '主播昵称',
  `avatar` varchar(1024) NOT NULL DEFAULT '' COMMENT '主播头像',
  `status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '记录状态，-1-删除，1-有效，默认为1',
  `createTime` bigint(20) NOT NULL COMMENT '创建时间，精确到毫秒',
  `updateTime` bigint(20) NOT NULL DEFAULT '0' COMMENT '最近修改时间，精确到毫秒',
  `lastUpdateTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录最近的修改时间，服务端专用，用来爬取更新的数据',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `idx_source_anchorId` (`source`,`anchorId`) USING BTREE,
  KEY `idx_createTime` (`createTime`) USING BTREE,
  KEY `idx_updateTime` (`updateTime`) USING BTREE,
  KEY `idx_lastUpdateTime` (`lastUpdateTime`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPACT COMMENT='主播信息表';

excute sql is:
    <insert id="insertOrUpdateAnchorInfo" parameterType="com.oppo.cpc.live.common.app.lib.objroom.AnchorInfoModel">
        INSERT INTO anchor_info (id, source, anchorId, name, avatar, status, createTime, updateTime) VALUES 
		(#{id,jdbcType=BIGINT}, #{source,jdbcType=VARCHAR}, #{anchorId,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, 
		#{avatar,jdbcType=VARCHAR},#{status,jdbcType=TINYINT}, #{createTime,jdbcType=BIGINT}, #{updateTime,jdbcType=BIGINT})
        ON DUPLICATE KEY UPDATE <if test="name != null">`name`=VALUES(name),</if>
        updateTime=VALUES(updateTime);
    </insert>
	
7、sharding rule configuration is:
rules:
- !ENCRYPT
  tables:
    anchor_info:
      columns:
        name:
          cipherColumn: name
          encryptorName: aes   
  encryptors:
    aes:
      type: AES
      props:
        aes-key-value: abcdisjckel14003c2f8ea32cc1d59e5

**Comment by eschh19** [comment]
sharding-jdbc cannot support this sql like "ON DUPLICATE KEY UPDATE name=VALUES(name),updateTime=VALUES(updateTime)",
change this sql to "ON DUPLICATE KEY UPDATE name=#{name},updateTime=#{updateTime}" can be successful excuted,i want to know WHY?

**Comment by dongzl** [comment]
Hi @eschh19 , I will check this problem, if I want some other data, please help me, thanks!

**Comment by terrymanu** [comment]
No response anymore
