### ISSUE TITLE
Sharding-Proxy can't start for can't find class org.apache.shardingsphere.orchestration.center.yaml.config.YamlCenterRepositoryConfiguration

### ISSUE THREAD

**Issue by jmbkeyes** [apache/shardingsphere#9404]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

I download the Sharding-Proxy4.1.1,   and modify the config files (config/server.yaml, config-sharding.yaml). But 
exception is thrown while running the sharding proxy, exceptions as below.
**Exception in thread "main" Cannot create property=authentication for JavaBean=org.apache.shardingsphere.shardingproxy.config.yaml.YamlProxyServerConfiguration@52d455b8**
 in 'reader', line 60, column 1:
    authentication:
    ^
Type org.apache.shardingsphere.orchestration.center.yaml.config.YamlCenterRepositoryConfiguration not present
 in 'reader', line 61, column 3:
      users:
      ^

        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:312)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:345)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:410)
        at org.apache.shardingsphere.underlying.common.yaml.engine.YamlEngine.unmarshal(YamlEngine.java:74)
        at org.apache.shardingsphere.underlying.common.yaml.engine.YamlEngine.unmarshal(YamlEngine.java:56)
        at org.apache.shardingsphere.shardingproxy.config.ShardingConfigurationLoader.loadServerConfiguration(ShardingConfigurationLoader.java:72)
        at org.apache.shardingsphere.shardingproxy.config.ShardingConfigurationLoader.load(ShardingConfigurationLoader.java:56)
        at org.apache.shardingsphere.shardingproxy.Bootstrap.main(Bootstrap.java:82)
Caused by: java.lang.TypeNotPresentException: Type org.apache.shardingsphere.orchestration.center.yaml.config.YamlCenterRepositoryConfiguration not present
        at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(Unknown Source)
        at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Unknown Source)
        at sun.reflect.generics.tree.ClassTypeSignature.accept(Unknown Source)
        at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Unknown Source)
        at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Unknown Source)
        at sun.reflect.generics.tree.ClassTypeSignature.accept(Unknown Source)
        at sun.reflect.generics.repository.ConstructorRepository.getParameterTypes(Unknown Source)
        at java.lang.reflect.Executable.getGenericParameterTypes(Unknown Source)
        at java.lang.reflect.Method.getGenericParameterTypes(Unknown Source)
        at java.beans.FeatureDescriptor.getParameterTypes(Unknown Source)
        at java.beans.MethodDescriptor.setMethod(Unknown Source)
        at java.beans.MethodDescriptor.<init>(Unknown Source)
        at java.beans.MethodDescriptor.<init>(Unknown Source)
        at java.beans.Introspector.getTargetMethodInfo(Unknown Source)
        at java.beans.Introspector.getBeanInfo(Unknown Source)
        at java.beans.Introspector.getBeanInfo(Unknown Source)
        at org.yaml.snakeyaml.introspector.PropertyUtils.getPropertiesMap(PropertyUtils.java:63)
        at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:126)
        at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:121)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.getProperty(Constructor.java:322)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:240)
        ... 12 more
Caused by: java.lang.ClassNotFoundException: org.apache.shardingsphere.orchestration.center.yaml.config.YamlCenterRepositoryConfiguration
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        ... 33 more
The two config files as below
![image](https://user-images.githubusercontent.com/12583734/107343745-9cce4a00-6afc-11eb-8d9a-74c1686d5974.png)

![image](https://user-images.githubusercontent.com/12583734/107343758-a22b9480-6afc-11eb-8795-3aafb10d3972.png)

`authentication:
  users:
    root:
      password: root
    sharding:
      password: sharding 
      authorizedSchemas: bocai_checkin
props:
  max.connections.size.per.query: 1
  acceptor.size: 16  # The default value is available processors count * 2.
  executor.size: 16  # Infinite by default.
  proxy.frontend.flush.threshold: 128  # The default value is 128.
    # LOCAL: Proxy will run with LOCAL transaction.
    # XA: Proxy will run with XA transaction.
    # BASE: Proxy will run with B.A.S.E transaction.
  proxy.transaction.type: LOCAL
  proxy.opentracing.enabled: false
  proxy.hint.enabled: false
  query.with.cipher.column: true
  sql.show: true`

**config-sharding.yaml:**
`schemaName: bocai_checkin

# 分库分表的信息 
dataSources:
  bocaicheckin2019:
    url: jdbc:mysql://10.0.0.5:3306/bocai_checkin2019?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: jmbkeyes
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  bocaicheckin2020:
    url: jdbc:mysql://10.0.0.5:3306/bocai_checkin2020?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: jmbkeyes
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    
# 分片规则
shardingRule:
  tables:
    trainee_checkin_checkout:
      actualDataNodes: bocaicheckin${2019..2020}.trainee_checkin_checkout_${1..12}
      tableStrategy:
        inline:
          shardingColumn: month
          algorithmExpression: trainee_checkin_checkout_${month % 100}
  defaultDatabaseStrategy:
    inline:
      shardingColumn: month
      algorithmExpression: bocaicheckin${(month / 100) as int}
  defaultTableStrategy:
    none:`

According to exception detail, it should be some jar files are missing. but I don't know which jars are missing.
Thanks in advance for your help!!!

**Comment by jmbkeyes** [comment]
close it
