### ISSUE TITLE
[SQL Definition Collation][Oracle]Collate the SQL definition of SET ROLE

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#9426]
### Target
- Collate SQL definition of `SET ROLE` to make SQL definition of `Apache ShardingSphere` the same with Oracle's.
- Add a test case

### How

1. Compare `SET ROLE` definition in [Official SQL Doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/SET-ROLE.html#GUID-863F9B6F-82B4-4C49-8E3A-3BA33AE79CAB) and [ShardingSphere SQL Doc](https://github.com/apache/shardingsphere/blob/master/shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/imports/oracle/DCLStatement.g4)
2. If there is any difference in ShardingSphere SQL Doc, please correct them referring to Official SQL Doc (**g4 file of ANTLR**)
3. Run `mvn install shardingsphere-sql-parser-oracle` 
4. Check whether there are any exceptions. If exists, please fix them. (Please pay attention to `xxxVisitor.class`)
5. Add new corresponding SQL case in `shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/main/resources/sql` and expected parsed result in `shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/main/resources/case`
6. Run SQLParserParameterizedTest (`shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/engine/SQLParserParameterizedTest.java`).

### Tips
- Since this issue is a similar one wit #9018 , whose PRs will give you some examples or hints.
- Here is [Contributor guidance](https://shardingsphere.apache.org/community/en/contribute/contributor/).

**Comment by ThanoshanMV** [comment]
Hi @tristaZero, I'll try to do it.

**Comment by tristaZero** [comment]
Yep, this is for COMDEV-399. Yesterday another student emailed me about COMDEV-385. But the recent commits you made convinced me to prefer you to take care of that issue. Therefore I create another one for other candidates.
Suppose you want to try other SQLs, please avoid these SQLs of COMDEV-399. 
Let's wait for others who have interests in COMDEV-399 to have a try.

**Comment by ThanoshanMV** [comment]
Okay tristaZero. When I try other SQLs in future, I'll avoid SQLs of COMDEV-399.

**Comment by Liangda-w** [comment]
Hello @tristaZero, I'm quite interested in COMDEV-399 would like to have a try on this issue:)

**Comment by Liangda-w** [comment]
Hi @tristaZero and @ThanoshanMV, I'm facing the following exception when running `SQLParserParameterizedTest`:

```
java.lang.Exception: Test class should have exactly one public zero-argument constructor

	at org.junit.runners.BlockJUnit4ClassRunner.validateZeroArgConstructor(BlockJUnit4ClassRunner.java:171)
	at org.junit.runners.BlockJUnit4ClassRunner.validateConstructor(BlockJUnit4ClassRunner.java:148)
	at org.junit.runners.BlockJUnit4ClassRunner.collectInitializationErrors(BlockJUnit4ClassRunner.java:127)
	at org.junit.runners.ParentRunner.validate(ParentRunner.java:416)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:84)
	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:65)
	at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:10)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:50)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
```
Below the Run/Debug Configuration. I've also tried to mark the `java` directory as Test Resource Root and the `resource` directory as Test Resources Root, but it still shows the warning that `SQLParserParameterizedTest` isn't a test class. Do you have any ideas how to fix this?

![image](https://user-images.githubusercontent.com/66914151/110216347-f54ff780-7eae-11eb-8b67-35fb608ce7ee.png)

**Comment by tristaZero** [comment]
@Liangda-w ,

Welcome. :)
I saw your PR,  did you fix the issue you mentioned?

**Comment by Liangda-w** [comment]
@tristaZero,

thank you! Yes, I did fix this issue by reinstalling JUnit! :)
