### ISSUE TITLE
When the SQL contains field 'row', Antlr4 will phrase the sql faile.

### ISSUE THREAD

**Issue by VanPersies** [apache/shardingsphere#9546]
shardingsphere-jdbc-core version: 5.0.0-alpha

If the SQL contains field which named 'row', will throw the exception below:

Caused by: org.antlr.v4.runtime.NoViableAltException
	at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:2026)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:467)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:393)
	at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser.select(MySQLStatementParser.java:3594)
	... 143 more

Is there any other keywords will cause this problem?
How could I avoid this probelm?
Why did this problem happen?

Thank you !

**Comment by jingshanglu** [comment]
@VanPersies `ROW` is a keyword in MySQL.

**Comment by jingshanglu** [comment]
@VanPersies You can use \`row\`.

**Comment by VanPersies** [comment]
got it , thank u~
