### ISSUE TITLE
Support object array insertion for PostgreSQL proxy

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#9602]
### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT, commit: a3bd7b60787d3ea104251002f582aabdf876fbc7

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
No exception thrown and data inserted

### Actual behavior
exception caught:
```
java.lang.IllegalArgumentException: Cannot find PostgreSQL type 'POSTGRESQL_TYPE_INT4_ARRAY' in column type when process binary protocol value
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:217)
	at org.apache.shardingsphere.db.protocol.postgresql.packet.command.query.binary.bind.protocol.PostgreSQLBinaryProtocolValueFactory.getBinaryProtocolValue(PostgreSQLBinaryProtocolValueFactory.java:107)
	at org.apache.shardingsphere.db.protocol.postgresql.packet.command.query.binary.bind.PostgreSQLComBindPacket.getParameters(PostgreSQLComBindPacket.java:77)
	at org.apache.shardingsphere.db.protocol.postgresql.packet.command.query.binary.bind.PostgreSQLComBindPacket.<init>(PostgreSQLComBindPacket.java:60)
	at org.apache.shardingsphere.db.protocol.postgresql.packet.command.PostgreSQLCommandPacketFactory.newInstance(PostgreSQLCommandPacketFactory.java:57)
	at org.apache.shardingsphere.proxy.frontend.postgresql.command.PostgreSQLCommandExecuteEngine.getCommandPacket(PostgreSQLCommandExecuteEngine.java:56)
	at org.apache.shardingsphere.proxy.frontend.postgresql.command.PostgreSQLCommandExecuteEngine.getCommandPacket(PostgreSQLCommandExecuteEngine.java:47)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:91)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Reason analyze (If you can)
array protocol is not supported for now

### Example codes for reproduce this issue (such as a github link).
```
                Array array = connection.createArrayOf("integer", new Integer[]{11, 12});
                statement.setArray(2, array);
```

**Comment by sandynz** [comment]
Usage example:

Table schema:
```
CREATE TABLE public.array_tc_0
(
    id bigint NOT NULL,
    aint2 smallint[],
    aint4 integer[],
    aint8 bigint[],
    afloat4 real[],
    afloat8 double precision[],
    abool boolean[],
    avarchar varchar[],
    CONSTRAINT array_test_0_pkey PRIMARY KEY (id)
);

CREATE TABLE public.array_tc_1 ...
```

Java code example:
```
        try (Connection connection = dataSource.getConnection()) {
            String sql = "insert into array_tc (id, aint2, aint4, aint8, afloat4, afloat8, abool, avarchar) values (?, ?, ?, ?, ?, ?, ?, ?)";
            try (PreparedStatement statement = connection.prepareStatement(sql)) {
                int index = 1;
                statement.setLong(index++, id);
                statement.setArray(index++, connection.createArrayOf("smallint", new Short[] {11, 12}));
                statement.setArray(index++, connection.createArrayOf("integer", new Integer[] {11, 12}));
                statement.setArray(index++, connection.createArrayOf("bigint", new Long[] {11L, 12L}));
                statement.setArray(index++, connection.createArrayOf("float4", new Float[] {11.1F, 12.1F}));
                statement.setArray(index++, connection.createArrayOf("float8", new Double[] {11.1D, 12.1D}));
                statement.setArray(index++, connection.createArrayOf("boolean", new Boolean[] {Boolean.TRUE, Boolean.FALSE}));
                statement.setArray(index++, connection.createArrayOf("varchar", new String[] {"\"a", "\\b", "c中文d"}));
                int updateCount = statement.executeUpdate();
                System.out.println("updateCount=" + updateCount);
                // array free
            }
        }
```
