### ISSUE TITLE
update sql error log: No value specified for parameter 1

### ISSUE THREAD

**Issue by dengjin001** [apache/shardingsphere#9621]
sharding 4.1.1+seata 1.4

error  log:
```
2021-03-10 09:24:26.061 [DubboServerHandler-192.168.0.187:20881-thread-198] INFO  ShardingSphere-SQL -Logic SQL: SELECT pg.goods_id, pg.order_num FROM pg_goods pg WHERE (goods_id) in ( (?) )
2021-03-10 09:24:26.061 [DubboServerHandler-192.168.0.187:20881-thread-198] INFO  ShardingSphere-SQL -SQLStatement: SelectStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.SelectStatement@161b03ab, tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@77d897da), tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@77d897da, projectionsContext=ProjectionsContext(startIndex=7, stopIndex=31, distinctRow=false, projections=[ColumnProjection(owner=pg, name=goods_id, alias=Optional.empty), ColumnProjection(owner=pg, name=order_num, alias=Optional.empty)]), groupByContext=org.apache.shardingsphere.sql.parser.binder.segment.select.groupby.GroupByContext@5ec4f821, orderByContext=org.apache.shardingsphere.sql.parser.binder.segment.select.orderby.OrderByContext@5284796, paginationContext=org.apache.shardingsphere.sql.parser.binder.segment.select.pagination.PaginationContext@29d7e268, containsSubquery=false)
2021-03-10 09:24:26.061 [DubboServerHandler-192.168.0.187:20881-thread-198] INFO  ShardingSphere-SQL -Actual SQL: master1 ::: SELECT pg.goods_id, pg.order_num FROM pg_goods pg WHERE (goods_id) in ( (?) ) ::: [1357890737098280960]
2021-03-10 09:24:26.152 [DubboServerHandler-192.168.0.187:20881-thread-198] INFO  ShardingSphere-SQL -Logic SQL: INSERT INTO undo_log (branch_id, xid, context, rollback_info, log_status, log_created, log_modified) VALUES (?, ?, ?, ?, ?, now(6), now(6))
2021-03-10 09:24:26.153 [DubboServerHandler-192.168.0.187:20881-thread-198] INFO  ShardingSphere-SQL -SQLStatement: InsertStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.InsertStatement@7b3a98fd, tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@24adcf40), tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@24adcf40, columnNames=[branch_id, xid, context, rollback_info, log_status, log_created, log_modified], insertValueContexts=[InsertValueContext(parametersCount=5, valueExpressions=[ParameterMarkerExpressionSegment(startIndex=109, stopIndex=109, parameterMarkerIndex=0), ParameterMarkerExpressionSegment(startIndex=112, stopIndex=112, parameterMarkerIndex=1), ParameterMarkerExpressionSegment(startIndex=115, stopIndex=115, parameterMarkerIndex=2), ParameterMarkerExpressionSegment(startIndex=118, stopIndex=118, parameterMarkerIndex=3), ParameterMarkerExpressionSegment(startIndex=121, stopIndex=121, parameterMarkerIndex=4), org.apache.shardingsphere.sql.parser.sql.segment.dml.item.ExpressionProjectionSegment@37aa517a, org.apache.shardingsphere.sql.parser.sql.segment.dml.item.ExpressionProjectionSegment@6eb68fd7], parameters=[112844670371471361, 192.168.0.154:8091:112844667779391488, serializer=jackson, javax.sql.rowset.serial.SerialBlob@ab71af46, 0])], generatedKeyContext=Optional.empty)
2021-03-10 09:24:26.153 [DubboServerHandler-192.168.0.187:20881-thread-198] INFO  ShardingSphere-SQL -Actual SQL: master1 ::: INSERT INTO undo_log (branch_id, xid, context, rollback_info, log_status, log_created, log_modified) VALUES (?, ?, ?, ?, ?, now(6), now(6)) ::: [112844670371471361, 192.168.0.154:8091:112844667779391488, serializer=jackson, javax.sql.rowset.serial.SerialBlob@ab71af46, 0]
2021-03-10 09:24:26.156 [DubboServerHandler-192.168.0.187:20881-thread-197] INFO  ShardingSphere-SQL -Logic SQL: update pg_goods pg
        set pg.order_num = pg.order_num + 1
        where pg.goods_id = ?
2021-03-10 09:24:26.156 [DubboServerHandler-192.168.0.187:20881-thread-197] INFO  ShardingSphere-SQL -SQLStatement: UpdateStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.UpdateStatement@7399f5bb, tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@37f5bf0b), tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@37f5bf0b)
2021-03-10 09:24:26.156 [DubboServerHandler-192.168.0.187:20881-thread-197] INFO  ShardingSphere-SQL -Actual SQL: master1 ::: update pg_goods pg
        set pg.order_num = pg.order_num + 1
        where pg.goods_id = ? ::: [1357890737098280960]
2021-03-10 09:24:26.158 [DubboServerHandler-192.168.0.187:20881-thread-197] INFO  ShardingSphere-SQL -Logic SQL: SELECT pg.goods_id, pg.order_num FROM pg_goods pg WHERE (goods_id) in ( (?) )
2021-03-10 09:24:26.158 [DubboServerHandler-192.168.0.187:20881-thread-197] INFO  ShardingSphere-SQL -SQLStatement: SelectStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.SelectStatement@161b03ab, tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@7d95e65d), tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@7d95e65d, projectionsContext=ProjectionsContext(startIndex=7, stopIndex=31, distinctRow=false, projections=[ColumnProjection(owner=pg, name=goods_id, alias=Optional.empty), ColumnProjection(owner=pg, name=order_num, alias=Optional.empty)]), groupByContext=org.apache.shardingsphere.sql.parser.binder.segment.select.groupby.GroupByContext@df4852d, orderByContext=org.apache.shardingsphere.sql.parser.binder.segment.select.orderby.OrderByContext@1d7b92d5, paginationContext=org.apache.shardingsphere.sql.parser.binder.segment.select.pagination.PaginationContext@76c6b96, containsSubquery=false)
2021-03-10 09:24:26.158 [DubboServerHandler-192.168.0.187:20881-thread-197] INFO  ShardingSphere-SQL -Actual SQL: master1 ::: SELECT pg.goods_id, pg.order_num FROM pg_goods pg WHERE (goods_id) in ( (?) ) ::: [1357890737098280960]
2021-03-10 09:24:26.202 [DubboServerHandler-192.168.0.187:20881-thread-198] DEBUG dao.com.htmj.dao.PgGoodsMapper.reduceGoodsNum -<==    Updates: 1
2021-03-10 09:24:26.212 [DubboServerHandler-192.168.0.187:20881-thread-197] INFO  ShardingSphere-SQL -Logic SQL: SELECT pg.goods_id, pg.order_num FROM pg_goods pg WHERE pg.goods_id = ? FOR UPDATE
2021-03-10 09:24:26.212 [DubboServerHandler-192.168.0.187:20881-thread-197] INFO  ShardingSphere-SQL -SQLStatement: SelectStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.SelectStatement@49baa1cc, tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@3dc12029), tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@3dc12029, projectionsContext=ProjectionsContext(startIndex=7, stopIndex=31, distinctRow=false, projections=[ColumnProjection(owner=pg, name=goods_id, alias=Optional.empty), ColumnProjection(owner=pg, name=order_num, alias=Optional.empty)]), groupByContext=org.apache.shardingsphere.sql.parser.binder.segment.select.groupby.GroupByContext@5915dcdc, orderByContext=org.apache.shardingsphere.sql.parser.binder.segment.select.orderby.OrderByContext@4206cd44, paginationContext=org.apache.shardingsphere.sql.parser.binder.segment.select.pagination.PaginationContext@51ba4aff, containsSubquery=false)
2021-03-10 09:24:26.212 [DubboServerHandler-192.168.0.187:20881-thread-197] INFO  ShardingSphere-SQL -Actual SQL: master1 ::: SELECT pg.goods_id, pg.order_num FROM pg_goods pg WHERE pg.goods_id = ? FOR UPDATE ::: [1357890737098280960]
2021-03-10 09:24:26.212 [DubboServerHandler-192.168.0.187:20881-thread-197] INFO  ShardingSphere-SQL -Logic SQL: update pg_goods pg
        set pg.order_num = pg.order_num + 1
        where pg.goods_id = ?
2021-03-10 09:24:26.212 [DubboServerHandler-192.168.0.187:20881-thread-197] INFO  ShardingSphere-SQL -SQLStatement: UpdateStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.UpdateStatement@7399f5bb, tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@6652b820), tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@6652b820)
2021-03-10 09:24:26.212 [DubboServerHandler-192.168.0.187:20881-thread-197] INFO  ShardingSphere-SQL -Actual SQL: master1 ::: update pg_goods pg
        set pg.order_num = pg.order_num + 1
        where pg.goods_id = ?
2021-03-10 09:24:26.218 [DubboServerHandler-192.168.0.187:20881-thread-197] ERROR i.seata.rm.datasource.exec.AbstractDMLBaseExecutor -execute executeAutoCommitTrue error:No value specified for parameter 1
java.sql.SQLException: No value specified for parameter 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:396)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.apache.shardingsphere.shardingjdbc.executor.SQLExecuteCallbackFactory$2.executeSQL(SQLExecuteCallbackFactory.java:62)
	at org.apache.shardingsphere.shardingjdbc.executor.SQLExecuteCallbackFactory$2.executeSQL(SQLExecuteCallbackFactory.java:58)
	at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteCallback.execute0(SQLExecuteCallback.java:82)
	at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteCallback.execute(SQLExecuteCallback.java:58)
	at org.apache.shardingsphere.underlying.executor.engine.ExecutorEngine.syncExecute(ExecutorEngine.java:97)
	at org.apache.shardingsphere.underlying.executor.engine.ExecutorEngine.parallelExecute(ExecutorEngine.java:93)
	at org.apache.shardingsphere.underlying.executor.engine.ExecutorEngine.execute(ExecutorEngine.java:76)
	at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteTemplate.execute(SQLExecuteTemplate.java:68)
	at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteTemplate.execute(SQLExecuteTemplate.java:51)
	at org.apache.shardingsphere.shardingjdbc.executor.AbstractStatementExecutor.executeCallback(AbstractStatementExecutor.java:129)
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.execute(PreparedStatementExecutor.java:148)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:145)
	at io.seata.rm.datasource.PreparedStatementProxy.lambda$execute$0(PreparedStatementProxy.java:55)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitFalse(AbstractDMLBaseExecutor.java:102)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.lambda$executeAutoCommitTrue$2(AbstractDMLBaseExecutor.java:142)
	at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.doRetryOnLockConflict(ConnectionProxy.java:302)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$LockRetryPolicy.execute(AbstractDMLBaseExecutor.java:186)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:141)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:84)
	at io.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:113)
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:111)
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:50)
	at io.seata.rm.datasource.PreparedStatementProxy.execute(PreparedStatementProxy.java:55)
	at sun.reflect.GeneratedMethodAccessor304.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
	at com.sun.proxy.$Proxy242.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at sun.reflect.GeneratedMethodAccessor343.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy241.update(Unknown Source)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doUpdate(MybatisSimpleExecutor.java:56)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.update(MybatisCachingExecutor.java:85)
	at sun.reflect.GeneratedMethodAccessor330.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:83)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy240.update(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor330.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy240.update(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	at sun.reflect.GeneratedMethodAccessor341.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
	at com.sun.proxy.$Proxy119.update(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:287)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:65)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy133.reduceGoodsNum(Unknown Source)
	at com.htmj.pgImpl.PgGoodsServiceImpl.reduceGoodsNum(PgGoodsServiceImpl.java:92)
	at com.htmj.pgImpl.PgGoodsServiceImpl$$FastClassBySpringCGLIB$$49f14815.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
	at com.htmj.pgImpl.PgGoodsServiceImpl$$EnhancerBySpringCGLIB$$1cf9b706.reduceGoodsNum(<generated>)
	at org.apache.dubbo.common.bytecode.Wrapper7.invokeMethod(Wrapper7.java)
	at org.apache.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:47)
	at org.apache.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:84)
	at org.apache.dubbo.config.invoker.DelegateProviderMetaDataInvoker.invoke(DelegateProviderMetaDataInvoker.java:56)
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)
	at com.alibaba.dubbo.rpc.Invoker$CompatibleInvoker.invoke(Invoker.java:55)
	at io.seata.integration.dubbo.alibaba.AlibabaDubboTransactionPropagationFilter.invoke(AlibabaDubboTransactionPropagationFilter.java:45)
	at com.alibaba.dubbo.rpc.Filter.invoke(Filter.java:29)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at io.seata.integration.dubbo.ApacheDubboTransactionPropagationFilter.invoke(ApacheDubboTransactionPropagationFilter.java:69)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:52)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:89)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:46)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:77)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:129)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:152)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:41)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:145)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:100)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:175)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-03-10 09:24:26.222 [DubboServerHandler-192.168.0.187:20881-thread-197] ERROR org.apache.dubbo.rpc.filter.ExceptionFilter - [DUBBO] Got unchecked and undeclared exception which called by 192.168.0.187. service: com.htmj.api.pg.PgGoodsService, method: reduceGoodsNum, exception: org.springframework.jdbc.BadSqlGrammarException: 

```

**Comment by avalon5666** [comment]
It seems that seata executed incorrect SQL or parameters.

**Comment by dengjin001** [comment]
two methods have add  @GlobalTransactional,  remove one @GlobalTransactional,  seems to be ok,
``` sharding-transaction-base-seata-at ```  4.1.1   seata 1.4.0

**Comment by avalon5666** [comment]
According to the exception stack, please check the seata first.

**Comment by terrymanu** [comment]
Closed because of no feedback
