### ISSUE TITLE
Job stop working for a big table

### ISSUE THREAD

**Issue by cowcomic** [apache/shardingsphere#9799]
### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT
build from git master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
shardingsphere-scaling

### Expected behavior
I want to move data from one Sharding to another Sharding

### Actual behavior
our mysql is RDS from huawei cloud , bin log is open and format is row
a simple table can be synchronized. any data update can be synchronized too

then i start a job for a big table millions of data
long time pass
scaling throw some error in log

```
[ERROR] 2021-03-23 21:45:31.070 [nioEventLoopGroup-4-1] o.a.s.s.mysql.client.MySQLClient - protocol resolution error
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Decode binlog event failed, errorCode: 1236, sqlState: HY000, errorMessage: Could not find first log file name in binary log index file
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Decode binlog event failed, errorCode: 1236, sqlState: HY000, errorMessage: Could not find first log file name in binary log index file
        at org.apache.shardingsphere.scaling.mysql.client.netty.MySQLBinlogEventPacketDecoder.checkError(MySQLBinlogEventPacketDecoder.java:101)
        at org.apache.shardingsphere.scaling.mysql.client.netty.MySQLBinlogEventPacketDecoder.decode(MySQLBinlogEventPacketDecoder.java:57)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
        ... 23 common frames omitted
[INFO ] 2021-03-23 21:45:31.070 [nioEventLoopGroup-4-1] o.a.s.s.mysql.client.MySQLClient - reconnect mysql client.
[WARN ] 2021-03-23 21:45:31.070 [nioEventLoopGroup-4-1] i.n.c.AbstractChannelHandlerContext - An exception 'io.netty.util.concurrent.BlockingOperationException: AbstractChannel$CloseFuture@2e9adae2(incomplete)' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Decode binlog event failed, errorCode: 1236, sqlState: HY000, errorMessage: Could not find first log file name in binary log index file
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Decode binlog event failed, errorCode: 1236, sqlState: HY000, errorMessage: Could not find first log file name in binary log index file
        at org.apache.shardingsphere.scaling.mysql.client.netty.MySQLBinlogEventPacketDecoder.checkError(MySQLBinlogEventPacketDecoder.java:101)
        at org.apache.shardingsphere.scaling.mysql.client.netty.MySQLBinlogEventPacketDecoder.decode(MySQLBinlogEventPacketDecoder.java:57)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
        ... 23 common frames omitted
[WARN ] 2021-03-23 21:45:31.071 [nioEventLoopGroup-4-1] o.a.s.s.mysql.client.MySQLClient - channel inactive
[INFO ] 2021-03-23 21:45:31.071 [nioEventLoopGroup-4-1] o.a.s.s.mysql.client.MySQLClient - reconnect mysql client.
[ERROR] 2021-03-23 21:45:32.976 [nioEventLoopGroup-4-1] o.a.s.s.mysql.client.MySQLClient - protocol resolution error
java.lang.NullPointerException: null
        at org.apache.shardingsphere.scaling.mysql.client.MySQLClient$MySQLBinlogEventHandler.reconnect(MySQLClient.java:262)
        at org.apache.shardingsphere.scaling.mysql.client.MySQLClient$MySQLBinlogEventHandler.channelInactive(MySQLClient.java:249)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:260)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:239)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:386)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:351)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:260)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:239)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:386)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:351)
        at io.netty.handler.codec.ByteToMessageCodec.channelInactive(ByteToMessageCodec.java:118)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:260)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:239)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:260)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
[INFO ] 2021-03-23 21:45:32.976 [nioEventLoopGroup-4-1] o.a.s.s.mysql.client.MySQLClient - reconnect mysql client.
[INFO ] 2021-03-23 22:15:55.317 [ShardingSphere-Scaling-execute-4] com.zaxxer.hikari.HikariDataSource - HikariPool-24 - Shutdown initiated...
[INFO ] 2021-03-23 22:15:55.317 [ShardingSphere-Scaling-execute-4] com.zaxxer.hikari.pool.HikariPool - HikariPool-24 - Close initiated...
[INFO ] 2021-03-23 22:15:55.317 [ShardingSphere-Scaling-execute-4] com.zaxxer.hikari.pool.HikariPool - HikariPool-24 - Closed.
[INFO ] 2021-03-23 22:15:55.317 [ShardingSphere-Scaling-execute-4] com.zaxxer.hikari.HikariDataSource - HikariPool-24 - Shutdown completed.
[INFO ] 2021-03-23 22:15:55.317 [ShardingSphere-Scaling-execute-4] com.zaxxer.hikari.HikariDataSource - HikariPool-21 - Shutdown initiated...
[INFO ] 2021-03-23 22:15:55.317 [ShardingSphere-Scaling-execute-4] com.zaxxer.hikari.pool.HikariPool - HikariPool-21 - Close initiated...
[INFO ] 2021-03-23 22:15:55.318 [ShardingSphere-Scaling-execute-4] com.zaxxer.hikari.pool.HikariPool - HikariPool-21 - Closed.
[INFO ] 2021-03-23 22:15:55.318 [ShardingSphere-Scaling-execute-4] com.zaxxer.hikari.HikariDataSource - HikariPool-21 - Shutdown completed.
[WARN ] 2021-03-24 05:46:13.031 [nioEventLoopGroup-4-1] i.n.c.AbstractChannelHandlerContext - An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NullPointerException: null
        at org.apache.shardingsphere.scaling.mysql.client.MySQLClient$MySQLBinlogEventHandler.reconnect(MySQLClient.java:262)
        at org.apache.shardingsphere.scaling.mysql.client.MySQLClient$MySQLBinlogEventHandler.channelInactive(MySQLClient.java:249)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:260)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:239)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:386)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:351)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:260)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:239)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:386)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:351)
        at io.netty.handler.codec.ByteToMessageCodec.channelInactive(ByteToMessageCodec.java:118)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:260)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:239)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:260)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
[INFO ] 2021-03-24 11:27:14.953 [ShardingSphere-Scaling-execute-6] com.zaxxer.hikari.HikariDataSource - HikariPool-7 - Starting...
[INFO ] 2021-03-24 11:27:15.016 [ShardingSphere-Scaling-execute-6] com.zaxxer.hikari.HikariDataSource - HikariPool-7 - Start completed.
```

at this time, the job is not stop but seems like not synchronizing data
any data update can not be synchronized to target mysql

**Comment by avalon5666** [comment]
Pls check binlog file exists.

**Comment by cowcomic** [comment]
the problem solved
huawei cloud make a binlog manage system themselves
expire_logs_days is not effective now
change the binlog expire time by their system then the problem solved
