### ISSUE TITLE
shardingsphere-proxy 4.x doesn't support sql: SELECT * FROM table WHERE expr IN (VALUE, ...)

### ISSUE THREAD

**Issue by xhkyyy** [apache/shardingsphere#9871]
### Which version of ShardingSphere did you use?

4.x

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

support SQL syntax: `SELECT * FROM table WHERE expr IN (VALUE, ...)`

### Actual behavior

```java
java.sql.SQLException: 2Unknown exception: [org.apache.shardingsphere.sql.parser.sql.segment.dml.item.ExpressionProjectionSegment cannot be cast to org.apache.shardingsphere.sql.parser.sql.segment.dml.column.ColumnSegment]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1074)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4074)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4006)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2468)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2629)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2713)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2663)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1599)
```

**Comment by dongzl** [comment]
Hi @xhkyyy , can you test the newest version, or test it with the `master` code, Thanks.

**Comment by xhkyyy** [comment]
> Hi @xhkyyy , can you test the newest version, or test it with the `master` code? Thanks.

Ok, I'll test the master branch later. 
However, I'm using the latest version of 4.x, and still hoping you'll fix this on the 4.x branch.

**Comment by dongzl** [comment]
> > Hi @xhkyyy , can you test the newest version, or test it with the `master` code? Thanks.
> 
> Ok, I'll test the master branch later.
> However, I'm using the latest version of 4.x, and still hoping you'll fix this on the 4.x branch.

Hi @xhkyyy , the `4.x` version is out of services, we will no plan to upgrade the `4.x` version again.
