### ISSUE TITLE
how can i deal with it ?

### ISSUE THREAD

**Issue by SpriderMan** [apache/shardingsphere#9951]
**version**:   apache-shardingsphere-4.1.0-sharding-scaling-bin
**request**:

curl -X POST \
  http://localhost:8888/shardingscaling/job/start \
  -H 'content-type: application/json' \
  -d '{
   "ruleConfiguration": {
      "sourceDatasource": "ds_0: !!org.apache.shardingsphere.orchestration.core.configuration.YamlDataSourceConfiguration\n  dataSourceClassName: com.zaxxer.hikari.HikariDataSource\n  properties:\n    jdbcUrl: jdbc:mysql://127.0.0.1:3308/scaling?serverTimezone=UTC&useSSL=false\n    username: sharding_slave\n    password: '\''123456'\''\n    connectionTimeout: 30000\n    idleTimeout: 60000\n    maxLifetime: 1800000\n    maxPoolSize: 50\n    minPoolSize: 1\n    maintenanceIntervalMilliseconds: 30000\n    readOnly: false\n",
      "sourceRule": "tables:\n  t_order:\n    actualDataNodes: ds_0.t_order\n    keyGenerator:\n      column: order_id\n      type: SNOWFLAKE",
      "destinationDataSources": {
         "name": "dt_0",
         "password": "123456",
         "url": "jdbc:mysql://127.0.0.1:3307/sharding_db?serverTimezone=UTC&useSSL=false",
         "username": "root"
      }
   },
   "jobConfiguration": {
      "concurrency": 1
   }
}'

**error**:
[nioEventLoopGroup-3-2] o.a.s.s.web.HttpServerHandler - Datasources check failed!
org.apache.shardingsphere.shardingscaling.core.exception.DatasourceCheckFailedException: Datasources check failed!
	at org.apache.shardingsphere.shardingscaling.core.execute.executor.checker.AbstractDataSourceChecker.checkConnection(AbstractDataSourceChecker.java:38)
	at org.apache.shardingsphere.shardingscaling.web.HttpServerHandler.checkDatasources(HttpServerHandler.java:116)
	at org.apache.shardingsphere.shardingscaling.web.HttpServerHandler.startJob(HttpServerHandler.java:101)
	at org.apache.shardingsphere.shardingscaling.web.HttpServerHandler.channelRead0(HttpServerHandler.java:76)
	at org.apache.shardingsphere.shardingscaling.web.HttpServerHandler.channelRead0(HttpServerHandler.java:56)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)

**Comment by tristaZero** [comment]
Hi @Lucas-307  Here.

**Comment by Lucas-307** [comment]
Datasource Check:
1. checkPrivilege
  - ALL PRIVILEGES
  or 
  - REPLICATION SLAVE + REPLICATION CLIENT
2. checkVariable
  - LOG_BIN = ON
  - BINLOG_FORMAT = ROW
  - BINLOG_ROW_IMAGE = FULL

@SpriderMan Please make sure privilege and variable is valid.

**Comment by SpriderMan** [comment]
> Datasource Check:
> 
> 1. checkPrivilege (sql: `SHOW GRANTS`)
> 
> * ALL PRIVILEGES
>   or
> * REPLICATION SLAVE + REPLICATION CLIENT
> 
> 1. checkVariable (sql: `SHOW VARIABLES`)
> 
> * LOG_BIN = ON
> * BINLOG_FORMAT = ROW
> * BINLOG_ROW_IMAGE = FULL
> 
> @SpriderMan Please make sure privilege and variable is valid.

![image](https://user-images.githubusercontent.com/18304842/114487259-db3dcd80-9c41-11eb-8176-c478620bd373.png)

GRANT ALL PRIVILEGES ON *.* TO 'sharding_slave'@'%' WITH GRANT OPTION

**Comment by SpriderMan** [comment]
> Datasource Check:
> 
> 1. checkPrivilege (sql: `SHOW GRANTS`)
> 
> * ALL PRIVILEGES
>   or
> * REPLICATION SLAVE + REPLICATION CLIENT
> 
> 1. checkVariable (sql: `SHOW VARIABLES`)
> 
> * LOG_BIN = ON
> * BINLOG_FORMAT = ROW
> * BINLOG_ROW_IMAGE = FULL
> 
> @SpriderMan Please make sure privilege and variable is valid.


but it also gets wrong like that

**Comment by sandynz** [comment]
Hi @SpriderMan , thanks for your feedback. We'll output detailed logs for better troubleshooting.
