### ISSUE TITLE
Under the environment of Ubuntu + eclipse, the path of project directory contains Chinese, which leads to the error that shardingsphere proxy cannot read the configuration file

### ISSUE THREAD

**Issue by wl4g** [apache/shardingsphere#9957]
Description: Under the environment of Ubuntu + eclipse, the path of project directory contains Chinese, which leads to the error that shardingsphere proxy cannot read the configuration file

Version: shardingsphere:5.0.0-alpha

Environment: Ubuntu:20 + Eclipse Oxygen.3a Release (4.7.3a)

Errors Stacktrace:

Exception in thread "main" java.io.FileNotFoundException: /home/xxx/%e6%96%87%e6%a1%a3/java-workspace/shardingsphere/shardingsphere-proxy/shardingsphere-proxy-bootstrap/target/classes/conf/server.yaml (没有那个文件或目录)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.apache.shardingsphere.infra.yaml.engine.YamlEngine.unmarshal(YamlEngine.java:55)
	at org.apache.shardingsphere.proxy.config.ProxyConfigurationLoader.loadServerConfiguration(ProxyConfigurationLoader.java:77)
	at org.apache.shardingsphere.proxy.config.ProxyConfigurationLoader.load(ProxyConfigurationLoader.java:60)
	at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:47)

**Comment by terrymanu** [comment]
Does anyone interest this issue?
